### ISSUE TITLE
Maven depends with old Jersey 1.x client

### ISSUE THREAD

**Issue by tcederquist** [Microsoft/mssql-jdbc#100]
Trying to include MSSql support for our toolset. However, compiling into a modern Jersey 2.x project for Java 1.8 has conflicts with this driver since mssql-jdbc includes a dependency to Jersey client 1.x which isn't compatible and causes missing Map class errors due to the dual inclusion of both versions of the libs. Can this be updated or removed for the 6.1.0-JRE8 version?

This comes from this dependency chain:
azure-keyvault -> azure-core -> jersey-client v1.19    <<--- this is a 2 year old library...

**Comment by JamieMagee** [comment]
I believe that this dependency is going away with the next major release of the Azure SDK for Java. You can follow development here: https://github.com/Azure/azure-sdk-for-java

**Comment by v-xiangs** [comment]
hello @tcederquist thanks for filling the issue. as what @JamieMagee said, the next release of azure-keyvault will not depend on azure-core, therefore it will not depend on jersey-client v1.19.

For now, if you do not use Azure Key Vault feature, I guess you can exclude the com.sun.jersey dependency from mssql-jdbc.

something like this:
```
<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>mssql-jdbc</artifactId>
    <version>6.1.0.jre8</version>
    <exclusions>
        <exclusion>
            <groupId>com.sun.jersey</groupId>
            <artifactId>jersey-client</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by tcederquist** [comment]
Great feedback, didn't know about the maven exclusion technique - that'll solve my problem until the next release. Great workaround and good to know the dependency won't be there in the future. Well done.
