### ISSUE TITLE
Handle sql_variant types as null (skip over them)

### ISSUE THREAD

**Issue by sehrope** [Microsoft/mssql-jdbc#101]
Currently if a ResultSet includes a sql_variant type then the driver will throw an exception during the column metadata parse phase of the response. This is because the driver does not yet handle sql_variant column types (presumably because sql_variant is complicated and parsing it would require handling many different types). Unfortunately this means that any SQL command that returns a sql_variant cannot be executed even if that particular column will not be processed.

Until it's fully supported one of the two following options would be nice:

1. A connection option to interpret sql_variant columns as null. If set, then calling any getXYZ(...) method on a sql_variant column would always return null.
2. Skipping over sql_variant columns in ResultSets as long as the getXYZ(...) methods are not invoked on them. The current "*sql_variant is not supported...*" exception could be thrown if one of those methods is invoked. The difference between this and the current driver would be that a user program could look at the ResultSetMetaData to determine which columns need to be skipped over (right now you can't do that as the metadata parsing phase throws the exception).

**Comment by v-afrafi** [comment]
Hi @sehrope. Just to let you know that we are in progress of supporting sql_variant type and we have a [branch](https://github.com/Microsoft/mssql-jdbc/tree/SqlVariant) in which we are pushing our development. Once completed and tested fully, it will be merged. Thank you for opening this issue and stay tuned for the updates!
