### ISSUE TITLE
[BUG] DatabaseMetaData.getColumns(...) IS_GENERATEDCOLUMN value icorrect

### ISSUE THREAD

**Issue by george-walker** [microsoft/mssql-jdbc#1013]
## Driver version
7.2.1.jre8

## SQL Server version
Azure SQL

## Client Operating System
Ubuntu 18.04

## JAVA/JVM version
openjdk full version "1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12"

## Table schema
```
CREATE TABLE product_list (
  id int auto_increment primary key,
  name NVARCHAR(100) NOT NULL,
  category NVARCHAR(50),
  business_unit NVARCHAR(50),
  quantity INTEGER,
  price FLOAT,
  realname NVARCHAR AS concat( business_unit, ':', name )
)
```

## Problem description
1. Expected behaviour:

https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#getColumns(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String)

The column IS_GENERATEDCOLUMN should return "YES" or "NO" as per JDBC

In the DDL above the column *realname* is a computed column

2. Actual behaviour:

The column IS_GENERATEDCOLUMN return "1" or "0"

3. Error message/stack trace:
4. Any other details that can be helpful:

**Comment by peterbae** [comment]
Hi @george-walker, thanks for contacting us about the issue. We've confirmed this issue, and will come up with a PR addressing this problem soon.

**Comment by rene-ye** [comment]
Hi @george-walker, #1016 has been merged. Closing the issue.
