### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Wichart009** [Microsoft/mssql-jdbc#1022]
I use MS JDBC Driver 7.2.1 with SquirrelSQL Client 3.9.1 connect to SQL Server Express 2017 and got an error as in attachment. This belongs to JDBC/SquirrelSQL, and how to solve it.
![SQLServerJDBC-SquirrelSQL](https://user-images.githubusercontent.com/12468949/55668591-3d66d980-5896-11e9-9bec-06fd21e998ea.jpg)

**Comment by cheenamalhotra** [comment]
Hi @Wichart009 

As you can see in the logs, this error is thrown by SquirrelSQL Client, and not JDBC Driver. You need to contact SquirrelSQL Client Support team for this issue.

On the contrary, please make sure the mssql jdbc driver was loaded properly and the Squirrel SQL Client application was restarted.

**Comment by Wichart009** [comment]
Thanks a lot. I'm sure that the MSSQL JDBC was loaded & set properly, due to another Database font end such as dBeaver is working.
![MSSQL-JDBC-dBeaver](https://user-images.githubusercontent.com/12468949/55698750-9b5c0400-59f1-11e9-92f7-36404858a9c1.jpg)
