### ISSUE TITLE
Connection failed for named instance

### ISSUE THREAD

**Issue by 23will** [Microsoft/mssql-jdbc#1026]
I'm seeing connection failed when using instanceName in connection string, i.e. `jdbc:sqlserver://server;databaseName=testdb;instanceName=testinstance`.

```
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host testdb, port 1433 has failed. Error: "Connection refused (Connection refused). Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
```

This is fixed by adding the instance's dynamic port to the connection string (since it's clearly checking the default port). According to the [documentation](https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-2017), either the port number or the the instance name has to be specified to connect to a named instance so I'm assuming this is a bug or there is no point in having the `instanceName` parameter.

**Comment by peterbae** [comment]
Hi @23will, thanks for contacting us. Our driver supports the lookup of the dynamic port based on the server name and the instance name, even if the user doesn't provide the port number. I think this might be a firewall or environment issue - could you follow the recommendations from [this](https://social.technet.microsoft.com/Forums/en-US/b076b534-217a-4baf-ae28-98def4de6879/unable-to-connect-to-named-instance-in-sql-server-2017?forum=sqlkjmanageability) page, and if the problem persists, share more about your environment + connection string?

**Comment by 23will** [comment]
Thank you for the quick reply, it turns out that the fault was on our end as we were passing the default port `1433` instead of port `0`which (obviously) disables the dynamic port lookup. For posterity, the driver looks at port 1434 (SQL Server Browser service) for the dynamic port lookup by name instance. Thanks again.
