### ISSUE TITLE
[FEATURE REQUEST] add getters for SQLServerSpatialDatatype members

### ISSUE THREAD

**Issue by vforchi** [microsoft/mssql-jdbc#1038]
## Is your feature request related to a problem? If so, please give a short summary of the problem and how the feature would resolve it
I am working on a project where I need to translate a `Geography` object into another spatial class, that implements a standard other than WKT/WKB

## Describe the preferred solution
I would like to be able to access the members of `SQLServerSpatialDatatype` that describe the spatial region, i.e. `pointList`, `figureList` and so on.

## Describe alternatives you've considered
Another option would be to change the visibility of the constructors of `Geography` from `private` to `protected`, so that I would be able to inherit from Geography and access the members from there, since they are protected.

**Comment by peterbae** [comment]
Hi @vforchi, I've addressed this issue in PR 1035 (the same PR for the last related issue). I've declared the default constructor as protected so that Geometry/Geography can be extended.

**Comment by vforchi** [comment]
I think it would be useful to also have the other constructors protected, otherwise I will just end up copying that code in one of my constructors.

**Comment by peterbae** [comment]
STGeomFromText and STGeomFromWKB methods give you access to the constructor (it's basically the same as calling the constructors themselves, except we do it in SQL Server fashion). Do you still need to copy the contents of the private constructors?

**Comment by vforchi** [comment]
Yes, but those methods would create a Geography, and not my class.

**Comment by peterbae** [comment]
Ok, I made them protected as well. Unless there's anything else you need added, after internal reviews I'll merge in the PR.

**Comment by vforchi** [comment]
Thanks, I think that's all I need.

**Comment by peterbae** [comment]
Fixed in PR #1035. Closing issue.
