### ISSUE TITLE
Option to set ssl protocol to "off"

### ISSUE THREAD

**Issue by rafiek** [microsoft/mssql-jdbc#1056]
## Question
Hello,

I'm in a scenario where there is no need for a SSL connection (development/test environment). However, the SQLServer has configured a certificate that uses an algorithm that is not supported by Java8. It uses OID 1.2.840.113549.1.1.10, which is rsassa-pss. The server is also configured that non-secure connections are allowed. But because there is a certificate the driver tries to setup a secured connection and fails.

Could you please add an option to set ssl protocol "none" or "off".

**Comment by rene-ye** [comment]
Hi @rafiek, the driver will not force a secure connection unless the encrypt property is turned on. This can be done either through the connection string via `encrypt=true` or through `SQLServerDataSource` via `datasource.setEncryption(true)`.

Other scenarios which will cause encryption to be turned on is if the user sets the `authentication` property, or if **Force Encryption** is turned on server side. Can you please share the connection string being used if none of the above works for you.

**Comment by rene-ye** [comment]
Closing the issue for now. Please feel free to re-open if you have any more questions.

**Comment by rafiek** [comment]
Hi @rene-ye, I use DataGrip as my database management tool with the following settings `encrypt=false` and `authentication=NotSpecified`. Server side the "force encryption" is not turned on.

This is my connection string:
`jdbc:sqlserver://default-listener.mydomain.com:1433;database=mydatabase`

**Comment by rene-ye** [comment]
Hi @rafiek, please provide all information you can regarding the issue, and a stand-alone reproduction if possible. Some details the team needs to know are below:

- SQL Server details (I see you have a listener configured, please explain if the server in question is a cluster or another special configuration and how to set it up)
- How you're creating this SSL certificate, and how you're installing/using this certificate
- Whether this is reproducible on any SQL Server or only in your setup. (Create a clean SQL Server and generate a SSL certificate. Attempt to establish a non-SSL connection to that server)
- Whether this is reproducible in a clean environment. (Create a basic application that only attempts to establish a SSL connection to a clean SQL Server)

**Comment by rene-ye** [comment]
Hi @rafiek, is there an update to this issue? The team is unable to replicate this scenario on our end.

**Comment by rafiek** [comment]
Hi @rene-ye, my DB admins have Microsoft employees on site to investigate this. As a workaround a self-signed certificate has been created for my connection. This works.

I was told that the certificate I received before was for use by sqlserver to authenticate against AD. It is very strange that I received this certificate.

**Comment by rene-ye** [comment]
Hi @rafiek, thanks for the update. I'll close this issue for now, but feel free to open it again or create a new thread if problems persist.
