### ISSUE TITLE
Add Replication property to mssql-jdbc driver

### ISSUE THREAD

**Issue by dougmei** [microsoft/mssql-jdbc#1058]
This is a feature request to add the "Replication" boolean property to the SQL Server connection in the mssql-jdbc driver so that it can be configured by setting the property in the url and/or in the connection properties, something like this:

db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.url=jdbc:sqlserver://localhost:59706;databaseName=symchuck;**replication=true**
db.connection.properties=**replication=true**;

This property is available through the SQLConnectionSringBuilder in ADO.Net and it would be nice to have it available in jdbc as well.

**Comment by rene-ye** [comment]
Hi @dougmei, the team will have a look to see what can be done.
