### ISSUE TITLE
[BUG] Variant type not supported in MSSQL-SERVER Version 7.0.0.jre8

### ISSUE THREAD

**Issue by duffymo** [microsoft/mssql-jdbc#1089]
## Table schema

Tried to run SQL query to generate data dictionary from https://dataedo.com/blog/useful-sql-server-data-dictionary-queries-every-dba-should-have:

select schema_name(tab.schema_id) as schema_name,
       tab.name as table_name,
       tab.create_date as created,
       tab.modify_date as last_modified,
       p.rows as num_rows,
       ep.value as comments
from sys.tables tab
       inner join (select distinct
                                   p.object_id,
                                   sum(p.rows) rows
                   from sys.tables t
                          inner join sys.partitions p
                            on p.object_id = t.object_id
                   group by p.object_id,
                            p.index_id) p
         on p.object_id = tab.object_id
       left join sys.extended_properties ep
         on tab.object_id = ep.major_id
              and ep.name = 'MS_Description'
              and ep.minor_id = 0
              and ep.class_desc = 'OBJECT_OR_COLUMN'
order by schema_name,
         table_name

Ran the query in IntelliJ Ultimate 2018.2 Data Grip module.

## Problem description

1. Expected behaviour:  Get data dictionary 
2. Actual behaviour: Got error message in the console.

3. Error message/stack trace:
[2019-06-14 15:04:33] [08S01] The "variant" data type is not supported.

4. Any other details that can be helpful:

**Comment by gordthompson** [comment]
This issue needs a title.

**Comment by gordthompson** [comment]
I am unable to reproduce the issue using mssql-jdbc-7.3.1.jre8-preview.jar and vanilla JDBC. This code ...

```java
String sql = 
          "select schema_name(tab.schema_id) as schema_name, "
        + "tab.name as table_name, "
        + "tab.create_date as created, "
        + "tab.modify_date as last_modified, "
        + "p.rows as num_rows, "
        + "ep.value as comments "
        + "from sys.tables tab "
        + "inner join (select distinct "
        + "p.object_id, "
        + "sum(p.rows) rows "
        + "from sys.tables t "
        + "inner join sys.partitions p "
        + "on p.object_id = t.object_id "
        + "group by p.object_id, "
        + "p.index_id) p "
        + "on p.object_id = tab.object_id "
        + "left join sys.extended_properties ep "
        + "on tab.object_id = ep.major_id "
        + "and ep.name = 'MS_Description' "
        + "and ep.minor_id = 0 "
        + "and ep.class_desc = 'OBJECT_OR_COLUMN' "
        + "order by schema_name, "
        + "table_name ";
ResultSet rs = st.executeQuery(sql);
ResultSetMetaData rsmd = rs.getMetaData();
for (int i = 1; i <= rsmd.getColumnCount(); i++) {
    System.out.printf("[%s] is type \"%s\"%n", 
            rsmd.getColumnLabel(i), rsmd.getColumnTypeName(i));
}
```

... produces ...

```
[schema_name] is type "nvarchar"
[table_name] is type "nvarchar"
[created] is type "datetime"
[last_modified] is type "datetime"
[num_rows] is type "bigint"
[comments] is type "sql_variant"
```

If DataGrip is choking on the `sql_variant` column then perhaps try `CAST(ep.value AS nvarchar(max)) as comments`.

**Comment by rene-ye** [comment]
Hi @duffymo, I'm able to execute the above query with the latest version of DataGrip, and can confirm that the query works properly with vanilla JDBC. This doesn't seem like a driver issue.

**Comment by duffymo** [comment]
Thank you for the help.  I was able to make this run perfectly by adding CAST appropriately.
