### ISSUE TITLE
[QUESTION] Customizing SQLServerDriver APIs

### ISSUE THREAD

**Issue by CheapLaoo** [microsoft/mssql-jdbc#1090]
## Question

I want to extend the class SQLServerDriver to override the acceptsURL Method however i found this class is a final class. Can i modify the source code  to remove the final .

**Comment by gordthompson** [comment]
This issue needs a more descriptive title.

**Comment by lilgreenbird** [comment]
Hi @CheapLaoo,

The SQLServerDriver class represents the MS JDBC Driver for SQL Server the acceptsURL method parses the connection URL into properties that is needed by the driver. Can you please tell us why you need to override the method? You are welcome to create a PR if you find any issue with the driver we will definitely review and consider adding that to the driver.

**Comment by CheapLaoo** [comment]
Hi @lilgreenbird 

Thanks for answering, I need to register different versions of the drivers so i override connect and acceptsURL method like below
` @Override
    public Connection connect(String s, Properties properties) throws SQLException {
        return !this.acceptsURL(s) ? null : super.connect(this.realUrl(s), properties);
    }
    @Override
    public boolean acceptsURL(String s) {
        try {
            return s.startsWith("jdbc:mysql"+Version+":") ? super.acceptsURL(this.realUrl(s)) : false;
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return  false;

final String realUrl(String s) {
        return s.substring(0, 10) + s.substring(12);
    }`

**Comment by rene-ye** [comment]
Hi @CheapLaoo, this seems like a very specific use case and wouldn't be something merged into the main repo. You're free to clone the repo and change the source code to your needs. However, the team won't be able to assist with any issues that occur in custom drivers.

**Comment by rene-ye** [comment]
Please feel free to re-open or create a new issue if further assistance is required.
