### ISSUE TITLE
[QUESTION] What would be the default value of XADefaultTimeout and XAMaxTimeout?

### ISSUE THREAD

**Issue by njbcyu** [microsoft/mssql-jdbc#1093]
## Question

Hello!

Currently I am using SQL Server 2012 and mssql-jdbc-driver-7.2.2.jar.

I read the documentation and know that if I call setTransactionTimeout(0),the TransactionTimeout here would be set to default timeout value, but I am not sure what the number is. Is it just infinite, or is it a value like 100,000 or something?

The documentation says, with SQL Server 2017, I can check their values under the following registry key:

"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL<version>.<instance_name>\XATimeout"

However, I am using the SQL Server 2012, and cannot find these two values there(maybe for 2012 they would not be created). Therefore, I am not able to determine what's the default value of these two variables. Could you please check it?

Thank you for your help!

Pomelo

**Comment by lilgreenbird** [comment]
hi @njbcyu,

The default timeout can be set with the `XADefaultTimeout` registry setting which has a default value of 0. For a better description of this please see [Configuring server-side timeout settings for automatic rollback of unprepared transactions(https://docs.microsoft.com/en-us/sql/connect/jdbc/understanding-xa-transactions?view=sql-server-2017#BKMK_ServerSide)

**Comment by njbcyu** [comment]
> hi @njbcyu,
> 
> The timeout settings are controlled by the `XADefaultTimeout` and `XAMaxTimeout` registry settings which should be created under the `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\MSSQL<version>.<instance_name>\XATimeout ` key as you mentioned.
> 
> The default timeout can be set with the `XADefaultTimeout` registry setting which has a default value of 0 meaning "no maximum value for timeout is enforced".
> 
> You can find more descriptions of this and examples of how these timeout values are interpreted in [Configuring server-side timeout settings for automatic rollback of unprepared transactions](https://docs.microsoft.com/en-us/sql/connect/jdbc/understanding-xa-transactions?view=sql-server-2017#BKMK_ServerSide)

Hello @lilgreenbird ,

Thanks for the reply.

With the SQL Server 2012 that I am currently using, I can't find these two registries under the given path. I am wondering under what condition would it be automatically created? I've read the documentation, but now these two are not present, and I want to set my default transaction timeout value to infinite. Can I directly create them and assign value 0 to them?

Thanks!

**Comment by cheenamalhotra** [comment]
Hi @njbcyu 

Yes these registry entries need to be created, if absent. The above link posted by @lilgreenbird discusses the exact location for creating them.

**Comment by rene-ye** [comment]
Please feel free to re-open or create a new issue if further assistance is required.
