### ISSUE TITLE
Does setMaxRows on statement affect the row count in insert statement?

### ISSUE THREAD

**Issue by Pryanic** [microsoft/mssql-jdbc#1107]
I use SQL SERVER 2019.
JDBC driver 7.2.0.jre8
I want to insert large number of rows(1000) as one query
```
Insert into table()
     values(
            row1,
           row2,
           ....,
           row1000)
```
And also I set the setMaxRows(10) on statement and statement insert just 10 rows. Is it okay?
The Redshift  doesn't do it.
I found that you in your driver execute SET ROWCOUNT and it's affect the result. Is it true?

**Comment by rene-ye** [comment]
Hi @Pryanic,

As per the JDBC API:
>Sets the limit for the maximum number of rows that any ResultSet object generated by this Statement object can contain to the given number. **If the limit is exceeded, the excess rows are silently dropped.**

The driver is using the proper API to restrict this, although I can see that JDBC specs specifically mention ResultSet and not all results. [The official Microsoft Docs page](https://docs.microsoft.com/sql/t-sql/statements/set-rowcount-transact-sql?view=sql-server-2017) seems to include a note regarding this bahavior: 
> Important
>Using SET ROWCOUNT will not affect DELETE, INSERT, and UPDATE statements in a future release of SQL Server. Avoid using SET ROWCOUNT with DELETE, INSERT, and UPDATE statements in new development work, and plan to modify applications that currently use it. For a similar behavior, use the TOP syntax. For more information, see TOP (Transact-SQL).

So it seems that this behavior of affecting INSERT wasn't intended. Unfortunately there's nothing we can do from the driver side as of now.

**Comment by Pryanic** [comment]
Do you have work around for this ?

**Comment by rene-ye** [comment]
It would depend on your use case, what are you trying to do with setMaxRow?

**Comment by Pryanic** [comment]
I want to set permanently maxRow and execute all my queries(INSERT, UPDATE,DELETE) via this statements. I don't want to add LIMIT in all select queries and add additional complex logic for deciding use rowLimit or not

**Comment by rene-ye** [comment]
I think in this scenario, you'd want a separate connection for SELECTS with maxRow and INSERT/UPDATE/DELETE. Or you'd have to detect when a select statement is going to be executed and toggle setMaxRows On/Off.
