### ISSUE TITLE
[QUESTION] Result set return the error from other result set

### ISSUE THREAD

**Issue by Pryanic** [microsoft/mssql-jdbc#1109]
I have the following table with only one columns and one row
`TABLE_1(COLUMN_1 int)`. The value in the row is 1;
I create the following stored procedure 
```
create or alter procedure new_procedure as 
begin 
select * from TABLE_1; 
select * from TABLE_1_ERROR; 
end ;
```
In my expectation I'll get one result set with data and other result set with error, but unfortunately I don't get it. 

My code just get result set from statement one by one, and read the result set in the following style:
```
while(rs.next()){

}
```
I don't understand why I get error in first result set
As I understand the stmt return just 1 resultSet

**Comment by rene-ye** [comment]
Similar behavior has #1110, please process all responses from the server. My output (TABLE_1 has a single row inside):
![image](https://user-images.githubusercontent.com/6042742/61396319-4fd0b600-a87c-11e9-8528-e1bf9e159e19.png)

**Comment by Pryanic** [comment]
You are right. Thank you.

**Comment by Pryanic** [comment]
But you get the error and result in one result set. I think that you should get two result sets;

**Comment by rene-ye** [comment]
I don't get the error in 1 result set. I get the error immediately after calling `resultsAvailable = s.getMoreResults();`, which is the second ResultSet. You can test this by only executing the procedure and doing nothing else. Executing the query will cause the driver to read the first result, and because it's not an error the driver won't throw. If we flip the error call in your stored procedure and did the same thing, the driver will throw.

**Comment by Pryanic** [comment]
I'll check it. Thank you.

**Comment by Pryanic** [comment]
I modified your code 
```

    public static void main(String[] args) throws SQLException, ClassNotFoundException {

        try (Connection con = DriverManager
            .getConnection(URL);
             Statement s = con.createStatement()) {
            boolean resultsAvailable = s.execute("EXEC new_procedure");
            int updateCount = -2;
            while (true) {
                updateCount = s.getUpdateCount();
                if (!resultsAvailable && updateCount == -1) {
                    break;
                }
                if (resultsAvailable) {
                    handleResultSet(s);
                } else {
                    System.out.println("Number of rows affected: " + updateCount);
                }
                System.out.println("FINISH");
                resultsAvailable = s.getMoreResults();
            }
        }
    }

    public static void handleResultSet(Statement s) throws SQLException {
        try (ResultSet rs = s.getResultSet())
        {
            System.out.println("RESULT SET");
            while (rs.next()) {
                System.out.println(rs.getString(1));
            }
        }
    }
```
And got the following result
![image](https://user-images.githubusercontent.com/13783593/61519018-8e4ca900-aa13-11e9-8d33-05c91c09aba7.png)


As you see I get the error in the first result set. The line `Finish` didn't appear. The s.getMoreResults(); wasn't executed. I use driver version 7.2.2.jre8

**Comment by rene-ye** [comment]
![image](https://user-images.githubusercontent.com/6042742/61547380-1de85c80-aa00-11e9-8c37-e8ab36de1440.png)

Are you sure you're testing with the same stored procedure and table as you mentioned in the issue? My output doesn't have a "2" and I do get the FINISH.

**Comment by Pryanic** [comment]
My table have 2 records(the number of records isn't important here) I'll check it in two ours

**Comment by Pryanic** [comment]
I can't find the changes between our codes

**Comment by rene-ye** [comment]
It's probably the stored procedure? Maybe create a new database and re-setup the environment.

**Comment by Pryanic** [comment]
```create or alter procedure new_procedure as 
begin 
select * from TABLE_1; 
select * from TABLE_1_ERROR; 
end ;
```
Is stored procedure

**Comment by Pryanic** [comment]
The same result on new DB with one table , one row, one stored procedure

**Comment by Pryanic** [comment]
And I use java 8 you use java 12. Did you check it on java 8

**Comment by rene-ye** [comment]
![image](https://user-images.githubusercontent.com/6042742/61550633-d4037480-aa07-11e9-8a0b-7e4388f6bb2b.png)
Changing JDK doesn't seem to do anything. Can you post your SQL Server version, and try the dev branch in github. I've attached compiled jre8 jars in case.

[7.4.0-SNAPSHOT.zip](https://github.com/microsoft/mssql-jdbc/files/3411927/7.4.0-SNAPSHOT.zip)

**Comment by Pryanic** [comment]
The jdbc metadata says me that my version of server `Version: 15.00.1600`
As I know it's a SQL SERVER 2019. Sorry but I didn't get your point about dev branch. I check your snapshot

**Comment by rene-ye** [comment]
Dev branch is just the most recent version of the driver, those jars I provided are just the compiled JRE8 version of the dev branch. If you can use those it's fine. SQL Server version seems fine too, I'm on 2019 15.0.1300.359.

**Comment by Pryanic** [comment]
I'll give you answer in few minutes

**Comment by Pryanic** [comment]
In your version drivers all works fine. When do you plan release this version of drivers?

**Comment by rene-ye** [comment]
Hmm that's weird, I don't recall any changes going in between 7.3 and 7.4 would affect this behavior. I can't provide a hard date for the release, but it should be released before the end of August.

**Comment by rene-ye** [comment]
@Pryanic I just tested the application with 7.2.2 and 7.3.1-preview. The issue seems to occur in 7.2.2 but not 7.3.1-preview, you don't need to wait for the next release to resolve this issue. You can get 7.3.1 from our release page here: https://github.com/microsoft/mssql-jdbc/releases/tag/v7.3.1

**Comment by Pryanic** [comment]
Thank you
