### ISSUE TITLE
[BUG]  Not all result sets returned 

### ISSUE THREAD

**Issue by Pryanic** [microsoft/mssql-jdbc#1110]
## Driver version

<version>7.2.2.jre8</version>

## SQL Server version

Ms SQL 2019
## Client Operating System

MacOS
## JAVA/JVM version

java version 1.8

I have the following stored procedure
```
create or alter procedure new_procedure as 
begin
  select 1;
  insert into table_with_2_rows values(10);
  select 2;
end
;
```
I expected get 3 result set but the stmt return only one. 
I create statement via connection.getStatement(). I execute the stored procedure as stmt.execute(query)

**Comment by rene-ye** [comment]
I am able to retrieve all 3 results from the stored procedure.
![image](https://user-images.githubusercontent.com/6042742/61390469-b1d6ee80-a86f-11e9-96ba-c9d1458d8c70.png)

Please make sure you're reading all of the results in the statement by using `s.getMoreResults()`. Gord has an example [here demonstrating reading all parts of the result set.](https://github.com/microsoft/mssql-jdbc/issues/826#issuecomment-429568069)

**Comment by Pryanic** [comment]
Thank you very much. Your answer very helpful for me
