### ISSUE TITLE
[BUG] Caller parameter favored over URL parameters

### ISSUE THREAD

**Issue by elijahgagne** [microsoft/mssql-jdbc#1111]
## Driver version
7.3.1.jre11-preview

## SQL Server version
Microsoft SQL Server 2014 (SP2-CU3) (KB3204388) - 12.0.5538.0 (X64)

## Client Operating System
Ubuntu 18.04.2 LTS

## JAVA/JVM version
11.0.2

## Table schema
n/a, this is a connect string issue

## Problem description
1. Expected behaviour: client successfully authenticates and connects
2. Actual behaviour: client fails to connect
3. Error message/stack trace:
```
[egagne:/opt/sqllinedir] [v] $ ./sqlline \
> -u 'jdbc:sqlserver://MY_SERVER;integratedSecurity=true;authenticationScheme=NTLM;domain=MY_DOMAIN;user=MY_USERNAME;password=MY_PASSWORD' \
> -d com.microsoft.sqlserver.jdbc.SQLServerDriver \
> -e 'select name from sys.databases'
Jul 20, 2019 12:34:42 PM com.microsoft.sqlserver.jdbc.SQLServerConnection connectInternal
SEVERE: ConnectionID:1 "User" (or "UserName") and "Password" connection properties must be specified for NTLM authentication.
Error: "User" (or "UserName") and "Password" connection properties must be specified for NTLM authentication. (state=,code=0)
com.microsoft.sqlserver.jdbc.SQLServerException: "User" (or "UserName") and "Password" connection properties must be specified for NTLM authentication.
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1620)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1162)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:760)
        at sqlline.DatabaseConnection.connect(DatabaseConnection.java:131)
        at sqlline.DatabaseConnection.getConnection(DatabaseConnection.java:182)
        at sqlline.Commands.connect(Commands.java:1309)
        at sqlline.Commands.connect(Commands.java:1203)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at sqlline.ReflectiveCommandHandler.execute(ReflectiveCommandHandler.java:38)
        at sqlline.SqlLine.dispatch(SqlLine.java:713)
        at sqlline.SqlLine.initArgs(SqlLine.java:407)
        at sqlline.SqlLine.begin(SqlLine.java:510)
        at sqlline.SqlLine.start(SqlLine.java:266)
        at sqlline.SqlLine.main(SqlLine.java:205)
No current connection
sqlline version 1.8.0
```
4. Any other details that can be helpful:

I first commented about this at https://github.com/microsoft/mssql-jdbc/issues/696#issuecomment-512056901. Based on discussion, I opened an issue with the sqlline developers at https://github.com/julianhyde/sqlline/issues/326. They reviewed the situation and determined that the issue is that the mssql-jdbc driver overwrites connection URL parameters with caller parameters. However, that is the opposite behavior of other drivers. Credit to @snuyanzin for analyzing this. They found that the section of code where this happens is: https://github.com/microsoft/mssql-jdbc/blob/fcff3a3a1b6de89ec5ebe6e6435f746d6551f7b7/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java#L666-L681
Whereas if you look at jtds, it has the opposite behavior as seen at https://sourceforge.net/p/jtds/code/HEAD/tree/tags/jTDS%201.3.1/src/main/net/sourceforge/jtds/jdbc/Driver.java#l411. That is, it overrides the callers parameters in favor of the parameters supplied in the URL. @snuyanzin mentioned that sqlline always sends the username/password parameters even if they are not needed because some drivers require that. In the case that the caller does not supply them, sqlline sends empty values. This seems to line up with the spec described at https://docs.oracle.com/javase/8/docs/api/java/sql/Driver.html where it says:
```
Parameters:
url - the URL of the database to which to connect
info - a list of arbitrary string tag/value pairs as connection arguments. Normally at least a "user" and "password" property should be included.
```

If you agreed that it makes sense to update mssql-jdbc so that URL parameters are favored over calling parameters, I would be happy to send you a pull request with an update for that. What do you think?

## JDBC trace logs
Can provide if necessary

## Reproduction code
Can provide if necessary

**Comment by ulvii** [comment]
Hi @elijahgagne,
Thanks for creating the issue.
This is not a bug and the current behavior of Microsoft JDBC driver is [JDBC-compliant](https://docs.oracle.com/javase/8/docs/api/java/sql/Driver.html#connect-java.lang.String-java.util.Properties-). 

> Note: If a property is specified as part of the url and is also specified in the Properties object, it is implementation-defined as to which value will take precedence. For maximum portability, an application should only specify a property once.

We can't change this behavior to the opposite, because there might be applications relying on it. As you can see from the JDBC specs, JDBC driver applications are recommended to either specify `URL` or `Properties`, not both. 
Hope this answers your questions.

**Comment by elijahgagne** [comment]
Thanks @ulvii, that was very helpful. It sounds like the sqlline developers are willing to adjust their code based on this information. I'll close this out.
