### ISSUE TITLE
How to create a keytab file for cross domain environment ?

### ISSUE THREAD

**Issue by poornics09** [microsoft/mssql-jdbc#1114]
Can someone help me on how to create and use keytab file in a cross domain environment?

Here is my scenario:

I have installed my java application in node 2 of Domain A and my MS SQL Server is running on Domain B where the AD for B is hosted. I would like to know how & where to create keytab file and use it in my java application?

I have created same account in both Domain A & B and created SPN in Domain B as **MSSQLSvc\serverOnDomainB@A.COM**  && **MSSQLSvc\serverOnDomainB:1433@A.COM**

**Comment by ulvii** [comment]
Hi @poornics09,
You should be able to [create a keytab](https://blogs.technet.microsoft.com/pie/2018/01/03/all-you-need-to-know-about-keytab-files/) using `ktpass` command.
`ktpass /princ user@domain /pass password /ptype KRB5_NT_PRINCIPAL /out mykeytab.keytab`

Once the keytab is created, you will need to specify it in [JAAS Login Configuration file](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-2017#creating-a-login-module-configuration-file). Your configuration file would be similar to 
```
SQLJDBCDriver {
 com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true useTicketCache=false renewTGT=false doNotPrompt=true storeKey=false
    debug=false  keyTab="mykeytab.keytab";
}; 
```

**Comment by poornics09** [comment]
Hi @ulvii 
Thank you for your response. Should I create keytab on the AD where the SQL server is running ?

I did in the same way but my keytab file is not working. Please refer my another post here for further details https://github.com/scgray/jsqsh/issues/63

**Comment by ulvii** [comment]
Hi @poornics09 ,
This is more of a Kerberos cross domain setup issue. I would suggest to take a look at the following to troubleshoot:
- https://docs.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-2017
- https://blogs.msdn.microsoft.com/psssql/2014/06/26/getting-cross-domain-kerberos-and-delegation-working-with-ssis-package/
- https://blogs.msdn.microsoft.com/anthonw/2006/08/02/how-does-authentication-work-cross-domain/
- https://sqlcan.com/2013/07/29/cross-domain-authentication-for-sql-server/

Hope this helps.
