### ISSUE TITLE
[BUG] Useless spaces in DatabaseMetaData#getStringFunctions and DatabaseMetaData#getNumericFunctions

### ISSUE THREAD

**Issue by snuyanzin** [microsoft/mssql-jdbc#1115]
## Driver version
7.2.2
## SQL Server version
```
Microsoft SQL Server 2017 (RTM-CU15-GDR) (KB4505225) - 14.0.3192.2 (X64) 
	Jun 15 2019 00:45:05 
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 19.04)
```
## Client Operating System
ubuntu 19.04

## JAVA/JVM version
java version "1.8.0"

## Problem description

1. Expected behaviour: call for `DatabaseMetaData#getStringFunctions` returns `ASCII,CHAR,CONCAT, DIFFERENCE,INSERT,LCASE,LEFT,LENGTH,LOCATE,LTRIM,REPEAT,REPLACE,RIGHT,RTRIM,SOUNDEX,SPACE,SUBSTRING,UCASE`
so there is a space between `,` and `DIFFERENCE`
The similar thing is for `DatabaseMetaData#getNumericFunctions` which returns
`ABS,ACOS,ASIN,ATAN,ATAN2,CEILING,COS,COT,DEGREES,EXP, FLOOR,LOG,LOG10,MOD,PI,POWER,RADIANS,RAND,ROUND,SIGN,SIN,SQRT,TAN,TRUNCATE` so there is a space between `,` and `FLOOR`
2. Actual behavior: no spaces, e.g. https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getNumericFunctions-- tells about comma-separated
> Retrieves a comma-separated list of math functions available with this database. These are the Open /Open CLI math function names used in the JDBC function escape clause.

**Comment by snuyanzin** [comment]
If there is no objections I could also provide a PR to fix it

**Comment by ulvii** [comment]
Hi @snuyanzin ,

Thanks for creating the issue, please feel free to create a PR, we will make sure to review it.

**Comment by ulvii** [comment]
Thanks for contricution, @snuyanzin. The PR is merged now.
