### ISSUE TITLE
[BUG] ISQLServerDataRecord broke API contract

### ISSUE THREAD

**Issue by cogman** [microsoft/mssql-jdbc#1119]
## Driver version
7.4.0

## Problem description
getRowData used to return `Object[]`, it has been switched to returning a `List<Object>`.  This is a breaking change to the API.

I don't have a good suggestion now that the driver is released.  You could have add a new default method.

`default List<Object> getRowListData() { return Arrays.asList(getRowData()); }`

Or triggered a major version bump.

Either way, 7.2 and 7.4 are now incompatible with each other.

**Comment by lilgreenbird** [comment]
hi @cogman 
Thank you for reporting this, you are correct, we are now working on a hotfix release that reverts this change. The PR for this is [1121](https://github.com/microsoft/mssql-jdbc/pull/1121) this will be in the upcoming 7.4.1. Hotfix release.

**Comment by rene-ye** [comment]
Hotfix released. Closing issue.
