### ISSUE TITLE
Is prepared statement unsupported with temp tables?

### ISSUE THREAD

**Issue by aarsan** [microsoft/mssql-jdbc#1131]
## Question

I am attempting to switch from JTDS to JDBC but running into an issue when creating and inserting into #temp tables. I have read that if I am using prepared statements, this will not work, and that I have to use a regular statement, not a prepared statement. Is this a bug?

**Comment by aarsan** [comment]
To add to this, I have two statements:

    1.     create table ...
    2.     insert into ...

Before switching to JDBC (when I was using JTDS), these executed within the same context. After switching to JDBC, it seems the insert cannot find the temp table. I am using prepared statements.

**Comment by ulvii** [comment]
Hi @aarsan ,
I suspect your application is trying to access a temporary table from a different session than it was created. Please post your JDBC code, I will investigate and get back to you.

**Comment by aarsan** [comment]
Thanks @ulvii. Here is my code. Again, just to reiterate, This code is unmodified from when it was working using JTDS. Once I switched to JDBC, I get "invalid object #temp", during the insert (after create table).

    package myapp.persistence.dao.admin;

    import java.sql.Connection;
    import java.sql.SQLException;
    import java.sql.Statement;
    import java.util.List;
    import myapp.common.service.myappServiceWorker;
    import org.apache.commons.dbutils.QueryRunner;

    public class ServiceHealthDAO {

    private static final String CREATE_TEMP_TABLE_FOR_UPSERT = " \n"
            + "CREATE TABLE #temp ( \n"
            + "	[Server] [varchar](100) COLLATE DATABASE_DEFAULT NOT NULL, \n"
            + "	[ServiceName] [varchar](200) COLLATE DATABASE_DEFAULT NOT NULL, \n"
            + "	[Type] [varchar](100) COLLATE DATABASE_DEFAULT NOT NULL, \n"
            + "	[ThreadId] [int] NOT NULL, \n"
            + " [WarningDetails] NVARCHAR(MAX) NOT NULL ) \n"
            + " \n";

    private static final String INSERT_INTO_TEMP_TABLE_FOR_UPSERT = "INSERT INTO #temp ([Server], [ServiceName], [Type], [ThreadId], [WarningDetails]) VALUES ('%s', '%s', '%s', %d, %s) \n";

    private static final String CREATE_INDEX_ON_TEMP_TABLE = " \n"
            + "CREATE INDEX #i_temp_Server_ServiceName_Type_ThreadId ON #temp([Server], [ServiceName], [Type], [ThreadId]) \n"
            + " \n";

    private static final String WHEN_MATCHED_MODE_1_START = "\n"
            + "WHEN MATCHED AND @mode = ? THEN \n"
            + "		UPDATE \n"
            + "		SET sh.[StartedOn] = @utcDate, \n"
            + "			sh.[LastCheckInOn] = @utcDate, \n"
            + "			sh.[StoppedOn] = NULL, \n"
            + "                 sh.[WarningDetails] = t.[WarningDetails] \n"
            + " \n";

    private static final String WHEN_MATCHED_MODE_2_STOP = "\n"
            + "WHEN MATCHED AND @mode = 2 THEN \n"
            + "		UPDATE \n"
            + "		SET sh.[LastCheckInOn] = @utcDate, \n"
            + "			sh.[StoppedOn] = @utcDate, \n"
            + "                 sh.[WarningDetails] = t.[WarningDetails] \n"
            + " \n";

    private static final String WHEN_MATCHED_MODE_3_CHECK_IN = "\n"
            + "WHEN MATCHED AND @mode = 3 THEN \n"
            + "		UPDATE \n"
            + "		SET sh.[LastCheckInOn] = @utcDate, \n"
            + "			sh.[StoppedOn] = NULL, \n"
            + "                 sh.[WarningDetails] = t.[WarningDetails] \n"
            + " \n";

    private static final String UPSERT_FROM_TEMP_TABLE_TEMPLATE = " \n"
            + "--Mode: 1=Start, 2=Stop, 3=Check in \n"
            + "DECLARE @mode INT = ? \n"
            + "DECLARE @utcDate DATETIME = GETUTCDATE() \n"
            + "\n"
            + "MERGE myapp.ServiceHealth AS sh\n"
            + "	USING #temp AS t\n"
            + "		ON t.[Server] = sh.[Server]\n"
            + "			AND t.[ServiceName] = sh.[ServiceName]\n"
            + "			AND t.[Type] = sh.[Type]\n"
            + "			AND t.[ThreadId] = sh.[ThreadId]\n"
            + "	%s \n" //JJK I substitute in the WHEN MATCHED part here.
            + "	WHEN NOT MATCHED THEN\n"
            + "		INSERT([Server]\n"
            + "	           ,[ServiceName]\n"
            + "	           ,[Type]\n"
            + "	           ,[ThreadId]\n"
            + "	           ,[StartedOn]\n"
            + "	           ,[StoppedOn]\n"
            + "	           ,[LastCheckInOn]\n"
            + "	           ,[WarningDetails]\n"
            + "	           )\n"
            + "		VALUES(t.[Server]\n"
            + "	           ,t.[ServiceName]\n"
            + "	           ,t.[Type]\n"
            + "	           ,t.[ThreadId]\n"
            + "            ,@utcDate\n"
            + "		   ,NULL\n"
            + "		   ,@utcDate\n"
            + "	           ,t.[WarningDetails]\n"
            + "		); \n"
            + " \n";

    public static void upsert(Connection connection, int mode, List<myappServiceWorker> workers) {
        try {
            if (workers == null || workers.isEmpty()) {
                throw new RuntimeException("workers cannot be null or empty");
            }
            if (mode != 1 && mode != 2 && mode != 3) {
                throw new RuntimeException("mode must be 1, 2, or 3 (start, stop, or check in)");
            }
           QueryRunner run = new QueryRunner();
              
                         
              
            StringBuilder sb = new StringBuilder();
            sb.append(CREATE_TEMP_TABLE_FOR_UPSERT);
            for (myappServiceWorker worker : workers) {
                String workerCheckHealthDetails = null;
                //if mode=2, we are stopping the service and I want to clear the warning messages
                if (mode != 2) {
                    workerCheckHealthDetails = worker.checkHealthDetails();
                }
                if (workerCheckHealthDetails == null) {
                    workerCheckHealthDetails = "";
                }
                sb.append(String.format(INSERT_INTO_TEMP_TABLE_FOR_UPSERT, worker.getServer(), worker.getUniqueServiceName(), worker.getType(), worker.getThread(), String.format("'%s'", workerCheckHealthDetails)));
            }
            sb.append(CREATE_INDEX_ON_TEMP_TABLE);
            switch (mode) {
                case 1: {
                    sb.append(String.format(UPSERT_FROM_TEMP_TABLE_TEMPLATE, WHEN_MATCHED_MODE_1_START));
                    break;
                }
                case 2: {
                    sb.append(String.format(UPSERT_FROM_TEMP_TABLE_TEMPLATE, WHEN_MATCHED_MODE_2_STOP));
                    break;
                }
                case 3: {
                    sb.append(String.format(UPSERT_FROM_TEMP_TABLE_TEMPLATE, WHEN_MATCHED_MODE_3_CHECK_IN));
                        
                    break;
                }
                default: {
                    throw new RuntimeException("mode must be 1, 2, or 3 (start, stop, or check in)");
                }
            }

           run.update(connection, sb.toString(), mode); 
       };
               run.update(connection, sb.toString());
                

       } catch (SQLException ex) {
           throw new RuntimeException(ex);
       }
    }

    public static void deleteByServiceName(Connection connection, String serviceName) throws 
        SQLException {
            String cmd = "DELETE FROM myapp.ServiceHealth WHERE ServiceName=?";
            QueryRunner queryRunner = new QueryRunner();
            queryRunner.update(connection, cmd, serviceName);
        }
    }

**Comment by ulvii** [comment]
Hi @aarsan ,
The code you posted does not contain any JDBC APIs, so it is hard for me to determine how you are using PreparedStatements. If you are just concatenating queries and executing them in a PreparedStatement, that should just work. For example, the code below prints `1`.
```
public class Issue1131 {
    public static void main(String[] args) {
        new SQLServerDriver();
        String connectionUrl = "jdbc:sqlserver://localhost;user=test;password=test;";
        try (Connection con = DriverManager.getConnection(connectionUrl);
                PreparedStatement stmt = con.prepareStatement(
                        "create table #temp (a int); insert into #temp values(1); select * from #temp;");
                ResultSet rs = stmt.executeQuery();) {
            rs.next();
            System.out.println(rs.getString(1));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
```
Please try to provide a JDBC repro code/table schema that would help me reproduce the issue on my end. 
Additionally, you can also try to disable PreparedStatement caching by calling `setDisableStatementPooling(true);` on Connection object and see if it makes a difference.

**Comment by ulvii** [comment]
Hi @aarsan ,
I took a look at Apache DBUtils source code and I suspect your application is failing because QueryRunner does [ParameterMetaData lookup](https://github.com/apache/commons-dbutils/blob/5f307466507ead09121a26d7c6fd931553f48e65/src/main/java/org/apache/commons/dbutils/AbstractQueryRunner.java#L280) to validate the number of parameters before executing PreparedStatements. To get ParameterMetaData, Microsoft JDBC driver executes [`sp_describe_undeclared_parameters`](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-describe-undeclared-parameters-transact-sql?view=sql-server-2017) on the server, which does not support temporary tables and `invalid object #temp` is thrown. Your application should work fine after turning off ParameterMetaData lookup using `pmdKnownBroken` property: `QueryRunner run = new QueryRunner(true);`.
I am not sure why jTDS does not fail in this scenario, perhaps it parses the SQL instead of contacting the server to get PreparedStatement parameter types. Hope this helps.

**Comment by aarsan** [comment]
Hi @ulvii . This is super helpful. I did get this working by using PrepareStatement instead of QueryRunner. But, I would like to continue to use QueryRunner (due to a lot of code change) so I will give this a try and see if this works. I very much appreciate the help. I'll let you know how it goes!

**Comment by gordthompson** [comment]
@ulvii re: `sp_describe_undeclared_parameters` and #temp tables:

To address the same limitation on the ODBC side, ODBC Driver 17 for SQL Server added a `UseFMTONLY=yes` connection string parameter.

**Comment by ulvii** [comment]
Hi @gordthompson ,
JDBC 7.4 also has [`useFmtOnly`](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-usefmtonly?view=sql-server-2017) connection property, but it is limited to work with `SELECT/INSERT/UPDATE/DELETE` queries.

**Comment by ulvii** [comment]
Please feel free to re-open the issue if you need further clarifications.

**Comment by aarsan** [comment]
> Hi @aarsan ,
> I took a look at Apache DBUtils source code and I suspect your application is failing because QueryRunner does [ParameterMetaData lookup](https://github.com/apache/commons-dbutils/blob/5f307466507ead09121a26d7c6fd931553f48e65/src/main/java/org/apache/commons/dbutils/AbstractQueryRunner.java#L280) to validate the number of parameters before executing PreparedStatements. To get ParameterMetaData, Microsoft JDBC driver executes [`sp_describe_undeclared_parameters`](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-describe-undeclared-parameters-transact-sql?view=sql-server-2017) on the server, which does not support temporary tables and `invalid object #temp` is thrown. Your application should work fine after turning off ParameterMetaData lookup using `pmdKnownBroken` property: `QueryRunner run = new QueryRunner(true);`.
> I am not sure why jTDS does not fail in this scenario, perhaps it parses the SQL instead of contacting the server to get PreparedStatement parameter types. Hope this helps.

This worked perfectly. Thank you for your help, @ulvii
