### ISSUE TITLE
[BUG] regression with 7.4.1 (against 7.2.2)

### ISSUE THREAD

**Issue by mprins** [microsoft/mssql-jdbc#1134]
**Sorry that this is vague, I will try to update this when I get a chance.**

There seems to be a regression in 7.4.1 which looks like an off-by-one bug.
We have some code inspecting a schema for tables, columns etc and store that in a metadata database so we can use it to configure a webapp.
All this works fine with 7.2.2-jre8, but fails with 7.4.1-jre8 (so just reverting the driver makes everything work again)

I need to set up a debugging environment to see if someting goes wrong when collecting and procesing the metadata from the database or if something is amiss inserting/updating the data.

## Driver version
 7.4.1-jre8

## SQL Server version

Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: ) (Hypervisor) 

## Client Operating System
windows server 2012

## JAVA/JVM version
 
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)

## Problem description

1. Expected behaviour: same as with 7.2.2
2. Actual behaviour: data is removed
3. Error message/stack trace:
4. Any other details that can be helpful:

**Comment by mprins** [comment]
Ahh yes, like #1136 all the tables in this schema have one or more underscores

| name  | type |
|---------------------|-------|
| l_voorziening       | TABLE |
| l_voorziening_soort | TABLE |
| p_voorziening       | TABLE |
| p_voorziening_soort | TABLE |

**Comment by peterbae** [comment]
Hi @mprins, if you think that this issue is identical to #1136, can I close this issue as duplicate? Otherwise, I'll leave this open for you to provide more details.

**Comment by mprins** [comment]
@peterbae It probably is the same issue so OK with me

If not a duplicate I can re-open. I've not gotten around to setting up an environment to reproduce and or further analyse this

**Comment by mprins** [comment]
close as duplicate of  #1136
