### ISSUE TITLE
Bulk copy from Sybase ASE fails for Binary data because of invalid precision

### ISSUE THREAD

**Issue by swapnil-pande** [microsoft/mssql-jdbc#1152]
## Driver version

7.4.1.jre8

 

## SQL Server version

Microsoft SQL Server 2016 (SP2-CU5) (KB4475776) - 13.0.5264.1 (X64)

                Jan 10 2019 18:51:38

                Copyright (c) Microsoft Corporation

                Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

 

 

## Client Operating System

Windows 10

 

## JAVA/JVM version

1.8

 

## Table schema

Both source and target table have column with Binary(48) datatype.

 

## Problem description

SQLServerBulkCopy is being used to copy data from Sybase ASE 15.7 to SQL Server 2016. Table schema is exactly same in source and target database .Result set obtained in Sybase ASE query is passed to SQLServerBulkCopy writeToServer method. However, it is generating BULK INSERT statement with BINARY(0) datatype (i.e. 48 is being replaced with 0 size) and which is causing *** SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: Line 1: Length or precision specification 0 is invalid. Msg 1001, Level 15, State 1, Line 1: Length or precision specification 0 is invalid.

 

1. Expected behaviour: While building column metadata, currently source precision is being used for Binary columns. Sybase ASE will store size as non-zero but precision will be 0 for Binary. SQLServerBulkCopy should either use size from metadata of source, or it should have some special handling like varchar to have non-zero size for binary columns.

2. Actual behaviour: Because of invalid value of size, bulk insert is failing.

3. Error message/stack trace: *** SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: Line 1: Length or precision specification 0 is invalid. Msg 1001, Level 15, State 1, Line 1: Length or precision specification 0 is invalid.

4. Any other details that can be helpful:

 

## JDBC trace logs

at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)

                at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:283)

                at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:129)

                at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)

                at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:26)

                at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.sendBulkCopyCommand(SQLServerBulkCopy.java:1548)

                at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.doInsertBulk(SQLServerBulkCopy.java:1504)

                at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.access$300(SQLServerBulkCopy.java:64)

                at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy$1InsertBulk.doExecute(SQLServerBulkCopy.java:662)

                at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)

                at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2979)

                at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.sendBulkLoadBCP(SQLServerBulkCopy.java:696)

                at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(SQLServerBulkCopy.java:1596)

                at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeResultSet(SQLServerBulkCopy.java:595)

                at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(SQLServerBulkCopy.java:533)

**Comment by ulvii** [comment]
Hi @swapnil-pande,
Thanks for creating the issue. We will investigate and get back to you soon.

**Comment by ulvii** [comment]
Hi @swapnil-pande,
I don't have access to a Sybase server, but I did some testing when both source and destination tables are in SQL Server and everything seems to work fine. Please see the following code.

```
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import com.microsoft.sqlserver.jdbc.SQLServerBulkCopy;
import com.microsoft.sqlserver.jdbc.SQLServerDriver;


public class Issue1152 {
    public static void main(String[] args) throws SQLException {
        new SQLServerDriver();

        String connectionUrl = "jdbc:sqlserver://localhost;user=test;password=test;";
        Connection con = DriverManager.getConnection(connectionUrl);
        Statement stmt = con.createStatement();

        // Create source and destination tables and insert value into source table.
        stmt.executeUpdate("create table issue1152_source (binaryCol binary(48))");
        stmt.executeUpdate("create table issue1152_dest (binaryCol binary(48))");
        stmt.executeUpdate("insert into issue1152_source values (Cast('testtesttestttest' As binary(48)))");

        // Get source table as a ResultSet.
        ResultSet rs = stmt.executeQuery("select binaryCol from issue1152_source");

        // Write to destination table.
        SQLServerBulkCopy bulkCopy = new SQLServerBulkCopy(con);
        bulkCopy.setDestinationTableName("issue1152_dest");
        bulkCopy.writeToServer(rs);
        bulkCopy.close();

        // Print source table.
        ResultSet rsSource = stmt.executeQuery("select * from issue1152_source;");
        rsSource.next();
        System.out.println("source: " + rsSource.getString(1));

        // Print destination table.
        ResultSet rsDest = stmt.executeQuery("select * from issue1152_source;");
        rsDest.next();
        System.out.println("source: " + rsDest.getString(1));

        stmt.executeUpdate("drop table issue1152_source;");
        stmt.executeUpdate("drop table issue1152_dest;");

        stmt.close();
        rs.close();
        rsSource.close();
        rsDest.close();

    }
}
```
I suspect column types of Sybase and SQL Server tables do not match and would suggest to explicitly map columns using `addColumnMapping()` API. [This page](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-bulk-copy-with-the-jdbc-driver?view=sql-server-2017#multiple-bulk-copy-operations) has a sample and more details. Hope this helps.

**Comment by swapnil-pande** [comment]
Hi @ulvii

Thank you for your reply. If both source and target resultset if from SQLServer, then there is no issue. However, current SQLServerBulkCopy implementation expects that size for Binary Column should be returned by precision column by all the result set metadata implementation, which sounds incorrect. There is no precision or scale for Binary data. Since SQLServer result set metadata is implementation in such way that, size is returned in precision field it will work if both source and target is from SQL Server. However, if source is Sybase ASE, then we will get this issue. I would suggest to reproduce the issue with some other source data base, typically Sybase ASE if possible.

**Comment by ulvii** [comment]
I installed Sybase ASE in our test lab and tried the code below and everything works fine. I am using [jTDS](http://jtds.sourceforge.net/) to connect to Sybase. 
```
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import com.microsoft.sqlserver.jdbc.SQLServerBulkCopy;
import com.microsoft.sqlserver.jdbc.SQLServerDriver;


public class Issue1152 {
    public static void main(String[] args) throws SQLException, ClassNotFoundException {
        new SQLServerDriver();
        Class.forName("net.sourceforge.jtds.jdbc.Driver");

        String connectionUrlSybase = "jdbc:jtds:sybase://localhost:5000;user=test;password=test";
        String connectionUrl = "jdbc:sqlserver://localhost:1433;user=test;password=test;";

        Connection conSource = DriverManager.getConnection(connectionUrlSybase);
        Connection conDest = DriverManager.getConnection(connectionUrl);

        Statement stmtSouce = conSource.createStatement();
        Statement stmtDest = conDest.createStatement();

        // Create source and destination tables and insert value into source table.
        stmtSouce.executeUpdate("create table issue1152_source (binaryCol binary(48))");
        stmtDest.executeUpdate("create table issue1152_dest (binaryCol binary(48))");
        stmtSouce.executeUpdate("insert issue1152_source values (0x1234500)");

        // Get source table as a ResultSet.
        ResultSet rs = stmtSouce.executeQuery("select binaryCol from issue1152_source");

        // Write to destination table.
        SQLServerBulkCopy bulkCopy = new SQLServerBulkCopy(conDest);
        bulkCopy.setDestinationTableName("issue1152_dest");
        bulkCopy.writeToServer(rs);
        bulkCopy.close();

        // Print source table.
        ResultSet rsSource = stmtSouce.executeQuery("select * from issue1152_source");
        rsSource.next();
        System.out.println("source: " + rsSource.getString(1));

        // Print destination table.
        ResultSet rsDest = stmtDest.executeQuery("select * from issue1152_dest");
        rsDest.next();
        System.out.println("destination: " + rsDest.getString(1));

        stmtSouce.executeUpdate("drop table issue1152_source");
        stmtDest.executeUpdate("drop table issue1152_dest;");

        stmtSouce.close();
        stmtDest.close();
        rs.close();
        rsSource.close();
        rsDest.close();

        conSource.close();
        conDest.close();

    }
}
```
Hope this helps.

**Comment by swapnil-pande** [comment]
I am using Jconn4 driver as our source database (Sybase ASE 15.7) has password encryption enabled and it seems that jTDS does not support that, so I could not test it.
Would you mind trying the same source code with com.sybase.jdbc4.jdbc.SybDriver ?
Jar: jconn4 version 7.07.

**Comment by ulvii** [comment]
Hi @swapnil-pande ,

I tried JConnect driver and bulk copy failed with `Line 1: Length or precision specification 0 is invalid`. This is happening because JConnect driver does not return correct metadata in the result set. According to JDBC specs, [getPrecision()](https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSetMetaData.html#getPrecision(int)) API is supposed to return length in bytes for binary data (48 in this case), but it returns 0. If you are willing to open an issue against JConnect driver, you can use the simple repro code below:
```
public class MetaDataTest {
    public static void main(String[] args) throws SQLException {
        String connectionUrl = "jdbc:sybase:Tds:localhost:5000";
        try (Connection con = DriverManager.getConnection(connectionUrl, "test", "test");
                Statement stmt = con.createStatement()) {

            stmt.executeUpdate("create table issue1152_source (binaryCol binary(48))");
            stmt.executeUpdate("insert issue1152_source values (0x1234500)");

            ResultSet rs = stmt.executeQuery("select binaryCol from issue1152_source");
            ResultSetMetaData metaData = rs.getMetaData();
            // Prints 0, bur correct return value is 48.
            System.out.println(metaData.getPrecision(1));

            stmt.executeUpdate("drop table issue1152_source");
        }
    }
}
```
Please let me know if you need further clarifications. For now I will close the issue as Microsoft JDBC driver behavior is correct and the incident needs to be resolved in JConnect driver.
