### ISSUE TITLE
[FEATURE REQUEST] Make mssql jdbc loom friendly

### ISSUE THREAD

**Issue by cogman** [microsoft/mssql-jdbc#1154]
## Is your feature request related to a problem? If so, please give a short summary of the problem and how the feature would resolve it

Currently, sql server uses the synchronized keyword in several places.  Unfortunately, loom may (or may not) support the synchronized keyword pausing a fiber, instead it may end up pausing the fiber carrier thread (it is an open question).

See: https://cr.openjdk.java.net/~rpressler/loom/Loom-Proposal.html

and for where those places are

https://github.com/microsoft/mssql-jdbc/search?q=synchronized&unscoped_q=synchronized

## Describe the preferred solution
There is an easy solution here, instead of using the synchronized keyword, use j.u.c locks such as https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/ReentrantLock.html 

These APIs will be guaranteed to pause fibers when they are hit.  Further, blocking calls such as Socket IO will also cause fibers to pause (rather than blocking the carrier thread).

## Reference Documentations/Specifications

https://github.com/microsoft/mssql-jdbc/search?q=synchronized&unscoped_q=synchronized
 https://cr.openjdk.java.net/~rpressler/loom/Loom-Proposal.html
 https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/locks/ReentrantLock.html

**Comment by peterbae** [comment]
Hi @cogman, thanks for contacting us. It seems like Project Loom is still under active development. We'll keep this issue open for now, and let us know when we can confirm that the synchronized keyword will have a problem with loom, then we'll look into it.

**Comment by cogman** [comment]
@peterbae Will do.

I opened this issue primarily because oracle is starting to advertise their driver as being "Fiber ready"

https://mail.openjdk.java.net/pipermail/jdbc-spec-discuss/2019-September/000529.html

What that means is really just "They've removed synchronized".

I'm watching the project pretty closely so I'll let ya'll know if this becomes more concrete.

**Comment by AlbozDroid** [comment]
Any update on this? Project Loom is now in preview in JDK 16.

**Comment by cogman** [comment]
Project loom is currently building with JDK 16.  There's still not a final release date.

As far as I've seen, it's still the case that synchronized blocks aren't handled.

**Comment by jono-coder** [comment]
I can do this, but if the files I edit are changed from a formatting perspective (as well as the relevant code changes), is that an issue?

Can someone please give me some info ito how best to proceed?

**Comment by jono-coder** [comment]
> I can do this, but if the files I edit are changed from a formatting perspective (as well as the relevant code changes), is that an issue?
> 
> Can someone please give me some info ito how best to proceed?

Ok, no worries, it's all covered in the README.md.

**Comment by cogman** [comment]
Just FYI for anyone watching this case, JDK 19 shipped with a loom preview and it looks like the `synchronized` the various `Object` blocking calls (`monitor`, `wait`) will cause problems if it wraps IO.

The postgres jdbc driver is currently going through a synchronized purge.

https://github.com/pgjdbc/pgjdbc/issues/1951

**Comment by Jeffery-Wasty** [comment]
This was resolved with #1931.
