### ISSUE TITLE
[QUESTION] Can a specific query get an empty value from a datasource?

### ISSUE THREAD

**Issue by keunilyoon** [microsoft/mssql-jdbc#1167]
Hi.

We operate in the following environments:

-Apache Tomcat 8 (Tomcat Datasource)
-Spring 4.3.21
-myBatis 3.4.5
-myBatis Spring 1.3.1
-MS SQL JDBC Driver 6.4.0.jre7

Recently, there are sudden data in the DB, but the result is Null.
No SQLException was thrown.

[Java Dao]
```
public Management selectData () throws SQLException {

return (Management) getSqlSession (). selectOne ("MANAGEMENT.selectManagement");
}

```
[Mapper]

```
<mapper namespace = "MANAGEMENT">

	<cache flushInterval = "60000" />

	<resultMap type = "com.domain.Management" id = "ManagementMap">
		<result property = "pData" column = "P_DATA" />
	</resultMap>


	<select id = "selectManagement" parameterType = "Management" resultMap = "ManagementMap">
		SELECT TOP 1 P_DATA FROM T_MANAGEMENT
	</select>

</mapper>
```

This service has been in trouble for many years, but after the following query was executed with the same Datasource at the time of the problem:
The result is traced as returning null.

-ALTER AUTHORIZATION ON DATABASE
-EXEC AS LOGIN

Do you have any related issues?

**Comment by peterbae** [comment]
Hi @keunilyoon, if I understood the question correctly, then yes, a datasource can definitely return a NULL value in a row. You can try this out yourself by doing something similar in SSMS:

```
create table varchartest (c1 varchar(200));
insert into varchartest values (NULL);
select * from varchartest;
```

The resulting row from the column `c1` will have a NULL value.

**Comment by keunilyoon** [comment]
> 
> 
> Hi @keunilyoon, if I understood the question correctly, then yes, a datasource can definitely return a NULL value in a row. You can try this out yourself by doing something similar in SSMS:
> 
> ```
> create table varchartest (c1 varchar(200));
> insert into varchartest values (NULL);
> select * from varchartest;
> ```
> 
> The resulting row from the column `c1` will have a NULL value.

Thank you for your answer. However, this code has been used for many years and suddenly started to return Null after the following sql was executed using the datasource:
-ALTER AUTHORIZATION ON DATABASE
-EXEC AS LOGIN

What query can suddenly return null in result?

**Comment by peterbae** [comment]
If you've been using the same MSSQL JDBC driver version (MS SQL JDBC Driver 6.4.0.jre7 in your case) and the query behavior suddenly changed, then something in your environment must've changed. Unless I'm missing some information here, it looks like this problem (if this is a problem) isn't related to the driver. If you're wondering why the queries `ALTER AUTHORIZATION ON DATABASE` and `EXEC AS LOGIN` are returning null, they are supposed to return no rows because those queries do not result in any return data from the SQL server.

**Comment by keunilyoon** [comment]
> 
> 
> If you've been using the same MSSQL JDBC driver version (MS SQL JDBC Driver 6.4.0.jre7 in your case) and the query behavior suddenly changed, then something in your environment must've changed. Unless I'm missing some information here, it looks like this problem (if this is a problem) isn't related to the driver. If you're wondering why the queries `ALTER AUTHORIZATION ON DATABASE` and `EXEC AS LOGIN` are returning null, they are supposed to return no rows because those queries do not result in any return data from the SQL server.

Thank you for the answer.
My question is not that the below query returned null
- ALTER AUTHORIZATION ON DATABASE
- EXEC AS LOGIN

The query that originally returned the data returned null.
It is assumed that the phenomenon has occurred since the above query was executed.
But it doesn't reproduce well.
Could some other query cause the Driver to return null without a SQLException?
For example, it might affect JDBC connections or memory areas.

**Comment by peterbae** [comment]
I'm not aware of any issues with the driver that involves a query to return null when it shouldn't. If you've been using the same driver version for a long time and this issue just became reproducible, then it's probably not the driver that's causing this.

**Comment by ulvii** [comment]
Hi @keunilyoon ,

Any updates on this? If you still want us to assist you, please make sure to provide standalone reproduction code.

**Comment by keunilyoon** [comment]
We did a long test to reproduce the same case, but couldn't.
Probably due to other factors, the result is empty.
Thanks
