### ISSUE TITLE
[QUESTION] AuthenticationJNI auth DLL loading

### ISSUE THREAD

**Issue by Pryanic** [microsoft/mssql-jdbc#1170]
## Relevant Issues and Pull Requests

I found in code of driver interesting class AuthenticationJNI and this class contains 

```
 String libName = "sqljdbc_auth";
 System.loadLibrary(libName);
```
In my application I should load drivers dynamically and I use few version of ms sql jdbc drivers, when I try to connect to MS Sql via Windows Authentication   all work fine, but when I change my driver I get the following exception 
 Native Library D:\sqljdbc_auth.dll already loaded in another classloader. 
How can I fix it?

**Comment by peterbae** [comment]
Hi @Pryanic, if you're using Tomcat, I recommend taking a look at this page:

[I'm encountering classloader problems when using JNI under Tomcat](https://cwiki.apache.org/confluence/display/tomcat/HowTo#HowTo-I'mencounteringclassloaderproblemswhenusingJNIunderTomcat)

If this is not applicable to you, then I suggest sticking to one version of MSSQL JDBC driver. Let me know if this solves your problem.

**Comment by Pryanic** [comment]
@peterbae  Thank you for your response. Unfortunately I don't use tomcat and sticking to one version doesn't help me. Each user of my application has own driver which loads via class loader for communication with Ms Sql server, so can we try to find other solution. Is it sqljdbc_auth thread safe?

**Comment by Pryanic** [comment]
I think  we can add small check and it helps me:
`

`

**Comment by peterbae** [comment]
Could you provide some reproduction code as to how your users are loading different versions of our driver within the same JVM context?

**Comment by Pryanic** [comment]
I think I can make small prototype for you. 

```
public Driver getDriver(DriverInformation info){
     URL[] urls = getUrlsByDriverVersion(info.getDriverVersion());
     URLClassLoader loader =new URLClassLoader(urls, 
     Thread.currentThread().getContextClassLoader()); 
     return (Driver) loader.loadClass(info.getMainDriverClass()).newInstance();
}
```

**Comment by peterbae** [comment]
I'm not sure about the context of DriverInformation, but I don't think it's necessary for users to load the driver versions themselves. Instead, I suggest the below code:

```
Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
Connection con = DriverManager.getConnection(connectionUrl);
```

This will allow the JVM to load the MSSQL JDBC driver from classpath, and the DriverManager will decide at runtime which driver to use for you. Otherwise, if you really need to go with the code you have above, then I believe this error you see with the AuthenticationJNI is expected, since loading the JNI library of the same name more than once will throw an error like the one you're experiencing.

**Comment by Pryanic** [comment]
@peterbae  Thank you for your answer. I really need to load jdbc driver from other classloader.

**Comment by ulvii** [comment]
Hi @Pryanic ,
We are planning to rename the DLL to match the jar name/version and it should resolve your issue for the upcoming releases of the driver. The code that loads the DLL will look like something like this:
```
System.loadLibrary(libName-driverVersion);
```
Unfortunately there is not much we can do about the past releases.

**Comment by Pryanic** [comment]
Hi @ulvii  it will be nice. Thank you. When do you plan release it?

**Comment by ulvii** [comment]
We will attempt to rename the DLLs for the next preview release.

**Comment by ulvii** [comment]
Hi @Pryanic ,
We renamed the DLLs to make sure their version matches the jar version. You can download the artifacts from [Maven ](https://search.maven.org/artifact/com.microsoft.sqlserver/mssql-jdbc_auth) and [GitHub](https://github.com/microsoft/mssql-jdbc/releases/tag/v8.1.1).
