### ISSUE TITLE
100ns time resolution truncated to 1 ms

### ISSUE THREAD

**Issue by marschall** [microsoft/mssql-jdbc#1182]
## Driver version
7.4.1.jre8

## SQL Server version
Microsoft SQL Server 2017 (RTM-CU13) (KB4466404) - 14.0.3048.4 (X64) 
	Nov 30 2018 12:57:58 
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 16.04.5 LTS)

## Client Operating System
Ubuntu 19.10

## JAVA/JVM version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (Zulu 8.40.0.25-CA-linux64) (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (Zulu 8.40.0.25-CA-linux64) (build 25.222-b10, mixed mode)

## Table schema
CREATE TABLE JAVA_TIME_42 (TIME_COLUMN TIME(7))

## Problem description

16:28:00.123456700 gets rounded to 16:28:00.123333300. I can't say whether that is on insertion or selection.

1. Expected behaviour: full 100ns precision
2. Actual behaviour: rounding to 1ms precision

## Reproduction code

```java
class TimeRoundingTest {

  @Test
  void timeRounding() throws SQLException {
    try (Connection connection = DriverManager.getConnection(url, user, password);
         Statement statement = connection.createStatement()) {

      statement.execute("DROP TABLE IF EXISTS JAVA_TIME_42");
      statement.execute("CREATE TABLE JAVA_TIME_42 (TIME_COLUMN TIME(7))");

      LocalTime expected = LocalTime.of(16, 28).withNano(123_456_700);
      try {
        try (PreparedStatement insert = connection.prepareStatement("INSERT INTO JAVA_TIME_42(TIME_COLUMN) VALUES (?)")) {
          insert.setObject(1, expected);
          insert.executeUpdate();
        }
        try (PreparedStatement select = connection.prepareStatement("SELECT TIME_COLUMN FROM JAVA_TIME_42");
             ResultSet resultSet = select.executeQuery()) {
          assertTrue(resultSet.next());
          LocalTime actual = resultSet.getObject(1, LocalTime.class);
          assertEquals(expected, actual);
          assertFalse(resultSet.next());
        }
      } finally {
        statement.execute("DELETE FROM JAVA_TIME_42");
        statement.execute("DROP TABLE JAVA_TIME_42");
      }
    }
  }

}
```

**Comment by harawata** [comment]
It's rounded on insertion.
It may pass if you add `setSendTimeAsDatetime=false` to the `url`.
https://docs.microsoft.com/en-us/sql/connect/jdbc/configuring-how-java-sql-time-values-are-sent-to-the-server?view=sql-server-ver15

https://github.com/microsoft/mssql-jdbc/blob/d07678129ad13eef29bf01e761b96c87308ca82e/src/main/java/com/microsoft/sqlserver/jdbc/dtv.java#L894-L903

https://github.com/microsoft/mssql-jdbc/blob/276d2ca654c6a4315829bab7df499b194cf0f32c/src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java#L5377-L5378

**Comment by marschall** [comment]
@harawata it does indeed pass with `sendTimeAsDatetime=false`

**Comment by ulvii** [comment]
Hi @marschall , @harawata,

Glad you could resolve the issue. I am closing the issue for now, please let me know if you have further questions.

**Comment by marschall** [comment]
Hello @ulvii 

I'm not sure I agree. The driver in its default configuration currently truncates data. I don't believe this is a good default. To be honest I don't know why offering data truncation by the driver is even an option.

Imagine you have been using the driver for some time in production. Then you suddenly discover that all you data is truncated and there is no way to restore the original data. I would not be happy.

**Comment by ulvii** [comment]
Hi @marschall,
The property exists to provide backward compatibility against older servers. Changing the default value of `sendTimeAsDatetime` to false is in our backlog and we will address it in on of the upcoming releases.

**Comment by marschall** [comment]
@ulvii do you have an issue for change of the default?

**Comment by harawata** [comment]
@marschall , I believe it's #1007 .
