### ISSUE TITLE
[QUESTION] Any plans to add asynchronous capabilities to driver?

### ISSUE THREAD

**Issue by thaDude** [microsoft/mssql-jdbc#1183]
## Question
Hello,

Looking at the [documentation](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/asynchronous-programming) for the .NET SQL Server client it allows making non-blocking requests. Are there any plans to port this functionality over to Microsoft's SQL Server JDBC driver?

If I understand correctly any JDBC API implementation is synchronous by definition. However, other non-JDBC features such as bulk insertion have already been implemented as part of this project.

Asynchronous Java clients for PostgreSQL and MySQL exist. Adding this functionality to the official Java client would provide arguments in support of using SQL Server when building "end-to-end" non-blocking applications with Vertx and similar frameworks.

Thank you.

**Comment by David-Engel** [comment]
@thaDude 

There are no plans to add asynchronous capabilities to this driver. Asynchronous database access to SQL Server via Java will be implemented in a driver using an API designed to be asynchronous like [R2DBC](https://github.com/r2dbc/r2dbc-mssql) or [ADBA](https://blogs.oracle.com/java/jdbc-next:-a-new-asynchronous-api-for-connecting-to-a-database).

Regards,
David

**Comment by thaDude** [comment]
@David-Engel thank you for your reply and the pointers.
