### ISSUE TITLE
SqlServerDriver.acceptUrl works wrong

### ISSUE THREAD

**Issue by Pryanic** [microsoft/mssql-jdbc#1188]
## Driver version

7.2.0.jre8
8.1.0.jre11-preview
## SQL Server version

MsSql16
## Client Operating System

MacOs
## JAVA/JVM version

Java12
## Table schema

My connection string looks like 

> jdbc:sqlserver://myIp:1433;database=master;password=pass**;**sdfsdf%;user=my_user;

As you see my password contains ;. I use Hikari CP and this pool uses acceptUrl method. I don't want change my password and I want to use Hikari CP. Can you help me with it?

**Comment by ulvii** [comment]
Hi @Pryanic ,
The behavior is not wrong, you need to escape semicolons, see [Using SQL escape sequences](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-sql-escape-sequences?view=sql-server-ver15). Try `jdbc:sqlserver://myIp:1433;database=master;password={pass**;**sdfsdf%};user=my_user;`.

**Comment by Pryanic** [comment]
How I should handle such password `pasS};word={qq`?

**Comment by ulvii** [comment]
`pasS};word={qq` should be escaped as `{pasS}};word={qq}`, but looks like driver does not handle this case. I will work on a PR for this scenario.

**Comment by Pryanic** [comment]
@ulvii Did you fix the bug?

**Comment by rene-ye** [comment]
We will fix this issue in a later release, it's in our backlog.
