### ISSUE TITLE
SQLServerConnection

### ISSUE THREAD

**Issue by fischerRo** [microsoft/mssql-jdbc#1191]
## Question
Why do you think the instance variable "state" in SQLServerConnection  don't need to be volatile.

The Method abort(Executor)  implements java.sql.Connection.abort(Executor)
I think that the javadoc means the other thread should see the change (closed Connection).
But yes the javadoc from  java.sql.Connection.abort(Executor) is not really explicit.

**Comment by ulvii** [comment]
Hi @fischerRo ,
Please describe your use case a bit more. How are you trying to access `state` after Connection.abort()?

**Comment by fischerRo** [comment]
Hi @ulvii,
I think if Thread A ist using the Connection and Thread B use Connection.abort(Executor) to abort the Connection that Thread A is using - perhaps because some blocking or loop problem on Thread A. So i think Thread A self not always (->java language spec.) could see the change from hist state variable. At the moment i think so: if the thread A not see the "state" change,  but he could not read/write to the Socket, so in the exception code a "second" Connection.close()  for Thread A is called. 
Kind Regards
Roman Fischer

**Comment by ulvii** [comment]
Hi @fischerRo ,
I created #1194 , please let me know if it resolves your issue.

**Comment by fischerRo** [comment]
Hi @ulvii,
Thanks, yes this resolves this issue.
