### ISSUE TITLE
getColumns on Azure returns only one column

### ISSUE THREAD

**Issue by ilkerc** [microsoft/mssql-jdbc#1192]
## Driver version
Tried on both `8.1.0.jre8.preview` and `7.4.1.jre8`. Works on `7.0.0.jre8` as expected.

## Problem description
`connection.metaData.getColumns("myDatabaseName", "mySchemaName", "myTableName", "%")`
returns only the first row on Azure. Expected to fetch all the columns in "myTableName". The same thing works perfectly on SQL Server.

**Comment by ulvii** [comment]
Hi @ilkerc ,
Are you using Azure SQL DB or Azure SQL DW?

**Comment by ilkerc** [comment]
> Hi @ilkerc ,
> Are you using Azure SQL DB or Azure SQL DW?

Hi @ulvii I'm using Azure SQL DW

**Comment by ulvii** [comment]
I confirmed the issue, thanks for reporting. We will work on a fix.

**Comment by ulvii** [comment]
#1197 merged.
