### ISSUE TITLE
mssql-jdbc 8.1.1 is not available in central maven repository 

### ISSUE THREAD

**Issue by aanavaneeth** [microsoft/mssql-jdbc#1211]
## Driver version
8.1.1jre11

## Problem description
The latest release 8.1.1.jre11 is not available in [maven central repo](https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/). Please upload that into the central repo.

**Comment by souravjha77** [comment]
Also, 8.1.1.jre8 jar ia also not available  on maven central repo

**Comment by rene-ye** [comment]
https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/8.1.1.jre8-preview/mssql-jdbc-8.1.1.jre8-preview.jar

https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/8.1.1.jre11-preview/mssql-jdbc-8.1.1.jre11-preview.jar

Do these links not work? I'm able to download the jars from the repo links. Note that 8.1.0 and 8.1.1 are both preview releases and therefore it's intended that there's no non-preview version of 8.x.

**Comment by almothafar** [comment]
https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc/8.1.1.jre11

It should be there if that published to mvn, it is an issue with publishing it.

**Comment by rene-ye** [comment]
That was an erroneous publish and we've asked Maven to remove the artifacts. 8.1.1 is not an RTW release, it's a preview release and should not be used in production.

**Comment by davejbur** [comment]
They're still there:
https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc/8.1.1.jre8
https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc/8.1.1.jre11
https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc/8.1.1.jre13
...along with their respective *-preview versions!

**Comment by rene-ye** [comment]
I believe maven is unable to remove the listing, even though the artifacts have been removed and attempting to include it will fail. We can check again with maven to see what can be done.

**Comment by davejbur** [comment]
OK, thanks for the explanation!
