### ISSUE TITLE
[QUESTION] Why was Travis CI config removed?

### ISSUE THREAD

**Issue by sehrope** [microsoft/mssql-jdbc#1218]
## Question
Why was the Travis CI config removed?  I liked having it in the repo as pushes to my own fork would trigger Travis builds.

## Relevant Issues and Pull Requests
The `travis-ci.yml` config file was removed in https://github.com/microsoft/mssql-jdbc/pull/1037 though the title implies that it's only to update Maven deps.

Was that intentional and can we add it back?

**Comment by rene-ye** [comment]
It's intentional; the removal was because of a combination of being unable to run specific tests which required setup and wanting to move completely to azure devops.

**Comment by ulvii** [comment]
@sehrope ,
As @rene-ye mentioned, Linux and macOS CI are now on Azure DevOps. Closing the issue.
