### ISSUE TITLE
[QUESTION] Using a SOCKS proxy

### ISSUE THREAD

**Issue by sulphy** [microsoft/mssql-jdbc#1223]
## Question
I noticed that other JDBC drivers like mySQL offer support for a SOCKS proxy.  I can't however, find anything similar for the mssql jdbc driver.  Is this feature actually available or perhaps could be done for future releases?

**Comment by peterbae** [comment]
Hi @sulphy, it looks like there were some efforts made to support SOCKS proxy in https://github.com/microsoft/mssql-jdbc/issues/462. We will put this item in our backlog.

**Comment by sehrope** [comment]
The PR I created for using a custom socket factory should be usable for a SOCKS proxy as well: https://github.com/microsoft/mssql-jdbc/pull/1217

I'm not sure if there would be name resolution issues (e.g. resolved locally vs resolved remotely by the proxy), but it's possible to use a custom socket factory that delegates to a SOCKS proxy to tunnel the connection.

**Comment by ulvii** [comment]
@sulphy ,
@sehrope 's PR is merged to dev now, could you let us know if it resolves your issue?
