### ISSUE TITLE
[FEATURE REQUEST] Using MSAL4J instead of ADAL4J

### ISSUE THREAD

**Issue by manikandanramaswami** [microsoft/mssql-jdbc#1227]
## Is your feature request related to a problem? If so, please give a short summary of the problem and how the feature would resolve it
ADAL4J library is in maintenance mode and no new features will get added to it. Microsoft recemmends it's users to migrate to MSAL4J instead. I faced a shortcoming with JDBC driver using ADAL4J in ColdFusion 11 environment and the response I got is to use MSAL4J.

https://github.com/AzureAD/azure-activedirectory-library-for-java/issues/134

## Describe the preferred solution
Here is the reference to migration process. https://docs.microsoft.com/en-us/azure/active-directory/develop/migrate-adal-msal-java

## Describe alternatives you've considered
Being ADAL4J team not ready to provide update, I am pretty much stuck with not working JDBC driver under cold fusion environment. Migrating it to MSAL4J is recommended solution by Microsoft.

## Additional context
None

## Reference Documentations/Specifications
Provided links above

**Comment by peterbae** [comment]
Hi @manikandanramaswami, the team will look into this.

**Comment by ulvii** [comment]
Hi @manikandanramaswami ,
We are aware of MSAL4J library and it is in our backlog to investigate the migration process. Please stay tuned.

**Comment by manikandanramaswami** [comment]
Hello, Thanks for the reply! Any specific timelines defined? Lack of this support seems like a blocker in my scenario. Let me know if I can contribute help in anyways.

**Comment by ulvii** [comment]
Hi @manikandanramaswami ,
It is in our backlog and will be addressed as soon as we have bandwidth. If you want to speed up the process, please feel free to create a PR and we will look into it.

**Comment by ulvii** [comment]
#1375 is merged and will be part of 9.1.0-preview release.
