### ISSUE TITLE
com.microsoft.sqlserver.jdbc.ParameterUtils.scanSQLForChar may contains logical error

### ISSUE THREAD

**Issue by Adams112** [microsoft/mssql-jdbc#1232]
## Driver version
7.2.0

## SQL Server version
N/A

## Client Operating System
N/A

## JAVA/JVM version
1.7.0

## Table schema
N/A

## Problem description
it's a repeatable bug.

as show below, it's a simple sql. In con.prepareStatement(sql2) line, scanSQLForChar method will find all '?' in this sql, so ps.setInt(1, 2) can find the place to set parameter.
you can see scanSQLForChar method. in scanSQLForChar method, when come with '/', scanSQLForChar expect next char be '*' or '-', but next is none of them. then it goes into case '-', case '[', case '"', then finds ']', then goes to end of this sql without finding '?'.

but if we replace '?' with parameter mamally, it works ok.
for example "select 1 / (select count(*) from a_basic_info where a_basic_info.contract_id = 1)"

## JDBC trace logs
Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: 索引 1 超出范围。
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:228)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setterGetParam(SQLServerPreparedStatement.java:1124)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setValue(SQLServerPreparedStatement.java:1138)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setInt(SQLServerPreparedStatement.java:1420)
	at test.Main2.test(Main2.java:45)
	at test.Main2.main(Main2.java:34)

## Reproduction code
    	String sql2 = "select 1 / (select count(*) from a_basic_info where a_basic_info.contract_id = ?)";
    	Connection con = DriverManager.getConnection(url, username, password);
    	PreparedStatement ps = con.prepareStatement(sql2);
    	ps.setInt(1, 2);

scanSQLForChar method
    static int scanSQLForChar(char ch, String sql, int offset) {
        char chQuote;
        char chTmp;
        final int len = sql.length();

        while (offset < len) {
            switch (chTmp = sql.charAt(offset++)) {
                case '/':
                    if (offset == len)
                        break;

                    if (sql.charAt(offset) == '*') { // If '/* ... */' comment
                        while (++offset < len) { // Go thru comment.
                            if (sql.charAt(offset) == '*' && offset + 1 < len && sql.charAt(offset + 1) == '/') {
                                // If end of comment
                                offset += 2;
                                break;
                            }
                        }
                        break;
                    } else if (sql.charAt(offset) == '-')
                        break;

                    // Fall through - will fail next if and end up in default case
                case '-':
                    if (sql.charAt(offset) == '-') { // If '-- ... \n' comment
                        while (++offset < len) { // Go thru comment.
                            if (sql.charAt(offset) == '\n' || sql.charAt(offset) == '\r') {
                                // If end of comment
                                offset++;
                                break;
                            }
                        }
                        break;
                    }
                    // Fall through to test character
                case '[':
                    chTmp = ']';
                case '\'':
                case '"':
                    chQuote = chTmp;
                    while (offset < len) {
                        if (sql.charAt(offset++) == chQuote) {
                            if (len == offset || sql.charAt(offset) != chQuote)
                                break;

                            ++offset;
                        }
                    }
                    break;
                default:
                    if (ch == chTmp)
                        return offset - 1;
                    break;
            }
        }

        return len;
    }

**Comment by ulvii** [comment]
Hi @Adams112 ,
We will investigate and get back to you soon.

**Comment by rene-ye** [comment]
Hi @Adams112, this was a known issue and already fixed in our [7.2.1 hotfix](https://github.com/microsoft/mssql-jdbc/releases/tag/v7.2.1).
