### ISSUE TITLE
[FEATURE REQUEST] Asynchronous server output reading

### ISSUE THREAD

**Issue by serge-rider** [microsoft/mssql-jdbc#1238]
## Is your feature request related to a problem? If so, please give a short summary of the problem and how the feature would resolve it

Sometimes we have a really long-running procedures which write a lot of output during their work. But it is not possible to get these logs until query is finished.

We have Statement.getWarnings() and Connection.getWarnings() which can be used to read server output (produced by PRINT or RAISE_ERROR commands). It works Ok but it is always synchronous.
I.e. we can get output log only after query execution is finished.

## Describe the preferred solution

Some other JDBC drivers support getWarnings calls in async mode. It allows to read output in a separate thread while main query is still running.
But any other solution will also work.

**Comment by ulvii** [comment]
Hi @serge-rider ,
This is more of a server-side behavior. The server executes SQL statements and then sends back the result sets, error and info messages, so the driver has to wait for the results. Only when the query execution is completed, the driver parses the TDS stream and generated SQL Warnings.

**Comment by serge-rider** [comment]
@ulvii Thank you for the answer.
So this is not possible, even in theory? I understand that this is more about server-side but may be there are some methods (system procedure call or query from a system table) which can be used to read output log from the server?

**Comment by ulvii** [comment]
Closing the issue, please let us know if you have any other questions.
