### ISSUE TITLE
[QUESTION] Building and running the project using IntelliJ (for learning and contributing)

### ISSUE THREAD

**Issue by tyqi11** [microsoft/mssql-jdbc#1252]
## Question

Hi, everyone!

I am new here in learning this JDBC tool for a test and debug course, where we need to analyze the source code and write test cases for the project. I've been trying to build the source code using IntelliJ for a few days but it fails all the time with different errors.

Can anyone give some instructions on the building process? Like a link or blog for tutorial?

Thanks so much!

**Comment by ulvii** [comment]
Hi @tyqi11 ,
There are instructions on how to build the driver and run the tests with Maven on our [README](https://github.com/microsoft/mssql-jdbc#prerequisites) file. I would suggest to give them a try first to get an idea about the build process.

 You should also be able to import the driver source code as a Maven project with IntelliJ. Once you imported the project, make sure to do a Maven update to resolve the dependencies and have at least JDK 11 as a compiler. If you also want to run the tests, you will need to set `mssql_jdbc_test_connection_properties` environment variable to provide the connection string to your SQL Server setup.

Please also feel free to post the error messages, I should be able to help if I have seen them before :)

**Comment by tyqi11** [comment]
Hi @ulvii ,
Thanks so much for the explanation about the process. I was trying to build the mssql-jdbc folder using Maven, and there were 6 test cases failed.  

[ERROR] Failures: 
[ERROR]   CallableStatementTest>AESetup.setupAETest:217->AESetup.readFromFile:321 enclaveProperties: 
D:\school\2-20_winter\mssql-jdbc\target\test-classes\JavaKeyStore.txt (The system cannot find the file specified) 
[ERROR]   JDBCEncryptionDecryptionTest>AESetup.setupAETest:217->AESetup.readFromFile:321 enclaveProperties: 
D:\school\2-20_winter\mssql-jdbc\target\test-classes\JavaKeyStore.txt (The system cannot find the file specified) 
[ERROR]   PrecisionScaleTest>AESetup.setupAETest:217->AESetup.readFromFile:321 enclaveProperties: 
D:\school\2-20_winter\mssql-jdbc\target\test-classes\JavaKeyStore.txt (The system cannot find the file specified) 
[ERROR]   RegressionAlwaysEncryptedTest>AESetup.setupAETest:217->AESetup.readFromFile:321 enclaveProperties: 
D:\school\2-20_winter\mssql-jdbc\target\test-classes\JavaKeyStore.txt (The system cannot find the file specified) 
[ERROR]   DataClassificationTest.testDataClassificationMetadata:45 
[ERROR]   UTF8SupportTest.setUp:109

The .dump file in surefire-reports folder shows that all the errors start with:
Boot Manifest-JAR contains absolute paths in classpath D:\school\2-20_winter\mssql-jdbc\target\test-classes 
java.lang.IllegalArgumentException: 'other' has different root

When I was trying to run single tests from the source code, there was an error in \mssql-jdbc\src\main\java\com\microsoft\sqlserver\jdbc\SQLServerJdbc42.java
Error:(20, 7) java: duplicate class: com.microsoft.sqlserver.jdbc.DriverJDBCVersion

Can you please help to check the problem?

Thank you!

**Comment by ulvii** [comment]
The failing tests require special environment setup, we are working on skipping them by default. Please stay tuned.

> When I was trying to run single tests from the source code.

If you are running the test from IntelliJ , try excluding SQLServerJdbc42.java from the project.

**Comment by tyqi11** [comment]
Hi @ulvii , thanks so much for your help before. Last time you mentioned:

> The failing tests require special environment setup

Can you explain how to do the special setup? 

My task is to build the project and run the test cases using Travis-CI. I've managed to build using both Maven and Gradle. But the tests failed. 
In Maven, the error message is:
> Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project mssql-jdbc: Fatal error compiling: error: invalid target release: 13

(I added maven-compiler-plugin in jre11 and jre11 in <profile> section.)

In Gradle, it is:
> org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 2.
> .....
> Caused by: org.junit.platform.commons.PreconditionViolationException: Cannot create Launcher without at least one TestEngine; consider adding an engine implementation JAR to the classpath

Can you give some instructions? Thanks!

**Comment by ulvii** [comment]
Hi @tyqi11 ,

Please find the [instructions](https://github.com/microsoft/mssql-jdbc/wiki/How-to-run-Always-Encrypted-tests-locally) on how to setup an environment for Always Encrypted tests. You also need to run the tests against SQL Server 2019. 
You need to set JAVA_HOME to JDK13 to be able to build jre13 jars. See build instructions for different JAVA versions [here](https://github.com/microsoft/mssql-jdbc#build). 
Also a note on Travis-Ci, we used to have a [setup](https://github.com/microsoft/mssql-jdbc/blob/e1f3d7e3e55b0b43e288b2c1224d3daf7fd50fc4/.travis.yml) for it in our repository, but moved to Azure DevOps.

**Comment by ulvii** [comment]
We disabled tests that require setup, so `mvn clean install` should run without test failures. Closing the issue, please feel free to let us know if you have any other questions.
