### ISSUE TITLE
[QUESTION] CI of pull requests

### ISSUE THREAD

**Issue by wrosenuance** [microsoft/mssql-jdbc#1258]
## Question
I am working on adding Azure AD support to the [Go language SQL server driver](https://github.com/denisenkom/go-mssqldb/pull/547) and a question that has come up in that project is how to do continuous integration for future pull requests.

I see this project has a continuous integration system set up for pull requests that runs in Azure DevOps - does it run against an Azure SQL server instance? Is it possible to authenticate using Azure AD and managed identities to support testing different authentication methods?

Please let me know if this is better handled as direct messages to the team - I realize this is not strictly on-topic for the JDBC driver, though you are definitely the closest thing I can find!

## Relevant Issues and Pull Requests
https://github.com/denisenkom/go-mssqldb/pull/547

**Comment by ulvii** [comment]
Hi @wrosenuance ,
[azure-pipelines.yml](https://github.com/microsoft/mssql-jdbc/blob/dev/azure-pipelines.yml) will give you an idea. You should be able to run the CI both on custom and Azure hosted VMs/SQL Servers, assuming Azure Devops pipelines have access to the resources. More details can be found [here ](https://docs.microsoft.com/en-us/azure/devops-project/azure-devops-project-github).

**Comment by wrosenuance** [comment]
Thanks!

It looks like an Azure Subscription is required - I'm guessing that means for this project that Microsoft manages / pays for the Azure Subscription used for CI? If so then we would need to find a way to fund / manage that for the Go driver project.

**Comment by ulvii** [comment]
You are correct. You can contact [Chris](https://github.com/chris-rossi) for further clarifications, he actively works with GO driver.

**Comment by wrosenuance** [comment]
Thank you! This is good to know!
