### ISSUE TITLE
spring boot hikaricp jdbc:mssql -> jdbc:sqlserver !tmpUrl.startsWith(sPrefix) check fail

### ISSUE THREAD

**Issue by ant103** [microsoft/mssql-jdbc#1259]
## Question

I can not speak English well. Please understand this.

I am using hikaricp in spring boot 2.x.

When setting url, hikaricp converts to "jdbc: mssql~" even if "jdbc: sqlserver~" is set. The problem here is that when you check the url in the mssql-jdbc driver, it checks to see if it starts with "jdbc: sqlserver" in the tmpUrl.startsWith (sPrefix) statement.
Here is a failure.
I think the case with jdbc: mssql is also correct, but I am wondering if there are any plans to fix this part.

static Properties parseUrl(String url, Logger logger) throws SQLServerException {
        Properties p = new Properties();
        String tmpUrl = url;
        String sPrefix = "jdbc:sqlserver://"; <- What should I do if "jdbc: mssql"????
        String result = "";
        String name = "";
        String value = "";
        StringBuilder builder;

        if (!tmpUrl.startsWith(sPrefix))
            return null;

**Comment by ulvii** [comment]
Hi @ant103 ,
`jdbc:sqlserver` is required for Microsoft JDBC Driver for SQL Server, this is required and constant. See https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver15

Which version of HikariCP are you using? Can you point me to HikariCP  source code that converts `jdbc: sqlserver` to `jdbc: mssql`? I briefly checked their [repository](https://github.com/brettwooldridge/HikariCP) and couldn't find any conversion of the connection string prefix.

**Comment by ulvii** [comment]
Closing the issue due to inactivity. Please feel free to re-open it if there are any other questions.
