### ISSUE TITLE
[QUESTION] Can the JDBC driver support NTLM between two untruest domains?

### ISSUE THREAD

**Issue by Dantes-Lu** [microsoft/mssql-jdbc#1261]
We have an environment, the application server is in domain A, but the SQL Server instance is in domain B. Domain A and domain B are entrusted. Currently we are using 8.2 JDBC driver. 

In the testing, the user we used is the domain B user. i.e. domain B\user. But the "login from an entrusted domain" error throw when establish the connection.

Here we want to confirm if the JDBC driver support the scenario mentioned above?

**Comment by ulvii** [comment]
Hi @Dantes-Lu ,

Did you add domain B\user to the list of logins of SQL Server? See [this page](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/create-a-login?view=sql-server-ver15) for instructions.

The error message is very generic and can get thrown for almost every NTLM authentication failure. Please post [SQL Server logs](https://docs.microsoft.com/en-us/sql/relational-databases/performance/view-the-sql-server-error-log-sql-server-management-studio?view=sql-server-ver15) and [Security event logs](https://support.microsoft.com/en-ca/help/302542/how-to-diagnose-system-problems-with-event-viewer-in-microsoft-windows) from the machine that your server is running on and I will take a look. 

Please also see #696 , #1172 for other NTLM related suggestions.

**Comment by ulvii** [comment]
Any updates on this @Dantes-Lu ?

**Comment by Dantes-Lu** [comment]
@ulvii 
We figure out it is a firewall issue. After open the JDBC port, the JDBC connection works now.
