### ISSUE TITLE
[QUESTION]How to set tcpKeepAlive time for each connection

### ISSUE THREAD

**Issue by yoshida0123** [microsoft/mssql-jdbc#1263]
## Question
Hello.

I am creating a client that uses JDBC connecter. This client connects multiple connections. I want to change the time of tcp KeepAlive for each connection. The tcp KeepAlive time is specified in the registry tcp_keepalive_time, tcp_keepalive_interval and tcp_keepalive_probes and cannot be changed when connecting.

Question
1. Is there a way to set different times for each connection using tcp KeepAlive?

2. Is there a method other than tcp KeepAlive to detect disconnection at different times for each connection?

3. If it is difficult to detect disconnection at different times for each connection using the above methods 1 and 2, how should the client connecting to the database detect the disconnection?

**Comment by mprins** [comment]
these kind of thing are managed by the operating system, not the java runtime and should definitely be avoided in application code.

if you want to manage jdbc connections you should look into one of the many available pooling solutions

**Comment by ulvii** [comment]
In addition to @mprins suggestions, you can also give [isValid()](https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html#isValid(int)) API a try.

**Comment by ulvii** [comment]
Hi @yoshida0123 ,
Do you have any other questions?

**Comment by ulvii** [comment]
Please feel free to re-open the issue if you have any other questions.
