### ISSUE TITLE
SQLServerBulkCopy may insert value into the wrong Column.

### ISSUE THREAD

**Issue by xianlinbox** [microsoft/mssql-jdbc#1265]
## Question
In SQLServerBulkCopy.java, we created a columnMappings in method validateColumnMappings(), code as follow:
```
                // Generate default column mappings
                ColumnMapping cm;
                for (int i = 1; i <= srcColumnCount; ++i) {
                    // Only skip identity column mapping if KEEP IDENTITY OPTION is FALSE
                    if (!(destColumnMetadata.get(i).isIdentity && !copyOptions.isKeepIdentity())) {
                        cm = new ColumnMapping(i, i);
                        // The vector destColumnMetadata is indexed from 1 to be consistent with column indexing.
                        cm.destinationColumnName = destColumnMetadata.get(i).columnName;
                        columnMappings.add(cm);
                    }
                }
 ```
in the code above, there is an assumption for this line  "**cm = new ColumnMapping(i, i);**" , the order of column in destColumnMetadata and srcColumnMetadata are the same.

But the srcColumnMetadata are coming from the  ***Mapping.java definition, The destColumnMetadata are coming from the table definition. These 2 are not always match.

**Comment by ulvii** [comment]
Hi @xianlinbox ,
If you don't define source and destination mappings, the driver will assume the columns are mapped based on ordinal position. For this to work, source and destination schemas must match. If they don't match, you can use `addColumnMapping()` API do define the relationships between source and destination columns. See [this page](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-bulk-copy-with-the-jdbc-driver?view=sql-server-ver15#bulk-copy-api-for-jdbc-driver) for more details and sample code.

**Comment by xianlinbox** [comment]
Got It, thanks for the clarification,

**Comment by ulvii** [comment]
Glad could help, closing the issue.
