### ISSUE TITLE
[FEATURE REQUEST] Native libraries auto-update

### ISSUE THREAD

**Issue by serge-rider** [microsoft/mssql-jdbc#1271]
Since version 8.x native Windows auth library name (former sqljdbc_auth.dll) must correspond to the driver version (e.g. mssql-jdbc_auth-8.2.0.x64.dll).
It makes usage of Maven artifact very inconvenient. As there is no any public link to this library and it can't be referenced as a Maven artifact.
At the moment the only way to update driver version is to download this library manually and put somewhere in your app build. Besides inconvenience this makes makes usage of indirect (LATEST or RELEASE) driver version impossible.

Possible solutions I see at the moment:
- Include native DLLs in driver jar (and unpack/load it on the first connection attempt). Perhaps some driver config options should be added to control this unpacking/linking behavior.
- Create Maven artifact for these DLLs (e.g. with native-maven-plugin). Probably the most straightforward way. 

Also, maybe, the most correct way would be to use JNA instead of JNI + DLLs. But I understand that it will require much more effort.

**Comment by ulvii** [comment]
Hi @serge-rider ,
The Dlls are already on [Maven](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc_auth). Perhaps we should add a link to the README file. Please let me know if this resolves your issue.

**Comment by serge-rider** [comment]
Thank you for the information!
It resolves the issue.

**Comment by ulvii** [comment]
#1272 adds the Maven download link to the README file. Please let us know if you have any other questions.
