### ISSUE TITLE
Can the mssql-jdbc 7.4 driver be used in android apps?

### ISSUE THREAD

**Issue by mjespo** [microsoft/mssql-jdbc#1276]
## Driver version 7
7.4

## SQL Server version
2014

## Client Operating System
Android Oreo

## JAVA/JVM version
1.8

## Problem description
com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "Socket closed".

**Comment by ulvii** [comment]
Hi @mjespo ,
Microsoft JDBC driver is not supported on Android devices. Please see [this ](https://docs.microsoft.com/en-us/sql/connect/jdbc/system-requirements-for-the-jdbc-driver?view=sql-server-2017#operating-system-requirements)page for the list of supported OS.

**Comment by ulvii** [comment]
Closing the issue, please let us know if you have any other questions.
