### ISSUE TITLE
[QUESTION] Same values being returned by STAsBinary and serialize

### ISSUE THREAD

**Issue by humada05** [microsoft/mssql-jdbc#1277]
## Question

My understanding is that sql server uses CLR data types for representing Spatial types internally, and the method `STAsBinary` would convert the object to a WKB format.

The difference between these two formats is clear when I query an actual DB:
```
DECLARE @g geometry;
SET @g = (geometry::STGeomFromText('LINESTRING( -122.360 47.656, -122.343 47.656)', 0))
select @g as CLR, @g.STAsBinary() as WKB
```

But the JDBC driver seems to return the same exact values whether I use `STAsBinary()` or `serialize()`. Is this intentional? I was under the impression that WKB formats needed to follow the [protocol described here](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry#Well-known_binary).

**Comment by peterbae** [comment]
Hi @humada05, the difference between serialize() and STAsBinary is that serialize() returns the WKB value whereas STAsBinary will return the WKB version of the Geometry/Geography object without the Z or M coordinate. The driver currently doesn't deal with how the SQL Server internally stores these data types as the driver only communicates with the server via WKB or WKT.

**Comment by humada05** [comment]
Thanks for clearing up the differences between those two methods,  @peterbae. 

I'm still confused as to why `STAsBinary` seems to give different values between the driver and the actual database. For example, the geometry object `POLYGON((0 0, 150 0, 150 150, 0 150, 0 0))`:

`STAsBinary()` on DB:
```
0x01030000000100000005000000000000000000000000000000000000000000000000C0624000000000000000000000000000C062400000000000C0624000000000000000000000000000C0624000000000000000000000000000000000
```

`STAsBinary()` through driver:
```
0x00000000010405000000000000000000000000000000000000000000000000C0624000000000000000000000000000C062400000000000C0624000000000000000000000000000C062400000000000000000000000000000000001000000020000000001000000FFFFFFFF0000000003
```

**Comment by peterbae** [comment]
Thanks for pointing that out @humada05. This happens because how the driver internally represents the spatial datatype information is different from the way SQL Server does it, because the driver only uses WKB/WKT to communicate with the server. The user can call STAsBinary() on a geometry object that they created locally in Java, but this binary representation won't necessarily match the representation of the same geometry object created in SQL Server. However, if the user were to insert this geometry object into SQL Server and then called STAsBinary() on the column, the data will be identical to its WKB/WKT representation. 

For example, if the user runs this code in java:
```
        try (Connection con = DriverManager.getConnection(<connection string>);) {
            SQLServerPreparedStatement pstmt = (SQLServerPreparedStatement) con.prepareStatement("insert into geomtest values (?)");
            // create table geomtest (g1 geometry);
            Geometry geo = Geometry.STGeomFromText("POLYGON((0 0, 150 0, 150 150, 0 150, 0 0))", 0);
            pstmt.setGeometry(1, geo);
            pstmt.execute();
        }
```

and runs this code in SQL Server:
```
DECLARE @g geometry;
SET @g = (geometry::STGeomFromText('POLYGON((0 0, 150 0, 150 150, 0 150, 0 0))', 0))
select @g.STAsBinary() as WKB0
select g1.STAsBinary() from geomtest;
```

the outcome should be the same from both select queries.

**Comment by humada05** [comment]
@peterbae So for further clarification, when I use STAsBinary() in the driver; the bytes returned are in WKB format right? At least thats what the docs seem to say.

If so, why does the format not match up with the specs I mentioned in https://github.com/microsoft/mssql-jdbc/issues/1277#issue-575658559. For example, the first byte should be either 0x00 or 0x01, indicating the endianness.

From what I'm seeing, the method is actually outputting in the CLR format for the spatial type [specified here](https://docs.microsoft.com/en-us/openspecs/sql_server_protocols/ms-ssclrt/77460aa9-8c2f-4449-a65e-1d649ebd77fa). Is this format also considered a WKB format?

**Comment by humada05** [comment]
Sounds good, thanks for the update!
