### ISSUE TITLE
[FEATURE REQUEST] Pull TVP name from SQLServerDataTable to avoid execution of sp_sproc_columns_100

### ISSUE THREAD

**Issue by Logic-32** [microsoft/mssql-jdbc#1281]
## Is your feature request related to a problem? If so, please give a short summary of the problem and how the feature would resolve it
We use a lot of TVPs via `PreparedStatement.setObject()`.  Often times, we're able to do this by passing in a `SQLServerDataTable` instance but rarely are we ever able to use `SQLServerPreparedStatement.setStructured()`.  This causes SQLServerPreparedStatement to [forcibly report the tvpName as null](https://github.com/microsoft/mssql-jdbc/blob/v8.2.1/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java#L1469) and then [execute a query to load the tvpName](https://github.com/microsoft/mssql-jdbc/blob/v8.2.1/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java#L291) (sp_sproc_columns_100 for modern SQL Servers).  The execution of that query happens ends up executing about 1.4 million times per hour and causes a high CPU as a result.

## Describe the preferred solution
In situations were we can still infer the `tvpName` without using `setStructured()`, such as when a `SQLServerDataTable` is passed in, use the provided `tvpName`.

## Describe alternatives you've considered
We could alternatively use `SQLServerPreparedStatement.setStructured()`.  That requires calling `unwrap()` on the PreparedStatement we have which breaks a metrics utility we use.  Additionally, the problem is further complicated by frameworks like JdbcTemplate and Apache QueryRunner which may not provide access to the underlying `SQLServerPreparedStatement` but still accept `SQLServerDataTable` instances.

## Additional context
This information was gained by querying sys.dm_exec_query_stats in SQL Server 2014.

**Comment by ulvii** [comment]
Hi @Logic-32 ,
We will investigate and get back to you soon.

**Comment by ulvii** [comment]
Hi @Logic-32 ,
To understand the scenario better, please provide a reproduction code/table schema with `setObject()`.

**Comment by Logic-32** [comment]
Type:
```sql
CREATE TYPE dbo.Integers AS TABLE
(
	Token INT NOT NULL
)
```

Proc:
```sql
CREATE PROCEDURE echoTVP
(
	@accountIds dbo.Integers READONLY
)
AS
BEGIN
	SELECT * FROM @accountIds
END
```

Java:
```java
public static void main(String[] args) throws Exception
{
	DataSource ds = // create DS;
	try (Connection conn = ds.getConnection();
		 PreparedStatement stmt = conn.prepareStatement("EXEC echoTVP @accountIds = ?"))
	{
		SQLServerDataTable accountIdRows = new SQLServerDataTable();
		accountIdRows.setTvpName("dbo.Integers"); // Important part here //
		accountIdRows.addColumnMetadata("token", Types.INTEGER);
		accountIdRows.addRow(1);

//			stmt.unwrap(SQLServerPreparedStatement.class).setStructured(1, "dbo.Integers", accountIdRows); // This is the alternative //
		stmt.setObject(1, accountIdRows);

		try (ResultSet rs = stmt.executeQuery())
		{
			System.out.println("--- got something");
		}
	}
	finally
	{
		((AutoCloseable) ds).close();
	}
}
```

**Comment by ulvii** [comment]
Hi @Logic-32 ,
What you are proposing makes sense, I created #1282. Please feel free to review the PR and let me know if it resolves your issue.

**Comment by Logic-32** [comment]
Looks more comprehensive than the PR I submitted :) So, yes.  I believe it will resolve my issue and then some.  Thanks!

**Comment by Logic-32** [comment]
@ulvii, do you happen to have any updates on this?  I'm curious, what's the normal timeline for getting something like this merged/tagged?  I'm not in a huge rush, just want to know if I should go about experimenting with a patched version internally or if it'll be out soon enough I don't have to worry about it.

**Comment by ulvii** [comment]
Hi @Logic-32 ,
We will try to include the change in the next preview release, which is scheduled for March 31st.

**Comment by ulvii** [comment]
#1282 merged.
