### ISSUE TITLE
overly restrictive license in Microsoft JDBC Driver For SQL Server Authentication Library For Windows

### ISSUE THREAD

**Issue by vloo** [microsoft/mssql-jdbc#1292]
## Question 
We would like to include "Microsoft JDBC Driver For SQL Server Authentication Library For Windows" to our product. This is not possible due to an overly restrictive license.
 
License:
https://raw.githubusercontent.com/microsoft/mssql-jdbc/dev/mssql-jdbc_auth_LICENSE

There is this section:
3. DATA COLLECTION. The software may collect information about you and your use of the software and send that to Microsoft. Microsoft may use this information to provide ....

Is this small library really sending information to Microsoft?

Is it possible to change the license so that we are be able to include this DLL to our product?
 
Thank very much for your time.
Kind regards,
Václav Stolín

**Comment by David-Engel** [comment]
> Is this small library really sending information to Microsoft?
> 
> Is it possible to change the license so that we are be able to include this DLL to our product?

@vloo 
No. The library is not collecting and sending information to Microsoft. (Note the use of "may".) You can net trace to verify. I actually noted this to our legal dept when we updated the license but they preferred to keep that section in for consistency across products. I'll bring it up to them again and see if we can remove it.

**Comment by ulvii** [comment]
Hi @vloo ,
We updated the the [license](https://github.com/microsoft/mssql-jdbc/blob/dev/mssql-jdbc_auth_LICENSE) for 8.4.0 release. Please let us know if you have any questions.
