### ISSUE TITLE
Hibernate @ManyToMany with cascade=merge and Always Encrypted

### ISSUE THREAD

**Issue by RomainWilbert** [microsoft/mssql-jdbc#1297]
## Driver version
8.2.2

## JAVA/JVM version
1.8.0

Hi !

I have configured my app with mssql-jdbc driver and always encrypted turned on.I have an entity with a @ManyToMany association as described :

```
    @ManyToMany(cascade = { CascadeType.MERGE })
    @JoinTable(name = "account_authority", joinColumns = @JoinColumn(name = "ACC_ID"), inverseJoinColumns = @JoinColumn(name = "AUTH_NAME"))
    @JsonIgnore
    private Set<Authority> authorities = new HashSet<>();
```

I configured hibernate with 

`hibernate.use_nationalized_character_data = true`

When I try to save my entity, insert is done in the join table but I get an error :

```
14:35:12.101 [http-nio-8080-exec-1] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 402, SQLState: S0002
14:35:12.102 [http-nio-8080-exec-1] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - The data types nvarchar and nvarchar(17) encrypted with (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'CEK_Auto1', column_encryption_key_database_name = 'cpa-dev-02-db') are incompatible in the equal to operator.
14:35:12.109 [http-nio-8080-exec-1] INFO  o.h.e.i.DefaultLoadEventListener - HHH000327: Error performing load command : org.hibernate.exception.SQLGrammarException: could not extract ResultSet
org.hibernate.exception.SQLGrammarException: could not extract ResultSet
```

I tried to fix length for fields on entity and using columnDefinition on jointTable but it does not help :(

**Comment by RomainWilbert** [comment]
I added @Nationalized on the entity that has the AUHT_NAME column and it works...
I thought that hibernate.use_nationalized_character_data = true was enough to handle this issue ?

**Comment by peterbae** [comment]
Hi @RomainWilbert, thanks for contacting us. While our driver sees a lot of usage with hibernate, we don't solve issues related to using their APIs. You should direct this question to hibernate instead, and I'll close this issue in due time unless there are JDBC specific questions.
