### ISSUE TITLE
Use static factory methods for wrapper types

### ISSUE THREAD

**Issue by marschall** [Microsoft/mssql-jdbc#13]
The driver currently instantiates wrapper types (Integer, Long, …) by directly calling the constructor using `new` rather than by calling the static `valueOf` factory methods. This is discouraged and deprecated in Java 9. To quote from the [Integer constructor](http://download.java.net/java/jdk9/docs/api/java/lang/Integer.html#Integer-int-)

> It is rarely appropriate to use this constructor. The static factory valueOf(int) is generally a better choice, as it is likely to yield significantly better space and time performance.

**Comment by ajlam** [comment]
Filing as follow-up for JDK9.

**Comment by marschall** [comment]
This is not really a JDK9 issue. Is this more a performance issue as the status `valueOf` methods reduce pressure on both the allocator and the heap.

**Comment by ajlam** [comment]
@marschall - Understood. The tag is for following up when we schedule our work for JDK9 support.

**Comment by v-xiangs** [comment]
Thank you @marschall. I’m closing this issue since the PR has been merged.
