### ISSUE TITLE
Unneeded temporary objects while URL parsing

### ISSUE THREAD

**Issue by ecki** [microsoft/mssql-jdbc#1304]
The URL parser state engine generates for each character read a StringBuilder and a new String object. This is not needed. Instead you can keep the StringBuilder, append it until the result step where you use a single toString(). Also in the initial state you dont need the append(result).

https://github.com/microsoft/mssql-jdbc/blob/c8a08c8509b1033f0500ed8545ae60162d3c2645/src/main/java/com/microsoft/sqlserver/jdbc/Util.java#L281

BTW: it looks like there is no state für ipv6 [1:2:3:4] literals.

**Comment by ecki** [comment]
Even less allocations you would get by remembering only the Index position and use substring() at the end of each state, not sure if this is faster, however.

**Comment by ulvii** [comment]
#1317 merged.
