### ISSUE TITLE
SQLServerDataTable adding column meta data requires ordering

### ISSUE THREAD

**Issue by FrodoOf9Fingers** [microsoft/mssql-jdbc#1307]
## Driver version
8.3.0.jre8-preview

## SQL Server version
Microsoft SQL Server 2014 (SP3-CU4) (KB4500181) - 12.0.6329.1 (X64) 
	Jul 20 2019 21:42:29 
	Copyright (c) Microsoft Corporation
	Developer Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: )

## Client Operating System
Windows 10

## JAVA/JVM version
"11.0.2"

## Table schema
N/A

## Problem description

1. Expected behaviour: I'm able to initialize in memory datatables with a different column order than the related custom sql Type
2. Actual behaviour: Casting errors are thrown from SQL server when the order of columns do not match

Potential resolution would be to update the documentation to clarify this requirement.

## Reproduction code
    public void example(DataSource ds) throws SQLServerException {
        //Given CREATE TYPE JavaTypes AS TABLE (name VARCHAR(MAX), pathId INT)
        //Version 8.3.0.jre8-preview
        var jdbc = new NamedParameterJdbcTemplate(ds);

        var dt1 = new SQLServerDataTable();
        dt1.addColumnMetadata("name", java.sql.Types.VARCHAR);
        dt1.addColumnMetadata("pathId", java.sql.Types.INTEGER);
        dt1.setTvpName("JavaTypes");
        dt1.addRow("someName", 42);

        var dt2 = new SQLServerDataTable();
        dt2.addColumnMetadata("pathId", java.sql.Types.INTEGER);
        dt2.addColumnMetadata("name", java.sql.Types.VARCHAR);
        dt2.setTvpName("JavaTypes");
        dt2.addRow(42, "someName");

        try {
            jdbc.queryForList("SELECT * FROM :dt", Map.of("dt", dt1));
        } catch (Exception e){
            System.out.println("Error running with first data table");
        }
        try {
            jdbc.queryForList("SELECT * FROM :dt", Map.of("dt", dt2));
        } catch (Exception e){
            System.out.println(("Error running with second data table");
        }
    }

**Comment by ulvii** [comment]
Hi @FrodoOf9Fingers ,
If you don't define source and destination mappings, the driver will assume the columns are mapped based on ordinal position. For this to work, source and destination schemas must match. If they don't match, you can use `addColumnMapping()` API do define the relationships between source and destination columns. The behaviour is already documented [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-bulk-copy-with-the-jdbc-driver?view=sql-server-ver15#bulk-copy-api-for-jdbc-driver), see ColumnMappings property.

**Comment by ulvii** [comment]
Closing the issue. Please feel free to let us know if you have any other questions.
