### ISSUE TITLE
Unreachable code in writeRPCStringUnicode

### ISSUE THREAD

**Issue by xingwenyang** [microsoft/mssql-jdbc#1323]
when i read this project, i found one little issue, i am not sure if i am correct. you(dev) please confirm it.

the issue is in the function "writeRPCStringUnicode" who is at this project's [file](https://github.com/microsoft/mssql-jdbc/blob/dev/src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java).
**### **the issue detail as below****
  1. no matter the 'isShortValue' is true or false at line 4477, the line "4502" and "4517" will never be executed. please help to confirm.

**Comment by rene-ye** [comment]
You are correct. `usePLP` can only be false if `isShortValue` is true, and in those scenarios, if statements with `isShortValue` in the `usePLP` else block will always resolve to `true`.

**Comment by ulvii** [comment]
Hi @xingwenyang ,
Thanks for reporting this. We confirmed that the code you mentioned is not required in the driver and removed it in #1330 .
