### ISSUE TITLE
SQLServerBulkBatchInsertRecord should be package private

### ISSUE THREAD

**Issue by YairHalberstadt** [microsoft/mssql-jdbc#1327]
`SQLServerBulkBatchInsertRecord` is public, but not documented anywhere.

I spent hours trying to use it, only to realize that it is impossible, as it relies on taking an  `ArrayList<Parameter[]>` in it's constructor, and `Parameter` is package private. It exists only to be used internally by `SqlServerPreparedStatement`.

If making it package private is too much of a breaking change, it should be deprecated, and the message should suggest using `preparedStatement.addBatch` instead. The documentation at https://docs.microsoft.com/en-us/sql/connect/jdbc/using-bulk-copy-with-the-jdbc-driver?view=sql-server-ver15 should also suggest using `preparedStatement.addBatch` as well.

**Comment by rene-ye** [comment]
Hi @YairHalberstadt, thanks for your suggestion, the team will consider this change.

**Comment by ulvii** [comment]
#1408 merged.
