### ISSUE TITLE
Is there an Always Encrypted KeyStoreProvider that works with both SSMS and a Java app running on a Unix box? 

### ISSUE THREAD

**Issue by phaninra** [microsoft/mssql-jdbc#1329]
## Question
Based on the what I understand from the article below, there are 3 out of the box keystore providers.
1. Java Keystore: SSMS cannot encrypt/decrypt the data.
2. Windows Certificate KeyStore provider: SSMS can decrypt the data but Java apps running on non-windows platform won't be able to encrypt/decrypt the data.
3. Azure Keystore provider: works with both SSMS and Java (but we cannot use Azure)

Is there a way to store the keys, besides Azure, in such a way that both SSMS and Java on Unix boxes can decrypt the data?

## Relevant Issues and Pull Requests
Ref: https://docs.microsoft.com/en-us/sql/connect/jdbc/using-always-encrypted-with-the-jdbc-driver?view=sql-server-ver15#using-windows-certificate-store-provider

**Comment by rene-ye** [comment]
Hi @phaninra, is it not possible to just follow the instructions under "Using Java Key Store provider". After creating the JKS, the user needs to create a CMK inside the JKS, and then create a CEK from that CMK. Does the CMK created not show up in SSMS wizards?

**Comment by phaninra** [comment]
thanks for the repsonse @rene-ye . These [instructions](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-always-encrypted-with-the-jdbc-driver?view=sql-server-ver15#using-column-master-key-store-providers-for-programmatic-key-provisioning) helped to perform the following operations successfully

- Generate CMK/CEKs from a Java app and insert CEKs into a sql server db.
- CRUD operations on encrypted columns from a Java app.

However, from what I understand, with this approach the manual queries executed through SSMS won't be able to see the plain text data. I've not found any references suggesting otherwise. Did I miss something?

**Comment by rene-ye** [comment]
Hi @phaninra, you should be able to export certificates from ssms in pfx format. These certificates can then be added to the JKS. The reverse should be true as well, you can export certificates from a JKS to pfx format and then use whatever openssl commands to convert the pfx to a readable format by SSMS (I believe it's cer). You should then be able to use T-SQL to import the certificate into SSMS where it can use it. The question here is: what is the linux SQL Server equivalent of the windows key store, and where do users place certificates so SSMS can find them.

**Comment by phaninra** [comment]
Thanks, I will try that.

**Comment by phaninra** [comment]
I've tried below approaches 
- Let SSMS generate a certificate for CMK and import that into JKS
- Inverse, i.e generate a key through command line and import that the SQL Server using SSMS

In both scenarios, sys.column_master_keys.key_store_provider_name was `MSSQL_CERTIFICATE_STORE` for the corresponding keys. 

I ran into following issue when I tried to perform CRUD operations from a Java app, because the jdbc-driver code picked up `MSSQL_CERTIFICATE_STORE`  for decryption purposes. 

```
java.lang.UnsatisfiedLinkError: com.microsoft.sqlserver.jdbc.AuthenticationJNI.DecryptColumnEncryptionKey(Ljava/lang/String;Ljava/lang/String;[B)[B
	at com.microsoft.sqlserver.jdbc.AuthenticationJNI.DecryptColumnEncryptionKey(Native Method)
	at com.microsoft.sqlserver.jdbc.SQLServerColumnEncryptionCertificateStoreProvider.decryptColumnEncryptionKeyWindows(SQLServerColumnEncryptionCertificateStoreProvider.java:61)
	at com.microsoft.sqlserver.jdbc.SQLServerColumnEncryptionCertificateStoreProvider.decryptColumnEncryptionKey(SQLServerColumnEncryptionCertificateStoreProvider.java:75)
	at com.microsoft.sqlserver.jdbc.SQLServerSymmetricKeyCache.getKey(SQLServerSymmetricKeyCache.java:157)
	at com.microsoft.sqlserver.jdbc.SQLServerSecurityUtility.decryptSymmetricKey(SQLServerSecurityUtility.java:136)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.getParameterEncryptionMetadata(SQLServerPreparedStatement.java:942)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:564)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2979)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:473)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
	at org.hibernate.dialect.identity.GetGeneratedKeysDelegate.executeAndExtract(GetGeneratedKeysDelegate.java:57)
```



Is the error related to the below comments found at this [document](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-always-encrypted-with-the-jdbc-driver?view=sql-server-ver15#using-windows-certificate-store-provider).

```
While the other keystore providers in this article are available on all platforms supported by the driver, the SQLServerColumnEncryptionCertificateStoreProvider implementation of the JDBC driver is available on Windows operating systems only.
```

**Comment by rene-ye** [comment]
That link error means the driver can't find the DLL, which is windows exclusive.

**Comment by phaninra** [comment]
Yep, currently the Java app is running on a Windows box. Did you mean it'd work fine on a Unix box?

**Comment by ulvii** [comment]
@phaninra , you need include the corresponding `mssql-jdbc_auth-<version>-<arch>.dll` in the classpath. For example, JDBC 8.2.2 requires mssql-jdbc_auth-8.2.2-x64.dll which can be found on [Maven](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc_auth).

**Comment by phaninra** [comment]
@ulvii  thanks for the response. The `.dll` maybe the missing piece to make it work but will this approach of using `MSSQL_CERTIFICATE_STORE ` work in a Java app running on a `Unix` box?

**Comment by ulvii** [comment]
@phaninra , `MSSQL_CERTIFICATE_STORE ` is for Windows only.
You should try Rene's suggestion on this [comment](https://github.com/microsoft/mssql-jdbc/issues/1329#issuecomment-624910215), JAVA Key Store seems to be the only option.

**Comment by phaninra** [comment]
@ulvii (I believe there's some confusion)

I did try those steps from Rene and [this ](https://github.com/microsoft/mssql-jdbc/issues/1329#issuecomment-626791872) was my follow up question.

Rephrasing my main question to avoid ambiguity if any -

Our setup : SQL Server running on a Windows box, SSMS, and Java-app-running-on-a-unix box.

Based on my findings on keystore providers so far,
- MSSQL_CERTIFICATE_STORE means only SSMS can encrypt/decrypt data. Java app running on a unix box won't be able to encrypt/decrypt data.
- MSSQL_JAVA_KEYSTORE means SSMS won't be able to encrypt/decrypt data.

Is that right? 

I'm hoping to find a solution where the ecnryption/decryption works seamlessly with both SSMS and Java-app-running-on-a-unix box.

**Comment by ulvii** [comment]
How are you running SSMS on Unix? From what I know SSMS is Windows only.

**Comment by phaninra** [comment]
@ulvii It's the Java client that's running on a Unix box, not SSMS.

**Comment by phaninra** [comment]
Hi guys, just wondering if there's anything else I should try out? [This post](https://github.com/microsoft/mssql-jdbc/issues/1329#issuecomment-626911965) has my latest findngs.

**Comment by rene-ye** [comment]
Hi @phaninra, we're just trying to get this scenario set-up in our test lab. Initial investigations confirms what you've described. When encrypting a column, the server stores the type of keystore used. If using SSMS, this value is MSSQL_CERTIFICATE_STORE. When the driver attempts to decrypt a column, the server sends this keystore name to the driver. Therefore, even if a Java keystore is loaded into the driver which contains the correct keys, the driver won't attempt to do a lookup since the JKS's name doesn't match MSSQL_CERTIFICATE_STORE.

**Comment by rene-ye** [comment]
Hi @phaninra, just an update to the thread. I wasn't able to find a workaround, which means the above scenario described is currently not possible.

**Comment by phaninra** [comment]
Thanks @rene-ye @ulvii . I'm exploring the sourcecode for potential solutions and could you keep the thread open for a few more days.

**Comment by rene-ye** [comment]
Hi @phaninra, sure, we can keep the thread open.

**Comment by phaninra** [comment]
Based on my team's exploration so far, there may be 2 solutions. _None of them is ideal_ but posting them for future readers.

**Solution 1**
- Use `MSSQL_JAVA_KEYSTORE` i.e. generate a key on command line and [push ](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-always-encrypted-with-the-jdbc-driver?view=sql-server-ver15#using-column-master-key-store-providers-for-programmatic-key-provisioning)that to sql server
- This will work with Java clients on on all platforms.
- Use a jdbc driver based GUI client like DBVisualizer for manual querying on encrypted data. Make sure to include AE connections parameters in jdbc url. You can still use SSMS for other stuff like DBA, reading/writing non-encrypted data.

**Solution 2**
- Use `MSSQL_CERTIFICATE_STORE` and import the cmk Windows certificate into a JKS. Use the value from `sys.column_master_keys.key_path` as the key alias while inserting into a JKS.
- Write a custom `SQLServerColumnEncryptionKeyStoreProvider` implementation that finds the correct key in a given JKS. Note that the `masterKeyPath` supplied to `com.microsoft.sqlserver.jdbc.SQLServerColumnEncryptionKeyStoreProvider.decryptColumnEncryptionKey(..)`  at runtime is the `sys.column_master_keys.key_path`. 
- Ugly part: Use reflection to do this - `SQLServerConnection.globalSystemColumnEncryptionKeyStoreProviders.put("MSSQL_CERTIFICATE_STORE", customProvider)`.  We need to override the default provider to keep things compatible with both SSMS and mssql-jdbc driver, especially when the latter is running on unix.


@rene-ye @ulvii   hoping for your inputs on Solution 2. I realize that updating `globalSystemColumnEncryptionKeyStoreProviders`  is not part of the official API. But given what's not working currently, I hope you are open to make things flexible so that no ugly reflection code needs to run in order to override the provider for `MSSQL_CERTIFICATE_STORE` on the mssql-jdbc client side.

**Comment by rene-ye** [comment]
Hi @phaninra, our recommendation for users with unique cross-platform needs is to use Azure Key Vault. If that can't be used then it's up to the customers to write their own provider as your team has done. Regarding the need for reflection, I don't think the driver will be able to directly support "redirecting" the key store name lookup as it seems to act as a security feature.

**Comment by ulvii** [comment]
Closing the issue, please feel free to re-open it if you have any other questions.
