### ISSUE TITLE
Fetching column info from catalog provides wrong order of the columns sometimes 

### ISSUE THREAD

**Issue by kolsan789** [microsoft/mssql-jdbc#1332]
## Driver version
8.2.2

## SQL Server version
Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Express Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 16299: ) 

## Client Operating System
Windows 10

## JAVA/JVM version
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)

## Table schema
INFORMATION_SCHEMA

## Problem description
1. Expected behaviour: 
connection.getMetaData().getColumns(catalog, schema, tableName, null) provides always the same column order

2. Actual behaviour:
connection.getMetaData().getColumns(catalog, schema, tableName, null) gives me the last column at first place sometimes

3. Error message/stack trace:
4. Any other details that can be helpful:

**Comment by kolsan789** [comment]
![sample1](https://user-images.githubusercontent.com/4585611/81413657-771bab00-914e-11ea-85d4-f9c45725118c.png)

**Comment by kolsan789** [comment]
![sample2](https://user-images.githubusercontent.com/4585611/81413682-83a00380-914e-11ea-9eb3-2d28f799c143.png)

**Comment by kolsan789** [comment]
the rows have the right order when taken from sp_columns_100 but selecting from the temp table somehow messes up the order

**Comment by rene-ye** [comment]
Hi @kolsan789, the team will look into this and get back to you. Just a few questions: how often does this happen, and are you using any tools/frameworks to execute the T-SQL other than our driver?

**Comment by kolsan789** [comment]
it happens sporadically. but once seen for a table it can be reproduced for the same table many times after that. I use DBeaver with the same driver bound but I think it has nothing to do with the issue...

**Comment by kolsan789** [comment]
proposal fix - add 'ORDER BY ORDINAL_POSITION' in the select part...

**Comment by ulvii** [comment]
Thanks for reporting this @kolsan789. We will work on a fix.

**Comment by lilgreenbird** [comment]
hi @kolsan789 , 

I have created [PR1348](https://github.com/microsoft/mssql-jdbc/pull/1348) containing this fix but am having trouble re-producing the issue you are seeing. I've created a jar with the changes can you please try this out and verify it fixes the problem you saw?

[mssql-jdbc-8.3.1-SNAPSHOT.preview.zip](https://github.com/microsoft/mssql-jdbc/files/4704029/mssql-jdbc-8.3.1-SNAPSHOT.preview.zip)

Thanks..

**Comment by kolsan789** [comment]
> hi @kolsan789 ,
> 
> I have created [PR1348](https://github.com/microsoft/mssql-jdbc/pull/1348) containing this fix but am having trouble re-producing the issue you are seeing. I've created a jar with the changes can you please try this out and verify it fixes the problem you saw?
> 
> [mssql-jdbc-8.3.1-SNAPSHOT.preview.zip](https://github.com/microsoft/mssql-jdbc/files/4704029/mssql-jdbc-8.3.1-SNAPSHOT.preview.zip)
> 
> Thanks..

Hi @lilgreenbird I have tested and it works. thanks!

**Comment by ulvii** [comment]
#1348 merged.
