### ISSUE TITLE
SQLServerException: Arithmetic overflow error converting numeric to data type numeric.

### ISSUE THREAD

**Issue by muneeba-mughal** [microsoft/mssql-jdbc#1333]
## Question
I have tried so many things now but nothing seems to work for me. 

I'm developing in Kotlin using hibernate verison `hibernate-jpa-2.1-api:1.0.2.Final` with driver version`mssql-jdbc:8.3.0.jre8-preview` along with `Microsoft SQL Azure`. 

In my code, I have column definition:
``` 
@Column(precision = 4, scale = 1, columnDefinition = "decimal", name = "value")
    var value: BigDecimal? = null
```
and my column in SQL Server had type `decimal(4,1)`.

On hibernate save operation, I get the error:
```
Exception: SQLServerException: Arithmetic overflow error converting numeric to data type numeric.
```

The value it's trying to insert is -3000. I'm really not sure what's causing the issue. 
 
Any help would be really appreciated. <3

**Comment by rene-ye** [comment]
Perhaps this issue would be more suitable for the Hibernate developers?

**Comment by ulvii** [comment]
@muneeba-mughal ,
`decimal(4,1)` is not suitable to store `-3000`, try `decimal(5,1)`

**Comment by muneeba-mughal** [comment]
Yeah this was an oversight on my end. Didn't even think about the column type being wrong. Thank you so much for your timely responses. I will now close this question. 
Thank you 🙏

**Comment by muneeba-mughal** [comment]
Yeah this was an oversight on my end. Didn't even think about the column type being wrong. Thank you so much for your timely responses. I will now close this question.
Thank you 🙏
