### ISSUE TITLE
[QUESTION] Regarding DNS lookup

### ISSUE THREAD

**Issue by SubhamPramanik** [microsoft/mssql-jdbc#1339]
## Question
Hi,
I'm facing an issue when I'm trying to connect to SQL Server. The SQL Server TCP connection is tunneled through a SOCK5 proxy. The question is:
"Does the default implementation consists of a DNS lookup before connecting to the proxy instead of relying on the DNS resolver of the proxy (a feature introduced with SOCKS5)?"

If yes, please guide me to prevent doing a DNS lookup before connecting to the proxy.

Also, I need to use Spring Boot with JPA to connect to the database, it would be very helpful if I get a sample implementation to connect to the database using a SOCKS5 proxy.

Thank you.

**Comment by ulvii** [comment]
Hi @SubhamPramanik ,
@sehrope recently created a [PR ](https://github.com/microsoft/mssql-jdbc/pull/1217) that allows to use a custom socket factory that delegates to a SOCKS proxy to tunnel the connection. You can take a look at this [test](https://github.com/microsoft/mssql-jdbc/blob/dev/src/test/java/com/microsoft/sqlserver/jdbc/socketfactory/CustomSocketFactoryTest.java) to get an idea on how to use the connection property.

**Comment by sehrope** [comment]
It performs the DNS resolution locally. It'd be nicer if it delayed resolution so the proxy could perform the lookup so that it can resolve names only known to the proxy. For the first version of that feature it was done with local resolution because it tied it more easily to the existing address resolution code the driver does for load balancing and HA.

As a workaround you can perform the remote host lookup yourself and supply the proxy-resolved IP address as the hostname to the driver.

**Comment by SubhamPramanik** [comment]
Hi,
Thank you for responding.

@ulvii I went through the test file and SocketFactory implementation, it does give some clarity on creating a proxy Socket. Now, the next thing would be to connect to the socket with an unresolved InetSocketAddress. How can I do that?

@sehrope I tried to do a remote host lookup, 

> `SocketAddress addr = new InetSocketAddress("localhost", 20004);`
> `Proxy proxy = new Proxy(Proxy.Type.SOCKS, addr);`
> `setSOCKS5ProxyAuthentication("", ""); //Specific to our system`
> `Socket s = new Socket(proxy);`
> `InetSocketAddress vAddr = InetSocketAddress.createUnresolved("db", 51651);`
>  `try {`
>  `    s.connect(vAddr);`
> `} catch (IOException e) {`
> `    e.printStackTrace();`
> `}`
> `ip = s.getRemoteSocketAddress().toString();`

The IP is getting resolved as `0.0.0.0/0.0.0.0:51651`, I am not expecting the resolved IP to be 0.0.0.0. Is the code right? 

If it helps, on MySQL equivalent [here](https://github.com/mysql/mysql-connector-j/blob/afc0a13cd3c5a0bf57eaa809ee0ee6df1fd5ac9b/src/main/core-impl/java/com/mysql/cj/protocol/StandardSocketFactory.java#L149), I can override and change `new InetSocketAddress(possibleAddresses[i], this.port)` to `InetSocketAddress.createUnresolved(possibleAddresses[i], this.port)`, this will serve the purpose. Is there something similar in MS SQL which I can work with?

**Comment by ulvii** [comment]
> . Now, the next thing would be to connect to the socket with an unresolved InetSocketAddress. 

The driver [performs](https://github.com/microsoft/mssql-jdbc/blob/439737ca34e0cd9ba61aa8de0103f6b1a031c46b/src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java#L2647) the DNS resolution locally so seems like the only option is to get the workaround @sehrope  suggested working, but I am not sure why IP is resolved to 0.0.0.0.

**Comment by sehrope** [comment]
I don't think the socket returned back by the proxy has the actual address. It's not part of the SOCKS protocol to send it back to the client. In theory the remote end of the SOCKS proxy could link to something that does not even have an IP address such as a unix socket or some other virtual circuit.

For now you would need to either have the address be equally resolvable on either end of the SOCKS connection or specify the IP address that the remote end of the proxy will use for the connection.

(Or submit a patch to add remote address resolution. :smile:)

**Comment by ulvii** [comment]
Hi @SubhamPramanik ,
Do you have any other questions for us?

**Comment by SubhamPramanik** [comment]
Hi, 
Thanks for the support. The project is on hold for now. I'll get back if required in the future. I'm closing this issue. Thank you.

**Comment by ravi-Mode** [comment]
Hi @ulvii , @sehrope ,
I have a similar request where when we pass the host name  is not known to service using the jdbc driver but proxy know about it. Since, we throw exception before even creating the custom socket based on hostname is resolved or not. Is there way to ignore it or we do some workaround using some property option to ignore it? I know ticket is close but  it seem the same issue so posted here, if required I can create a new issue.

**Comment by Jeffery-Wasty** [comment]
Hi @ravi-Mode,

Please create a new issue to discuss your scenario.
