### ISSUE TITLE
Add ability to get Database Compatibility Level from DatabaseMetaData

### ISSUE THREAD

**Issue by dhait** [microsoft/mssql-jdbc#1344]
## Is your feature request related to a problem? If so, please give a short summary of the problem and how the feature would resolve it
Some external libraries will build SQL queries for a JDBC connection, based on the specific dialect of the database.  So for example, if I know that a database is SqlServer 2008, for example, I will build SQL that avoids any constructs which are only in SqlServer 2017.  This information is usually obtained from the DatabaseMetaData.getDatabaseMajorVersion() call.

However, this function is not accurate if a database is running at a lower compatibility level.  If a SqlServer 2017 server has a database which is running at SqlServer 2008 compatibility; that database only recognizes SqlServer 2008 commands, and the client using the JDBC connection would need to know that.

## Describe the preferred solution
The least impactful solution would be to add an extension function to SQLServerDatabaseMetaData to return the compatibility level of the connected database.
For example, "getDatabaseCompatibilityLevel()"

## Describe alternatives you've considered
One could also just modify the original getDatabaseMajorVersion function, but this might have an unexpected impact beyond this particular use case.

## Additional context
Some of the DatabaseMetaData functions perform internal queries to get their data, so it should be straightforward to query sys.databases.

## Reference Documentations/Specifications
JDBC 4.X

**Comment by dhait** [comment]
Example impacted project issue:
[https://issues.apache.org/jira/browse/CALCITE-3344](https://issues.apache.org/jira/browse/CALCITE-3344)

**Comment by lilgreenbird** [comment]
hi @dhait , the team will look into this, thanks

**Comment by dhait** [comment]
I have humbly submitted a pull request for your review and consideration:
[https://github.com/microsoft/mssql-jdbc/pull/1345](https://github.com/microsoft/mssql-jdbc/pull/1345)

**Comment by ulvii** [comment]
Thanks for the contribution @dhait . We will review and test your PR for the upcoming release.

**Comment by ulvii** [comment]
#1345 merged.
