### ISSUE TITLE
Blob.setBinaryStream and write() fetches column entirely + side effects ResultSet.getBlob/Clob

### ISSUE THREAD

**Issue by aesd** [microsoft/mssql-jdbc#1354]
## Driver version
8.2.2.jre8

## SQL Server version
Microsoft SQL Server 2014 - 12.0.4100.1 (X64) 

## Client Operating System
Windows 7 x64

## JAVA/JVM version
1.8

## Table schema

`CREATE TABLE table (
id numeric(10,0) primary key
,data1 VARBINARY(MAX)
,data2 VARBINARY(MAX)
,data3 VARBINARY(MAX)
)`
## Problem description
I need to append to a blob columns. They are very large to fetching every time (~50mb).
When I use JPA and have an Entity with two fields Blob a; Blob b; the first is always fetched fully. This is reproduced in PROBLEM2.

And PROBLEM1 is I even cant do this with plain JDBC.

 try(ResultSet r = conn.createStatement().executeQuery("select data1, data2, data3 from table where id = 1")) {
                        Blob b = r.getBlob("data1");
                        try(OutputStream o = b.setBinaryStream(b.length() + 1)) {
                            o.write((byte)1); //triggers load all data (50Mb) from data1 column PROBLEM1
                            o.flush();
                        } 
                        r.getBlob("data2");
                        r.getBlob("data3");//triggers load all data from data2 column PROBLEM2
                    }
Expected:
PROBLEM1 - blob payload is not fetched totally. Only appended bytes go to DB
PROBLEM2 - no side effects 

How can i append only bytes to columns without fetching them entirely? Thank you.

**Comment by rene-ye** [comment]
> When I use JPA and have an Entity with two fields Blob a; Blob b; the first is always fetched fully

This is expected behavior, the mssql-jdbc driver does not support streaming for multiple LOB objects at the same time. Users must finish their work with the first LOB before moving the ResultSet cursor via ResultSet.next() or moving onto other LOBs within the same ResultSet. In such situations, users should also call LOB.free() or the LOB will be loaded into memory.

Regarding PROBLEM1, it seems you're attempting to write data into a BLOB object you recieved from the server. The correct way to do this is to read the server's BLOB object byte by byte via Blob.getBinaryStream(), append the necessary bytes to the local buffer object, and then create a new Blob via Connection.createBlob(). You can then use Blob.setBinaryStream() and set the local byte buffer.

Pseudo code:
```java
try (Connection c = DriverManager.getConnection(connString);Statement s = c.createStatement;ResultSet rs = s.executeQuery("select data1, data2, data3 from table where id = 1") {
    Blob b1 = rs.getBlob("data1");
    byte[] blobBuff = readInputStreamToByteArray(b1.getInputStream());
    byte[] desiredBuff = concatTwoByteArrays(blobBuff, appendBuff);
    Blob blobToSend = c.createBlob();
    try (OutputStream o = blodToSend.setBinaryStream(desiredBuff.length())) {
        o.write(desiredBuff);
        o.flush();
    }
    b1.free();
}
```

**Comment by aesd** [comment]
Thank you for the response.
>This is expected behavior, the mssql-jdbc driver does not support streaming for multiple LOB >objects at the same time. Users must finish their work with the first LOB before moving the >ResultSet cursor via ResultSet.next() or moving onto other LOBs within the same ResultSet. In such >situations, users should also call LOB.free() or the LOB will be loaded into memory.
Problem is that I cannot do that with JPA. But thats not that crytic as I hoped I can manage this manually wth JDBC.

And the second answer is that the real nice way to handle Blobs? I need to load entire blob in memory always? Why there is a need to fetch all data if only want to append several bytes? And what if I have 100Mb in Blob? Transfer all data to app server append and back? Its useless. Dont you think?

**Comment by rene-ye** [comment]
The JDBC API objects were designed with Oracle database in mind, these APIs seem sub-optimal at times when working with a different server such as SQL Server. The concept of LOBs are directly supported in Oracle and these APIs behave differently on Oracle server, e.g. they directly support LOB streaming and the server communicates differently with the driver. SQL Server has no concept of Blob/Clob/NClobs, and their mapping is currently varbinary(max)/varchar(max)/nvarchar(max). In the case where a LOB object is too large to be loaded into memory, LOB objects can be used to read the LOB object section by section.

**Comment by aesd** [comment]
Thats sad. Thank you.
