### ISSUE TITLE
Result set is empty with select * query

### ISSUE THREAD

**Issue by suhas9844** [microsoft/mssql-jdbc#1361]
## Driver version

8.3.1.jre14-preview
## SQL Server version

Microsoft SQL Azure (RTM) - 12.0.2000.8 
## Client Operating System

MAC
## JAVA/JVM version

1.8
## Table schema

 siteid varchar(100) primary key ,
    latitude float not null,
    longitude float not null,
    contactno varchar(12) not null,
    last_notification_time varchar(20)
## Problem description

When I run a select * query on a table, it returns a empty result set. The table is dbo schema.
Where as Update on this table is working.
Below is the jdbc connection string format.
`    	String connectionUrl="jdbc:sqlserver://{server}.database.windows.net:1433;database={};user={};password={};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;";
`
## Reproduction code

```
connection = DriverManager.getConnection(connectionUrl);
            Statement statement = connection.createStatement();
            String selectSql = "select * from dbo.SiteReferenceTable";
            ResultSet resultSet = statement. executeQuery(selectSql);
           while (resultSet.next()) {
               System.out.println(resultSet.getString(0) + "; " + resultSet.getFloat(1) + ";" +resultSet.getFloat(2) + ";" + resultSet.getString(3) );
            }
```

**Comment by rene-ye** [comment]
Hi @suhas9844, try `statement.executeQuery(selectSql)` instead of `statement.executeUpdate`?

**Comment by mprins** [comment]
`executeUpdate()` returns `int` not a resultset, check the docs: https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#executeUpdate(java.lang.String)

**Comment by suhas9844** [comment]
@mprins @rene-ye I am sorry I pasted wrong code I tried the executeQuery itself after it failed I tried executeUpdate to check if update works... I have updated the reproduction code ..

**Comment by rene-ye** [comment]
Can you confirm the data was actually inserted correctly via another tool such as SSMS? Execute the same select query from SSMS and see what the result returned is.

**Comment by suhas9844** [comment]
@rene-ye Yes I connected to the same Database through **Dbeaver** and ran the same **select *** query I was able to see 4 rows

**Comment by rene-ye** [comment]
Hi @suhas9844, can you give me the SQL for the executeUpdate that you expect to be returned by the SELECT, I'm attempting to recreate this in our test environment.

**Comment by suhas9844** [comment]
@rene Thanks for the correction I started with 1 and it gave the results. 
I am Sorry for not checking the documentation regarding the ResultSet starting from 1.
