### ISSUE TITLE
We experience performance degradation on JDBC 7.2 and 8.2 compared to JDBC 4 - known issue?

### ISSUE THREAD

**Issue by ArikLerer** [microsoft/mssql-jdbc#1372]
Hi, 
We experience performance degradation on JDBC 7.2 and 8.2 compared to JDBC 4.
We lately from sqljdbc4 into mssql-jdbc-7.2.2.jre8.
When performing a prepared statement like below in a loop we experience degradation of ~25% with the JDBC 7.2 and 7.8 drivers.
Upgrading to mssql-jdbc-8.2.2.jre8 did not resolve the problem.
Is this is a known issue? is there a workaround/patch for this?

SELECT A.KEY , A.CSM0 , A.CSM1 , A.CSM2 , A.CSM3 , A.CSM4 , A.CSM5 , A.CSM6 , A.CSM7 , A.CSM8 , A.CSM9 , A.CSM10 , A.CSM11 , A.CSM12 , A.CSM13 , A.CSM14 , A.CSM15 , A.CSM16 , A.CSM17 , A.CSM18 , A.CSM19 , A.CSM20 , A.CSM21 , A.CSM22 , A.CSM23 , A.CSM24 , A.CSM25 , A.CSM26 , A.CSM27 , A.CSM28 , A.CSM29 , A.CSM30 , A.CSM31 , A.CSM32 , A.CSM33 , A.CSM34 , A.CSM35 , A.CSM36 , A.CSM37 , A.CSM38 , A.CSM39 , A.CSM40 , A.CSM41 , A.CSM42 , A.CSM43 , A.CSM44 , A.CSM45 , A.CSM46 , A.CSM47 , A.CSM48 , A.CSM49 , A.CSM50 , A.CSM51 , A.CSM52 , A.CSM53 , A.CSM54 , A.CSM55 , A.CSM56 , A.CSM57 , A.CSM58 , A.CSM59 , A.CSM60 , A.CSM61 , A.CSM62 , A.CSM63 , A.CSM64 , A.CSM65 , A.CSM66 , A.CSM67 , A.CSM68 , A.CSM69 , A.CSM70 , A.CSM71, A.CSM72, A.CSM73 , A.CSM74 , A.CSM75 , A.CSM76 , A.CSM77 , A.CSM78 , A.CSM79 , A.CSM80 , A.CSM81 , A.CSM82 , A.CSM83 , A.CSM84 , A.CSM85 , A.CSM86 , A.CSM87 , A.CSM88 , A.CSM89 , A.CSM90 , A.CSM91 , A.CSM92 , A.CSM93 , A.CSM94 , A.CSM95 , A.CSM96 , A.CSM97 , A.CSM98 , A.CSM99 , A.CSM100 , A.CSM101 , A.CSM102 , A.CSM103 , A.CSM104 , A.CSM105 , A.CSM106 , A.CSM107 , A.CSM108 , A.CSM109 , A.CSM110 , A.CSM111 , A.CSM112 , A.CSM113 , A.CSM114 , A.CSM115 , A.CSM116 , A.CSM117 , A.CSM118 , A.CSM119 , A.CSM120 , A.CSM121 , A.CSM122 , A.CSM123 , A.CSM124 , A.CSM125 , A.CSM126 , A.CSM127 , A.CSM128 , A.CSM129 , A.CSM130 , A.CSM131 , A.CSM132 , A.CSM133 , A.CSM134 , A.CSM135 , A.CSM136 , A.CSM137 , A.CSM138 , A.CSM139 , A.CSM140 , A.CSM141 , A.CSM142 , A.CSM143 , A.CSM144 , A.CSM145 , A.CSM146 , A.CSM147 , A.CSM148 , A.CSM149 , A.CSM150 , A.CSM151 , A.CSM152 , A.CSM153 , A.CSM154 , A.CSM155 , A.CSM156 , A.CSM157 , A.CSM158 , A.CSM159 , A.CSM160 , A.CSM161 , A.CSM162 , A.CSM163 , A.CSM164 , A.CSM165 , A.CSM166 , A.CSM167 , A.CSM168 , A.CSM169 , A.CSM170 , A.CSM171 , A.CSM172 , A.CSM173 , A.CSM174 , A.CSM175 , A.CSM176 , A.CSM177 , A.CSM178 , A.CSM179 , A.CSM180 , A.CSM181 , B.CSM182 , B.CSM183 , B.CSM184 , A.CSM185, B.CSM186 AS LAST_REVIEW_DATE, B.CSM187 AS PERIODIC_REVIEW, B.CSM188 AS NEXT_REVIEW_DATE, A.CSM189, A.CSM190, A.CSM191, A.CSM192, A.CSM193, A.CSM194, A.CSM195, A.CSM196 , A.CSM197 , A.CSM198 , A.CSM199 , A.CSM200 , A.CSM201 , A.CSM202 , A.CSM203 , A.CSM204 , A.CSM205 , A.CSM206 , A.CSM207 , A.CSM208 , A.CSM209 , A.CSM210 , A.CSM211 , A.CSM212 , A.CSM213 , A.CSM214 , A.CSM215 , A.CSM216 , A.CSM217 , A.CSM218 , A.CSM219 , A.CSM220 , A.CSM221 , A.CSM222 , A.CSM223 , A.CSM224 , A.CSM225 , A.CSM226 , A.CSM227 , A.CSM228 , A.CSM229 , A.CSM230 , A.CSM231 , A.CSM232 , A.CSM233 , A.CSM234 , A.CSM235 , A.CSM236 , A.CSM237 , A.CSM238 , A.CSM239 , A.CSM240 , A.CSM241 , A.CSM242 , A.CSM243 , A.CSM244  FROM PARTY_H_LATEST A LEFT JOIN OUR_PROPERTIES B ON A.KEY = B.KEY WHERE A.KEY = ?

Thanks,
Arik

**Comment by ulvii** [comment]
Hi @ArikLerer ,
There are no known issues regarding performance. It is hard to say what could be wrong just by looking at the query. If you share a reproduction environment ( standalone JDBC repro code and table schema ) , we can take a look to determine if it is a JDBC issue.

**Comment by peterbae** [comment]
Hi @ArikLerer, did you have an update on this issue?

**Comment by ulvii** [comment]
Closed due to inactivity.
