### ISSUE TITLE
Poor performance using multi-parameter prepared statement (select) vs i-net merlia driver

### ISSUE THREAD

**Issue by multicaststorm** [microsoft/mssql-jdbc#1374]
## Driver version
mssql-jdbc-8.2.2.jre8

## SQL Server version
Microsoft SQL Server 2017 (RTM-CU17) (KB4515579) - 14.0.3238.1 (X64)   Sep 13 2019 15:49:57   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

## Client Operating System
Windows 10

## JAVA/JVM version
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

## Table schema
```
CREATE TABLE [dbo].[TestTable](
	[Date] [datetime] NOT NULL,
	[Code] [varchar](30) NOT NULL,
	[Value] [float] NOT NULL,
 CONSTRAINT [PK_TestTable] PRIMARY KEY CLUSTERED 
(
	[Date] ASC,
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
```

## Problem description

We are in the process of migrating from i-net merlia driver to mssql-jdbc driver. But have noticed some poor performance with multi-parameter select parameters (using prepared statements) in some cases

1. Expected behaviour:

   Running the example jdbc query should yield at least similar performance to the i-net merlia driver

2. Actual behaviour:

   Running the query 100 times in a loop yielded these results:

   - i-net merlia ~300ms
   - mssql-jdbc ~16000ms...yep, 50 times slower!!!

3. Error message/stack trace:

   n/a

4. Any other details that can be helpful:

   My simple benchmark test was using 400,000 rows of anonymised data (I will try to attach as zipped .csv file).

   If I hard code the first parameter (Code), then the performance issues go away

   Unfortunately wasn't solved by #1215 
   Also, difficult to tell, but this may be related/duplicate of #1196 

## Reproduction code
    Connection connection = ...; // either mssql-jdbc or merlia connection

    int loops = 100;
    long start = System.currentTimeMillis();
    for (int i = 0; i < loops; i++) {
      PreparedStatement statement = connection.prepareStatement(
            "SELECT t0.Value FROM dbo.TestTable t0 " +
            "WHERE t0.Code = ? " +
            "AND t0.Date = (" +
                  "SELECT MAX(t1.Date) FROM dbo.TestTable t1 " +
                  "WHERE t0.Code = t1.Code " +
                  "AND t1.Date < ?" +
            ')');
      statement.setString(1, "BXCLMLSM");
      statement.setTimestamp(2, Timestamp.valueOf(LocalDateTime.now()));
      ResultSet resultSet = statement.executeQuery();
      while (resultSet.next()) {
        float value = resultSet.getFloat(1);
        // ignore results
      }
      resultSet.close();
      statement.close();
    }
    connection.close();
    long duration = System.currentTimeMillis() - start;
    System.out.printf("Took %sms", duration);

[data.zip](https://github.com/microsoft/mssql-jdbc/files/4846848/data.zip)

**Comment by rene-ye** [comment]
Hi @multicaststorm, we'll take a look into this and get back to you if we're able to reproduce the same performance issues. Regarding the possibility that it's related to #1196, if this is an issue regarding our driver's current logic of preparing statements, then it'll be awhile before a fix is ready.

**Comment by multicaststorm** [comment]
Hi @rene-ye , thanks for the reply. 

I also just tried with jdts v1.3.1 and got the same performance as the mssql driver (~16000ms)

Unfortunately because the merlia driver is closed source and obfuscated binaries, its difficult to see what they are doing differently.

Either way I wouldn't expect hardcoding one of the parameters to have such dramatic difference.

If it is a problem with how prepared statements are created, then that seems a pretty fundamental issue and surely one to be fixed with reasonable urgency? (easy for me to say :))

**Comment by rene-ye** [comment]
It's difficult to say because the performance difference depends on the user's query. There are scenarios where are current logic is faster, which is why we're tentative on this change.

**Comment by Arthurm1** [comment]
@multicaststorm If hardcoding the VARCHAR param in the SQL fixes the issue then the driver is probably passing the String param as NVARCHAR - which will slow your query down because it can't take full advantage of the index.  Try using `sendStringParametersAsUnicode=false` when setting up your connection.  See [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver15) for an explanation.

Using SQL Server Profiler and comparing traces between drivers is a good way to check why there are performance diffs.  If I'm correct then you'd see Merlia pass the code param as VARCHAR and mssql-jdbc pass it as NVARCHAR

**Comment by multicaststorm** [comment]
@Arthurm1 ....You were absolutely correct....thank you very much!

I was previously aware of the VARCHAR/NVARCHAR performance penalty (i.e. querying VARCHAR index with NVARCHAR parameter), but wasn't aware of the 'sendStringParametersAsUnicode' setting.

I'm sure there is good reason that this setting exists, but just out of curiosity, why is it needed? Normally I would expect this behavior to be controlled using the correct jdbc parameter setter:

```
setString(1, "ABC"); // VARCHAR
setNString(1, "ABC"); // NVARCHAR
```

**Comment by Arthurm1** [comment]
@multicaststorm There's some info here #1367 but I've never _not_ used that setting
