### ISSUE TITLE
BulkCopy won't accept a LocalTime/LocalDateTime instances of 100ns precision

### ISSUE THREAD

**Issue by Arthurm1** [microsoft/mssql-jdbc#1376]
## Driver version
8.3.1.jre14-preview

## SQL Server version
Microsoft SQL Server 2019 (RTM-CU4) (KB4548597) - 15.0.4033.1 (X64)   Mar 14 2020 16:10:35   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Linux (Ubuntu 18.04.4 LTS) <X64>

## Client Operating System
Windows 10 with Docker

## JAVA/JVM version
JDK 14

## Problem description
1. Expected behaviour:
The driver should be able to bulk insert LocalTime/LocalDateTime instances of up to 100ns precision e.g. `2020-07-01 12:23:45.1234567`
2. Actual behaviour:
Throws an exception.
3. Error message/stack trace:
```
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Received an invalid column length from the bcp client for colid XX.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:283)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:129)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:26)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.doInsertBulk(SQLServerBulkCopy.java:1589)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy$1InsertBulk.doExecute(SQLServerBulkCopy.java:662)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7349)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3181)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.sendBulkLoadBCP(SQLServerBulkCopy.java:696)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(SQLServerBulkCopy.java:1654)
	at com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(SQLServerBulkCopy.java:619)
```
4. Any other details that can be helpful:
The `SQLServerBulkCopy` class handles 1000ns precision fine e.g. `2020-07-01 12:23:45.123456` but not 100ns.  The reason is that the bulk insert code calls the `toString` method on LocalTime/LocalDateTime to convert the data before sending.  If you look at the docs for `LocalTime#toString` you can see it will output the ns portion with trailing zeros for each scientific unit...
```
HH:mm:ss.SSS
HH:mm:ss.SSSSSS
HH:mm:ss.SSSSSSSSS
```
so once LocalTime/LocalDateTime hits 100ns precision the `toString` method will add 2 trailing zeros e.g. `2020-07-01 12:23:45.123456700` which BCP doesn't seem to like.

The String conversion is done [here](https://github.com/microsoft/mssql-jdbc/blob/4e3ab6690557c000bc16042771020ef530b54bf2/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java#L2272)

A workaround is to pass the data as a String without trailing zeros instead of using the LocalTime/LocalDateTime types.

**Comment by peterbae** [comment]
Hi @Arthurm1, thanks for contacting us. Could you show me how you're inserting a LocalTime/LocalDateTime object with our bulk copy API? Also the target table column type would be helpful.

**Comment by Arthurm1** [comment]
Hi @peterbae 

Column type is anything with 100ns precision e.g. `DATETIME2` or `TIME`

I'm implementing the `ISQLServerBulkData` interface and returning either a `java.time.LocalDateTime` for `DATETIME2` or a `java.time.LocalTime` for `TIME` in the array returned from `ISQLServerBulkData#getRowData()` method.  I supply zero for precision and scale but this doesn't seem to matter as the `toString` method is used to convert both types in `SQLServerBulkCopy`

Hope that helps.

**Comment by peterbae** [comment]
Thanks. The team will look into this and get back to you regarding this problem.

**Comment by rene-ye** [comment]
Hi @Arthurm1, can you post details regarding your implementation of the BulkData interface? While I can see that your explanation of why this is happening is valid, bulk copying CSV and ResultSets actually works fine with the example you provided: `2020-07-01 12:23:45.1234567`. On the other hand, I don't see how the driver would be able to work around this without converting it to String. For example, Time maps to java.sql.Time which doesn't actually support nanoseconds. The driver sends the information as String and relies on SQL Server to do the conversion on it's behalf.

**Comment by Arthurm1** [comment]
Hi @rene-ye 

It's not the fact it's converted to a String that I have an issue with - it's the type of String it produces.

Hopefully this will help...

Using Windows + Java 11 + Docker SQL Server 2019 + `com.microsoft.sqlserver:mssql-jdbc:8.4.1.jre11`

Create a test table...
```
create table dbo.foo (testCol datetime2)
```

Create a test class...
```java
package sqltest;

import com.microsoft.sqlserver.jdbc.ISQLServerBulkData;
import com.microsoft.sqlserver.jdbc.SQLServerBulkCopy;
import com.microsoft.sqlserver.jdbc.SQLServerConnection;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Properties;
import java.util.Set;

public class BulkInsertTest {

    private static String tempTable = "dbo.foo";
    private static String serverName = "???";
    private static String databaseName = "???";
    private static String userName = "???";
    private static String password = "???";

    private static Connection getConnection() throws SQLException {
        Properties connectionProps = new Properties();
        connectionProps.put("user", userName);
        connectionProps.put("password", password);
        String url = "jdbc:sqlserver://" + serverName +
                ";databaseName=" + databaseName +
                ";integratedSecurity=false";

        return DriverManager.getConnection(url, connectionProps);
    }

    private static class BulkRecord implements ISQLServerBulkData {
        boolean anyMoreData = true;
        Object data;

        BulkRecord(Object data) {
            this.data = data;
        }

        @Override
        public Set<Integer> getColumnOrdinals() {
            Set<Integer> ords = new HashSet<>();
            ords.add(1);
            return ords;
        }

        @Override
        public String getColumnName(int column) {
            return "testCol";
        }

        @Override
        public int getColumnType(int column) {
            return java.sql.Types.TIMESTAMP;
        }

        @Override
        public int getPrecision(int column) {
            return 0;
        }

        @Override
        public int getScale(int column) {
            return 7;
        }

        @Override
        public Object[] getRowData() {
            return new Object[]{ data };
        }

        @Override
        public boolean next() {
            if (!anyMoreData)
                return false;
            anyMoreData = false;
            return true;
        }
    }

    private static Object createWithNano(int nanos) {
        return LocalDateTime.of(2020, 1, 1, 12, 34, 56, nanos);
    }

    private static void writeData(Object data) throws SQLException {
        try (Connection conn = getConnection()) {
            final SQLServerConnection sqlServerConnection = conn.unwrap(SQLServerConnection.class);

            try (final SQLServerBulkCopy bulkCopy = new SQLServerBulkCopy(sqlServerConnection)) {
                bulkCopy.setDestinationTableName(tempTable);
                bulkCopy.writeToServer(new BulkRecord(data));
            }
        }
    }

    public static void main(String... args) throws SQLException {
          writeData(createWithNano(0)); // passes
          writeData(createWithNano(100000000)); // passes
          writeData(createWithNano(120000000)); // passes
          writeData(createWithNano(123000000)); // passes
          writeData(createWithNano(123400000)); // passes
          writeData(createWithNano(123450000)); // passes
          writeData(createWithNano(123456000)); // passes
          writeData(createWithNano(123456700).toString().substring(0, 27)); // passes with String
          writeData(createWithNano(123456700)); // FAILS with LocalDateTime - should pass
          writeData(createWithNano(123456780)); // should fail
          writeData(createWithNano(123456789)); // should fail
    }
}
```

Fill your test sql server details into the java code and run the main class.  It attempts to bulk insert a number of LocalDateTime instances with increasing precision.

You should see the program fails on the line I indicated in the comments.

You can see the previous line with the same datetime value that is passed as a String works.

This should be valid as datetime2 is accurate to 100ns but is rejected because [here](https://github.com/microsoft/mssql-jdbc/blob/4e3ab6690557c000bc16042771020ef530b54bf2/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java#L2272) the LocalDateTime is converted into a String: `2020-01-01T12:34:56.123456700` which has 2 additional zeros at the end.  These zeros cause the string to be rejected because it's too long.  Passing a String of `2020-01-01T12:34:56.1234567` works.

I imagine the same thing happens when trying to bulk insert a `LocalTime` value into a `TIME(7)` type.

Using `java.sql.Timestamp` instead of `LocalDateTime` or `LocalTime` works because `Timestamp#toString` method doesn't add trailing zeros.

As far as I can tell the options are...
1) Disallow `LocalTime` and `LocalDateTime` in bulk inserts
2) Special case `LocalTime` and `LocalDateTime` and write your own `toString` methods
3) Special case `LocalTime` and `LocalDateTime` and convert them to `java.sql.Timestamp` using `Timestamp.valueOf`
4) Special case `LocalTime` and `LocalDateTime` and truncate the `toString` result to (9 + scale) for `LocalTime` and (20 + scale) for `LocalDateTime` - which is roughly what I ended up doing athough this will truncate data, not round it like SQL Server does in a query window.

Another option is adding in...
`connectionProps.put("sendTemporalDataTypesAsStringForBulkCopy", "false");`

This goes down another path and allows any precision `java.sql.Timestamp` bulk insertion but rounds the nanos up to 100ns precision instead of rejecting values with too high precision.  It doesn't allow `LocalDateTime` though because it passes the String version of it into `java.sql.Timestamp#valueOf` and that can't cope with the `T` that `LocalDateTime` places between the date and time. That's all done [here](https://github.com/microsoft/mssql-jdbc/blob/4e3ab6690557c000bc16042771020ef530b54bf2/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java#L2442)

Should I be using this flag?  Is it not on by default because for performance reasons?  It seems to be converting a `LocalDateTime` to a `String` to a `java.sql.Timestamp` to a `Calendar` all to get (scaled) number of seconds in a day and then repeating the whole thing to get the number of days since `1st Jan 0001` which seems excessive.
