### ISSUE TITLE
Issues to connect with Azure SQL database using authentication type "ActiveDirectoryMSI"

### ISSUE THREAD

**Issue by sadafshaikh18** [microsoft/mssql-jdbc#1377]
## Driver version
mssql-jdbc-8.2.2.jre8.jar

## SQL Server version
Microsoft SQL Azure (RTM) - 12.0.2000.8  

## Client Operating System
Windows 10 OS
64 bit operating system, x64-based processor

## JAVA/JVM version
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

## Table schema
	Attribute1 nvarchar(38) NOT NULL,
	Attribute2 decimal(12, 0) NOT NULL,
	Attribute3 nvarchar(50) NULL,
	Attribute4 decimal(12, 0) NULL,
	Attribute5 datetime NULL,
	Attribute6 datetime NULL,
	Attribute7 varchar(50) NOT NULL,
	Attribute8 nvarchar(50) NULL,
	Attribute9 nvarchar(50) NULL,
	Attribute10 nvarchar(50) NULL,
	Attribute11 nvarchar(50) NULL

## Problem description

1. Expected behaviour: To connect with Azure SQL databse using managed service identity
2. Actual behaviour: ActiveDirectoryMSI is unspecified autheication type
3. Error message/stack trace:
Please find the attachment **StackTrace**
[StacTrace.txt](https://github.com/microsoft/mssql-jdbc/files/4862768/StacTrace.txt)

4. Any other details that can be helpful:
OpenLiberty startup logs
Launching defaultServer (Open Liberty 20.0.0.6/wlp-1.0.41.cl200620200528-0414) on Eclipse OpenJ9 VM, version 1.8.0_252-b09 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/install_apps_configuration_1491924271.xml
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/open-default-port.xml
[AUDIT   ] CWWKG0028A: Processing included configuration resource: /opt/ol/wlp/usr/servers/defaultServer/persistance.xml
[AUDIT   ] CWWKG0028A: Processing included configuration resource: /opt/ol/wlp/usr/servers/defaultServer/jndiRegistry.xml
[INFO    ] CWWKE0002I: The kernel started after 5.29 seconds
[INFO    ] CWWKF0007I: Feature update started.
**[WARNING ] CWWKG0032W: Unexpected value specified for property [authentication], value = [ActiveDirectoryMSI]. Expected value(s) are: [ActiveDirectoryIntegrated][ActiveDirectoryPassword][SqlPassword][NotSpecified].**

## Reproduction code
Code is been written in Open Liberty 20.0.0.6/wlp-1.0.41.cl200620200528-0414
Persistence.xml:
<server description="Sample Liberty server">

	<library id="MSJDBCLib">
		<fileset dir="${server.config.dir}/resources"
			includes="mssql-jdbc-8.2.2.jre8.jar" />
	</library>

	<jdbcDriver id="MSdriver" libraryRef="MSJDBCLib"
		 />
	<dataSource id="myDataSource"
		beginTranForResultSetScrollingAPIs="true"
		commitOrRollbackOnCleanup="rollback"
		isolationLevel="TRANSACTION_READ_COMMITTED"
		jndiName="<<dataSourceName>>" transactional="false"
		jdbcDriverRef="MSdriver">

	

		<properties.microsoft.sqlserver
			databaseName="<<DB_Name>>" serverName="<<ServerName>>"
			portNumber="<<PortNumber>>" encrypt="true" trustServerCertificate="false"
			hostNameInCertificate="<<CertificateDetails>>" loginTimeout="30"
			authentication="ActiveDirectoryMSI"
			msiClientId="<<MSIClientID>>"
			/>
	</dataSource>
</server>

**Comment by rene-ye** [comment]
Hi @sadafshaikh18, the error message and stack trace indicates the driver wasn't able to change authentication modes to ActiveDirectoryMSI, and attempted a password authentication with fields the user didn't provide. 8.2.2 version of the driver definitely supports the feature and we can confirm locally that there are no issues toggling the authentication mode on. Maybe your environment isn't picking up the correct version of the driver?

**Comment by sadafshaikh18** [comment]
Hi @rene-ye, Thank you for having a close look on the issue.
I have tried creating a data source separately, code snippet for the same is attached as 
[DataSourceSnippet.txt](https://github.com/microsoft/mssql-jdbc/files/4869489/DataSourceSnippet.txt)

Connectivity was established with this piece of code. So I think its not driver issue.
However, I wanted to check if someone has used this driver to create a pooled datasource  with authentication type as ActiveDirectoryMSI in any application server like olp, jboss etc

**Comment by peterbae** [comment]
Hi @sadafshaikh18, we took a look at this issue and it looks like the error message is coming from the [Open Liberty library](https://github.com/OpenLiberty/open-liberty/search?q=CWWKG0032W&unscoped_q=CWWKG0032W). Code [here](https://github.com/OpenLiberty/open-liberty/blob/e531636b09676e2d17ddd7a92419f780faf92b28/dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/metatype/metatype.xml) also shows that it doesn't support ActiveDirectoryMSI. I think you should redirect this issue to Open Liberty instead; let us know if you need anything else from our end.

**Comment by aguibert** [comment]
hi @peterbae, OpenLiberty developer here, your analysis sound correct and I've provided @sadafshaikh18 with a workaround on the OpenLiberty issue they raised.

Question for the SQLServer team:
I found documentation for the `ActiveDirectoryMSI` option [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver15) but the part I'm unsure of is whether or not this effects connection pooling/reuse? If not, we can simply add the option. If it does, we may need to do some additional work to cope with this in the OpenLiberty connection pool layer.

**Comment by peterbae** [comment]
It doesn't affect connection pooling as the connection is made once with the access token and the token doesn't need to be refreshed as long as the underlying connection is alive.

**Comment by peterbae** [comment]
Closing issue as it looks like this is not an issue with the driver. Let us know if you have any other questions.

**Comment by prawanpandey** [comment]
Facing this error while authenticating Azure Sql using authentication -ActiveDirectoryMSI
com.microsoft.sqlserver.jdbc.SQLServerException: Cannot use "Authentication=ActiveDirectoryMSI" with "User", "UserName" or "Password" connection string keywords.

JDBC Connection String - 
jdbc:sqlserver://xyz.database.windows.net:1433;database=hive;encrypt=false;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;authentication=ActiveDirectoryMSI;msiClientId=62adc8e3-3c56-42d9-8e3b-dc34171c27ca;

**Comment by Jeffery-Wasty** [comment]
Hi @prawanpandey,

Please create a new issue with the above information. This helps us keep issues separated. Thank you.
