### ISSUE TITLE
[FEATURE REQUEST] Accept connected sockets from custom socket factory

### ISSUE THREAD

**Issue by shubha-rajan** [microsoft/mssql-jdbc#1382]
## Is your feature request related to a problem? If so, please give a short summary of the problem and how the feature would resolve it
Currently, when using a custom socket factory that returns a connected socket, a `SocketException` is thrown because the `getConnectedSocket` method in `IOBuffer.java` will attempt to connect without checking whether the socket is already connected.

## Describe the preferred solution
Check whether a socket is connected before attempting to connect to it in `getConnectedSocket`. [See the corresponding code in the Postgres JDBC driver for reference](https://github.com/pgjdbc/pgjdbc/commit/f75572beb8b59a7a73f6e1d12d692b483dc04c85#diff-246d739711996f06a799a6dc8ad2ba9ehttps://github.com/pgjdbc/pgjdbc/commit/f75572beb8b59a7a73f6e1d12d692b483dc04c85#diff-246d739711996f06a799a6dc8ad2ba9e)

## Additional context
This small change would allow for compatibility with the Cloud SQL JDBC Socket Factory.

**Comment by peterbae** [comment]
Hi @shubha-rajan, thanks for the suggestion. The fix looks simple, and we will test the changes and make a PR if no issues are found.

**Comment by shubha-rajan** [comment]
> Hi @shubha-rajan, thanks for the suggestion. The fix looks simple, and we will test the changes and make a PR if no issues are found.

Thank you!

**Comment by peterbae** [comment]
Hi @shubha-rajan, sorry for the delay. We were busy working on the RTW and HotFix for our driver, and I will create a PR for this issue soon.

**Comment by peterbae** [comment]
I've created PR #1420 that addresses this issue. I've attached a zip file that contains this change - could you test it out and let me know if it works as intended @shubha-rajan?

[github-1382.zip](https://github.com/microsoft/mssql-jdbc/files/5158128/github-1382.zip)

**Comment by shubha-rajan** [comment]
> I've created PR #1420 that addresses this issue. I've attached a zip file that contains this change - could you test it out and let me know if it works as intended @shubha-rajan?
> 
> [github-1382.zip](https://github.com/microsoft/mssql-jdbc/files/5158128/github-1382.zip)

Just tested it and it works!
