### ISSUE TITLE
[QUESTION] Value is truncated to four decimal places when calling stored procedure using DECIMAL type

### ISSUE THREAD

**Issue by thecesrom** [microsoft/mssql-jdbc#1389]
## Question
I have a table where one column is of type DECIMAL(15, 8), and when I call the stored procedure that inserts data into that table I set the parameter type as DECIMAL but the value gets truncated to only four decimal places.

value = 0.00060606
inserted value = 0.0006

But when I set the parameter type to FLOAT it inserts the whole value.

value = 0.00060606
inserted value = 0.00060606

On the other hand, I set up a test using the same application and connecting to a MySQL database. Calling the Stored Procedure on MySQL using DECIMAL or FLOAT insert the value as expected, i.e. it's not truncating the value.

I am using the latest drivers for all DBs.

MSSQL: mssql-jdbc-8.2.2.jre11.jar
MySQL: mysql-connector-java-8.0.21.jar

I have opened a case with the vendor for the app I am using, but I wanted to also ask this question over here in case someone has ran into the same issue.

Thanks

**Comment by ulvii** [comment]
Hi @thecesrom ,
Does the same issue happen when using SSMS? Would you be able to provide a vanilla JDBC repro code, your stored procedure and table schema?

**Comment by thecesrom** [comment]
Hello @ulvii.

When calling the stored procedure using SSMS it does insert the full value.

The app I am using wraps Java calls from their own API, so I won't be able to share that code, but attached you'll find the scripts for the table and stored procedure [uploaded here](https://github.com/microsoft/mssql-jdbc/files/4949225/Script_637308385632087512.txt).

SQL query example:

```sql
DECLARE @RC INT
DECLARE @val DECIMAL(15, 8)
DECLARE @src VARCHAR(50)
DECLARE @ignition VARCHAR(50)

-- TODO: Set parameter values here.
SET @val = 0.00060606
SET @src = 'Azure Data Studio'

EXECUTE @RC = [dbo].[decimal_test_insert] @val,
    @src
GO



```
Result:
```
val                                     src
--------------------------------------- --------------------------------------------------
0.00060000                              execSProcCall - DECIMAL (API Call)
0.00060606                              execSProcCall - FLOAT (API Call)
0.00060606                              Azure Data Studio
0.00060606                              Microsoft SQL Server Management Studio 17

```
As I mentioned, I have opened a ticket with them, but I wanted to post this question over here in case I get a quicker response using this forum.

Thanks!

**Comment by peterbae** [comment]
Thanks. The team will look into this and get to you with our investigation results.

**Comment by thecesrom** [comment]
I have added a method to test inserting a decimal value using [this project](https://github.com/garystafford/mssql-sp-java-jdbc/) as baseline, and the results point that there is no problem with the JDBC driver.

This is the code I added to the `Examples.java`:
```java
public void insertDecimal() {
    CallableStatement cstmt = null;
    try {
        cstmt = connection.getConnection().prepareCall("{call dbo.decimal_test_insert(?, ?)}");
        cstmt.setBigDecimal("val", new BigDecimal("0.00069606"));
        cstmt.setString("src", "IntelliJ IDEA");
        cstmt.execute();
    } catch (Exception ex) {
        Logger.getLogger(RunExamples.class.getName()).
                log(Level.SEVERE, null, ex);
    } finally {
        if (cstmt != null) {
            try {
                cstmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(RunExamples.class.getName()).
                        log(Level.WARNING, null, ex);
            }
        }
    }
}
```

This is what I get on the table:
```
val                                     src
--------------------------------------- --------------------------------------------------
0.00069606                              IntelliJ IDEA
```

So I guess that the value is being modified by the application I am using.

Thanks for your support.
