### ISSUE TITLE
Add IOException as a cause of SQLServerException

### ISSUE THREAD

**Issue by aharbunou** [Microsoft/mssql-jdbc#139]
Hi, 
I have one comment for error handling in case of IOException. Is it possible to add the exception (SocketTimeoutException for example) to SQLServerException as a cause? We want to separate database timeouts from the rest of errors from SQL Server i.e. we need cause of SQLServerException. I will be very appreciated if you could implement this.
Thanks,
Andrei

**Comment by v-xiangs** [comment]
@aharbunou Hello. We are very glad to give help. Before we get started, we just want to clarify with you, do you want to add only SocketTimeoutException to SQLServerException  as a cause? or all kinds of timeout exceptions (socket timeout, login timeout, etc.) as cause? or all SQLServerExceptions have a cause? Thank you.

**Comment by aharbunou** [comment]
Hi @v-xiangs. Ideally, I would like to have cause of SQLServerException exception at any place where it possible. SocketTimeoutException is something that must have for me :) 
Thanks,
Andrei

**Comment by v-xiangs** [comment]
@aharbunou Thank you for confirming with us. It will require a lot of work for all the SQLServerException exceptions to have causes. Also, we need plenty of time to test them. For now, we will create a PR to add SocketTimeoutException as cause to meet your needs. And we will leave the issue open and work on adding causes to all SQLServerException exceptions. Thank you.

**Comment by v-xiangs** [comment]
hello @aharbunou , we created a PR to add causes to all SQLServerException exceptions. If you have time, could you please check if it meets your needs?

**Comment by aharbunou** [comment]
Hi @v-xiangs. Everything looks good for me. It is enough to improve my current error handling. I will create ticket If I need something else :) Thank you for all your work! I really appreciate it!

**Comment by v-xiangs** [comment]
@aharbunou We are glad to know it meets your needs. I am closing this issue and you are very welcome to create new tickets.
