### ISSUE TITLE
[FEATURE REQUEST] Update JDBC driver to use MSAL libraries for authentication with SQL.

### ISSUE THREAD

**Issue by jschrap** [microsoft/mssql-jdbc#1397]
We've received a recommendation to switch from ADAL libraries for authentication, to MSAL libraries. So we're going to do that.

On closer inspection, a scenario is that we use SQL server JDBC driver from Microsoft to connect to DB using AAD authentication. This JDBC driver internally uses ADAL. The latest version of JDBC driver from Microsoft is still using ADAL. When is MS planning to migrate their JDBC driver to use MSAL instead of ADAL?

See also: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-migration "Starting June 30th, 2020, we will no longer add new features to ADAL. We'll continue adding critical security fixes to ADAL until June 30th, 2022."

**Comment by ulvii** [comment]
Hi @jschrap ,

There is already PR #1375  which contains the ongoing work for the migration. Please stay tuned.

**Comment by ulvii** [comment]
#1375 is merged and will be part of 9.1.0-preview release.
