### ISSUE TITLE
java.lang.Character is "UNKNOWN"??

### ISSUE THREAD

**Issue by kdekooter** [Microsoft/mssql-jdbc#140]
A parameter of type `java.lang.Character` is interpreted as `javaType` "OBJECT" and mapped to `jdbcType` "UNKNOWN" leading to an exception.

Of course this type should be mapped to `JDBCType.CHAR`.

**Comment by v-afrafi** [comment]
Hi @kdekooter . What is your table datatype and how are you trying to insert/retrieve from it? Could you provide us any sample code that causes the exception you are mentioning?  Thank you.

**Comment by kdekooter** [comment]
The table datatype is `CHAR(1)`. In my app I am using the Springframework's `NamedParameterJdbcTemplate` which ends up calling `com.microsoft.sqlserver.jdbc.DataTypes`.

**Comment by v-afrafi** [comment]
@kdekooter, I am still not able to reproduce an exception. 
For example, having table defined as 
create table sample (col1 char(1) )

NamedParameterJdbcTemplate namedParameterJdbcTemplate = new NamedParameterJdbcTemplate(dataSource);
 String sql = "INSERT INTO " + "[test].[dbo].[sample]" + " values (:name)" ;
MapSqlParameterSource s = new MapSqlParameterSource(); 
s.addValue("name", 1);
namedParameterJdbcTemplate.update(sql, s);

**Comment by kdekooter** [comment]
My issue arises when the parameter is of type `char` or `java.lang.Character`. In your code that would look like: 
```
s.addValue("name", '1');
```

**Comment by v-afrafi** [comment]
@kdekooter Thanks.  SQL Server Type char is mapped to Java type String. In your case, you need to use s.addValue("name", "1"), setting the type as String. 
Please take a look at this [link ](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-basic-data-types) for a complete list of data types mappings.

**Comment by kdekooter** [comment]
@v-afrafi you are absolutely right. I should have read the manual ;-) http://www.tutorialspoint.com/jdbc/jdbc-data-types.htm
