### ISSUE TITLE
[QUESTION] - Authenticate to MS-SQL 2016 using service account (or) AD Account

### ISSUE THREAD

**Issue by sandeep540** [microsoft/mssql-jdbc#1404]
I am trying to Login from Java (Open JDK 11 , Jdbc, Springboot) with the below JDBC Driver

```
<!-- https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc -->
<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>mssql-jdbc</artifactId>
    <version>8.4.0.jre11</version>
</dependency>
```

For security reason , our org will not create a sql username/password, but a AD service account like

**SOURCING/svcAdmin** (SOURCING is domain, svcAdmin is AD Account to login)

There are many forums, telling to use jtds - I am not so keen on using that, is it possible to use native ms-sql jdbc driver and connect, can you please help with an example?

**Comment by rene-ye** [comment]
Hi @sandeep540, I believe you're looking for integrated authentication? If so, we have some articles on MSDN that should help:

[Kerberos Integrated on Windows.](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-ver15)
[AAD Integrated for Azure.](https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver15)

**Comment by peterbae** [comment]
Did the documents help? I'll close the issue in due time if there's no more action required.

**Comment by sandeep540** [comment]
Yes, it helped for Azure - AAD, For Kerberos,  I got a help from StackOverflow

**Comment by peterbae** [comment]
Closing the issue due to no action required.
