### ISSUE TITLE
Add additional options to JDBC params for Service Principal Auth

### ISSUE THREAD

**Issue by ravikd744** [microsoft/mssql-jdbc#1410]
Currently, when using ADAL, we request the access token and attach it to the connection object, so we are required to include ADAL4J or ADAL (pylib) in every platform as an additional lib and request token. When moving to MSAL, is it possible to merge the access token request to the JDBC driver?

Replace "Access Token" param with 3 additional parameters:
.option("TenantID","")
.option("ClientID","")
.option("ClientSecret/Cert","KeyVaultKey/plain secret")

Add a new "ClientCredential" or "ServicePrincipalWithCert" and "ServicePrincipalWithSecret" authentication type.

Particularly, in databricks/spark platforms, when we create external table references to Azure SQL, since the driver does not service principal auth, we are forced to resort to SQL Auth.

This SQL connector from MS stable for apache spark, relies on the MSSQL JDBC driver.

CREATE TABLE $tableName
        USING com.microsoft.sqlserver.jdbc.spark
        OPTIONS (
          url "jdbc:sqlserver://$url",
          databaseName "$databaseName",
          dbtable "$tableName",
          user "$user",
          password "$password",
          loginTimeout "240"
        )

**Comment by peterbae** [comment]
Hi @ravikd744, thanks for letting us know. The team will look into adding service principle auth as a new type of authentication while migrating to MSAL.

**Comment by peterbae** [comment]
I looked into this a bit more and it looks like the driver already supports a way for the user to do service principal authentication, by setting `keyStoreAuthentication` property to `KeyVaultClientSecret`. Details can be found [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-always-encrypted-with-the-jdbc-driver?view=sql-server-ver15).

I also looked at the MSAL PR that's in progress, and we are already adding a way for the user to provide tenant ID along with client ID and key, and therefore we won't need to add a new authentication type for this. Let me know if you have any questions/concerns.

**Comment by peterbae** [comment]
Correction, the driver doesn't have the AAD service principal authentication for connecting to DBs yet, the above link is for authenticating to AKV. Service principal auth is planned for development in this semester, and the work will likely begin soon after MSAL migration is completed. I will leave this issue open for reference.

**Comment by roehrijn** [comment]
Hi guys, we're also facing the need of service principal auth with client credentials. That's why we're running a modified JDBC driver version of yours. Don't know whether this might be of interest for you or not, here is how I did it. It is a very small change. I know that the hardcoded authority is definitely not possible in a general available driver version, however I think this can be solved easily. 

```diff
diff --git a/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerADAL4JUtils.java b/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerADAL4JUtils.java
index a94ca3cc..57acde1a 100644
--- a/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerADAL4JUtils.java
+++ b/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerADAL4JUtils.java
@@ -8,6 +8,7 @@ package com.microsoft.sqlserver.jdbc;
 import java.io.IOException;
 import java.net.MalformedURLException;
 import java.text.MessageFormat;
+import java.util.Date;
 import java.util.concurrent.ExecutionException;
 import java.util.concurrent.ExecutorService;
 import java.util.concurrent.Executors;
@@ -19,6 +20,7 @@ import javax.security.auth.kerberos.KerberosPrincipal;
 import com.microsoft.aad.adal4j.AuthenticationContext;
 import com.microsoft.aad.adal4j.AuthenticationException;
 import com.microsoft.aad.adal4j.AuthenticationResult;
+import com.microsoft.aad.adal4j.ClientCredential;
 import com.microsoft.sqlserver.jdbc.SQLServerConnection.ActiveDirectoryAuthentication;
 import com.microsoft.sqlserver.jdbc.SQLServerConnection.SqlFedAuthInfo;

@@ -30,11 +32,12 @@ class SQLServerADAL4JUtils {

     static SqlFedAuthToken getSqlFedAuthToken(SqlFedAuthInfo fedAuthInfo, String user, String password,
             String authenticationString) throws SQLServerException {
+
         ExecutorService executorService = Executors.newFixedThreadPool(1);
         try {
-            AuthenticationContext context = new AuthenticationContext(fedAuthInfo.stsurl, false, executorService);
-            Future<AuthenticationResult> future = context.acquireToken(fedAuthInfo.spn,
-                    ActiveDirectoryAuthentication.JDBC_FEDAUTH_CLIENT_ID, user, password, null);
+            String authority = "https://login.microsoftonline.com/<our-tenant-id>/";
+            AuthenticationContext context = new AuthenticationContext(authority, false, executorService);
+            Future<AuthenticationResult> future = context.acquireToken(fedAuthInfo.spn, new ClientCredential(user, password), null);

             AuthenticationResult authenticationResult = future.get();



```

**Comment by ulvii** [comment]
Thanks for the details @roehrijn . We will try to include support for Service Principal Authentication in the next production release.
