### ISSUE TITLE
Assistance doing simple password authentication against a domain account from non-member system

### ISSUE THREAD

**Issue by nneul** [microsoft/mssql-jdbc#1419]
## Question
I'm using this with DBeaver client (and also seeing similar problem from mssql-scripter tool).

From Perl DBD and tsql clients I am able to authenticate with "SHORTDOMAIN\userid" and password, with no special actions taken. This is from a non-domain-joined system - i.e. I'm not authenticating with kerberos -- just userid and password. 

From the dbeaver UI using mssql-jdbc, I have not been able to find any combination of settings to allow this authentication to work. I also have the same issue connecting with mssql-scripter utility, though that is python based. 

The usual response error is just a login failure. If this weren't working from other clients like the perl and freetds tsql command line client, I'd point it at server configuration -- but it's clearly working from other tools. Is there something I need to do to get this to work? 

Example:

```
root@itapps-d1:~ $ tsql -H HOSTNAME -U DOMAIN\\userid -D DBNAME -p 1433
Password: 
locale is "LC_CTYPE=C.UTF-8;LC_NUMERIC=en_US.UTF-8;LC_TIME=en_US.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=en_US.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=en_US.UTF-8;LC_NAME=en_US.UTF-8;LC_ADDRESS=en_US.UTF-8;LC_TELEPHONE=en_US.UTF-8;LC_MEASUREMENT=en_US.UTF-8;LC_IDENTIFICATION=en_US.UTF-8"
locale charset is "UTF-8"
using default charset "UTF-8"
Setting DBNAME as default database in login packet
1> 
```

I'm happy to run with a test build/etc. if it helps to diagnose.

**Comment by rene-ye** [comment]
Hi nneul, what version of the JDBC driver are you using? And what version JDK? Is your client a Windows or Linux OS. What version SQL Server are you using, is it SQL Server Linux or no? What type of authentication are you trying to accomplish here, does Windows Integrated not work?

**Comment by nneul** [comment]
Most recent test was with plugin 8.2.0-jre8, but I can drop in newer if needed to reproduce.  DBeaver embeds 1.8.0_252.

SQL Server Authentication - login failed
Windows Authentication - not option since unjoined linux box, fields all gray
NTLM - login is from an untrusted domain
Active Directory - Password - Login failed for user
Active Directory - MSI - pw prompt is grayed out
Active Directory - Integrated - pw and user prompt grayed out
Kerberos - not domain joined, cannot use
Custom - logon failed for user


Client on Linux (ub18 and ub20). I am able to use the 'Windows Authentication' from windows clients that are domain joined. 

Target SQL server version is 14.0.3281.6 on windows. 

I'm connecting from a non-domain member non-windows box, and my access to the target database (which is not under my control) is granted to a domain user. 

From a windows client I am able to use windows authentication with the plugin.

**Comment by nneul** [comment]
I have some other sql servers that are under my control that I could test with if needed, but the overall scenario would be the same - linux client, connecting to target server with an AD based userid+pw. 

Connecting with built-in sa account DOES work, but does not help this scenario.

**Comment by nneul** [comment]
Key thing with all of this - I can connect just fine with perl and tsql clients from linux - but not using the JDBC based client. So what's not clear to me is what they are doing different in how they pass the authentication information.

**Comment by rene-ye** [comment]
Did you have a read over this article: https://docs.microsoft.com/en-us/sql/connect/jdbc/using-ntlm-authentication-to-connect-to-sql-server?view=sql-server-ver15. Try specifying the domain name connection properties instead of providing it via 'Domain\User' format.
