### ISSUE TITLE
SQLServerPreparedStatement#setNull(idx, Types.OTHER) batch insert smalldatetime fail

### ISSUE THREAD

**Issue by it-sugar** [microsoft/mssql-jdbc#1427]
## Question
I have a table test and just one colume use smalldatetime
if insert batch
PreparedStatement preparedStatement = connection.prepareStatement("INSERT INTO test (column1) VALUES(?),(?)");
preparedStatement.setNull(1, JdbcType.OTHER.TYPE_CODE);
 preparedStatement.setNull(2, JdbcType.OTHER.TYPE_CODE); 
will insert 2 data success
but if use 
PreparedStatement preparedStatement = connection.prepareStatement("INSERT INTO test (column1) VALUES(?),(?)");
preparedStatement.setDate(1, new Date(System.currentTimeMillis()));
preparedStatement.setNull(2, JdbcType.OTHER.TYPE_CODE); 
it will throw SQLServerException Implicit conversion from data type varbinary to date is not allowed.
so it make me very confuse.

and if just insert one data,
INSERT INTO test (column1) VALUES(?)
both 
preparedStatement.setDate(1, new Date(System.currentTimeMillis()));
preparedStatement.setNull(1, JdbcType.OTHER.TYPE_CODE);
can execute success

## Relevant Issues and Pull Requests
as https://github.com/microsoft/mssql-jdbc/issues/1269
I use mybatis to insert data and find this issue and really can not understand this behavior

**Comment by rene-ye** [comment]
Hi @it-sugar, we'll take a look into this and get back to you.

**Comment by peterbae** [comment]
Hi @it-sugar, sorry for the delay in response. I contacted SQL Server team to ask about this problem, and the problem is occurring due to the implicit conversion that takes place when the user runs this SQL query (which is what the driver sends to the server from your Java code):

`exec sp_executesql N'INSERT INTO test (column1) VALUES (@P0),(@P1)',N'@P0 date, @P1 varbinary(8000)','2020-09-17',NULL`

And to quote the response from SQL Server team, for future reference:

```
This has to do with type derivation for SELECT …. UNION ALL… SELECT statement. Basically, the table value constructor (VALUES(@p0), (@p1) ) in the first INSERT statement gets translated to:

select @p0 union all select select @p1

In this case, since the types of @p0 and @p1 are different the type precedence rules come into play. Based on the type precedence rules, date has higher precedence than varbinary so the varbinary value will be converted to date but that will fail since that operation is not allowed. Note that this is an implicit conversion operation & implicit conversions from varbinary to any of the new date/time types are not allowed. You will get the same error if you do below:

select cast('2020-09-17' as date)
union all
select cast(NULL as varbinary(8000));

-- or
declare @d date = CAST(NULL as varbinary(8000));

The sp_executesql with 2 varbinary parameters is NOT the same as the first one because you are using smalldatetime instead of date for the type (@P0, @p1). Varbinary can be converted to smalldatetime/datetime implicitly since this is old SQL Server behavior. The new date/time types doesn’t allow such nonsensical operations & is more strict. So the insert with 2 varbinary is same as below which is fine and allowed for smalldatetime/datetime types:
```

As a workaround to this issue, you can either use SQLServerPreparedStatement.setSmallDateTime, change the table schema, change the query to insert one row at a time, or only insert Date/only insert Null per batch.

**Comment by it-sugar** [comment]
is there part of the response from SQL Server team is missing? I can understand  everything of response except the last line

**Comment by peterbae** [comment]
Sorry, I've edited my comment above with the rest of the response.

**Comment by it-sugar** [comment]
Thanks for your reply, @peterbae ! The incompatible implicit conversion create this issue, maybe I can specify this data type and use correct method to execute sql. Thanks a lot ~
