### ISSUE TITLE
[QUESTION] pdb link for DLLs for mssql-jdbc_auth returns 404 - CPP assert in sqljdbc_auth.dll 

### ISSUE THREAD

**Issue by notmaxx** [microsoft/mssql-jdbc#1429]
Hi, recently you posted here https://github.com/microsoft/mssql-jdbc/issues/907#issuecomment-565146447 that PDBs and DLLs are available for download. But PDB link returns 404

e.g.:
https://search.maven.org/artifact/com.microsoft.sqlserver/mssql-jdbc_auth/8.4.1.x64/dll - try to download PDB and you receive nginx 404
OR
here you see PDB in listing but when you click on link you receive 404
```
mssql-jdbc_auth-8.4.1.x64.dll                     2020-08-27 19:42    313840      
mssql-jdbc_auth-8.4.1.x64.dll.asc                 2020-08-27 19:42       499      
mssql-jdbc_auth-8.4.1.x64.dll.asc.md5             2020-08-27 19:42        32      
mssql-jdbc_auth-8.4.1.x64.dll.asc.sha1            2020-08-27 19:42        40      
mssql-jdbc_auth-8.4.1.x64.dll.md5                 2020-08-27 19:42        32      
mssql-jdbc_auth-8.4.1.x64.dll.sha1                2020-08-27 19:42        40      
mssql-jdbc_auth-8.4.1.x64.pdb                     2020-08-27 19:42   5591040      
mssql-jdbc_auth-8.4.1.x64.pdb.asc                 2020-08-27 19:42       499      
mssql-jdbc_auth-8.4.1.x64.pdb.asc.md5             2020-08-27 19:42        32      
mssql-jdbc_auth-8.4.1.x64.pdb.asc.sha1            2020-08-27 19:42        40      
mssql-jdbc_auth-8.4.1.x64.pdb.md5                 2020-08-27 19:42        32      
mssql-jdbc_auth-8.4.1.x64.pdb.sha1                2020-08-27 19:42        40      
mssql-jdbc_auth-8.4.1.x64.pom                     2020-08-27 19:42      1297      
mssql-jdbc_auth-8.4.1.x64.pom.asc                 2020-08-27 19:42       499      
mssql-jdbc_auth-8.4.1.x64.pom.asc.md5             2020-08-27 19:42        32      
mssql-jdbc_auth-8.4.1.x64.pom.asc.sha1            2020-08-27 19:42        40      
mssql-jdbc_auth-8.4.1.x64.pom.md5                 2020-08-27 19:42        32      
mssql-jdbc_auth-8.4.1.x64.pom.sha1                2020-08-27 19:42        40 
```

`https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc_auth/8.4.1.x64/mssql-jdbc_auth-8.4.1.x64.pdb` -> 404

**Comment by ulvii** [comment]
Hi @notmaxx ,
We decided .pdb files should not be released on Maven anymore and as of next production release we will be publishing symbols on Microsoft Symbol Server only, also making sure .pdb files do not contain any sensitive data. Apologies for inconvenience.

**Comment by notmaxx** [comment]
hi @ulvii we have pretty nasty production issue which I wanted to look into using PDBs, here is some screenshot

![image](https://user-images.githubusercontent.com/18590450/93401574-54ee1400-f837-11ea-963b-c7183a80a6e6.png)

how can we proceed with that? Should we open another ticket? It is pretty important for us - INCIDENT level

**Comment by ulvii** [comment]
Which version of the driver and DLL are you using? sqljdbc_auth.dll makes me think its an older version of the driver.

Please describe the issue a bit more. How did you start seeing the issue?

**Comment by notmaxx** [comment]
we can see this problem with different versions of driver, so far we tried:
- 7.4.1
- 8.4.1

We have Java program that connects to Azure MSSQL managed instance with WindowsFederation authn and sometimes receive this strange error that you saw on previous screenshots. We have suspicion that there is some timeout happens somewhere in the system. The problem is we do not receive any Exception in Java that we can catch and retry but instead there is assert in native CPP-code

When we run our program as windows service it prints this
![image](https://user-images.githubusercontent.com/18590450/93402381-75b76900-f839-11ea-886c-33d2ea6bcf42.png)

**Comment by ulvii** [comment]
I am attaching a .pdb file for you to be able to debug with 8.4.1 version of the driver. Please let me know how it goes.
[mssql-jdbc_auth-8.4.1.x64.zip](https://github.com/microsoft/mssql-jdbc/files/5235612/mssql-jdbc_auth-8.4.1.x64.zip)

**Comment by notmaxx** [comment]
@ulvii TL;DR looks like one of `ADAL*` function in `sni_fedauth.cpp` (inside of function `SNISecADALGetAccessToken`) returns error and expects `cbToken` (token length for https://github.com/microsoft/mssql-jdbc/blob/d1876fe28cb035a84661a5dc4f4c2e33fc1d1cd6/src/main/java/com/microsoft/sqlserver/jdbc/AuthenticationJNI.java#L11) to be zero but it is not zero so you throw `wassert`. Another option - function which calls `SNISecADALGetAccessToken` does similar check and throws similar `wassert`
