### ISSUE TITLE
Java/JDBC application crashes on assertion failure when using Windows integrated security

### ISSUE THREAD

**Issue by spn** [microsoft/mssql-jdbc#1433]
## Driver version
7.4.1, 8.4.1

## SQL Server version
Azure SQL Managed Instance

## Client Operating System
Windows Server 2016 amd64 10.0
## JAVA/JVM version
Oracle Corporation version 1.8.0_131 64-bit

## Problem description
Java application randomly crashes with assertion error when accessing Azure SQL Managed Instance using integrated authentication. The assertion error happens inside `sqljdbc_auth.dll` (for driver version 7.4.1). When upgrading the JDBC driver and DLL, the same assertion failure is shown for `mssql-jdbc_auth-8.4.1.x64.dll`.

The issue happens randomly, typically several times a day. It may depend on total volume of connections/queries being executed.

1. Expected behaviour:
No assertion failures.

2. Actual behaviour:
Assertion failure popup when running as command-line. Application crashes when running as Windows service.

3. Error message/stack trace:
No errors are reported from JDBC driver and no errors in log files.

Here is a screenshot of assertion popups:
![92528147-d99aca00-f25a-11ea-90df-71149fda4740](https://user-images.githubusercontent.com/550010/93495162-7d007480-f916-11ea-93f5-95b98b87d878.png)

4. Any other details that can be helpful:

We are using 64-bit Java 1.8 and SQL Server JDBC driver.

Client application is basically a multithreaded web server, each thread running SQL Server queries using JDBC driver. A new connection is opened for every query being run.

We are using Windows integrated security with `Authentication=ActiveDirectoryIntegrated` setting. The application is connecting to Azure SQL Server Managed Instance in a federated environment. There are no issues when connecting to on-prem SQL Server.

## JDBC trace logs

We are trying to get more information on this assertion: https://github.com/microsoft/mssql-jdbc/issues/1429

## Reproduction code
It's not easy to reproduce in a test application due to sporadic nature of this failure.

**Comment by notmaxx** [comment]
is `ADALGetAccessTokenForWindowsIntegrated` thread-safe or we need to put it under mutex/`synchronized` block?

**Comment by lilgreenbird** [comment]
hi @spn 

I've created jars with @notmaxx 's recommendation to make `ADALGetAccessTokenForWindowsIntegrated` synchronized can you give this a try to see if it resolves your issue? 

[github-1433.zip](https://github.com/microsoft/mssql-jdbc/files/5242602/github-1433.zip)


Otherwise, is it possible that you change to `Authentication=ActiveDirectoryIntegrated` for the time being so as to unblock you right now?

**Comment by lilgreenbird** [comment]
hi @spn 

have you had a chance to try this?

**Comment by spn** [comment]
@lilgreenbird We are running this driver in staging environment for a few days. No crashes were detected so far.

There were a couple of errors like this: `com.microsoft.sqlserver.jdbc.DLLException: The service is temporarily overloaded` but that seems unrelated, probably caused by Azure outage.

**Comment by spn** [comment]
hi @lilgreenbird I can confirm we had no crashes for more than a week with the driver build that you've provided.

We want to take this into production, because production system also suffers from the issue. If this fix works, can it be published as part of official release, to be considered "production-ready"?

**Comment by ulvii** [comment]
Hi @spn ,
Glad the change worked for you, we will definitely add it to the driver. The next preview release is scheduled for October 15th, the next production release is scheduled for January 31st 2021.

**Comment by ulvii** [comment]
#1441 merged.
