### ISSUE TITLE
[QUESTION] SQLServerBulkCopy JDBC driver - How reader works?

### ISSUE THREAD

**Issue by rayamoh** [microsoft/mssql-jdbc#1440]
Exploring SQLServerBulkCopy JDBC from Spring Batch to copy millions of records from Azure SQL to SQL server installed on Azure VM

Source is SQL view and Destination is SQL table

Batchsize = 250k and Count of records = 20Million

Question is related to reading from source. As batch size is 250K , it is not going to read entire 20Million into memory. But wondering how it works internally

1. Is it going to make 80 calls (20Million/250K) to source database?
2. If above one is true , how is it going to keep track of records read with out providing sort key in the code. Sample below or i 
  searched for other samples, no where i found sort key has to be given for batch size to work. Everywhere batchsize impacts 
  on writes to destination is mentioned but not on reads
3. Can streaming be enabled in above SQL server to SQL server scenario?

I searched a lot finding answer for 1 above, but could not find good information. Any insights is very helpful. Thanks!

https://docs.microsoft.com/en-us/sql/connect/jdbc/using-bulk-copy-with-the-jdbc-driver?view=sql-server-ver15

**Comment by ulvii** [comment]
Hi @rayamoh ,

BulkCopy API is not responsible for reading from the source database. It assumes the data to be copied is already fetched into a ResultSet or RowSet before attempting to send it to target database. In [this ](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-bulk-copy-with-the-jdbc-driver?view=sql-server-ver15#example)sample for example, the data is read into  `rsSourceData `  first. (`rsSourceData = stmt.executeQuery("SELECT ProductID, Name, ProductNumber FROM Production.Product");`) If loading all the data into memory is an issue, in your application you can split the source data into multiple result sets and use BulkCopy API to transfer each result set separately.

According to [documentation](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-bulk-copy-with-the-jdbc-driver?view=sql-server-ver15#sqlserverbulkcsvfilerecord), streaming is not supported. 

> Streaming of large data types such as varchar(max), varbinary(max), nvarchar(max), sqlxml, and ntext isn't supported.

**Comment by rayamoh** [comment]
Thanks @ulvii .  It clarifies my question. So for multiple result sets , is implementation going to be like below one?  W.r.t setFetchSize(chunksize) to read one chunk at a time , there will be multiple round trip calls to database; so wondering how it keeps track of last record read and fetch from next record as sort order of records is not guaranteed while fetching records from sql table or sql views? Please share insights.

Statement st = cn.prepareStatement("SELECT * FROM VIEW_FOO");

st.setFetchSize(10000);
ResultSet rs = st.executeQuery();
while (rs.next()) {
 Implement BULKCOPY
}

**Comment by ulvii** [comment]
The data will be inserted in whichever order it is in source ResultSet. If you are concerned about  sorting, the you should have an `ORDER BY` in your select statement, for example the query from the sample would become `(rsSourceData = stmt.executeQuery("SELECT ProductID, Name, ProductNumber FROM Production.Product ORDER BY ProductID");)`

**Comment by rayamoh** [comment]
But ResultSet may not hold entire 20Millions or so data in memory , so wondering what is recommended approach to do chunk reading to support SQLServerbulkcopy batchSize.  If setFetchSize(10000) is used , would bulkcopy trigger resultSet object to fetch next set of  records after it is done inserting current batch? Please let me know

**Comment by ulvii** [comment]
BulkCopy wouldn't trigger fetching next results. You would probably need to divide the data  using SQL queries, for example have select statement that loads the first 10000 rows into result set, copy that ResultSet to destination database, close the Resultset and execute another select statement that loads the next 10000  rows. Another option is to copy the data from source database into a CSV file and use BulkCopy to load CSV file into destination database.

**Comment by rayamoh** [comment]
Thanks. We implemented Chunk reading (reading one chunk at a time) and writer using BULK Insert. Working fine for us. Thanks for your insights
