### ISSUE TITLE
[QUESTION] Which MSSQL JDBC Driver is recommended?

### ISSUE THREAD

**Issue by chirangaalwis** [microsoft/mssql-jdbc#1448]
As a newbie to MSSQL, I encountered [this](https://mvnrepository.com/artifact/com.microsoft.sqlserver) list of JDBC drivers for MSSQL.

It was noticed that the packaged JARs under [this](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc) are OSGi supported bundles, while the rest seem to be non-OSGi JAR files.

Out of all these, seemingly the OSGi based artifacts are updated and maintained.

Appreciate if you can confirm whether using OSGi based drivers is the considered best practice. Also, appreciate if you could elaborate why there are multiple such connectors available.

**Comment by ulvii** [comment]
Hi @chirangaalwis ,
The official JDBC releases are on Maven Central, the other artifacts on  https://mvnrepository.com/  seem to come from different unofficial repositories. Please find the artifacts maintained by us [here](https://search.maven.org/artifact/com.microsoft.sqlserver/mssql-jdbc) and [here](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc) .

**Comment by chirangaalwis** [comment]
But @ulvii aren't the `Sqljdbc*` drivers been introduced under the Microsoft's official Maven repository?

**Comment by ulvii** [comment]
https://mvnrepository.com/  indexes lots of different repositories (1288 currently), we only publish and maintain artifacts for Maven Central repository. Sqljdbc* are not on Maven Central.

**Comment by ulvii** [comment]
Closing the issue, please let us know if you have any other questions.

**Comment by chirangaalwis** [comment]
+1 @ulvii thanks for the clarification.
