### ISSUE TITLE
Connection property "socketFactoryClass" doesn`t work

### ISSUE THREAD

**Issue by zxcvboy** [microsoft/mssql-jdbc#1455]
## Driver version
9.1.0.jre8-preview

## Client Operating System
Window 10

## JAVA/JVM version
Java SE-1.8
## Problem description
1. Expected behaviour:
   
   I followed [1217](https://github.com/microsoft/mssql-jdbc/pull/1217) and tried to use connection property "socketFactoryClass" to pass an invalid custom socket factory class. However this custom socket factory class was not adopted by driver manager, it still used default socket factory to create socket connection.  If this property worked, the error message shouldn`t look like this. 

2. Error message/stack trace:
com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host testdb, port 1433 has failed. Error: "testdb. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234)
	at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:285)
	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2462)
	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:668)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2363)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2214)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1275)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:861)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at test.Test.main(Test.java:21)

## Reproduction code

package test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Properties;

public class Test {

	public static void main(String[] args) {

            Connection con =null;
            String rtn="";
            String connectionUrl= "jdbc:sqlserver://testdb:1433;databaseName=LIFERAY_TEST";
            try{
                     Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    Properties props = new Properties();
                    System.out.println(InvalidSocketFactory.class.getName());
                    props.setProperty("socketFactoryClass", InvalidSocketFactory.class.getName());
                    props.setProperty("user", "MEHOLiferaySearch");
                    props.setProperty("password", "1qaz@WSX");
                   con = DriverManager.getConnection(connectionUrl,props);
                    if(con!=null)
                    {
                        rtn = "connect successfully";
                    }
            }
            catch (Exception e) {            
                e.printStackTrace();
            }
            finally
            {
                if(con!=null)
                {
                     try{
                          con.close();
                     }
                    catch (Exception e) {
                        e.printStackTrace();

                    }
                   
                }
            }
	}
}
class InvalidSocketFactory {}

**Comment by peterbae** [comment]
Hi @zxcvboy, I tried your reproduction code and I get the error below:

```
The class specified by the socketFactoryClass property must be assignable to javax.net.SocketFactory.
```

When I made the InvalidSocketFactory class extend SocketFactory and implemented the necessary classes from the abstract class, the connection worked. Could you try using the `DummySocketFactory` class example from `CustomSocketFactoryTest.java` test file and let me know if you can then see that this property is working?

**Comment by zxcvboy** [comment]
Hi. Peter. 
   
     I did it before. I have no idea why you can get this error. May I know what`s your java runtime and jdbc driver`s version? 

    Thanks a lot.

**Comment by peterbae** [comment]
I tried both Java 15 and Java 8, and the driver version was the latest.

**Comment by zxcvboy** [comment]
Hi. Peter. 

    Thanks for your help. 
    I have tried driver 8.4.1.jre8 & 9.1.0.jre8-preview but got same error message. InvalidSocketFactory  class was not adopted by driver as a custom socket factory.  This is really wired. I expected that I could get the same error message as yours. 
May I know what is your driver‵s version number? Did you use my codes to test it or use your codes? 

Thanks a lot.

**Comment by peterbae** [comment]
I used 9.1.0 driver and I used your codes.

**Comment by zxcvboy** [comment]
Hi. Peter. 
    After few testing, I found out why we got different error message. 
Did you change hostname from "testdb" to any hostname which your environment can recognize ? If I changed "testdb" to "localhost", I can get same error message as yours.  
It means that it does a DNS lookup first before create socket part. This is same issue as below. 
https://github.com/microsoft/mssql-jdbc/issues/1339


How can I prevent it doing a DNS lookup before connecting to the proxy?
The example "DummySocketFactory" only implemented creating proxy part but not DNS look up part.

Thanks a lot.

**Comment by peterbae** [comment]
Currently the driver doesn't allow you to not do a DNS lookup. You can do what was suggested as a workaround in [#1339](https://github.com/microsoft/mssql-jdbc/issues/1339), where you supply the proxy-resolved IP address as the hostname to the driver.

**Comment by zxcvboy** [comment]
Hi. Peter. 
    Thanks for your help. I have a workaround with this and I finished my scenario.

**Comment by peterbae** [comment]
Thanks, closing the issue.
