### ISSUE TITLE
[QUESTION]how to get sql at SQLServerPreparedStatement???

### ISSUE THREAD

**Issue by gstsgy** [microsoft/mssql-jdbc#1457]
## Relevant Issues and Pull Requests

SQLServerPreparedStatement sqlServerPreparedStatement = (SQLServerPreparedStatement)statement;
System.out.println("22222222222"+sqlServerPreparedStatement.toString());

22222222222SQLServerPreparedStatement:7

**Comment by gstsgy** [comment]
i want to get the last sql

**Comment by rene-ye** [comment]
Hi @gstsgy, there are no public APIs which would allow a user to retrieve the `userSql` variable currently in the PreparedStatement object. Considering the PreparedStatement must be prepared by the user by providing a SQL, it is unusual to have this request. If you're using a framework which obfuscates driver calls, perhaps there might be APIs there which would allow you to either retrieve the SQL or log what the framework is calling?

**Comment by gstsgy** [comment]
> Hi @gstsgy, there are no public APIs which would allow a user to retrieve the `userSql` variable currently in the PreparedStatement object. It is unusual to have such a need considering the PreparedStatement must first be prepared by providing a SQL string. If you're using a framework which obfuscates driver calls, perhaps there might be APIs in the framework which would allow you to either retrieve the last executed SQL or log what the framework is calling?

The MySQL's PreparedStatement is toString can get last sql ，but sqlserver is override toString 。

**Comment by rene-ye** [comment]
Hi @gstsgy, there is no JDBC specification that requires toString() to return the PreparedStatement's SQL. If you would like to see this added, please submit a feature request and the team will make a decision regarding if/when it'll be implemented in the upcoming semester(s).

**Comment by gstsgy** [comment]
> Hi @gstsgy, there is no JDBC specification that requires toString() to return the PreparedStatement's SQL. If you would like to see this added, please submit a feature request and the team will make a decision regarding if/when it'll be implemented in the upcoming semester(s).

thanks

**Comment by wfsgithub** [comment]
Hi, do you solve this problem? how to do ?

**Comment by gstsgy** [comment]
> Hi, do you solve this problem? how to do ?

rewrite source code

**Comment by gstsgy** [comment]
> Hi, do you solve this problem? how to do ?

重写源代码
