### ISSUE TITLE
Does the JDBC driver support login with the GMSA account?

### ISSUE THREAD

**Issue by Dantes-Lu** [microsoft/mssql-jdbc#1458]
## Driver version
8.2.0.jre8

## SQL Server version
SQL Server 2016 or above

## Client Operating System
Windows/Linux

## JAVA/JVM version
JDK 1.8

## Problem description
For security concern, in customer environment, the SQL Server is configured to use the GMSA account to manage username, password. I wonder if the GMSA is support or not in MS JDBC driver? If yes, what properties we should use in connection string?

**Comment by lilgreenbird** [comment]
hi @Dantes-Lu,
I will investigate and get back to you on this.

**Comment by Dantes-Lu** [comment]
Hi @lilgreenbird ,
I confirmed with my colleague, the SSMS can't login with the GMSA account. But I found there is a GSSCredential in kerosene. Can we use the default principle when create GSSName to use the platform OS credential for the authentication? You can consider we start the the JVM with the GSMA account.

**Comment by ulvii** [comment]
Hi @Dantes-Lu ,
You would need to fetch the default platform credential in your application and pass it to the driver:

```
GSSCredential credential = GSSManager.getInstance().createCredential(null, GSSCredential.DEFAULT_LIFETIME, new Oid("1.2.840.113554.1.2.2"), GSSCredential.ACCEPT_ONLY);
SQLServerDataSource ds = new SQLServerDataSource();
ds.setGSSCredentials(credential);
```

**Comment by Dantes-Lu** [comment]
Thanks all, I got enough information. Close this thread.
