### ISSUE TITLE
Closing a ResultSet early still fetches all remaining rows

### ISSUE THREAD

**Issue by danielbobbert** [microsoft/mssql-jdbc#1460]
## Driver version
<dependency>
  <groupId>com.microsoft.sqlserver</groupId>
  <artifactId>mssql-jdbc</artifactId>
  <version>8.4.1.jre8</version>
</dependency>

## SQL Server version
2016-SP2

## Client Operating System
Any

## JAVA/JVM version
Java 8

## Table schema

```
CREATE TABLE a (
  id nvarchar(36)
)

INSERT INTO a(id) VALUES('abc')
GO 1000000
```

## Problem description
We develop a tool that allows us to copy large tables from one (MS SQLServer) server to another server (using another database brand). We open a ResultSet by issuing a simple "SELECT * FROM a" on the source table, which may contain millions of rows. We then iterate over the ResultSet in a "while (r.next())" loop, pushing the row's values to a prepared "insert" statement which is then executed in batches.

Our tool has the ability to cancel the copy, which leads to a situation where we close the ResultSet on the source before having read all rows. We are seeing with the current driver, that ResultSet.close() takes very long (several minutes!). After some debugging we found, that the code spends its time in SQLServerResultSet.discardFetchBuffer().

Specifically, the code seems to execute lines 4238-4244:
```
try {
  while(true) {
    if (this.fetchBufferNext()) {
      continue;
    }
  }
}

```
to fetch all remaining rows in the ResultSet instead of simply aborting. So instead of simply closing the cursor (or whatever is used underneath), the whole table content seems to be read and transferred into our application (and discarded immediately).

1. Expected behavior:
When closing a ResultSet, that hasn't been fully iterated over yet, the ResultSet should *quickly* release all associated resources.

2. Actual behaviour:
ResultSet.close() seems to fetch all remaining rows. When the ResultSet contains millions of rows (and each row contains several columns) this takes very long (up to several minutes).

3. Error message/stack trace:
A thread dump shows, that the code is spending its time here:
  java.net.SocketInputStream.socketRead0(Native Method)
  java.net.SocketInputStream.socketRead(Unknown Source)
  java.net.SocketInputStream.read(Unknown Source)
  java.net.SocketInputStream.read(Unknown Source)
  com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2054)
  com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6643)
  com.microsoft.sqlserver.jdbc.TDSReader.nextPacket(IOBuffer.java:6546)
  com.microsoft.sqlserver.jdbc.TDSReader.ensurePayload(IOBuffer.java:6524)
  com.microsoft.sqlserver.jdbc.TDSReader.skip(IOBuffer.java:7174)
  com.microsoft.sqlserver.jdbc.ServerDTVImpl.skipValue(dtv.java:3362)
  com.microsoft.sqlserver.jdbc.DTV.skipValue(dtv.java:162)
  com.microsoft.sqlserver.jdbc.Column.skipValue(Column.java:152)
  com.microsoft.sqlserver.jdbc.SQLServerResultSet.skipColumns(SQLServerResultSet.java:216)
  com.microsoft.sqlserver.jdbc.SQLServerResultSet.discardCurrentRow(SQLServerResultSet.java:1712)
  com.microsoft.sqlserver.jdbc.SQLServerResultSet.fetchBufferNext(SQLServerResultSet.java:1765)
  com.microsoft.sqlserver.jdbc.SQLServerResultSet.discardFetchBuffer(SQLServerResultSet.java:5616)
  com.microsoft.sqlserver.jdbc.SQLServerResultSet.closeInternal(SQLServerResultSet.java:617)
  com.microsoft.sqlserver.jdbc.SQLServerResultSet.close(SQLServerResultSet.java:635)

4. Any other details that can be helpful:

## Reproduction code

```
Statement s = connection.createStatement();
ResultSet r = s.query("SELECT * FROM a");
r.next();
// the following line will hang while it fetches all remaining rows...
r.close();
```

**Comment by rene-ye** [comment]
Hi @danielbobbert, please have a read over #877. The gist of it is that what you're describing isn't possible by just calling the `close()` function. SQL Server is designed in a way where results from a query is buffered on the server side and it's mandatory for the client to process all of it before moving on.

**Comment by peterbae** [comment]
Closing as duplicate (of issue #877) / not an issue.
