### ISSUE TITLE
why i cannot establish connection with sql server

### ISSUE THREAD

**Issue by DSBRBrasil** [microsoft/mssql-jdbc#1462]
## Question
That's the error i've been get

The connection to the host localhost, named instance sqlexpress failed. Error: "java.net.SocketTimeoutException: Receive timed out". Verify the server and instance names and check that no firewall is blocking UDP traffic to port 1434.  For SQL Server 2005 or later, verify that the SQL Server Browser Service is running on the host.

**Comment by rene-ye** [comment]
Hi @DSBRBrasil, this seems to be a setup issue with your SQL Server. Please make sure you're able to connect to the server from SSMS. Also see if anything from this thread helps: https://social.msdn.microsoft.com/Forums/sqlserver/en-US/4e8a9c16-9a41-486d-a57a-78b90d7ccceb/jdbc-with-sql-express?forum=sqlexpress.

**Comment by lilgreenbird** [comment]
hi @DSBRBrasil ,

Do you have any updates are you able to connect via SSMS?

**Comment by DSBRBrasil** [comment]
Hi Guys,
It's was solved !!!!!  I was able setting the value port to 1433 
Follow the step by step
1) click start (windows) and search for **SQL Configuration Manager**
2) click on node tree on Configuration SQL Native
3) click on node tree on Protocol Client
4) click 2x on node tree on TCP/IP 
5) About the property **default Port** type it 1433 
6) Enable protocol to Yes
