### ISSUE TITLE
JDBC Connection failure with certain security providers

### ISSUE THREAD

**Issue by senthiltk** [microsoft/mssql-jdbc#1466]
## Driver version
6.3.2
8.4.1.jre8
## SQL Server version
Microsoft SQL Server 2012 (SP4) (KB4018073) - 11.0.7001.0 (X64) 
	Aug 15 2017 10:23:29 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

## Client Operating System
CentOs 7

## JAVA/JVM version
OpenJDK Runtime Environment (build 1.8.0_222-b10)

## Table schema
Not applicable.

## Problem description
When we initiate a JDBC connection, the connection fails after some time with the stack trace
```
FINE: *** SQLException:ConnectionID:1 ClientConnectionId: 03e92147-04b7-4f76-a663-7c4ac355fe0f com.microsoft.sqlserver.jdbc.SQLServerException: Connection reset ClientConnectionId:03e92147-04b7-4f76-a663-7c4ac355fe0f Connection reset ClientConnectionId:03e92147-04b7-4f76-a663-7c4ac355fe0f
Nov 25, 2020 9:33:58 PM com.microsoft.sqlserver.jdbc.SQLServerException logException
FINE: com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2658)com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:1972)com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6479)com.microsoft.sqlserver.jdbc.TDSReader.nextPacket(IOBuffer.java:6438)com.microsoft.sqlserver.jdbc.TDSReader.ensurePayload(IOBuffer.java:6416)com.microsoft.sqlserver.jdbc.TDSReader.readBytes(IOBuffer.java:6700)com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeInputStream.readInternal(IOBuffer.java:838)com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeInputStream.read(IOBuffer.java:826)com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1008)com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:990)com.cisco.ciscossl.provider.ciscojce.ssl.OpenSSLBIOInputStreamRawTLS$BackgroundReader.run(OpenSSLBIOInputStreamRawTLS.java:78)
```

We use encryption only for login with the jdbc connection.
On further debugging we found that this happens during SSLHandshake, when we use certain security providers. 
The security provider we use send a byte array of size 1024 to SSLHandshakeInputStream to fill. 
But the number of bytes in the TDS stream is less than 1024, but the code here assumes it has to fill all 1024 bytes and waits for the data from Socket, eventually it times out and throws the exception shown above.

The contract of InputStream https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#read(byte[]) if the size of byte array is more than the data available, is to fill the amount of data and return the length of the data filled. Its not happening in this case.

1. Expected behaviour: JDBC connection should be successful
2. Actual behaviour: JDBC Connection is failing.
3. Error message/stack trace:
4. Any other details that can be helpful:

**Comment by mprins** [comment]
please try to reproduce with a current version of the driver; 6.3.2 is really old and a preview release at that: https://github.com/microsoft/mssql-jdbc/releases/tag/v6.3.2

**Comment by senthiltk** [comment]
Tried with 8.4.1.jre8, same issue is seen.

**Comment by lilgreenbird** [comment]
hi @senthiltk ,

As mentioned can you please use the current driver release? As mentioned 6.3.2 is really old it was released in 2017. You can find the latest 8.4.1 driver [here](https://github.com/microsoft/mssql-jdbc/releases/tag/v8.4.1).

**Comment by lilgreenbird** [comment]
hi @senthiltk 

Connection reset could be triggered by the server side if it times out waiting for the client. From previous experience these are usually environment related and users have had success when they change some parameters. Please take a look at [issue 1127](https://github.com/microsoft/mssql-jdbc/issues/1127) and see if any of the suggestions resolve your issue?

**Comment by ulvii** [comment]
Hi @senthiltk ,
Which security provider are you using. Please also provide any other details that would help us reproduce the issue.

**Comment by peterbae** [comment]
Closing the issue due to inactivity, Feel free to open the issue again if you need any help.

**Comment by ashifahamed** [comment]
@peterbae  : Why did you close this issue.. I'm using jdbc driver 8.4.1 and my production servers are also getting the connection reset errors intermittently.
