### ISSUE TITLE
TDSWriter.writeReader high memory allocations

### ISSUE THREAD

**Issue by vyaslav** [microsoft/mssql-jdbc#1475]
## Driver version
8.4.1

## SQL Server version
15

## Client Operating System
Ubuntu 20

## JAVA/JVM version
11

## Table schema
N/A

## Problem description
There is alloc of char and byte arrays/buffers on every writeReader invocation:
https://github.com/microsoft/mssql-jdbc/blob/8c0d32ba4e3cac18e134699e861f52513a842123/src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java#L4099
We use SQLServerBulkCopy to write data from file to SQL Server and it yields few GiB/s of mem allocations. 
1. Expected behaviour:
char/byte buffer is created once per TDSWriter and reused on subsequent writes
2. Actual behaviour:
char and byte arrays/buffers on every writeReader invocation
3. Error message/stack trace:
4. Any other details that can be helpful:

## Reproduction code
Call SQLServerBulkCopy#writeToServer many times

**Comment by ulvii** [comment]
Hi @vyaslav ,
Thank you for the contribution. The team will review the PR and get back to you.
