### ISSUE TITLE
[QUESTION] why is the driver always throwing this error "The authenticationScheme NTLM is not valid." ?

### ISSUE THREAD

**Issue by 4bars** [microsoft/mssql-jdbc#1482]
## Question
I can't seem to figure out why the jdbc connector is always throwing 'The authenticationScheme NTLM is not valid'.

I can tell is is definitely failing here: https://github.com/microsoft/mssql-jdbc/blob/dev/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java#L245

But my connection string looks fine so I don't understand why it keeps moving into the last else statement.
        String connectionUrl = "jdbc:sqlserver://$myserver;integratedSecurity=true;authenticationScheme=NTLM;domain=$mydomain;user=$user;password=$password;"

Here is my OS and java version:

OS: Windows 10 Enterprise
openjdk version "1.8.0_242" 
OpenJDK Runtime Environment (build 1.8.0_242-b08) 
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

**Comment by rene-ye** [comment]
What version of the driver are you using? If you're using an older version of the driver before the NTLM implementation was added, then you'll get that error. Also check if any frameworks you're using is forcing an older version of the driver unbeknownst to you.

**Comment by 4bars** [comment]
@rene-ye  Wow, nice catch. I found the where the older driver was being used instead. Thank you.
