### ISSUE TITLE
[FEATURE REQUEST] Support Device Code OAuth Flow to login developers with MFA enabled accounts

### ISSUE THREAD

**Issue by mocleiri** [microsoft/mssql-jdbc#1483]
## Is your feature request related to a problem? If so, please give a short summary of the problem and how the feature would resolve it

Pull request #1456 added native support to the driver for token acquisition for service principals.  Previously it only supported using tokens acquired externally.

I would like to be able to use the device code flow so that I can login real users with MFA using the token based approach.

This would be used for developers running applications locally so that we can grant database access on their accounts which are protected by MFA which are normally unusable through the other login mechanisms.

## Describe the preferred solution

@ulvii integrate the code from my wrapper jdbc driver into the mssql driver for device code flow based authentication.

## Additional context

#1456 

## Reference Documentations/Specifications

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code

## Reference Implementation

Currently I am using a custom jdbc driver wrapper to pair the token acquisition logic to the current mssql jdbc driver.

Description on how to create a device code flow enabled app registration in Azure Active Directory:
https://github.com/mocleiri/device-code-sql-server-driver#device-code-flow

Code that uses the configured app registration to trigger the Device Code Flow Token Acquisition:
https://github.com/mocleiri/device-code-sql-server-driver/blob/master/src/main/java/device/code/sql/server/driver/DeveloperTokenSourceImpl.java#L57

The MFA enabled user needs to be granted permissions to MS SQL in azure or added into an Azure Security Group which has been granted access rights into the database.

The token acquisition and sending to Azure SQL Server or Azure SQL Server Managed Instance is just that an authentication request.  Authorization comes from setting up the group in SQL Server and then the user with MFA being in that group.

Refer to: https://stackoverflow.com/a/59188709/140424 and https://docs.microsoft.com/en-us/azure/azure-sql/database/authentication-aad-service-principal-tutorial#create-the-service-principal-user-in-azure-sql-database

**Comment by ulvii** [comment]
Hi @mocleiri ,
We recently added support for MFA in [9.1.1-preview release](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc). You would need to set `authentication=ActiveDirectoryInteractive` in connection string.

**Comment by mocleiri** [comment]
@ulvii thanks I missed that it was already covered.
