### ISSUE TITLE
Can I do batch insert into a temp table ?

### ISSUE THREAD

**Issue by meirmaor** [microsoft/mssql-jdbc#1492]
This is what I'm trying:

```
val createStmt= "create table #foobar(idx int)"
conn.setAutoCommit(false)
conn.prepareStatement(createStmt).execute()
val qInsert = "insert into #foobar values(?)"
val psInsert= conn.prepareStatement(qInsert)

psInsert.setInt(1,1)
psInsert.addBatch()
psInsert.executeBatch()
```

It tells me: Invalid object name '#foobar

Might be related to: https://github.com/microsoft/mssql-jdbc/issues/1131 
But I can't seem to workaround this.

**Comment by lilgreenbird** [comment]
hi @meirmaor,

As you mentioned this is the same as issue [1131](https://github.com/microsoft/mssql-jdbc/issues/1131) you need to make sure the application is accessing the temporary table in the same statement. Please see [example code](https://github.com/microsoft/mssql-jdbc/issues/1131#issuecomment-521788907) provided in that issue. So in your example, you would change qInsert to: 

`            String qInsert = "create table #foobar(idx int); insert into #foobar values(?)";
`

**Comment by meirmaor** [comment]
yes, but I actually have many values. 
I can't do it in one line. I want to loop and insert in batch. And then query the temp table(joined with something else).
Is not setting autocommit to false and using same connection sufficient. (I have this working against postgres and am trying to switch to sql server)

**Comment by lilgreenbird** [comment]
SQL Server temp tables are session based you can only access a temp table in the current session. If you change your code to create table in a Statement instead this would work too. i.e.

            String createStmt = "create table #foobar(idx int)";
            //PreparedStatement stmt = conn.prepareStatement(createStmt);
            //stmt.execute();
            Statement stmt = conn.createStatement();
            stmt.execute(createStmt);

            String qInsert = "insert into #foobar values(?)";
            PreparedStatement psInsert = conn.prepareStatement(qInsert);
            psInsert.setInt(1, 1);
            psInsert.addBatch();
            psInsert.executeBatch();

**Comment by meirmaor** [comment]
Thank you not using a prepared statement seems to work, yet the logic here escapes. Why does using a Prepared statement make the following statement not in the same session? or otherwise lose relevant context.
