### ISSUE TITLE
DatabaseMetaData getColumns failing for view?

### ISSUE THREAD

**Issue by EricRossC** [microsoft/mssql-jdbc#1493]
## Driver version
mssql-jdbc-8.4.1.jre8.jar and mssql-jdbc-9.1.1.jre8-preview.jar

## SQL Server version
Microsoft SQL Server 2005 - 9.00.4060.00 (Intel X86)   Mar 17 2011 13:20:38   Copyright (c) 1988-2005 Microsoft Corporation  Enterprise Edition on Windows NT 5.2 (Build 3790: Service Pack 2) 

## Client Operating System
CentOS release 6.7 (Final) and CentOS Linux release 8.2.2004 (Core)

## JAVA/JVM version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

## Table schema
dbo

## Problem description
I'm working with some code to get all the tables and views in the database, and for each one its columns and data types. We have the same code running against an Oracle, and it works, but against SQLServer it fails inside the getColumns method. 

The log says it's trying to use the sp_columns_100 procedure, but there's no such procedure.
 
1. Expected behaviour: List of columns for each table/view
2. Actual behaviour: NullPointerException 
3. Error message/stack trace:
    Exception inside connect(): java.lang.NullPointerException
java.lang.NullPointerException
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:61)
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:26)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.processExecuteResults(SQLServerStatement.java:1287)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.processResponse(SQLServerPreparedStatement.java:530)
        at com.microsoft.sqlserver.jdbc.TDSCommand.close(IOBuffer.java:7445)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.discardLastExecutionResults(SQLServerStatement.java:142)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.closeInternal(SQLServerStatement.java:653)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.closeInternal(SQLServerPreparedStatement.java:328)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.close(SQLServerStatement.java:668)
        at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getColumns(SQLServerDatabaseMetaData.java:661)
        at ListSIGDA.connect(ListSIGDA.java:54)
        at ListSIGDA.main(ListSIGDA.java:77)

4. Any other details that can be helpful:
sp_columns_100 doesn't exist.

## JDBC trace logs
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.Util parseUrl
DETALLADO: Property:serverName Value:x.y.x.z
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.Util parseUrl
DETALLADO: Property:portNumber Value:1433
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.Util parseUrl
DETALLADO: Property:databaseName Value:xxxxxx
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.Util parseUrl
DETALLADO: Property:sslProtocol Value:TLSv1.2
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.SQLServerConnection <init>
DETALLADO: ConnectionID:1 created by (SQLServerDriver:1)
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.SQLServerConnection login
DETALLADO: ConnectionID:1 This attempt server name: x.y.z.w port: 1433 InstanceName: null useParallel: false
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.SQLServerConnection login
DETALLADO: ConnectionID:1 This attempt endtime: 1608740188364
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.SQLServerConnection login
DETALLADO: ConnectionID:1 This attempt No: 0
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.SQLServerConnection connectHelper
DETALLADO: ConnectionID:1 Connecting with server: x.x.x.x port: 1433 Timeout slice: 1873 Timeout Full: 15
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.SQLServerConnection Prelogin
DETALLADO: ConnectionID:1 ClientConnectionId: 6d7dc970-40f8-4aee-be6a-357ddbbfc9c7 Server returned major version:9
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.TDSChannel enableSSL
ADVERTENCIA: TLSv1 was negotiated. Please update server and client to use TLSv1.2 at minimum.
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData <init>
DETALLADO:  SQLServerDatabaseMetaData:1 created by (ConnectionID:1 ClientConnectionId: 6d7dc970-40f8-4aee-be6a-357ddbbfc9c7)
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
DETALLADO: SQLServerCallableStatement:1 created by (ConnectionID:1 ClientConnectionId: 6d7dc970-40f8-4aee-be6a-357ddbbfc9c7)
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement buildExecSQLParams
DETALLADO: SQLServerCallableStatement:1: calling sp_executesql: SQL:EXEC sp_tables @P0, @P1, @P2, @P3
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.SQLServerResultSet <init>
DETALLADO: SQLServerResultSet:1 created by (SQLServerCallableStatement:1)
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
DETALLADO: SQLServerStatement:2 created by (ConnectionID:1 ClientConnectionId: 6d7dc970-40f8-4aee-be6a-357ddbbfc9c7)
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.SQLServerStatement doExecuteStatement
DETALLADO: SQLServerStatement:2 Executing (not server cursor) SELECT CAST(SERVERPROPERTY('EngineEdition') as INT)
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.SQLServerResultSet <init>
DETALLADO: SQLServerResultSet:2 created by (SQLServerStatement:2)
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
DETALLADO: SQLServerPreparedStatement:3 created by (ConnectionID:1 ClientConnectionId: 6d7dc970-40f8-4aee-be6a-357ddbbfc9c7)
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement buildExecSQLParams
DETALLADO: SQLServerPreparedStatement:3: calling sp_executesql: SQL:DECLARE @mssqljdbc_temp_sp_columns_result TABLE(TABLE_QUALIFIER SYSNAME, TABLE_OWNER SYSNAME,TABLE_NAME SYSNAME, COLUMN_NAME SYSNAME, DATA_TYPE SMALLINT, TYPE_NAME SYSNAME, PRECISION INT,LENGTH INT, SCALE SMALLINT, RADIX SMALLINT, NULLABLE SMALLINT, REMARKS VARCHAR(254), COLUMN_DEF NVARCHAR(4000),SQL_DATA_TYPE SMALLINT, SQL_DATETIME_SUB SMALLINT, CHAR_OCTET_LENGTH INT, ORDINAL_POSITION INT,IS_NULLABLE VARCHAR(254), SS_IS_SPARSE SMALLINT, SS_IS_COLUMN_SET SMALLINT, SS_IS_COMPUTED SMALLINT,SS_IS_IDENTITY SMALLINT, SS_UDT_CATALOG_NAME NVARCHAR(128), SS_UDT_SCHEMA_NAME NVARCHAR(128),SS_UDT_ASSEMBLY_TYPE_NAME NVARCHAR(max), SS_XML_SCHEMACOLLECTION_CATALOG_NAME NVARCHAR(128),SS_XML_SCHEMACOLLECTION_SCHEMA_NAME NVARCHAR(128), SS_XML_SCHEMACOLLECTION_NAME NVARCHAR(128),SS_DATA_TYPE TINYINT);INSERT INTO @mssqljdbc_temp_sp_columns_result EXEC sp_columns_100 @P0,@P1,@P2,@P3,@P4,@P5;SELECT TABLE_QUALIFIER AS TABLE_CAT, TABLE_OWNER AS TABLE_SCHEM, TABLE_NAME, COLUMN_NAME, DATA_TYPE,TYPE_NAME, PRECISION AS COLUMN_SIZE, LENGTH AS BUFFER_LENGTH, SCALE AS DECIMAL_DIGITS, RADIX AS NUM_PREC_RADIX,NULLABLE, REMARKS, COLUMN_DEF, SQL_DATA_TYPE, SQL_DATETIME_SUB, CHAR_OCTET_LENGTH, ORDINAL_POSITION, IS_NULLABLE,NULL AS SCOPE_CATALOG, NULL AS SCOPE_SCHEMA, NULL AS SCOPE_TABLE, SS_DATA_TYPE AS SOURCE_DATA_TYPE,CASE SS_IS_IDENTITY WHEN 0 THEN 'NO' WHEN 1 THEN 'YES' WHEN '' THEN '' END AS IS_AUTOINCREMENT,CASE SS_IS_COMPUTED WHEN 0 THEN 'NO' WHEN 1 THEN 'YES' WHEN '' THEN '' END AS IS_GENERATEDCOLUMN, SS_IS_SPARSE, SS_IS_COLUMN_SET, SS_UDT_CATALOG_NAME, SS_UDT_SCHEMA_NAME, SS_UDT_ASSEMBLY_TYPE_NAME,SS_XML_SCHEMACOLLECTION_CATALOG_NAME, SS_XML_SCHEMACOLLECTION_SCHEMA_NAME, SS_XML_SCHEMACOLLECTION_NAME FROM @mssqljdbc_temp_sp_columns_result ORDER BY TABLE_CAT, TABLE_SCHEM, TABLE_NAME, ORDINAL_POSITION;
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.SQLServerException logException
DETALLADO: *** SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: No se encontró el procedimiento almacenado 'sp_columns_100'. Msg 2812, Level 16, State 62, No se encontró el procedimiento almacenado 'sp_columns_100'.
dic 23, 2020 1:16:26 PM com.microsoft.sqlserver.jdbc.SQLServerResultSet <init>
DETALLADO: SQLServerResultSet:3 created by (SQLServerPreparedStatement:3)

## Reproduction code
import java.sql.*;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.*;

public class ListSIGDA
{
        public Connection connection;

        private static final String CONN_STR = "jdbc:sqlserver://x.y.z.w:1433;databaseName=Dbxxx;user=yyy;password=zzzzzz;sslProtocol=TLSv1.2";

        public void connect() throws Exception
        {
                String connectString;

                connectString = CONN_STR;

                System.out.println("Before DriverManager.getConnection");
                try {
                        connection = DriverManager.getConnection(connectString); //, CONN_U, CONN_P);
                        System.out.println("Connection established");

                        connection.setAutoCommit(false);

                        DatabaseMetaData metadata = connection.getMetaData();

                        ResultSet resultSet1 = metadata.getTables(null, null, null, new String[]{"TABLE", "VIEW"});
                        while(resultSet1.next()){
                                String tname = resultSet1.getString("TABLE_NAME");
                                String ttype = resultSet1.getString("TABLE_TYPE");

                                System.out.println(tname + " (" + ttype + ")");

                                ResultSet rsCols = metadata.getColumns(null, null, tname, "%"); // <- here

                                while (rsCols.next()) {
                                        String cName = rsCols.getString("COLUMN_NAME");
                                        String cType = rsCols.getString("TYPE_NAME");
                                        String cSize = rsCols.getString("COLUMN_SIZE");

                                        System.out.println("\t" + cName + " : " + cType + " " + cSize);
                                }
                        }
                } catch (Exception e) {
                        System.out.println("Exception inside connect(): " + e);
                        e.printStackTrace();
                }
        }
        public static void main(String[] args) throws Exception
        {
                Logger logger = Logger.getLogger("com.microsoft.sqlserver.jdbc");
                logger.setLevel(Level.FINE);

                FileHandler fh = new FileHandler("output.log");
                fh.setFormatter(new SimpleFormatter());
                logger.addHandler(fh);

                ListSIGDA client = new ListSIGDA();

                System.out.println("beginning");
                try {
                        client.connect();
                        System.out.println("after Connected");

                        client.connection.close();

                        System.out.println("after close");

                } catch (Exception e) {
                        try {
                                System.out.println("Exception : " + e);
                                client.connection.close();
                                e.printStackTrace();
                        } catch (Exception ex) {
                                System.out.println("Close Connection Exception : " + ex);
                                ex.printStackTrace();
                        }
                }
        }
}

**Comment by lilgreenbird** [comment]
hi @EricRossC ,

The Microsoft JDBC Driver for SQL Server version 8.4 only supports SQL Server 2008R2 and above for Windows 7 and above. Even the oldest driver version 1.2 will only support up to SQL Server 2008 I don't think it would be compatible with SQL Server 2005 and Windows NT.  I would recommend an upgrade since SQL Server 2005 had reached end of life since April, 2016. For more info, please see the [Microsoft JDBC Driver for SQL Server support matrix](https://docs.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix?view=sql-server-ver15).

**Comment by EricRossC** [comment]
Hi @lilgreenbird !

Thanks for the info! Sadly I'm sure there's no way to upgrade here, but I'll try the convince the people.
Best regards!

**Comment by matt-snider** [comment]
@EricRossC @lilgreenbird I don't think this is necessarily related to the version mismatch. I'm getting the same stack trace and I'm using driver version 10.2 running against MS SQL Server 2016. Is the`sp_columns_100` error actually related here? I could see that being called for `SQLServerDatabaseMetaData.getColumns`, but that would be a SQLException and not the NPE we see in the stack trace above.

Any insight into what might be causing this or how I can debug further?

**Comment by Jeffery-Wasty** [comment]
Hi @matt-snider,

Apologies we weren't able to see this earlier. If you're still having this issue, please open up a new issue, and we'll be able to address it from there.

**Comment by nathan-at-delphix** [comment]
We observed this stack several times as part of a single incident, while calling getColumns on a SQL Server 2016 database (13.0.7016.1) using driver version 8.4.1 (JRE8):

```
java.lang.NullPointerException: null 
at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:61) 
at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37) 
at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:26) 
at com.microsoft.sqlserver.jdbc.SQLServerStatement.processExecuteResults(SQLServerStatement.java:1287) 
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.processResponse(SQLServerPreparedStatement.java:530) 
at com.microsoft.sqlserver.jdbc.TDSCommand.close(IOBuffer.java:7445) 
at com.microsoft.sqlserver.jdbc.SQLServerStatement.discardLastExecutionResults(SQLServerStatement.java:142) 
at com.microsoft.sqlserver.jdbc.SQLServerStatement.closeInternal(SQLServerStatement.java:653) 
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.closeInternal(SQLServerPreparedStatement.java:328) 
at com.microsoft.sqlserver.jdbc.SQLServerStatement.close(SQLServerStatement.java:668) 
at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getColumns(SQLServerDatabaseMetaData.java:661) 
```

This occurred while connected to a database that had recently been dropped and re-attached using an older copy of the data files with a different schema. The stack didn't occur when calling the function on another database with an identical schema.

Unexpectedly, the error stopped occurring after we restarted the SQL Server instance that we were connecting to. It seems possible that NPE occurred due to bad or unexpected data from the SQL Server instance in response to the `sp_columns_100` call.

I know this issue is Closed, but I haven't raised a new issue because I've been unable to reproduce this behavior since, or gather any other data that might be helpful in troubleshooting the issue further.

**Comment by Jeffery-Wasty** [comment]
Hi @nathan-at-delphix,

If it does pop up again, let us know.
