### ISSUE TITLE
SQL_VARIANT's ID inconsistent with SQL Server's

### ISSUE THREAD

**Issue by julodiaz** [microsoft/mssql-jdbc#1495]
## Driver version
8.4.1

## SQL Server version
Microsoft SQL Server 2019 (RTM-CU8) (KB4577194) - 15.0.4073.23 (X64) 
	Sep 23 2020 16:03:08 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 18.04.5 LTS) <X64>

## Client Operating System
macOS Mojave (v 10.14.6), but DB runs inside Docker:
- Docker: 19.03.13, build 4484c46d9d
- SQL Server Image: mcr.microsoft.com/mssql/server:2019-lates

## JAVA/JVM version
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)

## Procedure Definition
`CREATE PROCEDURE [dbo].[ContactCustomField_Save_Dummy]
    @ContactID bigint,
    @Name varchar(50),
    @Value sql_variant
AS
Begin
    print 'this is a dummy stored procedure created for test purpose only'
END`

## Problem description
1. Expected behavior: Value passed to SP is properly converted to SQL_VARIANT in order to execute it.
2. Actual behavior: `The conversion from BIGINT to SMALLDATETIME is unsupported.`
3. Error message/stack trace:
```
com.microsoft.sqlserver.jdbc.SQLServerException: The conversion from BIGINT to SMALLDATETIME is unsupported.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:234)
	at com.microsoft.sqlserver.jdbc.DataTypes.throwConversionError(DataTypes.java:1112)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setObject(SQLServerPreparedStatement.java:1591)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setObject(SQLServerPreparedStatement.java:1510)
	at mssql.types.sqlvariant.TestConversion.executeSP(TestConversion.java:36)
	at mssql.types.sqlvariant.TestConversion.main(TestConversion.java:11)
```
4. Any other details that can be helpful:
It seems that somehow the class microsoft.sql.Types has another id for SQL_VARIANT or the DB is returning a wrong id for the type since when line 1510 of method **_setObject_** of class SQLServerPreparedStatement has reached the execution of JDBCType.of(jdbcType) it returns SMALLDATETIME.

So either the Types.java has a wrong id or the DB is wrongfully returning SMALLDATETIME's id for type SQL_VARIANT.

As a verification, if I execute the following SQL against the DB, the column DATA_TYPE for parameter @Value says -150:
```
EXEC sys.sp_sproc_columns @procedure_name = ContactCustomField_Save_Dummy
```

## JDBC trace logs
[JDBC_Trace_FINEST.log](https://github.com/microsoft/mssql-jdbc/files/5781659/JDBC_Trace_FINEST.log)

## Reproduction code
    public static final String JDBC_URL = "jdbc:sqlserver://localhost:1433;databaseName=<>;user=<>;password=<>";
    public static final String SP_CALL = "{ call dbo.ContactCustomField_Save_Dummy(?, ?, ?) }";

    public static void executeSP() {
        try (Connection connObj = DriverManager.getConnection(JDBC_URL)) {
            DatabaseMetaData metaData = connObj.getMetaData();
            ResultSet typeInfo = metaData.getTypeInfo();
            boolean iterate = true;
            Number sqlVariantId = null;

            while (typeInfo.next() && iterate) {
                Number dataType = typeInfo.getInt("DATA_TYPE");
                String typeName = typeInfo.getString("TYPE_NAME");

                if (typeName.equals("sql_variant") || typeName.equals("SQL_VARIANT")) {
                    iterate = false;
                    sqlVariantId = dataType;
                }
            }

            try (PreparedStatement statement = connObj
                    .prepareCall(SP_CALL, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY)) {
                statement.setObject(1, 10006962824L,-5);
                statement.setObject(2, "SomeString",12);
                assert sqlVariantId != null;
                statement.setObject(3, 10006962824L, sqlVariantId.intValue());
            }

        } catch (Exception sqlException) {
            sqlException.printStackTrace();
        }
    }

**Comment by peterbae** [comment]
Hi @julodiaz, thanks for contacting us. The team will look into this issue as soon as we can.

**Comment by lilgreenbird** [comment]
hi @julodiaz,

You should not be specifying the integer values of the SQLTypes directly like that as the mapping may be different in the driver. Instead please use java sql types or where it's not possible e.g. for SQL_VARIANT, the defined types in [Types.java](https://github.com/microsoft/mssql-jdbc/blob/dev/src/main/java/microsoft/sql/Types.java). i.e. your example:

            statement.setObject(1, 10006962824L, java.sql.Types.BIGINT);
            statement.setObject(2, "SomeString", java.sql.VARCHAR);
            statement.setObject(3, 10006962824L, microsoft.sql.Types.SQL_VARIANT);

**Comment by julodiaz** [comment]
Hi @lilgreenbird,

Ok, so just to confirm: is it known that a Microsoft SQL Type id can be different between the DB's metadata and the Driver?
If so, we could close this case.

By the way, is it documented that the right approach is this one and not to use the ids?

Thanks!

**Comment by lilgreenbird** [comment]
Yes the values are internal to the server so java.sql.Types should always be used unless the type does not exist that is why the driver defines them and maps to the server types.

I looked thru the docs did not find any samples of this. We have an upcoming release I will add this to the list of msdn doc updates.

Please close issue if you are satisfied with the solution. Thanks!

**Comment by julodiaz** [comment]
Cool, thanks for the brief!

Closing.
