### ISSUE TITLE
TimeoutTimer starts a new Thread for all queries with a query-timeout

### ISSUE THREAD

**Issue by fwi** [Microsoft/mssql-jdbc#150]
I think there is an opportunity to optimize the query-timeout function with relative ease.

In the ``TimeoutTimer`` class in ``IOBuffer`` I see on line 6800:

	timerThread = new Thread(this);

If I read the code correctly, this would mean that a call to
``SQLServerConnection.isValid(5)``
would start a new thread to facilitate the 5 second timeout function.
A call to ``isValid`` is executed often by connection pool implementations (with a timeout) and should be relatively cheap.

Creating and starting a new thread is a relatively expensive operation. 
This can be optimized using the ``ScheduledExecutorService``. Below a little bit of code to demonstrate.
One thing that needs special attention is the shutdown of the ``ScheduledExecutorService``: 
this must be done properly and timely to ensure there are no memory leaks when, for example, re-deploying web applications (war-files). I known this can be a bit tricky as other JDBC drivers have failed to do this properly and required work-arounds.

	package com.microsoft.sqlserver.jdbc;

	import org.junit.Assert;
	import org.junit.Test;

	import java.util.concurrent.ScheduledFuture;
	import java.util.concurrent.ScheduledThreadPoolExecutor;
	import java.util.concurrent.TimeUnit;
	import java.util.logging.Level;

	public class TimeoutTimerTest {

		@Test
		public void timeoutTest() {
			
			TdsTimeOutCommand cmd1 = new TdsTimeOutCommand("ttTest1");
			TimeoutTimerScheduled timer1 = new TimeoutTimerScheduled(1, cmd1);
			TdsTimeOutCommand cmd2 = new TdsTimeOutCommand("ttTest2");
			TimeoutTimerScheduled timer2 = new TimeoutTimerScheduled(2, cmd2);
			TimeoutTimerScheduled.prestart();
			try {
				timer1.start();
				timer2.start();
				// It appears it takes some time for timer-tasks to get scheduled:
				// this test will fail if sleep is set to 1001 milliseconds which, technically, should be enough.
				Thread.sleep(1500);
				Assert.assertNotNull("Command 1 interrupted.", cmd1.getInterruptReason());
				Assert.assertNull("Command 2 not interrupted.", cmd2.getInterruptReason());
				timer2.stop();
				Thread.sleep(1000);
				Assert.assertNull("Command 2 not interrupted after timer stopped.", cmd2.getInterruptReason());
			} catch (Exception e) {
				throw new AssertionError("Timeout test error.", e);
			} finally {
				TimeoutTimerScheduled.close();
			}
		}
		
		static class TdsTimeOutCommand extends TDSCommand {
			
			volatile String interruptReason;
			
			public TdsTimeOutCommand(String name) {
				super(name, 0);
			}

			@Override
			void interrupt(String reason) throws SQLServerException {
				interruptReason = reason;
				System.out.println(getLogContext() + " interrupted: " + reason);
			}

			@Override
			boolean doExecute() throws SQLServerException {
				return true;
			}
			
			public String getInterruptReason() {
				return interruptReason;
			}
			
		}
		
		// IOBuffer line 6800
		static class TimeoutTimerScheduled implements Runnable {
			
			private static final ScheduledThreadPoolExecutor tasks = new ScheduledThreadPoolExecutor(1);
			
			private final int timeoutSeconds;
			private final TDSCommand command;
			private volatile ScheduledFuture<?> task;
			
			TimeoutTimerScheduled(int timeoutSeconds,
					TDSCommand command) {
				assert timeoutSeconds > 0;
				assert null != command;

				this.timeoutSeconds = timeoutSeconds;
				this.command = command;
			}

			final void start() {
				
				task = tasks.schedule(this, timeoutSeconds, TimeUnit.SECONDS);
			}

			final void stop() {

				task.cancel(false);
			}

			@Override
			public void run() {
				
				// If the timer wasn't canceled before it ran out of
				// time then interrupt the registered command.
				try {
					command.interrupt(SQLServerException.getErrString("R_queryTimedOut"));
				}
				catch (SQLServerException e) {
					// Unfortunately, there's nothing we can do if we
					// fail to time out the request. There is no way
					// to report back what happened.
					command.log(Level.FINE, "Command could not be timed out. Reason: " + e.getMessage());
				}

			}

			public static void prestart() {
				tasks.prestartCoreThread();
			}

			public static void close() {
				tasks.shutdown();
			}
		}

	}

**Comment by v-nisidh** [comment]
@fwi Thanks for opening this issue.  After initial investigation we will update you on this.

**Comment by v-xiangs** [comment]
hello @fwi  , we have created a PR for this issue, please let us know what you think.

instead of using ScheduledThreadPoolExecutor#schedule() and delay the task, we decided to go with ExecutorService#execute() to start the task immediately and follow the rest of existing logic.

**Comment by fwi** [comment]
@v-xiangs I saw the PR, that was a quick response :) But unfortunately it still starts a thread for every query with a time-out (see also my comments in the PR https://github.com/Microsoft/mssql-jdbc/pull/162). The benefits will only start to show when a thread is not started (which is what a scheduled executor does: it registers a task for execution in a queue, it does not start the task and only executes the task after the time-out) AND one scheduled executor is re-used (at least within the life-time of one connection but preferably shared among all connections). I do not think the current PR improves the situation.

**Comment by v-xiangs** [comment]
closing this issue since PR #162 fixes it.
