### ISSUE TITLE
[QUESTION] HikariCP + SpringBoot 2 + mssql-jdbc driver configuration

### ISSUE THREAD

**Issue by pietrogalassi** [microsoft/mssql-jdbc#1503]
How to configure at best hikariCP + SpringBoot with mssql-jdbc driver ?
How to set cache prepared statement size?
What are other possible configuration ?

**Comment by rene-ye** [comment]
Hi @pietrogalassi, we don't directly support those frameworks, asking the owners of those products will yield better answers. As for prepared statement cache size, we have a connection property called `statementPoolingCacheSize` which should be what you're looking for. For the full list of connection properties, please refer to [our official docs](https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver15).

**Comment by pietrogalassi** [comment]
Perfect! So setting this in the url should be framework agnostic ?
jdbc:sqlserver:/server1;databaseName=DB1;statementPoolingCacheSize=250;disableStatementPooling=false

**Comment by rene-ye** [comment]
Yes that should work regardless of the framework, although it should be jdbc:sqlserver:// with 2 slashes.

**Comment by lilgreenbird** [comment]
close due to inactivity
