### ISSUE TITLE
[QUESTION] Connection Pool - How to find that a CallableStatement uses connection pool (specifically HikariCP)? SQL Profiler or PerfMon counters?

### ISSUE THREAD

**Issue by praskutti** [microsoft/mssql-jdbc#1513]
How to set up a profiler trace to find that my CallableStatement uses connection pool?
I set a trace to capture Audit:Login , Audit:Logout, RPC:Completed. But all I see is _1-Non-Pooled_ (image below)
Is there any configuration in Hikari/JDBC driver to get the pool to work? I would expect my second call to the service be _2-Pooled_ in profiler
Hikari configuration (I used both SQLServerDataSource and SQLServerConnectionPoolDataSource for datasourceclassname, both same result ):
```java
public HikariDataSource createHikariDataSource()  {
		HikariDataSource dbDatasource = new HikariDataSource();
		dbDatasource.setDataSourceClassName("com.microsoft.sqlserver.jdbc.SQLServerConnectionPoolDataSource");
		dbDatasource.addDataSourceProperty("databaseName", "tempdb");
		dbDatasource.setPoolName("myJDBCTestConnectionPool");
		dbDatasource.setUsername("someuser");
		dbDatasource.setPassword("totallysafepassword");
		dbDatasource.setMinimumIdle(5);
		dbDatasource.setMaximumPoolSize(10);
		dbDatasource.setConnectionTimeout(300);
		dbDatasource.setIdleTimeout(1000);
		dbDatasource.setMaxLifetime(1000);
		return dbDatasource;
    }
```

Proc execution code (redacted)
```java
public void execMyProc() {
	HikariDataSource hkds = createHikariDataSource();
	Connection conn = hkds.getConnection();
	CallableStatement stmt3 = conn.prepareCall({? = CALL dbo.connectionpooltest @InputParam1=?});
	stmt3.registerOutParameter(1,Types.INTEGER);
	stmt3.setInt(2,1);
	ResultSet rs1 = stmt3.executeQuery();
        rs1.close();
	conn.close();
}
```

HikariCP and mssql-jdbc maven pom.xml entries
```xml
<dependency>
	<groupId>com.zaxxer</groupId>
	<artifactId>HikariCP</artifactId>
	<version>3.4.5</version>
</dependency>
<dependency>
	<groupId>com.microsoft.sqlserver</groupId>
	<artifactId>mssql-jdbc</artifactId>
	<version>8.4.0.jre8</version>
</dependency>
```

SQL Code
```sql
use tempdb;
go
create or alter proc connectionpooltest (@InputParam1 int)
as
begin
	return @InputParam1;
end;
go
```

Profiler screenshot:

Java Version : 1.8.281 (Language level 11 or 8)
SQL Server 2017 Developer Edition (same behavior on 2014 and 2019)

Is there anyway to reliably say that my HikariCP configuration is using a pool ? How do I find it using profiler/prefmon/other tools?

**Comment by lilgreenbird** [comment]
hi @praskutti 

Although the mssql-jdbc driver should be compatible with Hikari pools we do not directly support it. Your questions relating to HikariCP are best directed to the HikariCP support team.

**Comment by praskutti** [comment]
@lilgreenbird , thanks for the response. Is there a list of directly supported connection pool libraries? Does JDBC directly support connection pooling (like ADO.NET SqlConnection) ?

**Comment by lilgreenbird** [comment]
the JDBC driver does support connection pool please see [Using connection pooling](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-connection-pooling?view=sql-server-ver15) for more info. You can also see tests for that in [PoolingTests.java](https://github.com/Microsoft/mssql-jdbc/blob/master/src/test/java/com/microsoft/sqlserver/jdbc/connection/PoolingTest.java).

**Comment by rene-ye** [comment]
Hi @praskutti, you can also try [turning on logging in the driver](https://docs.microsoft.com/en-us/sql/connect/jdbc/tracing-driver-operation?view=sql-server-ver15).

**Comment by praskutti** [comment]
@lilgreenbird  thank you, we went through it. I am unable to see the "2-Pooled" in the SQL Profiler. But I will dig further.
@rene-ye  , yeah, saw that! Thank you. I have asked my devs to check if we can enable logging for Hikari.

**Comment by ecki** [comment]
BTW a comment here, there was some confusion in the past because SQL Events (AuditLogoff and XEvent) shows if a connection pool is used or not. However it bases this decision only on the fact if the "reset session" (TDS 7.1 RESETCONNECTION flag) is used.

So if a pool uses normal "rollback" style resets it does not display as pooled even when it was.

**Comment by ecki** [comment]
I don’t think mssql-Jdbc offers a way to set this flag at all.. so most likely hikari can’t use it. But I haven’t checked the source. I only know that most pools won’t show up as pooled in the profiler for this reason (and that it is still pooled)


--
http://bernd.eckenfels.net
________________________________
Von: praskutti <notifications@github.com>
Gesendet: Tuesday, March 9, 2021 10:30:31 PM
An: microsoft/mssql-jdbc <mssql-jdbc@noreply.github.com>
Cc: Bernd <ecki@zusammenkunft.net>; Mention <mention@noreply.github.com>
Betreff: Re: [microsoft/mssql-jdbc] [QUESTION] Connection Pool - How to find that a CallableStatement uses connection pool (specifically HikariCP)? SQL Profiler or PerfMon counters? (#1513)


hi @ecki<https://github.com/ecki> , thanks for the valuable input. Do you how I can trace (or log) it for a HikariCP pool? is there anything in mssql-jdbc that would tell me that HikariCP sent this flag or not?

**Comment by praskutti** [comment]
@ecki , that is what i noticed too. The AuditLogout (and a subsequence sp_reset_connection) is **not** happening. But what i noticed was : Hikari creates a set of connections during startup (its is Spring based application). When I submit an API request, Hikari is using one among the connections it opened. I also do no see a AuditLogout after every calls, which makes me think that it uses the pooled connection

Query I used to get connection information:
``` sql
select dbname = DB_NAME(s.database_id), s.program_name, c.connection_id 
  , c.most_recent_sql_handle, c.connection_id,  s.logical_reads , c.last_read , c.last_write,  c.parent_connection_id
--, oa.*,  * , oa1.*
from sys.dm_exec_sessions s 
left join sys.dm_exec_connections C ON s.session_id = c.session_id
outer apply sys.dm_exec_query_plan(c.most_recent_sql_handle) oa
 outer APPLY sys.[dm_exec_sql_text](c.most_recent_sql_handle)  oa1
--left join sys.dm_exec_query_plan
where login_name like 'qa%' or login_name like '%dev_%'
```

**Comment by peterbae** [comment]
Closing the issue due to no actions required from the JDBC team. Please feel free to re-open if any other questions/problems arise.
