### ISSUE TITLE
sp_sqljdbc_xa_install and newer driver releases

### ISSUE THREAD

**Issue by TarasTielkes** [microsoft/mssql-jdbc#1514]
The "Understanding XA transactions" section in the Programming Guide notes that:

> The JDBC XA distributed transaction components are included in the SQL Server engine in SQL Server 2017 starting with cumulative update 16 and in SQL Server 2019, and can be enabled or disabled with a system stored procedure. To enable the required components to perform XA distributed transactions using the JDBC driver, execute the following stored procedure.
>
>EXEC sp_sqljdbc_xa_install
>
>To disable the previously installed components, execute the following stored procedure.
>
>EXEC sp_sqljdbc_xa_uninstall

However, the same section also notes that:
> The JDBC distributed transaction components are included in the xa directory of the JDBC driver installation. These components include the xa_install.sql and sqljdbc_xa.dll files. If you have different versions of the JDBC driver on different clients, it is recommended to use the newest sqljdbc_xa.dll on the server.

As such, I _assume_ that, even on these newer releases of MSSQL, a newer XA DLL matching the JDBC driver in use might need to be installed.

Questions:

1. Is the summary above correct? Specifically, is it recommended to install newer the XA DLL on MSSQL instances that already come with a "packaged" version, and support `sp_sqljdbc_xa_install`?
2. Which versions of the XA DLL are included in current 2017 and 2019 releases of MSSQL?
3. Is it possible to determine the version of the XA DLL in use by MSSQL, without requiring access to the server? If not, is this something you would consider adding (for instance, a stored procedure that returns the current XA DLL version information)?
4. What are the potential consequences of using older XA DLL versions in MSSQL in combination with more recent JDBC driver releases? In general, is there a stable API between the driver and the XA DLL?
5. What does `sp_sqljdbc_xa_install` actuall _do_? Is it copying a pre-packaged XA DLL into the MSSQL `Binn` directory, similar to the installation instructions in the JDBC driver distribution package?
6. Are there release notes available for the `sqljdbc_xa.dll` component over the release history of the driver?

**Comment by lilgreenbird** [comment]
hi @TarasTielkes 

As per [Understanding XA transactions](https://docs.microsoft.com/en-us/sql/connect/jdbc/understanding-xa-transactions?view=sql-server-ver15) the xa_install.sql it's just a script in plain text which contains sql commands:

>This script installs the extended stored procedures that are called by sqljdbc_xa.dll

It is always recommended to install the newest version of the DLL as per note:

>  Note
The JDBC distributed transaction components are included in the xa directory of the JDBC driver installation. These components include the xa_install.sql and sqljdbc_xa.dll files. If you have different versions of the JDBC driver on different clients, it is recommended to use the newest sqljdbc_xa.dll on the server.

There could be updates or fixes if any which will be listed in the driver release notes. Typically the XA DLL does not change much from release to release so there's a good chance that they **may** be compatible if you are using an old version but we recommend to always install the version that is packaged with the driver. Currently we do not include a version number in the sqljdbc_xa.dll but if you view the file properties you can see the date and version of the file.

**Comment by TarasTielkes** [comment]
Hi @lilgreenbird,

Question 5 above was not about the `xa_install.sql` script that is shipped in the `enu/xa/` directory of the driver package from the Microsoft site. That script is quite readable and well-commented. 

Rather, the question was regarding the `sp_sqljdbc_xa_install` stored procedure, which accoring to the linked article is "_included in the SQL Server engine in SQL Server 2017 starting with cumulative update 16 and in SQL Server 2019_". Does that script copy a pre-packaged version of `sqljdbc_xa.dll` into the MSSQL bin directory? Or is the DLL there in the referenced MSSQL releases to start with?

**Comment by lilgreenbird** [comment]
The sp_sqljdbc_xa_install/sp_sqljdbc_xa_uninstall stored procedures are not from the driver. They do not install/uninstall the DLL which is bundled in the driver. According to the doc this is to enable/disable XA distributed transactions:

>  Note
The JDBC XA distributed transaction components are included in the SQL Server engine in SQL Server 2017 starting with cumulative update 16 and in SQL Server 2019, and can be enabled or disabled with a system stored procedure. 

You can see the contents of the stored procedure if you are curious:
```
USE [master]
GO
/****** Object:  StoredProcedure [sys].[sp_sqljdbc_xa_install]    Script Date: 2/9/2021 3:41:21 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO

ALTER procedure [sys].[sp_sqljdbc_xa_install]
AS
    exec sys.sp_sqljdbc_xa_internal_remove

    --CREATE SYNONYM
    CREATE SYNONYM xp_sqljdbc_xa_init for sys.sp_xa_init
    CREATE SYNONYM xp_sqljdbc_xa_start for sys.sp_xa_start
    CREATE SYNONYM xp_sqljdbc_xa_end for sys.sp_xa_end
    CREATE SYNONYM xp_sqljdbc_xa_prepare for sys.sp_xa_prepare
    CREATE SYNONYM xp_sqljdbc_xa_commit for sys.sp_xa_commit
    CREATE SYNONYM xp_sqljdbc_xa_rollback for sys.sp_xa_rollback
    CREATE SYNONYM xp_sqljdbc_xa_forget for sys.sp_xa_forget
    CREATE SYNONYM xp_sqljdbc_xa_recover for sys.sp_xa_recover
    CREATE SYNONYM xp_sqljdbc_xa_rollback_ex for sys.sp_xa_rollback_ex
    CREATE SYNONYM xp_sqljdbc_xa_forget_ex for sys.sp_xa_forget_ex
    CREATE SYNONYM xp_sqljdbc_xa_prepare_ex for sys.sp_xa_prepare_ex
    CREATE SYNONYM xp_sqljdbc_xa_init_ex for sys.sp_xa_init_ex

    CREATE ROLE [SqlJDBCXAUser]

    -- Grant privileges to [SqlJDBCXAUser] role to the extended stored procedures.
    GRANT EXECUTE ON xp_sqljdbc_xa_init to [SqlJDBCXAUser]
    GRANT EXECUTE ON xp_sqljdbc_xa_start to [SqlJDBCXAUser]
    GRANT EXECUTE ON xp_sqljdbc_xa_end to [SqlJDBCXAUser]
    GRANT EXECUTE ON xp_sqljdbc_xa_prepare to [SqlJDBCXAUser]
    GRANT EXECUTE ON xp_sqljdbc_xa_commit to [SqlJDBCXAUser]
    GRANT EXECUTE ON xp_sqljdbc_xa_rollback to [SqlJDBCXAUser]
    GRANT EXECUTE ON xp_sqljdbc_xa_recover to [SqlJDBCXAUser]
    GRANT EXECUTE ON xp_sqljdbc_xa_forget to [SqlJDBCXAUser]
    GRANT EXECUTE ON xp_sqljdbc_xa_rollback_ex to [SqlJDBCXAUser]
    GRANT EXECUTE ON xp_sqljdbc_xa_forget_ex to [SqlJDBCXAUser]
    GRANT EXECUTE ON xp_sqljdbc_xa_prepare_ex to [SqlJDBCXAUser]
    GRANT EXECUTE ON xp_sqljdbc_xa_init_ex to [SqlJDBCXAUser]
```

You will need to copy the DLL from the driver release manually to the `Binn` folder as per the doc. Please follow the steps under 
[Configuring the JDBC distributed transaction components](https://docs.microsoft.com/en-us/sql/connect/jdbc/understanding-xa-transactions?view=sql-server-ver15#configuring-the-jdbc-distributed-transaction-components).

**Comment by vasek-cz** [comment]
> Hi @lilgreenbird,
> 
> Question 5 above was not about the `xa_install.sql` script that is shipped in the `enu/xa/` directory of the driver package from the Microsoft site. That script is quite readable and well-commented.
> 
> Rather, the question was regarding the `sp_sqljdbc_xa_install` stored procedure, which accoring to the linked article is "_included in the SQL Server engine in SQL Server 2017 starting with cumulative update 16 and in SQL Server 2019_". Does that script copy a pre-packaged version of `sqljdbc_xa.dll` into the MSSQL `Binn` directory? Or is the DLL there in the referenced MSSQL releases to start with?

Actually, is there any pre-packaged version of `sqljdbc_xa.dll` in SQL Server 2019 installer? If so, which component do I need to install for the DLL to be included? I was unable to find any resources about this being included in MSSQL installer and documentation isn't clear on this topic.

**Comment by TarasTielkes** [comment]
The linked "Configuring the JDBC distributed transaction components" page also contains the following section:
> Set the logging functionality as shown in the code example in the next section. Search for "Server XA DLL version:..." phrase in the output log file.

However, the only code section, at the end of the article, does not seem to be related to that comment.

**Comment by lilgreenbird** [comment]
@TarasTielkes I'm not sure what the confusion is that last step is to verify the version of DLL after the previous steps to copy

**Comment by lilgreenbird** [comment]
@vasek-cz As mentioned before the DLL is bundled with the Microsoft JDBC Driver for SQL Server. See [Configuring the JDBC distributed transaction components](https://docs.microsoft.com/en-us/sql/connect/jdbc/understanding-xa-transactions?view=sql-server-ver15#configuring-the-jdbc-distributed-transaction-components):

> 1. **Copy the new sqljdbc_xa.dll from the JDBC driver installation directory** to the Binn directory of every SQL Server computer that will participate in distributed transactions.

You can get the latest driver version and the DLL [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-ver15).

**Comment by lilgreenbird** [comment]
hi @TarasTielkes and @vasek-cz 

Sorry I just realized that I wasn't aware that starting **SQL Server 2017 CU16** the DLL from the driver is not required anymore the functionality is builtin and the **sp_sqljdbc_xa_install** stored procedure will enable them. So if you are using SQL Server 2017 CU16 and above you will not need to manually copy the DLL from the driver over as per instructions in the doc. I will make a note to word this more clearly in the documentation. Thanks!

**Comment by buuzta** [comment]
Hi @lilgreenbird 

I'm a bit puzzled. I've updated to SQL Server 2017 CU 23 (14.0.3381.3) but there is no sqljdbc_xa.dll. My application server mentioned that XA connections cannot be opened due to the missing DLL. I still have to manually copy it.
And running the SP only didn't worked as well. Inside the sqljdbc Zip file is an xa_install.sql to (re)create the neccessary XA procedures. After running that script everything worked as expected.

**Comment by TarasTielkes** [comment]
Hi @lilgreenbird,

Thank you for taking a second look.
	
The installation procedure for the XA integration library itself is clear and well-documented. It is _precisely_ the **SQL Server 2017 CU16** (and later) case for which the documentation could be improved.
	
In my understanding, there is a contradition between the following two statements:
> So if you are using SQL Server 2017 CU16 and above you will not need to manually copy the DLL from the driver over as per instructions in the doc

versus

> If you have different versions of the JDBC driver on different clients, it is recommended to use the newest sqljdbc_xa.dll on the server

I hope that my confusion is more clear now, and that my list of questions in the initial post makes more sense in that context.

**Comment by lilgreenbird** [comment]
hi @TarasTielkes 

Yes, thank you I will make a note to update the wording in the docs so it's more clear. So just to clarify again, the sdqljdbc_xa.dll is will no longer be necessary starting SQL Server 2017 CU16 as the functionality will be builtin eventually it will be deprecated. So your application will need to be updated if it's looking for the DLL.

**Comment by TarasTielkes** [comment]
Is there a changelog available for the MSSQL JDBC/XA integration library?

**Comment by David-Engel** [comment]
> Is there a changelog available for the MSSQL JDBC/XA integration library?

@TarasTielkes No. But there haven't been any changes to it since at least 2019, when the functionality was incorporated into SQL Server itself.

**Comment by dlmiles** [comment]
> hi [@TarasTielkes](https://github.com/TarasTielkes)
> 
> Yes, thank you I will make a note to update the wording in the docs so it's more clear. So just to clarify again, the sdqljdbc_xa.dll is no longer necessary starting SQL Server 2017 CU16 as the functionality will be builtin on server side eventually it will be deprecated. So your application will need to be updated if it's looking for the DLL.

It would be really good for the docs to clearly indicate a sequence of commands that can be used to prove the functionality is already built into the SQL Server from SSMS.  Like a manual  dummy transaction.

All versions of the JDBC driver I have looked at still provide the DLL, this seem strange if it is built into the SQL Server.  The current oldest supported SQL Server should have it built in, so what is the DLL being distributed for?  I also note the size of the DLL substantially decreased ~185KiB (9.4.1) to ~76KiB (13.4).  So claiming there has been no change in the driver/DLL in this area seems strange and just creating more confusion.

Re the OP question there was `SELECT * FROM sys.dm_os_loaded_modules` that historically has been able to confirm the DLL has been loaded.  However for a 2017 CU31 both 9.4.1 and 13.4 cause an access violation when trying to run an EXEC command to cause the DLL to be loaded to confirm it is setup.
