### ISSUE TITLE
ActiveDirectoryMSI  based connectionString in SQL Database Panel on AzurePortal

### ISSUE THREAD

**Issue by vnextcoder** [microsoft/mssql-jdbc#1516]
## Driver version

7.2
## SQL Server version

Microsoft SQL Azure (RTM) - 12.0.2000.8   Oct  1 2020 18:48:35   Copyright (C) 2019 Microsoft Corporation 
## Client Operating System

Web app service Linux Java 11 runtime. (Managed Service Identity)
## JAVA/JVM version

Java 11, Tomcat
## Table schema

dbo
## Problem description

1. Expected behaviour:
2. Actual behaviour:
3. Error message/stack trace:
4. Any other details that can be helpful:

## Reproduction code

Hi team

Please can you enable ActiveDirectoryMSI based connection string as well for JDBC Connection Strings in the azure Portal when SQL Database is being seen by the user.

Currently the ConnectionString panel for SQL Database lists out only Sql Auth, AD password based, AD Integrated examples. It would really help someone in future if an example is provided for ActiveDirectoryMSI as well as shown in Article https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver15  for Managed Identity based Connections

thank you

**Comment by lilgreenbird** [comment]
hi @vnextcoder 

This is the The Microsoft JDBC Driver for SQL Server driver team we are not responsible for the Azure Portal please contact the Azure team for any issues related to the portal. Please see [Create an Azure support request](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request).

**Comment by vnextcoder** [comment]
OK. got it.
