### ISSUE TITLE
[QUESTION] 9.2.1 release

### ISSUE THREAD

**Issue by sdebruyn** [microsoft/mssql-jdbc#1527]
## Question
What is the status of the 9.2.1 release? I see the branch has been created with the necessary changes. I think all is left is pushing it to Maven?

**Comment by peterbae** [comment]
Hi @sdebruyn, due to documentation delays from Microsoft's end, the release will happen tomorrow.

**Comment by peterbae** [comment]
9.2.1 Release is complete, closing the issue.
