### ISSUE TITLE
Connecting SqlServer from python using AD authentication and JavaKerberos

### ISSUE THREAD

**Issue by kvspreddy** [microsoft/mssql-jdbc#1528]
## Question
Getting below error while trying to connect sqlserver using python.

kinit -kt /tmp/tmp1/SampleUser.keytab SampleUser@domain.com
import sys
sys.path.insert(0, "/data/native_lib/JPype1-0.6.3-py2.7-linux-x86_64.egg")
sys.path.insert(0, "/data/native_lib/JayDeBeApi-1.1.1-py2.7.egg")
import jaydebeapi
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
url = "jdbc:sqlserver://Hostname:Port;databaseName=DBName;integratedSecurity=true;authenticationScheme=JavaKerberos"
user = "SampleUser.keytab"
sql = "select top 1 name,age,group,EmpNo  from Employeeetbl"
conn = jaydebeapi.connect(driver,url,{'user': user},"/usr/hdp/3.1.0.242-7/spark2/jars/mssql-jdbc-8.2.0.jre8.jar")
curs = conn.cursor()
curs.execute(sql)
curs.fetchall()

**Error:**

> conn = jaydebeapi.connect(driver,url,{'user': user},"/usr/hdp/3.1.0.242-7/spark2/jars/mssql-jdbc-8.2.0.jre8.jar")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/jaydebeapi/__init__.py", line 381, in connect
  File "build/bdist.linux-x86_64/egg/jaydebeapi/__init__.py", line 199, in _jdbc_connect_jpype
jpype._jexception.SQLServerExceptionPyRaisable: com.microsoft.sqlserver.jdbc.SQLServerException: Integrated authentication failed. ClientConnectionId:XXXXXXXXXXXXXXX

Appreciate your quick help..

**Comment by peterbae** [comment]
Hi @kvspreddy, you can't use our driver with Python, and you should use a driver compatible with Python instead, such as PyODBC.

**Comment by kvspreddy** [comment]
Thanks for your response. our requirement is connect using jdbc not ODBC.
Please note: I am able to connect when we change it to authenticationScheme=NTLM using the above code and drivers. But not using JavaKerberos.

**Comment by peterbae** [comment]
This could be related to the way you're using the jaydebeapi, but the error is too generic for me to provide an answer. Most likely this is occurring due to an environment setup issue, and you can refer to [this ](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-ver15)page for details. I'm also not sure why you need to provide a username for the conn variable since this is integrated authentication, but I've never used the jaydebeapi library nor familiar with python code myself.

**Comment by Thrameos** [comment]
The versions used here are very old.   JPype 0.6.2 and Python 2.7 are both very deprecated at this point.   If you can do it with Java code it should be possible to replicate with JPype and Python.   I am not sure what arguments that you would feed to JayDeBeAPI.   Though you could try with ``jpype.dbapi2`` to see if it gives a better result.
