### ISSUE TITLE
License link in 9.2.1 mssql-jdbc_auth POM file is incorrect

### ISSUE THREAD

**Issue by pwagland** [microsoft/mssql-jdbc#1536]
The [POM file](https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc_auth/9.2.1.x64/mssql-jdbc_auth-9.2.1.x64.pom) published on maven central has the incorrect license link.

It is: https://raw.githubusercontent.com/microsoft/mssql-jdbc/v9.2.1/mssql-jdbc_auth_LICENSE, but should be https://raw.githubusercontent.com/microsoft/mssql-jdbc/9.2.1/mssql-jdbc_auth_LICENSE

It is unclear if this is because the tag is incorrectly named, since the 9.2.1 tag is not following the normal convention of the other releases, where it should have been v9.2.1, or whether the release script should pick up the correct tag name to put into the POM file.

Either way, this ends up breaking scripts that automatically grab the license, as the link to get the license is broken.

**Comment by peterbae** [comment]
Thanks @pwagland, the team is looking into this now.

**Comment by peterbae** [comment]
I made a mistake with the tag of the release (It was 9.2.1 instead of v9.2.1). The issue should be fixed now.

**Comment by pwagland** [comment]
Looks good! Thanks for the prompt fix!!
