### ISSUE TITLE
[QUESTION] Documentation for connecting to SQL Server using MFA

### ISSUE THREAD

**Issue by austinkispotta-gep** [microsoft/mssql-jdbc#1537]
Hi, can you provide a documentation of how to connect to SQL Server using MFA.

Currently we use jdbc in logstash and connect to SQL Server using SQL Server Authentication by providing connection string, user and password.
Something in this format by adding it in logstash config file :
   jdbc_connection_string => "jdbc:sqlserver://mysqlserver.windows.net;databaseName=somedb;applicationintent=readonly;"
    jdbc_user => "user"
    jdbc_password => "pass"
    jdbc_driver_library => "/home/jdbc/mssql-jdbc-6.4.0.jre8.jar"
    jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"

I can see that connecting with MFA feature has been added recently in [this PR](https://github.com/microsoft/mssql-jdbc/pull/1464) so I wanted to know how to use it instead of SQL Server Authentication.

**Comment by peterbae** [comment]
Hi @austinkispotta-gep, you can find the documentation here: https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver15#connecting-using-activedirectoryinteractive-authentication-mode
