### ISSUE TITLE
Optional Dependency with Gradle

### ISSUE THREAD

**Issue by v-xiangs** [Microsoft/mssql-jdbc#155]
According to PR #148, the AKV and ADAL4J dependency are optional dependencies with Maven. It reduces dependency tree for any project that replies on mssql-jdbc. However, we couldn't find any equivalent option with Gradle. The most similar option may be `compileOnly`, but still, `optional` and `compileOnly` are different.

According to this [Issue](https://github.com/gradle/gradle/issues/867) on Gradle, it seems like there is no `optional` with Gradle. 

Any suggestions? Thanks.

**Comment by v-nisidh** [comment]
Acording to [survey](https://github.com/Microsoft/mssql-jdbc/wiki/JDBC-Survey-Results) we decided to go ahead with Maven as primary build system, although we are keeping our existing Gradle build Script. 

I am closing this issue. For more information please refer #62
