### ISSUE TITLE
[QUESTION] Where are the translated resource classes such as SQLServerResource_zh_TW and SQLServerResource_zh_CN when I build the jars myself

### ISSUE THREAD

**Issue by sken130** [microsoft/mssql-jdbc#1558]
When I build the jar myself by following the readme.md, I extracted the jar and compared it with your official one, and found that the following translated SQLServerResource classes are missing:

SQLServerResource_de.class
SQLServerResource_es.class
SQLServerResource_fr.class
SQLServerResource_it.class
SQLServerResource_ja.class
SQLServerResource_ko.class
SQLServerResource_pt_BR.class
SQLServerResource_ru.class
SQLServerResource_sv.class
SQLServerResource_zh_CN.class
SQLServerResource_zh_TW.class

May I know why it happens? Is it because of oversight or license issue?

If it's license issue, I would prefer you to mention it to the readme.md.

**Comment by lilgreenbird** [comment]
hi @sken130 

You don't have these in your jar file in your build because you don't have these files in your local directory. These are localized versions of the English texts in [SQLServerResource.java](https://github.com/microsoft/mssql-jdbc/blob/dev/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResource.java). We send this to our localization team to get proper translations and add them to our releases.

**Comment by sken130** [comment]
Is there any plan to include these translation files in the github source?
Or if there's none, then could you mention these limitations in readme.md?

**Comment by lilgreenbird** [comment]
hi @sken130 

This is not a limitation localized files are never included in the repo. Anything that is not part of the repo will obviously not be part of the jar in a local driver build. Getting all the text translated is a manual process they are not auto generated so they can not be part of the driver build. During development these text strings could be added/removed/changed we only send them off to the localization team to get proper translations when we code freeze and prepare for a stable release. These localized versions are then added the release jar only.

**Comment by sken130** [comment]
Understood. But still, could you put a reminder in readme.md about the absence of localization files in the github repo?

**Comment by peterbae** [comment]
I don't think README files should contain information about what is missing. The next time a similar question is asked, the users can refer to this issue for details.
