### ISSUE TITLE
Exception thrown when using java.sql.Types.OTHER

### ISSUE THREAD

**Issue by michaelbini** [Microsoft/mssql-jdbc#156]
Hi,
I am trying to write a method with dynamic data access, and I am getting exception
`com.microsoft.sqlserver.jdbc.SQLServerException: The conversion from BIGINT to OTHER is unsupported.`
here is my sample method to reproduce it:
```
	public List<MyData> read() {
		try {
			Connection connection = this.dataSource.getConnection();
			PreparedStatement ps = connection.prepareStatement("select * from TABLE_NAME where NAME = ?");
                     //ps.setObject(1,new String("test"),java.sql.Types.OTHER);
			ps.setObject(1,5,java.sql.Types.OTHER);
			ResultSet rs = ps.executeQuery();
			while (rs.next()) {
	            String s = rs.getString("NAME");
	            System.out.println(s);
	        }
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return null;
	}
```

This code works with JTDS 1.3.1 and once we tried migrating it to MS JDBC we got this error.

**Comment by v-afrafi** [comment]
Hi @michaelbini. Microsoft JDBC driver does not support java.sql.Types.Other. You can remove the type in setObject method or use the correct type. 
Please take a look at a complete list of datatypes supported in [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-basic-data-types).
