### ISSUE TITLE
UNKNOWN_ROW_COUNT with setAutoCommit(false) and TYPE_SCROLL_INSENSITIVE

### ISSUE THREAD

**Issue by fraquack** [microsoft/mssql-jdbc#1580]
## Driver version
4.2 - 9.2.1.jre11

## SQL Server version
Microsoft SQL Server 2014 (SP3-CU4-GDR) (KB4583462) - 12.0.6433.1 (X64)   Oct 31 2020 02:54:45   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 

## Client Operating System
Microsoft Windows Server 2012 R2 Standard

## JAVA/JVM version
openjdk 11.0.9.1 2020-11-04 LTS
OpenJDK Runtime Environment Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.9.12.1 (build 11.0.9.1+12-LTS, mixed mode)

## Table schema
```
select top (1000) 'abc' col
into test_table
from sys.columns A cross join sys.columns B

go

create view test_view as
select * from test_table
union all
select * from test_table
```

## Problem description
1. Expected behaviour:
    The method `ResultSet.getRow()`, called after `ResultSet.last()` (in a TYPE_SCROLL_INSENSITIVE ResultSet) retrieves the current row number if greater than 2000.
2. Actual behaviour: 
    UNKNOWN_ROW_COUNT (-3) is returned 
3. Error message/stack trace: 
    N/A
4. Any other details that can be helpful: 
    This issue occurs only if `setAutoCommit(false)` is called before retrieving the ResultSet.

## Reproduction code
```
try (Connection connection = DriverManager.getConnection("jdbc:sqlserver:...;integratedSecurity=true")) {
            connection.setAutoCommit(false);
            try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM test_view",
                    ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                 ResultSet resultSet = statement.executeQuery();) {
                resultSet.last();
                System.out.println(resultSet.getRow());
            }
        }
```

**Comment by v-zhangw** [comment]
Hello Fraquak,

I've tried to reproduce this behaviour but have not been able to.
Using your table schema and reproduction code.
I am returned 1000 by the getRow() call each time.

I've tried on versions 9.2.1 and 9.3.1 of the driver as well as adding more rows to the table and therefore view.
With and without setting auto commit false.

Are there any other conditions under which you can produce this issue?

**Comment by fraquack** [comment]
> Are there any other conditions under which you can produce this issue?

I've tested the code connecting with `integratedSecurity=true`.

> I've tried on versions 9.2.1 and 9.3.1 of the driver as well as adding more rows to the table and therefore view.

Please, try adding 1.000 rows to the table to reproduce the issue. After the first occurrence, UNKNOWN_ROW_COUNT should be returned also if 500 rows are deleted. Maybe this problem is related to the space reserved by the table.

**Comment by fraquack** [comment]
I've reproduced this issue also with other driver versions.
It looks like this bug has always been there, since 4.2 (the oldest one I could test).

**Comment by v-zhangw** [comment]
Hi fraquack,

We're having some trouble consistently reproducing this issue. Could you try this repro against another version of SQL Server and letting us know if you see any difference in behaviour.

**Comment by v-zhangw** [comment]
We are closing this issue since it could not be reproduced consistently and there has been a long period of inactivity. If anyone encounters this again and needs help, please comment and we can reopen.
