### ISSUE TITLE
What is the name of the Microsoft SQL Server protocol (I don't mean JDBC)

### ISSUE THREAD

**Issue by adligo** [microsoft/mssql-jdbc#1589]
## Driver version
9.2

## SQL Server version
Microsoft SQL Azure (RTM) - 12.0.2000.8 Apr 29 2021 13:52:20 Copyright (C) 2019 Microsoft Corporation

## Client Operating System
Windows 10

## JAVA/JVM version
JDK 15 something

## Table schema
any and all

## Problem description
The underlying specific DB socket protocol that this Type IV (Type 4) implements should be specified somewhere in the documentation of this project.  What is the name of the Microsoft SQL Server socket protocol (I don't mean JDBC) ?   The protocol name should be identifiable on this page;
https://github.com/microsoft/mssql-jdbc

  In addition some detail on the socket protocol that this project implements (I don't mean JDBC) needs to be referenced.  Is there a wiki, or official document from Microsoft that details the Microsoft SQL Server protocol somewhere?

https://en.wikipedia.org/wiki/JDBC_driver#Type_4_driver_%E2%80%93_Database-Protocol_driver/Thin_Driver(Pure_Java_driver)

## JDBC trace logs
None

## Reproduction code
https://github.com/microsoft/mssql-jdbc

**Comment by v-zhangw** [comment]
Hi adligo,

It is not fully clear what you are asking for.
The JDBC Driver communicates through tcp/ip.

**Comment by adligo** [comment]
JDBC Type 4 drivers wrap a vendor specific database (socket) protocol;
https://en.wikipedia.org/wiki/JDBC_driver#Type_4_driver_%E2%80%93_Database-Protocol_driver/Thin_Driver(Pure_Java_driver)

So for SQL Server what is this protocol called, does it have a name?

**Comment by mprins** [comment]
TDS
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/893fcc7e-8a39-4b3c-815a-773b7b982c50

**Comment by adligo** [comment]
Great Thanks so much!
