### ISSUE TITLE
Slight memory leak on new connection

### ISSUE THREAD

**Issue by elFarto** [microsoft/mssql-jdbc#1632]
I've been taking a very close look at the memory usage of a few of our applications, and I happen to come across the following *8kB* String beginning `com.microsoft.sqlserver.jdbc.SQLServerConnection:123456789101112`.

A quick look through the source code revealed the issue:
https://github.com/microsoft/mssql-jdbc/blob/8172599fd735a5481b784ed9ef0237b9ab6f7ea2/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L1300
loggingClassName is static, so you shouldn't be appending the current connectionId to it.

**Comment by lilgreenbird** [comment]
hi @elFarto ,

Thank you for catch, we will get this fixed in the upcoming release.
