### ISSUE TITLE
Reduce driver package footprint?

### ISSUE THREAD

**Issue by ydewit** [Microsoft/mssql-jdbc#164]
These are the dependencies I get by including the driver in my project: close to 10Mb of additional bytes:
{{{
[INFO] +- com.microsoft.sqlserver:mssql-jdbc:jar:6.1.0.jre8:compile
[INFO] |  \- com.microsoft.azure:azure-keyvault:jar:0.9.3:compile
[INFO] |     +- com.microsoft.azure:azure-core:jar:0.9.3:compile
[INFO] |     |  +- com.sun.jersey:jersey-client:jar:1.13:compile
[INFO] |     |  |  \- com.sun.jersey:jersey-core:jar:1.13:compile
[INFO] |     |  \- com.sun.jersey:jersey-json:jar:1.13:compile
[INFO] |     |     +- org.codehaus.jettison:jettison:jar:1.1:compile
[INFO] |     |     |  \- stax:stax-api:jar:1.0.1:compile
[INFO] |     |     +- com.sun.xml.bind:jaxb-impl:jar:2.2.3-1:compile
[INFO] |     |     |  \- javax.xml.bind:jaxb-api:jar:2.2.2:compile
[INFO] |     |     |     \- javax.xml.stream:stax-api:jar:1.0-2:compile
[INFO] |     |     +- org.codehaus.jackson:jackson-core-asl:jar:1.9.2:compile
[INFO] |     |     +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.2:compile
[INFO] |     |     +- org.codehaus.jackson:jackson-jaxrs:jar:1.9.2:compile
[INFO] |     |     \- org.codehaus.jackson:jackson-xc:jar:1.9.2:compile
[INFO] |     +- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO] |     |  \- org.apache.httpcomponents:httpcore:jar:4.4.6:compile
[INFO] |     +- javax.inject:javax.inject:jar:1:compile
[INFO] |     \- com.microsoft.azure:adal4j:jar:1.0.0:compile
[INFO] |        +- com.nimbusds:oauth2-oidc-sdk:jar:4.5:compile
[INFO] |        |  +- net.jcip:jcip-annotations:jar:1.0:compile
[INFO] |        |  +- org.apache.commons:commons-lang3:jar:3.3.1:compile
[INFO] |        |  +- com.nimbusds:lang-tag:jar:1.4:compile
[INFO] |        |  \- com.nimbusds:nimbus-jose-jwt:jar:3.1.2:compile
[INFO] |        |     \- org.bouncycastle:bcprov-jdk15on:jar:1.51:compile
[INFO] |        \- com.google.code.gson:gson:jar:2.8.0:compile
}}}

Is there a way to make the azure-keyvault an optional dependency considering that the mssql-jdbc.jar is only 766093 bytes and we are not going to use it with azure keyvault?

**Comment by ajlam** [comment]
@ydewit - which version of the jar are you including in your project?

**Comment by ydewit** [comment]
Hi @ajlam, that is great. I am using ```com.microsoft.sqlserver:mssql-jdbc:jar:6.1.0.jre8```. I did see the 6.1.4, but the ```-preview``` turned me away from it. Should I use 6.1.4 instead?

**Comment by rodlogic** [comment]
I just tried 6.1.4 and the extra dependencies are gone. Assuming that it is ok to use the preview release, I am good here and this issue can be closed.

**Comment by ydewit** [comment]
I just tried 6.1.4 and the extra dependencies are gone. Assuming that it is ok to use the preview release, I am good here and this issue can be closed.
