### ISSUE TITLE
COPY INTO Error: Not able to validate external location because The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by sergeik66** [microsoft/mssql-jdbc#1642]
## Question
Hello there,

The MS documentation [page  ](https://docs.microsoft.com/en-us/sql/t-sql/statements/copy-into-transact-sql?view=azure-sqldw-latest) states that there is no limitations on the number of files (PARQUET,ORC) to load into Synapse (SDW) dedicated pool. However, I encounter the following error message trying to execute COPY INTO command with 25,529 blobs in ADLS2 storage account. Same command using smaller number of files works as expected. Could you please elaborate on this matter?
Is there a limit and why command returns 403 status?

Best,
-Sergei 

**Additional info:**
Client:
**SSMS v18.9.1**
Databricks runtime:
**8.3.x-scala2.12**
Server version: 
**Microsoft Azure SQL Data Warehouse - 10.0.13580.0 Jul 31 2021 18:43:30 Copyright (c) Microsoft Corporation**
SQL Command:
**COPY INTO schema.table
FROM dfs_location_folder_path
WITH (
FILE_TYPE = 'PARQUET', 
CREDENTIAL = xxxxx
COMPRESSION = 'Snappy',
IDENTITY_INSERT = 'OFF'
)**
Error message:
**Not able to validate external location because The remote server returned an error: (403) Forbidden.**

**Comment by David-Engel** [comment]
I recommend you contact Azure Synapse Analytics (Azure SQL Data Warehouse) support. This repo is for the Microsoft JDBC Driver for SQL Server. We do not know why the server would be returning that error message.

Regards,
David

**Comment by sergeik66** [comment]
Thank you David.

The reason I posted the question in this repo was because my application (ADB) is using JDBC Driver for SQL Server and initial error was produced by the com.databricks.spark.sqldw.SqlDWSideException class.
"Azure Synapse Analytics failed to execute the JDBC query produced by the connector". I will reach out to the other team as you suggested.

Best,
-Sergei
