### ISSUE TITLE
JDBC driver does not properly execute SSL-over-TDS handshake

### ISSUE THREAD

**Issue by hrstoyanov** [microsoft/mssql-jdbc#1653]
## Driver version
9.4.0.jre16 (latest from Maven central repo)

## SQL Server version
TDS compliant server proxy

## Client Operating System
MacOs BigSur 11.5.2

## JAVA/JVM version
Java 16

## Table schema
not applicable

## Problem description
Microsoft's TDS document (see section 2.2.6.5 PRELOGIN) specify that during PRE-LOGIN message exchange the client and the server can execute SSL handshake protocol to establish secure connection (whether only for the subsequent LOGIN or for the entire session). **My tests shows that the JDBC Driver fails to execute the SSL Handshake properly and a proper TDS server would fail the connection due to unfinished SSL handshake**. In particular, it fails to to execute a last confirmation step and send finishing message to the TDS server. Such behavior is not observed with other TDS clients such as  Microsoft SQL Management Studio, Azure Data Studio, .NET clients - all tested against the same TDS server.

I have attached 5 files to this issue:

1. A detailed log from MS SQL JDBC driver attempting to connect with some trivial code, like:
```
DriverManager.getConnection("jdbc:sqlserver://127.0.0.1:1437;user=test;password=test;encrypt=true;trustServerCertificate=true");
```

2. A detail log from the TDS server. This may require more explanation, but you should see the payloads and their sizes exchanged with the client.

3. A network capture file (produced by the WireShark free tool) that tracks independently the communications between the JDBC client and the TDS server. You need to install WireShark to browse the network capture file, but I have also attached 2 screenshots for your convenience.

[jdbc-ssl-issue.zip](https://github.com/microsoft/mssql-jdbc/files/7168334/jdbc-ssl-issue.zip)

**Here is what I observe:**

1. Line 138 in the log confirms that the client has received the last SSL handshake payload of 2455 bytes from the TDS server, and the messages from line:293-line:350 show the client parsing SSL chunks and is trusting the TDS server certificate (line:350). This is independently confirmed with **screenshot1** from the WireShark capture file, which shows a payload of exactly 2463 bytes sent to the client (2455+8=2463, TDS header is 8 bytes).

2. The client is expected to send a final SSL handshake confirmation message to the TDS server
The logs indicate that from line:308 the client starts building up such a response, which is made ready by line:352-line:356, where 90 bytes are supposed to be sent to the TDS server. **However, line:360 shows the "flushing the stream" never happens!**.

3. **Without properly confirming the end of the SSL handshake**, the client assume SSL connection has been established, and proceeds to build a LOGIN message of size 355 bytes (line:361 - line: 423) that it eventually sends to the TDS server as encrypted payload of 373 bytes (see line 419). This is confirmed by the network capture file, where **screenshot2** shows the TDS server **never receiving the 90 bytes** finishing SSL handshake message, but directly forced to deal with the LOGIN message of size 373.

4. The TDS server, still expected SSL handshake message (wrapped as TDS messages) attempts to parse the TDS packet header and blows up with "Unknown value: 23" for the message type.

```
00:08:46 FINER [ai.dy.db.mssql] (macbook23-thread-2) Read 8 bytes (no SSL) from socket channel into byteBuffer[p:8|l:8|c:8|r:0] -  [1632909979|_nohash_|OP|PRE_LOGIN, L:localhost:1437 - R:localhost:55589, INPUT]
00:08:58 SEVERE [ai.dy.db.mssql] (macbook23-thread-2) Error for input connection: [1632909979|_nohash_|OP|PRE_LOGIN, L:localhost:1437 - R:localhost:55589, INPUT]: java.lang.IllegalArgumentException: Unknown value: 23
```

## JDBC trace logs
See attachments

## Reproduction code
TDS server code can be provided under NDA.

**Comment by lilgreenbird** [comment]
hi @hrstoyanov 

The Microsoft JDBC Driver for SQL Server is built to work with Microsoft SQL Server we have not seen any issues relating to SSL handshaking.  We don't have the resources to support or debug code from a 3rdparty server, but if the driver is not performing proper handshakes this should fail for SQL Server as well. Could you please create your scenario and share a simple  java repro of this using MS SQL Server? 

Another thing to try is see if you can repro your issue with the [SqlClient driver](https://github.com/dotnet/SqlClient) which is also open source on github.

**Comment by David-Engel** [comment]
Hi @hrstoyanov 

Few thoughts: Have you compared to a successful Wireshark capture between the JDBC driver and SQL Server? How is SQL Server handling the LOGIN message? I wonder if your TDS server is assuming that all messages will start/end on packet boundaries. It shouldn't matter if the stream is flushed or not. As long as the server receives the proper data (it will get sent eventually when the stream is subsequently written to), things should flow correctly.

The ignoring of flush on the stream is intentional, according to the comments in the source:
https://github.com/microsoft/mssql-jdbc/blob/7f3af328177744039f76be1d891d1529a387b884/src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java#L894

If seems that the JDBC driver handles flushes very carefully/intentionally during the login phase. Another example:
https://github.com/microsoft/mssql-jdbc/blob/7f3af328177744039f76be1d891d1529a387b884/src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java#L4226

Regards,
David

**Comment by hrstoyanov** [comment]
@lilgreenbird My expectation was that the MS SQL JDBC driver complies with the TDS protocol.  I could be  that by some accident, it may work with MS SQL server SSL handshake.  As I mentioned in the report, (the latest) MSQL Management Studio and the (latest) new Azure Data Studio do not exhibit such SSL handshake problems , work flawlessly after establishing the connection with my TDS server.

In addition, I just tested my TDS server proxy  with a simple .NET SqlClient (see below) - **it works just fine**! My TDS server acts like a proxy - it connects on the front with SqlClient and on the back - with true MS SQL Server 2019. Both connection front and back are forced into complete session SSL (not just during the LOGIN exchange) . **No problem** (e..g running scripts, pulling huge result sets through my double-encrypted TDS proxy)!

 The captured WireShark file for the .NET SqlClient looks slightly different in the SSL handshake part, so direct comparison with the Java JDBC client (see my previous attachment) is not possible, unfortunately. Still, take a look:
[dotnet.zip](https://github.com/microsoft/mssql-jdbc/files/7185154/dotnet.zip)

.NET version for MacOS:
```
hristo:~$dotnet --version
5.0.300
hristo:~$
hristo:~$dotnet run --configuration Release -- conn conn
DONE! connecting
DONE! reading result set
DONE! with everything
```

C# code:
```C#
using System;
using System.Configuration;
using System.Data.SqlClient;

public class SimpleConnect {
        static readonly string ConnString = ConfigurationManager.AppSettings["SimpleConnect_ConnString"];

        public static void Launch( ) {
            try {
                using ( var connection = new SqlConnection(ConnString) ) {
                    connection.Open( );
                    Console.WriteLine("DONE! connecting");
                    var cmd = new SqlCommand( "select 1", connection );
                    using (var rdr = cmd.ExecuteReader()) while (rdr.Read()) {  }
                    Console.WriteLine("DONE! reading result set");
                }
            } catch ( Exception ex ) {
                Console.WriteLine( "ERROR:" + ex.Message );
            }
            //Console.ReadKey( );
        }      
    }
```

Configuration:
```
Data Source=127.0.0.1;User ID=test;Password=test;Connect Timeout=360;TrustServerCertificate=yes
```



@David-Engel 
If you assume so, can you please explain what happened with this particular outgoing payload of 90 bytes from the jdbc logs I supplied, lines 352-360:
```
FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream@293bb8a5 Writing 90 bytes
Sep 15, 2021 12:07:52 AM com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeOutputStream writeInternal
FINEST: TDSChannel (ConnectionID:1) (SSLHandshakeOutputStream): Writing 90 bytes...
Sep 15, 2021 12:07:52 AM com.microsoft.sqlserver.jdbc.TDSWriter writeBytes
FINEST: TDSWriter@1d0d6318 (ConnectionID:1) Writing 90 bytes
Sep 15, 2021 12:07:52 AM com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream flush
FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream@293bb8a5 Flushing
Sep 15, 2021 12:07:52 AM com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeOutputStream flush
FINEST: TDSChannel (ConnectionID:1) (SSLHandshakeOutputStream): Ignored a request to flush the stream
```
As I demonstrated with the WireShark capture, this payload of 90 bytes is missing (never send overt the network, never received by the TDS server), **all other  payloads sent by the client are fully accounted to a byte**!

Also, since you requested it, here is a

**Comment by David-Engel** [comment]
@hrstoyanov 

Let's back up a bit. 

> My tests shows that the JDBC Driver fails to execute the SSL Handshake properly and a proper TDS server would fail the connection due to unfinished SSL handshake. In particular, it fails to to execute a last confirmation step and send finishing message to the TDS server. Such behavior is not observed with other TDS clients such as Microsoft SQL Management Studio, Azure Data Studio, .NET clients - all tested against the same TDS server.

You've tested **_ONE_** TDS client against your custom TDS server. SSMS and ADS both use implementations of the SqlClient .NET library under the covers (ADS basically using a much newer version.) Before claiming that JDBC "fails to execute the SSL Handshake properly" when JDBC clearly works fine against all supported versions of SQL Server and Azure SQL databases, you might want to expand the testing of your custom TDS server implementation. How about trying the Microsoft ODBC Driver for SQL Server? Or the Microsoft OLE DB Driver for SQL Server? Or jTDS? or FreeTDS? Or tedious? Or go-mssql? ODBC and OLE DB are easy to use from C# wrapped in the System.Data.Odbc/System.Data.OleDd libraries. Tedious and Go-mssql are pretty simple to get started with following the guides here: https://www.microsoft.com/en-us/sql-server/developer-get-started
You already have Java set up, so testing jTDS should be simple.

Regardless of the TDS specification, if you want to implement a robust TDS server, you will need to accommodate the actual behavior of current clients actually in use.

**Comment by hrstoyanov** [comment]
Ok @David-Engel , here is test with a different JDBC driver - the commercial [CDATA MS SQL JDBC driver](https://www.cdata.com/download/getfile.aspx?file=demo/RURG-V/setup.zip&name=SQL%20Server%20Driver&tag=Download-jdbc). **SSL handshake + some trivial Java client code all worked just fine**, also confirmed with WireShark capture! Hopefully the screenshot below does not need further comments...

I will try with other drivers you suggested, but jTDS is very old/unsupported and I did not figure out a way to tell it to accept any SSL server certificate.
![Screen Shot 2021-09-17 at 12 26 40 PM](https://user-images.githubusercontent.com/5327044/133846558-0c9ccbdf-71e5-4c28-aff7-9e9d778d2f6e.png)

**Comment by hrstoyanov** [comment]
Ok ... I think I solved the mystery of the missing TLS handshake message.

The MS JDBC Driver documentation states that it only supports TLSv1.2,  **but in no way enforces this limitation in the TLS handshake negotiation** by default. One need to use the ```sslProtocol=TLSv1.2``` connection option!
Java 16/17, which I use, however additionally  support TLSv1.3 (Not sure this is the case with java 11 and earlier). So, my TDS Servers end up negotiating  TLSv1.3  with a MS JDBC Client which runs on Java 16/17 and proceed to do TLS handshake accordingly. This is causing  a handshake misunderstanding as TLSv.13 has a shorter/faster handshake workflow than TLSv1.2 and earlier versions! 

A few ways to solve the problem is to enforce TLS v1.2 on the MS JDBC client side:
-  by using a connection property ```sslProtocol=TLSv1.2```
-  as a global property:
   - in code: ```jSystem.setProperty("jdk.tls.client.protocols", "TLSv1.2");```
   - or from the command line:  ```java -Djdk.tls.client.protocols=TLSv1.2 ...```

Of course, **a much better fix is for MS JDBC Driver to implementTLSv1.3 already. It is 2021**!

There is also some questionable behavior on the server side, which I may have to bring to the Oracle JDK team:

My expectation is that when instantiating a SSL context and engine  like this:
```java
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLEngine;
...
var sslContext = SSLContext.getInstance("TLSv1.2");
sslEngine = sslContextcreateSSLEngine();
...
```
the resulting SSL engine is only capable to negotiate up to TLSv1.2. That is not the case, unfortunately - the engine could still end up negotiating TLSv1.3 handshake!

**Comment by hrstoyanov** [comment]
Feel free to close this issue, if you do not see this as a problem for MS JDBC current behaviour.

**Comment by David-Engel** [comment]
Makes sense. 

> Of course, **a much better fix is for MS JDBC Driver to implementTLSv1.3 already.**!

Client drivers have already tested TLS 1.3 and the conclusion is that it is simply incompatible with the current TDS design of TLS over TDS. Server-side changes (TDS protocol changes) are needed first. We are waiting on those before we can support TLS 1.3 in the JDBC driver.

Glad you figured it out.

Closing this issue.

Regards,
David
