### ISSUE TITLE
[QUESTION] License of MD4.java?

### ISSUE THREAD

**Issue by msternermxy** [microsoft/mssql-jdbc#1658]
## Question
The file https://github.com/microsoft/mssql-jdbc/blob/dev/src/main/java/mssql/security/provider/MD4.java mentions that "Use is subject to license terms.". What is the relation between that license and the MIT license of this project? Are they compatible? If not, maybe it would better to distribute this functionality separately?

## Relevant Issues and Pull Requests
The class was introduced for #696

**Comment by David-Engel** [comment]
I'm looking into the history of where that file came from. I'll get back soon.

**Comment by David-Engel** [comment]
The code traces it's roots to the MD4 implementation in OpenJDK (plus custom changes to eliminate dependencies), which is under the GPLv2 license:

https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/sun/security/provider/MD4.java

Even under that license, though, we are going to replace it with something that allows the mssql-jdbc driver to remain under the MIT license.
