### ISSUE TITLE
[QUESTION] REDIST for mssql-jdbc_auth_LICENSE?

### ISSUE THREAD

**Issue by msternermxy** [microsoft/mssql-jdbc#1659]
## Question
The file https://github.com/microsoft/mssql-jdbc/blob/dev/mssql-jdbc_auth_LICENSE mentions under 2.a.i. that there would be a "REDIST list in the software" or a list "at REDIST" that describes which code can be copied and distributed in object code form. Could you help me locate this list?

I assume the intention is to allow redistribution of the mssql-jdbc driver *including* the auth part, as the [JDBC driver FAQ](https://docs.microsoft.com/sv-se/sql/connect/jdbc/frequently-asked-questions-faq-for-jdbc-driver) says that the current driver is "redistributable", but it's not very easy to make that interpretation from this license. Could you confirm that is the case?

**Comment by David-Engel** [comment]
Looks like the copy of the license there is not quite up-to-date (I'll update it). If you download the ZIP file (https://aka.ms/downloadmssqljdbc), it contains the official version that states:

> 2. DISTRIBUTABLE CODE. The software may contain code you are permitted to distribute (i.e. make available for third parties) in applications you develop, as described in this Section. 
>    a) Distribution Rights. The code and test files described below are distributable if included with the software.
>        i. REDIST.TXT Files. You may copy and distribute the object code form of code listed on the REDIST list in the software, if any, or listed at REDIST (https://aka.ms/jdbceularedist);

The ZIP (and tar.gz) file also contains a redist.txt file that states:

> Distributable Code for the Microsoft JDBC Driver for SQL Server
> 
> The entire package may be redistributed.
>
> For the latest version of this REDIST file, please visit https://aka.ms/jdbceularedist

Regards,
David
