### ISSUE TITLE
This Driver is not configured for integrated authentication (UnsatisfiedLinkError: <SYSTEM32 PATH>\mssql-jdbc_auth-9.4.0.x64.dll: %1 is not a valid win32 application)

### ISSUE THREAD

**Issue by gitissuepost** [microsoft/mssql-jdbc#1660]
Hi,

I am using mssql-jdbc (9.4.0.jre8) to connect to SQL Server in Windows Authentication mode. But while execution, it fails saying "This Driver is not configured for integrated authentication" and throws exception saying "UnsatisfiedLinkError: C:\Windows\System32\mssql-jdbc_auth-9.4.0.x64.dll: %1 is not a valid win32 application"

Thanks,

[Linked Issue - 1601](https://github.com/microsoft/mssql-jdbc/issues/1601)

**Comment by lilgreenbird** [comment]
hi @gitissuepost 

Please see [Connecting with integrated authentication on Windows](https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url).  The DLL can be downloaded from [Maven](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc_auth).

**Comment by gitissuepost** [comment]
> hi @gitissuepost
> 
> Please see [Connecting with integrated authentication on Windows](https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url). The DLL can be downloaded from [Maven](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc_auth).

@lilgreenbird 

Every thing is inline as mentioned in the above link. Also the dll was taken from maven. However, it says "UnsatisfiedLinkError: C:\Windows\System32\mssql-jdbc_auth-9.4.0.x64.dll: %1 is not a valid win32 application" for both Windows 7 and Windows 10 with admin rights. Similar exception thrown for x32 version of dll as well.

**Comment by lilgreenbird** [comment]
hi @gitissuepost 

NTLM does not use the DLL to authenticate. 
What OS architecture are you running? If x86 you will need to use the mssql-jdbc_auth-9.4.0.x86.dll. Can you provide a screen shot of your system property? 

Also, where are you running the driver from and what java version are you using? It looks like your application is running in 32 bit mode. Can you please provide your repro code along with all details of your environment.

**Comment by gitissuepost** [comment]
I can't share the actual and complete code as it's in a corporate network. However, I can provide you the details around it.

OS Architecture - x64 (Both Win 7 and Win 10)
Java Version - 1.8.171 x64
Connection code is pretty straight forward.
All screenshots attached for your reference.

**Comment by lilgreenbird** [comment]
hi @gitissuepost 

Why NTLM would take this long is puzzling. I understand you said you do not want to use SQL authentication but I'm wondering if that takes a long time as well? The only thing I can think of is that your CLASSPATH is messed up and is taking a long time to find the class files? What is your CLASSPATH, and PATH variable set to? Could you make sure to have c:\windows\system32 and the location of the driver jar 1st?

I don't know why your application is looking for a win32 application either. The error message suggests it did find the DLL but I don't know why it expects it to be an win32 app. I'm wondering if your DLL is corrupted? Could you check the DLL you downloaded does it show that it has the digital signature from Microsoft Corporation? This is really strange as if you removed the DLL you will see another error complaining that it can not be found. You could also try to set the java.library.path explicitly i.e. -Djava.library.path=<path containing DLL>.

I'm sorry I'm just taking guesses here but I really can not think of any reasons why this is happening for you?  I've never seen this before we have lots of users using integrated authentication and with java 8. I just tried this on my local machine as well using the released 9.4.0 jar to verify. There is something strange in your environment, is it possible to try this in a fresh clean machine or VM?

**Comment by lilgreenbird** [comment]
I am wondering if your JDK is mixed up and your GUI env is actually using another version of the JDK with the wrong bitness? To eliminate this possibility, can you try this very simple standalone java program using command line only:

```
public class Tester {
    public static void main(String[] args) {
        String connectionUrl = "jdbc:sqlserver://localhost;user=sa;password=password;integratedSecurity=true";
        try (Connection con = DriverManager.getConnection(connectionUrl); Statement stmt = con.createStatement();) {
            String SQL = "SELECT @@VERSION";
            ResultSet rs = stmt.executeQuery(SQL);
            while (rs.next()) {
                System.out.println(rs.getString(1));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
```

In a command prompt, set CLASSPATH to contain only the current folder and location of the driver jar. e.g.
`
set CLASSPATH=.;c:\path_containing_jar|mssql-jdbc-9.4.0.jre8.jar
`

Then from the same command prompt, set your JAVA_HOME, compile and run: 
`
java -version
javac Tester.java
java Tester -Djava.library.path=c:\path_containing_dll
`

**Comment by gitissuepost** [comment]
@lilgreenbird 

I figured out that the problem is with our enterprise artifactory. The dll available there seems corrupted as the size of the dll is around 2kb which doesn't look right. However, the dll from maven central is of 307kb. That must be the reason, it says it's not a valid win32 application. I have raised a request to update that file in artifactory and I hope it will work fine after that. Downloading files directly from maven central is restricted here.

Last question I have is, will this wok across all environments i.e. Linux and Mac? With this response, you can close this ticket.

**Comment by lilgreenbird** [comment]
hi @gitissuepost 

Good to hear you've solved your issue. For Linux/Mac, obviously the DLL will not work so you will have to use Kerberos. Here's a link to the [docs ](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-ver15)for your reference.
