### ISSUE TITLE
[QUESTION] Is there a timeline for Java 17 support?

### ISSUE THREAD

**Issue by Ortofta** [microsoft/mssql-jdbc#1664]
## Question
Hi,

Is there a timeline for when we can expect Java 17 support in the driver? 
I guess it may be a while, given that we just got Java 16 support in the last release? 
Anyway, I would really like to move on to Java 17, as it's an LTS.

Thank you!

**Comment by David-Engel** [comment]
We generally add new Java version support in our regularly-scheduled releases that follow the Java version release date. You can look for a MS JDBC driver GA release at the end of January. It will probably be in a preview release between now and then, first.

Regards,
David

**Comment by Ortofta** [comment]
Thank you for taking the time to reply David. This is very useful information for my planning - much appreciated!
