### ISSUE TITLE
[QUESTION] Can I auth jdbc with service principal id and certificate(either a file or path)?

### ISSUE THREAD

**Issue by jiahh-ms** [microsoft/mssql-jdbc#1666]
## Question
Hi,

I'm working on connect sql database with jdbc using service principal auth, and exploring if we can use a certificate instead of secret. 

In this [doc page ](https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-2017#connecting-using-activedirectoryinteractive-authentication-mode) it says it needs a SP id and a secret when the auth type is setting to SP. 
I verified this option works and now trying to see if we can connect sql db using jdbc with SP id and a certificate, from either a path or binary content. The SP is from a AAD app I created and cert is created from a AKV signed by me. I'm trying to upload the cert to the AAD app and use this access sql db.

Can some one please tell me if this is supported and how?

And we are doing this this because we are trying to mimic how a AAD app use MSI to connect to SQL.
I created a Azure VM and I'm able to use the MSI created by VM to access SQL. 
But I'm not sure on a random machine how can a AAD app get this MSI and use it to connect SQL with jdbc.

If you know the answer for either please let me know. Thank you!

Regards,
Jiaheng He

**Comment by lilgreenbird** [comment]
hi @jiahh-ms 

I’m not sure if you are looking for the [Client Certificate Authentication feature](https://docs.microsoft.com/en-us/sql/connect/jdbc/client-certification-authentication-for-loopback-scenarios?view=sql-server-ver15)? Here are some [sample test code ](https://github.com/lilgreenbird/mssql-jdbc/blob/dev/src/test/java/com/microsoft/sqlserver/jdbc/clientcertauth/ClientCertificateAuthenticationTest.java)which use this feature.

Also, the JDBC driver does support MSI authentication via the property _**authentication=ActiveDirectoryMSI**_ . You can see sample code on how to use that [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-2017#connecting-using-activedirectorymsi-authentication-mode).
