### ISSUE TITLE
Add link to driver documentation on Wiki

### ISSUE THREAD

**Issue by tttomat19** [Microsoft/mssql-jdbc#169]
To find documentation for this project in most expected place
it would be good to have a link to https://docs.microsoft.com/en-us/sql/connect/jdbc/getting-started-with-the-jdbc-driver on Wiki home tab of github project.

Sorry, can't edit issue title. Should be "Add link to driver documentation on Wiki".

**Comment by v-nisidh** [comment]
@tttomat19 : Thanks for opening this issue. 

I added following 3 links in [Wiki Home Page](https://github.com/Microsoft/mssql-jdbc/wiki).
- Microsoft JDBC Driver for SQL Server 
- Getting Started with the JDBC Driver
- Frequently Asked Questions (FAQ) for JDBC Driver

If you satisfied, please close this issue.
