### ISSUE TITLE
Is there a way to configure the read timeout in miliseconds?

### ISSUE THREAD

**Issue by hmantri05** [microsoft/mssql-jdbc#1695]
`JDBCTemplate.setQueryTimeout` sets the timeout in seconds. Is there a way this timeout can be set in miliseconds?
I came across a parameter named `queryTimeout` that can be mentioned in the SQL Server connection string, but that too configures timeout in seconds.

**Comment by lilgreenbird** [comment]
hi @hmantri05,

the driver does not support that level of precision in the timeout values
