### ISSUE TITLE
Unable to pass SQL Server Authentication parameters via jaas file when using ActiveDirectoryServicePrincipal authentication

### ISSUE THREAD

**Issue by rahulgulati89** [microsoft/mssql-jdbc#1702]
## Driver version
mssql-jdbc-9.4.0.jre8.jar

## Client Operating System
Linux

## JAVA/JVM version
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (build 25.302-b08, mixed mode)

## Table schema
      [ACCOUNTID]
      ,[BOOKINGCLIENTID]
      ,[BOOKINGACCOUNTID]
      ,[BOOKINGPOSITIONID]
      ,[BOOKINGCLIENTNAME]
      ,[BOOKINGHEDGEID]
      ,[BOOKINGEXERCISEID]
      ,[TRADEORIGIN]

## Problem description
I am trying to connect to SQL Server running in Azure from Kafka Connect/Java and i am using ActiveDirectoryServicePrincipal authentication mode for the connection. However, I am unable to paas SQL Server authentication parameters named "**AADSecurePrincipalId**" and "**AADSecurePrincipalSecret**" via jaas fie. Upon passing them like this, the connector complains with this error

**SQLJDBCDriver {
    com.microsoft.sqlserver.jdbc.SQLServerDataSource
    AADSecurePrincipalId="***"
    AADSecurePrincipalSecret="***";
};**

**Error ->**
"org.apache.kafka.connect.errors.ConnectException: com.microsoft.sqlserver.jdbc.SQLServerException: Both \"AADSecurePrincipalId\" and \"AADSecurePrincipalSecret\" connection string keywords must be specified, if \"Authentication=ActiveDirectoryServicePrincipal\".\n\ta"

However if i pass them in connection string then my application could connect to database fine and i can push records to the table as well from kafka connect/Java.

"connection.url": "jdbc:sqlserver://dsql001shared.database.windows.net:1433;database=SsocNcs;**aadSecurePrincipalId=***;aadSecurePrincipalSecret=*****;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;authentication=ActiveDirectoryServicePrincipal"

On the other hand, something like this works with kerberos integrated authentication while connecting to on premise SQL Server DB.

**/etc/jaas.conf** ->

SQLJDBCDriver {
    com.sun.security.auth.module.Krb5LoginModule required
    useTicketCache=true
    useKeyTab=true
    renewTGT=true
    doNotPrompt=true
    keyTab="/etc/kafka/keytabs/svcdevdatahub@sys.dom.keytab"
    principal="svcdevdatahub@SYS.DOM";
};

Question is that is Jaas file method only supported for kerberos authentication or is there a way to pass the connection credentials for 
**ActiveDirectoryServicePrincipal**  authentication method when connecting to azure sql server db.

~     
## JDBC trace logs
NA

## Reproduction code
Can be reproduced from Java App

**Comment by lilgreenbird** [comment]
hi @rahulgulati89 

thank you we'll investigate and get back to you.

**Comment by lilgreenbird** [comment]
hi @rahulgulati89 

The JAAS Login Configuration file is used for [Kerberos authentication](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server)) only.

For `ActiveDirectoryServicePrincipal` you can either specify the property in the connection string, or use the [SQLServerDataSource ](https://docs.microsoft.com/en-us/sql/connect/jdbc/reference/sqlserverdatasource-class)interface as show in the example [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver15#connecting-using-activedirectoryserviceprincipal-authentication-mode).

**Comment by v-zhangw** [comment]
Hi @rahulgulati89,
Has your question been answered?
It has been a few days and we would like to close this issue.

**Comment by rahulgulati89** [comment]
Yes Please. Thank you
