### ISSUE TITLE
useBulkCopyForBatchInsert does not work?

### ISSUE THREAD

**Issue by JDBC-0** [microsoft/mssql-jdbc#1708]
## Driver version
9.4.0

## SQL Server version
Microsoft SQL Server 2019 (RTM-GDR) (KB4583458) - 15.0.2080.9 (X64)   Nov  6 2020 16:50:01   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

## Client Operating System
Microsoft Windows [Version 10.0.19041.1348]

## JAVA/JVM version
openjdk version "11.0.11" 2021-04-20

## Problem description
I tested long running processes with mutliple long running INSERTs. Switching on bulk insert through the JDBC URL:

useBulkCopyForBatchInsert=true

does not to do anything better - the performance is still the smae. The (hundred thousands) records are stored via prepared statement

"INSERT INTO pb2.dbo.test_Date2_tab VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"

Switching sendTemporalDataTypesAsStringForBulkCopy also didn't show any difference.

I wonder how to see if the driver is really using bulk insert? Is there some parameter to output a hint that executeBatch() is executed with enabled bulk insert?

Hint: some of the columns are DATE values and I read that:

"Due to the limitations of Bulk Copy API, MONEY, SMALLMONEY, DATE, DATETIME, DATETIMEOFFSET, SMALLDATETIME, TIME, GEOMETRY, and GEOGRAPHY data types, are currently not supported for this feature."

Could that be the reason that useBulkCopyForBatchInsert is somehow not used? Anyway, the driver should output (e.g. through "debug parameter" if the bulk insert is effectively used or not.

**Comment by lilgreenbird** [comment]
hi @JDBC-0 

You are correct, bulk copy is not supported for spatial columns. 

This is clearly stated in the [`Known limitations` in  Using bulk copy API for batch insert operation](https://docs.microsoft.com/en-us/sql/connect/jdbc/use-bulk-copy-api-batch-insert-operation#known-limitations) doc as you mentioned above, as well as in the [`Limitations of spatial datatype` in Using spatial datatypes.](https://docs.microsoft.com/en-us/sql/connect/jdbc/use-spatial-datatypes?limitations-of-spatial-datatypes) doc.

**Comment by JDBC-0** [comment]
So, is there a way to somehow output if a statement is not "good enough" for bulk insert to be active? E.g. URL paameter "debugOutput=true"?

**Comment by v-zhangw** [comment]
There is not a parameter in the vein of "debugOutput" parameter.

**Comment by lilgreenbird** [comment]
@JDBC-0 

you can turn on [tracing ](https://docs.microsoft.com/en-us/sql/connect/jdbc/tracing-driver-operation?view=sql-server-ver15)for the driver if you want to know what the driver is doing but there are no trace logs for things that the driver does not do. This is not an error scenario for the driver it's just not currently supported and as mentioned the behavior is clearly documented. Please let us know if you have other questions otherwise we will be closing this issue.

**Comment by David-Engel** [comment]
@JDBC-0

If you turn on tracing at the FINE level, you'll see a log message like this when the driver encounters an unsupported scenario:

> Parsing user's Batch Insert SQL Query failed: [specific error]
> Falling back to the original implementation for Batch Insert.

Regards,
David

**Comment by JDBC-0** [comment]
Thanks, David. Too bad that this only is logged on level FINE, but at least this could help during debugging.
