### ISSUE TITLE
[QUESTION] SQLServerParameterMetaData retrieval always executed with "SET FMT ONLY"?

### ISSUE THREAD

**Issue by fall14123** [microsoft/mssql-jdbc#1714]
## Question

[SQLServerParameterMetaData](https://github.com/microsoft/mssql-jdbc/blob/main/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java#L28) states "_Prepared statements are executed with SET FMT ONLY to retrieve column meta data_", which seems to contradict  https://github.com/microsoft/mssql-jdbc/blob/main/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java#L340-L354 - wondering it's just outdated documentation or still holds true. thanks.

**Comment by lilgreenbird** [comment]
hi @fall14123 

yes, as per [set fmtonly doc ](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-fmtonly-transact-sql)it has been replaced by `sp_describe_undeclared_parameters` however this stored procedure is only available for SQL Server 2012 and above so when this is not available set fmtonly is still used.

**Comment by fall14123** [comment]
thanks for the details @lilgreenbird - forgot to mention we are on sqlserver 2019 - so for us (again, on sqlserver 2019), as long as "st.getUseFmtOnly()" evaluates to false, we shouldn't invoke "SET FMT ONLY" (according to https://github.com/microsoft/mssql-jdbc/blob/main/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerParameterMetaData.java#L340).
