### ISSUE TITLE
[QUESTION] call stored procedure return sqlwarning too many will out of memory

### ISSUE THREAD

**Issue by cy7851** [microsoft/mssql-jdbc#1718]
## Question
We now have a problem that in calling the stored procedure, 1000000 messages are printed, resulting in 1000000 new sqlwarning objects in the sqlwarnings collection in the SqlServerStatement.
I tried to set ResponseBuffering to adaptive, but the result is the same，I tried to set response buffering to adaptive, but the result is the same.
Cursor is only valid for resultset, so I don't know how to avoid this problem. Do you have any good suggestions.

**Comment by tkyc** [comment]
Hi @cy7851,  could you provide some clarity on the following questions:

1. What is the driver version you are using?
2. What is your connection string?
3. Could your provide repro code/app for us to use to investigate?
4. What was the stored procedure call that was made?

Thanks

**Comment by tkyc** [comment]
Hi, I will closing this issue soon for inactivity.

**Comment by cy7851** [comment]
Hi @tkyc thanks for your response,  I'm sorry it took so long to reply to you.
1.The driver version is mssql-jdbc-7.4.1-jre8.
2.String connectionUrl = "jdbc:sqlserver://127.0.0.1:1443;databaseName=test;username=username;password=password;"; 
   The link string is similar to this
3.    
``` java

    String connectionUrl = "jdbc:sqlserver://127.0.0.1:1443;databaseName=test;username=username;password=password;";

            try (Connection con = DriverManager.getConnection(connectionUrl); Statement stmt = con.createStatement();
                    Statement stmt1 = con.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_UPDATABLE);) {
                
                stmt1.setFetchSize(100);
                if (stmt.isWrapperFor(com.microsoft.sqlserver.jdbc.SQLServerStatement.class)) {
                    SQLServerStatement SQLstmt = stmt.unwrap(com.microsoft.sqlserver.jdbc.SQLServerStatement.class);
                    SQLstmt.setResponseBuffering("adaptive");
                    System.out.println("Response buffering mode has been set to " + SQLstmt.getResponseBuffering());
                }
                stmt1.execute("test");
                
        

            }
        }
```
The test code is as abov. The code that executes this test calls  stored procedure below. If the memory does not overflow, debug can see that the number of sqlWarnings of the stmt1 attribute is 1000001

4. stored procedure 
``` sql
create procedure test
                        
as 
Declare @ii int;
set @ii=0;
                
while @ii < 1000000
begin
     print(@ii);
     set @ii=@ii+1;
end
go        
```

**Comment by tkyc** [comment]
Thanks @cy7851, with the above repro code, I'll do some investigating and get back to you.

**Comment by tkyc** [comment]
Hi @cy7851, from running your code, the sqlwarnings are from the print() within the procedure. These warnings are coming from the SQL server side, I'm afraid we can't do anything about the sqlwarnings on the driver side as aggregating the warnings by the driver is behaving as expected.

A couple of ideas that may help you with your problem:

1. The sqlwarnings vector is reset with each statement execution, maybe break down the looping within the the stored procedure and then execute the statement multiple times instead.

2. I'm assuming that the repro code you gave me is a simplified version of what your doing (and not the real thing). But from the code, the warnings were coming from the print() in the stored procedure. If you removed the print() there were no warnings. So I'd recommend addressing and correcting the warnings from the stored procedure.

I'll be closing this issue as it is not directly a driver problem.
