### ISSUE TITLE
Using DatabaseMetadata getDatabaseProductVersion to correctly detect Azure SQL vs SQL Server verions

### ISSUE THREAD

**Issue by dqmdev** [microsoft/mssql-jdbc#1729]
Microsoft have published the following statement, saying that @@version is returning the wrong information for Azure SQL databases
https://docs.microsoft.com/en-us/sql/t-sql/functions/version-transact-sql-configuration-functions?view=sql-server-ver15#remarks

JDBC driver DatabaseMetadata methods such as getDatabaseMajorVersion and getDatabaseProductVersion reflect the version returned by select @@version

Unclear from the statement issued by Microsoft, if we should expect different (and correct) major.minor versions to be returned than currently. Versus, this not change, and application vendors have to add code to use the workaround to detect Azure SQL etc.

i.e. SQL Server JDBC driver version 9.4.0.0 will return 12.00.2327 from DatabaseMetadata.getDatabaseProductVersion

**Comment by v-zhangw** [comment]
Hello @dqmdev getDatabaseProductVersion uses a select serverproperty query and should return the correct sql server version on Azure SQL.

**Comment by v-zhangw** [comment]
As far as detecting Azure SQL, I do not believe you can identify that with just major, minor and product version. Running a select on server property query would be the recommended way.

**Comment by dqmdev** [comment]
To clarify, it wasn't clear from the article, if Azure SQL and Azure SQL DW were expected to report a different major.minor number than is reported currently.

It seemed to imply as such, and suggesting that if you were trying to use that to determine SQL vs Synapse etc, to so something else explicitly

Specific text being:

_We are aware of an issue where the product version reported by @@VERSION is incorrect for Azure SQL Database.

We are aware of an issue where the product version reported by @@VERSION is incorrect for Azure SQL Database.

The version of the SQL Server database engine run by Azure SQL Database is always ahead of the on-premises version of SQL Server, and includes the latest security fixes. This means that the patch level is always on par with or ahead of the on-premises version of SQL Server, and that the latest features available in SQL Server are available in Azure SQL Database._




https://docs.microsoft.com/en-us/sql/t-sql/functions/version-transact-sql-configuration-functions?view=sql-server-ver15#remarks
