### ISSUE TITLE
Java 17 support out of preview?

### ISSUE THREAD

**Issue by mosabua** [microsoft/mssql-jdbc#1732]
## Question

When is Java 17 support with the 10.1.0 or later coming. We are working towards Java 17 in Trino and would like to upgrade the driver to a version that works on Java 11 and 17.

Currently only a preview is in Central - https://search.maven.org/artifact/com.microsoft.sqlserver/mssql-jdbc
even though your readme suggests otherwise. 

## Relevant Issues and Pull Requests

https://github.com/trinodb/trino/issues/9876

**Comment by tkyc** [comment]
Hi @mosabua, currently we are in the middle of doing release work. So expect a stable release of Java 17 some time late January or early February.

**Comment by mosabua** [comment]
Awesome news! Thanks.

**Comment by v-zhangw** [comment]
Hello, @mosabua 
We have just released version 10.2.0 which has Java 17 support. Thank you for your patience!

**Comment by mosabua** [comment]
Thank you so much. I created a follow up PR and will try to get that all the way to merge.
