### ISSUE TITLE
[QUESTION]For ADAL , how we got the client id

### ISSUE THREAD

**Issue by shivamdabas** [microsoft/mssql-jdbc#1736]
hi,
with ADAL authentication we are using hard coded value of client id stored in variable JDBC_FEDAUTH_CLIENT_ID, can we use other client id as well and how we got this value.
Thanks

**Comment by v-zhangw** [comment]
Hello @shivamdabas,

As you noted the JDBC_FEDAUTH_CLIENT_ID is hard coded and cannot be changed.

As for using other client IDs, there are some connection options where you can supply your own as noted here: https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver15

How are you trying to connect in particular?
