### ISSUE TITLE
[QUESTION] mssql-jdbc_auth 10.2.0 Not Released on The Central Repository

### ISSUE THREAD

**Issue by sualeh** [microsoft/mssql-jdbc#1746]
## Question
Has mssql-jdbc_auth 10.2.0 not been released on The Central Repository?

## Relevant Issues and Pull Requests
- [Release notes for the Microsoft JDBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver?view=sql-server-ver15)

**Comment by v-zhangw** [comment]
Hi @sualeh,
Maven Central Repository can take some time to process our release. Sometimes even a little past 24 hours. I would recommend checking again tomorrow.

**Comment by lilgreenbird** [comment]
hi @sualeh 

I do see this in the repo looks but looks like index isn't updated, hopefully will be soon. 

[10.2.0.x64](https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc_auth/10.2.0.x64/)
[10.2.0.x86](https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc_auth/10.2.0.x86/)

**Comment by lilgreenbird** [comment]
it's indexed now, hope this answers your question, Please feel free to request re-opening if you still have issues accessing the release.
