### ISSUE TITLE
The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption.

### ISSUE THREAD

**Issue by medwards8** [microsoft/mssql-jdbc#1771]
## Driver version
mssql-jdbc-10.2.0.jre8

## SQL Server version
Microsoft SQL Server 2019 (RTM-GDR) (KB4583458) - 15.0.2080.9 (X64)   Nov  6 2020 16:50:01   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19042: ) (Hypervisor) 

## Client Operating System
Windows 10 Enterprise 10.0 <X64>

## JAVA/JVM version
![2022-03-17_10-32-32](https://user-images.githubusercontent.com/100300381/158829068-83a97f47-62bf-4dfe-90b9-2a1b71ba744d.jpg)

Error I'm currently getting:
![2022-03-17_09-51-52](https://user-images.githubusercontent.com/100300381/158830700-1042c1ff-acde-4d61-9e5d-0722d5adf3ad.jpg)

Content of config file it is referencing:
![2022-03-17_10-49-39](https://user-images.githubusercontent.com/100300381/158830688-6c46db57-e771-4932-8ecb-d953885a4af5.jpg)

Doing this same process on 8.5.1 it runs perfectly fine, only get this error on 8.5.4.  I have tried:

-Updating java version
-adding trustServerCertificate=true
-specifying username/password
-sslProtocol=TLSv1/v1.2

Produces same error every time.

**Comment by medwards8** [comment]
Hi @v-zhangw thanks that seems to work now.  Strange I'm sure I tried adding that in, I must have done some other configuring in the meantime

**Comment by v-zhangw** [comment]
No problem. The unable to find valid certification path error usually means an issue with certificates set up. Using trustservercertificate is a quick fix if you can use it.
