### ISSUE TITLE
Metadata check warns about working TOP statement 

### ISSUE THREAD

**Issue by Quafadas** [microsoft/mssql-jdbc#1776]
## Driver version
ivy"com.microsoft.sqlserver:mssql-jdbc:10.2.0.jre17",

## SQL Server version
Provide the output of executing `SELECT @@VERSION` on your target SQL Server.
Microsoft SQL Server 2019 (RTM-CU15) (KB5008996) - 15.0.4198.2 (X64) 
	Jan 12 2022 22:30:08 
	Copyright (C) 2019 Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

## Client Operating System
Windows

## JAVA/JVM version
Provide the JAVA/JVM version (e.g. java version "1.8.0").
17.0.2

## Table schema
Provide the table schema to repro the issue.
None needed; 
```
val limit = 1
sql" SELECT TOP ( $limit ) val FROM (values (3),(5)) as t(val) ".query[Int]

```

## Problem description
Provide full details of the problem.
This is the complete downstream manifestation. 
https://github.com/tpolecat/doobie/issues/1672

When checking the meta data of a valid query, that has a variable "TOP" parameter, the driver errors. 
>the jdbc java.sql.ParameterMetaData given by the jdbc driver - that's what the driver is returning incorrectly

## Expected behavior
The parameter checking should allow a valid (variable) parameter in a TOP statement. 

## Actual behavior
The query runs successfully , but fails the "metadata test" of the library. The library use (apparently) the java.sql.ParameterMetaData from the driver for that validation.

  Query0[scala.Int] defined at DBTest.scala:33
  SELECT TOP ( ? ) val FROM (values (3),(5)) as t(val)
  ? SQL Compiles and TypeChecks
    The number of rows provided for a TOP or FETCH clauses row count
    parameter must be an integer.

## Error message/stack trace
Complete error message and stack trace.

## JDBC trace logs
Provide the JDBC driver trace logs.  Instructions can be found here: https://docs.microsoft.com/sql/connect/jdbc/tracing-driver-operation

**Comment by v-zhangw** [comment]
Hi @Quafadas,
What is the test that your app is performing doing? From the discussion in in the linked issue it sounds like the test is comparing something against data from parametermetadata, could you provide what exactly is being compared?

**Comment by Daenyth** [comment]
Doobie allows you to write code like
```scala
def getUser(userId: String): Query0[(String, Int)] =
  sql"select name, age from users where id = $userId".query[(String, Int)]`
```

The [`check`](https://tpolecat.github.io/doobie/docs/13-Unit-Testing.html) testing method allows you to take the `Query0` from that expression, prepare a jdbc statement based on it, and check that the statement metadata agrees with the type you said it should

**Comment by v-zhangw** [comment]
Is parameter metadata not returning the correct type in your case? What is the type on the server and the type that parameter metadata is returning?

Is it possible to repro this with a short java application?

**Comment by Daenyth** [comment]
it should be - ultimately it's all happening with calls to jdbc + some metadata being passed around.

Someone would have to pull out the jdbc interactions from the scala side and minimize it

**Comment by Quafadas** [comment]
I am willing to try to be helpful as far as I can. I am however, a naive part time programmer - my java-fu is weak. 

Would you accept a short scala application that you can run with scala-cli https://scala-cli.virtuslab.org ? Should be zero setup for you, it will call down to java bits of the driver I think on the JVM...

**Comment by Quafadas** [comment]
So, I did have a look at this, but basically, I got stuck. I can't figure out how to instantiate an mssql connection outside  having access to an actual SQL server. I tried via docker with Testcontainers.org, but cannot get the container started ... so I'm afraid I'm giving up on the reproduction. I'm sorry. 

```
Mar 31, 2022 3:51:09 PM com.microsoft.sqlserver.jdbc.SQLServerConnection Prelogin
WARNING: ConnectionID:1 ClientConnectionId: 3630786e-cb12-4840-b30d-babb00b6063f Prelogin error: host localhost port 61352 Unexpected end of prelogin response after 0 bytes read

```

**Comment by v-zhangw** [comment]
It is difficult to proceed trying to find out what's going on here without more information to work with. https://tpolecat.github.io/doobie/docs/06-Checking.html doesn't provide enough details for me to build my own repro to try and debug what's going on.

**Comment by Quafadas** [comment]
Okay, I think I have a way to show you at least something; 

1. You'll need a docker image for SQL server, otherwise I can't figure out how to actually get a driver instantiated.
```
 sudo docker run --cap-add SYS_PTRACE -e 'ACCEPT_EULA=1' -e 'MSSQL_SA_PASSWORD=bigStrongPwd1000' -p 1433:1433 --name sqledge -d mcr.microsoft.com/azure-sql-edge
```
2. Install scala cli
https://scala-cli.virtuslab.org

3. Run this gist
```
scala-cli https://gist.github.com/Quafadas/361d07b678637f9736ef945d4f9178b9
```

It's going to succeed. This sledgehammer to crack a nut "proves" that these queries are "valid". Or at least they run.

4. Run this (testing) gist via
```
scala-cli test https://gist.github.com/Quafadas/c725606a6fd3ae155c3fd12caacbd5ac  
```

For me, it fails with; 
```
  Query0[scala.Int] defined at doobie typcheck.scala:40
  SELECT TOP ( ? ) val FROM (values (3),(5)) as t(val)
  ✕ SQL Compiles and TypeChecks
    The number of rows provided for a TOP or FETCH clauses row count
    parameter must be an integer.
    at munit.Assertions.fail(Assertions.scala:273)
    at munit.Assertions.fail$(Assertions.scala:15)
    at munit.FunSuite.fail(FunSuite.scala:11)
    at doobie.munit.analysisspec$Checker.checkImpl(analysisspec.scala:59)
    at doobie.munit.analysisspec$Checker.check(analysisspec.scala:39)
    at doobie.munit.analysisspec$Checker.check$(analysisspec.scala:37)
    at MyTests.check(c725606a6fd3ae155c3fd12caacbd5ac-main/doobie typcheck.scala:19)
    at MyTests.$init$$$anonfun$1(c725606a6fd3ae155c3fd12caacbd5ac-main/doobie typcheck.scala:41)
Caused by: doobie.munit.analysisspec$Checker$ErrorItems
    at doobie.munit.analysisspec$Checker$ErrorItems$.apply(analysisspec.scala:65)
    at doobie.munit.analysisspec$Checker.checkImpl(analysisspec.scala:58)
    ... 5 more
```

I have an open question, on whether we can see the 5 more, which is where I suspect the actual driver is called. 

I hope, that this provides at least some context.

**Comment by v-zhangw** [comment]
Hi @Quafadas,
Just wanted to let you know that this is still on our radar. Just that given this repro is more cumbersome to set up we have not quite gotten around to it.

**Comment by v-zhangw** [comment]
Hello,
Sorry for the lack of updates. We have had a lot on our plate and this issue did not make it into the current sprint. We will revisit it during the issue triage in 2 weeks.

**Comment by jono-coder** [comment]
Here's a simple example of what the OP is trying to explain:

You have a table called **Line** and you do a simple query like this:

```
try (final var connection = DriverManager.getConnection(System.getenv().get("mssql_jdbc_test_connection_properties"))) {
	try (final var stmt = connection.prepareStatement("SELECT [id] FROM [dbo].[Line] WHERE [id] = ?")) {
		stmt.getMetaData();
	}
}
```

The above works fine and if you check the SQL Profiler, the following command is being sent to SQL Server when stmt.getMetaData() is called:

"set fmtonly on SELECT [id] FROM [dbo].[Line] WHERE [id] = null set fmtonly off".

---

Now if you alter that SQL statement slightly and you do add a TOP(?) statement like this:

```
try (final var connection = DriverManager.getConnection(System.getenv().get("mssql_jdbc_test_connection_properties"))) {
	try (final var stmt = connection.prepareStatement("SELECT TOP(?) [id] FROM [dbo].[Line] WHERE [id] = ?")) {
		stmt.getMetaData();
	}
}

```
Then the command in the SQL Profiler is now:

"set fmtonly on SELECT TOP(null) [id] FROM [dbo].[Line] WHERE [id] = null set fmtonly off".

The _null_ in the TOP statement is not allowed by SQL Server.

The solution, seeing as one is only interested in the metaData, is to perhaps remove the TOP clause from the command sent to SQL Server or put a _1_ into the TOP clause.

**Comment by lilgreenbird** [comment]
apologies this issue had fallen through the cracks.

It looks like the SQL query provided by doobie is invalid as per previous msg one would get an error if you try to execute `select top(null)` in SSMS as well. So I would recommend contacting doobie support on why it is generating invalid SQL queries.

**Comment by Quafadas** [comment]
@lilgreenbird As you say - an old issue I'd forgotten about - you can see the upstream discussion here https://github.com/tpolecat/doobie/issues/1672

But the claim from the people that maintain doobie, is that;

> check analysis works by inspecting the jdbc java.sql.ParameterMetaData given by the jdbc driver - that's what the driver is returning incorrectly

I've updated the two gists above, which display the same behaviour on 12.4.2

My understanding remains the same, that Doobie is a slave to the SQL drivers metadata. When it tries to Typecheck 

```
// Works
val queryWorking = sql" SELECT TOP ( 1 ) val FROM (values (3),(5)) as t(val) ".query[Int]

// Fails
val limit : Int = 2
val queryLessWorking = sql" SELECT TOP ( $limit ) val FROM (values (3),(5)) as t(val) ".query[Int]
```

I did the best I could,

**Comment by lilgreenbird** [comment]
hi @Quafadas 
I think I see what the issue is now, I will be working on a fix. Thanks for the patience.
