### ISSUE TITLE
Insertion of NULLs into GUID column in bulk mode

### ISSUE THREAD

**Issue by andreitokar** [microsoft/mssql-jdbc#1777]
## Driver version
9.4.1, 10.2.0

## SQL Server version
Microsoft SQL Server 2016 (SP2-CU15) (KB4577775) - 13.0.5850.14 (x64)  
Sep 17 2020 22:12:45
Copyright (C) 2019 Microsoft Corporation
Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: )

## Client Operating System
Windows 10

## JAVA/JVM version
1.8.0

## Table schema
CTEATE TABLE test (u_id UNIQUEIDENTIFIER);
INSERT INTO test(u_id) VALUES (?);

## Problem description
Unable to insert NULL value into UNIQUEIDENTIFIER column in bulk insert mode (;useBulkCopyForBatchInsert=true), neither with setString(1,null), nor with setNull(1, VARCHAR).

## Expected behavior
record inserted into table

## Actual behavior
Exception is thrown

## Error message/stack trace
Data type guid is not supported in bulk copy.

**Comment by v-zhangw** [comment]
Hi @andreitokar,

Thanks for reaching out, we will be taking a look shortly.

**Comment by v-zhangw** [comment]
Hello @andreitokar,

Could you provide some more context on what you are trying to do?
Are you trying to insert a null value with bulkcopy or inserting a null value via some other method while useBulkCopyForBatchInsert=true is set?

It would help a lot to see the java stack trace with the JDBC exception and a small java app reproducing the problem.

**Comment by andreitokar** [comment]
Hi @v-zhangw. Yes, i was trying to insert a bunch of records by using PreparedStatement INSERT in a batch mode. Target table has a column of type UNIQUEIDENTIFIER and some rows should have NULLs in this column (pls. see "TABLE SCHEMA" section above for example of table definition and INSERT statement). To improve performance, I would like to use bulkCopy mode, but if any of the values for ? parameter are NULL, batch execution fails with exception listed in "Error Message" section.

Due to an obvious omission, exception is thrown [here](https://github.com/microsoft/mssql-jdbc/blob/82a1c5dae01cecb8cbaab3e4ef5a7420d44f1981/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java#L2048)   
I do not have a full stack trace, because it was truncated due to the fact that it's is multi-threaded, spring boot application, and trace has tons of unrelated entries instead.
Everything works just fine after proposed PR #1778 has been applied.

**Comment by v-zhangw** [comment]
Thanks @andreitokar,
We will try to review your PR and test it soon.

**Comment by lilgreenbird** [comment]
hi @andreitokar 

apologies this took a bit longer than expected as we were busy with our [11.1.0 preview release.](https://github.com/microsoft/mssql-jdbc/releases/tag/v.11.1.0) We will get back to reviewing the PR as soon as possible.

**Comment by lilgreenbird** [comment]
hi @andreitokar 

thank you for the PR, however could you please include a test case for this?

**Comment by lilgreenbird** [comment]
PR#1778
