### ISSUE TITLE
TimeoutPoller leaks memory when query frequency is high

### ISSUE THREAD

**Issue by johnny-egeland** [microsoft/mssql-jdbc#1781]
## Driver version
com.microsoft.sqlserver:mssql-jdbc:10.2.0.jre17

## SQL Server version
Microsoft SQL Server 2019 (RTM-CU9) (KB5000642) - 15.0.4102.2 (X64) 
	Jan 25 2021 20:16:12 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor)

## Client Operating System
Ubuntu 20.04.4 LTS

## JAVA/JVM version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

## Table schema
Not applicable

## Problem description
Any "TimeoutCommands" entered into the "TimeoutPoller" is retained in the poller until the entire Timeout period has elapsed. The command is not removed when it's completed or closed. In our application the default timeout period is (or was) 1800 seconds, and the ArrayList retaining these commands grew very large when the SQL query volume was high. On our culprit server, the memory usage peaked at 17 Gb when the VM ran out of memory.

I do realize that the timeout can be shortened dramatically on my side. But I still don't think it's a good idea to retain commands to a fixed timeout period, as this means I need to "tune" this in order to get an acceptable middle line between working properly; a.e. long running queries are not canceled, while I don't run out of memory due to completed queries (as most of them complete quickly). They should be removed when they are complete.

## Expected behavior
The poller should check if the command is complete, and remove it from the poller if so. Suggested patch to the code (not testet, nor verified if it is thread-safe and race condition free):
```
diff --git a/src/main/java/com/microsoft/sqlserver/jdbc/TimeoutPoller.java b/src/main/java/com/microsoft/sqlserver/jdbc/TimeoutPoller.java
index 6c53d4d7..ab69c836 100644
--- a/src/main/java/com/microsoft/sqlserver/jdbc/TimeoutPoller.java
+++ b/src/main/java/com/microsoft/sqlserver/jdbc/TimeoutPoller.java
@@ -61,7 +61,10 @@ final class TimeoutPoller implements Runnable {
                     while (timeoutCommandIterator.hasNext()) {
                         TimeoutCommand<TDSCommand> timeoutCommand = timeoutCommandIterator.next();
                         try {
-                            if (timeoutCommand.canTimeout()) {
+                            if (timeoutCommand.getCommand().getRequestComplete()) {
+                                timeoutCommandIterator.remove();
+                            }
+                            else if (timeoutCommand.canTimeout()) {
                                 try {
                                     timeoutCommand.interrupt();
                                 } finally {
```

## Actual behavior
The server VM runs out of memory when there are a lot of queries within a short(-ish) time period.

## Error message/stack trace
We get OutOfMemoryExceptions... Stack traces for those are not related to the driver... However, here is a screenshot from my profiler:
![TimeoutPollerMemoryLeak](https://user-images.githubusercontent.com/89024642/160547037-191f09d8-b220-4ecb-9c67-cab26138114b.png)

## Any other details that can be helpful
No, I think the cause is pretty clear...

## JDBC trace logs
Not really applicable here.

**Comment by v-zhangw** [comment]
Hi @johnny-egeland,
Thank you for reaching out, we will be taking a look shortly.

**Comment by v-zhangw** [comment]
@johnny-egeland 
The suggested change in logic sounds reasonable. Implementation would still need testing. Will try to test your PR soon.

**Comment by johnny-egeland** [comment]
@v-zhangw The suggested change was the simplest way I could come up with, and it seems to have some side effects on the Windows and Mac tests? Looking briefly at it, I can't really tell why, as I can't exactly think of any reasons why something would have a dependency on a completed command being present in the TimeoutPoller specifically. I mean, commands only get added there when a queryTimeout is used, and it is not by default. I run Ubnutu myself, so I'm not sure I can reproduce the test problems myself. In any case, I don't have time to look any closer at it for the time being. But I will take a look as soon as I can unless you get around to it first.

**Comment by johnny-egeland** [comment]
@v-zhangw The Pull-Request suddenly seems OK now. Not sure why it has changed. Let me know if I need to make any changes, or if you have any suggestions for a better approach for fixing the issue.

**Comment by johnny-egeland** [comment]
I created another pull request using a slightly different approach to fix this:
https://github.com/microsoft/mssql-jdbc/pull/1789

This handles removal of the command from the poller on command completion. This means it does not need to wait until the next timeout poller tick to free up memory. However, the downside (as an ArrayList is used to retain the commands), is another list scan to find the entry to remove. So this will perform slightly worse CPU wise, while being somewhat better memory wise.

**Comment by lilgreenbird** [comment]
this is obsoleted by PR#1794
