### ISSUE TITLE
Request for jdbc 4.0

### ISSUE THREAD

**Issue by harris-yin** [Microsoft/mssql-jdbc#182]
Recently I meet the SSL error due to the windows patch.
My application is running on JRE1.6, and can't update to 1.8 due to business reason.
I'm looking for the source code of version 4.0, and to overwrite it to avoid the SSL error.

**Comment by ajlam** [comment]
@harris-yin, unfortunately JDBC 4.0 is not open sourced. However, the source code here is very similar in terms of existing functionality. Although JDBC 4.0 and JRE 1.6 are out of service, we might be able to try to understand the issue you're running into. Can you please the callstack and the exact error message?

**Comment by harris-yin** [comment]
I did get the error message but it was no in English.
I found following blog dealing the same error with me, so that point me to fix my jdbc driver.
https://blogs.msdn.microsoft.com/dataaccesstechnologies/2016/11/30/intermittent-jdbc-connectivity-issue-the-driver-could-not-establish-a-secure-connection-to-sql-server-by-using-secure-sockets-layer-ssl-encryption-error-sql-server-returned-an-incomplete-respons/

**Comment by ajlam** [comment]
@harris-yin, there are two supported methods of configuring cipher suites:

- Via GP: https://msdn.microsoft.com/en-us/library/windows/desktop/bb870930(v=vs.85).aspx
- Via cmdlets: https://technet.microsoft.com/en-us/library/dn296632.aspx
               - Available on Win10/Server2016 only.

**Comment by harris-yin** [comment]
Yeah, I did know that solution.
I thought the best way to solve my problem should do no change with my system security setting.
But it seems disable cipher suites is the only method now.
Thanks for your kindly help.

**Comment by harris-yin** [comment]
@ajlam One more thing to confirm.
These two cipher suites should be disable on application side or DB side?

**Comment by ajlam** [comment]
@harris-yin, disable them on the SQL Server host machine.
