### ISSUE TITLE
[QUESTION] how to set tenant id for auth type: ActiveDirectoryServicePrincipal

### ISSUE THREAD

**Issue by JStooke** [microsoft/mssql-jdbc#1822]
## Question
Using mssql-jdbc-10.2.0.jre8.jar following the wiki to use authentication: ActiveDirectoryServicePrincipal appears to only require parameters:
- username (populated with Client ID)
- password (populated with Client Secret)
- authentication (populated with ActiveDirectoryServicePrincipal)

Without being able to specify the tenantid authentication fails as its different to the tenant the machine running the script is on. Is there any way to specify it similar to the ODBC parameter AadAuthority?

I'll be honest i'm assuming the error is a missing tenantid, the current error is below:

03-May-2022 13:36:22.016 WARNING [server-command-33] com.matillion.bi.emerald.server.model.util.jdbc.JDBCQueryHelper.getIdentifierQuoteString Failed to authenticate the user xxxxxxxxxxxxxxxxxxxx in Active Directory (Authentication=ActiveDirectoryServicePrincipal). com/nimbusds/common/contenttype/ContentType
	com.microsoft.sqlserver.jdbc.SQLServerException: Failed to authenticate the user xxxxxxxxxxxxxxxxxx in Active Directory (Authentication=ActiveDirectoryServicePrincipal). com/nimbusds/common/contenttype/ContentType
		at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getCorrectedException(SQLServerMSAL4JUtils.java:240)
		at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getSqlFedAuthTokenPrincipal(SQLServerMSAL4JUtils.java:97)
		at com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:5341)
		at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:5293)
		at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:5180)
		at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:305)
		at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:128)
		at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
		at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6162)
		at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4785)
		at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$100(SQLServerConnection.java:90)
		at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4723)
		at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7785)
		at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3793)
		at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3233)
		at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)
		at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)
		at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)
		at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)
		at com.matillion.bi.emerald.server.model.jdbc.ConnectionManager.getConnection(ConnectionManager.java:73)
		at com.matillion.bi.emerald.server.model.util.jdbc.JDBCQueryHelper.getIdentifierQuoteString(JDBCQueryHelper.java:798)
		at com.matillion.bi.emerald.component.implementation.orchestration.loadunload.DatabaseLoad.getMetadataDetails(DatabaseLoad.java:320)
		at com.matillion.bi.emerald.shared.command.components.sqleditor.GetMetadataDetails.run(GetMetadataDetails.java:78)
		at com.matillion.bi.emerald.shared.command.components.sqleditor.GetMetadataDetails.run(GetMetadataDetails.java:33)
		at com.matillion.bi.emerald.shared.model.command.CallbackServerCommand$CallbackCommandEvent.run(CallbackServerCommand.java:65)
		at com.matillion.bi.emerald.server.controller.ServerModelManager.fire(ServerModelManager.java:418)
		at sun.reflect.GeneratedMethodAccessor340.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
		at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
		at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
		at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
		at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
		at com.google.common.eventbus.EventBus.post(EventBus.java:212)
		at com.matillion.bi.emerald.server.controller.ServerCommandExecutor$CommandEventTask.run(ServerCommandExecutor.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)

Cheers

**Comment by tkyc** [comment]
Hi, tenant id shouldn't be required from what I understand. Just confirming, so you're following this guide right? [https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver15#connect-using-activedirectoryserviceprincipal-authentication-mode](url)

From the stacktrace, it doesn't look like it is showing the MSAL error. Could you set a breakpoint in this function and check the `ExecutionException`? It should be accessed by `e.getMessage()`. https://github.com/microsoft/mssql-jdbc/blob/0c703a74888da1897d2feb261d0ca91693caa422/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerMSAL4JUtils.java#L213

**Comment by JStooke** [comment]
Hi, thanks for responding so quickly, really appreciate it. So the driver is used by an existing app so unable to add breakpoints but turned logging level to finest and the driver does indeed identify the appropriate tenant when initially communicating with the server. So as you rightly pointed out, my assumption that a missing tenantid was the problem was wrong. 

The more detailed logs below. 

Interestingly a similar question recently popped up on stackoverflow: [https://stackoverflow.com/questions/72044650/unable-to-connect-to-azure-db-using-jdbc-with-activedirectoryserviceprincipal](url) with an identical issue. 

Noticed "com/nimbusds/common/contenttype/ContentType" popping up a lot. Am I perhaps missing a dependency?

04-May-2022 07:43:48.723 FINE [server-command-38] com.microsoft.sqlserver.jdbc.SQLServerDriver.connect Microsoft JDBC Driver 10.2.0.0 for SQL Server
04-May-2022 07:43:48.723 FINE [server-command-38] com.microsoft.sqlserver.jdbc.Util.parseUrl Property:serverName Value:***servername***
04-May-2022 07:43:48.723 FINE [server-command-38] com.microsoft.sqlserver.jdbc.Util.parseUrl Property:databaseName Value:***dbname***
04-May-2022 07:43:48.723 FINE [server-command-38] com.microsoft.sqlserver.jdbc.SQLServerConnection.<init> ConnectionID:5 created by (SQLServerDriver:1)
04-May-2022 07:43:48.723 FINE [server-command-38] com.microsoft.sqlserver.jdbc.SQLServerConnection.login ConnectionID:5 This attempt server name: ***servername*** port: 1433 InstanceName: null useParallel: false
04-May-2022 07:43:48.723 FINE [server-command-38] com.microsoft.sqlserver.jdbc.SQLServerConnection.login ConnectionID:5 This attempt endtime: 1651650231723
04-May-2022 07:43:48.723 FINE [server-command-38] com.microsoft.sqlserver.jdbc.SQLServerConnection.login ConnectionID:5 This attempt No: 0
04-May-2022 07:43:48.723 FINE [server-command-38] com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper ConnectionID:5 Connecting with server: ***servername*** port: 1433 Timeout slice: 3000 Timeout Full: 3
04-May-2022 07:43:48.768 FINE [server-command-38] com.microsoft.sqlserver.jdbc.SQLServerConnection.Prelogin ConnectionID:5 ClientConnectionId: 0b9d0616-d7be-4986-b4d7-46ed60d82113 Server returned major version:12
04-May-2022 07:43:48.830 FINE [server-command-38] com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo ConnectionID:5 ClientConnectionId: 0b9d0616-d7be-4986-b4d7-46ed60d82113 FEDAUTHINFO token stream length = 204
04-May-2022 07:43:48.830 FINE [server-command-38] com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo ConnectionID:5 ClientConnectionId: 0b9d0616-d7be-4986-b4d7-46ed60d82113 CountOfInfoIDs = 2
04-May-2022 07:43:48.830 FINE [server-command-38] com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo ConnectionID:5 ClientConnectionId: 0b9d0616-d7be-4986-b4d7-46ed60d82113 Read rest of FEDAUTHINFO token stream: [*\*\*]
04-May-2022 07:43:48.830 FINE [server-command-38] com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo ConnectionID:5 ClientConnectionId: 0b9d0616-d7be-4986-b4d7-46ed60d82113 FedAuthInfoOpt: ID=2, DataLen=58, Offset=22
04-May-2022 07:43:48.830 FINE [server-command-38] com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo ConnectionID:5 ClientConnectionId: 0b9d0616-d7be-4986-b4d7-46ed60d82113 FedAuthInfoData: https://database.windows.net/
04-May-2022 07:43:48.830 FINE [server-command-38] com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo ConnectionID:5 ClientConnectionId: 0b9d0616-d7be-4986-b4d7-46ed60d82113 FedAuthInfoOpt: ID=1, DataLen=124, Offset=80
04-May-2022 07:43:48.830 FINE [server-command-38] com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo ConnectionID:5 ClientConnectionId: 0b9d0616-d7be-4986-b4d7-46ed60d82113 FedAuthInfoData: https://login.windows.net/ ***tenantid***
04-May-2022 07:43:48.984 FINE [server-command-38] com.microsoft.sqlserver.jdbc.SQLServerException.logException *** SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: Failed to authenticate the user ***clientid*** in Active Directory (Authentication=ActiveDirectoryServicePrincipal). com/nimbusds/common/contenttype/ContentType Failed to authenticate the user ***clientid*** in Active Directory (Authentication=ActiveDirectoryServicePrincipal). com/nimbusds/common/contenttype/ContentType
04-May-2022 07:43:48.985 FINE [server-command-38] com.microsoft.sqlserver.jdbc.SQLServerException.logException 
	com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getCorrectedException(SQLServerMSAL4JUtils.java:240)
	com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getSqlFedAuthTokenPrincipal(SQLServerMSAL4JUtils.java:97)
	com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:5341)
	com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:5293)
	com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:5180)
	com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:305)
	com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:128)
	com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6162)
	com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4785)
	com.microsoft.sqlserver.jdbc.SQLServerConnection.access$100(SQLServerConnection.java:90)
	com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4723)
	com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7785)
	com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3793)
	com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3233)
	com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)
	com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)
	com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)
	com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)
	com.matillion.bi.emerald.server.model.jdbc.ConnectionManager.getConnection(ConnectionManager.java:73)
	com.matillion.bi.emerald.server.model.util.jdbc.JDBCQueryHelper.getIdentifierQuoteString(JDBCQueryHelper.java:798)
	com.matillion.bi.emerald.component.implementation.orchestration.loadunload.DatabaseLoad.getMetadataDetails(DatabaseLoad.java:320)
	com.matillion.bi.emerald.shared.command.components.sqleditor.GetMetadataDetails.run(GetMetadataDetails.java:78)
	com.matillion.bi.emerald.shared.command.components.sqleditor.GetMetadataDetails.run(GetMetadataDetails.java:33)
	com.matillion.bi.emerald.shared.model.command.CallbackServerCommand$CallbackCommandEvent.run(CallbackServerCommand.java:65)
	com.matillion.bi.emerald.server.controller.ServerModelManager.fire(ServerModelManager.java:418)
	sun.reflect.GeneratedMethodAccessor342.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
	com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
	com.google.common.eventbus.EventBus.post(EventBus.java:212)
	com.matillion.bi.emerald.server.controller.ServerCommandExecutor$CommandEventTask.run(ServerCommandExecutor.java:47)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	java.lang.Thread.run(Thread.java:748)
	 caused by java.util.concurrent.ExecutionException: java.lang.RuntimeException: com/nimbusds/common/contenttype/ContentType
		com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getCorrectedException(SQLServerMSAL4JUtils.java:238)
		com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getSqlFedAuthTokenPrincipal(SQLServerMSAL4JUtils.java:97)
		com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:5341)
		com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:5293)
		com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:5180)
		com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:305)
		com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:128)
		com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
		com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6162)
		com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:4785)
		com.microsoft.sqlserver.jdbc.SQLServerConnection.access$100(SQLServerConnection.java:90)
		com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:4723)
		com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7785)
		com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3793)
		com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3233)
		com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)
		com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)
		com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)
		com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)
		com.matillion.bi.emerald.server.model.jdbc.ConnectionManager.getConnection(ConnectionManager.java:73)
		com.matillion.bi.emerald.server.model.util.jdbc.JDBCQueryHelper.getIdentifierQuoteString(JDBCQueryHelper.java:798)
		com.matillion.bi.emerald.component.implementation.orchestration.loadunload.DatabaseLoad.getMetadataDetails(DatabaseLoad.java:320)
		com.matillion.bi.emerald.shared.command.components.sqleditor.GetMetadataDetails.run(GetMetadataDetails.java:78)
		com.matillion.bi.emerald.shared.command.components.sqleditor.GetMetadataDetails.run(GetMetadataDetails.java:33)
		com.matillion.bi.emerald.shared.model.command.CallbackServerCommand$CallbackCommandEvent.run(CallbackServerCommand.java:65)
		com.matillion.bi.emerald.server.controller.ServerModelManager.fire(ServerModelManager.java:418)
		sun.reflect.GeneratedMethodAccessor342.invoke(Unknown Source)
		sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		java.lang.reflect.Method.invoke(Method.java:498)
		com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
		com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
		com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
		com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
		com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
		com.google.common.eventbus.EventBus.post(EventBus.java:212)
		com.matillion.bi.emerald.server.controller.ServerCommandExecutor$CommandEventTask.run(ServerCommandExecutor.java:47)
		java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		java.util.concurrent.FutureTask.run(FutureTask.java:266)
		java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		java.lang.Thread.run(Thread.java:748)

Thanks again!

**Comment by tkyc** [comment]
Hi @JStooke, I've uploaded a modified driver jar to this comment (I changed it so that the MSAL error message should print instead since you were unable to debug on your end). Could you use my modified driver jar to attempt another login and then share the stacktrace again? Hopefully the MSAL error might add more visibility to the exact issue.

Right, as for the `com/nimbusds/common/contenttype/ContentType`, I believe that's a compile dependency of MSAL so it's needed for running, might also be worth a check to see if you have that dependency.
[mssql-jdbc-10.2.0.jre8.zip](https://github.com/microsoft/mssql-jdbc/files/8634541/mssql-jdbc-10.2.0.jre8.zip)

**Comment by tkyc** [comment]
Closing as thread has been inactive. We can reopen if necessary.

**Comment by JStooke** [comment]
@tkyc apologies for the delay getting back to this. Thanks very much for providing the augmented file. 

It did indeed point to the missing ContentType dependency:
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/nimbusds/common/contenttype/ContentType
		at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getCorrectedException(SQLServerMSAL4JUtils.java:238)

I've added content-type-2.2.jar alongside the mssql driver and connected successfully! thanks again for your support!

Being quite new to the java game, is there any reasoning behind a dependency being embedded or not at compile time? Presumably content-type-2.2.jar is seen as such a common dependency that its not included by default?

Cheers

**Comment by tkyc** [comment]
@JStooke, happy to help. Glad it's working for you now.

So in the past, the mssql-jdbc driver would package all the required dependencies in an [uber jar](https://stackoverflow.com/questions/11947037/what-is-an-uber-jar). However, due to security compliancy we can't do that anymore. So unfortunately, if you use the standalone driver jar you'll need to manually resolve dependencies and transitive dependencies.

For future reference and for anyone who stumbles across this thread, to get all the required dependencies for the driver you can follow the guide [here](https://github.com/microsoft/mssql-jdbc/wiki/Download-MSAL4J-And-AKV-Dependencies-with-Apache-Maven).
