### ISSUE TITLE
Error in connection properties jaasConfigurationName SQL Server JDBC Driver JASSConfiguration

### ISSUE THREAD

**Issue by pcnchang** [microsoft/mssql-jdbc#1835]
## Driver version
All versions since 6.1.7 jre8

## SQL Server version
It does not matter.

## Client Operating System
Redhat Enterprise Linux 8.5

## JAVA/JVM version
OpenJDK 1.8.0u312

## Table schema
N/A

## Problem description
From https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver15
The JAAS configuration name is passed via "jaasConfigurationName".
It seems to be a typo. From your JDBC driver, it shall be "JASSConfigurationName".

## Expected behavior
JAAS configuration name shall be passed in to jaasConfigurationName however it fails to pass that properties to JDBC Driver.
   JASSConfigurationName="jaas1" e.g. works.
  jassConfigurationName=jaas1 does not work.

If this is a documentation error from Microsoft. Please kindly correct them via your internal channel. Many thanks.

**Comment by David-Engel** [comment]
Thanks. This looks to be a long-standing typo in the API itself, not the connection string property. The connection string property is "jaasConfigurationName" and the driver expect it as such. Only the API on SQLServerDataSource has the typo, "setJASSConfigurationName"/"getJASSConfigurationName". Fortunately that API is little-used so the impact is minimal. We'll consider fixing it in a future release.

Thanks,
David

**Comment by pcnchang** [comment]
Many thanks! I will let IBM folks know as well. Any possible estimate of ETA or next patched JDBC driver from SQL Server database team?

**Comment by v-zhangw** [comment]
Hi @pcnchang, we plan on having this fixed by our next Stable release at the end of July. It may also make the next preview release which is in early June.

**Comment by mswatosh** [comment]
When this is fixed can the original "setJASSConfigurationName"/"getJASSConfigurationName" be left in as deprecated, and pointed to the new setJAASConfigurationName/getJAASConfigurationName methods? This would prevent breaking any customer that are currently using the properties.

> Fortunately that API is little-used so the impact is minimal. 
WebSphere uses this API to set properties specified in configuration (and other application servers may as well), so the impact may be greater than expected.

**Comment by lilgreenbird** [comment]
hi @mswatosh 

Thank you for your input. We will keep the misspelled APIs for the upcoming release however they will be deprecated and then removed in later releases.

Thanks
