### ISSUE TITLE
Authentication error when using certain non-English Windows language settings

### ISSUE THREAD

**Issue by Avery-Dunn** [microsoft/mssql-jdbc#1839]
## Driver version
10.2.0.0

## Client Operating System
Windows 10

## JAVA/JVM version
Java 11

## Problem description
When trying to log into an Azure SQL Server managed instance via Azure Directory Interactive and using DataGrip, a login page is displayed but after entering credentials the authentication attempt times out after two minutes with an error message that comes from a thrown `com.microsoft.sqlserver.jdbc.SQLServerException` exception : 

`The specified database user/password combination is rejected: Fehler beim Authentifizieren des Benutzers "xxx@yyy" in Active Directory (Authentication=ActiveDirectoryInteractive). No Authorization code was returned from the server`

`<message>*** SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: Fehler beim Authentifizieren des Benutzers "xxx" in Active Directory (Authentication=ActiveDirectoryInteractive). No Authorization code was returned from the server Fehler beim Authentifizieren des Benutzers "xxx" in Active Directory (Authentication=ActiveDirectoryInteractive). No Authorization code was returned from the server</message>`

However, this only occurs when the Window's system language is something other than English. Several users have reported being able to reproduce this issue when their system language is French or German, and for all of them setting their system language to English allows them to authenticate.

See this issue in the MSAL Java repo for more background info: https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/492

## Expected behavior
The login page appears, user enters their credentials, the authentication is successful.

## Actual behavior
After two minutes, the authentication attempt fails. This occurs if Window's system language is French or German, and changing it to English allows logins to succeed.

## Error message/stack trace
`<message>*** SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: Fehler beim Authentifizieren des Benutzers "xxx" in Active Directory (Authentication=ActiveDirectoryInteractive). No Authorization code was returned from the server Fehler beim Authentifizieren des Benutzers "xxx" in Active Directory (Authentication=ActiveDirectoryInteractive). No Authorization code was returned from the server</message>`

(see [this comment](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/492#issuecomment-1105604854) in the MSAL Java repo for a more logs from the person who originally reported this issue)

## Any other details that can be helpful
The issue was first reported in the MSAL Java repo (https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/492), but we haven't been able to reproduce it when using the msal4j package on its own (see [this comment](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/492#issuecomment-1137861016)), which is why we believe the issue is somewhere on the mssql-jdbc side of things and are opening this thread for better tracking.

Multiple users have reported having this problem when the operating system's language is French or German, and that changing it to English solves the problem. Other languages may cause it too, but this hasn't been reported/we couldn't reproduce it.

The users who reported it seem to all be using DataGrip, not sure if it happens in other contexts.

## JDBC trace logs
See [this comment](https://github.com/AzureAD/microsoft-authentication-library-for-java/issues/492#issuecomment-1105604854) in the MSAL Java repo for a full log from the person who originally reported this issue (didn't want to upload their stuff here without asking)

**Comment by tkyc** [comment]
Hey @Avery-Dunn thanks for reaching out.

As I was investigating this more on the driver side, I narrowed the problem down to `htmlMessageSuccess()` from the MSAL library. I think I was quick to blame the driver as the cause of the problem as I thought it had something to do with our localization process.

So within the driver, depending on the cx's system's language (eg. German), the driver passes in a localized string to `htmlMessageSuccess()` (this function seems to be the cause of the problem). When I was playing around with the MSAL library some more, I noticed that when I pass in a string that is not English to `htmlMessageSuccess()`, I would get that `No Authorization code was returned from the server` message. However, its works just fine with an English string.

On the MSAL side could you confirm that this is the correct behaviour of `htmlMessageSuccess()`? Does this function only work with English strings and not strings in other languages? If that's the case, on the driver side we'll need to correct the driver code.

I attached some code to this comment that reproduces the issue solely with the MSAL library. Thanks for the help.
[ReproApp.zip](https://github.com/microsoft/mssql-jdbc/files/8789974/ReproApp.zip)

**Comment by tkyc** [comment]
Hi @Avery-Dunn, after some more debugging I believe I found the cause of the problem. I opened a PR for the MSAL library [here](https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/511) to fix it.

**Comment by Avery-Dunn** [comment]
Thanks to the fix by @tkyc in https://github.com/AzureAD/microsoft-authentication-library-for-java/pull/511 in MSAL Java's [recent release](https://github.com/AzureAD/microsoft-authentication-library-for-java/releases/tag/v1.13.0), this issue should be resolved.
