### ISSUE TITLE
Clarify depracted Lob public constructors

### ISSUE THREAD

**Issue by marschall** [Microsoft/mssql-jdbc#185]
Both `SQLServerClob` and `SQLServerBlob` have deprecated public constructors. They are not used by the driver itself. I assume they are there to avoid breaking clients. I assume `Connection#createClob` and `Connection#createBlob` should be used instead. If that's true then it would be nice if this was documented in an `@deprecated` Javadoc tag and possibly in some kind of versioning policy on when the constructors will be removed.

**Comment by v-afrafi** [comment]
@marschall Thank you for pointing out this . We will update the javadocs for these constructors. But for now, we will not be removing the deprecated ones.

**Comment by v-afrafi** [comment]
fixed by PR #226.
