### ISSUE TITLE
Big performance regression 8.2.2.0 -> 10.2.1

### ISSUE THREAD

**Issue by zeekoe** [microsoft/mssql-jdbc#1860]
## Driver version
Impacted version: mssql-jdbc-10.2.1.jre11.jar
Better performing version: 8.2.2.0 (I can get the jre if that's relevant; probably 8, possibly 11)

## SQL Server version
Microsoft SQL Server 2017 (RTM-CU29-GDR) (KB5014553) - 14.0.3445.2 (X64) 
	May 29 2022 12:36:31 
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

## Client Operating System
Red Hat Enterprise Linux Server 7.9

## JAVA/JVM version
OpenJDK 11.x
Hibernate 5.3.14.Final

## Table schema
not relevant

## Problem description
While testing on acceptance environment, we found out that certain batch jobs take a significant longer amount of time (2 to 4 times slower). In a piece of code that does some processing and writes data, this is the output of a practical run.

On the left, the hour/minute of the day, on the right the amount of records created.

8.x:

minute | count
-- | --
02:10 | 1411
02:11 | 13480
02:12 | 13365
02:13 | 13383
02:14 | 9124
02:16 | 578

10.x:

minute | count
-- | --
02:11 | 2069
02:12 | 2860
02:13 | 2880
02:14 | 2549
02:15 | 3084
02:16 | 2426
02:17 | 3319
02:18 | 2996
02:19 | 2704
02:20 | 1026
02:21 | 527
02:22 | 594
02:23 | 576
02:24 | 649
02:25 | 1955
02:26 | 3089
02:27 | 3337
02:28 | 3441
02:29 | 2999
02:30 | 2912
02:31 | 2766
02:32 | 1564

All in all, the processes will take up too much time for a night job after the driver update.

We don't do complex stuff; we do use hibernate for persistence, running on JBoss that manages the transactions. I didn't trace the logs, but I think all select + insert stuff is done in one big transaction, so all these tens of thousands of records will be inserted in one transaction.

Has there been performance testing on 10.2.x vs 8.x, and is this consistent with your testing?

**Comment by Chrriis** [comment]
@zeekoe Could it be another case of bug #1196? One way to test would be to use the 11.1.2 preview, see if it has the bug, and activate the connection property `prepareMethod` with a value of `prepare` to see if that fixes the issue.

**Comment by zeekoe** [comment]
Thanks a lot! I didn't think of checking closed issues, but indeed, this very much looks like a duplicate of that. We'll wait for 11.x to be out of preview.
