### ISSUE TITLE
[QUESTION] sp_reset_connection and connection pooling

### ISSUE THREAD

**Issue by SpaceCondor** [microsoft/mssql-jdbc#1861]
## Question

What is the recommended way to handle connection pooling and the inability to have `sp_reset_connection `called when a connection is returned to the pool?

When using connection pooling, the current behavior of the JDBC driver is to not call the `sp_reset_connection` stored procedure when the connection is returned to the pool. This leads to issues with temporary tables and other things that are typically reset when `sp_reset_connection` is executed.

Per the documentation: 

> The JDBC driver does not currently call the sp_reset_connection stored procedure when it returns the connection to the pool. Instead, the driver relies on third-party Java Application Servers to return the connections back to their original states.

My first thought was to manually call `exec sp_reset_connection` when a connection is returned manually, but that stored procedure is internal and cannot be called manually.

**Comment by tkyc** [comment]
Hi, @SpaceCondor I'm afraid there isn't a manual way to call `sp_reset_connection` using the driver. Within the driver, we set a reset bit in the next command to the server to reset the connection. This only works if the 3rd party pooling library implements the pooling interfaces. 

Like you shared, as per the documentation, the driver depends on 3rd party pooling libraries to reset the connection. I suspect if the connection isn't being reset, then the pooling library needs to implement the pooling interfaces. I think it's best to direct this question to the team responsible for the pooling library you're using.

**Comment by tkyc** [comment]
@SpaceCondor I'd recommend either Apache's [dbcp2](https://mvnrepository.com/artifact/org.apache.commons/commons-dbcp2) or [HikariCP](https://mvnrepository.com/artifact/com.zaxxer/HikariCP) as we test the driver with those pooling libraries.

**Comment by tkyc** [comment]
@SpaceCondor Hmm, that is odd. I believe we've been testing with HikariCP for a long time. I'll do some digging on the subject and get back to you. In the mean time, would it be possible for you to try dbcp2?

**Comment by SpaceCondor** [comment]
@tkyc Yup, will do! I'll let you know if I find anything as well.

**Comment by tkyc** [comment]
@SpaceCondor Unfortunately, it looks like HikariCP doesn't use the required pooling APIs. There's a discussion about it [here](https://github.com/brettwooldridge/HikariCP/issues/54).

I looked through the dbcp2 project and it looks like they do use the pooling APIs. So, I believe it should work.

**Comment by SpaceCondor** [comment]
@tkyc Thank you for the feedback! Glad to know I wasn't missing something with HikariCP. I'll investigate using dbcp2 as a replacement.

Thanks again for the help!
