### ISSUE TITLE
Support sql server 2008 R2

### ISSUE THREAD

**Issue by Thinh-origami** [microsoft/mssql-jdbc#1867]
is there any version of SQL-JDBC that still support sql server 2008 R2 ?, I use JDK 18.

**Comment by tkyc** [comment]
@Thinh-origami Yes, currently according to this [matrix](https://docs.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix?view=sql-server-ver16) version 7.2 of the driver is the most recent driver version that supports 2008 R2.
