### ISSUE TITLE
11.2.0 fails to deploy in OSGi environment without msal4j

### ISSUE THREAD

**Issue by MrEasy** [microsoft/mssql-jdbc#1892]
## Driver version
11.2.0

## SQL Server version
Microsoft SQL Server 2019 (RTM-GDR) (KB5014356) - 15.0.2095.3 (X64)   Apr 29 2022 18:00:13   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 22000: ) (Hypervisor) 
(but unrelated to issue)

## Client Operating System
Win 11 (but unrelated)

## JAVA/JVM version
17.0.4  (but unrelated)

## Problem description
This change here:
-  _Added explicit dependency for com.microsoft.azure.msal4j (was a transitive dependency in previous releases) [1863](https://github.com/microsoft/mssql-jdbc/pull/1863)_

introduced an explicit dependency on msal4j (which is good compared to the transitive before), but seems to have missed to flag it as optional, like the others.
https://github.com/microsoft/mssql-jdbc/pull/1863/commits/ef14c5bdb5bca8364639e47899513277306527a4

As a result, the driver will not deploy anymore in an OSGi environment without that dependency:
``org.apache.felix.resolver.reason.ReasonException: Unable to resolve com.microsoft.sqlserver.mssql-jdbc/11.2.0: missing requirement [com.microsoft.sqlserver.mssql-jdbc/11.2.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.microsoft.aad.msal4j)(version>=1.13.0)(!(version>=2.0.0)))"``

I think this was just missed, since the optional check is still there:
https://github.com/microsoft/mssql-jdbc/blob/7f9a984170ae607fda61644e18193d0580daa632/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L5576

## Expected behavior
Dependency declared optional and deploying without successfully.

**Comment by MrEasy** [comment]
PR: https://github.com/microsoft/mssql-jdbc/pull/1893
Works fine again with this change.

**Comment by Jeffery-Wasty** [comment]
Hi @MrEasy,

Thanks for bringing this to our attention. You may be right, I'll look through our requirements again, but this should be a quick yes/no.

**Comment by lilgreenbird** [comment]
hi @MrEasy 
Thank you for bringing this to our attention. You are correct we will get this fixed in the next release.
