### ISSUE TITLE
Non-serializable field in SQLServerConnectionPoolProxy

### ISSUE THREAD

**Issue by marschall** [Microsoft/mssql-jdbc#190]
SQLServerConnectionPoolProxy implements `java.io.Serializable` but has a field `wrappedConnection` of type `SQLServerConnection` which itself does not implement `java.io.Serializable`. As a result `SQLServerConnectionPoolProxy` objects can not be serialized successfully.
My recommendation would be to remove the `java.io.Serializable` marker interface from `SQLServerConnectionPoolProxy`.

**Comment by v-xiangs** [comment]
@marschall Thank you for your input. Would you recommend we define the `wrappedConnection` as `transient`? I noticed there are some other places in the driver that SQLServerConnection objects are defined as `transient` to skip serialization on the objects. We would like to hear your suggestions. Thank you.

**Comment by marschall** [comment]
I don't think marking the `wrappedConnection` as `transient` is a good approach. Yes, it would allow for serialization to happen without exception. However after deserialization the `wrappedConnection` field would be `null`.  A `SQLServerConnectionPoolProxy` object does not seem to be usable or valid if the `wrappedConnection` is `null`. `SQLServerBlob` and friends seem to be different because they seem to be specifically coded to work with a `null` connection (I only did a superficial review).

**Comment by marschall** [comment]
I'm not super familiar with the pooling, resource and transaction specifications, but if there is no need for `SQLServerConnectionPoolProxy` to be `Serializable` then I would not make it `Serializable`. If it has to be `Serializable` then somehow a `SQLServerConnection` needs to be recreated after deserialization, even comming up with semantics for this seems to be a challenge.

**Comment by v-xiangs** [comment]
@marschall Thank you for your ideas. I totally understand your points of view. My only concern was, it might break user's existing code then I realized it's not possible since the class is not public. I will create a PR to fix it. Thank you very much for filling the issue.

**Comment by marschall** [comment]
@v-xiangs I can not see how it breaks existing code, I fully expect a `NotSerializableException` to be thrown when somebody does try to serialize a `SQLServerConnectionPoolProxy`.

**Comment by v-xiangs** [comment]
@marschall I thought SQLServerConnectionPoolProxy was public, which might break user's existing code if we remove Serializable interface from it (compilation error). Since it's not public, we do not need to worry about this. I submitted a PR for it and will merge it later. Thank you for your contribution.
