### ISSUE TITLE
Expired token exception after upgrade to 11.2.0.jre11

### ISSUE THREAD

**Issue by akleemans** [microsoft/mssql-jdbc#1908]
## Versions
**Driver version**: JDBC driver version: 11.2.0.jre11
(`com.microsoft.sqlserver:mssql-jdbc:11.2.0.jre11`)

**SQL Server version**: Microsoft SQL Azure (RTM) - 12.0.2000.8 
	Aug 10 2022 15:14:09 
	Copyright (C) 2022 Microsoft Corporation

**Client Operating System**: Linux on Azure App Service, single instance
**Docker base image**: `eclipse-temurin:11-jre-alpine`

**JAVA/JVM version**: Java 11

**Java Spring**: 2.7.2

JDBC connection string: `jdbc:sqlserver://<db-server-name>.database.windows.net:1433;database=<db-name>;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;Authentication=ActiveDirectoryMSI;`

## Problem description
Since we upgraded from `9.4.1.jre11` to `11.2.0.jre11` some days ago, we get failures periodically.

We updated 4 Microservices and all of them show the new bevhaviour: They are mostly working normally, but after some time (sometimes around a day), the one or more connection from the pool fail for around an hour (which generates around 80 exceptions in that time).

For example, we had the behaviour twice for the last 3 days (only a single service shown):

![failures](https://user-images.githubusercontent.com/1068130/187619052-7f99fdf3-bc01-4a6e-874c-e2793a7b13f3.png)

## Exception

> org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:83)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:330)
...
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80)
	... 119 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user '\<token-identified principal\>'. Token is expired. ClientConnectionId:\<uuid\>
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:300)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:133)
...

We think the JDBC token renewal process was changed with the newer version, but we don't know what exactly causes the exception. We read somewhere that Azure does a health check on active connections every now and then (10 hours?) but we do not see why this should now fail when it was working before.

**Comment by Jeffery-Wasty** [comment]
Hi @akleemans,

This seems to be very similar to another ongoing issue of ours, also with Hikari. Can you send us the configuration used in Hikari? I think 'maximum-pool-size' is what we're most concerned with now, but all the information you can send will be helpful. Additionally, is your application taking advantage of [Idle Connection Resiliency](https://docs.microsoft.com/en-us/sql/connect/jdbc/connection-resiliency?cid=kerryherger&view=sql-server-ver16)? Finally, can you please try running with these custom jars, and sending us the resulting logs. They have custom logging that should provide more insight around token expiry. If this is a token issue, this may help as well.

[Custom_Logging_Jars.zip](https://github.com/microsoft/mssql-jdbc/files/9463230/Custom_Logging_Jars.zip)

**Comment by tkyc** [comment]
Some background info on tokens within the driver. The driver doesn't cache the token, so we do not renew it. Every time a login is performed we fetch a fresh token through MSAL. If a token expiry does occur it's likely a configuration issue.

What's the the lifetime of a connection within the connection pool? By default tokens have a lifetime of 1 hour, so if the lifetime of a connection within the pool is > 1 hour then I could see an expiry happening.

**Comment by akleemans** [comment]
Hi @Jeffery-Wasty 

Thanks for the quick reply!
We use the provided standard values for Hikari. We use spring-data-jpa:2.7.2. with spring-jdbc.
We checked and `maximum-pool-size` is at default of 10. About the Idle Connection Resiliency, we don't configure it explicitly so I guess the default values are applied.

Thanks also for the Jars, we're currently checking what the easiest way is to recreate the issue on our environment with the custom jars included.

**Comment by Jeffery-Wasty** [comment]
Hi @akleemans,

Reading a bit more into this, this seems to be a common problem with HikariCP. Recommended advice is [checking the number of active connections](https://github.com/brettwooldridge/HikariCP/wiki/JDBC-Logging#microsoft-sql-server) at point of failure, to confirm whether the connections are being returned to the pool correctly. If not, this will need to be implemented. As well, if you're not using version 5.0.0, it is recommended you do, as that resolved an error where connections were not correctly being returned to the pool. Finally, as a temporary fix, you can simply increase the size of the pool, granting more connections. This is not a fix of course, but should reduce the number of exceptions while work is being done resolving the issue.

**Comment by Jeffery-Wasty** [comment]
Hi @akleemans,

Just wanted to check in and see whether the issue persists, and whether you have tried any of the solutions described above. If there is no further reply, we'll mark the issue as closed. Thanks!
