### ISSUE TITLE
Issues with TLS1.2 Encryption while client/server handshake

### ISSUE THREAD

**Issue by dinesm25** [microsoft/mssql-jdbc#1909]
Hi Team,

I have a scenario where I want to throw the exception instead of establishing the connection.
I am using a JAVA based application with JDBC thin driver.

Environment setup;

TLS1.2 server entry is added in regedit and I have disabled TLS1.2 at the server side
Server:
TLSv1 and TLS1.1 enabled
TLS1.2 disabled

Client (java app)
sslProtocol=TLSv1.2

MS SQL Driver: 9.4.1
URL:
encrypt=true 
provided cert info as well. 

Getting the below warning:
TLS1.1 was negotiated. Please update server and client to use TLSv1.2 at minimum.

But, I want the connection to be failed as the server does not support TLSv1.2. But instead of failing, it is negotiating with the server and establishing a connection. how do I prevent it?

**Comment by Jeffery-Wasty** [comment]
Hi @dinesm25,

We'll take a look at this, whether this is something we can add as a configuration option. Typically, we want to prevent as many failures as possible, and if we can do that by negotiating TLS1.1, that is probably desired, but we'll definitely look into this.

**Comment by dinesm25** [comment]
@Jeffery-Wasty Is there any way, we can access TLS server protocol version from java classes(in client app)? So that we can manually throw an exception. We tried to access SSLSocket,SSLSession, ServerSocketFactory classes. none seems to work.

**Comment by dinesm25** [comment]
@Jeffery-Wasty  We are using Oracle JAVA as our JVM. (tried with Java 8/Java 11/Java 17).  Yes. In the jdbc URL, I am passing the TLSv1.2 as sslProtocol. You can find the above environment setup for other configuration details. I am still getting negotiation warning message followed by it, the connection is getting established. Please let us know the steps to fail the connection if server and client use different sslProtocol version.

**Comment by dinesm25** [comment]
Getting this below exception if I use custom socket factory class


2022-09-07 16:30:12.86 Logon       Error: 17832, Severity: 20, State: 2.
2022-09-07 16:30:12.86 Logon       The login packet used to open the connection is structurally invalid; the connection has been closed. Please contact the vendor of the client library. [CLIENT: ::1]

**Comment by Jeffery-Wasty** [comment]
We're still looking into this. There doesn't appear to be a current configuration option to support this use case, so this will need to be scheduled for in our next planning. You mention that the server does not support TLSv1.2, which version of SQL Server are you using. I see support exists for several different versions listed [here](https://support.microsoft.com/en-us/topic/kb3135244-tls-1-2-support-for-microsoft-sql-server-e4472ef8-90a9-13c1-e4d8-44aad198cdbe).

**Comment by Jeffery-Wasty** [comment]
Hi @dinesm25,

Just checking in to see if you're able to provide more information on your configuration. As said in the prior messages, the behavior that the driver currently has around TLS1.2 and re-negotiation is unlikely to change, and thus we'll probably move forward with closing the issue. We'd like to know if there is any possibility the server you're using can in no way support TLS1.2, in which case we'll need to re-examine this to ensure compatibility with situations similar to this one. Please let us know. Thanks!

**Comment by Jeffery-Wasty** [comment]
Hi @dinesm25,

We'll close the issue for inactivity. If you would like to discuss this issue further, feel free to leave a comment, and we can re-open it if necessary.
