### ISSUE TITLE
DatabaseMetadata.getColumns() is not returning all columns of table 

### ISSUE THREAD

**Issue by www-viveksharma** [microsoft/mssql-jdbc#1911]
## Driver version
10.2.1.jre8

## SQL Server version
Microsoft SQL Azure (RTM) - 12.0.2000.8

## Client Operating System
Linux x64.

## JAVA/JVM version
1.8.0_332-b09

## Table schema
Create a table called 'SOH' with following columns:
```
SalesOrderID        bigint  
RevisionNumber      tinyint 
OrderDate           datetime    
DueDate             datetime    
ShipDate            datetime    
Status              tinyint 
SalesOrderNumber    nvarchar    25
CustomerID          int 
ShipToAddressID     int 
```

run `sp_columns_100 'SOH', 'dbo';  `
DatabaseMetaData.getColumns() runs this to get the metadata

Then ALTER TABLE add three columns:
```
    OnlineOrderFlag     bit
    SalesOrderNumber    nvarchar    25
    PurchaseOrderNumber nvarchar    25
```

run `sp_columns_100 'SOH', 'dbo';  `
the three new columns are not shown

## Problem description
DatabaseMetadata.getColumns() is not returning all columns of table after table has been altered
## Expected behavior
DatabaseMetadata.getColumns() must return the new columns of table after table has been altered.
## Actual behavior
Incomplete list of columns are returned (**it does not return new columns that were added to the table**)
```
SalesOrderID        bigint  
RevisionNumber      tinyint 
OrderDate           datetime    
DueDate             datetime    
ShipDate            datetime    
Status              tinyint 
SalesOrderNumber    nvarchar    25
CustomerID          int 
ShipToAddressID     int 

```
## Error message/stack trace
No error occurs, it just returns incomplete data.
## Any other details that can be helpful
Refer: https://github.com/microsoft/mssql-jdbc/issues/1859.

## JDBC trace logs
NA

**Comment by tkyc** [comment]
HI @www-viveksharma, I'm still unable to repro the issue when following your steps. These are the steps I performed in SSMS with the same SQL db version.

```
1. Create the table
create table SOH (
SalesOrderID        bigint,  
RevisionNumber      tinyint, 
OrderDate           datetime,    
DueDate             datetime,    
ShipDate            datetime,    
Status              tinyint, 
SalesOrderNumber    nvarchar(25),
CustomerID          int, 
ShipToAddressID     int 
)

2. Queried the table, here I see all 9 columns
sp_columns_100 'SOH', 'dbo';

3. Altered the table with 3 new columns
alter table SOH add OnlineOrderFlag bit, AccountNumber nvarchar(25), PurchaseOrderNumber nvarchar(25);

4. Queried the table again, however I do see the 3 new columns in addition to the previous 9
sp_columns_100 'SOH', 'dbo';
```

Is there anything missing from what I did? This is all done on a fresh environment.

**Comment by www-viveksharma** [comment]
The difference I see in the new columns is that when I run:
```
SELECT DOMAIN_CATALOG 
  FROM INFORMATION_SCHEMA.COLUMNS c
 WHERE TABLE_SCHEMA = 'dbo'
   AND TABLE_NAME = 'SOH' 
 ORDER BY ORDINAL_POSITION ;  
```
The `DOMAIN_CATALOG` shows as NULL for existing columns, but for the new 3 columns added, `DOMAIN_CATALOG` = `Adventureworks`...

**Comment by www-viveksharma** [comment]
can this issue be related to some system indexes not being refreshed after the alter table was done ?

**Comment by www-viveksharma** [comment]
Let me know if you want me to run some other query and you want to look at that result

**Comment by www-viveksharma** [comment]
@tkyc any updates on this ?

**Comment by tkyc** [comment]
Like I mentioned before, since it isn't a direct driver issue (because we're working off of SSMS/Db clients rather than through the driver), your best bet is to contact the Azure SQL team.

**Comment by dosbol** [comment]
`GRANT REFERENCES ON TYPE::dbo.aliastype TO user`
solved the problem for me
