### ISSUE TITLE
[QUESTION]How JDBC Driver Process Charset

### ISSUE THREAD

**Issue by cavonchen** [microsoft/mssql-jdbc#1917]
## Question

Question：
     with my java source code encoded and compiled by UTF8，sql includes an chinese character，but SqlServer use Chinese_PRC_CI_AS  kind of GBK, I am wondering how sql string convert from UTF8 to GBK
Table：
     create table t_charset_test (val varchar(800))
     insert  into t_charset_test values ('中');
     insert  into t_charset_test values ('abc');
JavaCode：
```
@Test()
    public void testSqlServer() throws SQLException {
        String url = "jdbc:sqlserver://xx:1433;DatabaseName=cxh";
        Properties props = new Properties();
        props.setProperty("user", "xx");
        props.setProperty("password", "xx");

        try (Connection conn = DriverManager.getConnection(url, props)) {
            try (Statement statement = conn.createStatement()) {
                ResultSet resultSet = statement.executeQuery(
                    "select val from t_charset_test  where val = ('中') ");
                boolean next = resultSet.next();
                Assert.assertTrue(next);
                System.out.println(resultSet.getString(1));
            }
        }
    }
```
JavaCode Charset：UTF-8
DB version：SqlServer 2008
DB Server Collation：Chinese_PRC_CI_AS
JDBC version:
```
<dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>8.4.1.jre11</version> 
        </dependency> 
```

**Comment by Jeffery-Wasty** [comment]
Hi @cavonchen,

I'm not sure what's the problem here. The JDBC driver supports CP936, or GBK, collation, so use between the driver and your server should work well. If you're still concerned with potential conversion errors, consider moving from GBK to GB18030. GB18030 is a superset of GBK that supports the entire Unicode space, but I don't see any potential problem with the current setup.

**Comment by Jeffery-Wasty** [comment]
Just wanted to follow up on this, do you have any further questions? If not, I'll be going ahead and closing the issue.
