### ISSUE TITLE
[QUESTION] Exception is not thrown as expected when the session is killed in SQL database

### ISSUE THREAD

**Issue by DorisTao77** [microsoft/mssql-jdbc#1918]
## Question
A follow up issue of #1846: https://github.com/microsoft/mssql-jdbc/issues/1846

Hi @lilgreenbird, I have investigated the issue with the Databricks side. From the current findings, the issue may still persist with the newly released 11.2.0 version: https://github.com/microsoft/mssql-jdbc/releases/tag/v11.2.0

We have tried to only use Scala codes, which don’t involve Spark and just tries to call the library in the same way how Spark calls it. . After killing the session and giving only part of the records, but the error doesn’t show up. It could be the scenario when the error doesn't show up.

%scala
import java.sql.DriverManager
import java.sql.Connection
import java.util.Properties;
import java.sql.{Connection, PreparedStatement, ResultSet}

val jdbcHostname = "xinrandatabseserver.database.windows.net"
val jdbcDatabase = "xinranSQLDatabase"
val jdbcPort = "1433"
val driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
val token = "xxxxxxxxx"

val jdbcUrl = "jdbc:sqlserver://%s:%s;databaseName=%s;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net".format(jdbcHostname, jdbcPort, jdbcDatabase)+ ";accessToken="+token
 
val info:Properties = new Properties();
info.setProperty("accesstoken", token);
    
// make the connection
Class.forName(driver)
connection = DriverManager.getConnection(jdbcUrl,info )

val sqlText = "SELECT 1 FROM (select UNITS from payment_balance_new) emp_alias"
val stmt = connection.prepareStatement(sqlText,
        ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY)
stmt.setFetchSize(0)
stmt.setQueryTimeout(0)
val resultSet = stmt.executeQuery()
var count = 0 
while ( resultSet.next() ) {
 // println("__________________________"+resultSet.getString(1))
  count = count + 1
}

print(count)
// the actual result should be 2673440
//assert(count == 2673440)

![image](https://user-images.githubusercontent.com/92084556/190054034-6cd7a017-1d73-4c1c-b23e-a556b561f476.png)

Could you help further look into it? Thanks in advance!

## Relevant Issues and Pull Requests
https://github.com/microsoft/mssql-jdbc/issues/1846
https://github.com/microsoft/mssql-jdbc/pull/1857

**Comment by Jeffery-Wasty** [comment]
Hi @DorisTao77,

We're following up on this issue through the email you sent, expect updates on that thread.

**Comment by DorisTao77** [comment]
Hi @Jeffery-Wasty , thanks for your reply!

I have just updated on the email thread. The manual kill and the programmatical kill are the same by veryfying form my tests.

The used java code example from my side to programmatical kill the session, the returned results would show clearly how many records were returned, the number is less than the actual records:
[java codes.txt](https://github.com/microsoft/mssql-jdbc/files/9752066/java.codes.txt)


We have had a further tests from our side. We may have observed that the performance may be different on the Ubuntu machine when they have different cores, even we are using the exact same codes and same Java version.
•	When the Ubuntu machine only has only 1 core, the error throws as expected when the session is killed, same as the behavior on Windows:
 
![image](https://user-images.githubusercontent.com/92084556/195021127-5b51ee6b-a63c-48e2-b439-354848cb2a21.png)


•	While the Ubuntu machine has more than 1 core, for example 4 cores, the error could not show up when the session is killed for most of the time:
 
![image](https://user-images.githubusercontent.com/92084556/195021163-3097fd4e-b0c9-45f4-9e45-ee5b0f0649e9.png)



While the behavior seems different for the Ubuntu on Window, although it has multiple cores:
 
![image](https://user-images.githubusercontent.com/92084556/195021200-d509d7c7-763f-4b66-9429-a4998e656c63.png)

 

As Databricks clusters would use Ubuntu VMs with multiple cores for parallelism, the tests seem to be able to explain the reason behind the issue. 


Could you help check from your side about the different behavior on Ubuntu VM with different number of cores, and the possible reason behind? Thanks in advance!

**Comment by lilgreenbird** [comment]
could you please give this a try I made a change it's just a guess since I'm unable to repro the issue you are seeing.
[driver.zip](https://github.com/microsoft/mssql-jdbc/files/9827166/driver.zip)

**Comment by DorisTao77** [comment]
Hi, I have downloaded and retired with this new version, but the results are the same.

**Comment by DorisTao77** [comment]
Hi, I have shared the test details in the internal email thread, you can also try to login the shared VM to check more details, thanks in advance!

**Comment by lilgreenbird** [comment]
thanks @DorisTao77 I believe I've found the issue now here are the jars built with the change in PR #1943 please give this a try

[driver.zip](https://github.com/microsoft/mssql-jdbc/files/9885039/driver.zip)

**Comment by DorisTao77** [comment]
Hi @lilgreenbird , thanks so much for your hard work!

I have done tests from my side with this newly provided library(Version 12.1.0) on the multi-core Ubuntu VM, the failure (Done Status 258) would show up every time during the tens of tries.
 
![image](https://user-images.githubusercontent.com/92084556/198681175-614cce35-f7fc-4cf9-8f6e-0764aa423a11.png)

Have also done the same tests on the Databricks side with Spark, the behavior is the same:
 
![image](https://user-images.githubusercontent.com/92084556/198681218-066f3bb8-6dec-4eb6-aedb-ca27882db770.png)


I believe the issue should have been resolved with this latest jar. May I also confirm which driver version is expected to have this fix? Thanks again!

**Comment by Jeffery-Wasty** [comment]
Closed by #1943
