### ISSUE TITLE
MaxResultBuffer and SelectMethod JDBC Params MS Tracking ID 2209060060001424

### ISSUE THREAD

**Issue by Hades63146** [microsoft/mssql-jdbc#1919]
To Whom it may concern,
Hi all
we have opened a ticket in Microsoft 
"we need help with jdbc driver parameters - TrackingID#2209060060001424"

In a nutshell, the ticket dealt with an issue that when we set the parameter of **"SelectMethod=Cursor"** via Debezium 1.7 Kafka connector with MSSQLSERVER via JDBC driver 9.4. one of the tables had caught a large set with CDC LSN recap since we had a streaming break and thus, the memory that was consumed by the server to create that cursor reached to 300GB of memory and it has caused us a **resource semaphore** wait type for other operations on the source server and from there **downtime**

My questions and as I have seen a parameter called **MaxResultBuffer** are:
1. What is it used for? as I have seen, when it is not set, the text on help said that all data set is being brought. 
2. could it be related to the select method?

**Comment by Hades63146** [comment]
OK SHALL DO

**Comment by Jeffery-Wasty** [comment]
Hi @Hades63146,

Any update on this issue? We'll move forward with closing it if there are no further questions.

**Comment by Hades63146** [comment]
Hi yes,
In the meantime we shall close the ticket since we decided to use debezium
max queue property.
Had we decided to revert is shall reopen the ticket with reference to the
previous one
Thx

בתאריך יום ב׳, 26 בספט׳ 2022, 18:50, מאת Jeffery Wasty ‏<
***@***.***>:
