### ISSUE TITLE
When errors occur in a batch, only last one is visible, masking the original cause of the failure

### ISSUE THREAD

**Issue by inponomarev** [microsoft/mssql-jdbc#1924]
When batch execution fails, we usually want to see the _first_ failed statement. The subsequent failures can be caused by the first one, but in the exception thrown the (irrelevant) information of only the last failure is available. 

Note the following line:

https://github.com/microsoft/mssql-jdbc/blob/05ef7c07d184e9f8b659c351f68599b1a94132e3/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java#L1879

Our scenario:

1. We are using `SET IDENTITY_INSERT .. ON` in one batch with `INSERT`s to fill a table with `IDENTITY` fields.
2. Insertions fails somewhere in the middle of the batch because of constraint violation.
3. But what we see in exception is "Cannot insert explicit value for identity column", which has nothing to do with the real cause of the error.

Can we change the logic of error handling so that the first failure in the batch is saved and is used when building `BatchUpdateException`?

**Comment by Jeffery-Wasty** [comment]
Hi @inponomarev,

We'll look into this. You make a good argument around how returning the last known error can mask the actual problem, but we'll have to take a look into the impact this has on other workflows. Thanks for the PR as well, we'll take a look into that too.

**Comment by Jeffery-Wasty** [comment]
Apologies, this is a common issue that I failed to recognize. Use `getResultSet` and `getMoreResults` to process the response and see all the errors returned. For more information, please see: [https://learn.microsoft.com/en-us/sql/connect/jdbc/using-multiple-result-sets?view=sql-server-ver16](https://learn.microsoft.com/en-us/sql/connect/jdbc/using-multiple-result-sets?view=sql-server-ver16)

**Comment by inponomarev** [comment]
Hi @Jeffery-Wasty thanks a lot for your quick replies! 

As I figured out, indeed, the individual errors are visible. In our particular case we're using jOOQ and we're able to intercept all the errors in the batch via `ExecuteListener.exeption(...)`.

However it would be nice if you considered the change of the driver's behaviour. Now the exception that causes program termination may contain the irrelevant information, which is bad. The choice of the _last_ error for the exception message seems to be just arbitrary. 

Can we consider either reporting the first error in the batch or at least giving a hint that more than one error occurred in the batch?

**Comment by Jeffery-Wasty** [comment]
Hi @inponomarev,

Glad to hear that you're able to see all errors. The driver is used by many people and organizations, and a fundamental change to its behavior would need to be well warranted. Additionally, there are other workflows that depend on the _last_ error message, which was a reason behind the initial decision. As long as the first error can be seen, we see no problem, and no changes are needed for the driver.

If you have any additional questions, please let us know, otherwise we'll move forward with closing the issue.

**Comment by inponomarev** [comment]
@Jeffery-Wasty I fully understand the danger of breaking things. However let us spend a bit more time considering this issue, maybe we still can improve something here.

If there are reasons to show exactly the last error (I hope that there _are_ reasons indeed, and  it's not just your guess that there are such reasons) -- ok let's keep the last error then.
 
But can we tweak the error's message itself so that it will contain an information like "%d errors occured, the last one: %s"? All the other exception properties may remain the same.

Since error message text is used by humans, not by scripts, I believe this can significantly improve the speed of debugging. 

The initial problem that I faced was the completely misleading error message in the log.
