### ISSUE TITLE
Presto jdbc driver supports TLS 1.3 version?

### ISSUE THREAD

**Issue by lathasrikoyya** [microsoft/mssql-jdbc#1945]
I could see the latest version of presto-jdbc is 0.277
<dependency>
    <groupId>com.facebook.presto</groupId>
    <artifactId>presto-jdbc</artifactId>
    <version>0.277</version>
</dependency>
but I could not find the information about whether it supports TLS 1.3 version or not?
please confirm about the same.

**Comment by David-Engel** [comment]
@lathasrikoyya You've contacted an entirely unrelated product team. I suggest asking the team that owns the product you are asking about: https://github.com/prestodb/presto/issues
