### ISSUE TITLE
TCP keepalive socket options are not enabled on Linux

### ISSUE THREAD

**Issue by danburkert** [microsoft/mssql-jdbc#1949]
## Driver version

11.2.1.jre11

## SQL Server version

unknown (this is a driver-side issue)

## Client Operating System

Linux

## JAVA/JVM version

11

## Problem description

The JDBC driver documentation states [1]

> To detect broken idle connections, the driver relies on TCP keepalive packets at the socket level. On Linux and Java 11+, the driver automatically enables keepalive packets at a 30-second interval (KeepAliveTime) with a 1-second delay between retries when a failure occurs (KeepAliveInterval).

When using the JDBC driver to connect to a SQL Server database with a java process instrumented with `strace -f -e trace=setsockopt` shows that the relevant keepalive socket options are not being set.

With a debugger, I was able to ascertain that [this block][2] should be setting the relevant socket options, but instead the `else` branch is executed. This is because of a bug in the code: the driver ships its own version of the [`jdk.net.ExtendedSocketOptions`][4] class named [`com.microsoft.sqlserver.jdbc.ExtendedSocketOptions`][3], including separate definitions of `TCP_KEEPIDLE` and `TCP_KEEPINTERVAL`.  It's these alternate definitions that are used to check for presence in the set of supported socket options.  However, the set contains the `jdk.net.ExtendedSocketOptions` versions of these options. Best I can tell, there is no `Object.equals` override for any of the socket options classes, so reference equality is used to check for set inclusion. Thus, while the socket options set includes `jdk.net.ExtendedSocketOptions.TCP_KEEPIDLE` and `jdk.net.ExtendedSocketOptions.TCP_KEEPINTERVAL`, the containment checks for the `com.microsoft.sqlserver.jdbc.ExtendedSocketOptions` versions returns false, dropping the flow into the `else` branch.

[1]: https://learn.microsoft.com/en-us/sql/connect/jdbc/connection-resiliency?view=sql-server-ver16#connection-recovery
[2]: https://github.com/microsoft/mssql-jdbc/blob/main/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerJdbc43.java#L65-L74
[3]: https://github.com/microsoft/mssql-jdbc/blob/572461928fba73dee785217379b2893b988f8fe8/src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java#L87-L153
[4]: https://docs.oracle.com/en/java/javase/11/docs/api/jdk.net/jdk/net/ExtendedSocketOptions.html

**Comment by danburkert** [comment]
I have verified via `strace` that removing the `com.microsoft.sqlserver.jdbc.ExtendedSocketOptions` class and using `jdk.net.ExtendedSocketOptions` for the contaiment checks enabled the keepalive socket options appropriately. I'm not submitting a PR because I imagine this will break compatibility with JRE 8.  https://github.com/sisudata/mssql-jdbc/commit/eb68e1d8fa35a6b49b7f70b6a53b46bf9023a49b

**Comment by Jeffery-Wasty** [comment]
Hi @danburkert,

Thank you for finding this. We'll look into this, and keep you updated on a solution.

**Comment by David-Engel** [comment]
Fixed via #1953 and included in today's [12.1.0 preview release](https://github.com/microsoft/mssql-jdbc/releases/tag/v12.1.0).
