### ISSUE TITLE
Cooperate/Respect Interrupts

### ISSUE THREAD

**Issue by jschulist** [Microsoft/mssql-jdbc#196]
Encountered a situation where a piece of code was calling cancel(true) on a future runnable but upon inspection Thead.currentThead().isInterrupted() was returning false inside the runnable.  The problem is this runnable communicates with sql and the interrupt status/flag is being removed/swallowed by the driver.  Specifically the path I encountered was in the [login method of SqlServerConnection](https://github.com/Microsoft/mssql-jdbc/blob/808e658010331b3475e6bdc0abe66aed2804c3b7/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L1715).  The method is using Thead.sleep and is swallowing the InterruptedException.  Because Thead.sleep throws InterruptedException when it encounters an interrupt it clears the interrupt status/flag.  When execution ultimately returns to the runnable it has no knowledge that an interrupt ever occurred making it impossible for it to act on it.  The driver doesn't necessarily need to halt it's execution but in my opinion it should not hide the fact that interrupt occurred.

I'm certainly no expert when it comes to java threading so I'll defer to guidance provided by IBM: https://www.ibm.com/developerworks/library/j-jtp05236/

NOTE: From a quick look through the codebase this is not the only area of concern

**Comment by v-xiangs** [comment]
@jschulist Thank you for finding the issue. We created a PR for it to restore the thread's interrupt status. We hope this will work for you. Thank you.

**Comment by jschulist** [comment]
Thanks, the PR LGTM.

**Comment by v-xiangs** [comment]
@jschulist Thank you for getting back to us. I am closing the issue.
