### ISSUE TITLE
Incorrect batched CallableStatement timeout behavior

### ISSUE THREAD

**Issue by mmimica** [microsoft/mssql-jdbc#1961]
## Driver version
11.2.1, main

## SQL Server version
Microsoft SQL Server 2019 (RTM-CU8) (KB4577194) - 15.0.4073.23 (X64) 
	Sep 23 2020 16:03:08 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 18.04.5 LTS) <X64>

## Client Operating System
Linux

## Table schema
See https://github.com/microsoft/mssql-jdbc/pull/1960

## Problem description
With enablePrepareOnFirstPreparedStatementCall=true.
When timeout happens, the update count in the BatchUpdateException is incorrect and doesn't reflect what actually happened.

## Expected behavior
In the test, 5 statements are executed in a batch. The 4th one statement times out. The first three succeed, the last two fail. updateCount should reflect that.

## Actual behavior
See the test in https://github.com/microsoft/mssql-jdbc/pull/1960

**Comment by tkyc** [comment]
Thanks, we'll take a look and get back to you.
