### ISSUE TITLE
[QUESTION] Java Application encounters SQLServerException while there is an exception in batch executing 

### ISSUE THREAD

**Issue by anujkgarg** [microsoft/mssql-jdbc#1967]
## Question
I am using SQLServer 2017.  I have created an application in Java 8. I am using SQL Server JDBC driver (mssql-jdbc-7.2.2.jre8.jar) downloaded from https://www.microsoft.com/en-us/download/details.aspx?id=57782

**DDL -**  

```
create table dbo.Employee (id int primary key, name varchar(100), age int);
create table dbo.Employee_Audit (id int primary key, name varchar(100), age int);
```

**Trigger**  - 

```
CREATE TRIGGER [dbo].[AutoGenerateOMAInsertTrigger] ON [dbo].[Employee] AFTER INSERT 
AS 
BEGIN 
	DECLARE @threshold int = 0, 
			@name varchar(100),
			@age int
	SET @threshold = (select max(id) from dbo.Employee) 
	SET @name = (select name from dbo.Employee where id = @threshold) 
	SET @age = (select max(id) from dbo.Employee where id = @threshold) 
	if @threshold % 7 = 0
		insert into dbo.Employee_Audit (id, name, age) values (10, @name, @age) 
END
```

With the DDL & trigger provided as above,  let us consider the following example - 

Table Name : **dbo.Employee** 
Table Name to which the Trigger inserts : **dbo.Employee_Audit**

**Batch 1 :** 10 INSERTS -> Executed successfully on dbo.Employee -> Trigger is fired and inserts are successfully executed on dbo.Employee_Audit
**Batch 2 :** 10 UPDATES -> Executed successfully on dbo.Employee
**Batch 3 :** 10 UPDATES -> Executed successfully on dbo.Employee
**Batch 4 :** 5 INSERTS -> Executed on dbo.Employee -> Trigger is fired and causes a Primary Key violation on dbo.Employee_Audit. This throws a SQLServerException which is caught by the Java application communicating with dbo.Employee.
Due to this exception, the previously executed batches (**Batch 1, 2, 3, 4**) are rolled back.
**Batch 5 :** 10 INSERTS -> Executed successfully on dbo.Employee -> Trigger is fired and inserts are successfully executed on dbo.Employee_Audit
Commit -> On commit only the 10 inserts as part of Batch 5 are seen in the dbo.Employee  and all others are lost.

**Questions :** 

1. Is this the expected behaviour of SQLServer ? How can I rolled back only batch 4 ? Is there any way to achieve it in SQL Server ? 
2. If a primary key violation is hit on table "dbo.Employee" (which is the table communicated with the Java application) an exception of type BatchUpdateException is seen. But in the above mentioned scenario SQLServerException is hit rather than a BatchUpdateException. Why is this behaviour different ?

**### Sample Code** 

```
package org.example;

import java.sql.*;

public class JDBCIssue {
    public static void reproduce(Connection con, boolean reproduceSQLServerException) throws SQLException {
        // Batch 1
        PreparedStatement prepStmt1 = con.prepareStatement("insert into dbo.Employee (id, name, age) values (?, ?, ?)");;
        for (int id = 1; id <= 10; ++id) {
            prepStmt1.setInt(1, id);
            prepStmt1.setString(2, String.format("name - %d", id));
            prepStmt1.setInt(3, id);
            prepStmt1.addBatch();
        }
        prepStmt1.executeBatch();
        Savepoint sv1 = con.setSavepoint("Batch-1-SavePoint");

        // Batch 2
        PreparedStatement prepStmt2 = con.prepareStatement("update dbo.Employee set name = ? where id = ?");
        for (int id = 1; id <= 10; ++id) {
            prepStmt2.setString(1, String.format("First update - %d", id));
            prepStmt2.setInt(2, id);
            prepStmt2.addBatch();
        }
        prepStmt2.executeBatch();
        Savepoint sv2 = con.setSavepoint("Batch-2-SavePoint");

        // Batch 3
        PreparedStatement prepStmt3 = con.prepareStatement("update dbo.Employee set name = ? where id = ?");
        for (int id = 1; id <= 10; ++id) {
            prepStmt3.setString(1, String.format("Second update - %d", id));
            prepStmt3.setInt(2, id);
            prepStmt3.addBatch();
        }
        prepStmt3.executeBatch();
        Savepoint sv3 = con.setSavepoint("Batch-3-SavePoint");

        PreparedStatement prepStmt4 = con.prepareStatement("insert into dbo.Employee (id, name, age) values (?, ?, ?)");
        if (reproduceSQLServerException) {
            // Batch 4 -- Primary Key violation - ID%7=0
            // This will rollback batch 1, 2 and 3.
            try {
                for (int id = 11; id <= 15; ++id) {
                    prepStmt4.setInt(1, id);
                    prepStmt4.setString(2, String.format("name - %d", id));
                    prepStmt4.setInt(3, id);
                    prepStmt4.addBatch();
                }
                prepStmt4.executeBatch();
                Savepoint sv4 = con.setSavepoint("Batch-4-SavePoint");
            } catch (Exception e) {
                System.out.println("Exception " + e.getMessage());
                e.printStackTrace();
                con.rollback(sv3);
            }
        } else {
            // Batch 4 -- Primary Key violation
            // This will rollback batch 4, and table will contain changes of batch 1, 2 and 3.
            try {
                int id = 1;
                prepStmt4.setInt(1, id);
                prepStmt4.setString(2, String.format("name - %d", id));
                prepStmt4.setInt(3, id);
                prepStmt4.addBatch();
                prepStmt4.executeBatch();
                Savepoint sv4 = con.setSavepoint("Batch-4-SavePoint");
            } catch (Exception e) {
                System.out.println("Exception " + e.getMessage());
                e.printStackTrace();
                con.rollback(sv3);
            }
        }

        // Table contain changes of batch 5
        // Batch 5
        PreparedStatement prepStmt5 = con.prepareStatement("insert into dbo.Employee (id, name, age) values (?, ?, ?)");
        for (int id = 16; id <= 20; ++id) {
            prepStmt5.setInt(1, id);
            prepStmt5.setString(2, String.format("name - %d", id));
            prepStmt5.setInt(3, id);
            prepStmt5.addBatch();
        }
        prepStmt5.executeBatch();
        Savepoint sv5 = con.setSavepoint("Batch-5-SavePoint");

        prepStmt1.close();
        prepStmt2.close();
        prepStmt3.close();
        prepStmt4.close();
        prepStmt5.close();
    }

    public static void main(String[] args) {
        /*
         *
         *  Steps to reproduce -
         *  1) Create tables (dbo.Employee and dbo.Employee_Audit)
         *  2) Create Trigger (dbo.AutoGenerateOMAInsertTrigger)
         *  3) For SQLServerException, set reproduceSQLServerException = true
         *     For BatchUpdateException, set reproduceSQLServerException = false
         */
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=qatest;user=sa;password=w3b@ct10n;encrypt=true;trustServerCertificate=true";
        try {
            boolean reproduceSQLServerException = true;
           /*
           reproduceSQLServerException = true, then dbo.Employee will contain the below record -
           id|name     |age|
            --+---------+---+
            16|name - 16| 16|
            17|name - 17| 17|
            18|name - 18| 18|
            19|name - 19| 19|
            20|name - 20| 20|

            ######################################################

            reproduceSQLServerException = false, then the dbo.Employee will contain the below record -
            id|name              |age|
            --+------------------+---+
             1|Second update - 1 |  1|
             2|Second update - 2 |  2|
             3|Second update - 3 |  3|
             4|Second update - 4 |  4|
             5|Second update - 5 |  5|
             6|Second update - 6 |  6|
             7|Second update - 7 |  7|
             8|Second update - 8 |  8|
             9|Second update - 9 |  9|
            10|Second update - 10| 10|
            16|name - 16         | 16|
            17|name - 17         | 17|
            18|name - 18         | 18|
            19|name - 19         | 19|
            20|name - 20         | 20|
             */
            try (Connection con = DriverManager.getConnection(connectionUrl)) {
                con.setAutoCommit(false);
                reproduce(con, reproduceSQLServerException);
                con.commit();
            }
        } catch(SQLException e) {
            e.printStackTrace();
        }
    }
}

```
## Relevant Issues and Pull Requests
mssql-jdbc-7.2.2.jre8.jar

**Comment by tkyc** [comment]
Hey @anujkgarg, we'll need to do some investigating and get back to you. We'll keep you updated.

**Comment by lilgreenbird** [comment]
hi @anujkgarg 

Could you please upgrade to the latest [12.1.0 preview](https://github.com/microsoft/mssql-jdbc/releases/tag/v12.1.0) or  [11.2.1 stable release](https://github.com/microsoft/mssql-jdbc/releases/tag/v11.2.1) ? The version 7.2.2 you are on is quite old and there had been a lot of fixes and updates since then. 

Also, please share a standalone java repro for the issue you are seeing.

Thanks..

**Comment by anujkgarg** [comment]
Updated trigger, DDL and Java code.

@lilgreenbird  - This issue is reproducible with [11.2.1 stable release](https://github.com/microsoft/mssql-jdbc/releases/tag/v11.2.1) also.

I can see below exception - 

> 
> com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK__Employee__3213E83F6F3FC141'. Cannot insert duplicate key in object 'dbo.Employee_Audit'. The duplicate key value is (10).
> 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
> 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1673)
> 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatementBatch(SQLServerPreparedStatement.java:2910)
> 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtBatchExecCmd.doExecute(SQLServerPreparedStatement.java:2774)
> 	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7627)
> 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3912)
> 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:268)
> 	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:242)
> 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2172)
> 	at org.example.JDBCIssue.reproduce(JDBCIssue.java:43)
> 	at org.example.JDBCIssue.main(JDBCIssue.java:67)
>

**Comment by anujkgarg** [comment]
Hi @tkyc and @lilgreenbird - I will upload the sample code asap.

**Comment by anujkgarg** [comment]
Hi @tkyc and @lilgreenbird - I have added the sample code to reproduce SQLServerException and BatchUpdateException. Looking for your reply. Thanks in advance.

**Comment by lilgreenbird** [comment]
hi @anujkgarg 

please let us know if you have further questions otherwise we will be closing this soon due to inactivity.
