### ISSUE TITLE
Zip file directory structure issue

### ISSUE THREAD

**Issue by David-Engel** [microsoft/mssql-jdbc#1978]
## Driver version
8.4 through 11.2

## Client Operating System
Windows 10

## Problem description
Using 7-Zip, if you look at the folder structure in the released zip file, you can see that there is an issue in the directory separator between the `sqljdbc_<version>` folder and the language folder, making the folders appear as one:
![image](https://user-images.githubusercontent.com/26262303/204682782-e963dcc2-4c03-48db-86cf-b704095d23b4.png)

This is causing problems for Chocolatey: https://github.com/dgalbraith/chocolatey-packages/issues/448

## Expected behavior
The zip package should extract into `sqljdbc_<version>\<language` using 7-Zip (and Chocolatey).

## Actual behavior
The zip package extracts into `sqljdbc_<version><language>` using 7-Zip.
You can use https://download.microsoft.com/download/d/1/9/d194dc5c-4db6-4fb6-8ba2-219c93272b7b/sqljdbc_11.2.0.0_enu.zip as an example.

## Any other details that can be helpful
The Windows built-in Compressed Folder Tools extracts the zip file correctly.

**Comment by lilgreenbird** [comment]
thanks @David-Engel

**Comment by lilgreenbird** [comment]
we have identified and fixed the issue, this will be fixed in the next release.
