### ISSUE TITLE
[QUESTION] Backport PR#1943 fix in v12.1.0 to v11.2.x for stable release

### ISSUE THREAD

**Issue by jieyu-lin** [microsoft/mssql-jdbc#1981]
## Question
Hi, this is a follow issue with: [#1918](https://github.com/microsoft/mssql-jdbc/issues/1918)

As mentioned, the issue is happening in Databricks and as v12.1.0 is still in preview release, which means this version won't be mature at the moment. Databricks side plan to upgrade its new DBR to pull v11.2.x for default, which is much more stable version. As the issue we concerned are fixed properly in v12.1.0 with PR#1943, will it be possible that v11.2.x backported this specific fix? Since it should be fixed in v11.2.0, which is highlight [here](https://github.com/microsoft/mssql-jdbc/releases/tag/v11.2.0#:~:text=Added%20check%20for%20DONE_ERROR%20status%20token%20which%20may%20occur%20from%20a%20killed%20session%20on%20the%20server%201857). 

## Relevant Issues and Pull Requests

[#1918](https://github.com/microsoft/mssql-jdbc/issues/1918)
[#1846](https://github.com/microsoft/mssql-jdbc/issues/1846)

Closed PR number with:
[PR#1943](https://github.com/microsoft/mssql-jdbc/pull/1943)

and version discussion between
[v11.2.0](https://github.com/microsoft/mssql-jdbc/releases/tag/v11.2.0)
[v11.2.1](https://github.com/microsoft/mssql-jdbc/releases/tag/v11.2.1)
[v12.1.0](https://github.com/microsoft/mssql-jdbc/releases/tag/v12.1.0)

**Comment by lilgreenbird** [comment]
hi @jieyu-lin 

yes we are looking at a hot fix for 11.2 I can not give you a specific date at the moment but this should happen in the next few weeks. The fix you mentioned will be included.

**Comment by jieyu-lin** [comment]
Hi @lilgreenbird ,

Thank you for the response. I would like to follow this hot fix for 11.2.x and if there is any release note, please share with me as well as ETA for the hot fix.

Thank you.

BR,
jieyulin

**Comment by DorisTao77** [comment]
Hi @lilgreenbird,

I have confirmed with Databricks engineering team that they are deciding to upgrade to the 11.2.x driver version in their new DBR version(from DBR-12.1 onwards), which will be available in **Q1-2023**. 

Thus, they want to understand if it is possible to have the backport to 11.2.x and have the stable release with this fix by **Jan-2023**. May I confirm it with you? Thanks in advance! 

Regards,
Xinran

**Comment by lilgreenbird** [comment]
hi @DorisTao77 

yes we will be backporting this fix to a hotfix release for 11.2 that's targeted for mid Jan.

**Comment by lilgreenbird** [comment]
[11.2.2](https://github.com/microsoft/mssql-jdbc/releases/tag/v11.2.2) has been released

**Comment by DorisTao77** [comment]
HI @lilgreenbird, thanks so much for your quick update! I will notify the Databricks team about it.
