### ISSUE TITLE
[QUESTION] Which driver version supports SQL Server 2022

### ISSUE THREAD

**Issue by siggemannen** [microsoft/mssql-jdbc#1983]
## Question
Hello, i'm trying to figure out which driver version (if any) supports connecting to stand alone installation of SQL Server 2022. 
Can't find the information here: https://learn.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix?view=sql-server-ver16

I'm using 9.1.1.jre8-preview and it doesn't seem to be able to connect to SQL Server 2022 using AD authentication. The error occurs after a little while, so i suspect some sort of protocol error.
The connection string is something like:

`jdbc:sqlserver://someServerInAD;databaseName=someDb;integratedSecurity=true;lastUpdateCount=false;selectMethod=direct;responseBuffering=adaptive`

I have no problem connecting to similarily installed SQL Server 2017 and earlier.

**Comment by lilgreenbird** [comment]
hi @siggemannen 

What is the error you are getting?
I'll let our product manager @David-Engel comment on SQL Server 2022 support.

**Comment by David-Engel** [comment]
SQL Server 2022 should be generally backwards compatible with existing clients. As far as JDBC drivers that will declare "official support" for SQL Server 2022, the next GA release (12.2 at the end of Jan 2023) will definitely have that. TBD if we go back and declare it for 11.2. But we've been testing against preview releases of SQL Server 2022 in the latest releases (previews and 11.2 GA) and they should all work fine. I'm guessing your error may be related to a config issue.

**Comment by siggemannen** [comment]
Hello and thanks for getting back to me. I have now retested with firewall rules setup correctly, and it works even with 9.1.1.jre8-preview version!
Sorry about troubling you and thanks for the answers!
