### ISSUE TITLE
The usage of useBulkCopyForBatchInsert=true connection parameter leads to invalid batch inserts.

### ISSUE THREAD

**Issue by balazstbb** [microsoft/mssql-jdbc#1993]
## Driver version
Any

## SQL Server version
Any

## Client Operating System
Any

## JAVA/JVM version
Any

## Table schema
`CREATE TABLE test (c1 varchar(1), c2 varchar(3))`

## Problem description
Columns mixing up on batch insert and leads to invalid data

## Expected behavior
The same result expected like if no batch of inserts

## Actual behavior
Reproducible with the 
`com.microsoft.sqlserver.jdbc.preparedStatement.BatchExecutionWithBulkCopyTest.testReverseColumnOrder()`
unit test from the [PR](https://github.com/microsoft/mssql-jdbc/pull/1992)

## Error message/stack trace
Reproducible with the 
`com.microsoft.sqlserver.jdbc.preparedStatement.BatchExecutionWithBulkCopyTest.testReverseColumnOrder()`
unit test from the [PR](https://github.com/microsoft/mssql-jdbc/pull/1992)

## Any other details that can be helpful
Possible fix: [PR](https://github.com/microsoft/mssql-jdbc/pull/1992)

## JDBC trace logs
Reproducible with the 
`com.microsoft.sqlserver.jdbc.preparedStatement.BatchExecutionWithBulkCopyTest.testReverseColumnOrder()`
unit test from the [PR](https://github.com/microsoft/mssql-jdbc/pull/1992)

**Comment by tkyc** [comment]
We'll take a look and get back to you, but our response will be a bit delayed as were in the middle of finalizing a couple of hotfix releases.

**Comment by Jeffery-Wasty** [comment]
Resolved by #1992
