### ISSUE TITLE
Using Bulk Copy to insert uniqueidentifier to Azure Data Warehouse results in invalid column type

### ISSUE THREAD

**Issue by hchenatsafe** [microsoft/mssql-jdbc#1999]
## Driver version
11.2.1.0

## SQL Server version
Microsoft Azure SQL Data Warehouse - 10.0.18045.0 Oct 11 2022 03:10:58 Copyright (c) Microsoft Corporation

## Client Operating System
Microsoft Windows 11 Pro

## JAVA/JVM version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

## Table schema
TABLE_CATALOG | TABLE_SCHEMA | TABLE_NAME | COLUMN_NAME | ORDINAL_POSITION | COLUMN_DEFAULT | IS_NULLABLE | DATA_TYPE | CHARACTER_MAXIMUM_LENGTH | CHARACTER_OCTET_LENGTH | NUMERIC_PRECISION | NUMERIC_PRECISION_RADIX | NUMERIC_SCALE | DATETIME_PRECISION | CHARACTER_SET_CATALOG | CHARACTER_SET_SCHEMA | CHARACTER_SET_NAME | COLLATION_CATALOG | COLLATION_SCHEMA | COLLATION_NAME | DOMAIN_CATALOG | DOMAIN_SCHEMA | DOMAIN_NAME
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
SQLPool | dbo | hc_test_uniqueidentifier | _uniqueidentifier | 1 |   | YES | uniqueidentifier |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  

## Problem description
When using Bulk Copy to insert a row with a column containing the uniqueidentifier data type to Azure Data Warehouse, I will receive this error: `Invalid column type from bcp client for colid 1.`

The issue occurs only when using Bulk Copy.

## Expected behavior
The row is inserted without any errors.
## Actual behavior
I receive the error below:

## Error message/stack trace
`com.microsoft.sqlserver.jdbc.SQLServerException: 110802;An internal DMS error occurred that caused this operation to fail. Details: Please use this Error ID when contacting your Administrator for assistance. EID:(d65450e6dc884758a9be76dbc1d88e25)
SqlNativeBufferBufferBulkCopy.WriteTdsDataToServer, error in OdbcDone: SqlState: 42000, NativeError: 4816, 'Error calling: bcp_done(this->GetHdbc()) | SQL Error Info: SrvrMsgState: 1, SrvrSeverity: 16,  Error <1>: ErrorMsg: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column type from bcp client for colid 1. | Error calling: pConn->Done() | state: FFFF, number: 418, active connections: 3', Connection String: Driver={pdwodbc17e};app=TypeD00-DmsNativeWriter:DB40\mpdwsvc (24828)-ODBC;autotranslate=no;trusted_connection=yes;server=\\.\pipe\DB.40-feeb931069d5-0\sql\query;database=Distribution_58
`

**Comment by tkyc** [comment]
Hi, we'll do some investigating and get back to you. We're in the middle of performing hotfix releases so replies might be delayed.

**Comment by tkyc** [comment]
Hi @hchenatsafe, I'm getting the same error returned as you in my own reproduction. But, I was able to get a workaround. In the meantime, could you try and see if this works for you as well? I found that if I do a `CAST` to `UNIQUEIDENTIFIER` I was able to perform the bulk insert.

So, my prepared statement with the cast before insert looked like the following:
`DECLARE @val UNIQUEIDENTIFIER = CAST(? AS UNIQUEIDENTIFIER); INSERT INTO uidTable VALUES(@val);`

I'm still investigating this issue to narrow down the cause (although to me this seems like an Azure data warehouse problem). I'll keep you posted.

**Comment by tkyc** [comment]
As suspected, this is an Azure data warehousing issue. I discovered a similar issue [here](https://social.technet.microsoft.com/Forums/azure/en-US/91e6bb49-a812-4961-812c-dc277894a35d/internal-dms-error-occurred-that-caused-this-operation-to-fail?forum=sqldatawarehousing). It seems that there was a fix made, but for `UNIQUEIDENTIFIER` it was missed. I recommend reaching out to support through the Azure portal as this is a server side issue and not specifically a driver issue.

**Comment by hchenatsafe** [comment]
Hello @tkyc ,

Thank you for investigating and your suggestion of using CAST as a workaround. 

Our application relies on using the raw [Bulk Copy](https://learn.microsoft.com/en-us/sql/connect/jdbc/using-bulk-copy-with-the-jdbc-driver?view=sql-server-ver16) method rather than batch insert. It seems this means we don't have easy access to the CAST workaround. 

Is the CAST workaround still doable using our Bulk Copy method? Or could there be other workarounds we can try?

**Comment by tkyc** [comment]
@hchenatsafe Unfortunately, the workaround won't work with the raw bulk copy. The only recommendation I can make is to use the [bulk copy API for batch insert](https://learn.microsoft.com/en-us/sql/connect/jdbc/use-bulk-copy-api-batch-insert-operation?view=sql-server-ver16) which should allow you to do a cast.
