### ISSUE TITLE
Wildcard in import statements

### ISSUE THREAD

**Issue by iamatinkerer** [Microsoft/mssql-jdbc#2]
In many files, the import statements use wildcard to import all the classes in the packages

E.g. https://github.com/Microsoft/mssql-jdbc/blob/master/src/main/java/com/microsoft/sqlserver/jdbc/KerbAuthentication.java
`import java.util.*;`

It is a good practice to specify the specific classes in these imports.

**Comment by v-xiangs** [comment]
@iamatinkerer Thank you very much for pointing this out. You are right, it is a good practice to specify classes in imports. We really appreciate your participation and hope you could help us to fix it.

**Comment by iamatinkerer** [comment]
@v-xiangs 
>hope you could help us to fix it.

Can I take this issue and send a PR then?

**Comment by ajlam** [comment]
@iamatinkerer - we are working on getting a development branch created. Once that's available, you can send a PR there. Please stay tuned and thank you for your help 😄

**Comment by v-ahibr** [comment]
@iamatinkerer 
We've just set up a dev branch. You can create a pull request there.

**Comment by v-nisidh** [comment]
Closing this issue as it is fixed by #52
