### ISSUE TITLE
[FEATURE REQUEST] MS-SQL driver closes prepared statements on endRequest, but that is not what JDBC 4.3 seems to require

### ISSUE THREAD

**Issue by roeltje25** [microsoft/mssql-jdbc#2010]
This issue refers to an earlier closed issue #1703. The claim was that the driver is following the JDBC spec. Below is a reiteration of a comment I gave there describing why, actually, I think the SQL driver is introducing functionality not in the spec, which is detrimental at least in the case of Ironjacamar, but seemingly also for openliberty.

To give a little push-back on the claim that this is not a driver issue. The JDBC spec is not at all requiring prepared statements to be closed on an endRequest call.  As can be seen in the javadoc of the endRequest call [here](https://javadoc.scijava.org/Java9/java/sql/Connection.html#endRequest--). The methods were added to JDBC to indicate that a unit of work was done and are supposed to be used by connection pool managers (like the one in wildfly). (refer to [here](https://groups.google.com/g/r2dbc/c/zZ09hFMR9N8/m/aTKoFU8pBwAJ)) These managers are likely to cache prepared statements as well. Transparently using the endRequest method hint, as specified, may then in some vendors work fine, and other vendors (=Microsoft SQL JDBC Driver) clean the statements, making the prepared statement cache break.... While the spec actually defines this should be supported in [JSR 221](https://download.oracle.com/otn-pub/jcp/jdbc-4_3-mrel3-spec/jdbc4.3-fr-spec.pdf?AuthParam=1671613668_ad8b575d94e8b7dd8d5dd742ddd0b3f6) Section 11.6. It seems the MS SQL Driver is one of the few drivers actually implementing the JDBC 4.3 behavior to close the PreparedStatements. Even open-liberty [here](https://github.com/OpenLiberty/open-liberty/issues/4734) claims this a very strict and not specified behavior.

As such, I would strongly suggest that the prepared statements should not be closed on endRequest calls. Or at least, there should be an option in the driver to bypass this - I must say problematic - behavior. Would you guys be open for a driver option that can bypass the cleanup of prepared statements?

thanks for your consideration,

Roel

_Originally posted by @roeltje25 in https://github.com/microsoft/mssql-jdbc/issues/1703#issuecomment-1361052266_

**Comment by Jeffery-Wasty** [comment]
Hi @roeltje25,

Thank you for the additional information, we'll take another look into this issue and get back to you.

**Comment by roeltje25** [comment]
@Jeffery-Wasty 
That's mich appreciated

**Comment by lilgreenbird** [comment]
hi @roeltje25 

As previously mentioned Connection.endRequest() is used to define a boundary for connection pool managers. It is intended to allow JDBC drivers to clean up connection-related resources when a pooled connection is returned to the pool (the application calls Connection.close() but the pooling manager keeps the physical connection open for re-use). That is exactly what the MS JDBC driver does, including closing open statements, ensuring that the next requestor that receives the connection receives one that is in a clean state.

 I am sorry this behavior is not what you want for your particular vendor but as per [JDBC specs](https://javadoc.scijava.org/Java9/java/sql/Connection.html#endRequest--) "exact behavior of this method is vendor specific" and this is the implementation for the Microsoft JDBC driver for SQL Server. There are users who rely on this behavior so it can not, and will not be changed.  I'm sorry if this wasn't clear in the previously issue. I would suggest that you contact support with your vendor to handle this properly.

As for adding an option to toggle this, I have added this as a feature request but given the reasons mentioned previously and that no one else had ever had a problem with this before this will likely be quite low priority. However fyi here is a link to our [Survey ](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAFhcKCP4bxUQUxBNDA1NjRER0Y5SVhRQ1hSN0g1Q09MQS4u) you can request features and or fixes there we do take into consideration the impact/severity of the issue, and the number of user upvotes when we do planning for each semester.

**Comment by Jeffery-Wasty** [comment]
As per [this comment](https://github.com/microsoft/mssql-jdbc/issues/1703#issuecomment-1369789662), the fix has been "implemented in IronJacamar and is present in recent WildFly". Closing issue.

**Comment by roeltje25** [comment]
Thank you very much for picking this up upstream.
