### ISSUE TITLE
SQLServerException provides null SQLState and 0 error code

### ISSUE THREAD

**Issue by labkey-adam** [microsoft/mssql-jdbc#2015]
## Driver version
12.1.0.jre11-preview

## SQL Server version
Microsoft SQL Server 2022 (RC1) - 16.0.950.9 (X64)

## Client Operating System
Windows 10

## JAVA/JVM version
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

## Table schema
N/A

## Problem description
SQLExceptions thrown by the 12.1.0 preview driver no longer include valid SQLState or error code values. This appears to be a significant regression since many applications rely on these values for proper exception handling. We happen to use Spring SQLExceptionTranslators to translate SQLExceptions into standard Spring runtime exceptions (DataIntegrityViolationException and DeadlockLoserDataAccessException in the below examples) and the translations are now failing because these return values are incorrect.

A couple examples that our test suite flagged are provided below, but this is likely not an exhaustive list.

## Expected behavior
In previous versions (11.2.1, 10.2.1), calling getSQLState() returned a valid SQL state code and getErrorCode() returned a valid vendor code. Two examples:

- Divide by zero ("com.microsoft.sqlserver.jdbc.SQLServerException: An error occurred during the current command (Done status 0). Divide by zero error encountered."):
  - e.getSQLState() returned "S0001"
  - e.getErrorCode() returned 8134
- Deadlock loser ("com.microsoft.sqlserver.jdbc.SQLServerException: An error occurred during the current command (Done status 0). Transaction (Process ID 66) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction."):
  - e.getSQLState() returned "40001"
  - e.getErrorCode() returned 1205

## Actual behavior
With the preview driver, the above exceptions no longer provide valid values. In both cases:
- e.getSQLState() returns null
- e.getErrorCode() returns 0

Let me know if you need more information to resolve this.

**Comment by tkyc** [comment]
Hey @labkey-adam, thanks informing us. I'm able to reproduce the issue. We'll look into the bug.

**Comment by Jeffery-Wasty** [comment]
In the meantime, are you able to use the previous stable version, 11.2.1?

**Comment by labkey-adam** [comment]
@tkyc and @Jeffery-Wasty Thanks for the quick responses. Yes, we are able to use 11.2.1, no problem. We appreciate your efforts!

**Comment by tkyc** [comment]
Hi, we just released a 11.2.3 version of the driver with the fix.

**Comment by labkey-adam** [comment]
That's great, @tkyc ! Is there a plan to release a new 12.x preview version?

**Comment by Jeffery-Wasty** [comment]
Hi @labkey-adam,

The 12.2.0 release is planned for the end of this month, Jan 31st.

**Comment by lilgreenbird** [comment]
fixed in #2018
