### ISSUE TITLE
[QUESTION] Get `0x81` varchar from jdbc

### ISSUE THREAD

**Issue by HariHaravelan** [microsoft/mssql-jdbc#2035]
## Question
For SQL server 2012 table with the VARCHAR column, contains a `0x81` character. When using JDBC `resultset.getString` to read the column, `efbfbd (Replacement Character in UTF-8)` is obtained. This seems to be due to `0x81` being unused in Windows-1252 (https://www.ascii-code.com/), so it can not be converted to `UTF-8`

Two questions:
1. the column is used to store hash values, and it may contain some unused characters. What is the best option to store the values? like `varbinary` or `nvarchar`?
2. for the JDBC connection, is it possible to set a session with a specific character set?
for example, for MySQL JDBC connection, the "characterEncoding=Cp1252" option may be used. Is there a similar way for SQL Server?

**Comment by Jeffery-Wasty** [comment]
Hi @HariHaravelan,

Can we get additional information as to what is happening here. Would you be able to share with us the data being retrieved, and how you're doing it? For JDBC there is a parameter, `sendStringParametersAsUnicode` that may be what you're looking for, but its tough to say without additional detail

**Comment by HariHaravelan** [comment]
I have table `test`
#### Create
`create table test (a int primary key, b varchar(50));`
#### Insert 
```
insert into test select 1, convert (varchar(50),0x233F);
insert into test select 2, convert (varchar(50),0x2381);
```
Executing this query gives me the below output
`select a,cast(b as varbinary(50)) FROM test`
<img width="398" alt="read as binary" src="https://user-images.githubusercontent.com/1903425/211534280-ae6d5cbc-4dea-455a-86ef-c65909979feb.png">


when I read that data using MS-SQL JDBC driver using the below snippet
  ```
  public static void main(String[] args) {

        String connectionUrl = "jdbc:sqlserver://localhost:1434;encrypt=false;databaseName=qatest;user=sa;password=w3b@ct10n;";

        try (Connection con = DriverManager.getConnection(connectionUrl)) {
            Statement stmt = con.createStatement();
            String SQL = "SELECT cast(b as varbinary(100)) as c,* FROM test";
            ResultSet rs = stmt.executeQuery(SQL);

            while (rs.next()) {
                System.out.println(rs.getInt("a") + "\t" + rs.getString("b"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }
```
It gives output 
```
1	#?
2	#�

```
Both `#? and #�` converts to binary data`0x233F`
`0x2381` also converts into `0x233F`
This seems to be due to 0x81 being unused in Windows 1252

How do I read the data without losing bytes data value using MS-SQL JDBC, please assist?

### Environmental details

#### SQL Server version
Microsoft SQL Server 2012 
#### DB Charset : 
SQL_Latin1_General_CP1_CI_AS

#### JAVA/JVM version
OpenJDK Version "1.8.0_201"

**Comment by Jeffery-Wasty** [comment]
Would it be possible for the existing Windows 1252 tables to be converted to UTF 8? I don't see an option that allows the driver to recognize a 1252 input and allow for character compatibility or prevent data loss. I do see there are conversion options, including using Windows API [MultiByteToWideChar](https://msdn.microsoft.com/en-us/library/windows/desktop/dd319072%28v=vs.85%29.aspx), that can be used to convert successfully.

**Comment by Jeffery-Wasty** [comment]
Hi @HariHaravelan,

Just following up on the previous comment, is this switch something that you'd be able to implement?

**Comment by Jeffery-Wasty** [comment]
We'll close this issue in the next few days if there is no further activity. Please let us know if there is anything else we can help you with regarding this issue.
