### ISSUE TITLE
Bulk Insert using PreparedStatement with an IDENTITY column raises exceptions

### ISSUE THREAD

**Issue by JohnAtPheasantVille** [microsoft/mssql-jdbc#2036]
## Driver version
12.1.0.jre11-preview

## SQL Server version
Microsoft SQL Server 2019 (RTM-CU18) (KB5017593) - 15.0.4261.1 (X64)   Sep 12 2022 15:07:06   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19045: ) 

## Client Operating System
WINDOWS 10 Pro, Version 22H2, Build 19045.2364

## JAVA/JVM version
JDK 19.0.1

## Table schema
MS provided AdventureWorks database (but any database will do as will CREATE a new Table in Java source

## Problem description
Referring to 
https://learn.microsoft.com/en-us/sql/connect/jdbc/use-bulk-copy-api-batch-insert-operation?view=sql-server-ver16

I created a scratch Java program (attached, suffix renamed from .java to .txt) that 
a) Connects to MS-SQL AdventureWorks
b) Creates a simple SELECT statement to check communicating with SQL Server ok (not needed to reproduce issue)
c) Create a new SQL table (Person.Test) with two columns, IDENTITY and VARCHAR
d) Attempt (by various means) to BULK insert a 1000 rows into the table (using MS Web page quoted above as a template)
e) Various exceptions raised depending on approach - listed below

Checked that Table is being Dropped and Created and Selectable by adding Break points to the source and querying the table in SSMS.

1) Leave the first column undefined (similar to if using a CSV leaving the first field empty - e.g. ",Text"). This is how the attached java source is setup. I would have expected, by not defining column 1 as it is an IDENTITY field that the driver would detect this and so auto-generate new identity integers for each row.

SQL Exception: com.microsoft.sqlserver.jdbc.SQLServerException: The value is not set for the parameter number 1.

Stack Trace
  com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237) com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.buildParamTypeDefinitions(SQLServerPreparedStatement.java:441)
com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.buildPreparedStrings(SQLServerPreparedStatement.java:394)  com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatementBatch(SQLServerPreparedStatement.java:2817)  com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtBatchExecCmd.doExecute(SQLServerPreparedStatement.java:2774)
  com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7637)
  com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4027)
  com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:270)
  com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:244)
  com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2171)
  Scratch.ConnectToSqlServer.main(ConnectToSqlServer.java:74)

2) Uncomment the lines marked [A] to provide the insert with specified IDENTITY values gives the following exception

SQL Exception: java.sql.BatchUpdateException: An explicit value for the identity column in table 'Person.Test' can only be specified when a column list is used and IDENTITY_INSERT is ON.

Stack Trace
  com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2180)
  Scratch.ConnectToSqlServer.main(ConnectToSqlServer.java:74)

3) Comment back the [A] and uncomment [B]  ("; useBulkCopyForBatchInsert=true") to request the use of Bulk Insert for performance gives the following exception

SQL Exception: java.sql.BatchUpdateException: Unable to retrieve data from the source.

Stack Trace
  com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2138)
  Scratch.ConnectToSqlServer.main(ConnectToSqlServer.java:74)

4) Finally, uncommenting out the 3 statements marked [A] gives the same exception as in (2) above

## Expected behavior
The 1000 rows to be added to table Person.Test
## Actual behavior
Exceptions reported as described above in points [1..4]
## Error message/stack trace
Detailed above (and reproducible from the source file attached)
## Any other details that can be helpful
None that I can think of
[ConnectToSqlServer.txt](https://github.com/microsoft/mssql-jdbc/files/10392569/ConnectToSqlServer.txt)

## JDBC trace logs
Provide the JDBC driver trace logs.  Instructions can be found here: https://docs.microsoft.com/sql/connect/jdbc/tracing-driver-operation

**Comment by tkyc** [comment]
Hi, we'll do some investigating on our end and get back to you. At the moment we're performing release tasks so answers may be delayed.

**Comment by JohnAtPheasantVille** [comment]
Following on from advice from those responsible for the documentation (see related GitHub issue [(https://github.com/MicrosoftDocs/sql-docs/issues/8478)]) I have managed to do a Bulk Insert using the same table and data using the SQLServerBulkCopy() class, although this is a lot more longwinded than using the useBulkCopyForBatchInsert=true option on the connection string. For comparison, I have also attached the two source files needed for this approach (again, having changed the suffix from .java to .txt).
[ConnectToSqlServer.txt](https://github.com/microsoft/mssql-jdbc/files/10427956/ConnectToSqlServer.txt)
[SqlBulkRecord.txt](https://github.com/microsoft/mssql-jdbc/files/10427957/SqlBulkRecord.txt)

**Comment by JohnAtPheasantVille** [comment]
David,

Thanks for pointing this out. I would never have spotted that as my background thought process reminded me that all the columns must be declared for the Bulk Insert to work (e.g. when importing CSV files) and also when I implemented the ISQLServerBulkRecord interface. 

I have since expanded the example to 4 columns in the SQL data table to get a better feel of the requirements when dealing with the MS-SQL server only version. 

It took a couple of goes to get your suggestion to work as I first thought that the INSERT INTO only needed to declare enough ? for the columns I was importing (1 in my case). This didn't work as got the 'number of columns doesn't match' and so tried 3 ? (omitting just the identity column) and defining NULL values for the other two columns and this worked. In essence you have to pretend that the IDENTITY column doesn't exist and so all the other columns are then referenced from 1 (rather than 2 as would be the case for my example table attached above).

I have a GitHub issue for expanding the documentation to handle an IDENTITY column which should help others if they explore this route.

I have since implemented the MS-SQL API one and while it means that I have to reference the MS-SQL JDBC API rather than go through java.sql to keep a generic interface and the ISQLServerBulkData implements Serializable which caused me a few issues, I now have both working and so will look forward to comparing the performance of each.

One small query, if I could be indulgent regarding 

Set<Integer>	ISQLServerBulkRecord.getColumnOrdinals()

The documentation says that your implementation of the interface should "Get the ordinals for each of the columns represented in this data record."

I have set this to 1, 2, 3, .. n, where n is the number of columns in the table (including the IDENTITY column). 

My question is - When would you not just return set(1, 2, 3, 4, ... n) as otherwise why not just supply the number of columns in the table? I must be missing what the true purpose of this method is.

Thanks so much for your time in resolving my query. Apart from an appreciated answer to the question above, this issue can be closed.

**Comment by tkyc** [comment]
>My question is - When would you not just return set(1, 2, 3, 4, ... n) as otherwise why not just supply the number of columns in the table? I must be missing what the true purpose of this method is.

There isn't any specific reason for that method that I'm aware of (this was before my time). To me, the method looks more like a potential for trouble if the implementation doesn't return an ordered set of ordinals if that is what is expected.
