### ISSUE TITLE
[FEATURE REQUEST] Configurable interface name

### ISSUE THREAD

**Issue by gwi42** [microsoft/mssql-jdbc#2037]
We would like to be able to configure the client interface name for SQL Server profiling and logging tools.
We're currently maintaining a custom build with the changes in the attached PR.

Comments/Suggestions are very welcome!

We'd be happy if this would be considered for merge, so we can start using the standard version again.

**Comment by Jeffery-Wasty** [comment]
Hi @gwi42,

We'll take a look at this and get back to you on how we'd like to move forward with the feature. A customizable interface name sounds handy, but may cause other issues, so we'll look through it. We will not be able to fully look through this until our GA release is out at the end of January, at the very least, but will get back to you when we do.

**Comment by Jeffery-Wasty** [comment]
Can we ask about your use case, why do you need a custom interfaceName? Why not instead use the appName? Looking at appName, it looks as if it was satisfy your use case as that allows pass in a custom name value (see application name [here](https://learn.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver15)).

**Comment by gwi42** [comment]
Hi @Jeffery-Wasty,
we have an application that uses separate connections in submodules.
These can be identified with the interfaceName and as we generate statistics for each submodule, we need to be able to set both the application name as well as the interface name.

**Comment by Jeffery-Wasty** [comment]
Ok, thank you for the explanation. We'll triage the issue and get back to you on when/if this is something we move forward with. Is the custom build working well for you? Would you be able to keep using it for the time-being?

**Comment by gwi42** [comment]
Yes, we already maintain it for quite a while and just thought of trying to get this merged into the main version to reduce our maintenance overhead. Thanks for considering it!

**Comment by David-Engel** [comment]
Why couldn't you use a formatted application name? Like `applicationName=[interface]-[submodule]`?

The interface name is used on the server side to differentiate which drivers are used when. It helps identify problematic drivers. If we allow customers to override it, it makes identifying driver issues (on a global scale) more difficult. This change is not going to happen.

**Comment by gwi42** [comment]
Hi @David-Engel,
Thanks for your clarification.
I'll remove the PR and close the issue...
