### ISSUE TITLE
Null/Junk character gets injested while Bulk insert but not on single query insert

### ISSUE THREAD

**Issue by Utkarshpatel05** [microsoft/mssql-jdbc#2046]
Hi Developers,

I am facing a weird issue. I am trying to insert records with Bulk Copy but the data inserted are having unwanted null/junk characters between the data character for a specific column. 
Eg : 
Original Data : HR
Data in database : H R 
Please check the ScreenShot (unwanted_Character_issue_Screenshot.png) for the issue. The Screenshot consist of the data exported by the result of the Query : Select * from abc.
In the SQL Server Management Studio the Data is visible as shown in Screenshot (Sqlserver studio perspective.png).
The data is injested but due to unwanted null character it is causing trouble with other application.

I have checked the encoding of the source Data, It was US-ASCII
Also there are no hidden characters in the data. But however upon insert using Bulk Copy it adds null character for that column data only. 

Column definition : [abc] [nvarchar](255) NULL
The collation of that column is SQL_Latin1_General_CP1_CI_AS
There are no constraints or index on this column
Java : 11

I have used below statement to insert 
SQLExecutor.getInstance().insertRecord(new TableServerBulkRecord(table,metaData), table.getTableName(), metaData);

[TableServerBulkRecord.txt](https://github.com/microsoft/mssql-jdbc/files/10463903/TableServerBulkRecord.txt)
![unwanted_Character_issue_Screenshot](https://user-images.githubusercontent.com/49652987/213636999-f19fc2c4-7db1-441a-a6d4-77ec17ce0140.png)
![Sqlserver studio perspective](https://user-images.githubusercontent.com/49652987/213638430-fb0fc3e8-31f1-4015-9039-0c965d2b3fc3.png)

**Comment by Utkarshpatel05** [comment]
The collation of that column is  SQL_Latin1_General_CP1_CI_AS

**Comment by Jeffery-Wasty** [comment]
Hi @Utkarshpatel05,

We'll look into this issue. If there was just a character inserted at the end, it might make sense, but the character being inserted in between the others is very odd. We'll get back to you with our findings. Which version of the driver are you using? Additionally, which version of SQL Server are you using?

**Comment by Jeffery-Wasty** [comment]
Closed for inactivity. Please comment if you're still having the issue and are able to provide us with additional information.

**Comment by Utkarshpatel05** [comment]
Hi @Jeffery-Wasty,

The issue has been resolved. We found that the order of the columns in column list mapped with data was incorrect. After correcting the mapping it was working alright.
Thanks for the support.
