### ISSUE TITLE
[FEATURE REQUEST] Release a Java 19 / jre19 version to Maven Central

### ISSUE THREAD

**Issue by Harmelodic** [microsoft/mssql-jdbc#2047]
## Is your feature request related to a problem? If so, please give a short summary of the problem and how the feature would resolve it
I'd like to use the latest JDK and JRE (19) for running my applications, and not have to compile my own jre19 version of `mssql-jdbc`

## Describe the preferred solution
There be an available version of `mssql-jdbc` on [Maven Central](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc) that supports Java 19.

## Describe alternatives you've considered
I could build my own version and use that, but that would involve building my own version and then hosting it somewhere (or building it as part of building the application), whereas the optimal solution is just to use the official version from Maven Central, like you can for jre18, jre17, etc.

## Additional context
I tried to download this repository and just do `mvn package -Pjre19`, as stated in the README for this repo and the tests failed.
`mvn compile -Pjre19` worked though.

**Comment by Jeffery-Wasty** [comment]
Hi @Harmelodic,

Starting with release 12.1.0, we've consolidated all releases into one of two types: Java 8 and Java 11+. The Java 11 version you see on Maven ([12.1.0.jre11-preview](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc/12.1.0.jre11-preview)), is a Java 11+ version, compatible with Java 11, 17, and 19, and therefore can be used with jre19 as you have described in your setup.

**Comment by lilgreenbird** [comment]
please let us know if you have further questions otherwise we will be closing this issue since this answers your question

**Comment by Harmelodic** [comment]
Closing, since new version will offer jre19 support, via being JDK11+ supportive.

**Comment by Harmelodic** [comment]
Re-opening for a quick further question:

Why keep the `.jre11` naming standard? Why not change to just a normal SemVer version and then document that it supports LTS & latest?

Then _maybe_ have a `.jre8` version, for people who are still on Java 8 (even though they shouldn't be).

**Comment by lilgreenbird** [comment]
we do have a jre8 jarfor Java 8 please see [12.1.0 preview release](https://github.com/microsoft/mssql-jdbc/releases/tag/v12.1.0). The jre11 jar supports Java 11 and later we kept this as this makes it more obvious which Java version it supports and this is similar to the naming scheme in other drivers.

**Comment by Harmelodic** [comment]
I would argue that it is actually _less_ clear in what versions of Java the driver supports because it is going to support _more_ than just Java 11.

I will find it _very_ confusing if I'm developing an application using Java 19, and then looked in my dependency management file and saw I was using a driver marked `jre11`, and then had to look in documentation/this PR to find out that it's actually fine.

In my opinion, it would be better if the driver version was just a [Semantic Version](https://semver.org/), and then there was documentation available to detail which versions of the driver supported which Java versions, for those who want/need to know.
