### ISSUE TITLE
Insert query parameters are generated with nvarchar(4000) instead of actual column length in the DB

### ISSUE THREAD

**Issue by vaibhavs-uipath** [microsoft/mssql-jdbc#2050]
## Driver version
tried both 10.2.1.jre8 and 11.2.3.jre8 (latest)

## SQL Server version
Microsoft SQL Azure (RTM) - 12.0.2000.8 Nov 8 2022 12:27:23 Copyright (C) 2022 Microsoft Corporation

## JAVA/JVM version
java 11

## Table schema
CREATE TABLE [dbo].[audit_logs](
	[id] [nvarchar](36) NOT NULL,
	[tenant_id] [nvarchar](36) NULL,
	[account_id] [nvarchar](36) NULL,
	[organization_id] [nvarchar](36) NOT NULL,
	[entity_id] [nvarchar](36) NULL,
	[entity_type_name] [nvarchar](36) NULL,
	[code] [nvarchar](50) NULL,
	[message] [nvarchar](200) NULL,
	[data] [nvarchar](100) NULL,
	[severity] [nvarchar](50) NULL,
	[type] [nvarchar](36) NULL,
	[action] [nvarchar](50) NULL,
	[created_on] [bigint] NULL,
	[modified_on] [bigint] NULL,
	[created_by] [nvarchar](50) NULL,
	[modified_by] [nvarchar](50) NULL,
	[error_log] [nvarchar](4000) NULL,
	[entity_name] [nvarchar](100) NULL,
	[metadata] [nvarchar](4000) NULL,
	[level] [nvarchar](36) NULL,
	[project_id] [nvarchar](36) NULL,
	[user_name] [nvarchar](50) NULL,
 CONSTRAINT [PK_AUDIT_LOGS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)

## Problem description
We are using java(spring-boot) with mssql. The insert query generated has params with nvarchar(4000) instead of column length in DB. I tried mentioning column length in the Entity class using **@Column(length=50)** but some how mssql is generating param with len 4000.
This is the query that was generated: 

Declare 
 **@P0 nvarchar(4000),**@P1 bigint,@P2 nvarchar(4000),@P3 bigint,@P4 nvarchar(4000),@P5 nvarchar(4000),@P6 nvarchar(4000),@P7 nvarchar(4000),
 @P8 nvarchar(4000),@P9 nvarchar(4000),@P10 nvarchar(4000),@P11 nvarchar(4000),@P12 nvarchar(4000),@P13 nvarchar(4000),
 @P14 nvarchar(4000),@P15 nvarchar(4000),@P16 nvarchar(4000),@P17 nvarchar(4000),@P18 nvarchar(4000),@P19 nvarchar(4000),
 @P20 nvarchar(4000),@P21 nvarchar(4000)

 insert into dbo.audit_logs (created_by, created_on, modified_by, modified_on, account_id, organization_id, tenant_id, 
 project_id, action, code, data, entity_id, entity_name, entity_type_name, error_log, level, message, metadata, severity, type,
  user_name, id) values
  (@P0, @P1, @P2, @P3, @P4, @P5, @P6, @P7, @P8, @P9, @P10, @P11, @P12, @P13, @P14, @P15, @P16, @P17, @P18, @P19, @P20, @P21)
  
## Expected behavior
query should generate  **@P0 nvarchar(50)** and similar for other parameters.

**Comment by tkyc** [comment]
Hi, we are aware of this issue. The discussion can be continued here https://github.com/microsoft/mssql-jdbc/issues/1826.
