### ISSUE TITLE
`@@TRANCOUNT` is called when calling `setAutoCommit(true)` even if `@@TRANCOUNT` is not supported.

### ISSUE THREAD

**Issue by jbruggem** [microsoft/mssql-jdbc#2054]
## Driver version
MSSQL JDBC driver version: 11.2.3

## SQL Server version

SQL pool in Azure Synapse

```
Microsoft SQL Azure (RTM) - 12.0.2000.8 
Jan 19 2023 13:50:08 
Copyright (C) 2022 Microsoft Corporation
```

## Client Operating System

Linux

## JAVA/JVM version

openjdk 11.0.13 2021-10-19 LTS

## Table schema

Any table schema will do. 

## Problem description

I am trying to read data from a *serverless* SQL pool in Azure Synapse using [Confluent's Kafka Connect JDBC](https://github.com/confluentinc/kafka-connect-jdbc/). 

Microsoft's documentation on Synapse mentions that [@@TRANCOUNT](https://learn.microsoft.com/en-us/sql/t-sql/functions/trancount-transact-sql?view=sql-server-ver16) is not supported in Synapse. 

Unfortunately, when [Kafka Connect JDBC calls `setAutoCommit(true)`](https://github.com/confluentinc/kafka-connect-jdbc/blob/e9746cf78cf6cdf5760b924d7248145a26c4b730/src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java#L516), it seems that the MSSQL JDBC driver [calls @@TRANCOUNT](https://github.com/microsoft/mssql-jdbc/blob/901ec95427f8e8333296346c93a69efbd012b366/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L4040). 

This results in an exception : `Caused by: com.microsoft.sqlserver.jdbc.SQLServerException:  '@@TRANCOUNT' is not supported.`

## Expected behavior

I was hoping that `setAutoCommit(true)` wouldn't call unsupported transaction-related features.

## Actual behavior

It seems that it isn't possible to call `setAutoCommit(true)` if the server doesn't support transactions.

## Error message/stack trace

Stack trace of the exception mentioned above:

```
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException:  '@@TRANCOUNT' is not supported.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:300)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:133)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:26)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$1ConnectionCommand.doExecute(SQLServerConnection.java:4027)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7620)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3916)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectionCommand(SQLServerConnection.java:4035)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.setAutoCommit(SQLServerConnection.java:4182)
	at io.confluent.connect.jdbc.source.JdbcSourceTask.validateNonNullable(JdbcSourceTask.java:516)
```

**Comment by tkyc** [comment]
Hi, we'll look into this and see what's the appropriate fix for this.

**Comment by lilgreenbird** [comment]
hi @jbruggem 

According to the documentation you linked @@TRANSCOUNT does apply to Azure Synapse Analytics

![image](https://user-images.githubusercontent.com/8549794/214965373-130f3116-9c1d-41cb-b597-d6258aedd344.png)

However the note says that it's not supported by **serverless** SQL pool in Azure Synapse Analytics which is what you are using.

Why is your application calling the setAutoCommit API which is used to manage transactions if transactions are not supported on your server? It looks like you will need to either use a database that supports transactions if you want to manage your own transactions using this API, or request changes to the app you are using to support a mode that doesn't require transactions. 

btw I found this [article](https://forum.knime.com/t/querying-data-in-a-serverless-sql-pool-in-azure-synapse/38640) which looks similar to the issue you are seeing, they suggested to try `SET IMPLICIT_TRANSACTIONS OFF` as a workaround which didn't work for them and they eventually had to add disabling transactions in their app. But maybe this is worth a try for you?

**Comment by jbruggem** [comment]
@lilgreenbird as mentionned in the original description, I'm using Kafka Connect's JDBC to connect to the serverless SQL pool. I'm therefore *not* in control of the code that interacts with the driver, and I can't run my own queries.

I can configure KC JDBC to stay in `READ_UNCOMMITTED` mode, but I can't prevent it to call `setAutoCommit`.

**Comment by lilgreenbird** [comment]
ok that was just a suggestion to see if you can find a workaround to your issue. 

In any case there's nothing the driver can do, if you are calling `setAutoCommit` to manage transactions then you will need to use a database that support transactions.

**Comment by jbruggem** [comment]
OK, thanks for your quick replies.
