### ISSUE TITLE
Make TnirFirstAttemptTimeoutMs configurable

### ISSUE THREAD

**Issue by motymichaely** [Microsoft/mssql-jdbc#206]
Hey,

The current hardcoded setting of TnirFirstAttemptTimeoutMs of 500ms can cause failures on high latency connections (for instance, when running hybrid  cloud environments). I am not sure how turning TransparentNetworkIPResolution off can impact connectivity to AlwaysOn servers but this doesn't sound to be a valid solution when compared to having the ability to set custom timeout value. For instance, having TransparentNetworkIPResolutionTimeoutMs property in the driver can do the trick.

Any objections?

**Comment by v-xiangs** [comment]
Hello @motymichaely. Thank you for filling the issue. We have noticed the issue and started to work on it. Please stay tuned. 
In the meanwhile, you can set transparentNetworkIPResolution to false and set multiSubnetFailover to true. This will skip using of TnirFirstAttemptTimeoutMs and still be able to connection to AlwaysOn servers. Also, if it's high latency network, increasing loginTimeout at the same time will help too. Please let me know if this does not solve the problem.

**Comment by motymichaely** [comment]
@v-xiangs - Thanks! Looking forward for a fix.

I've already tried `transparentNetworkIPResolution=false` together with `multiSubnetFailover=true` but it didn't solve the problem. It only worked when setting `transparentNetworkIPResolution=false` and `multiSubnetFailover=false` but this doesn't seem like a good idea for AlwaysOn servers.

**Comment by v-xiangs** [comment]
@motymichaely Thank you for getting back to us. You are right, setting transparentNetworkIPResolution=false and multiSubnetFailover=false is not a good solution for AlwaysOn servers. Before we fix this issue in the driver, could you please also try increasing the loginTimeout as well? Thank you.

**Comment by motymichaely** [comment]
@v-xiangs - Thanks for clarification.

Unfortunately, loginTimeout has no impact.

**Comment by v-xiangs** [comment]
@motymichaely I am sorry to hear that.. please stay tuned. We will provide a fix for it as soon as possible.

**Comment by v-xiangs** [comment]
Hello @motymichaely , sorry to keep you waiting for so long. If the problem still persists, would you like to try out the new PR #240 we created? With this PR, you will not be able to set `TransparentNetworkIPResolutionTimeoutMs` property, instead, we increased time slice for each connection when setting `transparentNetworkIPResolution=false`. I hope this works for you.

**Comment by v-xiangs** [comment]
@motymichaely Hello. Did you have chance to test the PR?

**Comment by v-xiangs** [comment]
@motymichaely Hello. We are closing this issue since we haven't heard from you. Please feel free to re-open it if the issue still bothers you.
