### ISSUE TITLE
Regression - Stored procedure can't be executed - "Parameter {...} was not defined for stored procedure"

### ISSUE THREAD

**Issue by JackPGreen** [microsoft/mssql-jdbc#2063]
## Driver version
12.2.0.jre11

## SQL Server version
Microsoft Azure SQL Edge Developer (RTM) - 15.0.2000.1565 (ARM64)  	Jun 14 2022 00:37:12  	Copyright (C) 2019 Microsoft Corporation 	Linux (Ubuntu 18.04.6 LTS aarch64) <ARM64>

## Client Operating System
Mac OSX

## JAVA/JVM version
org.eclipse.justj.openjdk.hotspot.jre.full.macosx.aarch64_17.0.2.v20220201-1208

## Problem description
After upgrading from 11.2.1 to 12.2.0, when executing a stored procedure we get `Parameter {...} was not defined for stored procedure`.
This affects multiple different OS and database versions.

From debugging the source code this looks to have been introduced in https://github.com/microsoft/mssql-jdbc/pull/1898.

In `com.microsoft.sqlserver.jdbc.SQLServerCallableStatement.findColumn(String)`, a `metaQuery` is constructed to get information on the stored procedures' columns.

In both 11.2.1 & 12.2.0, the `metaQuery` returns no results.

The following section then attempts to get a position from `map` - if `parameterNames` was `null`, previously it would return a value (the next increment of `ai`) - whereas now it will only do this if `parameterNames` is non-`null` and has exactly one element.

Therefore no results are returned, and the query fails.

You can probably see this change more clearly here - https://github.com/microsoft/mssql-jdbc/commit/fa48f7cbb7505f3ca2bdfd4fe6b65c491184fd30

**Comment by tkyc** [comment]
Hi, could you share an example stored procedure that reproduces the error. I was wrong in assuming `metaQuery` should always have a result.

**Comment by JackPGreen** [comment]
> Hi, could you share an example stored procedure that reproduces the error. I was wrong in assuming `metaQuery` should always have a result.

Sorry, unfortunately I'm not able to share a minimal example of the stored procedure.

I did run the generated `metaQuery` on the database itself and got no results their either if it helps.
