### ISSUE TITLE
Mandatory jdk.net OSGi-import 

### ISSUE THREAD

**Issue by MrEasy** [microsoft/mssql-jdbc#2068]
## Driver version
12.2.0

## JAVA/JVM version
17.0.6

## Problem description
With change of issue https://github.com/microsoft/mssql-jdbc/issues/2042 a check for non-mandatory jdk.net.ExtendedSocketOptions was added.
This is done in a fail-safe way [here](https://github.com/microsoft/mssql-jdbc/blob/d842883e3e69420a7a798294cb58ac252eead011/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDriver.java#L1000), but the Class#forName call leads a mandatory Import-Package being created in the manifest on package ``jdk.net``, which was probably not intended and can lead to issues in OSGi-environments not providing this package:
``Unable to resolve com.microsoft.sqlserver.mssql-jdbc/12.2.0: missing requirement [com.microsoft.sqlserver.mssql-jdbc/12.2.0] osgi.wiring.package; filter:="(osgi.wiring.package=jdk.net)"``

## Expected behavior
Would expect the Import-Package being declared as optional to also deploy in an environment without the package being exported.

**Comment by tkyc** [comment]
Thanks for bringing this to our attention. We'll look into it.

**Comment by tkyc** [comment]
I just opened a PR. Let us know if it resolves the problem for you. Thanks.

**Comment by MrEasy** [comment]
> I just opened a PR. Let us know if it resolves the problem for you. Thanks.

Thank you - Can confirm, that issue is resolved with jdk.net;resolution:=optional in manifest.
Did not build it anew, but modifed manifest directly with your change.
