### ISSUE TITLE
Support JPA Logging with a proper toString function in SQLServerStatement

### ISSUE THREAD

**Issue by suchwerk** [microsoft/mssql-jdbc#2086]
Hibernate JPA has a slow query logging. The preparedStatment which is slow is logged. With mssql-jdbc this is useless due the lack of a proper toString function for prepared statements.

```
2023-02-27 14:35:49 INFO  [org.hib.SQL_SLOW] f33ac0603c4f (executor-thread-2075) SlowQuery: 91 milliseconds. SQL: 'wrapped[ SQLServerPreparedStatement:1643213 ]'
```
 
I would like to see the sql query in the quarkus logs.

[SQLServerStatement.java](https://github.com/microsoft/mssql-jdbc/blob/9cbaf1754194c4a6391e192f12fc59df7ad3ee03/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java)

**Comment by Jeffery-Wasty** [comment]
Hi @suchwerk,

Thank you for the enhancement idea. We're always looking to improve communication with users through better logging. This is something we'll consider when we're looking to implement the next round of enhancements.

**Comment by Jeffery-Wasty** [comment]
Sorry, just re-reading the issue, what are you looking for the "proper" toString function to return?

**Comment by suchwerk** [comment]
The toString function should particularly return the sql query.

**Comment by Jeffery-Wasty** [comment]
Yes, I see now you mentioned that in the original post, apologies for missing that. We'll look into adding this as part of a set of changes to improve logging and error messages. We'll keep you updated on the progress.
