### ISSUE TITLE
[QUESTION] the diffrence between Statement and PreparedStatment

### ISSUE THREAD

**Issue by foojane** [microsoft/mssql-jdbc#2095]
### Driver version
	<groupId>com.microsoft.sqlserver</groupId>
	<artifactId>mssql-jdbc</artifactId>
	<version>9.2.1.jre8</version>
### SQLServer version
SQL Server 12.0.5000.0
### JDK version
JDK 1.8

I have a large table which contains over 10 Millions rows, when i run the sql "select * from table where createTime='20230220'" in SQL Server Mangement Studio, it returns data immediately and continuously return data until the end. 
Then i use mssql jdbc driver to query data with the same sql, if I use the statement method, the phenomenon is the same as that executed directly in SQL Server Management Studio,however if i use the prepared statement method,it returns a timeout error.The example code are following
Statement Method
`Connection conn = DriverManager.getConnection(xxx);
PreparedStatement stmt = conn.prepareStatement('select * from table where createTime='20230220'');
stmt.execute();
ResultSet jdbcResult = stmt.getResultSet();`

PreparedStatement Method
`Connection conn = DriverManager.getConnection(xxx);
PreparedStatement stmt = conn.prepareStatement('select * from table where createTime=?');
stmt.setString(1, "20230220");
stmt.execute();
ResultSet jdbcResult = stmt.getResultSet();`
after execute the "stme.execute" command, i get an error message
com.microsoft.sqlserver.jdbc.SQLServerException: Read timed out
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3206)
	at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:2064)
	at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6617)
	at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7803)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:600)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3272)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:505)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:483)
## Relevant Issues and Pull Requests

I guess if sqlserver receives a preparedstatement method it collects all the data before returning to the client and the statement method starts returning once the data is collected
Can anyone help answer this question? thanks a lot!

**Comment by tkyc** [comment]
Running a query with `Statement` will be as close to similar to running a query in SSMS. But for a `PreparedStatement`, the query is wrapped and ran through `sp_executesql` on the server. We do this for prepared statements because we use `sp_executesql` for batches and parameterization.

This one difference shouldn't have such an impact on your case. This makes me think it has something to do with a bad query plan. Another way to see or phrase your case, is "_performance differences of query in applications vs. SSMS"_. If you google this topic, you'll see a lot of discussion on query plans. It's quite possible that between two similar queries, a performance difference can arise just because of a difference in the query plan. So, this is a viable path for more investigating.

Can you try executing the following in SSMS? This should be what the `PreparedStatement` is doing. (Fyi, the `@P0 time` might be the wrong type, so replace `time` with the type appropriate for your `createTime`.)

```
exec sp_executesql N'select * from table where createTime=@P0',N'@P0 time',20230220
```

I'm curious if you'd encounter an error if you execute the above in SSMS.

**Comment by Jeffery-Wasty** [comment]
Hi @foojane,

Just wanted to follow up and see if you were able to try executing the query that Terry provided?

**Comment by foojane** [comment]
> Running a query with `Statement` will be as close to similar to running a query in SSMS. But for a `PreparedStatement`, the query is wrapped and ran through `sp_executesql` on the server. We do this for prepared statements because we use `sp_executesql` for batches and parameterization.
> 
> This one difference shouldn't have such an impact on your case. This makes me think it has something to do with a bad query plan. Another way to see or phrase your case, is "_performance differences of query in applications vs. SSMS"_. If you google this topic, you'll see a lot of discussion on query plans. It's quite possible that between two similar queries, a performance difference can arise just because of a difference in the query plan. So, this is a viable path for more investigating.
> 
> Can you try executing the following in SSMS? This should be what the `PreparedStatement` is doing. (Fyi, the `@P0 time` might be the wrong type, so replace `time` with the type appropriate for your `createTime`.)
> 
> ```
> exec sp_executesql N'select * from table where createTime=@P0',N'@P0 time',20230220
> ```
> 
> I'm curious if you'd encounter an error if you execute the above in SSMS.

Thanks for your helping, I've tried executing the command you supplied,but there is no difference with executing the query in SSMS directly. @Jeffery-Wasty 
By the way, I want to know is there a way to get the execution plan through preparedstatement
### More information related
The createTime field is a non-unique, non-clustered index on the table

**Comment by tkyc** [comment]
@foojane [sys.dm_exec_query_plan(<plan_handle>)](https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-exec-query-plan-transact-sql?view=azuresqldb-current) can be used to get the execution plan.

To get the plan handle, off hand I recall the query below should list all plan handles associated with prepared statements (the query below is just to get you started, you'll likely need to refine it to your needs). I believe you'll have to execute your prepared statement first and then execute the query below.

```
select * from sys.dm_exec_cached_plans where objtype = 'Prepared';
```

**Comment by foojane** [comment]
It seems i found the reson why using PreparedStetement was slower than executing in SSMS.
The data type of createTime in my table is char(8).
When executing in SSMS, the execute plan shows "Index Seek(NonClustered)" with index 'createTime'，but when using PreparedStatement，the type of input was converted to nvarchar(4000),so this query used 'Table Scan' rather than 'Index Seek'
I want to know if there is a way i can set the type of parameter?

**Comment by foojane** [comment]
I also noticed this issue #1826, is there any plan to deal with this situation?

**Comment by tkyc** [comment]
@foojane apologies for the delayed response (for some reason I didn't get notified by email).

>I also noticed this issue https://github.com/microsoft/mssql-jdbc/issues/1826, is there any plan to deal with this situation?

I'll bring this up again in our triage, but I can't make any promises.
