### ISSUE TITLE
SQLServerException: Data type LONGNVARCHAR not supported in Table-Valued Parameter

### ISSUE THREAD

**Issue by rabbit-mom** [Microsoft/mssql-jdbc#210]
hi,I met a problem when I use jdbc 6.1.4.jre7-preview version.A field in a table is "xml" type,I looked up some information on the Internet, the "xml" type is  corresponding with "LONGNVARCHAR",but I use "LONGNVARCHAR" or "LONGVARCHAR" is both not feasible

**Comment by v-suhame** [comment]
@rabbit-mom Thanks for raising this issue! We will add a fix to support xml, along with support for ntext, text, and image. In the meanwhile, you can use VARCHAR or NVARCHAR as the JDBC type to pass xml.

**Comment by v-afrafi** [comment]
@rabbit-mom Could you test Pr #259 . This should fix the issue. Thank you.

**Comment by v-afrafi** [comment]
closing this issue as solved by pr #259. Please feel free to reopen this if you face any issue.  Thanks.
