### ISSUE TITLE
Cannot find JDK 17 Release in Maven Central

### ISSUE THREAD

**Issue by benstpierre** [microsoft/mssql-jdbc#2111]
We were upgrading libraries from v11 to v12 of JDBC for SQL Server. Currently we have 

        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>11.2.3.jre17</version>
        </dependency>

As far as I can see there are no jre17 releases in maven central.  Just JRE 8 and JRE 11.  Looking at the github project it appears you can build for 17 and 19  so why are they no longer in maven central for the new major verison?

<img width="1870" alt="image" src="https://user-images.githubusercontent.com/1399854/231865772-a75c18ed-06d0-4e17-bc0a-94b09e7440b2.png">

**Comment by Jeffery-Wasty** [comment]
Hi @benstpierre,

Starting with release 12.1.0, we're releasing only two versions. A Java 8 version, and a version for Java 11 **and greater**. To use driver version 12.2.0 with jre17, please use the 12.2.0jre11 release.

**Comment by lilgreenbird** [comment]
@benstpierre hope that answers your question please feel free to request re-opening if you have more questions

**Comment by benstpierre** [comment]
![image](https://github.com/microsoft/mssql-jdbc/assets/1399854/32928e4d-0230-45ea-8ff9-57791d2e36b0)
@lilgreenbird looks to me like this is changing in 12.3.x to have versions for JRE 17, 20?

**Comment by Jeffery-Wasty** [comment]
The additional releases for 12.3.0 were a mistake on our part. As you can see by the 12.3.1 releases, we only plan on having 2 releases moving forward.
