### ISSUE TITLE
[QUESTION] setClientCertificate and setClientKey required path to the files, is there an option to pass to it the content of the file ? 

### ISSUE THREAD

**Issue by Vic-tator** [microsoft/mssql-jdbc#2134]
Hey,
setClientCertificate and setClientKey required path to the files, is there an option to pass to it the content of the file? 
Due to security reasons there is not option to put/save this files locally.

**Comment by tkyc** [comment]
Unfortunately there isn't, you'll need to have it on the machine.

**Comment by lilgreenbird** [comment]
You could store the certificate/key anywhere you like eg on AKV and download if needed. I'm not sure how you would pass the "content" of a certificate but no, you will need to specify the path to the location of these files.

**Comment by Vic-tator** [comment]
Do you considering to add such option ?

**Comment by Vic-tator** [comment]
Thank you :)
