### ISSUE TITLE
[FEATURE REQUEST] Publish additional Maven POMs that follow semantic versioning

### ISSUE THREAD

**Issue by dfuenzalida** [microsoft/mssql-jdbc#2135]
## Is your feature request related to a problem? If so, please give a short summary of the problem and how the feature would resolve it

The versioning scheme used to publish the JDBC driver is not compatible with the way [version ranges in Maven](https://www.baeldung.com/maven-dependency-latest-version#maven-version-range-syntax) work. For instance, I can select the newest version of the PostgreSQL driver on the major version 42 with:

```xml
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>(42,)</version><!-- 42.0.0 or later -->
            <scope>runtime</scope>
        </dependency>
```

In the case of the SQL Server JDBC driver, the version of the supported JDK is part of the overall driver version (eg. `12.2.0.jre8`), when I want to pull the latest version of the driver, I'd like use something like:

```xml
<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>mssql-jdbc</artifactId>
    <version>(12.2,)</version>
</dependency>
```

Using this dependency actually pulls `mssql-jdbc-12.3.0.jre20-preview` which is not what I expected if my POM file declares a version of Java earlier than Java 20.

## Describe the preferred solution

What I'd like is to have some versioning scheme that allows me to grab the latest version of the driver for an LTS version of Java.

## Describe alternatives you've considered

I'd like the team to consider publishing additional POMs that resolve to the appropriate version in a way that is compatible with version ranges. I think a solution like the following would work.

New, additional POMs using a new scheme that moves the version of Java from the *version* to the *artifact id* level:

```xml
<project ...>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>mssql-jdbc_jre8</artifactId> <!-- add the version of Java to the artifact id -->
    <version>12.2.0</version><!-- remove the version of Java from the version -->
    <packaging>pom</packaging>
...
<dependencies>
  <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
      <version>12.2.0.jre8</version>
  </dependency>
</dependencies>
...
</project>
```

This would have the benefit of being backwards compatible while enabling applications wanting to consume the specific/newest versions of the driver *for a given Java runtime*, they would be able to do so using the new POM file:

```

<!-- A Java 8 application wanting to consume the latest driver in the 12.2 series -->
<dependencies>
  <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc_jre8</artifactId><!-- Use Java 8 -->
      <version>(12.2,)</version><!-- use version 12.2.0 or newer -->
  </dependency>
</dependencies>
```

## Additional context

This would probably help with the issue discussed in #1504

**Comment by Jeffery-Wasty** [comment]
Hi @dfuenzalida,

We'll look into this further, and see if this is a change we'll look to make.

**Comment by lilgreenbird** [comment]
we will have to keep the current naming scheme as JRE 8 jar is different from 11+. There are APIs that are not supported in JRE 8 so that jar is different.

**Comment by Jeffery-Wasty** [comment]
Hi @dfuenzalida,

We've looked into the idea of adding additional POM files. While there are benefits (that you have explained above), we believe the changes the structure and organization of the project would very easily lead to confusion by someone not privy to the situation. If there was precedent, if other Microsoft drivers did this, we would reconsider, but as we can't find such precedent, we don't believe this to be a good idea to implement.

We'll close this issue now, as this is an enhancement we're not looking to implement.
