### ISSUE TITLE
Not able to connect with SQL Server 2022 with TLS 1.3  

### ISSUE THREAD

**Issue by 4devwithgit** [microsoft/mssql-jdbc#2149]
## Driver version
mssql-jdbc-12.2.0.jre8. Tried using ODBC 18, but cant find the required jar

## SQL Server version
 MSSQL 2022

## Client Operating System
Windows 10

## JAVA/JVM version
java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) Client VM (build 25.333-b02, mixed mode, sharing)
PS C:\Users\naher>

## Table schema
basic connection issue to DB

## Problem description
Trying to connect to SQL 2022, with TLS 1.3 providing all the SSL parameters, while the DB connects fine with TLS 1.2, but fails with TLS 1.3. Here, client is the standalone java program.

## Expected behavior
TLS 1.3 to SQL DB from a java program to be successful.

## Actual behavior
Failing just after the Client Hello, Server terminating the connection

## Error message/stack trace
SQL Driver Registered!
javax.net.ssl|FINE|01|main|2023-06-12 19:24:33.116 IST|Thread.java:1178|jdk.tls.keyLimits:  entry = AES/GCM/NoPadding KeyUpdate 2^37. AES/GCM/NOPADDING:KEYUPDATE = 137438953472
javax.net.ssl|FINE|01|main|2023-06-12 19:24:33.363 IST|Thread.java:1178|duplex close of SSLSocket
javax.net.ssl|FINE|01|main|2023-06-12 19:24:33.368 IST|Thread.java:1178|close the underlying socket
javax.net.ssl|FINE|01|main|2023-06-12 19:24:33.368 IST|Thread.java:1178|close the SSL connection (initiative)
javax.net.ssl|FINE|01|main|2023-06-12 19:24:33.369 IST|Thread.java:1178|wait for close_notify or alert
javax.net.ssl|WARNING|01|main|2023-06-12 19:24:33.376 IST|Thread.java:1178|handling exception (
"throwable" : {
  javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
      at com.ibm.jsse2.bj.a(bj.java:235)
      at com.ibm.jsse2.bj.b(bj.java:360)
      at com.ibm.jsse2.bj.j(bj.java:35)
      at com.ibm.jsse2.bj.h(bj.java:331)
      at com.ibm.jsse2.bj.a(bj.java:483)
      at com.ibm.jsse2.bj.d(bj.java:189)
      at com.ibm.jsse2.bj.d(bj.java:310)
      at com.ibm.jsse2.bj.close(bj.java:70)
      at com.microsoft.sqlserver.jdbc.TDSChannel.disableSSL(IOBuffer.java:813)
      at com.microsoft.sqlserver.jdbc.TDSChannel.close(IOBuffer.java:2200)

## JDBC trace logs
dont have this, will try to enable.

**Comment by Jeffery-Wasty** [comment]
Hi @4devwithgit,

Can you provide us your connection string or connection properties used?

Also, yes, please provide us with additional logging as soon as you can. Instructions on how to do so can be found here: https://learn.microsoft.com/en-us/sql/connect/jdbc/tracing-driver-operation?view=sql-server-ver16.

**Comment by 4devwithgit** [comment]
I am actually able to connect to SQL DB with one change,

		String url = "jdbc:sqlserver://b2biqawinmk2.in.syncsort.dev:1433;databaseName=B2BTEST13";
		
		
		Properties props = new Properties();
		props.setProperty("user", "b2biuser");
		props.setProperty("password", "password");
		
		props.setProperty("encrypt", "strict");
		
		props.setProperty("sslProtocol", sslProtocol);
		
		props.setProperty("trustServerCertificate", "false");
		props.setProperty("trustStore", trustStore);
		props.setProperty("trustStorePassword",trustStorePassword);
		props.setProperty("hostNameInCertificate","b2biqawinmk2.in.syncsort.dev");

Earlier, I was doing,
 **props.setProperty("encrypt", "true");** which didnt work, and I though only the server needs to be in "strict" mode. But its working now with TLSv1.3 as verified from the JDK SSL logs below,

javax.net.ssl|FINE|01|main|2023-06-20 14:44:42.109 IST|Thread.java:1178|Consuming ServerHello handshake message (
"ServerHello": {
  "server version"      : "TLSv1.2",
  "random"              : "FC C6 95 32 3D 01 64 08 52 15 81 A5 94 57 DC 3A 8C F2 77 41 77 3A 33 D5 A5 3D 0E FD D4 9B 0A 2E",
  "session id"          : "79 1A ED F9 FA D7 E3 20 06 EA E9 72 30 92 A2 1F E6 35 C8 BB 3D A3 9F 1A 79 C9 32 10 98 77 BE 24",
  "cipher suite"        : "TLS_AES_256_GCM_SHA384(0x1302)",
  "compression methods" : "00",
  "extensions"          : [
    "supported_versions (43)": {
      "selected version": [TLSv1.3]
    },
    "key_share (51)": {
      "server_share": {
        "named group": secp256r1
        "key_exchange": {
          0000: 04 5e a4 dd f6 6b 3f 03  c8 e2 1b 09 93 39 38 f6  .....k.......98.
          0010: 3f bf 22 be 40 63 a4 fc  b4 dd 0a b0 7c 85 22 98  .....c..........
          0020: bd eb 68 74 fa 99 fb 26  6a 65 56 fd 90 39 b4 ae  ..ht....jeV..9..
          0030: 31 b9 0c b9 b6 09 08 48  1d 08 ec 6a 71 19 e0 d2  1......H...jq...
          0040: f1 
        }
      },
    }
  ]
}
)
javax.net.ssl|FINE|01|main|2023-06-20 14:44:42.109 IST|Thread.java:1178|Consumed extension: supported_versions
javax.net.ssl|FINE|01|main|2023-06-20 14:44:42.110 IST|Thread.java:1178|**Negotiated protocol version: TLSv1.3**

So, I am good now, please verify the DB driver is also good. And we can close this ticket.

**Comment by Jeffery-Wasty** [comment]
Glad to hear you were able to find a resolution, closing the ticket.
