### ISSUE TITLE
Bulk insert with datetime2 and useBulkCopyForBatchInsert=true results in an error "Received an invalid column length from the bcp client"

### ISSUE THREAD

**Issue by krasnyd** [microsoft/mssql-jdbc#2151]
## Driver version
11.2.3.jre17

## SQL Server version
Microsoft SQL Server 2019 (RTM-CU20) (KB5024276) - 15.0.4312.2 (X64)   Apr  1 2023 12:10:46   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19045: ) (Hypervisor) 

## Client Operating System
Windows 10

## JAVA/JVM version
OpenJDK 17.0.7

## Table schema
```sql
create table dbo.JavaTSTError(
	ID int IDENTITY(1,1) primary key, 
	DateColumn datetime2 not null
)
```

## Code for reproducing
```java
package org.example;

import java.sql.*;
import java.time.LocalDateTime;

public class DateTimeProblem {
    public static void main(String[] args) throws Exception {
        String connectionUrl =
                "jdbc:sqlserver://localhost:1434;"
                        + "database=javatest;"
                        + "user=sa;"
                        + "password=***;"
                        + "useBulkCopyForBatchInsert=true;"
                        + "encrypt=true;"
                        + "trustServerCertificate=true;";

        PreparedStatement ps = null;
        try (Connection connection = DriverManager.getConnection(connectionUrl)) {
            ps = connection.prepareStatement("insert into dbo.JavaTSTError (DateColumn) values (?)");
            for (int i = 0; i < 5; i++) {
                LocalDateTime now = LocalDateTime.of(2021, 12, 1, 1, 10, 10, 412451245);
                System.out.println(now.toString());
                ps.setTimestamp(1, Timestamp.valueOf(now));
//                ps.setString(1, "2023-06-20 22:13:56.173597825"); // this also triggers the error
                ps.addBatch();
            }
            ps.executeBatch();

        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            ps.close();
        }

    }
}
```

## Problem description
I am trying to bulk insert data to a specific table that has datetime2 column. When I turn on _useBulkCopyForBatchInsert_ it returns an error "Received an invalid column length from the bcp client for colid 1". 

## Expected behavior
Insert all 5 rows into the table dbo.JavaTSTError as a bulk operation. 

## Actual behavior
Data will not be inserted and it will return an error:
```
java.sql.BatchUpdateException: Received an invalid column length from the bcp client for colid 1.
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeBatch(SQLServerPreparedStatement.java:2138)
	at org.example.DateTimeProblem.main(DateTimeProblem.java:27)
```

## Any other details that can be helpful
I tried to experiment with this, because inserting data to a table with similar structure worked for me. I found out, that if I add another column to the table dbo.JavaTSTError, for example with 
```sql
alter table dbo.JavaTSTError add AnotherColumn datetime null
```
it magically starts to work. 

I also found a workaround - convert LocalDateTime to string, formatted as `yyyy-MM-dd'T'HH:mm:ss.SSSSSS`

It looks like a similar issue was solved by #1559, but I still encountered it in latest JDBC driver release. 

## JDBC trace logs
I can provide it if needed.

**Comment by Jeffery-Wasty** [comment]
That error can mean you are passing in a value too large for that column. 

DateTime2 takes in nanos between 0 and 7 digits (see https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetime2-transact-sql?view=sql-server-ver16). When I change the number of nanoseconds to 7-digits, it works for me.

I can't say why it works when altering the table, as, while I see the datetime2 column still has 7 nanos, its able to round off from 9 to 7, in the case that the table is altered. 

I'm not sure how easy it is to change the nanos in LocalDateTime (I wasn't able to, it kept converting back to 9 digits). Is it possible to use the string input for your queries instead?

**Comment by Jeffery-Wasty** [comment]
Hi @krasnyd,

We will be closing this issue in a week if there is no further update.
