### ISSUE TITLE
Azure SQL Database limitations cause SQLServerDatabaseMetaData.getUsername to fail

### ISSUE THREAD

**Issue by tmclean-feith** [microsoft/mssql-jdbc#2158]
## Driver version

9.2.0.jre8

## SQL Server version

Microsoft SQL Azure (RTM) - 12.0.2000.8   Jun  1 2023 13:36:49   Copyright (C) 2022 Microsoft Corporation 

## Client Operating System

Red Hat Enterprise Linux 8

## JAVA/JVM version
Provide the JAVA/JVM version (e.g. java version "1.8.0").

openjdk version "1.8.0_362"
OpenJDK Runtime Environment (build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (build 25.362-b09, mixed mode)

## Table schema

N/A

## Problem description

SQLServerDatabaseMetaData::getUsername is using the "system_user" keyword to derive the current username. This is disallowed under impersonated security contexts on Azure SQL Database as per the documentation below. The result of running getUsername in an impersonated security context is an error stating the SUSER_SNAME is disallowed under this SQL Server version.

This issue is present in both the stated version above and the current main branch.

https://learn.microsoft.com/en-us/sql/t-sql/functions/system-user-transact-sql?view=sql-server-ver16

## Expected behavior

SQLServerDatabaseMetaData::getUsername should always return the name of the user in the current security context, including impersonated contexts.

## Actual behavior

Calling the JDBC DatabaseMetaData::getUsername throws the following exception and stacktrace.

## Error message/stack trace

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Built-in function 'SUSER_SNAME' in impersonation context is not supported in this version of SQL Server.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer.nextRow(SQLServerResultSet.java:5448)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.fetchBufferNext(SQLServerResultSet.java:1771)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServerResultSet.java:1029)
	at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getUserName(SQLServerDatabaseMetaData.java:1702)
	at org.springframework.jdbc.core.metadata.GenericCallMetaDataProvider.<init>(GenericCallMetaDataProvider.java:68)
	at org.springframework.jdbc.core.metadata.SqlServerCallMetaDataProvider.<init>(SqlServerCallMetaDataProvider.java:37)
	at org.springframework.jdbc.core.metadata.CallMetaDataProviderFactory$1.processMetaData(CallMetaDataProviderFactory.java:120)
	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:336)
	... 163 common frames omitted

## Any other details that can be helpful

It seems that the CURRENT_USER keyword may be a viable alternative.

https://learn.microsoft.com/en-us/sql/t-sql/functions/current-user-transact-sql?view=sql-server-ver16

**Comment by Jeffery-Wasty** [comment]
Hi @tmclean-feith,

Thank you for pointing this out to us. We'll discuss this, and get back to you on our thoughts and a possible resolution.

**Comment by tmclean-feith** [comment]
```
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;

public class Main {
	
	public static void main( String[] args ) throws Throwable {
		
		String jdbcUrl    = args[0];
		String username   = args[1];
		String password   = args[2];
		String targetUser = args[3];
		
		Connection conn = DriverManager.getConnection( jdbcUrl, username, password );
		
		try {
			System.out.println( "Before impersonate: " + conn.getMetaData().getUserName() );
			try( CallableStatement asOtherUser = conn.prepareCall( "EXECUTE AS USER = '" + targetUser + "'" ) ) {
				asOtherUser.execute();
				System.out.println( "After impersonate: " + conn.getMetaData().getUserName() );
			}
			
			try( CallableStatement revert = conn.prepareCall( "REVERT" ) ) {
				revert.execute();
				System.out.println( "After revert: " + conn.getMetaData().getUserName() );
			}
		}
		finally {
			conn.close();
		}
	}
}
```

**Comment by David-Engel** [comment]
We can't change to `CURRENT_USER` without a breaking change in the driver behavior. `SYSTEM_USER` returns the login of the user at the system/instance level. `CURRENT_USER` returns the name of the database user for the current security context. Two different pieces of information. You can associate a system user with a different database user in each database on the system.

For a visual, here's what they look like in SSMS. Database users are circled in green. System users are circled in orange:
![image](https://github.com/microsoft/mssql-jdbc/assets/26262303/f1cd76bd-b70d-4e9d-8b13-132b63a49571)

**Comment by tmclean-feith** [comment]
Thank you for the explanation @lilgreenbird, that make sense. The change to CURRENT_USER was only a suggestion for a possible solution. However, SQLServerDatabaseMetaData::getUsername is still broken when connected to an Azure SQL database as it relies on SYSTEM_USER, which is disallowed on Azure SQL.

**Comment by lilgreenbird** [comment]
thanks you are correct, we will be updating the docs to list this as a limitation

**Comment by tmclean-feith** [comment]
@lilgreenbird, are you suggesting that the JDBC method DatabaseMetaData::getUsername will not function under Azure SQL Database? If so, this is not acceptable as existing libraries are likely leveraging this internally. For example, we encountered this issue through Spring JDBC.

**Comment by David-Engel** [comment]
Against an Azure SQL DB connection logged in as "ExampleUser":
1. When I query `SELECT SYSTEM_USER`, I get 'ExampleUser'.
2. When I query `SELECT CURRENT_USER`, I get 'dbo', since that's the database user associated with 'ExampleUser'.

After an `EXECUTE AS user = 'TestUser1' command against an Azure SQL DB connection logged in as "ExampleUser": 
3. When I query `SELECT SYSTEM_USER`, I get error 40529.
4. When I query `SELECT CURRENT_USER`, I get 'TestUser1'.

So you are proposing in step 3, that the driver detect error 40529 from the server, run `SELECT CURRENT_USER`, and return that result instead, right?

**Comment by tkyc** [comment]
Just an update. A fix for this will likely be made and included in the next GA release (in January).
