### ISSUE TITLE
TLSv1.3 is not working with SelectMethod=cursor

### ISSUE THREAD

**Issue by 4devwithgit** [microsoft/mssql-jdbc#2170]
## Driver version
mssql-jdbc-12.2.0.jre8.jar

## SQL Server version
SQL 2022

## Client Operating System
both the application and DB are running on Windows 2022.

## JAVA/JVM version
java -version
java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) Client VM (build 25.333-b02, mixed mode)

## Table schema
for all

## Problem description
Its the same problem as , https://github.com/microsoft/mssql-jdbc/issues/2157 but thats closed.
TLS1.3 is not working

## Expected behavior
Successful communication with Database with TLS 1.3

## Actual behavior
Application not working with SQL database with TLS 1.3.

[2023-06-30 02:54:43.802] ERROR [1688118883802] The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 1 (""): Data type 0x00 is unknown.
[2023-06-30 02:54:43.802] ERRORDTL [1688118883802]com.microsoft.sqlserver.jdbc.SQLServerException: The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 1 (""): Data type 0x00 is unknown.

## Error message/stack trace
[2023-06-30 02:54:43.802] ERROR getSIVersion()
[2023-06-30 02:54:43.802] ERROR [1688118883802] The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 1 (""): Data type 0x00 is unknown.
[2023-06-30 02:54:43.802] ERRORDTL [1688118883802]com.microsoft.sqlserver.jdbc.SQLServerException: The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 1 (""): Data type 0x00 is unknown.
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1695)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:620)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:539)
at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7685)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4048)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:272)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:246)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:457)
at com.sterlingcommerce.security.lc.LM.getSIVersion(LM.java:955)
at com.sterlingcommerce.security.lc.LM.loadMap(LM.java:2582)
at com.sterlingcommerce.security.lc.LM.loadOldSet(LM.java:3114)
at com.sterlingcommerce.security.lc.LM.reload(LM.java:3380)
at com.sterlingcommerce.security.lc.LM.refresh(LM.java:3319)
at com.sterlingcommerce.security.lc.LM.(LM.java:3454)
at com.sterlingcommerce.security.lc.LicenseVerify.checkAndInstallLicense(LicenseVerify.java:57)
at com.sterlingcommerce.security.lc.LicenseVerify.checkSfgLicense(LicenseVerify.java:28)
at com.sterlingcommerce.security.lc.LicenseVerify.checkLicenses(LicenseVerify.java:17)
at com.sterlingcommerce.woodstock.ops.server.PassPhrase.startup(PassPhrase.java:325)
at com.sterlingcommerce.woodstock.ops.server.PassPhrase.main(PassPhrase.java:137)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
at java.lang.reflect.Method.invoke(Method.java:508)
at com.sterlingcommerce.woodstock.noapp.NoAppLoader.main(NoAppLoader.java:99)
[2023-06-30 02:54:43.802] ERROR 000000000000 GLOBAL_SCOPE getSIVersion()

## Any other details that can be helpful
TLSv1.2 works fine without any changes, but breaks with tlsv1.3

Here are the connection parameters,
To be precise, we are setting the below propeties, and even after removing the selectmethod, I am still getting the error,

**LOG7 _url= jdbc:sqlserver://xyz.in.syncsort.dev:1433;databaseName=B2BTEST13**
LOG7 testOnReserveQuery=SELECT PRODUCT_LABEL from SI_VERSION where PRODUCT_LABEL = ?
LOG7 minimumsize=1
LOG7 trustStorePassword=password
LOG7 password=password
LOG7 trustServerCertificate=false
LOG7 executeTestOnReserve=true
LOG7 trustStore=C:\B2BI\6200\MSSQLServer2022_TLS1.3_103.35\truststore.jks
LOG7 encrypt=strict
LOG7 sslProtocol=TLSv1.3
LOG7 systemPool=true
LOG7 user=xyz1
LOG7 poolName=mssqlPool
LOG7 testOnReserveInterval=60000
LOG7 prevEffectiveDate=Wed Jul 19 06:46:36 PDT 2023
LOG7 hostNameInCertificate=b2biqawinmk2.in.syncsort.dev

## JDBC trace logs
No

**Comment by 4devwithgit** [comment]
In my standalalone java program, if I add "SelectMethod=cursor" to the JDBC URL, I get the exact same error. However, when its removed from my program it works fine.
But, in my application, even after removing I am getting errors as reported. Not sure if other parameters shared above are causing issues like SelectMethod.
This seem to be issue with TDS 8.0 which is not working the way it used to be TLS 1.2 in previous TDS stream used for TLS 1.2

**Comment by tkyc** [comment]
Could you provide us your standalone repro application?

**Comment by 4devwithgit** [comment]
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;

public class SQLServer {
	public static void main(String[] argv) throws Exception {
		System.setProperty("javax.net.debug", "all");
		
		//String sslProtocol = "TLSv1.2";
		String sslProtocol = "TLSv1.3";
		String trustStore = "C:\\Users\\Dev.Sahu\\OneDrive - Precisely Inc\\1\\_2023\\defects\\QA\\startup_tls1.3_db2\\SQL\\tls13\\truststore.jks";
		String trustStorePassword = "password";
		
		System.out.println("-------- SQL Server. Testing ------");
		System.out.println("***************START***************");
		try {
			Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
		} catch (ClassNotFoundException e) {
			System.out.println("Where is your Oracle JDBC Driver?");
			e.printStackTrace();
			return;
		}
		System.out.println("SQL Driver Registered!");
		//good one
		/*String url = 
				"jdbc:sqlserver://DevWin20161.fyre.ibm.com:1433;databaseName=DB1;"+
						"encrypt=true; trustServerCertificate=false;" + 
				"trustStore=/root/soft/sqlcert/truststore.ks;trustStorePassword=password;" +
				"hostNameInCertificate=DevWin20161;sslProtocol=TLSv1.2";*/
		//good1
		//String url = "jdbc:sqlserver://DevWin20161.fyre.ibm.com:1433;DatabaseName=DB1;encrypt=true;
		//trustServerCertificate=false;trustStore=/root/soft/sqlcert/truststore.ks;trustStorePassword=password;hostNameInCertificate=DevWin20161;sslProtocol=TLSv1.2";
		
		//good2
		//String url = "jdbc:sqlserver://DevWin20161.fyre.ibm.com:1433;databaseName=DB1;trustServerCertificate=true;sslProtocol=TLSv1.2";
	
		//String url = "jdbc:sqlserver://b2biqawinmk2.in.syncsort.dev:1433;databaseName=B2BTEST13";				//default
		//mssqlPool.url=jdbc:sqlserver://b2biqawinmk2.in.syncsort.dev:1433;databaseName=B2BTEST13;SelectMethod=cursor
		String url = "jdbc:sqlserver://XYZ.in.syncsort.dev:1433;databaseName=B2BTEST13;SelectMethod=cursor";
		
		//String url = "jdbc:sqlserver://DevWin20161.fyre.ibm.com:1433;databaseName=DB1;user=user1;password=password\\\\;";
		
		/*String url =   
			    "jdbc:sqlserver://DevWin20161.fyre.ibm.com:1433;" +  
			     "databaseName=DB1;integratedSecurity=true;" +  
			     "encrypt=true; trustServerCertificate=true;" +  
			     "trustStore=/root/soft/sqlcert/truststore.ks;trustStorePassword=password;" +
			     "hostNameInCertificate=DevWin20161";  
		*/
		
		//com.ibm.jsse2.overrideDefaultTLS=true
		//props.setProperty("com.ibm.jsse2.overrideDefaultTLS", "true");
		//props.setProperty("jdk.tls.client.protocols", "TLSv1.2");
		//props.setProperty("javax.net.ssl.keyStore", keyStore);
		//props.setProperty("javax.net.ssl.keyStoreType","JKS");
		//props.setProperty("javax.net.ssl.keyStorePassword","password1");
		
		//props.setProperty("javax.net.ssl.trustStore", "/root/soft/sqlcert/truststore.ks");
		//props.setProperty("javax.net.ssl.trustStore", "/root/soft/dbconn/trust.jks");
		//props.setProperty("javax.net.ssl.trustStoreType","JKS");
		//props.setProperty("javax.net.ssl.trustStorePassword","password");
		//props.setProperty("oracle.net.ssl_version", "1.0");
		//props.setProperty("oracle.net.ssl_version", tlsVersion);
		//props.setProperty("oracle.net.ssl_cipher_suites", "TLS_RSA_WITH_AES_256_CBC_SHA256");
		Properties props = new Properties();
		//props.setProperty("trustStore", "/root/soft/sqlcert/truststore.ks");
		//props.setProperty("trustStorePassword", "password");
		props.setProperty("user", "user");
		props.setProperty("password", "password");
		
		props.setProperty("encrypt", "strict");
		//props.setProperty("encrypt", "true");
		props.setProperty("sslProtocol", sslProtocol);
		//props.setProperty("MultipleActiveResultSets","false");
		//props.setProperty("trustServerCertificate", "true");
		props.setProperty("trustServerCertificate", "false");
		props.setProperty("trustStore", trustStore);
		props.setProperty("trustStorePassword",trustStorePassword);
		props.setProperty("hostNameInCertificate","b2biqawinmk2.in.syncsort.dev");
		
		
		
		Connection conn = null;

		try {
			conn = DriverManager.getConnection(url, props);
			System.out.println(" ");
			System.out.println("!!!!!!!!!!!!!!!! GOT THE CONNECTION !!!!!!!!!!!!!!!!");
			System.out.println(" ");
			System.out.println(" ");
			System.out.println("valid :" + conn.isValid(5));
			System.out.println(" ");
			DatabaseMetaData dbmd = conn.getMetaData();
			System.out.println("DB driver version:"+dbmd.getDriverVersion());
			System.out.println(" ");
			System.out.println("DB version:"+dbmd.getDatabaseProductVersion()); 
			System.out.println(" ");

			Statement stmt = conn.createStatement();
			//stmt.executeUpdate("drop table survey");
			System.out.println(" ");
			System.out.println("Creating a test Table, SURVEY");
			System.out.println(" ");
		    stmt.executeUpdate("create table survey (id int, name CHAR(50) );");
		    System.out.println(" ");
		    System.out.println("Inserting values to table, SURVEY");
		    System.out.println(" ");
		    stmt.executeUpdate("INSERT INTO survey(id, name)VALUES(111, '123456789')");
		    
		    conn.commit();
		    System.out.println(" ");
		    System.out.println("Querying values from table");
		    System.out.println(" ");
		    ResultSet rs = stmt.executeQuery("SELECT * FROM survey");
		    outputResultSet(rs);

		    System.out.println(" ");
		    System.out.println("Dropping the table now");
		    System.out.println(" ");
		    stmt.executeUpdate("drop table survey");
		    
		    rs.close();
		    stmt.close();
		    conn.close();
		    System.out.println(" ");
		    System.out.println("Thanks !!!!!!!!!!!!!!!!");
		    System.out.println(" ");
		} 	catch (SQLException e) {
			System.out.println("Connection Failed! Check output console");
			e.printStackTrace();
			return;
		}
		if (conn != null) {
			System.out.println("You made it, take control your database now!");
		} else {
			System.out.println("Failed to make connection!");
		}
	}
	
	private static void outputResultSet(ResultSet rs) throws Exception {
	    ResultSetMetaData rsMetaData = rs.getMetaData();
	    int numberOfColumns = rsMetaData.getColumnCount();
	    for (int i = 1; i < numberOfColumns + 1; i++) {
	      String columnName = rsMetaData.getColumnName(i);
	      System.out.print(columnName + "   ");

	    }
	    System.out.println();
	    System.out.println("----------------------");

	    while (rs.next()) {
	      for (int i = 1; i < numberOfColumns + 1; i++) {
	        System.out.print(rs.getString(i) + "   ");
	      }
	      System.out.println();
	    }

	  }
}

**Comment by 4devwithgit** [comment]
Here is the output, without ssl logs. We can see the same error, except that SQL State and Error code is not present. Please run the same program without "SelectMethod=cursor" in the url. In this case, we dont see the error.

Secondly, in the application, inspite of having it removed, I am still seeing the same error. So besides SelectMethod, what can be the other issue with TDS 8.0 stream? I have already shared the exact connection parameters being passed during the application connection to the driver.

**Appreciate the help and quick response, as TLSv1.3 support for the SQL DB is importand and this is blocking our release.**

-------- SQL Server. Testing ------
***************START***************
SQL Driver Registered!
 
!!!!!!!!!!!!!!!! GOT THE CONNECTION !!!!!!!!!!!!!!!!
 
 
valid :true
 
DB driver version:12.2.0.0
 
DB version:16.00.1000
 
 
Creating a test Table, SURVEY
 
 
Inserting values to table, SURVEY
 
 
Querying values from table
 
Connection Failed! Check output console
com.microsoft.sqlserver.jdbc.SQLServerException: The incoming tabular data stream (TDS) protocol stream is incorrect. The stream ended unexpectedly.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1695)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteCursored(SQLServerStatement.java:2093)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:894)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:814)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7685)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4048)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:272)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:246)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeQuery(SQLServerStatement.java:736)
	at SQLServer.main(SQLServer.java:120)

**Comment by 4devwithgit** [comment]
Also, I see the difference between the output of standalone program Vs the application is coming into picture with the Statement and PreparedStatement..
With use of PreparedStatement too I am getting the same errors as compared to Statement, and ofcourse in the enterprise application we are bound to use PreparedStatement.

**Comment by 4devwithgit** [comment]
After doing more testing here is the conclusion
1) Application uses PreparedStatement, but it always gives the error
2) Java program (standalone) works with Statement, but that also doesnt work with PreparedStatement.
3) Java program (standalone) works with Statement only when SelectMethod=cursor is not present.
4) Application works fine with TLSv1.2 with encrypt true, but when we set, encrypt=strict (on DB and the program side both) and use TLSv1.3, it doesnt work

So, definitely this is a database issue which is not working in TDS 8.0 for TLSv1.3

**Comment by tkyc** [comment]
@4devwithgit Thanks for your efforts for looking into this. I'll do some investigating on my side and let you know. I'll keep you posted.

**Comment by 4devwithgit** [comment]
Here is the output,

**Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64)   Oct  8 2022 05:58:25   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2022 Datacenter 10.0 <X64> (Build 20348: ) (Hypervisor)**

**Comment by 4devwithgit** [comment]
Hi,
Any update on this issue? How can it be resolved? Our release is gating on this to offer support for TLS 1.3 with SQL DB, but looks like we are not able to accommodate due to this issue.
Thanks

**Comment by tkyc** [comment]
When I was looking into your issue, I've discovered an unrelated security problem with TDS 8 that I was debugging. So I don't recommend using TDS 8 with any driver version <= 12.2.0. We'll need to apply a fix/patch for this (I'll update the thread later on this).

But beyond that, regarding your problem. Using your standalone application exactly as is (other than changing the server properties to my own) I wasn't able to reproduce your problem. `selectMethod=cursor` works for me and I didn't error out. But, the SQL Server version I tested your issue on is older than your version. I'll need to time to setup a new environment with the appropriate versions to retest.

Could you also try retesting on a more recent version of SQL 2022? Let me know that version as well.

**Comment by tkyc** [comment]
Also, could you try using the `serverCertificate` property? I recall trustStore for TDS 8 was obsolete (not that it isn't supported, but it's preferred to use `serverCertificate`;

**Comment by 4devwithgit** [comment]
Here are the further findings,

1) I tried with the serverCertificate, by doing below settings as per the link, https://learn.microsoft.com/en-us/sql/connect/jdbc/understanding-ssl-support?view=sql-server-ver16, which says 
encrypt = strict
hostNameInCertificate = value
trustStore = blank
trustStorePassword = blank
serverCertificate = value
So, I set it as,
                 props.setProperty("trustStore", "");
		 props.setProperty("trustStorePassword", "");
		 props.setProperty("serverCertificate", trustStore);
and added a pem file containing the key,
String trustStore = "C:\\Users\\Dev.Sahu\\OneDrive - Precisely Inc\\1\\_2023\\defects\\QA\\startup_tls1.3_db2\\SQL\\tls13\\**output.pem**";

But, it always resulted in the failure, during establishing the connection, while the connection parameters are,

PROPS ------------------------------ 
Parameter trustStorePassword=
Parameter password=password
Parameter trustServerCertificate=false
Parameter encrypt=strict
Parameter trustStore=
Parameter sslProtocol=TLSv1.3
Parameter user=b2biuser
Parameter serverCertificate=C:\Users\Dev.Sahu\OneDrive - Precisely Inc\1\_2023\defects\QA\startup_tls1.3_db2\SQL\tls13\output.pem
Parameter hostNameInCertificate=b2biqawinmk2.in.syncsort.dev
PROPS ------------------------------ 

Caused by: java.security.cert.CertificateException: Error validating Server Certificate: C:\Users\Dev.Sahu\OneDrive - Precisely Inc\1\_2023\defects\QA\startup_tls1.3_db2\SQL\tls13\output.pem: Error validating Server Certificate: C:\Users\Dev.Sahu\OneDrive - Precisely Inc\1\_2023\defects\QA\startup_tls1.3_db2\SQL\tls13\output.pem: Unable to initialize, java.io.IOException: insufficient data..
	at com.microsoft.sqlserver.jdbc.ServerCertificateX509TrustManager.checkServerTrusted(SQLServerTrustManager.java:157)
	at com.ibm.jsse2.bp.checkServerTrusted(bp.java:3)
	at com.ibm.jsse2.z$e.a(z$e.java:86)
	... 20 more

So, when you are using the parameter "serverCertificate" and its working, can u give the dump of parameters for me to set it correctly? Looks like its complaining of the insufficient data. Need help on this.

2) We will test with the latest build of SQL 2022 and let you know.

3) In my next comment, I am attaching version of the file which you may test it again with PreparedStatement instead of Statement and may hit the issue. Please test it like below and see the results
- a) test it as is and see the results (it has PreparedStatement and SelectMethod which never works)
- b) test it by commenting lines, 148,152,153 and uncomment line 155 (Change from PreparedStatement to Statement, but retaining SelectMethod parameter"
- c) On top of verison b) Comment line 50, uncomment line 47 . This is without "SelectMethod=cursor". This is the only setting which works, but it doesnt help, as we need to use PreparedStatement and "SelectMethod=cursor"

**Comment by 4devwithgit** [comment]
`
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;

import com.microsoft.sqlserver.jdbc.SQLServerException;

public class SQLServer {
	public static void main(String[] argv) throws Exception {
		System.setProperty("javax.net.debug", "all");
		
		//String sslProtocol = "TLSv1.2";
		String sslProtocol = "TLSv1.3";
		String trustStore = "C:\\Users\\Dev.Sahu\\OneDrive - Precisely Inc\\1\\_2023\\defects\\QA\\startup_tls1.3_db2\\SQL\\tls13\\truststore.jks";
		//String trustStore = "C:\\Users\\Dev.Sahu\\OneDrive - Precisely Inc\\1\\_2023\\defects\\QA\\startup_tls1.3_db2\\SQL\\tls13\\output.pem";
		String trustStorePassword = "password";
		
		System.out.println("-------- SQL Server. Testing ------");
		System.out.println("***************START***************");
		try {
			Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
		} catch (ClassNotFoundException e) {
			System.out.println("Where is your Oracle JDBC Driver?");
			e.printStackTrace();
			return;
		}
		System.out.println("SQL Driver Registered!");
		//good one
		/*String url = 
				"jdbc:sqlserver://DevWin20161.fyre.ibm.com:1433;databaseName=DB1;"+
						"encrypt=true; trustServerCertificate=false;" + 
				"trustStore=/root/soft/sqlcert/truststore.ks;trustStorePassword=password;" +
				"hostNameInCertificate=DevWin20161;sslProtocol=TLSv1.2";*/
		//good1
		//String url = "jdbc:sqlserver://DevWin20161.fyre.ibm.com:1433;DatabaseName=DB1;encrypt=true;
		//trustServerCertificate=false;trustStore=/root/soft/sqlcert/truststore.ks;trustStorePassword=password;hostNameInCertificate=DevWin20161;sslProtocol=TLSv1.2";
		
		//good2
		//String url = "jdbc:sqlserver://DevWin20161.fyre.ibm.com:1433;databaseName=DB1;trustServerCertificate=true;sslProtocol=TLSv1.2";
	
		//String url = "jdbc:sqlserver://b2biqawinmk2.in.syncsort.dev:1433;databaseName=B2BTEST13";				//default
		//mssqlPool.url=jdbc:sqlserver://b2biqawinmk2.in.syncsort.dev:1433;databaseName=B2BTEST13;SelectMethod=cursor
		//String url = "jdbc:sqlserver://b2biqawinmk2.in.syncsort.dev:1433;databaseName=B2BTEST13;MultipleActiveResultSets=FALSE";
		String url = "jdbc:sqlserver://b2biqawinmk2.in.syncsort.dev:1433;databaseName=B2BTEST13;SelectMethod=cursor";
		
		//String url = "jdbc:sqlserver://DevWin20161.fyre.ibm.com:1433;databaseName=DB1;user=user1;password=password\\\\;";
		
		/*String url =   
			    "jdbc:sqlserver://DevWin20161.fyre.ibm.com:1433;" +  
			     "databaseName=DB1;integratedSecurity=true;" +  
			     "encrypt=true; trustServerCertificate=true;" +  
			     "trustStore=/root/soft/sqlcert/truststore.ks;trustStorePassword=password;" +
			     "hostNameInCertificate=DevWin20161";  
		*/
		
		//com.ibm.jsse2.overrideDefaultTLS=true
		//props.setProperty("com.ibm.jsse2.overrideDefaultTLS", "true");
		//props.setProperty("jdk.tls.client.protocols", "TLSv1.2");
		//props.setProperty("javax.net.ssl.keyStore", keyStore);
		//props.setProperty("javax.net.ssl.keyStoreType","JKS");
		//props.setProperty("javax.net.ssl.keyStorePassword","password1");
		
		//props.setProperty("javax.net.ssl.trustStore", "/root/soft/sqlcert/truststore.ks");
		//props.setProperty("javax.net.ssl.trustStore", "/root/soft/dbconn/trust.jks");
		//props.setProperty("javax.net.ssl.trustStoreType","JKS");
		//props.setProperty("javax.net.ssl.trustStorePassword","password");
		//props.setProperty("oracle.net.ssl_version", "1.0");
		//props.setProperty("oracle.net.ssl_version", tlsVersion);
		//props.setProperty("oracle.net.ssl_cipher_suites", "TLS_RSA_WITH_AES_256_CBC_SHA256");
		Properties props = new Properties();
		//props.setProperty("trustStore", "/root/soft/sqlcert/truststore.ks");
		//props.setProperty("trustStorePassword", "password");
		props.setProperty("user", "b2biuser");
		props.setProperty("password", "password");
		
		props.setProperty("encrypt", "strict");
		//props.setProperty("encrypt", "true");
		props.setProperty("sslProtocol", sslProtocol);
		//props.setProperty("MultipleActiveResultSets","false");
		//props.setProperty("trustServerCertificate", "true");
		props.setProperty("trustServerCertificate", "false");
		//props.setProperty("trustStore", "");
		//props.setProperty("trustStorePassword", "");
		//props.setProperty("serverCertificate", trustStore);
		props.setProperty("trustStore", trustStore);
		props.setProperty("trustStorePassword", trustStorePassword);
		
		props.setProperty("hostNameInCertificate","b2biqawinmk2.in.syncsort.dev");
		
		System.out.println("Parameter url= " + url);
		System.out.println("PROPS ------------------------------ ");	
		props.forEach((key, value) -> {
			System.out.println("Parameter " +  key.toString() + "=" + value.toString());
	    });
		System.out.println("PROPS ------------------------------ ");
		Connection conn = null;

		try {
			conn = DriverManager.getConnection(url, props);
			System.out.println(" ");
			System.out.println("!!!!!!!!!!!!!!!! GOT THE CONNECTION !!!!!!!!!!!!!!!!");
			System.out.println(" ");
			System.out.println(" ");
			System.out.println("Valid connection : " + conn.isValid(5));
			System.out.println(" ");
			DatabaseMetaData dbmd = conn.getMetaData();
			System.out.println("DB driver version : " + dbmd.getDriverVersion());
			System.out.println(" ");
			System.out.println("DB version : " + dbmd.getDatabaseProductVersion()); 
			System.out.println(" ");

			Statement stmt = conn.createStatement();
			//PreparedStatement stmt = conn.prepareStatement("drop table survey");
			try {
			System.out.println("Drop existing test table if already exists");
			//stmt.executeUpdate("drop table survey");
			stmt.execute("drop table survey");
			} catch (SQLServerException sqe) {
				System.out.println("ERROR!!! Cannot drop the table 'survey', because it does not exist or you do not have permission.");
				System.out.println("Ignore and proceed...");
				//sqe.printStackTrace();
			}
			
			Statement stmt1 = conn.createStatement();
			System.out.println(" ");
			System.out.println("Creating a test Table, SURVEY");
			System.out.println(" ");
		    //stmt.executeUpdate("create table survey (id int, name CHAR(50) );");
			stmt1.execute("create table survey (id int, name CHAR(50) );");
			//stmt.executeUpdate();
			
			//PreparedStatement insertstmt = conn.prepareStatement("INSERT INTO survey(id, name)VALUES(111, '123456789')");
			Statement insertstmt = conn.createStatement();	    
			System.out.println(" ");
		    System.out.println("Inserting values to table, SURVEY");
		    System.out.println(" ");
		    insertstmt.executeUpdate("INSERT INTO survey(id, name)VALUES(111, '123456789')");
		    //insertstmt.execute();
		    
		    conn.commit();
		    
		    PreparedStatement queryStmt = conn.prepareStatement("SELECT * FROM survey");
		    System.out.println(" ");
		    System.out.println("Querying values from table SURVEY");
		    System.out.println(" ");
		    queryStmt.execute();
		    ResultSet rs = queryStmt.getResultSet();
		    
		    //ResultSet rs = stmt.executeQuery("SELECT * FROM survey");
		    int count = stmt.getUpdateCount();
		    System.out.println("count=" + count);
		    outputResultSet(rs);

		    System.out.println(" ");
		    System.out.println("Dropping the table now");
		    System.out.println(" ");
		    stmt.executeUpdate("drop table survey");
		    
		    rs.close();
		    stmt.close();
		    conn.close();
		    System.out.println(" ");
		    System.out.println("Thanks !!!!!!!!!!!!!!!!");
		    System.out.println(" ");
		} 	catch (SQLException e) {
			System.out.println("Connection Failed! Check output console");
			e.printStackTrace();
			return;
		}
		if (conn != null) {
			System.out.println("You made it, take control your database now!");
		} else {
			System.out.println("Failed to make connection!");
		}
	}
	
	private static void outputResultSet(ResultSet rs) throws Exception {
	    ResultSetMetaData rsMetaData = rs.getMetaData();
	    int numberOfColumns = rsMetaData.getColumnCount();
	    for (int i = 1; i < numberOfColumns + 1; i++) {
	      String columnName = rsMetaData.getColumnName(i);
	      System.out.print(columnName + "   ");

	    }
	    System.out.println();
	    System.out.println("----------------------");

	    while (rs.next()) {
	      for (int i = 1; i < numberOfColumns + 1; i++) {
	        System.out.print(rs.getString(i) + "   ");
	      }
	      System.out.println();
	    }

	  }
}
`

**Comment by 4devwithgit** [comment]
How to share the code file directly? Though I shared my file with copy/paste, the line numbers may change due to formattings, so instead of that I want to zip the file and share it, but dont see any option.

**Comment by tkyc** [comment]
From the error, it looks like your pem file (certificate) is invalid. How are you getting your pem file? When I create the pem file, I run the following openssl command:

```
openssl s_client -showcerts -connect <your-server-IP>:<your-port>
```

The command generates an output. Copy from the `-----BEGIN CERTIFICATE-----` to `-----END CERTIFICATE-----` into a pem file. This is what my connection string looks like:

```
jdbc:sqlserver://myserver;user=sa;password=pwd;encrypt=strict;serverCertificate=C:\mydir\tds8.pem;trustServerCertificate=false;hostNameInCertificate=myserver.cloudapp.azure.com;sslProtocol=TLSv1.3;
```

**Comment by tkyc** [comment]
I've retested with the exact SQL Server version you have with your repro app (with `serverCertificate`) and it's failing for me now. I'll need to debug further.

**Comment by tkyc** [comment]
Looks like it's a server regression. You'll need to update to the latest CU, after updating your repro app is working. Here is the link to the CU update.

https://learn.microsoft.com/en-us/troubleshoot/sql/releases/sqlserver-2022/cumulativeupdate6

**Comment by 4devwithgit** [comment]
Thanks. Great its working now with the build CU6 of SQL 2022. I think we are good now.
I regenerated pem file using your steps and now its with serverCertificate, without the truststore and trustStorePassword. But, ideally would want to continue to use the truststore, because moving away from it will require too many changes in different cases like install, upgrade, runtime, APIs, docker etc. 
The issue that you have discovered with truststore, will that be addressed in future build of SQL 2022, or will it be handled in driver? Thanks

**Comment by tkyc** [comment]
The issue with the trustStore will be addressed in a future release of the mssql-jdbc driver and likely a hotfix. I'll be closing the issue for now since the issue has been resolved.

**Comment by 4devwithgit** [comment]
Sure, thanks a lot for the help @tkyc

**Comment by lilgreenbird** [comment]
@4devwithgit 

fyi we have just released 12.4.0 we would recommend that you upgrade to this release as this contains all the latest fixes and also support having your server certificate in the truststore as you had originally intended to do.

**Comment by 4devwithgit** [comment]
Please share the link for download of 12.4.0.

I only see 12.2.0 is the GA version, https://learn.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-ver16

**Comment by Jeffery-Wasty** [comment]
Hi @4devwithgit,

Our documents are still being updated, they should be up-to-date by the end of the day. The latest driver can also be found on Maven and [GitHub](https://github.com/microsoft/mssql-jdbc/releases/tag/v12.4.0).

**Comment by 4devwithgit** [comment]
Thanks @Jeffery-Wasty !
