### ISSUE TITLE
Does your version of [mssql-jdbc-9.4.1.jre11.jar] support TLS1.2 and TLS1.3?

### ISSUE THREAD

**Issue by pilyong17** [microsoft/mssql-jdbc#2173]
I was wondering if the version [mssql-jdbc-9.4.1.jre11.jar] supports TLS 1.2 and TLS 1.3.

**Comment by tkyc** [comment]
9.4.1 supports TLS 1.2. It doesn't support TLS 1.3. From version 11.2.0 is when the driver supports TLS 1.3 via our TDS 8.0 feature. More info can be found here: https://learn.microsoft.com/en-us/sql/relational-databases/security/networking/tds-8?view=sql-server-ver16#strict-connection-encryption

**Comment by pilyong17** [comment]
Thanks for the detailed explanation. Have a great day.
