### ISSUE TITLE
Doesn't the mssql-jdbc-12.2.0 version support TLS v1, v1.1?

### ISSUE THREAD

**Issue by pilyong17** [microsoft/mssql-jdbc#2175]
I changed the mssql-jdbc version from 9.4.1 to 12.2.0.
However, when I tried to connect to MSSQL from the client, the following error message occurred.

*** error message**
"tlsv1 was negotiated. please update server and client to use tlsv1.2 at minimum"
			
Upon checking, the mssql version on the customer's server did not support TLS 1.2.
I recommended updating it, but they said they couldn't do it at the moment for other reasons.

I wonder if mssql jdbc version 12.2.0 does not support TLS v1, v1.1.

**Comment by tkyc** [comment]
The driver supports TLSv1 and TLSv1.1. Where is the server located? If it's on Azure, I recall Azure only allowing TLSv1.2. Also, it's possible that the JDK might have TLSv1.1 disabled. So, if it's failing on an older TLS version, it's likely a server/env setup issue.

In our docs: https://learn.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver16, if you look up `sslProtocol` it lists out the supported TLS versions and TLSv1.1 is on there.

**Comment by pilyong17** [comment]
The server is installed on secure equipment, not a CSP.
Maybe adding the following options to the driver url could have an impact?

**[...;encrypt=true;trustServerCertificate=true]**

**Comment by pilyong17** [comment]
.

**Comment by tkyc** [comment]
You'll need `trustServerCertificate=false`. If it's `true` then the certificate isn't validated and is unsecure. For your use, your connection string should be like `encrypt=true;trustServerCertificate=false;sslProtocol=TLSv1.1`. What's your SQL Server version (the output of `SELECT @@VERSION`)? If the SQL Server is out of date, that could have an impact.

**Comment by pilyong17** [comment]
I'm not sure if changing `trustServerCertificate=false` will work.
If we set it to `true`, wouldn't that be one less step, since it would just pass without verification?

*** SQL Server version**
Not exactly, but... SQL Server 2008 does not support `TLSv1.2 or higher.`
But if the mssql jdbc 12.2 version supports TLSv1 TLSv1.1, then the SQL Server version shouldn't matter, right?
As you said, it could be a JDK or some other environment issue...

**Comment by pilyong17** [comment]
I checked, and it seems to be because `tomcat` has `sslEnabledProtocols="TLSv1.2+TLSv1.3"` in its `server.xml`.
Thank you for your response. :)
