### ISSUE TITLE
[QUESTION] 12.3.0 and 12.3.1 and the label "Preview release"

### ISSUE THREAD

**Issue by jubax** [microsoft/mssql-jdbc#2178]
## Question
I am waiting for some post 12.2 release because I stumbled across a critical bug about a race condition which should be fixed in 12.3. I just noticed that 12.3.0 and 12.3.1 are labeled as "Preview release". My questions:

- What does "preview release" mean? Does it mean you would not recommend using it in production?
- When does the next "stable release" ship?

Thanks

## Relevant Issues and Pull Requests
The fix I'm waiting for is https://github.com/microsoft/mssql-jdbc/issues/2084

**Comment by tkyc** [comment]
Preview releases are not as vigorously tested as a stable release. So yes, personally I wouldn't recommend it in production. Usually, we do these previews to let the community try out new features/fixes sooner (and if any problems are reported, we can correct them before the stable release). Also, for preview releases, we do not support doing hotfixes for these versions.

The next stable release is next week on July 31st (if all goes well).

**Comment by mmimica** [comment]
On a related note: 12.4.0 got "-preview" suffix on [maven central](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc) for some reason.

**Comment by Jeffery-Wasty** [comment]
We've re-released 12.4.0, this time without the `-preview` suffix. Please use that version when it becomes available.

**Comment by lilgreenbird** [comment]
hi @mmimica 

Apologies for the confusion. The stable release is already on maven it's just not indexed yet so it's not showing in the search. You can see that here:

https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/

**Comment by jubax** [comment]
Thank you!
