### ISSUE TITLE
MS Azure SQL Db connection failing intermittently while generating access token from AAD

### ISSUE THREAD

**Issue by manatoshadhikari** [microsoft/mssql-jdbc#2179]
Quarkus application is not able to connect  to MS SQL Db when authentication is set to 
authentication=ActiveDirectoryServicePrincipal.
This is an intermittent issue, like if we deploy the 3 instances of Pod some may start running and some may fail.
On checking the logs we find that it gets timed out while generating tokens from AAD. 

com.microsoft.sqlserver.jdbc.SQLServerException: Failed to authenticate the user 76022cdb-ccb7-4e4c-a0e7-3b295dcfa337 in Active Directory (Authentication=ActiveDirectoryServicePrincipal). java.net.SocketTimeoutException: Connect timed out

But when we check manually if the AAD URLs are reachable from pod, it looks completely ok.

**Comment by tkyc** [comment]
Are you on 12.3.1 version of the driver? What does your connection string look like?

**Comment by manatoshadhikari** [comment]
driver version: 11.2.0.jre11
connection string 
jdbc:sqlserver://<**>.database.windows.net:1433;database=<****>;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;authentication=ActiveDirectoryServicePrincipal;

**Comment by tkyc** [comment]
11.2.0 version of the driver doesn't support `ActiveDirectoryServicePrincipal`. You'll need a 12.3.1+ version of the driver.

**Comment by manatoshadhikari** [comment]
Did upgrade the driver version to 12.3.1.jre11-preview
Started 3 pods, 1 is running and another 2 failed with error 

 Execution of class com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier failed.: 
com.microsoft.aad.msal4j.MsalClientException: java.net.SocketTimeoutException: Connect timed out

We have also checked connections from the nodes in which the pods are failing, connections to AAD is ok without any major delays

**Comment by tkyc** [comment]
That's a pretty generic error. One other thing I noticed, is that there's a mismatch for your msal4j version. 12.3.1 uses msal4j 1.13.8 (not 1.13.9). Let me know if you see the issue, after switching the msal4j version.

**Comment by tkyc** [comment]
Also, remove the `hostNameInCertificate=.database.windows.net;` in your connection string. It's best to let the driver determine that.

**Comment by tkyc** [comment]
Any updates on this? Otherwise, I'll be closing.
