### ISSUE TITLE
[QUESTION] - How to handle secondary DB instance removal from AG read list

### ISSUE THREAD

**Issue by Logic-32** [microsoft/mssql-jdbc#2205]
## Question

We’re using Availability Groups (AG) in AlwaysOn mode to take advantage of the extra compute/scalability/recovery options they offer.  Currently, we have a situation where, when one instance is removed from the Read List of the AG, our Java apps will cache/maintain connections to the instance that was removed and continue to read from it using `applicationIntent=ReadOnly`.  We know this is in part due to our DataSource not evicting/expiring the connection when the Read List changes and the fact that removal from the list doesn't terminate the instance itself so connections do remain "healthy."

What we’re wondering is, is there an easier way to detect if an instance was removed from the Read List and auto-expire any connections to the removed instance?  If not, do you happen to know of any common DataSource options or other solutions to this problem?

FWIW,
- We have considered setting a short TTL on connections so the DataSource aggressively evicts them.  We’re not very comfortable with the impact that has historically had on our database and hope there are better solutions.
- We do have `multiSubnetFailover=true` set as well.  But, that's more about establishing a connection and less about maintaining it.
- The core of this problem has to do with the synchronization of data to certain secondaries getting behind.  We want to remove them from the AG while they catch up but existing connections start to get excessively stale data in that case.

## Relevant Issues and Pull Requests

I skimmed through existing/outstanding issues and didn't notice anything particularly relevant.

**Comment by Logic-32** [comment]
> I'm not sure how the Read List is configured or maintained but I suppose...

The Read List is maintained in SQL Server itself.  Part of the AG Listener and how AG's function in general.  Meaning, "detecting" a change could be difficult.  So, I'm not surprised the mssql-jdbc driver doesn't have a means of doing so.

I was hopeful this was known issue and there were some established best practices around it.  I can try checking with our DataSource implementation to see if they have any tricks and, if not, probably go a route similar to WatchService.  Thanks!

**Comment by lilgreenbird** [comment]
Detecting a change in a file somewhere isn't really the responsibility of the driver, this is something at the application level. I do agree with you that this functionality should probably be included somewhere in AG, but we are only supporting the JDBC driver here and unfortunately I'm not too familiar with AG to comment on how or whether that can be done.

**Comment by Logic-32** [comment]
Unfortunately my understanding of how AGs work is a bit limited myself.  We're pretty new to them.  Part of my hope here stemmed from the idea that MSSQL was relatively smart and might broadcast an event of some kind stating that a read-only instance was no longer valid and that any information on it was at a lower level we just haven't been looking at yet.  But, alas...

With that said, if you're curious to read up on them, the Read List I'm referring to is actually a "read-only routing list": https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/configure-read-only-routing-for-an-availability-group-sql-server?view=sql-server-ver16#configure-a-read-only-routing-list
