### ISSUE TITLE
Windows SQL Server driver link in readme broken

### ISSUE THREAD

**Issue by paix120** [microsoft/mssql-jdbc#2210]
This link in the README file goes to a non-existent page:

https://www.microsoft.com/en-us/sql-server/developer-get-started/java/windows

**Comment by Jeffery-Wasty** [comment]
Hi @paix120,

You're correct, all the links in that section are dead. We'll look into correcting this.

**Comment by paix120** [comment]
Thanks!

**Comment by sillihkram** [comment]
Just checking-in. None of the links have been fixed. Anyone have a reasonable estimate on a new URL/fixed link?

**Comment by Jeffery-Wasty** [comment]
It looks like they have the replacement up, available here: https://www.microsoft.com/en-us/sql-server/developer-tools. We'll update the links in the readme as soon as we are able to.
