### ISSUE TITLE
[Question] - Unanticipated Index Creation in MSSQL and its Impact on Column Alteration - INDEX_VV_<3to4DigitNumber>_<3to4DigitNumber>[QUESTION]

### ISSUE THREAD

**Issue by gitqueries** [microsoft/mssql-jdbc#2211]
## Question
SQL Version - 12.00.6118(SQL Server 2014)

In MSSQL, indexes are created in a few tables and certain columns apart from the ones defined in the schema with the index name format **_'INDEX_VV_<3to4DigitNumber>_<3to4DigitNumber>' (e.g., INDEX_VV_40627_40626)_**.

Due to this, when attempting to ALTER the column, we face an issue as there is an unexpected index that is dependent on the column.

We have checked and confirmed whether there were any index rebuilding activities, SQL tuning performed, SQL jobs configured, or any custom modifications made at the SQL level in relation to indexes.

Is there any scenario in which an index with such a format will be created?

**Comment by lilgreenbird** [comment]
hi @gitqueries 

This repo is for the Microsoft JDBC Driver for SQL Server we support issues related to the driver only. You can obtain support on the server via the Azure management portal or submit a problem report to the Connect site. Here is a [link ](https://learn.microsoft.com/en-us/troubleshoot/sql/general/support-policy-sql-server#obtain-support-from-microsoft)to the doc that describes how to get support from Microsoft on SQL Server.

**Comment by rootcause000** [comment]
Hi @lilgreenbird , Sure. Thanks for the prompt response.
