### ISSUE TITLE
Forced encryption even if turned off on both sides

### ISSUE THREAD

**Issue by konsultaner** [microsoft/mssql-jdbc#2214]
Shouldn't that:

https://github.com/microsoft/mssql-jdbc/blob/145c10e90148087e48c6c18f0f3449bcbb3d1708/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L3551-L3555

be 

```java
if (!isTDS8 && TDS.ENCRYPT_OFF != negotiatedEncryptionLevel && TDS.ENCRYPT_NOT_SUP != negotiatedEncryptionLevel) { 
    tdsChannel.enableSSL(
        serverInfo.getParsedServerName(),
        serverInfo.getPortNumber(), 
        clientCertificate, 
        clientKey,
        clientKeyPassword,
        false
    );
    clientKeyPassword = "";
}
```

if I use the driver with my mssql 14 server and encryption is turned off on both sides, it still tryes to connect via ssl.

**Comment by David-Engel** [comment]
Even when encryption is "OFF" on both sides, encryption is still used to encrypt the login information. After login, the connection returns to unencrypted.

**Comment by konsultaner** [comment]
Ok, I do understand, but this should be configurable as well. IMO the credentials are not necessarily more valuable than the transferred Information. 🤔 

Do the MSSQL Server demand such a behaviour or would i.e. MSSQL 2014 also allow to receive the login data unencrypted as well? 

The Problem I have is that java 17 does not want to talk to my MSSQL 14 due to a RSA 1024bit encryption issue. Java 17 wants at least 2048bit and I'm only able to change thigs on the client side. Turning encryption off would be a good solution because I'm in a closed network with no internet access.

**Comment by David-Engel** [comment]
SQL Server would only accept an unencrypted login if the client specifies that it doesn't support encryption. This is used for backwards compatibility with very old clients. It's not something we would put it any modern client.

I don't know which setting it would be off hand, but you should be able to modify the Java 17 config to allow RSA 1024 bit encryption: https://www.java.com/en/configure_crypto.html

**Comment by konsultaner** [comment]
@David-Engel Thanks for your reply. So there is no way of getting this as a configurable option? I would write a PR if possible? If not I consider selfhosting a modified version of your code. Would it be enough to just change the lines I marked or would it be more of an effort to make it possible?

**Comment by David-Engel** [comment]
> So there is no way of getting this as a configurable option? I would write a PR if possible? If not I consider selfhosting a modified version of your code. Would it be enough to just change the lines I marked or would it be more of an effort to make it possible?

There's a little more to it in the negotiation prior. But I would not support adding it as an option.

> > I don't know which setting it would be off hand, but you should be able to modify the Java 17 config to allow RSA 1024 bit encryption: https://www.java.com/en/configure_crypto.html
> 
> I know that, but I can't do this due to ensurance reasons :(

If you have those kinds of requirements, I would think downgrading it at any point, whether in the Java config, or via driver options, would go against the same reasons. It sounds like your only option, within your requirements, is to get the server config fixed.

**Comment by konsultaner** [comment]
Thank you for the clarification 👌😇

**Comment by ecki** [comment]
Btw, jTDS does connect without (just saying :)

**Comment by David-Engel** [comment]
> Btw, jTDS does connect without (just saying :)

And jTDS sends your credentials in plain text. Most people care about that kind of thing. :)

**Comment by konsultaner** [comment]
> > Btw, jTDS does connect without (just saying :)
> 
> And jTDS sends your credentials in plain text. Most people care about that kind of thing. :)

Not in a unittest environment or in a dmz.
