### ISSUE TITLE
[FEATURE REQUEST] Document sendStringParametersAsUnicode impact

### ISSUE THREAD

**Issue by JBodkin-Amphora** [microsoft/mssql-jdbc#2241]
I've been working on an implementation of keyset pagination for an rest API that is using SQL Server as the datastore. When testing the endpoint, I found that the order of rows being returned from the database was inconsistent. The first query would be as follows:

```
SELECT TOP(10) *
FROM table
ORDER BY id
```

The subsequent query would be as follows:

```
SELECT TOP(10) *
FROM table
WHERE id> :highest_id
ORDER BY id
```

The driver implicitly converts `:highest_id` to unicode so the parameter is: `N':highest_id'`.

Upon further investigation, I found this was happening because char/varchar parameters are being automatically converted to unicode but SQL Server does not convert them back. Disabling sendStringParametersAsUnicode fixes the issue.

> For example, if you are using the SQL collation SQL_Latin1_General_CP1_CI_AS, the non-Unicode string 'a-c' is less than the string 'ab' because the hyphen (-) is sorted as a separate character that comes before b. However, if you convert these strings to Unicode and you perform the same comparison, the Unicode string N'a-c' is considered to be greater than N'ab', because the Unicode sorting rules use a word sort that ignores the hyphen.

https://learn.microsoft.com/en-GB/sql/relational-databases/collations/collation-and-unicode-support?view=sql-server-ver16

Please consider expanding on the documentation on the following pages to highlight this issue:
* https://learn.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver16
* https://learn.microsoft.com/en-us/sql/connect/jdbc/reference/setsendstringparametersasunicode-method-sqlserverdatasource?view=sql-server-ver16

**Comment by lilgreenbird** [comment]
hi @JBodkin-Amphora 

Thanks we will look into adding more to the docs.

**Comment by lilgreenbird** [comment]
docs have been updated to add note
