### ISSUE TITLE
The getters and setters for useBulkCopyForBatchInsert is not available for SQLServerConnectionPoolProxy

### ISSUE THREAD

**Issue by PriyadharshiniP** [microsoft/mssql-jdbc#2245]
## Driver version
ms-sql-jdbc-12.4.2jre11.jar

## SQL Server version
Microsoft SQL Server 2019 (RTM-CU18) (KB5017593) - 15.0.4261.1 (X64)   Sep 12 2022 15:07:06   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19045: ) 

## Client Operating System
Windows

## JAVA/JVM version
Java 17

## Table schema
NA

## Problem description

The comments in the SQLServerConnectionPoolProxy and SQLServerConnection classes specify that the public functionalities of both classes should remain the same. 
For SQLServerConnectionPoolProxy, the getters and setters for **_useBulkCopyForBatchInsert_** are absent.

While this is mentioned in the comments of the SQLServerConnectionPoolProxy, 
**_This class's public functions need to be kept identical to the SQLServerConnection's._**

Since we use a connection pool and don't see another way to get the underlying SQLServerConnection from the SQLServerConnectionPoolProxy to set the bulk copy flag only while executing specific batch inserts. We would like to set the bulk copy only when running specific bulky insert statements.

## Expected behavior
Provide getters and setters for useBulkCopyForBatchInsert in SQLServerConnectionPoolProxy similar to SQLServerConnection.

## Actual behavior
SQLServerConnectionPoolProxy doesn't have setters and getters for useBulkCopyForBatchInsert but available in SQLServerConnection.

## Error message/stack trace
NA
## Any other details that can be helpful
NA

## JDBC trace logs
NA

**Comment by tkyc** [comment]
Looks reasonable to do, marking as enhancement. I'll let you know if/when this is taken up.
