### ISSUE TITLE
[QUESTION] v12 Support for Java 17

### ISSUE THREAD

**Issue by no-1ankush** [microsoft/mssql-jdbc#2252]
We are implementing Java applications on Azure Kubernetes Service (AKS) with Java 17 and looking to add Azure Workload Identity (AWI) to authenticate the Azure SQL Server. We have encountered some limitations with Microsoft's SDK and their support for AWI token refresh.

Based on our research and testing, we discovered that Microsoft's only supports automatic AWI token refresh with the version 12, but its production version is not yet available for Java 17. Instead, it's only available as a preview version. Additionally, production versions for v12 are available only for Java 8 and 11.
 
[https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc)

Microsoft SDK v11 & below supports setting the AWI token only once which expires after a set duration resulting in application failure.. We tested the preview version (12.3.0.jre17-preview) in our application and it is working as expected..

Can you please advise on when we can expect the stable v12 compatible with Java 17 or any other recommendation to handle it..

**Comment by tkyc** [comment]
@no-1ankush Moving forward, the team decided to release a JDK 11+ version of driver that supports JDK versions >= JDK 11. But, prior to this decision, all older driver versions labeled `jre11` also works with JDK 17 as these were tested against JDK 17 (if the driver was released after the JDK 17 release).

As for AWI, the driver should indirectly support this. AWI should be possible through `authentication=ActiveDirectoryDefault`, which uses the credential chain from the azure-identity library. I've never personally set this up myself, but if you add the above connection string property and configure "...environment variables set by the workload identity webhook, DefaultAzureCredential will authenticate the configured identity" as mentioned in the azure-identity doc [here](https://learn.microsoft.com/en-us/java/api/overview/azure/identity-readme?view=azure-java-stable#defaultazurecredential).

You can also use AWI through the driver's accessToken callback feature. This feature lets you implement a callback that the driver uses to fetch the token for authentication. When implementing the accessToken callback, you'll need to use the [AWI credential](https://learn.microsoft.com/en-us/java/api/com.azure.identity.workloadidentitycredentialbuilder?view=azure-java-stable) from azure-identity. Examples of accessToken callback implementations can be found [here](https://learn.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver16#connect-using-access-token-callback).

**Comment by no-1ankush** [comment]
Thank you @tkyc for answering the question.. Validated the Java 17 application with version 12.4.2.jre11, utilizing the accessToken call back feature and is working as expected..
