### ISSUE TITLE
Since 12.4.2 only SHA2 checksums on maven central

### ISSUE THREAD

**Issue by ecki** [microsoft/mssql-jdbc#2263]
## Problem description

Since version 12.4.2 the driver artifacts in maven central only have .sha256 checksum files.

`.sha1` files are still mandatory, and not having them can cause problems (for example when directly talking to maven central it will provide a generated sha1 header so maven does not complain, but some proxy repository managers might not be so smart, resulting in "missing checksum" errors.

While investigating this I also notices that you provide checksum files for signatures files. This is somewhat frowned upon, is this intentional? https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/12.4.2.jre11/mssql-jdbc-12.4.2.jre11.jar.asc.sha256

Good version with only SHA1 and MD5:

https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/12.4.1.jre11/

first (released) bad version:

https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/12.4.2.jre11/

All recent preview versions also have this problem.

Can you maybe also describe where and how you stage your central releases, it looks to me like the validation of staging artifacts needs to be fixed if they accept this.

I dont see specific options, your deploy plugin in the pom seems a bit old, but none of them should have that problem. Or do you deploy with gradle?

**Comment by ecki** [comment]
Here is the thread on maven-users with the statements that sha1 is still mandatory and no checksums for signatures, and some description of the problems it causes with nexus3:

https://lists.apache.org/thread/msqjgdb7cog6klz1ydkwnz3tvs77p8b8

**Comment by tkyc** [comment]
Just an update on this. Prior to 12.4.2, releases were directly handled by us. But moving forward, because of compliancy, we had to switch over to an internal pipeline plugin to handle our releases. And because of this switch, we had to use sha256 and provide checksums of signatures for release. Otherwise we wouldn't be complying with the new policy and releasing wouldn't be permitted. I'm corresponding with the team who handles these things. I'll let you know if I learn anything new. We intend to have a stable release by January 31st, so I hope to have things resolved by then.

**Comment by ecki** [comment]
> and provide checksums of signatures

Personally I think they can be helpful and do no harm, so that part I would not lose sleep about. But the missing sha1 files is an issue (and I really wonder why central does not do more basic consistency checks given the fact it’s ethereal).

**Comment by Drakonhawk** [comment]
For other Artifacts like the Auth DLLs also the POM is missing since 12.4.2. Maven or Gralde build fails without a POM.
https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc_auth/12.4.2.x64

**Comment by tkyc** [comment]
Thanks, that's also on my radar as well. By the time next release comes around (January 31st), this should all be resolved.

**Comment by Jeffery-Wasty** [comment]
Hi @ecki,

Release has concluded. Expect the latest 12.6 release to be available on Maven in the next day, including the correct checksums and signatures.
