### ISSUE TITLE
What is up with the Azure dependency?

### ISSUE THREAD

**Issue by lukecapizano** [Microsoft/mssql-jdbc#227]
`<dependency>
  <groupId>com.microsoft.azure</groupId>
  <artifactId>azure-keyvault</artifactId>
  <version>0.9.3</version>
</dependency>`

My deployment ends up with dozens of extra .jars (almost 10MB worth) because of this. This [manual download](https://www.microsoft.com/en-us/download/details.aspx?id=11774) doesn't contain these dependencies... why is this in the .pom?

**Comment by ajlam** [comment]
@lukecapizano, the Azure Key Vault dependencies were removed and made optional in our [6.1.4 preview release ](https://github.com/Microsoft/mssql-jdbc/releases/tag/v6.1.4) with PR #146. The manual download you see on the MS Download Center is for an older version of the JDBC driver (version 6.0).

**Comment by lukecapizano** [comment]
@ajlam Oh, thanks for the explanation. Since the Azure Key Vault dependencies are optional, I'm assuming I can exclude the azure dependencies and still use all of the standard JDBC features available against a local SQL Server?

Gradle example:

```
dependencies {
    testCompile "junit:junit:4.12"
    compile("com.microsoft.sqlserver:mssql-jdbc:6.1.0.jre8") {
        exclude group: "com.microsoft.azure"
    }
}
```

**Comment by ajlam** [comment]
@lukecapizano "com.microsoft.azure" covers the Azure Key Vault and Azure Active Directory for Java dependencies. These dependencies are used in the following scenarios: 
- Always Encrypted - encryption key gets stored in Azure Key Vault
- Azure AD authentication - authenticating to Azure SQL Database with Azure AD auth methods

If you're connecting to your local SQL Server, standard JDBC features should be unaffected when excluding that group.
