### ISSUE TITLE
When you batch insert multiple pieces of data, the precision of the column is affected when the BigDecimal type has a null value

### ISSUE THREAD

**Issue by UoweMe** [microsoft/mssql-jdbc#2283]
## Driver version
12.2.0-jre8 && 12.5.0-preview-jre8

## SQL Server version
2017

## Client Operating System
Linux

## JAVA/JVM version
1.8.0

## Table schema
[dbo].[test_decimal]

## Problem description
When you batch insert multiple pieces of data, the precision of the column is affected when the BigDecimal type has a null value.
table structure:
CREATE TABLE [dbo].[test_decimal] (
[id] bigint NOT NULL ,
[base_e] decimal(31,4),
[base_d] decimal(31,4),
[base_l] numeric(31,4),
[base_p] numeric(31,4),
PRIMARY KEY ([id])
);
mybatis xml sql template:
    <insert id="batchInsert" parameterType="java.util.List">
        INSERT INTO [dbo].[test_decimal] (
        [id]
        ,[base_e]
        ,[base_d]
        ,[base_l]
        ,[base_p]
        )
        VALUES
        <foreach collection="list" item="item" index="index" separator=",">
            (#{item.id,jdbcType=BIGINT}
            ,#{item.baseE,jdbcType=DECIMAL}
            ,#{item.baseD,jdbcType=DECIMAL}
            ,#{item.baseL,jdbcType=DECIMAL}
            ,#{item.baseP,jdbcType=DECIMAL})
        </foreach>
    </insert>
insert data:
[
    {
        "id":4,
        "baseE":0.1,
        "baseD":1.22,
        "baseL":2.333,
        "baseP":3.4444
    },
    {
        "id":5,
        "baseE":0.1,
        "baseD":1.22,
        "baseL":null,
        "baseP":3.4444
    },
        {
        "id":6,
        "baseE":0.1,
        "baseD":1.22,
        "baseL":2.333,
        "baseP":3.4444
    }
]
result data:
4,0.1000,1.2200,2.0000,3.4444
5,0.1000,1.2200,null,3.4444
6,0.1000,1.2200,2.0000,3.4444

## Expected behavior
Whatever values are inserted, including null values, does not affect the original data.

## Actual behavior
From the result, the value of the third column here has been abnormal, and the decimal place has been discarded.

## Error message/stack trace
No error message or stack trace.

## Any other details that can be helpful
1. The inserted data contains null values and is of type BigDecimal.
2. I suspect this problem is a scenario not covered by the previous rounding of BigDecimal type.

## JDBC trace logs
Nothing.

**Comment by Jeffery-Wasty** [comment]
Hi @UoweMe,

I notice you are testing with 12.5.0, are you testing with the connection property `calcBigDecimalScale` set to `true`?

**Comment by UoweMe** [comment]
> Hi @UoweMe,
> 
> I notice you are testing with 12.5.0. Are you testing with the connection property `calcBigDecimalScale` set to `true`?

Thank you for your attention. I just added calcBigDecimalScale=true to the connection string and inserted two rows, but it still behaves the same as the above error.

data:
1.11,1.11,null,1.13
3.35,3.35,3.37,3.38

result:
1.11,1.11,null,1.13
3.35,3.35,3.00,3.38

**Comment by Jeffery-Wasty** [comment]
Hi @UoweMe,

My apologies, the name of the property was recently changed - it is actually `calcBigDecimalPrecision`. Can you try that as well?

However, from my testing, I don't see the issue you describe. Regardless if whether the above property is set I get successful insert as seen below:

![image](https://github.com/microsoft/mssql-jdbc/assets/25423471/aed07ab9-a1d7-426c-8bc5-a935638434b0)

Do you have Java repro code for your issue? As well, what is your connection string?

**Comment by UoweMe** [comment]
@Jeffery-Wasty 
I re-added the configuration item, but it still doesn't seem to work.
![image](https://github.com/microsoft/mssql-jdbc/assets/44517452/befc8a90-f2a3-479f-b50c-b7c0ccae32aa)
![image](https://github.com/microsoft/mssql-jdbc/assets/44517452/beb4ab8f-f6c1-45cb-ae26-8ea8c67f5826)
This is my connection string: jdbc:sqlserver://xxx.xxx.xxx.xxx:1433;DatabaseName=TEST_TEMP;calcBigDecimalPrecision=true;calcBigDecimalScale=true
I used the Mybatis plug-in and hikari connection pool in the springboot project. And my entity is:
public class TestDecimal {
    private Long id;
    private BigDecimal baseE;
    private BigDecimal baseD;
    private BigDecimal baseL;
    private BigDecimal baseP;
}
The xml is:
    <insert id="batchInsert" parameterType="java.util.List">
        INSERT INTO [dbo].[test_decimal] (
        [id]
        ,[base_e]
        ,[base_d]
        ,[base_l]
        ,[base_p]
        )
        VALUES
        <foreach collection="list" item="item" index="index" separator=",">
            (#{item.id,jdbcType=BIGINT}
            ,#{item.baseE,jdbcType=DECIMAL}
            ,#{item.baseD,jdbcType=DECIMAL}
            ,#{item.baseL,jdbcType=DECIMAL}
            ,#{item.baseP,jdbcType=DECIMAL})
        </foreach>
    </insert>
And my dependency is
        <dependency>
            <groupId>com.microsoft.sqlserver</groupId>
            <artifactId>mssql-jdbc</artifactId>
            <version>12.5.0.jre8-preview</version>
        </dependency>

**Comment by lilgreenbird** [comment]
hi @UoweMe could you please share your repro code? That would make it easier for us to see the issue.

**Comment by Jeffery-Wasty** [comment]
Hi @UoweMe,

I'm using your table definition, inserting the same values with the null value, and the results are as you see above. Does this produce a different result for you.

```
/**
 * Test big decimal null case
 */
    try (SQLServerConnection con = getConnection(); Statement stmt = con.createStatement()) {
        con.setCalcBigDecimalPrecision(true);
        TestUtils.dropTableIfExists("test_decimal", stmt);
        stmt.executeUpdate("CREATE TABLE " + "test_decimal" + " (id bigint NOT NULL, base_e decimal(31,4)," +
                "base_d decimal(31,4),base_l numeric(31,4),base_p numeric(31,4), PRIMARY KEY (id))");

        try (PreparedStatement pstmt = con.prepareStatement("insert into " + "test_decimal" + " values(?,?,?,?,?)")) {
            long id = 4;
            pstmt.setObject(1, id);
            BigDecimal baseE = new BigDecimal("0.1");
            pstmt.setObject(2, baseE);
            BigDecimal baseD = new BigDecimal("1.22");
            pstmt.setObject(3, baseD);
            BigDecimal baseL = new BigDecimal("2.333");
            pstmt.setObject(4, baseL);
            BigDecimal baseP = new BigDecimal("3.4444");
            pstmt.setObject(5, baseP);

            pstmt.execute();
        }

        try (PreparedStatement pstmt = con.prepareStatement("insert into " + "test_decimal" + " values(?,?,?,?,?)")) {
            long id = 5;
            pstmt.setObject(1, id);
            BigDecimal baseE = new BigDecimal("0.1");
            pstmt.setObject(2, baseE);
            BigDecimal baseD = new BigDecimal("1.22");
            pstmt.setObject(3, baseD);
            BigDecimal baseL = new BigDecimal("2.333");
            pstmt.setObject(4, null);
            BigDecimal baseP = new BigDecimal("3.4444");
            pstmt.setObject(5, baseP);

            pstmt.execute();
        }

        try (PreparedStatement pstmt = con.prepareStatement("insert into " + "test_decimal" + " values(?,?,?,?,?)")) {
            long id = 6;
            pstmt.setObject(1, id);
            BigDecimal baseE = new BigDecimal("0.1");
            pstmt.setObject(2, baseE);
            BigDecimal baseD = new BigDecimal("1.22");
            pstmt.setObject(3, baseD);
            BigDecimal baseL = new BigDecimal("2.333");
            pstmt.setObject(4, baseL);
            BigDecimal baseP = new BigDecimal("3.4444");
            pstmt.setObject(5, baseP);

            pstmt.execute();
        }
    }
```

**Comment by UoweMe** [comment]
@Jeffery-Wasty 
I have used your code and configuration, and it is fine when you insert a single piece, but it will be problematic when you insert a batch, as follows:
`    /**
     * Test big decimal null case
     */
    @Test
    private static void main(String[] args) throws SQLException {
        String connectionString = "jdbc:sqlserver://localhost:1433;databaseName=;userName=;password=;encrypt=false;trustServerCertificate=true;calcBigDecimalPrecision=true;";
        try (SQLServerConnection con = (SQLServerConnection) DriverManager.getConnection(connectionString); Statement stmt = con.createStatement()) {
            stmt.executeUpdate("CREATE TABLE " + "test_decimal" + " (id bigint NOT NULL, base_e decimal(31,4)," +
                    "base_d decimal(31,4),base_l numeric(31,4),base_p numeric(31,4), PRIMARY KEY (id))");
            try (PreparedStatement pstmt = con.prepareStatement("insert into " + "test_decimal" + " values(?,?,?,?,?),(?,?,?,?,?),(?,?,?,?,?)")) {
                pstmt.setObject(1, 4);
                pstmt.setBigDecimal(2, new BigDecimal("0.1"));
                pstmt.setBigDecimal(3, new BigDecimal("1.22"));
                pstmt.setBigDecimal(4, new BigDecimal("2.333"));
                pstmt.setBigDecimal(5, new BigDecimal("3.4444"));
                pstmt.setObject(6, 5);
                pstmt.setBigDecimal(7, new BigDecimal("0.1"));
                pstmt.setBigDecimal(8, new BigDecimal("1.22"));
                pstmt.setBigDecimal(9, null);
                pstmt.setBigDecimal(10, new BigDecimal("3.4444"));
                pstmt.setObject(11, 6);
                pstmt.setBigDecimal(12, new BigDecimal("0.1"));
                pstmt.setBigDecimal(13, new BigDecimal("1.22"));
                pstmt.setBigDecimal(14, new BigDecimal("2.333"));
                pstmt.setBigDecimal(15, new BigDecimal("3.4444"));
                pstmt.execute();
            }
        }
    }`
And the result is:
4,0.1000,1.2200,2.0000,3.4444
5,0.1000,1.2200,,3.4444
6,0.1000,1.2200,2.0000,3.4444

**Comment by Jeffery-Wasty** [comment]
Hi @UoweMe,

Thank you, I'm now able to see the issue you describe.

**Comment by Jeffery-Wasty** [comment]
Hi @UoweMe,

I don't see anything in the driver that explains why this is happening, especially because the single insert scenario I described above works fine. It may have something with how SQL handles BigDecimal, but on our end, the best move seems to be to block the above situation for a `null` BigDecimal column.

If you still want to insert multiple times with a single execute, please try batch insert as follows:

```
String connectionString = "jdbc:sqlserver://localhost:1433;databaseName=;userName=;password=;calcBigDecimalPrecision=true;";
        try (SQLServerConnection con = (SQLServerConnection) DriverManager.getConnection(connectionString); Statement stmt = con.createStatement()) {
            stmt.executeUpdate("CREATE TABLE " + "test_decimal" + " (id bigint NOT NULL, base_e decimal(31,4)," +
                    "base_d decimal(31,4),base_l numeric(31,4),base_p numeric(31,4), PRIMARY KEY (id))");
            try (PreparedStatement pstmt = con.prepareStatement("insert into " + "test_decimal" + " values(?,?,?,?,?)")) {
                pstmt.setObject(1, 4);
                pstmt.setBigDecimal(2, new BigDecimal("0.1"));
                pstmt.setBigDecimal(3, new BigDecimal("1.22"));
                pstmt.setBigDecimal(4, new BigDecimal("2.333"));
                pstmt.setBigDecimal(5, new BigDecimal("3.4444"));
                pstmt.addBatch();
                pstmt.setObject(1, 5);
                pstmt.setBigDecimal(2, new BigDecimal("0.1"));
                pstmt.setBigDecimal(3, new BigDecimal("1.22"));
                pstmt.setBigDecimal(4, null);
                pstmt.setBigDecimal(5, new BigDecimal("3.4444"));
                pstmt.addBatch();
                pstmt.setObject(1, 6);
                pstmt.setBigDecimal(2, new BigDecimal("0.1"));
                pstmt.setBigDecimal(3, new BigDecimal("1.22"));
                pstmt.setBigDecimal(4, new BigDecimal("2.333"));
                pstmt.setBigDecimal(5, new BigDecimal("3.4444"));
                pstmt.addBatch();
                pstmt.executeBatch();
            }
        }
```

**Comment by David-Engel** [comment]
If you want to play with how SQL handles multiple values in a single insert with respect to decimal rounding (regardless of the underlying driver), here's some T-SQL you can execute from SSMS or any other tool:
Adjusting the precision of P32 shows how it affects the resulting values of P31 and P33.

```
CREATE TABLE [dbo].[test_decimal] (
[id] bigint identity NOT NULL ,
[base_e] decimal(31,4),
[base_d] decimal(31,4),
[base_l] numeric(31,4),
[base_p] numeric(31,4),
PRIMARY KEY ([id])
);

DECLARE @P11 DECIMAL(38,4) = 0.1;
DECLARE @P21 DECIMAL(38,4) = 1.22;
DECLARE @P31 DECIMAL(38,4) = 2.333;
DECLARE @P41 DECIMAL(38,4) = 3.4444;
DECLARE @P12 DECIMAL(38,4) = 0.1;
DECLARE @P22 DECIMAL(38,4) = 1.22;
DECLARE @P32 DECIMAL(38,0) = null;
DECLARE @P42 DECIMAL(38,4) = 3.4444;
DECLARE @P13 DECIMAL(38,4) = 0.1;
DECLARE @P23 DECIMAL(38,4) = 1.22;
DECLARE @P33 DECIMAL(38,4) = 2.333;
DECLARE @P43 DECIMAL(38,3) = 3.4444;

INSERT INTO [dbo].[test_decimal] (
[base_e]
,[base_d]
,[base_l]
,[base_p]
)
VALUES
(@P11
,@P21
,@P31
,@P41),
(@P12
,@P22
,@P32
,@P42),
(@P13
,@P23
,@P33
,@P43)
```

**Comment by UoweMe** [comment]
@Jeffery-Wasty Thanks for your proposal, I will consider how to replace the existing sql. In addition, in my project, because the difference between null and 0.00 is ignored, using 0.00 instead of null can still guarantee the accuracy in batch insertion.

**Comment by UoweMe** [comment]
@David-Engel 
Thank you for your attention. In fact, yesterday I also tried to break the point in the development tool to troubleshoot this problem, so in the end, I used 0.00 to replace null without affecting my business. I will try again to find the root cause of the driver's influence here.

**Comment by Jeffery-Wasty** [comment]
Great to hear there's another solution you were able to find. Closing issue as resolved.
