### ISSUE TITLE
jdbc driver version 12.x not available for jdk17

### ISSUE THREAD

**Issue by sschotte** [microsoft/mssql-jdbc#2294]
## Question
We need to support MS SQL Server 2022 on jdk17. We checked the compatibility matrix and we see this:
Driver version 12.4 and 12.2 are the only ones compatible.
These versions claim to run on jdk17 however when downloading there are only the jre8 and jre11 jars.
We are expecting the jre17 jar. Which one needs to be used for running on Java 17 ?

**Comment by barryw-mssql** [comment]
Please use the JRE 11 JAR for whichever driver you choose. The JRE 11 JAR supports JDK 11+. I would recommend the 12.4 driver as it is the newer driver unless there is some specific reason you want to use the 12.2 driver.

**Comment by sschotte** [comment]
Thanks for the info. We are using the JDK17 Java version hence the question if the 12.4 driver has a jar for 1re17. It is not available in the download package.
Driver 11.2 has the jre17 jar however the compatibility matrix does not indicate it is compatible with MS SQL Server 2022.
Please clarify what we need to use to officially in a supported way connect to MS SQL Server 2022 via a java application using Java 17 (jdk/jre17).

**Comment by Jeffery-Wasty** [comment]
Starting from driver version 12.1.0, two versions of the driver are released. One for Java 8 and one for Java 11 and greater. Therefore, please use the jre11 version for Java 17.

We're looking into updating our documentation to make this more clear in the future.

**Comment by Jeffery-Wasty** [comment]
Readme has been updated, closing issue.
