### ISSUE TITLE
SQLServerBulkCopy doesn't check BigDecimal scale

### ISSUE THREAD

**Issue by Arthurm1** [Microsoft/mssql-jdbc#230]
When using `SQLServerBulkCopy` to import a `BigDecimal` into a `Numeric` column the scale isn't checked.

If the column metadata is defined as a `Decimal(10, 4)` and then `new BigDecimal("1").setScale(2, RoundingMode.HALF_UP)` is passed the table will end up with a value of 0.01 instead of 1.0

I think it would be safer if the `IOBuffer.writeBigDecimal` was passed `bulkScale` by the `SQLServerBulkCopy.writeColumnToTdsWriter` method and then threw an exception when the `bigDecimalVal.scale()` differed from `bulkScale`

**Comment by v-suhame** [comment]
Yes, using `bulkScale` value in `IOBuffer#writeBigDecimal` is the best option. 
Thanks @Arthurm1! I will submit a fix.

**Comment by v-suhame** [comment]
@Arthurm1 can you review PR#233?

**Comment by v-suhame** [comment]
Closing this issue with fix #251. Thanks again @Arthurm1 !
