### ISSUE TITLE
Officially Support Java 21

### ISSUE THREAD

**Issue by ecki** [microsoft/mssql-jdbc#2306]
Java 21 is for some time the latest LTS but not all compoennts have catched up and proclaim support for it. For example the Microsoft Download page only mentions it is supported on Java 20.

## Describe the preferred solution
Declare Java21 as supported.

## Describe alternatives you've considered
Define what Java 21 not work yet (if there are any), or give an ETA for a version which is supposed to work with Java 21. Or remove the upper Java version from the download page (i.e. Java 8+, latest fully tested version x)

## Reference Documentations/Specifications
https://learn.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-ver16

**Comment by Jeffery-Wasty** [comment]
Hi @ecki,

Our documentation is updated with every stable release. As the driver supports Java 21 starting from 12.5, we will update documentation to reflect this alongside our 12.6 release, which is planned for January 31.

**Comment by Jeffery-Wasty** [comment]
Closing as docs will be updated when 12.6 is released.
