### ISSUE TITLE
Missing .jar files

### ISSUE THREAD

**Issue by harmonica2** [Microsoft/mssql-jdbc#231]
The latest version of “Microsoft JDBC Driver 6.0 for SQL Server” is missing the following files:
•	sqljdbc.jar,
•	sqljdbc4.jar
•	sqljdbc41.jar
These files are required for backwards compatibility, and are referred to in the documentation here:
https://docs.microsoft.com/en-us/sql/connect/jdbc/using-the-jdbc-driver
These files were part of the download late last year, but now they are not.
Would you please update the download to include these files again?

**Comment by ajlam** [comment]
@harmonica2 - apologies for moving around the packages. We updated the Microsoft Download Center and created a new download center page for each JDBC driver version. 

The sqljdbc.jar and sqljdbc4.jar can be found in the package for the [JDBC driver 4.0](https://www.microsoft.com/en-us/download/details.aspx?id=54629). These are the same jars we used to ship in the newer versions of the driver (ex. JDBC v4.1, v4.2, and v6.0). 

The sqljdbc41.jar shipped in several packages below: 
- The original JDBC driver v4.1 [here](https://www.microsoft.com/en-us/download/details.aspx?id=54670)
- The JDBC driver v4.2 [here](https://www.microsoft.com/en-us/download/details.aspx?id=54671). 
- The JDBC driver v6.0 [here](https://www.microsoft.com/en-us/download/details.aspx?id=11774)

I will also update https://docs.microsoft.com/en-us/sql/connect/jdbc/using-the-jdbc-driver to clarify. 

Please let me know if you have additional questions.

**Comment by harmonica2** [comment]
Thanks for the quick response.  Please include instructions for sqljdbc4.jar, because this is the one required for RJDBC.

**Comment by ajlam** [comment]
You can download the sqljdbc4.jar from the [JDBC driver 4.0](https://www.microsoft.com/en-us/download/details.aspx?id=54629) package.

**Comment by harmonica2** [comment]
I've confirmed that RJDBC works in Windows using the JDBC driver 4.0.
