### ISSUE TITLE
mssql-jdbc-14.4.2.jre8 TLSv1.3 

### ISSUE THREAD

**Issue by ovidiugugila** [microsoft/mssql-jdbc#2313]
Hi, everyone,

I've the following scenario.

I recently had a scenario in my app where is required to use TLSv1.3 in my client-server communication.
I use SQL Management Studio 2022 in order to use TLSv1.3 and as client I use a java client. My problem is the following:

    when I build the connection url in order to communicate with database even if I set the protocol to TLSv1.3 in my ClientHello I can see the both version of TLS is supported, TLSv1.2 and also TLSv1.3.

I already set the sslProtocol=TLSv1.3;encrypt=strict;trustServerCertificate=false; in my connection url.

Is any way to force the Client side to use the TLSv1.3 only?
![connUrlFlags](https://github.com/microsoft/mssql-jdbc/assets/22844582/6863c4ec-fd83-4399-b5de-cc59943faa23)
![gitSupportedVersion](https://github.com/microsoft/mssql-jdbc/assets/22844582/5921f385-10f7-4e26-8b77-b5f6df2085ce)

**Comment by AlBundy33** [comment]
you can try to start your application with `-Djdk.tls.client.protocols="TLSv1.3"`

**Comment by ovidiugugila** [comment]
Your fix is valid, I tried it....but I want to know if it is a similar fix to the mssql-jdbc driver level.

**Comment by Jeffery-Wasty** [comment]
Hi @ovidiugugila,

Does this resolve your issue? Let us know if you require further information or assistance. Without further communication, we'll assume the issue is resolved and mark it as closed.
