### ISSUE TITLE
JDBC slow on SQL Server 2022 on Azure VM

### ISSUE THREAD

**Issue by pceglie** [microsoft/mssql-jdbc#2314]
## JDBC 12.4 just runs slower?

Moving from SQL Server 2016 STD to SQL2022 STD on Azure Virtual Machine (E8bds_v5) the application runs very slow. About 3 times slower.

I'm using selectMethod = direct in the connection string (the application heavily uses cursors).

Metrics on VM doesn't show any kind of issue (CPU, RAM, DIsks) but application is very slow.

What am I missing?

Thanks

**Comment by pceglie** [comment]
The SQL VM and the application VM are in the same azure vnet.
Do you have any ideas for testing it?

**Comment by AlBundy33** [comment]
check pings from
your pc to sql vm
your app vm to sql vm
you can also try iperf

or write a simple program to measure the speed and run it from different locations maybe also on sql vm if possible)

**Comment by Jeffery-Wasty** [comment]
Hi @pceglie,

Is further assistance needed on this issue? Without further communication, we'll assume the matter is resolved, and close the issue.

**Comment by pceglie** [comment]
Hi @Jeffery-Wasty , thanks for your support.
I'll test 12.6 jdbc driver in the next days but for now that's all.
Regards

**Comment by pceglie** [comment]
Hi @Jeffery-Wasty , thanks for your support.
I'll test 12.6 jdbc driver in the next days but for now that's all.
Regards
