### ISSUE TITLE
Connection.getMetaData().getProcedures does not handle schema as a pattern

### ISSUE THREAD

**Issue by snicoll** [microsoft/mssql-jdbc#2336]
## Driver version
12.6.0.jre11

## SQL Server version
2017-latest

## Client Operating System
MacOS

## JAVA/JVM version
openjdk version "17.0.10" 2024-01-16 LTS

## Table schema
A full repro is available here:
https://github.com/ks-no/spring-jdbc-demo

## Problem description
The Javadoc of `java.sql.DatabaseMetaData#getProcedures` states that the schema and procedureName parameters are pattern and not exact match, just like its sibbling `getFunctions`.

Looking at `com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData`, those parameters seem to be handled as patterns using the `escapeIDName` method. However the sames arguments for `getProcedures` are not.

## Expected behavior
Searching for a procedure using `some\_schema` should search for exactly `some_schema` (and not any character between `some` and `schema`).

## Actual behavior
If the pattern character is escaped using the escape character, the search does not succeed.

See also https://github.com/spring-projects/spring-framework/issues/32295

**Comment by tkyc** [comment]
Thanks for the repro taking a look. I'll get back to you.

**Comment by snicoll** [comment]
The repro is from a third party with a weird test. Let me know if you're having trouble running it (like I did) and I can provide something more straightforward.

**Comment by audunmeltzer** [comment]
If you run test from intellij, you need this plugin: https://plugins.jetbrains.com/plugin/14080-kotest

**Comment by tkyc** [comment]
@snicoll

>The repro is from a third party with a weird test. Let me know if you're having trouble running it (like I did) and I can provide something more straightforward.

Thanks, if you can share that as well.

**Comment by tkyc** [comment]
Using `escapeIDName` seems to fix the issue. Still testing/evaluating the fix...
