### ISSUE TITLE
Release notes are not visible for 12.6.1 driver?

### ISSUE THREAD

**Issue by HarshaVardhan-Sai** [microsoft/mssql-jdbc#2343]
On the official MSSQL JDBC Driver release notes page there is no documentation for 12.6.1 (at https://learn.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver?view=sql-server-ver16) but the milestone https://github.com/microsoft/mssql-jdbc/milestone/73?closed=1is in closed status. would we be having more fixes in this version or this is ready to be published?

Kindly confirm
Thank you

**Comment by Jeffery-Wasty** [comment]
Hi @HarshaVardhan-Sai,

You're right, we missed this. The docs will be updated shortly.

**Comment by Jeffery-Wasty** [comment]
Docs have been updated, will be visible in a few hours.
