### ISSUE TITLE
Computed columns and BULK INSERTs

### ISSUE THREAD

**Issue by chaks7** [microsoft/mssql-jdbc#2345]
https://github.com/microsoft/mssql-jdbc/blob/eae6d7b33571c92029169b33378b2405e8df448a/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerBulkCopy.java#L1737

Can the driver exclude computed columns? If a table has computed column in the definition I cannot import the data.

**Comment by Jeffery-Wasty** [comment]
Hi @chaks7,

What version of the driver are you using? We had [an enhancement recently](https://github.com/microsoft/mssql-jdbc/pull/1562) to ignore computed columns for batch insert merged in our 12.5 release. You can use the 12.6.1 stable release if you're interested in this enhancement.

**Comment by chaks7** [comment]
Hi @Jeffery-Wasty: Yes, realized it is now fixed in 12.6.1. I was on the older version: 11.2.3.jre11. Closing the issue.
