### ISSUE TITLE
Any estimated date of release of 12.6.2 driver or 12.7.0?

### ISSUE THREAD

**Issue by HarshaVardhan-Sai** [microsoft/mssql-jdbc#2374]
Hi Team,

Could you please let us know if there is already a planned date for the release of 12.6.2 driver as 12.6 does contain bugs even after hotfix version 12.6.1 or it would be directly 12.7.0 driver release?

**Comment by Jeffery-Wasty** [comment]
Our 12.7 release is planned for this Thursday (April 4th). It is a preview release. There is no 12.6.2 hotfix currently planned.

**Comment by HarshaVardhan-Sai** [comment]
Thank you @Jeffery-Wasty & @lilgreenbird 
With 12.6.1 driver using Call to execute a stored procedure fails as the stored procedure is also expecting default values.

**Comment by HarshaVardhan-Sai** [comment]
Hi @lilgreenbird 
It is about executing stored procedure using CALL and luckily I see the following issue has similar code :  https://github.com/microsoft/mssql-jdbc/issues/2344
