### ISSUE TITLE
[QUESTION] Release 12.7.0 without suffix .jre8/.jre11

### ISSUE THREAD

**Issue by Eng-Fouad** [microsoft/mssql-jdbc#2391]
## Question

I noticed a new release [12.7.0](https://central.sonatype.com/artifact/com.microsoft.sqlserver/mssql-jdbc/12.7.0) without a suffix. Does that mean future releases will not have suffix .jre8/.jre11 anymore?

**Comment by barryw-mssql** [comment]
The JDBC 12.7.0 preview release was built using a new build/release process and the suffix was accidentally omitted. All future releases will have the suffix.

Please let us know if this answers your question.

Thx,
Barry

**Comment by Eng-Fouad** [comment]
> The JDBC 12.7.0 preview release was built using a new build/release process and the suffix was accidentally omitted. All future releases will have the suffix.
> 
> Please let us know if this answers your question.
> 
> Thx, Barry

Thanks for your answer. I appreciate it.
