### ISSUE TITLE
SQLServerMetaData Constructor Issue

### ISSUE THREAD

**Issue by mpwong852** [microsoft/mssql-jdbc#2404]
## Driver version
11.2.3.jre17

## JAVA/JVM version
Java 17

## Is your feature request related to a problem? If so, please give a short summary of the problem and how the feature would resolve it
I need to use create "SQLServerMetaData" like below

(new SQLServerMetaData("row_id", java.sql.Types.INTEGER, 0, 0, true, false, SQLServerSortOrder.Unspecified, -1)

I find that **enum SQLServerSortOrder is not public**, which cause me can not use this constructor. Can you make it become public ?

## Describe the preferred solution
make enum SQLServerSortOrder become public
```[tasklist]
### Tasks
```

**Comment by tkyc** [comment]
Looks like an innocuous change. This should be acceptable todo. Feel free to make a PR or I will later.
