### ISSUE TITLE
[QUESTION] How to connect using an AD Domain user from Linux

### ISSUE THREAD

**Issue by ChrisCollinsIBM** [microsoft/mssql-jdbc#2406]
## Question
I recently ran into an issue where the end user wanted to connect using the MS SQL Server JDBC driver, and no matter what permutation of DOMAIN\user or passing the domain in the connection string we used, the server was reporting that "SQL Server authentication was requested using a domain user".

We can't use integrated security for a linux system not on the AD and there may or may not be the possibility of having a hardware appliance join the domain, and with the open source JTDS driver this does work when passing the NTLMv2 flag.

So is there a way to pass a domain user to the SQL Server and request something other than SQL Server authentication from Linux?

## Relevant Issues and Pull Requests
#2127 is loosely related - but they were joining the domain so not quite the same.

**Comment by tkyc** [comment]
Could you provide the server logs for when the login attempt was made? And also, what does your connection string look like? Thanks.

Just a FYI incase:
https://docs.microsoft.com/en-us/sql/relational-databases/performance/view-the-sql-server-error-log-sql-server-management-studio?view=sql-server-ver15

**Comment by ChrisCollinsIBM** [comment]
The connection string value is very basic:

`jdbc:sqlserver://hostname:port;databaseName=databaseName;encrypt=false;;statementPoolingCacheSize=10;queryTimeout=300`

Username and password are passed in when building the connection and the domain is prepended in `DOMAIN\user` format still as the driver didn't previous have an explicit domain field (but does now).


Unfortunately it's not our SQL Server but a customer's, but while on the log error we received was:

`Attempting to use an NT account name with SQL Server authentication`

I had asked them if this error was related to something on the SQL Server itself but they indicated they didn't believe that it was, and switching over to using JTDS instead with NTLM we were able to login with the DOMAIN\user which leads me to believe it's not a setting on the SQL Server.

It seems like the driver is explicitly trying to use SQL Server Authentication instead of NTLM, and reading the connection properties available to control the authentication it appears that parameters such as `authenticationScheme` are only applicable when using integratedSecurity which isn't available in Linux especially when not on a domain.

That being said, reading a little further I see the `authentication` parameter seems to indicate maybe something there could be used specifically `authentication=ActiveDirectoryPassword`. Is this the value we need to include if a user wants to auth via Active Directory vs SQL Server Authentication?

**Comment by ChrisCollinsIBM** [comment]
I was able to re-create this with a test SQL Server as well. Created a local user (not domain, but still windows auth)

`Login failed for user 'EC2AMAZ-L1Q0M0K\dbUser'. Reason: Attempting to use an NT account name with SQL Server Authentication. [CLIENT: 172.XX.XX.XXX]`

I tried adding `authentication=ActiveDirectoryPassword` to the connection string but got some SSL errors indicating that although `encrypt=false` was used maybe it's mandatory when using this auth?

Some guidance would be appreciated but this test coincides with what we were seeing on the customer system.

**Comment by ChrisCollinsIBM** [comment]
I'll try the user/pass in the connection string manually along with the domain pulled out into the proper field to see.

I did find the doc above you referenced but since it uses integratedSecurity that won't work as the driver throws an error.

```ds.setIntegratedSecurity(true);
ds.setAuthenticationScheme("NTLM");```

**Comment by ChrisCollinsIBM** [comment]
Any followup on this @tkyc?

**Comment by David-Engel** [comment]
Per the [doc](https://learn.microsoft.com/en-us/sql/connect/jdbc/using-ntlm-authentication-to-connect-to-sql-server?view=sql-server-ver16), I believe `integratedSecurity=true` is also required. Try `jdbc:sqlserver://<hostname>;integratedSecurity=true;authenticationScheme=NTLM;domain=<server_domain>;user=<userName>;password=<password>`

**Comment by ChrisCollinsIBM** [comment]
> Per the [doc](https://learn.microsoft.com/en-us/sql/connect/jdbc/using-ntlm-authentication-to-connect-to-sql-server?view=sql-server-ver16), I believe `integratedSecurity=true` is also required. Try `jdbc:sqlserver://<hostname>;integratedSecurity=true;authenticationScheme=NTLM;domain=<server_domain>;user=<userName>;password=<password>`

Hi David, 

As I mentioned in a previous comment this doesn't work on Linux:

----

I did find the doc above you referenced but since it uses integratedSecurity that won't work as the driver throws an error.

ds.setIntegratedSecurity(true);
ds.setAuthenticationScheme("NTLM");
If you try to enable it, you get this:
Unable to communicate with a database for the following reason : This driver is not configured for integrated authentication., likely because no mssql-jdbc_auth-<version>-<arch>.dll will be available on a Linux system

**Comment by tkyc** [comment]
@ChrisCollinsIBM 

Apologies for the delay. I was occupied with another issue and was setting things up to verify NTLM on a linux client. I can 100% confirm that NTLM works. I was able to successfully authenticate with NTLM using the driver.

This is the connection string I used: 

`jdbc:sqlserver://my-sql-server.mydomain.ad;integratedSecurity=true;authenticationScheme=NTLM;domain=mydomain.ad;user=domainUser;password=domainUserPassword;encrypt=false;trustServerCertificate=true;`

Since this works with JTDS, I don't think it's any problem with group policies, permissions or any fault with the domain user and domain controller. Maybe the driver version you're using doesn't have NTLM support? Starting with 7.3.1 was when mssql-jdbc supported NTLM. What's the exact driver version you are using?

**Comment by ChrisCollinsIBM** [comment]
> @ChrisCollinsIBM 
> 
> 
> 
> Apologies for the delay. I was occupied with another issue and was setting things up to verify NTLM on a linux client. I can 100% confirm that NTLM works. I was able to successfully authenticate with NTLM using the driver.
> 
> 
> 
> This is the connection string I used: 
> 
> 
> 
> `jdbc:sqlserver://my-sql-server.mydomain.ad;integratedSecurity=true;authenticationScheme=NTLM;domain=mydomain.ad;user=domainUser;password=domainUserPassword;encrypt=false;trustServerCertificate=true;`
> 
> 
> 
> Since this works with JTDS, I don't think it's any problem with group policies, permissions or any fault with the domain user and domain controller. Maybe the driver version you're using doesn't have NTLM support? Starting with 7.3.1 was when mssql-jdbc supported NTLM. What's the exact driver version you are using?

Was this on a Linux system? If I try to use integratedSecurity I get the error I've posted a few times now in previous comment.

**Comment by tkyc** [comment]
@ChrisCollinsIBM 

That's right. I didn't get that error. That error shouldn't be thrown because if `authenticationScheme=NTLM`, it should skip the logic that does native auth. This is the reason that's making me think you might be using an older driver version that doesn't support NTLM. What's your driver version?

**Comment by ChrisCollinsIBM** [comment]
Ok that's something I can't believe I didn't check before now, "am I on the latest" should be the first thing.

I'll check that tomorrow and get back to you, appreciate the follow up.

**Comment by ChrisCollinsIBM** [comment]
@tkyc - Latest results. It was using 7.2 which doesn't have the NTLM flag, my bad!

I swapped out the driver for 12.4 with the following connection string:

```
jdbc:sqlserver://172.XX.XX.XX:1433;integratedSecurity=true;authenticationScheme=NTLM;databaseName=testDb;statementPoolingCacheSize=10;queryTimeout=300
```

New error:
```
Unable to communicate with a database for the following reason : Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication.
```


I as mentioned back at the start, using the JTDS driver I can do an NTLM authentication without having to have the source Linux machine join the domain, which is the behaviour I'm trying to re-create with the Microsoft Driver.

**Comment by ChrisCollinsIBM** [comment]
Ok I think I figured out the secret formula.

Passing the domain field in the user yields the untrusted domain error, but passing the domain IN the domain field in the connection string works.

```
jdbc:sqlserver://172.XX.XX.XX:1433;integratedSecurity=true;authenticationScheme=NTLM;domain=XXXXXX-XXXXXX;databaseName=testDb;statementPoolingCacheSize=10;queryTimeout=300
```

That gives me what I need and I can schedule a JDBC driver update in a future release as well as ensuring we present the domain field and document how to connect via NTLM.

Thanks @tkyc and @David-Engel for your assistance and prompt feedback.

**Comment by tkyc** [comment]
> According to a previous issue related to this it looks like you indicated that the Linux machine MUST join the domain for this to work.

Oops. I'll retract that. Incase anyone else stumbles on this thread or the other.

**Comment by rdk** [comment]
Using connection string 

`jdbc:sqlserver://172.XX.XX.XX:1433;integratedSecurity=true;authenticationScheme=NTLM;domain=XXXXXX-XXXXXX;databaseName=testDb`

(especially `integratedSecurity=true;authenticationScheme=NTLM` part)
works if you want to login as any AD user from linux with username and password.

Even though no "integrated security" ot NTLM is actually happening there. Right?
Or am I missing something?

**Comment by tkyc** [comment]
@rdk 

That's the correct connection string to use.

> Even though no "integrated security" ot NTLM is actually happening there. Right?

NTLM is occurring. If you do a "select auth_scheme from sys.dm_exec_connections where session_id=@@spid" it should say you used NTLM.

**Comment by ChrisCollinsIBM** [comment]
@rdk That certainly is part of the confusion. Having to specify `integratedSecurity=true` for `authenticationScheme=NTLM` to function when you're not actually using integrated security (since you're not in windows or joined to the domain) is a bit unintuitive.

So NTLM is occurring as @tkyc says, but integrated security is not.

**Comment by Photosdeshawn** [comment]
https://administrator71.github.io/amputee/ It’s all done now

**Comment by renaud67-onet** [comment]
Hello,
with clouddbeaver, I try to connect to MS SQLSERver using AD, with this URL : 

jdbc:sqlserver://<hostnam>:1433;integratedSecurity=true;authenticationScheme=NTLM;domain=xxxx;databaseName=master, 
from th SQL server side This error is thrown : Login failed for user ''. Reason: An attempt to login using SQL authentication failed. Server is configured for Integrated authentication only
the account used for testing, works well to connect with ms studio or sql developer.
Any idea ?
Thnak you all
