### ISSUE TITLE
Date handling is broken.  Returns datetime with time zone offset for date field

### ISSUE THREAD

**Issue by Daemach** [microsoft/mssql-jdbc#2407]
## Driver version
12.4.2.jre11

## SQL Server version
Microsoft SQL Server 2019 (RTM-CU24) (KB5031908) - 15.0.4345.5 (X64) 
	Dec  4 2023 14:44:16 
	Copyright (C) 2019 Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor)

## Client Operating System
Windows Server 2019 Datacenter

## JAVA/JVM version
Java 11.0.22 (Eclipse Adoptium)

## Table schema
CREATE TABLE [dbo].[fees](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[date] [date] NOT NULL,
	[monthEndDate]  AS (eomonth([date])),
	[quarterEndDate]  AS ([dbo].[quarterEndDate]([date])),
	[uploadDetailID] [int] NULL,
	[accountID] [int] NULL,
	[modelID] [int] NULL,
	[platformID] [smallint] NULL,
	[custodianID] [smallint] NULL,
	[consultantID] [int] NULL,
	[modelAdvisorID] [int] NULL,
	[mmaID] [int] NULL,
	[accountNumber] [varchar](128) NULL,
	[accountName] [varchar](128) NULL,
	[marketValue] [float] NULL,
	[rate] [float] NULL,
	[fee] [float] NULL,
	[adjustment] [float] NULL,
	[total]  AS ([fee]+[adjustment]),
	[dCreated] [datetime] NOT NULL,
	[bAdjustment] [bit] NULL,
	[dReported] [date] NULL,
	[portfolioTransactionID] [int] NULL,
	[userID] [int] NULL,
	[feeSourceID] [tinyint] NULL,
)

## Problem description
`Date` and `datetime` fields are returning `dateTimeOffset` timestamps from the jdbc driver ( April, 25 2024 13:56:29 -0400 )

## Expected behavior
I expect a date from a `date` datatype - no time, no time zone offset, just a date ( 2024-04-25 )
`datetime` fields should not return a time zone offset, just a date and time.

## Actual behavior
For either `date` or `datetime`: ( April, 25 2024 13:56:29 -0400 )

## Error message/stack trace
No error, this is the normal (and incorrect) driver output

## Any other details that can be helpful
Switching to jTDS driver eliminates this problem, but it doesn't support MSSQL 2019.

**Comment by tkyc** [comment]
Looking into this... I'll get back to you.

**Comment by tkyc** [comment]
@Daemach 

Could you provide a demo application that reproduces the error (that inserts and selects the data and datetime)? When I debug the code paths for date and datetime, I don't see how this could happen.

**Comment by tkyc** [comment]
Also, what does your connection string look like?

**Comment by lilgreenbird** [comment]
as per @tkyc could you please provide a repro. 
also, could you pls clarify, did this work for you in previous versions of the driver?

**Comment by Daemach** [comment]
I'm sorry about the delay - travelling at the moment and don't have much with me.  I use this with an application server called Lucee - JTDS driver works, this one doesn't.  I assumed it was a driver issue.  Connection string is pretty simple, something like DatabaseName=VeritiAdmin&sendStringParametersAsUnicode=true&SelectMethod=direct

**Comment by Daemach** [comment]
> as per @tkyc could you please provide a repro. also, could you pls clarify, did this work for you in previous versions of the driver?

I don't think I've used a previous version of the library.  I only went this route because JTDS is being phased out.

**Comment by tkyc** [comment]
> I'm sorry about the delay - travelling at the moment and don't have much with me. I use this with an application server called Lucee - JTDS driver works, this one doesn't. I assumed it was a driver issue. Connection string is pretty simple, something like DatabaseName=VeritiAdmin&sendStringParametersAsUnicode=true&SelectMethod=direct

No worries. Whenever you can provide a repro, I'll take a look at this issue again.

**Comment by Daemach** [comment]
Can you recommend a connection string?

**Comment by tkyc** [comment]
@Daemach 

For this case, a simple string like the one below is enough:

`jdbc:sqlserver://your-server:1433;database=your-database;user=your-user;password=your-password;encrypt=false;trustServerCertificate=true`

**Comment by Jeffery-Wasty** [comment]
Hi @Daemach,

We'll be closing this issue in ~a week if there is no further reply.
