### ISSUE TITLE
MFA Authentication within the same application window

### ISSUE THREAD

**Issue by Schmlughtz007** [microsoft/mssql-jdbc#2409]
If we try to do an interactive authentication with JDBC using MFA (Multi Factor Authentication)
What happens by default is a new instance of the browser opens then the authentication is done, then the browser will redirect to a localhost with a random port number, and the process finishes with no authentication.

Ideally we would have the MFA open on the same application, avoid creating a new instance of the browser and once authenticated get the token and make the application work.
![Capture d’écran 2024-05-08 132009](https://github.com/microsoft/mssql-jdbc/assets/43368751/a80fe116-5785-4aa4-8a36-0348d8c90c8f)

**Comment by tkyc** [comment]
@Schmlughtz007 What driver version did this occur on? I recall there being related fixes with interactive auth, so depending on the version it may have been corrected.

**Comment by Schmlughtz007** [comment]
Hello @tkyc 

It was with the version 12.6.1 of the driver , argh I juste saw that thé latest is 12.7.0 do you think it has been resolved in thé latest version?

Thx

**Comment by Schmlughtz007** [comment]
The driver is the jdbc Microsoft driver

**Comment by tkyc** [comment]
> It was with the version 12.6.1 of the driver , argh I juste saw that thé latest is 12.7.0 do you think it has been resolved in thé latest version?

Disregard what I mentioned earlier. I reread your post just now, earlier I had misunderstood your original post.

> What happens by default is a new instance of the browser opens then the authentication is done, then the browser will redirect to a localhost with a random port number, and the process finishes with no authentication.

This is the expected behaviour eg. when a new browser window opens.

> ...and the process finishes with no authentication

Are you saying interactive auth is failing for you? You're unable to auth to the server through interactive?

> Ideally we would have the MFA open on the same application, avoid creating a new instance of the browser and once authenticated get the token and make the application work

So you want MFA to open a new browser tab, within an existing browser? Instead of a new browser instance? If that's the case, that isn't something the driver doesn't have control over. All that is delegated to MSAL4J.

**Comment by Schmlughtz007** [comment]
Hello @tkyc 

OK, I'll try to explain what I am trying to do, and what is not working.
I wanted to use an application, let's say dbschema (a java application), by the way the same problem arises for other db modeling like tools). 

In dbschema after installing the driver, I want to connect with MFA.
The problem is when I click connect from DBSchema, there is a web browser (outside of DBSchema) that opens to authenticate with the MFA. Once the authentication is done the Web Browser redirects to a localhost and a random port number (screen shot of the bug I mentionned) And DBSchema keeps waiting for a feedback from the browser, a feedback that never comes.

This article explains the issue in Microsoft : https://learn.microsoft.com/en-us/troubleshoot/sql/ssms/cant-reach-this-page
So Microsoft resolves the issue by opening the authentication MFA screen directly in the tool (SSMS) and not in a browser.

I was thinking if in the driver you could force the opening to be a native popup instead of having an opening of the Web Browser?

**Comment by tkyc** [comment]
@Schmlughtz007 

Thanks for the clarification. I see your point. However, the driver doesn't have control over the browser popup. We delegate to msal4j to do interactive auth and so they're opening the browser. We don't have control over this within the driver.

> This article explains the issue in Microsoft : https://learn.microsoft.com/en-us/troubleshoot/sql/ssms/cant-reach-this-page
So Microsoft resolves the issue by opening the authentication MFA screen directly in the tool (SSMS) and not in a browser.

From the article, it suggests defaulting your system browser to Windows Edge. If you haven't already and if possible, I recommend trying that.

**Comment by Jeffery-Wasty** [comment]
Hi @Schmlughtz007,

Let us know if this answers your concerns. Without further reply we'll be closing this issue in a few days.
