### ISSUE TITLE
Intermittent driver exception on shutdown

### ISSUE THREAD

**Issue by joel-rieke** [microsoft/mssql-jdbc#2437]
## Driver version
9.4.1.jre11

## SQL Server version
Microsoft SQL Server 2019 (RTM-GDR) (KB5035434) - 15.0.2110.4 (X64) 
	Mar 12 2024 18:25:56 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor)

## Client Operating System
Linux

## JAVA/JVM version
eclipse-temurin:17.0.10_7-jre-jammy

## Table schema
n/a

## Problem description
While attempting to cycle a Virtual machine in AKS, we're getting the following exception.

java.lang.NullPointerException: Cannot invoke "com.microsoft.sqlserver.jdbc.TDSChannel$ProxySocket.setStreams(java.io.InputStream, java.io.OutputStream)" because "this.proxySocket" is null

The throwing of this exception causes other undesirable side-effects.

## Expected behavior
No NullPointerException even though we are shutting down.

## Actual behavior
java.lang.NullPointerException: Cannot invoke "com.microsoft.sqlserver.jdbc.TDSChannel$ProxySocket.setStreams(java.io.InputStream, java.io.OutputStream)" because "this.proxySocket" is null

## Error message/stack trace
Complete error message and stack trace.
java.lang.NullPointerException: Cannot invoke "com.microsoft.sqlserver.jdbc.TDSChannel$ProxySocket.setStreams(java.io.InputStream, java.io.OutputStream)" because "this.proxySocket" is null
at com.microsoft.sqlserver.jdbc.TDSChannel.disableSSL(IOBuffer.java:734)
at com.microsoft.sqlserver.jdbc.TDSChannel.close(IOBuffer.java:2097)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.clearConnectionResources(SQLServerConnection.java:3797)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.close(SQLServerConnection.java:3781)

## Any other details that can be helpful
If this was already fixed in a newer version of the driver, please let me know so I can upgrade.

## JDBC trace logs
Intermittent, sorry I don't have this...

**Comment by Jeffery-Wasty** [comment]
Hi @joel-rieke,

It looks like a null check was merged for 9.5.0. Please upgrade your driver version to at least 9.5.0 (we recommend the latest, 12.6.2).

**Comment by joel-rieke** [comment]
Looks like it's already been fixed...  I'll follow your advice and if I see this happen again, I'll either re-open this one or file a separate new issue.

**Comment by joel-rieke** [comment]
Incidentally, I did try to jump to 12.6.2, but none of our existing jdbc connection urls seem to work in our development environment.  Perhaps there was a change in requirements for the jdbc connection url going from 9.4.1 12.6.2.  I did notice that 9.5.0 only has a pre-release build available to it which makes me a little nervous about using it?

**Comment by Jeffery-Wasty** [comment]
What about the next stable release after 9.4.1, [10.2.0](https://github.com/microsoft/mssql-jdbc/releases/tag/v10.2.0)?

**Comment by joel-rieke** [comment]
Same problem with 10.2.0.  I switched back to 9.5.0.jdk17 prerelease for now.  It seems it can't find the database name using our existing jdbc url config.

**Comment by Jeffery-Wasty** [comment]
I'm not seeing any changes from 9.5.0 to 10.2.0 that would explain the issue you're seeing. Can you create a new issue and provide the connection string options you are using in the description? This will help us keep things organized as the thread we're commenting in now has had its issue already resolved.

**Comment by joel-rieke** [comment]
This maybe is an issue with trustServerCertificate=true parameter?  We use this in development.  Will the jdbc connections fail with new builds and this parameter?

**Comment by Jeffery-Wasty** [comment]
I don't see any changes made to [`trustServerCertificate`](https://learn.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver15) between 9.5.0 to 10.2.0. One thing I am seeing is that the default value for `encrypt` was changed from `false` to `true` starting after the 9.4.0 release. Considering the two are linked, could this be a source of your issues? Please see our MS Docs page on ["Understanding encryption support"](https://learn.microsoft.com/en-us/sql/connect/jdbc/understanding-ssl-support?view=sql-server-ver15) for more information on these parameters and their changes.
