### ISSUE TITLE
Reconnection issue with `lockTimeout` configured

### ISSUE THREAD

**Issue by Jeffery-Wasty** [microsoft/mssql-jdbc#2438]
As reported in https://github.com/microsoft/mssql-jdbc/issues/2353, when a reconnection is triggered while lockTimeout is configured this can lead to a case where the TDSCommand iCounter is null. In #2253 this created a NullPointerException which was subsquently fixed for 12.7.0, but the underlying reconnection issue remains. It is thought this is related to our other retry/reconnection issues and so work needs to conclude on rewriting the underlying retry logic first before tackling an edge case such as this one.

**Comment by Jeffery-Wasty** [comment]
We will provide updates on the reconnection issue in this GitHub thread.

**Comment by HeinzHuberRsg** [comment]
Our connection settings (from openliberty):
```
        <properties.microsoft.sqlserver
                serverName="${DATASOURCE_DRBQUERJOURNAL_HOSTNAME}"
                portNumber="${DATASOURCE_DRBQUERJOURNAL_PORT}"
                databaseName="${DATASOURCE_DRBQUERJOURNAL_DATABASE}"
                user="${DATASOURCE_DRBQUERJOURNAL_USERNAME}"
                password="${DATASOURCE_DRBQUERJOURNAL_PASSWORD}"
                encrypt="true"
                applicationIntent="readwrite"
                trustServerCertificate="true"
                multiSubnetFailover="true"
                transparentNetworkIPResolution="true"
                lockTimeout="240s"
                serverPreparedStatementDiscardThreshold="10"
                disableStatementPooling="false"
                statementPoolingCacheSize="10"
        />

```

**Comment by Jeffery-Wasty** [comment]
Hi @HeinzHuberRsg,

Do you have the repro mentioned in https://github.com/microsoft/mssql-jdbc/issues/2353? 

![image](https://github.com/user-attachments/assets/8fab7d15-21a7-40f8-b5a8-987b48945a54)

I'm not able to see the above referenced case (I'm guessing its closed). I am working on the reconnection changes at the moment, but am not able to reproduce the above issue.

**Comment by Jeffery-Wasty** [comment]
Still not able to repro this, but a solution would be adding the error to the list of custom list of errors to retry on, aka Configurable Retry Logic. I'll post a link to the PR and Wiki link (both once created) for more information.
