### ISSUE TITLE
Extra metadata lookup for stored procedures with named parameters

### ISSUE THREAD

**Issue by ajlam** [microsoft/mssql-jdbc#244]
When calling a stored procedure with named parameters, the driver does an extra metadata lookup query per each invocation of the stored procedure call. The jTDS driver does not do any metadata lookup, even if parameters are set by name. 

Also in case of Stored Procedure Call Stored Procedure directly without calling `sp_executesql` Ref #263

**Comment by v-nisidh** [comment]
@ferozed,  @icecrystal23, @xsuoownit , @chrismcbride76 I opened #263 Pull Request in order to fix this issue. Your suggestions are welcome.

**Comment by ajlam** [comment]
@gordthompson, @brettwooldridge, @marschall, @sehrope - would appreciate your thoughts on PR #263 as well.

**Comment by TobiasSQL** [comment]
As an FYI I started looking into calling the proc directly over TDS-RPC. @v-nisidh, are you already working on this?

**Comment by v-afrafi** [comment]
I created pr #547 to address the issue with calling stored procedures directly. I would appreciate getting reviews and feedback on that.  

Notice that this still does not have the push for avoiding the metadata lookup with named params. Will be adding that soon to the same pr in another commit.

**Comment by jd-18723** [comment]
Would be really nice to see this released! :)
