### ISSUE TITLE
Mark a (former "stable") release as unstable.

### ISSUE THREAD

**Issue by JDBC-0** [microsoft/mssql-jdbc#2460]
E.g. V 12.6.2 has explizit problems (connection errors in some situations) - that did not occur in the previous and the next versions. But 12.6.2 is still labeled as "stable release". 

An older version should be marked as "deffective" (instead of stable) if it is known to introduce new bugs (that were fixed in later versions).

**Comment by barryw-mssql** [comment]
Thank you for you feedback. We have since released the JDBC 12.6.3 hotfix to address those issues.
