### ISSUE TITLE
JDBC 12.8.0 Introduced a memory leak 

### ISSUE THREAD

**Issue by asharovarov** [microsoft/mssql-jdbc#2486]
## Driver version
12.8.0

## SQL Server version
Microsoft SQL Azure (RTM) - 12.0.2000.8   Jul  3 2024 15:47:16   Copyright (C) 2022 Microsoft Corporation 

## Client Operating System
Container on Debian GNU/Linux 10. Kernel: 5.15.148.2-2.cm2 

## JAVA/JVM version
Java 11

## Problem description
After upgrade from JDBC 12.4.1 to 12.8.0 started seeing continuous `java.lang.OutOfMemoryError: Java heap space`. Application memory grows continuously until the app crashes. Comparing memory dumps showed that the app accumulated 48K of SQLServerCallableStatements in 10 mins and doesn't release them.  

The app uses connection pooling. Here is the method that creates connection:
```
    public SQLServerConnection create()
    {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            SQLServerConnection sqlServerConnection = (SQLServerConnection) DriverManager.getConnection(url);
            sqlServerConnection.setStatementPoolingCacheSize(50);
            sqlServerConnection.setDisableStatementPooling(false);
            sqlServerConnection.setServerPreparedStatementDiscardThreshold(20);
            return sqlServerConnection;
        }
        catch (SQLException | ClassNotFoundException e) {
            logger.error("Exception creating a connection. Error={}", e.getMessage(), e);
            return null;
        }
    }

```
 Sample code that uses the connection:
```
    public void write(SomeData data) {
        SQLServerConnection sqlServerConnection = getConnection();

         SQLServerPreparedStatement preparedStatement = connection.prepareStatement("{call "+repositoryConfig.getProcName()+"(?,?,?,?)}");

        if (preparedStatement != null) {
            try {
                preparedStatement.setDate(1, Date.valueOf(LocalDate.ofEpochDay(data.getBusinessDate())));
                preparedStatement.setLong(2, data.getId());
                preparedStatement.setLong(3, data.getValue());
                preparedStatement.execute();
            }
            catch (SQLException e) {
                // Exception handling and logging
            }
            finally {
                returnConnection(sqlServerConnection);
            }
        }
    }
 ```

## Expected behavior
The SQLServerCallableStatements pool should not grown uncontrollably 
## Actual behavior
SQLServerCallableStatements pool grows until application crashes with OOM.

**Comment by asharovarov** [comment]
Looks like an issue with the `reconnectListeners`
![MemoryDump](https://github.com/user-attachments/assets/f8d06b5e-72ab-48be-8c6d-03717808b70e)

**Comment by Jeffery-Wasty** [comment]
Hi @asharovarov,

We're working on reproducing this issue, how easy is it to reproduce on your end? I believe the issue may be due to the introduction of "flexible callable statements" in 12.5.0. If possible, would you be able to test the following 2 versions of the driver:

* 12.5.0 - https://github.com/microsoft/mssql-jdbc/releases/tag/v12.5.0 - This should have the memory leak
* 12.5.0 w/ the above feature removed - [without.flex.calls.zip](https://github.com/user-attachments/files/16564177/without.flex.calls.zip) - This should NOT have a memory leak

If you are able to test these, it would really help us out! If not, no worries, we'll reproduce and test this on our end, but a resolution may take longer as there are existing issues that the team is working on at the moment.

**Comment by tkyc** [comment]
It doesn't look like the pstmt is being closed. Add a `preparedStatement.close();` or use a try-with-resources.

**Comment by lilgreenbird** [comment]
hi @asharovarov 

the pstmt should always be closed you would eventually run into issues anyway but 12.8.0 did add the reconnectListeners so it revealed the issue more. If you use it with try-with-resources as suggested above things will be closed and cleaned up properly. Thanks.

**Comment by asharovarov** [comment]
The code was written, but someone else, and was working fine until the JDBC update. I have modified it to use try-with-resources and no memory leak anymore.

Thank you for the help!

**Comment by davidfrankson** [comment]
Did your returnConnection() method call a connection.close()  If so, then doesn't the JDBC spec dictate that the statements should be cleaned up automatically?
