### ISSUE TITLE
Feature support: Multiple Active Result Sets (MARS)?

### ISSUE THREAD

**Issue by ajlam** [Microsoft/mssql-jdbc#249]
We have been prioritizing new feature support for [Multiple Active Result Sets (MARS)](https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-multiple-active-result-sets-mars) against support for SQL Variant data type and idle connection resiliency. Before getting too far ahead of ourselves with investigation and prioritization, we wanted to understand if there are any workloads/scenarios that could benefit from this feature and if there is an existing need for this support.

MARS is currently supported in [ADO.NET SqlClient](https://msdn.microsoft.com/en-us/library/h32h3abf(v=vs.110).aspx) and [ODBC ](https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-multiple-active-result-sets-mars#sql-server-native-client-odbc-driver) drivers for SQL Server.

**Comment by brettwooldridge** [comment]
My intuition is that MARS is much more important in the JDBC landscape.

**Comment by ajlam** [comment]
Deprioritizing MARS for now as we work on bug fixes for reported issues.

**Comment by UC4Guru** [comment]
on https://www.connectionstrings.com/sql-server/ every client provided by microsoft supports MARS with 

- MultipleActiveResultSets=true;
- MARS_Connection=yes;

our product moves more and more functionality from c++ to java - and our application has apx. a 20% better performance - if the connection is made with MARS - so this connection (url) option would be needed for JDBC as well to sub stain the same performance with the new stack.

thanks
holli

**Comment by Jeffery-Wasty** [comment]
I have asked the JDBC team about this. There are no plans to support MARS.
