### ISSUE TITLE
Bump to version 12.6 causing error code [8162]

### ISSUE THREAD

**Issue by filipa00silva** [microsoft/mssql-jdbc#2496]
## Driver version
12.8.0.jre11

## SQL Server version
Microsoft SQL Server 2019 (RTM-CU25) (KB5033688) - 15.0.4355.3 (X64) 
	Jan 30 2024 17:02:22 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor)

## Client Operating System
MacOs Sonoma 14.6.1

## JAVA/JVM version
openjdk-17.0.1

## Table schema
```
CREATE or alter PROCEDURE dbo.GetSomthingSp (
         @Arg1 VARCHAR(5),
	@Arg2 VARCHAR(2) OUTPUT,
	@Arg3 BIT OUTPUT,
	@Arg4 VARCHAR(255) = NULL,
	@Arg5 VARCHAR(255) = NULL OUTPUT,
	@Arg6 VARCHAR(255) = NULL OUTPUT
)
AS
    SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
    SET NOCOUNT ON
    SET XACT_ABORT ON

SELECT
	@Arg1 = t1.something,
	@Arg3 = t1.somethingElse,
	@Arg5 = t1.somethingSomething,
	@Arg6 = t2.somethingSomethingElse
FROM Database.dbo.whatever t1

BEGIN
	SET @Arg3 = CASE WHEN EXISTS (SELECT * FROM blahblah)
                THEN 1
		ELSE 0
	END
END
go
``` 

## Problem description
Our project has been using the driver version 10.2.0.jre17, but we decided to bump to 12.6.2.jre11. There were no code changes. Now when we try to call some stored procedures on the database, we get the following error:

```CallableStatementCallback; uncategorized SQLException for SQL [{call Database.dbo.GetSomthingSp(@Arg1 = ?, @Arg4 = ?, @Arg2 = ?, @Arg3 = ?, @Arg5 = ?, @Arg6 = ?)}]; SQL state [S0002]; error code [8162]; The formal parameter "@Arg4" was not declared as an OUTPUT parameter, but the actual parameter passed in requested output.```

I would like to understand how can I tackle this. Is this expected behaviour? Is there something we're missing in our configuration? We've tried several versions of the driver, namely 12.4.2.jre11 where this issue doesn't occur.
What exactly changed from version 12.4.2.jre11  to version 12.6.2.jre11 that creates this problem? 
We also tried rearranging the code I will add below so that the order of the parameters in the constructor matches de order of parameters in the SP and the issue is fixed. We didn't want to do this, because we would have to change a lot of things in our code base and it seems odd that it has been working correctly and only now this change is required. 
Besides, since we're providing the name of the parameters as far as I know the order shouldn't matter, am I missing something?

## Error message/stack trace
``` 
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The formal parameter "@Arg4" was not declared as an OUTPUT parameter, but the actual parameter passed in requested output.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:270)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1778)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:703)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:622)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7775)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4408)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:293)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:263)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:599)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyCallableStatement.execute(HikariProxyCallableStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$call$5(JdbcTemplate.java:1223)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:1164)
	... 163 common frames omitted
```

## Any other details that can be helpful
I tried using jdbc version 12.4.2.jre11 and the call is successful, I also tried setting `useFlexibleCallableStatements` to `false`, but it didn't change anything. 

Our java code that prepares the parameters for the SimpleJdbcCall looks like this
```
public class GetSomthingSp extends AbstractProcedure<Optional<Obj>, Void> {

    private static final String PROCEDURE_NAME = "Database.dbo.GetSomthingSp";

    private static final String ARG1 = "@Arg1";
    private static final String ARG4 = "@Arg4";

    private static final String ARG2 = "@Arg2";
    private static final String ARG3 = "@Arg3";
    private static final String ARG5 = "@Arg5";
    private static final String ARG6 = "@Arg6";

    private String arg1;
    private String arg4;

    public GetSomthingSp(String arg1, String arg4) {
        super(PROCEDURE_NAME,
              new SqlParameter[]{
                      new SqlParameter(ARG1, Types.VARCHAR),
                      new SqlParameter(ARG4, Types.VARCHAR),
                      new SqlOutParameter(ARG2, Types.VARCHAR),
                      new SqlOutParameter(ARG3, Types.TINYINT),
                      new SqlOutParameter(ARG5, Types.VARCHAR),
                      new SqlOutParameter(ARG6, Types.VARCHAR)
              }, false);

        this.arg1 = arg1;
        this.arg4 = arg4;
    }

    @Override
    protected SqlParameterSource getParameterMap() {
        return new MapSqlParameterSource()
                .addValue(ARG1, this.arg1)
                .addValue(ARG4, this.arg4);
    }
    ....
}
```

Thanks in advance, hope you guys can help me out 🤗

**Comment by tkyc** [comment]
@filipa00silva 

Could you test out version 12.5.0 and 12.4.2 and let me know if the issue occurs on these version?

**Comment by filipa00silva** [comment]
@tkyc With versions 12.8.1 and 12.4.2 the issue doesn't occur. I guess I'll just use the latest one then, thanks :D

**Comment by Jeffery-Wasty** [comment]
Looks like this issue was related to the 'flexible callable statements' feature, which has since been backed out in 12.8.1. Closing issue.
