### ISSUE TITLE
[QUESTION] 'Login failed for user' when using AD credentials

### ISSUE THREAD

**Issue by rnv812** [microsoft/mssql-jdbc#2512]
## Question

We use `mssql-jdbc-12.6.4` in Logstash to connect to MSSQL database, but we are facing authentication problem: `Login failed for user 'domian\username'.` 

Here is the traceback:
<img width="952" alt="error preview" src="https://github.com/user-attachments/assets/bdd7cfc8-4ad2-4e1d-a3c1-2f6872be4f7b">

Configuration with jdbc connection string:
```
input {
    jdbc {
        jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"
        jdbc_driver_library => "/app/logstash/utils/jdbc/mssql-jdbc-12.6.4.jre11.jar"
        jdbc_connection_string => "jdbc:sqlserver://***:1433;databaseName=***;user=***\***;password=***;encrypt=true;trustServerCertificate=true;loginTimeout=30;"
        jdbc_user => "***"
        jdbc_password => "***"
        statement => "SELECT 1"
    }
}
```

We specify username in format `<domain>\<username>`.

We tried to connect to DB using [`sqlcmd`](https://learn.microsoft.com/en-us/sql/tools/sqlcmd/sqlcmd-utility?view=sql-server-ver16&tabs=go%2Cwindows&pivots=cs1-bash) util with the same parameters and **authentication was successful**:

```bash
sqlcmd -C -S "***:1433" -d "***" -U "***\***" -Q "SELECT 1"
```

```
Password: 

------------
           1
(1 row affected)
```

Do you have any idea why authentication fails in case of using driver?

Thank you.

**Comment by tkyc** [comment]
You'll need to use `integratedSecurity=true`, to login with the Windows account. And so, you'll need to logon to Windows using your domain user. Then you should supply a connection string that looks like the one below without the user/password.

`jdbc:sqlserver://***:1433;databaseName=***;encrypt=true;trustServerCertificate=true;loginTimeout=30;integratedSecurity=true;`.

OR you can also do the following below in your connection string to use your AD user to login. The connection string below uses `NTLM` and `integratedSecurity=true`:

`jdbc:sqlserver://my-sql-server.mydomain.ad;integratedSecurity=true;authenticationScheme=NTLM;domain=mydomain.ad;user=domainUser;password=domainUserPassword;encrypt=false;trustServerCertificate=true;`

**Comment by rnv812** [comment]
Thank you for you answer. I tried your examples and in both cases behavior was the same: Message about failed logon is gone, but nothing happened then. After about 10 minutes of hanging I can see that "Connection reset by peer":  
![traceback](https://github.com/user-attachments/assets/1a895a5c-c5bc-471d-a075-d03020118bbb)
I also tried with `authenticationScheme=JavaKerberos` and result was the same.

I'm on linux and I have ticket granting ticket for user in `klist`. Domain controller port 88 (used for kerberos) is reachable as well as database port 1433.

Cannot really got why `sqlcmd` authenticates successfully (just providing to it user and password), but driver does not.

**Comment by tkyc** [comment]
Could you grab me the SQL Server logs?

Also, just curious, does a basic SQL authentication work with the driver?

https://learn.microsoft.com/en-us/sql/relational-databases/performance/view-the-sql-server-error-log-sql-server-management-studio?view=sql-server-ver16

**Comment by rnv812** [comment]
With basic SQL Authentication I got "Login failed for user '<username>' ". Actually SQL Server belongs to customer, not us, but I'll try to ask them to provide the logs. Thank you for instruction.

**Comment by rnv812** [comment]
While I'm waiting for the logs, I checked what network connections are established for the process that uses driver to figure out the reason of 10 minutes hanging. Using `netstat -tupn | grep <PID>` I can see that for the first ~ 1-2 minutes  it is connected to database to port `1433` and during all 10 minutes of hanging process has connection to domain controller / dns servers (it periodically changes) to port `53` using `udp`.

Port `53` of DC and DNS servers are all reachable (checked it with  `telnet <server> <port>`).

What it could be?

Tried with next jdbc string: `jdbc:sqlserver://<ip>:1433;integratedSecurity=true;authenticationScheme=NTLM;domain=<mydomain>;user=<domainUser>;password=<domainUserPassword>;encrypt=false;trustServerCertificate=true;`

**Comment by tkyc** [comment]
For your connection attempts with the domain user, are you still setting the user in the format of `<domain>\<username>` still?

If you are, with the connection string below, try only doing `<username>` without the prepended domain.

`jdbc:sqlserver://<ip>:1433;integratedSecurity=true;authenticationScheme=NTLM;domain=<mydomain>;user=<domainUser>;password=<domainUserPassword>;encrypt=false;trustServerCertificate=true;`

**Comment by rnv812** [comment]
Tried with and without prepended domain. Behavior is the same.

**Comment by tkyc** [comment]
Any news on the server logs?

**Comment by rnv812** [comment]
Here is log entries:
```log
09/25/2024 11:07:02,Logon,Unknown,Login failed. The login is from an untrusted domain and cannot be used with Integrated authentication. [CLIENT: xx.xx.xx.xx]
09/25/2024 11:07:02,Logon,Unknown,SSPI handshake failed with error code 0x80090302<c/> state 14 while establishing a connection with integrated security; the connection has been closed. Reason: AcceptSecurityContext failed. The operating system error code indicates the cause of failure. The function requested is not supported   [CLIENT: xx.xx.xx.xx]

```

**Comment by tkyc** [comment]
I was expecting a different error, because you were able to auth through sqlcmd and you mentioned you also had a successful `klist`.

Can you confirm again if your machine is properly domain joined (through some alternative command)? I'm guessing you already doubled checked further for domain problems after that log error message.

**Comment by rnv812** [comment]
Yeah, checked this using `kinit` with same credentials and got TGT successfully. Do you have an idea how can I check it especially for NTLM authentication scheme?

Also I tried to grant all related permissions to JVM in security policy:
```
grant {
    // Permissions to access network resources
    permission java.net.SocketPermission "*", "connect,resolve";
    permission java.net.SocketPermission "*", "connect,resolve";
    
    // Permissions for NTLM or Kerberos authentication
    permission javax.security.auth.AuthPermission "doAs";
    permission javax.security.auth.AuthPermission "doAsPrivileged";
    permission javax.security.auth.kerberos.ServicePermission "*", "initiate";
};
```
This didn't help.

**Comment by tkyc** [comment]
> Do you have an idea how can I check it especially for NTLM authentication scheme?

No, I believe there isn't a way to check for that other than making a connection.

I'm wondering if it's a SPN issue. It shouldn't be because you're able to get TGT. Do you see the following in the SQL Server logs?

`The SQL Server Network Interface library successfully registered the Service Principal Name (SPN)`

OR

`The SQL Server Network Interface library could not register the Service Principal Name (SPN)`

We want it to say `successfully registered the Service Principal Name (SPN)`.

**Comment by rnv812** [comment]
Ok. Thank you. I asked customers about this messages.

**Comment by rnv812** [comment]
Due to long delays in responses from the customer, I suggest to close this issue until new information comes from my side. Thank you for your assistance!

**Comment by rnv812** [comment]
Hi, here is message from logs:
```
The SQL Server Network Interface library could not register the Service Principal Name (SPN) [ MSSQLSvc/SetverName:1433 ] for the SQL Server service. Windows return code: 0x200b, state: 15. Failure to register a SPN might cause integrated authentication to use NTLM instead of Kerberos. This is an informational message. Further action is only required if Kerberos authentication is required by authentication policies and if the SPN has not been manually registered.
```

**Comment by lilgreenbird** [comment]
hi @rnv812 

Based on the error above it looks like @tkyc was right it's an issue with the SPN. Please make sure to register the SPN and verify in the logs that this was done successfully. . Then you will need to specify the SPN using the `serverSpn` connection property. Please see [Setting the connection properties](https://learn.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver16) for a description of the property. 

I would suggest using a standalone java app to test the connection here is an [example](https://learn.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver16) of how to do that using NTLM.
