### ISSUE TITLE
Driver cuts out the question mark from columns labels (aliases)

### ISSUE THREAD

**Issue by DmitriyGod** [microsoft/mssql-jdbc#2535]
## Driver version
latest

## SQL Server version
mcr.microsoft.com/mssql/server:2022-latest
## Client Operating System
any

## JAVA/JVM version
any
## Table schema
no

## Problem description
Driver cuts out the question mark from columns labels (aliases):
```Java
var stmt = connection.prepareStatement(
    """
        select 1 as "any questions ???"
        """);

var metaData = stmt.getMetaData();
var actual = metaData.getColumnLabel(1);
var expected = "any questions ???";

Assertions.assertEquals(expected, actual);
```
out:
Expected :any questions ???
Actual   :any questions nullnullnull

## Expected behavior
Driver must keep question marks 
## Actual behavior
Driver cuts out the question mark from columns labels (aliases).
## Error message/stack trace
-
## Any other details that can be helpful
All other drivers keeps question mark in labels. 

## JDBC trace logs
-

**Comment by machavan** [comment]
Adding a stmt.executeQuery post prapreStatement makes it bring the column labels correctly.
```
try (Connection connection = DriverManager.getConnection(url)) {
	try(var stmt = connection.prepareStatement(
		    """
	        select 1 as "any questions ???"
	        """);) {
		

                stmt.executeQuery();
		
                var metaData = stmt.getMetaData();
		var actual = metaData.getColumnName(1);
		var expected = "any questions ???";
		Assertions.assertEquals(expected, actual);				
	}			
}
```

**Comment by DmitriyGod** [comment]
We are developing a security tool that checks query on compile-time via PreparedStatement. We are cannot execute query. Also this is common task — to know query Metadata without execution

**Comment by machavan** [comment]
Sure. Is changing the alias to a name (which does not contain question marks) an option at your end, as a work-around?

**Comment by DmitriyGod** [comment]
Hi! PR looks fine. In which release will the changes be?
