### ISSUE TITLE
[QUESTION] For ActiveDirectoryServicePrinciplaCertificate authentication for azure sql can we pass certificate and key from the keystore??

### ISSUE THREAD

**Issue by muskaan62** [microsoft/mssql-jdbc#2551]
## Question
My use case is to connect to Azuresql using ActiveDirectoryServicePrinciplaCertificate authentication but driver requires both certificate and private key path to pass in connection string.
Instead of path can i put certificate and private key in keystore and pass keystore location or keystore in the connection string??
If yes, do we have any reference?

**Comment by divang** [comment]
If you have not gone through below docs, please have a look: 
https://learn.microsoft.com/en-us/sql/relational-databases/security/authentication-access/azure-ad-authentication-sql-server-setup-tutorial?view=sql-server-ver16
https://learn.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver16#connect-using-activedirectoryserviceprincipal-authentication-mode

The **clientCertificate** param is mandatory property in case of ActiveDirectoryServicePrincipalCertificate auth method.
FINE: *** SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: "Both "UserName" and **"clientCertificate" connection string keyword must be specified**, if "Authentication=ActiveDirectoryServicePrincipalCertificate". "Both "UserName" and "clientCertificate" connection string keyword must be specified, if "Authentication=ActiveDirectoryServicePrincipalCertificate".
Nov 29, 2024 1:49:47 PM com.microsoft.sqlserver.jdbc.SQLServerException logException

**Comment by muskaan62** [comment]
Thanks @divang for help here. i know its mandatory i was just curious is there any other way to do that..since driver has requirement to pas the physical path of **clientCertificate** and if there's any other way like pass stream or keystore for this, so that certificate or private key need not be on the same machine i reached out.

**Comment by divang** [comment]
If you want to avoid dealing with certificates and managing their paths, why not consider using Active Directory Managed Identity (ActiveDirectoryManagedIdentity)?
https://learn.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-ver16

Detail setup can be referenced here:
https://techcommunity.microsoft.com/blog/azuredbsupport/using-managed-service-identity-msi-to-authenticate-on-azure-sql-db/1288248

**Comment by muskaan62** [comment]
Thanks @divang our requirement is to have certificate and private key for  authentication.

**Comment by divang** [comment]
@muskaan62 Driver does not support directly specifying a KeyStore in the connection string.
