### ISSUE TITLE
TVP second operation issue with result set

### ISSUE THREAD

**Issue by v-xiangs** [Microsoft/mssql-jdbc#261]
For TVP, if we use the same result set twice, the second operation does nothing: no data is copied and no data is thrown, unless we move the cursor backwards (if possible).

It will be better if we throw exception when result set cursor is in the end.

**Comment by v-suhame** [comment]
\+ if table type used for TVP doesn't exist, then copying from empty ResultSet into TVP doesn't throw exception.

> ResultSet rs = stmt.executeQuery("SELECT * FROM "+srcTable); // rs is empty
> SQLServerPreparedStatement pStmt =(SQLServerPreparedStatement) conn.prepareStatement("INSERT INTO " + tableName + " select * from ? ; ");
> pStmt.setStructured(1, tvp, rs); // use table type that doesn't exist
> pStmt.execute(); // no exception

**Comment by v-xiangs** [comment]
closing this issue since they are expected behaviours.
