### ISSUE TITLE
Supporting Java Platform Module System, a.k.a. Jigsaw

### ISSUE THREAD

**Issue by v-nisidh** [Microsoft/mssql-jdbc#266]
Java Platform Module System, a.k.a. Jigsaw is one of biggest feature of JDK 9.

**Following Tasks need to be analyzed:** 

- [x] Analyze how Jigsaw modular approach impacts JDBC
- [ ] Can we / Should we bundle our driver as module in java eco system? 

**Update: JSR 376: Java Platform Modular System**
EC has not approved 1st Public Review Ballot. [View Result](https://www.jcp.org/en/jsr/results?id=5959)

Will keep you updated...

**Comment by v-nisidh** [comment]
You can find some of updates related to this in #268

**Comment by cheenamalhotra** [comment]
PR #732 merged, closing issue.
