### ISSUE TITLE
Use a redirect URL for survey link in README

### ISSUE THREAD

**Issue by sehrope** [Microsoft/mssql-jdbc#271]
Rather than have the README point to a specific survey it should be pointed at a fixed URL that can be redirected to the latest survey. That would obviate the need for commits / merges to update the survey.

I would imagine that Microsoft has a redirect service for this type of thing already. If not, there are a number of URL shortening services that allow for editing the destination URL.

**Comment by ajlam** [comment]
@sehrope, thanks for the great suggestion. I've created a fixed URL that we'll use from now on: https://aka.ms/mssqljdbcsurvey
