### ISSUE TITLE
Prepared statement execute batch does use the BulkCopy API

### ISSUE THREAD

**Issue by deanchen** [Microsoft/mssql-jdbc#277]
Batching prepared statements does not invoke the BulkCopy API. This causes individual sp_execs for each statement dramatically slowing down large bulk loads.

https://github.com/Microsoft/mssql-jdbc/blob/515724c9a1ca7ce7579432f86ea8479788e15d41/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java#L2258

While one can implement BulkCopy using the BulkCopy interface. External db agnostic systems like Spark and Hadoop integrate directly via JDBC.

**Comment by peterbae** [comment]
Hi @deanchen, thanks for bringing this issue to our attention.

I have a few questions regarding this the interaction between the batch processing with prepared statement and the SQLBulkCopy API:

1. Did you imply that only the INSERT statements would be handled with the SQLBulkCopy API with prepared statement?
2. If so, the prepared statement would accept individual insert SQL queries as its parameter, whereas the SQLBulkCopy API accepts either ResultSets or ISQLServerBulkRecord (from a file) as its parameter. How would we convert SQL queries into either of those formats?
3. Could you elaborate a bit more on the "External db agnostic systems like Spark and Hadoop integrate directly via JDBC."? Do you mean that Spark and Hadoop would have access to batch execute API, but not the SQLBulkCopy API? If so, would the user add multiple INSERT queries for batch process, and expect it to be handled by SQLBulkCopy underneath?

**Comment by peterbae** [comment]
Hi @deanchen, have you had a chance to read my last comment? Thanks for the contribution.

**Comment by cheenamalhotra** [comment]
Hi @deanchen I hope your issue is resolved. Feel free to reopen if you need further assistance.
