### ISSUE TITLE
what's the difference of the website downloaded "sqljdbc42.jar" and "mssql-jdbc-6.1.0.jre8.jar"?

### ISSUE THREAD

**Issue by softboy99** [Microsoft/mssql-jdbc#281]
I'm confused, why two different names? both needed?

**Comment by v-afrafi** [comment]
The naming of our open source previews has changed. The sqljdc41.jar and sqljdbc42.jar correspond to “mssql-jdbc-6.1.x-jre7.jar”  and “mssql-jdbc-6.1.x-jre8.jar” now. 
The website downloaded jars are production release and the "mssql-jdbc-6.1.x" jars are latest preview versions of the driver.

**Comment by v-afrafi** [comment]
Closing this issue. Please feel free to reopen it if you had any other questions.
