### ISSUE TITLE
ResultSet#getObject returns Short for SmallInt and TinyInt instead of Integer

### ISSUE THREAD

**Issue by Arthurm1** [Microsoft/mssql-jdbc#284]
Currently calling `ResultSet#getObject` on a `TinyInt` or `SmallInt` column returns a `Short`.

According to the JDBC spec this should return an `Integer`

http://download.oracle.com/otndocs/jcp/jdbc-4_2-mrel2-spec/index.html
Page 193.  Table B-3

**Comment by v-nisidh** [comment]
@Arthurm1 : We understand that JDBC Specs maintained `TINYINT` and `SMALLINT` mappings for backwards compatibility

We will try to evaluate how it is useful for end users.

Ref: Page 192 Section B.3

> Note – The JDBC 1.0 specification defined the Java object mapping for the
SMALLINT and TINYINT JDBC types to be Integer. The Java language did not
include the Byte and Short data types when the JDBC 1.0 specification was
finalized. The mapping of SMALLINT and TINYINT to Integer is maintained to
preserve backwards compatibility.

**Comment by cheenamalhotra** [comment]
@Arthurm1 We are working towards reviewing the PR #545 created to fix this issue. Appreciate your reviews and feedback for the same as well.

**Comment by cheenamalhotra** [comment]
Hi @Arthurm1 

We investigated support for `ResultSet.getObject()` APIs to return `Integer` types for `SMALLINT` and `TINYINT` but as the returned object is of small precision (Short/Byte), it can always be converted to `Integer` by end user applications and hence does not cause any breaking changes for client applications.

We are closing this issue as we don't find this backward supportability useful.
