### ISSUE TITLE
java.lang.VerifyError: Bad type on operand stack

### ISSUE THREAD

**Issue by mayong1030** [Microsoft/mssql-jdbc#295]
I refer this URL to do. But I found one error.
https://msdn.microsoft.com/en-us/library/mt591987(v=sql.1).aspx
----------------------------------java----------------------------------------
private static void setAzureKeyVaultProvider(){
		ExecutorService service = Executors.newFixedThreadPool(10);
		SQLServerKeyVaultAuthenticationCallback authenticationCallback = new SQLServerKeyVaultAuthenticationCallback() {  
		       @Override  
		    public String getAccessToken(String authority, String resource, String scope) {  
		    	   
		        AuthenticationResult result = null;  
		        try{  
		                AuthenticationContext context = new AuthenticationContext(authority, false, service);  
		            ClientCredential cred = new ClientCredential("XX", "XX");
		             
		  
		            Future<AuthenticationResult> future = context.acquireToken(resource, cred, null);  
		            result = future.get();  
		        }  
		        catch(Exception e){  
		            e.printStackTrace();  
		        }  
		        return result.getAccessToken();  
		    }  
		};  
		
		try {
			SQLServerColumnEncryptionAzureKeyVaultProvider akvProvider = new SQLServerColumnEncryptionAzureKeyVaultProvider(authenticationCallback, service);
		} catch (SQLServerException e) {
			logger.error("setAzureKeyVaultProvider error:"+e.getStackTrace());
		} 
	}

Exception in thread "restartedMain" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionAzureKeyVaultProvider.<init>(Lcom/microsoft/sqlserver/jdbc/SQLServerKeyVaultAuthenticationCallback;Ljava/util/concurrent/ExecutorService;)V @104: invokespecial
  Reason:
    Type 'com/microsoft/sqlserver/jdbc/**KeyVaultCredential'** (current frame, stack[5]) is not assignable to 'com/microsoft/windowsazure/credentials/**CloudCredentials'**
  Current Frame:
    bci: @104
    flags: { }
    locals: { 'com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionAzureKeyVaultProvider', 'com/microsoft/sqlserver/jdbc/SQLServerKeyVaultAuthenticationCallback', 'java/util/concurrent/ExecutorService', 'org/apache/http/impl/client/HttpClientBuilder' }
    stack: { 'com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionAzureKeyVaultProvider', uninitialized 94, uninitialized 94, 'org/apache/http/impl/client/HttpClientBuilder', 'java/util/concurrent/ExecutorService', 'com/microsoft/sqlserver/jdbc/KeyVaultCredential' }
  Bytecode:
    0x0000000: 2ab7 0002 2a12 03b5 0001 2a12 04b5 0005
    0x0000010: 2a12 06b5 0007 2a04 bc08 5903 0454 b500
    0x0000020: 0801 2ba6 002a bb00 0959 120a b800 0bb7
    0x0000030: 000c 4e04 bd00 0d59 0312 0e53 3a04 bb00
    0x0000040: 0f59 2d19 04b6 0010 01b7 0011 bf2a bb00
    0x0000050: 1259 2bb7 0013 b500 14b8 0015 4e2a bb00
    0x0000060: 1659 2d2c 2ab4 0014 b700 17b5 0018 b1  
  Stackmap Table:
    full_frame(@77,{Object[#153],Object[#154],Object[#155]},{})

	at com.contract.ContractApplication.setAzureKeyVaultProvider(ContractApplication.java:56)
	at com.contract.ContractApplication.main(ContractApplication.java:30)
	... 5 more

---------------------------------------pom.xml------------------------------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.contract</groupId>
	<artifactId>contract</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>war</packaging>

	<name>contract</name>
	<description>Demo project for Spring Boot</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.2.RELEASE</version>
		<relativePath /> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>

		<dependency>
			<groupId>com.microsoft.sqlserver</groupId>
			<artifactId>mssql-jdbc</artifactId>
			<version>6.1.0.jre8</version>
			

		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>org.jdom</groupId>
			<artifactId>jdom2</artifactId>
		</dependency>
		<dependency>
			<groupId>joda-time</groupId>
			<artifactId>joda-time</artifactId>
		</dependency>
		
		
		<dependency>
			<groupId>org.springframework.session</groupId>
			<artifactId>spring-session-jdbc</artifactId>
			<version>1.3.1.RELEASE</version>
			<type>pom</type>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web</artifactId>
		</dependency>
		
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-log4j12</artifactId>
				</exclusion>
				<exclusion>
					<groupId>log4j</groupId>
					<artifactId>log4j</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security.extensions</groupId>
			<artifactId>spring-security-saml2-core</artifactId>
			<version>1.0.2.RELEASE</version>
		</dependency>
		
		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		

		
		
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-storage</artifactId>
			<version>5.0.0</version>
		</dependency>
		
		
		
		
		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.json</artifactId>
			<version>1.1.0-M2</version>
		</dependency>

		
		
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-keyvault</artifactId>
			<version>1.0.0</version>
		</dependency>
		
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-keyvault-core</artifactId>
			<version>1.0.0</version>
		</dependency>
		
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-keyvault-webkey</artifactId>
			<version>1.0.0</version>
		</dependency>

		
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-core</artifactId>
			<version>0.9.7</version>
		</dependency>
		
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure</artifactId>
			<version>1.0.0</version>
		</dependency>

		<dependency>
			<groupId>javax.json</groupId>
			<artifactId>javax.json-api</artifactId>
			<version>1.0</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<optional>true</optional>
			<scope>true</scope>
		</dependency>
		
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-mgmt-resources</artifactId>
			<version>1.0.0</version>

		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<fork>true</fork>
				</configuration>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-war-plugin</artifactId>
					<configuration>
						<includeEmptyDirectories>true</includeEmptyDirectories>
						<warName>contract</warName>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
	</build>
	<profiles>
		<profile>
			<id>dev2</id>
			<properties>
				<activatedProperties>dev2</activatedProperties>
			</properties>
		</profile>
		<profile>
			<id>stg</id>
			<properties>
				<activatedProperties>stg</activatedProperties>
			</properties>
		</profile>
		<profile>
			<id>prod</id>
			<properties>
				<activatedProperties>prod</activatedProperties>
			</properties>
		</profile>
	</profiles>

</project>

-----------------------------------------------------------------------------------------------------------------

**Comment by mayong1030** [comment]
I changed version to 0.9.7,  The issue is close.
<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-keyvault</artifactId>
			<version>**0.9.7**</version>
		</dependency>

**Comment by v-nisidh** [comment]
@mayong1030 : Closing this issue as per your comments.
