### ISSUE TITLE
SQLServerBulkCSVFileRecord should accept an InputStream as one of the constructor overloads

### ISSUE THREAD

**Issue by ferozed** [Microsoft/mssql-jdbc#311]
SQLServerBulkCSVFileRecord takes a path to a file on the local filesystem. This works fine when you are doing a bulk upload of a local file. However, this is problematic if the file exists in a remote filesystem, for eg, S3 or HDFS. In that case, we have to copy the file locally, then upload it. Yes, there is the interface, but implementing it requires implementing 95% of what the SQLServerBulkCSVFileRecord class provides out of the box (handling metadata, and parsing input from stream according to that metadata).

All this will be solved if there was an overload available that took an InputStream.

Also, since some of this code will be needed by implementers of the interface, it should be put in a common utility class so that it can be leveraged. I am specifically talking about  the follwoing methods:

SQLServerBulkCSVFileRecord:addColumnMetadataInternal()
SQLServerBulkCSVFileRecord:getRowData()

**Comment by v-afrafi** [comment]
Hi @ferozed. Just tested using Azure file services. We are able to bulkcopy from csv in remote filesystem. Can you specify what problems you face using S3 or HDFS for instance? Do you get any error messages?

**Comment by v-afrafi** [comment]
@ferozed just wanted to confirm that you are correct. Right now, the driver fails to load a csv file providing a url to the csv. Thanks for filling out this issue. We will mark it as enhancement.

**Comment by v-afrafi** [comment]
Hi @ferozed. Could you try testing #318 and see if this is fixing your issue with a file on the remote filesystem? Thanks.

**Comment by v-afrafi** [comment]
Hi @ferozed . Do you have any updates on pr #318 and if that helped you with your issue with a file on remote filesystem?
Also, could you open another issue for the second part of your question? This way we can track it down easier. Thanks! :)

**Comment by v-afrafi** [comment]
Fixed by pr #318 . Thanks @ferozed for testing it.
