### ISSUE TITLE
Possible bug in marshalling JSON

### ISSUE THREAD

**Issue by benjamin-bader** [Microsoft/mssql-jdbc#312]
It's not clear from MSDN docs, but I'm wondering if the JDBC driver might be incorrectly marshalling empty JSON data as null?

In a select query, I have a subquery that is essentially aggregating a one-to-many relation into a JSON array - for (a very simple) example:

```sql
-- assume tables x and y, which have a 1->many relationship
SELECT x.id,
       (SELECT y.a, y.b, y.c
        FROM y
        WHERE y.x_id = x.id
        FOR JSON PATH, INCLUDE_NULL_VALUES)
FROM x
```

In Java, I'm reading this from a `ResultSet` as:
```java
ResultSet rs = ...;
String id = rs.getString(1); // x.id
String json = rs.getString(2); // the JSON result
```

This works fine when the subquery returns at least one row.  When it doesn't, the call to `rs.getString(2)` returns `null`.  This is surprising to me; I'd expect that an empty JSON list would be rendered as `"[]"`.  Is this correct behavior?

**Comment by v-suhame** [comment]
@benjamin-bader If you run the T-SQL directly in SSMS, you will notice it returns `NULL` and not an empty JSON. As null bitmap compression is in place for >= SQL Server 2008 R2, the response received from SQL Server has no data corresponding to the null column value of a row, so `rs.getString(2)` returns `null`. 

It is correct behavior, driver displays whatever it receives from Server.

Thanks!

**Comment by benjamin-bader** [comment]
Got it, thanks!

**Comment by nsidhaye** [comment]
@benjamin-bader Thanks for closing but it might be worth to test it without `INCLUDE_NULL_VALUES` option? 

As per my understanding you are using JSON functionality of SQL Server with `INCLUDE_NULL_VALUES`. Specifying [INCLUDE_NULL_VALUES](https://docs.microsoft.com/en-us/sql/relational-databases/json/include-null-values-in-json-include-null-values-option) option will add `null` value in JSON output.

**Comment by benjamin-bader** [comment]
@nsidhaye that's a good point, I haven't yet tested without that option.  Per my understanding, it _shouldn't_ have an effect on the output if no rows match the subquery.  I'll test it out tomorrow, and if there's a difference, I'll let you know - otherwise, I'll keep this one closed.  Thanks!

**Comment by v-suhame** [comment]
`INCLUDE_NULL_VALUES` affects the properties **inside** JSON. So yes, it wouldn't impact the output if no rows match the subquery.
