### ISSUE TITLE
Support For Batch or Bulk Inserts to Azure SQL Data Warehouse (SQLDW)

### ISSUE THREAD

**Issue by rblevi01** [Microsoft/mssql-jdbc#331]
Microsoft support recommended this driver for connecting to Azure SQL Data Warehouse (not Azure SQL Database).  It works however inserts are very slow at 13 rows per second.  I happen to be using DataStage.  Same issue is reported by Talend users.  Is this driver designed to work with Azure SQL Data Warehouse?  If so, what configuration will cause it to use Batch or Bulk inserts?  Note that my same system and configuration when pointing to Azure SQL Database inserts 10,000 rows per second.  Looking at the data sent to Data Warehouse, it appears single row inserts are sent to Data Warehouse and a Batch is sent to Database.

**Comment by v-nisidh** [comment]
Thanks @rblevi01, 

We are working on this. 

Meanwhile can you verify if [BulkCopy option](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-bulk-copy-with-the-jdbc-driver) is suitable for your case?

**Comment by ajlam** [comment]
@rblevi01 - out of curiosity, have you tried [PolyBase](https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-guide)? This is the recommended way of loading data into Azure SQL Data Warehouse.

**Comment by ajlam** [comment]
@rblevi01, have you been able to try out PolyBase for data loading?

**Comment by cheenamalhotra** [comment]
Closing the issue due to inactivity.

**Comment by ikoblik** [comment]
@cheenamalhotra , @ajlam I noticed that this bug was closed due to inactivity, but was the originally reported issue fixed? Does MSSQL JDBC driver now support Batch updates when interacting with Data Warehouse. My team experiences similar issues, no mattar how many clients we cannot insert more than 10 records to DW.

**Comment by cheenamalhotra** [comment]
Hi @ikoblik - We closed the issue as we were of the view using Polybase might have resolved customer's issue as there was no response from customer. 

I am reopening this thread as I do see many customers facing similar issue - we will investigate on providing support for better performance/Bulk Copy options.

**Comment by ajilius** [comment]
The bulk copy API performs much better than 5-10 rows per second. I regularly load to ASDW using this JDBC driver API, and 40megabytes per second - row counts depend on data content, but will be in the hundreds of thousands - are achievable. Of course, the recommendation to use Polybase will improve this by 1-2 orders of magnitude.

**Comment by peterbae** [comment]
The implementation is underway, and a PR that implements bulk copy API for batch inserts against Azure SQL DW will be made soon.

**Comment by sadikovi** [comment]
Is there any progress of this issue? I am experiencing the same problem when trying to perform bulk insert using JDBC. Polybase has just too much overhead for my use case.

**Comment by peterbae** [comment]
Fixed in #686. Wiki for this feature can be found here: https://github.com/Microsoft/mssql-jdbc/wiki/How-to-enable-Bulk-Copy-API-for-batch-insert-operations

Closing the issue.

**Comment by nagarc1** [comment]
> Microsoft support recommended this driver for connecting to Azure SQL Data Warehouse (not Azure SQL Database). It works however inserts are very slow at 13 rows per second. I happen to be using DataStage. Same issue is reported by Talend users. Is this driver designed to work with Azure SQL Data Warehouse? If so, what configuration will cause it to use Batch or Bulk inserts? Note that my same system and configuration when pointing to Azure SQL Database inserts 10,000 rows per second. Looking at the data sent to Data Warehouse, it appears single row inserts are sent to Data Warehouse and a Batch is sent to Database.

Can you please tell me the configuration needed for Data stage to Azure SQL database ( Not Data warehouse)

**Comment by nagarc1** [comment]
@peterbae Can we use Datastage to load data into Azure SQL database. can you share instructions? any doc?

**Comment by peterbae** [comment]
Hi @nagarc1, I'm not an expert on Datastage, and I haven't tried using that in conjunction with our driver. If anyone has tried using Datastage with our JDBC driver against Azure DB, please let us know!
