### ISSUE TITLE
Errors in getParameterMetaData() when non-space characters in query

### ISSUE THREAD

**Issue by chadberchek** [Microsoft/mssql-jdbc#344]
I discovered a variety of scenarios where `PreparedStatement.getParameterMetaData()` either throws an exception or returns an incorrect parameter count in a subsequent call to `getParameterCount()`, all of which appear to be related to the presence or absence of whitespace characters (spaces, newlines, tabs).

Below is a test suite Gist which demonstrates some of the issues. Five of the seven tests fail for me (the other two are just to demonstrate that the errors are only due to whitespace differences). Note that each test first executes the statement to prove that the statement really works and is not the problem; only fetching the parameter metadata is the problem. Please note that most of the issues with with line breaks also occur with tabs.

https://gist.github.com/chadberchek/1d0c686890a69e171e6e01d0ec6fffdb#file-experiment-java

Here is a summary of my results:

Test | Result
-----|--------
insertWithLineBreakBeforeTableName (build of 8103dc386f1210f93216c8a37fa4e018f98bdf38) | SQLServerException: Incorrect syntax near the keyword 'WHERE'.
insertWithLineBreakBeforeTableName (6.1.0.jre8) | SQLServerException: Unable to identify the table insert into experiment (id) values (?) for the metadata.
insertWithNoSpaceAfterTableName | SQLServerException: Invalid column name 'id'.
updateWithLineBreakAfterWhere | SQLServerException: Incorrect syntax near the keyword 'where'.
updateWithLineBreakBeforeFirstParameter | Parameter count mismatch Expected :2 Actual   :0
updateWithLineBreakAfterUpdate | SQLServerException: Unable to identify the table update experiment set id = ? where id = ? for the metadata.

Tested with driver 6.1.0.jre8 and also a local build of 8103dc386f1210f93216c8a37fa4e018f98bdf38 (for JDK8) against Microsoft SQL Server 2008 R2 (SP2) - 10.50.4000.0 (X64).

**Comment by ajlam** [comment]
Hi @chadberchek. Really appreciate your help with finding this issue and providing these tests. We'll follow up with our investigation soon. We're working on stabilizing the source code to prepare for a release, so we may have a delay in following up quickly.  

Out of curiosity, did you see this behavior with any of the older JDBC Drivers?

**Comment by v-xiangs** [comment]
hello @chadberchek . Thank you very much for reporting so many failing scenarios. Could you please also test those scenarios with version 6.1.6 or later? because we had a fix #181 merged for release #181, I am just wondering if that fixes anything related to Line Break. Thank you.

**Comment by chadberchek** [comment]
@v-xiangs As noted I tested with 8103dc3. I believe this already has the code you are referring to merged into it. I see a merge of pull request #181 in the history: 7d4d62b7b479a51f8fbc492c2535a56241ea7aeb

**Comment by chadberchek** [comment]
@ajlam I ran these tests with 4.0.2206.100 (from Maven, 'com.microsoft.sqlserver:sqljdbc4:4.0.2206.100') and got the same results.

**Comment by v-xiangs** [comment]
Hello @chadberchek , I created a PR #351 to fix the issues you found.

Thank you very much for providing the test code, it really helped a lot! Would you mind if I add your test code to the PR as one of the unit tests?

**Comment by chadberchek** [comment]
That would be fine. You have my permission to use the code however you want.
