### ISSUE TITLE
How does the versioning scheme work?

### ISSUE THREAD

**Issue by tubbynl** [Microsoft/mssql-jdbc#346]
In #281 the following is mentioned

> The naming of our open source previews has changed. The sqljdc41.jar and sqljdbc42.jar correspond to “mssql-jdbc-6.1.x-jre7.jar” and “mssql-jdbc-6.1.x-jre8.jar” now.
The website downloaded jars are production release and the "mssql-jdbc-6.1.x" jars are latest preview versions of the driver.

will the website downloads also be provided as -stable or -release versions in the maven repository or is the non-postfixed version considered to be the -release one?

is 6.1.0.jre8 considered to be more stable than 6.1.7.jre8-preview?

**Comment by ajlam** [comment]
Hi @tubbynl. Thanks for posting. We're currently gearing up for a new stable release, which will be released on Maven and the Microsoft Download Center. We haven't closed on a release name for the stable jars. We would most likely go with a non-postfixed name, but are definitely open to suggestions. Does "-stable" or "-release" work better in your opinion?

**Comment by tubbynl** [comment]
I prefer non-postfixed (6.1.0) for released/stable versions.

And for the current -preview versions i think 6.2-rc1 would more fit the purpose. Judging on the releasenotes they contain new features but are non-breaking (hence the minor-bump) and preview indicate sort of release candidates

In the current version scheme it's not possible to release a patch release on 6.1 ( 6.1.1) for example to fix the optional dependency on azure-vault

**Comment by tubbynl** [comment]
and the jre7 and jre8 postfixes are currently also required. But on that i would suggest to bump the major for 8

so having 6.x for jre7(jdbc41) and 7.x for jre8(jdbc42)

**Comment by v-nisidh** [comment]
@tubbynl 

> so having 6.x for jre7(jdbc41) and 7.x for jre8(jdbc42)

It's good idea. Better 7.x for JDK 7 & 8.x for JDK 8. 

Right now we have only one codebase for JDK 7 & 8 and due to that we used simple approach to build jar with postfix. Another reason for this type of versioning is Semantic Versioning. 

After open source we are trying to adopt [Semantic Versioning 2.0.0](http://semver.org/) where major version will be bumped if we make any incompatible API changes. 

For stable releases, simplest approach is preview tag / postfix text **will not be present** in release name. In stable releases patch version will be 0.

> In the current version scheme it's not possible to release a patch release on 6.1 ( 6.1.1) for example to fix the optional dependency on azure-vault

For patch releases, also I think same above approach is useful. You can think of development of incremental patch releases and finally released as next stable release.

**Comment by tubbynl** [comment]
Moving the supported baseline version of Java is a incompatible API change, it is not uncommon to develop the new features using only the currently actively supported Java version (support on 7 ended). Bumping and updating Java versions at runtime is considered bestpractice because it deliveres security And performance improvements and are non-breaking

**Comment by tubbynl** [comment]
And btw; if the codebase is the same for 7 and 8 there is no need to have different version artifacts, the 7 compiled version works on 8, you can even compile using jdk8 but compatible for 7. The resulting classes/jar can be used for 7 and higher

**Comment by tubbynl** [comment]
and if you reflect that onto git you get
* master -> the release of the next major 7.x (only java8, being able to use java8)
* release/6 -> maintenance support on 6.x (only java7)
* bugfix/6.0 -> bugfix support on 6.0.x (only java7, security-fixes, bugfix)
* tags -> actually released versions (tagging commits on release / bugfix branches)

mostly before release and when providing previews you use the master and just  before release you create the release branch, and from the release branch you create the bugfix branch upon release

**Comment by ajlam** [comment]
Hi @tubbynl, thanks for your awesome suggestions. We're going to take some time to make sure we move forward with a versioning scheme that clarifies things for customers/users. We'll follow up on this issue and get some feedback from you.

**Comment by tubbynl** [comment]
Smaller steps forward from here are
* verify wether the jre7 works on jre8 (if the build includes all sources there is no reason why it shouldn't). That would remove the need for multiple versions with jre postfix
* releasing the next preview as 6.2-preview8 
* releasing the next final version as 6.2.0

**Comment by jubax** [comment]
I actually had the impression from the mssql-jdbc github start site that 6.1.0 is the current stable release (e.g. https://repo.maven.apache.org/maven2/com/microsoft/sqlserver/mssql-jdbc/6.1.0.jre8/).

Is 6.1.0 recommended for production or should I use 6.1.7.jre8-preview for a later version or is it better to stick with 6.0?

Note that we are already using 6.1.0 in development and qa for several months and we do not have any issues so far.

**Comment by tubbynl** [comment]
6.1.0 is the current stable

**Comment by tubbynl** [comment]
final question on this then; on the microsoft website there's a 6.0 version with Date Published: 1/23/2017
https://www.microsoft.com/en-us/download/details.aspx?id=11774

is that a newer or older version than 6.1.0?, because the latter is of november 2016

**Comment by ajlam** [comment]
@tubbynl, the v6.0 [package on the download center](https://www.microsoft.com/en-us/download/details.aspx?id=11774) is older than v6.1.0. The version published date was updated when we had to move some of the JDBC bits around on the backend of the download center. Apologies for any confusion this may have caused.

**Comment by greg-pendlebury** [comment]
@ajlam So how does one get the DLLs for 6.1 if it is not in the download center? It is a minor point. Our testing (6.1.7-preview) seems to work against older DLLs, but not upgrading them (and trying to find what we would upgrade them to) caused some debate internal to our team.

**Comment by tubbynl** [comment]
as the intention jars and java in general is it to work platform independent, no dll's are required as they bind you to a specific platform (and specific versions of dll's for that matter).

**Comment by greg-pendlebury** [comment]
@tubbynl The packaged drivers from the Microsoft website include DLLs. Have a look at the readme. One is for integration authorization, the other is for XA support. I would guess licensing prevents their distribution on GitHub but I could be wrong. It is mainly the absence of 6.1 from the Microsoft website (and thus the absence of 6.1 DLLs). I hope that 6.2 is in both locations as per @ajlam's comment above

**Comment by ajlam** [comment]
@greg-pendlebury, you're correct. The licensing for the DLLs is different than the JARS.

The v6.2.0 release just went out and is available on the download center [here](https://go.microsoft.com/fwlink/?linkid=852460). The DLLs are also available there.
