### ISSUE TITLE
Refactor common code from SQLServerBulkCSVRecord into a utility class.

### ISSUE THREAD

**Issue by ferozed** [Microsoft/mssql-jdbc#352]
Some of the code in SQLServerBulkCSVRecord code will be needed by implementers of the ISQLServerBulkRecord interface, it should be put in a common utility class so that it can be leveraged. I am specifically talking about the following methods:

SQLServerBulkCSVFileRecord:addColumnMetadataInternal()
SQLServerBulkCSVFileRecord:getRowData()

**Comment by cheenamalhotra** [comment]
Hi @ferozed wanted some more clarity regarding this issue - I believe this is regarding data processing based on datatype in both methods, where you are suggesting to move parsing logic to _Util_ class which can be reused by implementers.

We do maintain _Util_ class which is private to driver, but if we move parsing logic there, it will anyhow not be available for implemented classes.. As you know, we are strictly following JDBC APIs and only methods that are exposed by API will be available in public domain.

Let us know how would you like to go ahead in this case.

**Comment by cheenamalhotra** [comment]
Closing the issue due to inactivity.
