### ISSUE TITLE
TDS error under high load

### ISSUE THREAD

**Issue by jubax** [Microsoft/mssql-jdbc#357]
We are using:

- 6.1.0 driver (build from source)
- SQL Server 2014

We are experiencing problems with the JDBC driver under high load. The test we are running works fine up to a certain limit. Then the driver logs something like:

`
Jun 21, 2017 9:39:24 AM com.microsoft.sqlserver.jdbc.TDSParser throwUnexpectedTokenException
SEVERE: ConnectionID:19 ClientConnectionId: abfb1747-17a7-44cb-abba-6c861c55d9bb: getNextResult: Encountered unexpected unknown token (0x83)
Jun 21, 2017 9:39:24 AM com.microsoft.sqlserver.jdbc.TDSReader throwInvalidTDSToken
SEVERE: ConnectionID:19 ClientConnectionId: abfb1747-17a7-44cb-abba-6c861c55d9bb got unexpected value in TDS response at offset:5166
Jun 21, 2017 9:39:25 AM com.microsoft.sqlserver.jdbc.TDSParser throwUnexpectedTokenException
SEVERE: ConnectionID:19 ClientConnectionId: abfb1747-17a7-44cb-abba-6c861c55d9bb: batch completion: Encountered unexpected TDS_RETURN_VALUE (0xAC)
Jun 21, 2017 9:39:25 AM com.microsoft.sqlserver.jdbc.TDSReader throwInvalidTDSToken
SEVERE: ConnectionID:19 ClientConnectionId: abfb1747-17a7-44cb-abba-6c861c55d9bb got unexpected value in TDS response at offset:461
`

We suspect some kind of a transfer error (incomplete transfer), but we do not really know what's going on.

The other thing which is strange is that we do not see stack trace as with other connection errors. It seems the exception is suppressed somewhere.

Do you have an idea what's causing the problem or how we could debug it? Activate additional logging/integrate additional logs in the source code?

Thanks,

Juergen

**Comment by v-ahibr** [comment]
Hi @jubax ,

Thanks for letting us know about this issue. You can save debug logs by adding the following code snippet to your application:

```
Handler fh = new FileHandler("JDBCDriverTrace.log"); 
fh.setFormatter(new SimpleFormatter()); //create TXT formatter 
Logger logger = Logger.getLogger("com.microsoft.sqlserver.jdbc"); 
logger.addHandler(fh); 
logger.setLevel(Level. FINEST); //Log level can be one of SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST
```

Also, can you verify if you see this issue in the latest 6.1.7 driver from the dev branch? We've recently fixed some TDS errors and want to check if this error is resolved by those fixes.

**Comment by jubax** [comment]
I will try with 6.1.7 this week. Why does the Git repository only contains tags for 6.1.0..6.1.5 and not 6.1.6 and 6.1.7? I will try the version in the maven repository, but it would be nice if I could build it from source.

**Comment by v-nisidh** [comment]
Interesting!!! You can download code from tags. Please see [Tags](https://github.com/Microsoft/mssql-jdbc/tags). 

From above link you can download source code for that tag. Also you can browse tags from GitHub Project Page from Branch Button. [Tag 6.1.7](https://github.com/Microsoft/mssql-jdbc/tree/v6.1.7) 

From command prompt `git fetch --all` and `git fetch --tags --force` might be useful.

**Comment by jubax** [comment]
`git fetch --tags`

did retrieve the missing tags. Thanks!

**Comment by v-afrafi** [comment]
Hi @jubax Just wanted to follow up if you still see this issue with the 6.1.7?  Thanks!

**Comment by jubax** [comment]
I'm currently testing 6.2.0 and so far I no longer see any TDS errors in the log file. So this issue might be fixed in 6.2.0.

**Comment by v-xiangs** [comment]
@jubax thank you very much for confirming with us. So, I am closing this issue for now,please feel free to re-open it if the issue happens again. Thank you.

**Comment by magnusgf** [comment]
For what it's worth, I still observe this error

TDSReader@20343 (ConnectionID:2 ClientConnectionId: d870f06a-8055-4dcf-bf8b-be3ea7c030cf) got unexpected value in TDS response at offset:7992

After upgrading from JDBC driver version 4.1 to 6.2.1 jre 8. 

Did anything change regarding this?

**Comment by ChristinaSi** [comment]
I'm getting the same error message as @magnusgf. Is there any solution by now? 
(I'm using version 6.3.6.jre8-preview.)

**Comment by magnusgf** [comment]
No, but I ended up using version 6.1.0jre8. For some reason this works.

**Comment by peterbae** [comment]
Hi @ChristinaSi, could you provide the debug logs / stack for the error you're seeing?
