### ISSUE TITLE
What is the release schedule?

### ISSUE THREAD

**Issue by jbuffin** [Microsoft/mssql-jdbc#359]
There have been a lot of pre-release versions. When will a production release be cut?

**Comment by ajlam** [comment]
Hi @jbuffin, we just finished with the production/stable release, [v6.2.0](https://github.com/Microsoft/mssql-jdbc/releases/tag/v6.2.0). The package is also available on the [MS Download Center](https://go.microsoft.com/fwlink/?linkid=852460). 

Our goal is to continue releasing monthly previews that will roll into stable releases every 6 months (give or take).

**Comment by jbuffin** [comment]
@ajlam Great! Thanks so much
