### ISSUE TITLE
Implement properly Cross Domain Kerberos using JavaKerberos

### ISSUE THREAD

**Issue by pierresouchay** [Microsoft/mssql-jdbc#36]
The Driver wrongly assumes the SPN to have the same value as the default_realm in krb5.conf.

Which means when connecting with principal my.user@MYREALM.COM and connecting to to sqlserver:PORT@MYOTHERTRUSTEDREALM.COM the driver wrongly assumes the SPN is MSSQLSvc/sqlserver:PORT@MYREALM.COM instead of the right MSSQLSvc/sqlserver:PORT@MYOTHERTRUSTEDREALM.COM even if DNS are correctly set up and domain to REALMS correctly described in krb5.conf file.

Using the default_realm is evil and should not be used at all.

Since the last driver (jdbc42, version 6.0), it is possible to override the Spn, but older drivers (compatible with Java 7) are not. Would it be possible to implement this feature?

**Comment by v-mabarw** [comment]
@pierresouchay The [serverSpn ](https://msdn.microsoft.com/en-us/library/ms378988(v=sql.110).aspx)connection property allows you to use Kerberos in a cross realm scenario.  If you are looking for the Java 7 compatible version, are you able to use the JDBC 4.1 compliant jar (which you can build here, retrieve from Maven (look for version 6.1.0.jre7), or obtain from the latest driver package on the [Microsoft Download Center](https://www.microsoft.com/en-us/download/details.aspx?displaylang=en&id=11774))?

**Comment by pierresouchay** [comment]
@v-mabarw I have a working patch for the driver, what it does:

For generating a SPN (in makeSPN()):

Try to find a valid REALM name (for Oracle JVM using sun.securitt.krb5.Config.getKDCList(realm)) by looking into hostname. (so for myserver.sub.domain.com, would look for real called myserver.sub.domain.com, then sub.domain.com, domain.com and finally com). If no valid realm found (aka getKDCList() did never return any KDC, ignore it).
If no KDC has been found, retry on the canonical name of server.
If nothing has been found, keep the SPN unchanged, otherwise add @FOUND_REALM after the existing SPN.

If a SPN has been provided by the user, do the same if SPN is not suffixed with a REALM, but do not try on canonical name.

The code could be enhanced a bit by having another mechanism for other JVMs (such as the one from IBM) to detect the REALM.

Are you interested with a Merge Request ?

**Comment by ajlam** [comment]
@pierresouchay - hoping to get PR #40 merged in one of our next few releases 😄

**Comment by v-afrafi** [comment]
Thank you so much @pierresouchay! . PR #40 is tested and merged now. As you mentioned, the fix does not work on IBM JVM and needs different implementation. Could you please create new issue so that we can later fix this?

**Comment by pierresouchay** [comment]
@v-afrafi I think it now should work with IBM JVM since we fallback on DNS resolution for identifying the REALM.

**Comment by v-afrafi** [comment]
@pierresouchay You are correct. Just confirming that got the same results with IBM. Thank you for your contribution again!

**Comment by pierresouchay** [comment]
Cool ;)

Happy to know the fallback system works with any JVM
