### ISSUE TITLE
Unable to use addRow with Character / char datatype -mssql-jdbc-6.1.0.jre8

### ISSUE THREAD

**Issue by ethesx** [Microsoft/mssql-jdbc#360]
Passing a value with datatype of Character or char to SQLServerDataTable.addRow results in
```
java.lang.ClassCastException: java.lang.Character cannot be cast to java.lang.String
at com.microsoft.sqlserver.jdbc.SQLServerDataTable.addRow(SQLServerDataTable.java:206)
```
The case CHAR does not allow for conversion prior to casting in case NVARCHAR

```
case CHAR:
    if(val instanceof UUID && (val != null))
    val = ((UUID)val).toString();
case VARCHAR:
case NCHAR:
case NVARCHAR:
    bValueNull = (null == val);
    nValueLen = bValueNull ? 0 : (2 * ((String)val).length());
```

**Comment by v-xiangs** [comment]
@ethesx Hello. Thank you for the report. Is there any reason you want to use `char` type instead of `String`? If you could use `SQLServerDataTable.addRow()` with String value, it should work for you.

**Comment by ethesx** [comment]
The DB TVP datatype as well as the domain objects are `Char` / `char` so conversion is simply an extra step.  We have just worked around it by passing a String so far.

**Comment by v-xiangs** [comment]
Hello @ethesx  thank you for getting back to us. if we look at [Datatype mappings](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-basic-data-types) on Microsoft Docs, we can see the SQL Server type Char is mapped to Java type String. However, if you think conversion is an extra step for you, I will talk with the team and see if we can add the conversion for you to the code.

**Comment by ethesx** [comment]
I see that as well, however there are bound to be char datatypes used in other applications and it's not clear that SQLServerDataTable class isn't supposed to handle such a datatype at the outset. If the type won't be handled, a checked exception and error would be more helpful instead of a vague cast exception at run-time (and possibly save some of your time :) ).

**Comment by ajlam** [comment]
Hi @ethesx, thanks for the suggestion. We'll think about updating the cast exception for the future. Closing this issue for now.
