### ISSUE TITLE
SQLServerException is not thrown by jdbc driver

### ISSUE THREAD

**Issue by tmichal17** [Microsoft/mssql-jdbc#367]
When executing a JDBC statement with multiple INSERT statements and only one of the INSERTS causes an SQL error, the appropriate exception is suppressed by the jdbc driver. The relating code is in the close method of TDSCommand, where the exceptionis just logged at level finest but not handled.

We use this driver under Linux with JRE 1.8.0_131:    
	<dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
      <version>6.2.0.jre8</version>
    </dependency>

Our log:

TDSCommand@4ddee582 (SQLServerStatement:1 executeXXX): starting request...
TDSCommand@4ddee582 (SQLServerStatement:1 executeXXX): finishing request
TDSCommand@4ddee582 (SQLServerStatement:1 executeXXX): request complete
TDSCommand@4ddee582 (SQLServerStatement:1 executeXXX): Reading response...
TDSCommand@4ddee582 (SQLServerStatement:1 executeXXX): disabling interrupts
ConnectionID:10 ClientConnectionId: badd99c2-29aa-44fd-be9d-c58c485e9335 started
TDSCommand@4ddee582 (SQLServerStatement:1 executeXXX): closing...
TDSCommand@4ddee582 (SQLServerStatement:1 executeXXX): processing response...
ConnectionID:10 ClientConnectionId: badd99c2-29aa-44fd-be9d-c58c485e9335 rolled back
*** SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: Fehler beim Konvertieren einer Zeichenfolge in ein Dat
TDSCommand@4ddee582 (SQLServerStatement:1 executeXXX): close ignoring error processing response: Fehler beim Konvertieren
ENTRY
TDSCommand@4ddee582 (SQLServerStatement:1 executeXXX): detaching...
TDSCommand@19f1e8e6 (Connection.commit): starting request...

The transaction is correctly rolled back, but it was difficult to find out, why there is missing data in the database, without any exception has been thrown and no info or error log output was given.

Thanks,
Thomas

**Comment by v-nisidh** [comment]
Thanks @tmichal17 for opening this issue. 
Can we get some more details? 
1. Can you share us your logging configuration?  Did you enable logs only for TDSCommand or for all? 
1. Is your insert query trying to insert date time in form of String? 
1. Which SQL Server you are using? 
1. Which JDK / JRE you are using?  Oracle / OpenJDK / SAP / IBM?

**Comment by tmichal17** [comment]
Thanks, @v-nisidh,  for looking into this issue! 

1. The logging configuration was:
logging.level.root = INFO
logging.level.org.apache.camel.log = DEBUG
logging.level.com.microsoft.sqlserver.jdbc.internals.TDS = TRACE
logging.level.com.microsoft.sqlserver.jdbc = DEBUG
logging.level.com.microsoft.sqlserver.jdbc.internals.TDS.DATA = DEBUG
logging.level.com.microsoft.sqlserver.jdbc.internals.TDS.Reader = DEBUG
logging.level.com.microsoft.sqlserver.jdbc.internals.TDS.Writer = DEBUG
logging.level.com.microsoft.sqlserver.jdbc.internals.TDS.TOKEN = DEBUG
logging.level.com.microsoft.sqlserver.jdbc.internals.SQLServerStatement = INFO

2. We had used a wrong string with date time information: "2017-06-01 07:00:00+0000" instead of "2017-06-01 07:00:00".
The second correct version is working fine. The issue is not the date format problem, which was handled correctly by the server, but the exception that was given by the server but not thrown by the JDBC driver, what made it so difficult to debug and find our wrong format.

3. We use SQL Server 2016 (SQL Server 13.0.4001.0)

4. We use Oracle JDK 1.8.0_101

**Comment by v-xiangs** [comment]
@tmichal17 Thank you for the report.

After investigation, we believe this is expected behaviour and exception is not suppressed by the driver.

In this scenario of multiple statements, as following JDBC specs, we have to call `Statement#getMoreResults()` to retrieve any subsequent results. Without calling the method, JDBC driver only shows the result of the first INSERT statement. By calling the method once, JDBC driver gives the result of the second INSERT statement, and so on. Then, you should be able to see the exception.

Please let us know it this resolves the problem. Thank you :)

**Comment by tmichal17** [comment]
That sounds reasonable and solves the problem.
Thank you very much for your investigation and the explanation!
Best regards,
Thomas
