### ISSUE TITLE
Missing Locale for checking properties passed by user. 

### ISSUE THREAD

**Issue by v-afrafi** [Microsoft/mssql-jdbc#381]
The driver is missing Locale in some String functions which produces an incorrect parameter being passed in other languages. 
For instance:
 https://github.com/Microsoft/mssql-jdbc/blob/master/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L1360

Reference of issue:
https://docs.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server

**Comment by peterbae** [comment]
fixed by #384
