### ISSUE TITLE
SQLServerBulkCopy with a SQLServerBulkCSVFileRecord on temp file does not delete on exit.

### ISSUE THREAD

**Issue by sathley** [Microsoft/mssql-jdbc#398]
I am using SQLServerBulkCopy with SQLServerBulkCSVFileRecord.
I created a `File.createTempFile(..)` with my csv data and set `tempFile.deleteOnExit()`.
But this file does not get deleted after the java process exits. The SQLServerBulkCopy is leaving some stream open somewhere which is not letting the file to get deleted.

https://stackoverflow.com/a/28751091/842443

**Comment by v-xiangs** [comment]
@sathley Hello, thanks for creating the issue. We are just wondering if you close the `SQLServerBulkCopy`  object? According to this [doc](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-bulk-copy-with-the-jdbc-driver), if you close the object, the temp file should be deleted on exit.

**Comment by sathley** [comment]
Yup. You are correct. I was not closing the `SQLServerBulkCSVFileRecord` object. It works fine if I close it. Thanks for the help!
