### ISSUE TITLE
No Exception when executing a faulty procedure that selects before error

### ISSUE THREAD

**Issue by goreRatzete** [Microsoft/mssql-jdbc#399]
Given a stored procedure like the following:

```
ALTER PROCEDURE [dbo].[SP_TEST] AS
BEGIN
	SELECT 1;

    exec doesnotexist;
    
END
```

And executing it via the jdbc:

`execute("EXEC SP_TEST")`

No exception is thrown.

However, when executing the procedure in sql server management studio, it returns the following:
```
(1 row(s) affected)
Msg 2812, Level 16, State 62, Procedure SP_TEST, Line 6 [Batch Start Line 8]
Could not find stored procedure 'doesnotexist'.
```

I have been trying to debug a procedure for hours and finally found that there is no exception on the jdbc side. Searching the web I found a [similar problem in MySql](https://bugs.mysql.com/bug.php?id=15121).

The exception will be thrown correctly when removing the "SELECT 1" statement.

**Comment by v-xiangs** [comment]
@goreRatzete Thanks for creating the issue. We have investigated on our end, this is a valid scenario. To get exception, you have to call `getMoreResults()` on `Statement`.  
After calling `execute()`, the first result is the result of `SELECT 1;`. When we call `getMoreResults()`, we get the second result, which contains the exception.

**Comment by goreRatzete** [comment]
Thanks for the reply. 

I see. I even checked statement.warnings but couldn't find anything. 

It seems a bit unintuitive to me. Ideally, if any exceptions are encountered during execute, it should be brought to the attention of the program via an Exception. (imo).

**Comment by v-xiangs** [comment]
@goreRatzete Thank you for sharing your opinion. I totally agree with you that this is not intuitive. However, we are following [JDBC spec](https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#execute(java.lang.String,%20java.lang.String[])), it's documented here:

> The execute method executes an SQL statement and indicates the form of the first result. You must then use the methods getResultSet or getUpdateCount to retrieve the result, and getMoreResults to move to any subsequent result(s).

**Comment by goreRatzete** [comment]
Alright, thanks for explaining.
