### ISSUE TITLE
Inconsistent coding style

### ISSUE THREAD

**Issue by cobookman** [Microsoft/mssql-jdbc#4]
https://github.com/Microsoft/mssql-jdbc/blob/master/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerColumnEncryptionJavaKeyStoreProvider.java#L81

**Comment by ajlam** [comment]
@cobookman Thanks for filing an issue about this! As we move forward with developing new features, etc., we will definitely keep coding style consistency in mind.

**Comment by cobookman** [comment]
I wouldn't mind fixing all the style guide issues.  And adding a linter to a github pre-commit hook. Just need a style guide to reference.  Here's google's for example: https://google.github.io/styleguide/javaguide.html

Btw we are also prone to having style guide issues as well :D.
https://github.com/google/guava/issues/1891

**Comment by sehrope** [comment]
+1 for doing this now across the board.

Style changes are like taking off a band-aid. Best to get it over with all at once.

**Comment by adenfitz** [comment]
From https://blogs.msdn.microsoft.com/dotnet/2015/02/09/automatic-code-formatter-released-to-github/ 
"We strongly believe that having a consistent style greatly increases the readability and maintainability of a code base. The individual style decisions themselves are subjective, the key is the consistency of the decisions. As such the .NET team has a set of style guidelines for all C# code written by the team."

**Comment by v-nisidh** [comment]
@cobookman : In current [6.1.3 release](https://github.com/Microsoft/mssql-jdbc/releases/tag/v6.1.3) we fixed inconsistent coding style. You can find formatting rules in [mssql-jdbc_formatter.xml](https://github.com/Microsoft/mssql-jdbc/blob/v6.1.3/mssql-jdbc_formatter.xml)

If you are satisfied then I will close this issue otherwise your comments are welcome.
