### ISSUE TITLE
DatabaseMetaData.getTables(...) is missing columns in the ResultSet

### ISSUE THREAD

**Issue by ryan-gustafson** [Microsoft/mssql-jdbc#406]
Using the 6.2.1.jre8 driver, when I process the `ResultSet` returned by the `DatabaseMetaData.getTables(...)`, it is missing the following columns:
- TYPE_CAT
- TYPE_SCHEM
- TYPE_NAME
- SELF_REFERENCING_COL_NAME
- REF_GENERATION

Because the columns are missing, an error occurs when calling `ResultSet.getString(String)`, such as `com.microsoft.sqlserver.jdbc.SQLServerException: The column name TYPE_CAT is not valid.`
Instead, the columns should be present, and `null` returned.

I checked the JDBC 4.2 spec, but it did not seem to enumerate the expected columns.  However, the Java 8 docs for JDBC 4.2 explicitly lists the columns, makes no mention of optionality, and says `null` maybe returned, which is only possible if the column is present.
http://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getTables-java.lang.String-java.lang.String-java.lang.String-java.lang.String:A-

I also encounter similar issues with `DatabaseMetaData.getColumns`, with for example SCOPE_CATALOG.  I suggest all the `ResultSet` returning APIs on this class be checked to see they conform structurally.

**Comment by v-xiangs** [comment]
Hello @ryan-gustafson Thank you very much for the report. If we look at this [page](https://docs.microsoft.com/en-us/sql/connect/jdbc/reference/gettables-method-sqlserverdatabasemetadata), it says those types are not supported by the driver. The reason behind is, the driver uses SQL Server stored procedure [sp_tables](https://docs.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-tables-transact-sql) to retrieve those metadata, which does not return those types.

**Comment by ryan-gustafson** [comment]
@v-xiangs Ok, I wasn't aware of that page.  However, I believe unsupported should manifest as `null` in the metadata result however, not as an incompatible `ResultSet` structure.

This is an issue for code attempting to operate on varying JDBC drivers following the standard.  For example, one may switch to H2 for in-memory unit tests.  Deviant drivers make things more complicated.

There are many ways to potentially handle the issues with the differences in structure returned by the **sp_tables** store procedure.

Related to this compatibility issue on database metadata, I'm also awaiting the support for __sql_variant__ type, as this readily shows up when interacting with the INFORMATION_SCHEMA tables.

**Comment by ajlam** [comment]
@ryan-gustafson #387 (provides support for sql_variant) was just merged to the dev branch. Can you take a look and let us know what you think?

**Comment by v-xiangs** [comment]
Hello @ryan-gustafson , thank you for you explanation. However, after talking to the team, we decide to not change the behavior since it is not supported by SQL Server and also has been documented. Thank you very much for your contribution. We are closing this issue now.

**Comment by atkawa7** [comment]
Sample query. Can be fine tuned [Source](https://github.com/sfa-siard/JdbcMsSql/blob/main/src/ch/admin/bar/siard2/jdbc/GetTablesQuery.java)
```sql
SELECT
  DB_NAME() AS TABLE_CAT,
  s.name AS TABLE_SCHEM,
  o.name AS TABLE_NAME,
  case o.type
    when 'U' then 'TABLE'
    when 'V' then 'VIEW'
    when 'TT' then 'TABLE TYPE'
    else 'SYSTEM TABLE'
  end AS TABLE_TYPE,
 STUFF((SELECT DISTINCT '| ' + CONVERT(VARCHAR, p.value)
 FROM sys.extended_properties p
 WHERE (p.major_id = o.object_id and p.minor_id = 0 and p.class = 1)
 FOR XML PATH ('')), 1, 2, '') AS REMARKS,
  NULL AS TYPE_CAT,
  NULL AS TYPE_SCHEM,
  NULL AS TYPE_NAME,
  NULL AS SELF_REFERENCING_COL_NAME,
  NULL AS REF_GENERATION,
  m.definition as QUERY_TEXT
FROM sys.all_objects o
  JOIN sys.schemas s
    ON (o.schema_id = s.schema_id)
  LEFT JOIN sys.sql_modules m
    ON (m.object_id = o.object_id)
WHERE
o.type = 'U' AND is_ms_shipped = 0
 AND DB_NAME() = 'XYZ'
 AND s.name LIKE '%' ESCAPE 'null'
 AND o.name LIKE '%' ESCAPE 'null'
ORDER BY TABLE_TYPE, TABLE_CAT, TABLE_SCHEM, TABLE_NAME
```
