### ISSUE TITLE
connection reset on first select on MacOS 10.10.5 while connected to SQL Server 2008

### ISSUE THREAD

**Issue by alanruttenberg** [Microsoft/mssql-jdbc#434]
## Driver version or jar name
Please tell us what the JDBC driver version or jar name is.
mssql-jdbc-6.3.0.jre8-preview.jar, sqljdbc42.jar
## SQL Server version
Please tell us what the SQL Server version is.
SQL Server 2008
## Client operating system
Please tell us what operating system the client program is running on.
MacOS 10.10.5
## Java/JVM version
Example: java version "1.8.0", IBM J9 VM
Java 1.8.0_71 Oracle Corporation
## Table schema
Please tell us the table schema

## Problem description
Please share more details with us.
I am able to connect, however on the first select statement I try to execute I get a connection reset.
## Expected behavior and actual behavior
Please tell us what should happen and what happened instead
I get results of the query
## Repro code
Please share repro code with us, or tell us how to reproduce the issue.

Below is a trace of from where the connection is established until the connection is reset. I can send the full trace on request.

On the same machine and OS, using Oracle Java 1.7.0_72, with "-XX:MaxPermSize=128M" and using sqljdbc4.jar the query succeeds.
A tool running with Java 1.6 also succeeds. (DbVisualizer)
No version of the JDBC driver I have tried in Java 1.8 has been able to successfully run the query.
I have used scutil to set the hostname, and tried passing workstationID as suggested in https://github.com/Microsoft/mssql-jdbc/issues/177 

    FINEST: TDSReader@21 (ConnectionID:8 ClientConnectionId: 0e05fbff-2f79-4e4b-a84d-561e920740f1) Reading 8 bytes from offset 359
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerConnection processEnvChange
    FINER: ConnectionID:8 ClientConnectionId: 0e05fbff-2f79-4e4b-a84d-561e920740f1 Network packet size is 8000 bytes
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSReader reset
    FINEST: TDSReader@21 (ConnectionID:8 ClientConnectionId: 0e05fbff-2f79-4e4b-a84d-561e920740f1): Resetting to: com.microsoft.sqlserver.jdbc.TDSReaderMark@767c2edd
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSReader readBytes
    FINEST: TDSReader@21 (ConnectionID:8 ClientConnectionId: 0e05fbff-2f79-4e4b-a84d-561e920740f1) Reading 19 bytes from offset 357
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSParser parse
    FINEST: TDSReader@21 (ConnectionID:8 ClientConnectionId: 0e05fbff-2f79-4e4b-a84d-561e920740f1): logon: Processing TDS_DONE (0xFD)
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSParser parse
    FINEST: TDSReader@21 (ConnectionID:8 ClientConnectionId: 0e05fbff-2f79-4e4b-a84d-561e920740f1): logon: Processing EOF
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerConnection connectInternal
    FINER: ConnectionID:8 ClientConnectionId: 0e05fbff-2f79-4e4b-a84d-561e920740f1 End of connect
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerDriver:1 connect
    FINER: RETURN ConnectionID:8 ClientConnectionId: 0e05fbff-2f79-4e4b-a84d-561e920740f1
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerConnection:8 createStatement
    FINER: ENTRY
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerConnection:8 createStatement
    FINER: ENTRY 1,003 1,007
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerStatement:13 setResponseBuffering
    FINER: ENTRY adaptive
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerStatement:13 setResponseBuffering
    FINER: RETURN
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
    FINER: Properties for SQLServerStatement:13: Result type:1003 (2003) Concurrency:1007 Fetchsize:128 bIsClosed:false useLastUpdateCount:true
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
    FINE: SQLServerStatement:13 created by (ConnectionID:8 ClientConnectionId: 0e05fbff-2f79-4e4b-a84d-561e920740f1)
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerConnection:8 createStatement
    FINER: RETURN SQLServerStatement:13
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerConnection:8 createStatement
    FINER: RETURN SQLServerStatement:13
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerConnection:8 createStatement
    FINER: ENTRY
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerConnection:8 createStatement
    FINER: ENTRY 1,003 1,007
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerStatement:14 setResponseBuffering
    FINER: ENTRY adaptive
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerStatement:14 setResponseBuffering
    FINER: RETURN
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
    FINER: Properties for SQLServerStatement:14: Result type:1003 (2003) Concurrency:1007 Fetchsize:128 bIsClosed:false useLastUpdateCount:true
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
    FINE: SQLServerStatement:14 created by (ConnectionID:8 ClientConnectionId: 0e05fbff-2f79-4e4b-a84d-561e920740f1)
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerConnection:8 createStatement
    FINER: RETURN SQLServerStatement:14
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerConnection:8 createStatement
    FINER: RETURN SQLServerStatement:14
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerStatement:14 executeQuery
    FINER: ENTRY SELECT name FROM ClinicTest.Academic.discipln
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSCommand startRequest
    FINEST: TDSCommand@2f8d36 (SQLServerStatement:14 executeXXX): starting request...
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSWriter writeBytes
    FINEST: TDSWriter@5b6f4790 (ConnectionID:8) Writing 8 bytes
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSWriter writeBytes
    FINEST: TDSWriter@5b6f4790 (ConnectionID:8) Writing 8 bytes
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSWriter writeBytes
    FINEST: TDSWriter@5b6f4790 (ConnectionID:8) Writing 90 bytes
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerStatement doExecuteStatement
    FINE: SQLServerStatement:14 Executing (not server cursor) SELECT name FROM ClinicTest.Academic.discipln
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSCommand startResponse
    FINEST: TDSCommand@2f8d36 (SQLServerStatement:14 executeXXX): finishing request
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSWriter endMessage
    FINEST: TDSWriter@5b6f4790 (ConnectionID:8) Finishing TDS message
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSChannel logPacket
    FINEST: /128.205.164.201:53825 SPID:55 TDSWriter@5b6f4790 (ConnectionID:8) sending packet (120 bytes)
    01 01 00 78 00 37 01 00 16 00 00 00 12 00 00 00   ...x.7..........
    02 00 00 00 00 00 00 00 00 00 01 00 00 00 53 00   ..............S.
    45 00 4C 00 45 00 43 00 54 00 20 00 6E 00 61 00   E.L.E.C.T. .n.a.
    6D 00 65 00 20 00 46 00 52 00 4F 00 4D 00 20 00   m.e. .F.R.O.M. .
    43 00 6C 00 69 00 6E 00 69 00 63 00 54 00 65 00   C.l.i.n.i.c.T.e.
    73 00 74 00 2E 00 41 00 63 00 61 00 64 00 65 00   s.t...A.c.a.d.e.
    6D 00 69 00 63 00 2E 00 64 00 69 00 73 00 63 00   m.i.c...d.i.s.c.
    69 00 70 00 6C 00 6E 00                           i.p.l.n.
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream writeInternal
    FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream@f31c68 Writing 29 bytes
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream flush
    FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream@f31c68 Flushing
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream writeInternal
    FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream@f31c68 Writing 149 bytes
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream flush
    FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream@f31c68 Flushing
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSCommand onRequestComplete
    FINEST: TDSCommand@2f8d36 (SQLServerStatement:14 executeXXX): request complete
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSCommand startResponse
    FINEST: TDSCommand@2f8d36 (SQLServerStatement:14 executeXXX): Reading response...
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream readInternal
    FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@ffa6a9a Reading 5 bytes
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream readInternal
    FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@ffa6a9a Read -1 bytes
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream writeInternal
    FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream@f31c68 Writing 29 bytes
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream flush
    FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream@f31c68 Flushing
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.TDSReader readPacket
    FINER: TDSReader@22 (ConnectionID:8 ClientConnectionId: 0e05fbff-2f79-4e4b-a84d-561e920740f1) Premature EOS in response. packetNum:0 headerBytesRead:0
    Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerException logException
    FINE: *** SQLException:ConnectionID:8 ClientConnectionId: 0e05fbff-2f79-4e4b-a84d-561e920740f1 com.microsoft.sqlserver.jdbc.SQLServerException: SQL Server did not return a response. The connection has been closed. SQL Server did not return a response. The connection has been closed.

**Comment by v-xiangs** [comment]
Hello @alanruttenberg Thank you very much for the report and providing very detailed information!

I did notice you said "No version of the JDBC driver I have tried in Java 1.8 has been able to successfully run the query", but I still want to confirm with you if version 6.1.7 works for you? If you didn't try 6.1.7, could you please give it a try?

I also noticed this line in the trace you provided:
```
Aug 06, 2017 3:16:28 AM com.microsoft.sqlserver.jdbc.SQLServerConnection processEnvChange
```
Is your MacOS client machine hosted on Microsoft Azure? If not, this may be the cause of the issue and we will need to fix it.

**Comment by alanruttenberg** [comment]
Thank you for your quick response!

My machine is not on Azure. Nor is the server, which was developed and has been keep locally for HIPAA compliance. I understand that Azure may be able to host HIPAA compliant data, but we haven't made that move. 

Regarding 6.1.7, I've tried 6.2, which didn't work. For 6.1.7 do you mean the release at https://github.com/Microsoft/mssql-jdbc/releases/tag/v6.1.7 ?

I'll try that and report back.

**Comment by alanruttenberg** [comment]
Doesn't work. Looks like the same issue, looking at the trace. If you want I can send you the full trace. Let me know where.

**Comment by alanruttenberg** [comment]
I used the java 8 version, btw. mssql-jdbc-6.1.7.jre8.preview.jar

**Comment by ajlam** [comment]
Hi @alanruttenberg, can you please send your trace with logging level = FINEST to me at: andrela@microsoft.com?

**Comment by alanruttenberg** [comment]
sent

**Comment by ajlam** [comment]
Received. Thanks, @alanruttenberg. I'll work with Shawn to investigate the issue. Will circle back soon.

**Comment by v-xiangs** [comment]
Hello @alanruttenberg Thank you for the log! I tested on Mac OS 10.10 and it worked for me with Java 8. Is it possible for you to test it against a higher Mac OS version rather than 10.0? If we look at the [Java 8 System Requirements](https://www.java.com/en/download/help/sysreq.xml), it says Java 8 supports Mac OS X 10.8.3+, could it be the cause?

**Comment by ajlam** [comment]
Hi @alanruttenberg, we haven't heard back from you. Going to close this issue for now. Please feel free to reopen.

**Comment by alanruttenberg** [comment]
Hi,
Sorry for delay - vacation. 
I looked up and see I miswrote the version of OSX I am using (sorry).
I'm on 10.10.5
![about](https://user-images.githubusercontent.com/241934/30181024-e4a6ebf4-93df-11e7-8255-a6f64ec772b2.png)

**Comment by v-xiangs** [comment]
@alanruttenberg thank you for getting back to us. I am reopening the issue and will look at the issue as soon as possible.

**Comment by alanruttenberg** [comment]
Any news?

**Comment by v-xiangs** [comment]
Hello @alanruttenberg sorry for the delay, I am recently busy with other tasks. I tested it again on our Mac machine, I couldn't see this error. Could you please help me narrow down the cause? 

1. Did you use cursor on statements? 
2.The error happens when you run a select query from a table. Would you mind telling us what the table definition is or what values the table contents? I am thinking it may be related to specific column definition and values.

Thank you.

**Comment by v-xiangs** [comment]
Hello @alanruttenberg does the issue still exist ? if yes, could you please provide the information according to my last comments?

**Comment by cheenamalhotra** [comment]
Closing the issue due to inactivity. @alanruttenberg please re-open if there are any more concerns.
