### ISSUE TITLE
FIPS Compliant Mode

### ISSUE THREAD

**Issue by ulvii** [Microsoft/mssql-jdbc#438]
We recently (version 6.1.2) introduced 3 new connection properties for [FIPS](https://github.com/Microsoft/mssql-jdbc/wiki/FIPS) mode: `fips`, `trustStoreType`, `fipsProvider`. The implementation assumes `fipsProvider` contains `trustStoreType` [when calling ](https://github.com/Microsoft/mssql-jdbc/blob/97ab207fffaf23c967ecbe775423f6262dab9eaf/src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java#L1651)`Keystore.getInstance(trustStoreType,fipsProvider)`.  However, not all providers that contain FIPS-complaint algorithms also provide keystores, such as `IBMJCEFIPS`. [See this page](https://www.ibm.com/support/knowledgecenter/en/SSYKE2_7.0.0/com.ibm.java.security.component.70.doc/security-component/progpractices.html). In this case, users have to use non-FIPS IBMJCE provider (`IBMJCE`) to store the keys, which means they also have to set `fipsProvider=IBMJCE`. This can be confusing, because `IBMJCE` is not the actual FIPS provider, but it is the provider that contains keystore. 

Below are a few possible solutions to solve the issue and  we would really appreciate any feedback from the community. 

1. Keep the current implementation and update the documentation describing the differences. This way we would not be introducing breaking changes, but the connection property `fipsProvider`  could still be confusing to users because of the naming. 
2. Rename the connection property `fipsProvider` to `trustStoreProvider`. This would break the existing FIPS applications, but the name of the property would be less confusing. 
3. Remove the connection property `fipsProvider`. If provider is not specified, `Keystore.getInstance(trustStoreType)` traverses the list of registered providers and creates a new instance of matching Keystore. So, instead of creating a new Keystore from the specified provider, the driver would  create it from the most preferred (the one that comes first in security providers list) provider. This would obviously be a breaking change too, but also would let us avoid any possible confusions. 

I am also posting links to the related PRs below. 

https://github.com/Microsoft/mssql-jdbc/pull/97
https://github.com/Microsoft/mssql-jdbc/pull/135
https://github.com/Microsoft/mssql-jdbc/pull/325
https://github.com/Microsoft/mssql-jdbc/pull/433

We would appreciate opinions on the proposed solutions. Please feel free to let us know if you have other suggestions 👍

**Comment by nsidhaye** [comment]
@ulvi : In case of non fips provider why some body need to pass fipsprovider attribute?

As a database driver we should not focus only on one FIPS provider. Now in case of IBM it is special case. One should not pass FIPS Provider in case of IBM FIPS implementation as IBM FIPS implementation strictly took values from JRE.

While other FIPS provider can give liberty to choose runtime FIPS configuration before opening SSL connection.

**Comment by ulvii** [comment]
Hi @nsidhaye ,

Please see my comment on https://github.com/Microsoft/mssql-jdbc/pull/433. Thank you.

**Comment by ajlam** [comment]
@sehrope and @ErikBergfurInfor - Do either of you have any additional thoughts/suggestions to share?

**Comment by ErikBergfurInfor** [comment]
I would go with option 2, since it cleans stuff up and we are not currently using the property.
We are using java.security to set up our FIPS environment but I believe it's still good to have options to tell the driver specifically what provider to use and not rely solely on the java.security being set up correctly.

**Comment by sehrope** [comment]
+1 to either option 2 or 3 though leaning more toward 2 as the extensibility would be useful to other users wishing to avoid editing `java.security`.

I'm usually on the side of maintaining backwards compatibility but think cleaning up the confusing property names now is good idea. I don't see any external comments on the original PR that added that feature so hard to gauge who external to Microsoft would be impacted by the change. I can't imagine it would be particularly widespread. Presumably anybody using features as recent as that would be tracking breaking changes to the driver and know it's coming. Plus they're app would break at connect time...

Somewhat related, it'd be nice if the choice of keystore itself could be externalized as a connection property. Part of the purpose of  PR #74 for adding a custom TrustManager is to supply a custom keystore on a per-connection basis without mucking with JVM-wide settings. That allows for per-connection certificate pinning without maintaining a static shared keystore. Plus the keystore doesn't have to be persisted which is a big +1 in a container/stateless deployment environment.

**Comment by nsidhaye** [comment]
Thanks @ulvii for discussion. 

FIPSProvider attribute introduced especially for keystore usage. For getting keystore instance we can pass appropriate FIPSprovider thinking of useful in custom runtime configurations for FIPS. 

`ks = KeyStore.getInstance(trustStoreType, fipsProvider);`

@ulvii showed me that even with runtime FIPS configuration one will get appropraite keystore instance without passing fipsprovider. Keystore will pick up appropriate provider. 

I am comfortable with option 3.

**Comment by ajlam** [comment]
@ErikBergfurInfor and @sehrope, thanks for your input. 

@sehrope, re: #74, apologies for the delay in this. We're investigating and will circle back. If possible, I may need to ask you to rebase the PR against the dev branch.

**Comment by ulvii** [comment]
Hi @ErikBergfurInfor, @sehrope , @nsidhaye ,

Thank you so much for the input. We decided to remove the connection property `fipsProvider`. I have attached the jar file that contains the changes to this issue. It would be great if you could test it as well :smile:

[mssql-jdbc-fips-removed.zip](https://github.com/Microsoft/mssql-jdbc/files/1258616/mssql-jdbc-fips-removed.zip)

**Comment by ErikBergfurInfor** [comment]
We don't use the _fipsProvider_ property, so we should be fine. We currently don't have the bandwidth to do a full scale test with a snapshot release

**Comment by ulvii** [comment]
#460 has been merged. Thanks to everyone for the feedback :)
