### ISSUE TITLE
Error message errors

### ISSUE THREAD

**Issue by v-xiangs** [Microsoft/mssql-jdbc#453]
## Driver version or jar name
all versions

## SQL Server version
N/A

## Client operating system
N/A

## Java/JVM version
N/A

## Table schema
N/A

## Problem description
Some error messages inside SQLServerResource.java file have grammatical/spelling issues. Please see @ulvii 's comments in PR #452 . We decide to merge #452 first and create an issue to remind us the rest.

Please note, changing error messages may break client programs if those error messages are public to the client.

## Expected behavior and actual behavior
N/A

## Repro code
N/A

**Comment by ulvii** [comment]
Fixed by #459
