### ISSUE TITLE
Version Correlation with Microsoft Website

### ISSUE THREAD

**Issue by isapir** [Microsoft/mssql-jdbc#491]
## Driver version or jar name
I don't know.  That's exactly the problem.

When I go to https://www.microsoft.com/en-us/download/details.aspx?id=54671 I get the most recent version as sqljdbc_4.2.8112.100_enu from June 5th 2017, but here I get numbers like 6.2.1.

What is the correlation between the versioning schemes?  Are the ones here more up to date?  Is this repository the official "home" of the MSSQL JDBC drivers?

Please clarify, thank you.

**Comment by ajlam** [comment]
Hi @isapir, apologies for the confusion.  

> What is the correlation between the versioning schemes?

When we open sourced the JDBC Driver ([v6.1.0](https://github.com/Microsoft/mssql-jdbc/releases/tag/v6.1.0)), we updated the naming convention for the jars to make it easier for users to understand what versions of the jars they should use. 

The previous jars, including the ones in the `sqljdbc_4.2.8112.100_enu` package, are named `sqljdbc41.jar` or `sqljdbc42.jar`. This caused a lot confusion as the `41` and `42` in the name actually corresponds to the JDBC specification number and **not** the JDBC version number. 

To help alleviate this confusion, beginning v6.1.0+, we switched to `mssql-jdbc-#.#.#.jre7.jar` and `mssql-jdbc-#.#.#.jre8.jar`. This was done to make it more straightforward to understand which jar should be used for the appropriate JDK. More info in this [blog](https://blogs.msdn.microsoft.com/jdbcteam/2017/03/31/jdbc-download-center-pages-and-repackaging/).

> Are the ones here more up to date?

Beginning v6.1.0+, we use GitHub and Maven Central to release our previews, while the Microsoft Download Center is used only to release stable/RTW versions of the driver. The most recent RTW release was [v6.2](https://github.com/Microsoft/mssql-jdbc/releases/tag/v6.2.1). The Microsoft Download Center link is [here](https://www.microsoft.com/en-us/download/details.aspx?id=55539). The Microsoft Download Center package contains the jars and extra DLLs required for XA transactions and integrated authentication on Windows. If you just want the jars, you can also get them on Maven Central. 

>  Is this repository the official "home" of the MSSQL JDBC drivers?

Yes, this GitHub repository is the official home/source code repository for the JDBC Driver. We do all active development here. 

Hope that answers your questions. Please let me know if there's anything else you'd like clarification for.

**Comment by isapir** [comment]
Thank you for clarifying.
