### ISSUE TITLE
Azure Java “Web app with MySQL in-app” unable to fetch data in Front-end from database. 

### ISSUE THREAD

**Issue by Keval0001** [Microsoft/mssql-jdbc#494]
## Driver version or jar name
com.microsoft.sqlserver 6.2.1.jre8

## SQL Server version
Please tell us what the MYSQL 6.0.6

## Client operating system
Windows 10

## Java/JVM version
 java version "1.8.0", IBM J9 VM

## Problem description
I am trying to fetch data from MySQL database which is hosted in Microsoft Azure and my spring boot maven app is also deployed in Azure.

When I am hitting my data hosting link, it displays data in JSON format on a web browser. For Example - https://xyz.azurewebsites.net/checklist displays data in JSON format.

On the other end When I am hitting my front-end link, it displays my design. For Example - https://xyz.azurewebsites.net/search.html displays HTML view.

Note - This complete app working fine on local server //localhost/3306. But it is not running fine when I am deploying it on Microsoft Azure. Kind of mismatch issue.

Can anyone please help me out? Where am I doing a mistake? 

Also, Let me know if any other details needed from my end?
-- | --

## Expected behavior and actual behavior
Actual behavior - running fine on localhost 
Expected behavior - Should run on the cloud using cloud database.

**Comment by ajlam** [comment]
Hi @Keval0001, can you please confirm which database you are using? Microsoft SQL Server/Azure SQL Database or MySQL? This JDBC Driver is to be used against Microsoft SQL Server.

**Comment by Keval0001** [comment]
@ajlam Thank for your reply! Currently, I am using MYSQL Workbench. I knew that driver will be used against Microsoft SQL Server but I tried both drivers but nothing works for me. I don't know where am I doing a mistake.
If you want I am ready to share my code snippet.

**Comment by ajlam** [comment]
@Keval0001 - You should not include the mssql-jdbc driver in your POM.xml file if you're trying to connect to a MySQL database. The mssql-jdbc driver itself is only compatible with SQL Server.

May I suggest opening a bug in the [mysql-connector-j](https://github.com/mysql/mysql-connector-j) repository? Please also take a look at some of the [getting started tutorials](https://spring.io/guides/gs/accessing-data-mysql/) available for accessing data in MySQL from a Spring application. Outside of that, my general suggestion would be to ensure that your firewall rules allow both inbound and outbound traffic to/from your application and wherever your MySQL database is hosted. 

Unfortunately, this driver repository and the team working on it focus on Java application connectivity to SQL Server and not MySQL. Closing this issue.
