### ISSUE TITLE
Issue while building

### ISSUE THREAD

**Issue by xennygrimmato** [Microsoft/mssql-jdbc#5]
When I try to build on Mac OS X, I get the following message:

```
WARNING: ConnectionID:2 ClientConnectionId: 1c5a0f8d-3638-4189-b360-5c7d9be1760f Prelogin error: host localhost port 3306 Unexpected response type:74
```
I have set a local DB's config in `src/test/serverConfig.cfg`.
How do I build the project?

**Comment by nsidhaye** [comment]
Is your SQL Server using port 3306? 

By default maven tries to run unit test cases. You can skip test by adding **-Dmaven.test.skip=true**

`mvn package -Pbuild42 -Dmaven.test.skip=true`
or
`mvn install -Pbuild42 -Dmaven.test.skip=true`

**Comment by v-nisidh** [comment]
@xennygrimmato : By adding -Dmaven.test.skip=true can you able to build ?

**Comment by xennygrimmato** [comment]
@v-nisidh `mvn install -Pbuild42 -Dmaven.test.skip=true` works for me. Thanks.
