### ISSUE TITLE
SQL database JDBC Driver support for Sharding

### ISSUE THREAD

**Issue by sarkarn** [Microsoft/mssql-jdbc#506]
## Driver version or jar name
Please tell us what the JDBC driver version or jar name is.
6.0

## SQL Server version
Please tell us what the SQL Server version is.
SQL Server 2016

## Client operating system
Please tell us what oprating system the client program is running on.
Windows

## Java/JVM version
Example: java version "1.8.0", IBM J9 VM
JDK 1.8

## Table schema
Please tell us the table schema
Not applicable
## Problem description
Please share more details with us.
Currently, SQL Database sharding client library only written on C#.Net. It means any Java client cannot utilize the sharding concept.

## Expected behavior and actual behavior
There should be Sharding client library written in Java.

## Repro code
Not Applicable.

**Comment by ajlam** [comment]
Hi @sarkarn, thanks for filing this issue. We are currently working on making the Elastic Database Client Library available in Java. Will respond back in this issue when available.

**Comment by anumjs** [comment]
Hi @sarkarn, the Elastic Database Client Library is now available: https://github.com/Microsoft/elastic-db-tools-for-java/ 
Email us at  SaaSFeedback at microsoft dot com for feedback/questions.

**Comment by cheenamalhotra** [comment]
@sarkarn Closing this issue since the Client Library is available in Java on Maven now.
> 
      <groupId>com.microsoft.azure</groupId>
      <artifactId>elastic-db-tools</artifactId>
      <version>1.0.0</version>
