### ISSUE TITLE
execute as user

### ISSUE THREAD

**Issue by Mincol** [Microsoft/mssql-jdbc#523]
## Driver version or jar name
6.1.6.jre8-preview

## SQL Server version
12.0.2269

## Client operating system
Windows 10

## Java/JVM version
1.8

## Table schema
??

## Problem description
How can I switch to different user and user schema?

## Expected behavior and actual behavior
I log in using LOG_IN_USER.
I execute java.sql.Statement.execute("execute as user = 'STATEMENT_USER'")
I expect that all subsequent SQL statement would use tables from schema associated to user STATEMENT_USER not LOG_IN_USER.

But all subsequent calls uses LOG_IN_USER schema. I need to prefix all tables.

## Repro code
Please share repro code with us, or tell us how to reproduce the issue.

**Comment by cheenamalhotra** [comment]
Hi @Mincol 

> I expect that all subsequent SQL statement would use tables from schema associated to user STATEMENT_USER not LOG_IN_USER. But all subsequent calls uses LOG_IN_USER schema. I need to prefix all tables.

If you are trying to switch to a schema that can be used by default, without specifying prefix, maybe `USE <schema>` is what you are looking for. This `<schema>` need not be prefixed in subsequent queries until next `USE` query is executed.

On the other hand, if you are looking forward to switch context explicitly as STATEMENT_USER after logging in as LOG_IN_USER, `EXECUTE AS LOGIN = STATEMENT_USER_LOGIN` should be used followed by `EXECUTE AS USER = STATEMENT_USER` which allows server-level context switching (not from within a database), provided STATEMENT_USER is created using STATEMENT_USER_LOGIN as illustrated in example  [here](https://docs.microsoft.com/en-us/sql/t-sql/statements/execute-as-transact-sql#examples).

Let us know if you have any further questions.

**Comment by v-afrafi** [comment]
Hi @Mincol . Just wanted to follow up and see if the issue is resolved per @cheenamalhotra 's comments? Thanks!

**Comment by cheenamalhotra** [comment]
Hi @Mincol closing this issue due to no response. Feel free to re-open if you have any concerns.

**Comment by Vmarci94** [comment]
Hi!

I found one solution.
My issue was, call stored procedure, on behalf user of another.
I found one microsoft test, [this](https://github.com/microsoft/mssql-jdbc/blob/9ff36a54c1f7801bf8c24d0ea073b6e160f54308/src/test/java/com/microsoft/sqlserver/jdbc/callablestatement/CallableMixedTest.java#L108).

So it's work me in Spring Boot with Hibernate:
```java
    private void execute(String executorName, String param1, String param2){
        String sql = " EXECUTE AS USER = ?; EXECUTE [MY_SP] ?,?; REVERT;";
        try (Connection connection = dataSource.getConnection();
             PreparedStatement preparedStatement = connection.prepareStatement(sql)) {

            preparedStatement.setString(1, executor);
            preparedStatement.setString(2, param1);
            preparedStatement.setString(3, param2);

            preparedStatement.execute();
            connection.commit();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
```

Important note:
You must config dataSoruce (Catalog name and Schema nem)
