### ISSUE TITLE
Document Release Schedule

### ISSUE THREAD

**Issue by sehrope** [Microsoft/mssql-jdbc#524]
When will the next release, 6.3.x, will be published as a non-preview build to Maven central?

More generally, is there guidance on when release builds will be cut and published to Maven central? I wasn't able to find anything in the project docs or wiki. Would be good to have either a documented schedule, i.e. feature merged into `dev` by X will be in release on date Y, or if that's not workable, a generic statement somewhere on the wiki that says, "*We publish versions when we feel they're ready*".

On that overall subject, I'd be in favor of more / smaller releases, ideally tied to individual new features or bug fixes, rather than wider multi PR releases. That also has the advantage of getting code tested in more real world applications sooner as the vast majority of people don't compile custom dev builds for testing. That would be a bit more load on the maintainers but hopefully the CI suite is robust enough and the rest of the deploy process could be automated enough that it's a non-issue.

Thoughts?

**Comment by nsidhaye** [comment]
May be creating milestone with tentative release date and tagging issues with Milestone might be one of way to give hints of future releases. 

https://github.com/Microsoft/mssql-jdbc/milestones

**Comment by David-Engel** [comment]
@sehrope,
Our goal is to release monthly preview builds of the JDBC driver for SQL Server which contain incremental feature additions. For non-preview releases which are deemed production ready, our goal is twice a year. Since the last stable release was June 30, the next one will likely be near the beginning of 2018.
