### ISSUE TITLE
Formatting problem with "Setting the Connection Properties" article in Docs

### ISSUE THREAD

**Issue by gordthompson** [Microsoft/mssql-jdbc#527]
The Microsoft Docs article

[Setting the Connection Properties](https://docs.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties)

has a formatting problem that renders the property values table largely unreadable. The "Description" column is significantly obscured by the right-hand sidebar regardless of how large I make my browser window (IE and Firefox), and there isn't even a horizontal scroll bar to let me see what I'm missing.

(There are a couple of familiar faces in the "Contributors" list for that page (@ajlam and @v-nisidh) so I thought I'd mention it here instead of posting yet another comment at the bottom of that page.)

**Comment by ajlam** [comment]
Thanks for filing this issue @gordthompson! 

@MightyPen, is there anything we can do about this table?

**Comment by ajlam** [comment]
@gordthompson, while we work this out, a workaround would be to zoom out a bit on the page. At 80-90% magnification, I'm able to see the full table. Sorry for this inconvenience.

**Comment by peterbae** [comment]
Since this is a formatting problem that's managed elsewhere, I've created an issue in sql-docs-pr: https://github.com/MicrosoftDocs/sql-docs-pr/issues/4989

I will keep this issue open until the problem has been solved.

**Comment by MightyPen** [comment]
Fixed by PR 5295.

**Comment by MightyPen** [comment]
@gordthompson @ajlam  @peterbae  @AfsanehR   Fixed by PR 5295.  The fix will go live late March/26 2018 (barring the unexpected).
MightyPen = GeneMi.

**Comment by peterbae** [comment]
Problem fixed, closing the issue.
