### ISSUE TITLE
SQLServerDataTable should not call toString on all objects

### ISSUE THREAD

**Issue by cogman** [microsoft/mssql-jdbc#531]
## Problem description

Right now, SqlServerDataTable will take in a type, if that type is numeric, it will call toString on that type and then it will use whatever numeric type it is turning it into to parse the output string.

String/numeric parsing in java is horribly slow and uses quite a bit of memory.  Instead of doing that, DataTable should check "Is this an instance of Number" (which often, it will be), and then should use the various "xValue" methods off of number to turn it into the desired type.  toString and parsing should only be called if this method fails.

**Comment by cogman** [comment]
Also, a bunch of these null checks and sets are superfluous.  Object arrays start off with null as the default value, per the language spec.  We should just do one null check at the beginning rather than sprinkling the null checks throughout all of the row code.

**Comment by cheenamalhotra** [comment]
Hi @cogman Thanks for raising this issue. 

I created PR #538 to make desired changes in `SQLServerDataTable` > `internalAddRow()` function. Appreciate your review and feedback on the same.

**Comment by cogman** [comment]
Pretty much exactly what I imagined it to be.  Thanks!

**Comment by cheenamalhotra** [comment]
Closing issue as PR #990 is now merged.
