### ISSUE TITLE
Survey Link is either stale or not Working

### ISSUE THREAD

**Issue by nsidhaye** [Microsoft/mssql-jdbc#532]
Survey link is not working. 

https://www.surveybuilder.com/s/uYRGS 

> Oops, this survey is no longer available. This may be because the author has removed the survey or received enough responses.

**Comment by v-afrafi** [comment]
Hi @v-nisidh . We have closed the issue for September survey, will be updating another survey soon. Thanks!

**Comment by cheenamalhotra** [comment]
Hi @nsidhaye we created new issue #536 with reference to new survey. Closing this issue. 
Results for past surveys can be found in Wiki page [here](https://github.com/Microsoft/mssql-jdbc/wiki/JDBC-Survey-Results#jdbc-driver-for-sql-server---sentiment-survey-september-2017)
