### ISSUE TITLE
Geometry and Geography typenames are not supported

### ISSUE THREAD

**Issue by jpoernomoatsafe** [Microsoft/mssql-jdbc#533]
## Driver version or jar name
mssql-jdbc-66.2.2.jre8

## SQL Server version
tested with SQL Server 2014

## Client operating system
Windows 10 x64

## Java/JVM version
java version "1.8.0_144"

## Table schema
CREATE TABLE [dbo].[my_table]([GEOM] [geography] NULL) 

## Problem description
`SQLServerPreparedStatement.getParameterMetaData()` will fail if `SQLServerPreparedStatement` was prepared using a query that contains geometry or geography column types. 
Seems that the source of the issue is, our resultSet from "exec sp_describe_uneclared_parameters ?") returns a typename of "geometry" or "geography". 
DataTypes.SSType does not have these value, and therefore an exception is thrown.

## Expected behavior and actual behavior
expected -- the method returns a `SQLServerParameterMetadata` successfully (for reference, the JDBCType for geography was VARBINARY in sqljdbc41.jar)
actual -- the following exception was thrown:

> Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: A metadata error for the parameter {0} occurred.
> 	at com.microsoft.sqlserver.jdbc.SQLServerParameterMetaData.parseQueryMeta(SQLServerParameterMetaData.java:289)
> 	at com.microsoft.sqlserver.jdbc.SQLServerParameterMetaData.<init>(SQLServerParameterMetaData.java:573)
> 	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.getParameterMetaData(SQLServerPreparedStatement.java:2799)
> 	at COM.safe.fme.JdbcBackendHelper.bindValues(JdbcBackendHelper.java:1204)
> 	... 3 more
> Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid SQL Server data type geography.
> 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:227)
> 	at com.microsoft.sqlserver.jdbc.SSType.of(DataTypes.java:185)
> 	at com.microsoft.sqlserver.jdbc.SQLServerParameterMetaData.parseQueryMeta(SQLServerParameterMetaData.java:242)
> 	... 6 more

## Repro code
for example, using the above table schema, create a prepared statement with a query of `INSERT INTO [my_table] ([GEOM]) VALUES (?)`

```
sqlServerConnection = getSQLServerConnection(); // set up SQLServerConnection
PreparedStatement statement = sqlServerConnection.prepareStatement("INSERT INTO [my_table] ([GEOM]) VALUES (?)");
statement.setQueryTimeout(5000);
ParameterMetaData metaData = statement.getParameterMetaData(); // ---> this throws an exception
```

**Comment by peterbae** [comment]
Hi @jpoernomoatsafe, thanks for creating this issue. We are currently working on adding support for Geometry/Geography datatypes, and will let you know once they are under review / merged into preview.

**Comment by peterbae** [comment]
Hi @jpoernomoatsafe, I've merged in the initial implementation for supporting Geometry/Geography datatypes into Spatial_Datatypes branch. This branch will not be merged into preview for now - but please feel free to use/test it.

**Comment by peterbae** [comment]
Geometry/Geography types are supported starting from preview release v6.5.0. Closing this issue.
