### ISSUE TITLE
Setting a BIT field to 1 with TVPs results in a 0

### ISSUE THREAD

**Issue by alexnixon** [microsoft/mssql-jdbc#539]
```
SQLServerDataTable table = new SQLServerDataTable();
table.addColumnMetadata("Wat", Types.BIT);
table.addRow(1);
```
This table will store a 0 into your database, because the `1` gets converted to `"1"` with `toString`, then parsed to `false` with `Boolean.parseBoolean`.

I personally disagree with `SQLServerDataTable::addRow`'s general approach of "call `toString` on the argument then parse it in a lax manner". I think it would be better to:

- Handle known types specifically, e.g. if you attempt to set a BIT field with a `Byte`, cast it to a `Byte` and handle the value
- Handle known values specifically, e.g. allow 0, 1, true, false to set a BIT field
- Reject unknown types and nonsense values with an exception

**Comment by gordthompson** [comment]
Related: #538 (via #531 ).

**Comment by cheenamalhotra** [comment]
Thanks @gordthompson for relating PR to the issue. 

> Handle known types specifically, e.g. if you attempt to set a BIT field with a Byte, cast it to a Byte and handle the value

I guess that's implemented in PR.

> Handle known values specifically, e.g. allow 0, 1, true, false to set a BIT field

We will update PR to parse inputs (1, 0) for Boolean type (True, False) respectively.

> Reject unknown types and nonsense values with an exception

SQL Server does that for us, so additional logic in Java is not needed. We rely on SQLException and throw it directly. Is there any specific case where it will be helpful [_other than integers 0,1 for Boolean that will now be handled_]?

**Comment by alexnixon** [comment]
Thanks for the update. I disagree with your point that we can rely on SQL Server to reject unknown types because the code frequently calls `toString` on the values passed in then parsing them. So all the downstream code sees is whatever type the string is subsequently parsed as.

To clarify I've come up with some examples by looking at the code (though I haven't run these so correct me if I'm wrong). I believe the PR does fix the BIT case that I reported but there are still several cases where I think the code continues to be overly permissive and others where I think the PR has introduced regressions:

```
Object unknownTypeInstance = new Object() { @Override public String toString() { return "1"; } };

{
    SQLServerDataTable table = new SQLServerDataTable();
    table.addColumnMetadata("c1", Types.BIT);

    //     Before PR: insert 0
    //      After PR: insert 1
    // What I expect: REJECT because the type is unknown
    table.addRow(unknownTypeInstance);

    //     Before PR: insert 0
    //      After PR: insert 1
    // What I expect: REJECT because of truncation
    table.addRow(0.6f);

    //     Before PR: insert 0
    //      After PR: insert 1
    // What I expect: REJECT because of truncation (debatable given 1.0f is representable exactly, but I think a rule of
    //                "you can't set integral fields with floating point types" is easy to grok).
    table.addRow(1.0f);

    //     Before PR: insert 0
    //      After PR: insert 0
    // What I expect: insert 0
    table.addRow(0);

    //     Before PR: insert 1
    //      After PR: insert 1
    // What I expect: insert 1
    table.addRow(1);

    //     Before PR: insert 0
    //      After PR: insert 0
    // What I expect: REJECT because of truncation
    table.addRow(3);
}

{
    SQLServerDataTable table = new SQLServerDataTable();
    table.addColumnMetadata("c1", Types.SMALLINT);

    //     Before PR: REJECT with NumberFormatException
    //      After PR: insert (1234567 % 2^16)
    // What I expect: REJECT because of truncation
    table.addRow(1234567);

    //     Before PR: insert 1
    //      After PR: insert 1
    // What I expect: REJECT because the type is unknown
    table.addRow(unknownTypeInstance);

    //     Before PR: REJECT with NumberFormatException
    //      After PR: insert 1
    // What I expect: REJECT because of truncation
    table.addRow(0.6f);

    //     Before PR: REJECT with NumberFormatException
    //      After PR: insert 1
    // What I expect: REJECT because of truncation
    table.addRow(1.0f);

    //     Before PR: REJECT with NumberFormatException
    //      After PR: insert 3
    // What I expect: REJECT because of truncation
    table.addRow(3.0f);
}
```

**Comment by cheenamalhotra** [comment]
@alexnixon Thanks for your feedback!

> I disagree with your point that we can rely on SQL Server to reject unknown types because the code frequently calls toString on the values passed in then parsing them. So all the downstream code sees is whatever type the string is subsequently parsed as.

Sorry for the confusion, I meant to say about Datatype Parser and not SQL Server - thanks for clearing out. 

We are currently reviewing regressions and will get back to you soon on this. Welcoming any more suggestions/improvement areas for #538 .

**Comment by alexnixon** [comment]
Thanks. I've added my suggestions onto #538 directly.

**Comment by cheenamalhotra** [comment]
Closing issue as PR #990 is now merged.
