### ISSUE TITLE
MSSQL JDBC library needs to use Shade plugin to prevent class path versioning issues

### ISSUE THREAD

**Issue by nicolehaugen79** [Microsoft/mssql-jdbc#551]
We have noticed an issue with some of the Azure Mgmt SDKs in that they don't repackage their dependencies into a custom Microsoft namespace, using either the Maven Shade plugin or the Gradle Shadow plugin.  Without using these plugins, this can cause versioning issues when this SDK is used in conjunction with other open source libraries using similar, but different versions of dependencies (e.g. 'class path hell').  Often, when class path hell occurs, you'll see an exception at run time saying "NoSuchMethod" because there are two versions of the same dependency used, but the wrong version gets loaded for one of the libraries that uses it.  Using the Shade\Shadow plugins will prevent this.

I'm logging this issue because in looking at the POM for the mssql-jdbc library, it doesn't reference the Maven Shade plugin.  Please take a look at using this plugin to ensure that version conflicts don't occur when using the mssql-jdbc SDK.

Here's a link to a similar issue that was logged against the Document DB library that describes this type of problem in greater detail since a versioning conflict issue was found when using the Document DB library in combination with the App Insights SDK. [https://github.com/Azure/azure-documentdb-java/issues/90](url)

**Comment by cheenamalhotra** [comment]
Hi @nicolehaugen79 

We haven't come across any major concerns for conflicts from customers working with our dependencies yet. It might be a good feature for client applications, but its definitely not for the driver. I did some research on pros and cons of using this plugin and below are our concerns:

- Using shade plugin will create packages for the dependencies in driver jars which we don't want to do in any scenario. 
- The dependent jars are optional for clients and we do not want to force them with the driver.
- Maven dependency resolution would fail for clients if we implemented this.
