### ISSUE TITLE
Cannot query for time only variables

### ISSUE THREAD

**Issue by rPraml** [Microsoft/mssql-jdbc#559]
## Driver version or jar name
latest (6.3.5)

## SQL Server version
SQL Server 14.0.3006

## Client operating system
Windows

## Java/JVM version
Example: java version "1.8.x", Oracle VM

## Table schema
```sql
create table dateandtime (id integer not null, 
 my_date date, 
 my_time time, 
 my_timestamp datetime2 
 constraint pk_esimple primary key (id))
```

## Problem description
A prepared statement with `select * from dateandtime where my_time = ?` and `pstmt.setTime(1,...)` fails with `com.microsoft.sqlserver.jdbc.SQLServerException: The data types time and datetime are incompatible in the equal to operator.`

## Expected behavior and actual behavior
Query with Time should work

## Repro code
See https://github.com/Microsoft/mssql-jdbc/pull/558

**Comment by v-afrafi** [comment]
Hello @rPraml,
Since earlier versions of the SQL Server do not support time datatype, the driver by default sends the time datatype as datetime. In order to send value as time, you need to change the connection property of `sendTimeAsDatetime ` to false. 

You can also read further regarding how time values are sent on [msdn docs](https://docs.microsoft.com/en-us/sql/connect/jdbc/configuring-how-java-sql-time-values-are-sent-to-the-server). Thank you.

**Comment by rPraml** [comment]
Hello @v-afrafi 
applying `sendTimeAsDatetime=false` will solve this issue, but I'm wondering, if there are still more options that are required, so that the (latest) driver works correctly with the latest SQL-Server.
(I understand that there may be options to enable backward compatiblility to servers <= 2005, but 2005 is how old now?)

I also read the msdn docs:
> In SQL Server JDBC Driver 3.0, sendTimeAsDatetime is true by default.
> In a future release, the sendTimeAsDatetime connection property may be set to false by default. 

I would really appreciate if the default value would be changed to false NOW. (or at least soon)
 
My expection is, if I develop a new application with the latest driver and sql-server version, that everything works out of the box and does not require to apply a bunch of compatibility-parameters to the connection strings, that fixes issues that were related to SQL-Server 2005 (which extended support ended at April 12, 2016) 

I also updated the Pull Request with additional tests to show, that the behaviour is a bit inconsistent: If I use TVP & TIME - everything works fine (also with `sendTimeAsDatetime=true`)

cheers
Roland

**Comment by v-afrafi** [comment]
Hi @rPraml . That is correct, the property was added for backward compatibility of the driver, however, I agree with your point in changing the default value.  
Will discuss this with the team and will update you further on this. Thanks.

**Comment by v-afrafi** [comment]
Hi @rPraml , thanks for creating this issue. We have merged pr #572 which will address this.

**Comment by v-afrafi** [comment]
@rPraml  also, we will soon be updating the MSDN documentation regarding this change with the upcoming v6.4.0 release.

**Comment by ecki** [comment]
With later compat levels (>120) it looks like the driver sends DATETIME2 even when the column is not of that time. That causes problems in our case. Is there a property for that type as well (or could the driver actually inspect the target types (and not require binding column types or altering database)?

**Comment by rene-ye** [comment]
Hi @ecki, can you create a separate issue and describe/provide repro for the scenario that's currently not working for you?
