### ISSUE TITLE
Support for using the credential from platform GSS integration for Kerberos

### ISSUE THREAD

**Issue by kilokahn** [microsoft/mssql-jdbc#580]
## Driver version or jar name
Tested with 6.3.6.jre8-preview

## SQL Server version
Tested with 12.0.5207

## Client operating system
Tested with RHEL (3.10.0-693.5.2.el7.x86_64)

## Java/JVM version
```
>java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

## Table schema
N/A

## Problem description
I was trying to use the platform GSS integration (as described in "Native platform GSS integration" at https://docs.oracle.com/javase/8/docs/technotes/guides/security/jgss/jgss-features.html), and noticed that the code in `com.microsoft.sqlserver.jdbc.KerbAuthentication#intAuthInit` assumes the use of only JAAS. It also has support for impersonated credentials, but not for the use of the default initiator principal as defined in `org.ietf.jgss.GSSManager#createContext(org.ietf.jgss.GSSName, org.ietf.jgss.Oid, org.ietf.jgss.GSSCredential, int) `

If we define a means for allowing the use of this default principal (from the platform GSS), we can let the `GSSManager` create the appropriate `GSSCredential` for us.

### Expected behavior
When the `sun.security.jgss.native` system property is set to true, the platform GSS implementation should be used for GSSCredential creation and JAAS configuration files are not necessary.
### Actual behavior
When the `sun.security.jgss.native` system property is set to true, mssql-jdbc doesn't use the platform GSS implementation, but rather still goes down the JAAS path and expects credentials to be provided.

## Repro code
Try with any MS-SQL server that uses Kerberos for authentication and whose client attempts to use the platform GSS integration by setting `-Dsun.security.jgss.native=true`. I have added a sample project in https://github.com/kilokahn/mssql-jdbc/blob/default-principal-usage-java-kerberos/src/samples/platform-gss/src/main/java/PlatformGSS.java 

## Possible fix and contributing code
IMO, there are 2 options:
1. We can try to model the platform GSS authentication as a new AuthenticationScheme and introduce an implementation of com.microsoft.sqlserver.jdbc.SSPIAuthentication that specifically addresses this scheme where the GSSManager delegates the creation of the GSSCredential to the platform (host)
2. Introduce an additional flag with the `JavaKerberos` AuthenticationScheme (say `useDefaultPrincipal`) that will be used to have the GSSManager delegates the creation of the GSSCredential to the platform (host). EDIT: in hindsight the flag is better named as `usePlatformGssCredential`?

I took a shot at approach 2 [here](https://github.com/kilokahn/mssql-jdbc/tree/default-principal-usage-java-kerberos). Can you please see if this makes sense? Thanks!

**Comment by ulvii** [comment]
Hi @kilokahn ,

Please note that the driver already provides a default JAAS configuration, JAAS configuration files are used only if a user wants to request a different configuration. You should be able to create a Kerberos ticket with `kinit` and connect without providing JAAS files. Please let me know if you need help with that.

As far as I understand, you would still need to create a Kerberos ticket for native GSS Integration and I don't see how it is different from the current behavior of the driver.

**Comment by kilokahn** [comment]
Thanks for the reply @ulvii . 

> You should be able to create a Kerberos ticket with kinit and connect without providing JAAS files. Please let me know if you need help with that.

Can you please point to some code that demonstrates this? Maybe that will help me understand this better.

> As far as I understand, you would still need to create a Kerberos ticket for native GSS Integration and I don't see how it is different from the current behavior of the driver.

For native GSS integration, if the `GSSCredential` in the call to `org.ietf.jgss.GSSManager#createContext(org.ietf.jgss.GSSName, org.ietf.jgss.Oid, org.ietf.jgss.GSSCredential, int)` (i.e. the 3rd param) is left blank, as per the [GSSManager javadoc](https://docs.oracle.com/javase/8/docs/api/org/ietf/jgss/GSSManager.html#createContext-org.ietf.jgss.GSSName-org.ietf.jgss.Oid-org.ietf.jgss.GSSCredential-int-) (and tracing through the code), the external (non-java) GSSAPI is queried to obtain the credential. With this, there is no need for the Java code to create any kerberos ticket and it will reuse the credential from the external (or platform) GSSAPI. This is the same logic that happens in the `jtds` driver code  - see [this snip](https://github.com/milesibastos/jTDS/blob/1b23cdd050309aa49ab89ce784be1970e43f5141/src/main/net/sourceforge/jtds/jdbc/TdsCore.java#L4594) from one of the clones of `jtds` source code.

Thanks!

**Comment by ulvii** [comment]
Kerberos ticket is created externally, using `kinit` tool.

On Windows, it comes with JDK, on RHEL you can try to install `krb5-workstation` package.  See "To install packages for a Kerberos client" section [here](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/managing_smart_cards/installing-kerberos).

Once you have `kinit` installed, follow the instructions of the tool to create a Kerberos ticket. You can verify the ticket with `klist` tool.

After creating a proper Kerberos ticket, remove the following lines from your [repro code ](https://github.com/kilokahn/mssql-jdbc/blob/default-principal-usage-java-kerberos/src/samples/platform-gss/src/main/java/PlatformGSS.java)and you should be able to connect.

```
driverProperties.setProperty("useDefaultPrincipal", "true"); // Additional property to be added
System.setProperty("sun.security.jgss.native", "true");
```
The driver will use the ticket to authenticate. You can also run your application with `sun.security.krb5.debug=true ` option to see the debug trace.

**Comment by kilokahn** [comment]
Thanks again @ulvii for the reply. The point of using setting `sun.security.jgss.native` to true was that we need not create the ticket ourselves and reuse credentials provided by the platform GSS implementation.

**Comment by ulvii** [comment]
From the [link](https://docs.oracle.com/javase/8/docs/technotes/guides/security/jgss/jgss-features.html) you have posted above: 

`Unlike the default Java GSS implementation, which relies on the JAAS KerberosLoginModule for initial credential acquisition, when using native GSS, the initial credential should be acquired beforehand. That is, call kinit prior to calling JGSS APIs.`

Am I missing something?

**Comment by kilokahn** [comment]
The `kinit` call is indeed done but not part of the java code corresponding to the jdbc driver usage. It is done much before (say as part of shell logon and the TGT is refreshed periodically) and it is hence available to the platform GSS when the `createContext` call is made.

I was suggesting the introduction of the flag (say `usePlatformGssCredential`) which will automatically use the credential from the platform GSS, if available, or will error out if unavailable.

**Comment by ulvii** [comment]
@kilokahn , `kinit` call **is not** "part of the java code corresponding to the jdbc driver usage", you are not required to have any JDBC specific configuration when creating a ticket ( standard Kerberos ticket ). You can create them as part of shell logon or use the existing tickets. The driver will look for the ticket in the default credential cache and use it to authenticate. 

Please try the [steps ](https://github.com/Microsoft/mssql-jdbc/issues/580#issuecomment-351874600) above.

**Comment by kilokahn** [comment]
Thanks for your patience (and apologies for misinterpreting your directions in creating the kerberos ticket) @ulvii :slightly_smiling_face: 

As per the [steps](https://github.com/Microsoft/mssql-jdbc/issues/580#issuecomment-351874600) above, when we don't set the `sun.security.jgss.native` to true, the JDK Kerberos implementation (in package `sun.security.jgss.krb5`) will be used, which is not what I am looking for. Rather I am looking for the JGSS API (in package `sun.security.jgss`) to delegate the credential fetch implementation to the platform kerberos implementation (like MIT Kerberos, etc. which might be installed on the RHEL box, and hence `native`). There are subtle differences between the two implementations (like referrals mechanism for multiple realms, support for different ciphers, etc.) which cause the ccaches to not be trivially interoperable.

The point was to be able to set the `sun.security.jgss.native` to true, and have no use of the JDK Kerberos implementation whatsoever. I will try to convert the changes on https://github.com/kilokahn/mssql-jdbc/tree/default-principal-usage-java-kerberos into a PR. 

Again, I appreciate the help you are providing here :+1:

**Comment by kilokahn** [comment]
Hello @ulvii 

Is there anything else that I can help with to get this moving forward?

Thank you!

**Comment by cheenamalhotra** [comment]
Hi @kilokahn 

We appreciate your contribution for introducing platform gss for Kerberos authentication. We are currently reviewing the PR and will come back to you soon!

Thanks!

**Comment by kilokahn** [comment]
@cheenamalhotra / @ulvii  - is there an update on this one? Thanks!

**Comment by ulvii** [comment]
Closing the issue as the driver already provides this functionality via `gsscredential` connection property. 
```
GSSCredential credential = GSSManager.getInstance().createCredential(null, GSSCredential.DEFAULT_LIFETIME, new Oid("1.2.840.113554.1.2.2"), GSSCredential.ACCEPT_ONLY);
SQLServerDataSource ds = new SQLServerDataSource();
ds.setGSSCredentials(credential);
```
Please let us know if you have any questions.

**Comment by aanavaneeth** [comment]
@ulvii How should we use this? in tyhe connection string? Could you please give an example connection string?

**Comment by aanavaneeth** [comment]
ok. I tried it but getting "no valid creds" error :(

**Comment by aanavaneeth** [comment]
please reopen this request. I don't think the given solution is working.

**Comment by aanavaneeth** [comment]
hello, writing this for those who face issues like me: 
The solution @ulvii provides work. :) 

below is the data source creation code
<pre>
 @Bean
  DataSource dataSource() throws SQLException, GSSException {
        GSSCredential credential = GSSManager.getInstance().createCredential(null, GSSCredential.DEFAULT_LIFETIME, new Oid("1.2.840.113554.1.2.2"), GSSCredential.ACCEPT_ONLY);
        SQLServerDataSource dataSource = new SQLServerDataSource();
        dataSource.setURL("jdbc:sqlserver://servername;databaseName=dbname;integratedSecurity=true;authenticationScheme=JavaKerberos;");
        dataSource.setGSSCredentials(credential);
        dataSource.getConnection();
        return dataSource;
    }
</pre>
apart from that we need to set 3 jvm params:

<pre>
-Dsun.security.jgss.native=true
-Dsun.security.jgss.lib=/usr/local/libexec/libjgssfix.so
-Djavax.security.auth.useSubjectCredsOnly=false
</pre>
