### ISSUE TITLE
Date consistently displayed in 2 days difference

### ISSUE THREAD

**Issue by BharahthyKannan** [Microsoft/mssql-jdbc#583]
## Driver version or jar name
sqljdbc4-3.0

## Client operating system
Windows

## Java/JVM version
Java version "1.8.0",

## Problem description
Connected to MSSQL database Via Squirrel client and driver sqljdbc4-3.0.   The result especially the data column is consistently shifted to 2 days. 

## Expected behavior and actual behavior
Squirrel client to connect MSSQL
driver sqljdbc4-3.0 is used. 
Created datetime2 column in the table is 12/12/2017. But the result is generated as 10/12/2017

## Repro code
Use sqljdbc4-3.0

**Comment by cheenamalhotra** [comment]
Hi @BharahthyKannan 

Driver versions 3.0 and 4.0 are out of mainstream support as you can see the support matrix [here](https://docs.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix).. 
Request you to test your usecase with latest version of driver and report for any issues.

**Comment by cheenamalhotra** [comment]
Hi @BharahthyKannan are you getting same error with latest driver as well?

**Comment by rene-ye** [comment]
The issue has been tested with Squirrel and the latest version of Mssql-JDBC. There does not appear to be a discrepancy between the datetime2 inputted and the datetime2 displayed. Closing the issue for now.
