### ISSUE TITLE
Set the jre8 version as default

### ISSUE THREAD

**Issue by gstojsic** [Microsoft/mssql-jdbc#59]
Currently issuing the command:
`mvn clean install`
for which most java developers expect that it should build something, issues an ugly build error. This is because a profile must be set in order for the build to succeed. Currently there are two profiles, one for jre8 and one for jre7. Consider making the jre8 default so that the above command builds the jre8 version by default.

**Comment by v-xiangs** [comment]
fixed by PR #60 thank you
