### ISSUE TITLE
Implement JDBC 4.1 getObject

### ISSUE THREAD

**Issue by marschall** [Microsoft/mssql-jdbc#6]
The driver currently lacks critical JDBC 4.1 methods. Most notably:

* [ResultSet#getObject(int,Class)](https://github.com/Microsoft/mssql-jdbc/blob/master/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java#L2384)
* [ResultSet#getObject(String,Class)](https://github.com/Microsoft/mssql-jdbc/blob/master/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerResultSet.java#L2401)
* [CallableStatement#getObject(int,Class)](https://github.com/Microsoft/mssql-jdbc/blob/master/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java#L733)
* [CallableStatement#getObject(String,Class)](https://github.com/Microsoft/mssql-jdbc/blob/master/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerCallableStatement.java#L754)

These limitations make it impossible to retrieve [Java 8 Date and Time API](http://www.oracle.com/technetwork/articles/java/jf14-date-time-2125367.html) data types.

**Comment by ajlam** [comment]
@marschall - would require adding new APIs. Filing as an enhancement and for follow-up investigation.

**Comment by marschall** [comment]
I don't see this as an enhancement but as a compliance issue. These are existing JDBC 4.1 APIs. I do not see how you can claim compliance yet do not implement these APIs.

**Comment by ajlam** [comment]
@marschall - I am not 100% well versed with the JDBC 4.1 API. We are following up to understand if the APIs you mentioned above are completely required for JDBC 4.1 compliance.

**Comment by v-mabarw** [comment]
@marschall @ajlam The JDBC specification identifies features that are required for compliance as well as enhancements that are considered optional.  I've confirmed that the getObject methods mentioned here fall under the optional category (if you want more detail, you can refer to Chapter 6 in the [4.1 specification](http://download.oracle.com/otn-pub/jcp/jdbc-4_1-mrel-spec/jdbc4.1-fr-spec.pdf))

**Comment by marschall** [comment]
@v-mabarw I see, chapter 6.3, you are correct. You may want to delete [these comments](https://github.com/Microsoft/mssql-jdbc/search?utf8=✓&q=%22The+driver+currently+does+not+implement+JDDBC+4.1+APIs%22&type=Code) as they are all in optional methods (and contain a typo).

**Comment by v-mabarw** [comment]
@marschall Thanks for pointing out those comments, we'll update them & fix the typo.

Am I correct in understanding that you are still looking for those APIs to be implemented?

**Comment by marschall** [comment]
@v-mabarw yes, I would still like to see these methods implemented. The main reason being that these methods are the only way to use Java 8 Date and Time types.

**Comment by v-xiangs** [comment]
Thank you @marschall the PR is merged now. We very appreciate your contribution!
