### ISSUE TITLE
License mismatch between this and the file from Download Center

### ISSUE THREAD

**Issue by psy-q** [Microsoft/mssql-jdbc#602]
I believe there is a mismatch of licenses between the compiled version of this library:

https://www.microsoft.com/en-us/download/details.aspx?id=55539

And the one used inside this repository (MIT license). The compiled version from the Download Center ships with a proprietary license that allows no modification and limits redistribution. Which license is now applicable, or does it vary depending on where one downloads from?

**Comment by David-Engel** [comment]
Hi @psy-q ,

The license on this repository if just for the JDBC driver and its source.

The license at the Microsoft Download Center covers the downloadable package which includes additional libraries not part of this repository. The license for those allows redistribution but no modification as the additional libraries are not open source.

Regards,
David

**Comment by psy-q** [comment]
Thus when one just needs the JDBC driver, it's fine to pull it from the raw URL from GitHub (e.g. during a build process) and add the MIT license to it when redistributing it?
