### ISSUE TITLE
the file mssql-jdbc-6*.jar fails in OWASP Dependency Checker

### ISSUE THREAD

**Issue by mcleanl** [Microsoft/mssql-jdbc#604]
## Driver version or jar name
Please tell us what the JDBC driver version or jar name is.
tried 6.2.1.jre8 and 6.2.2.jre8 however this issue has been going on for a while.  the newer version fo the OWASP Dependency Checker is more fussy  and fails.  The older version I was previously using flagged the problem (Content in prolog of pom) but did not fail.

## SQL Server version
Please tell us what the SQL Server version is.
Not relevant to this issue

## Client operating system
Please tell us what operating system the client program is running on.
Windows (Server 2012 R2) however that is not relevant to this issue.

## Java/JVM version
Example: java version "1.8.0", IBM J9 VM
1.8.0_144

Using OWASP Dependency Checker CLI version 3.1.0 (latest version) on a java project that includes the mssql-jdbc dependency.

<dependency>
			<groupId>com.microsoft.sqlserver</groupId>
			<artifactId>mssql-jdbc</artifactId>
			<version>6.2.2.jre8</version>
		</dependency>

Fails with the following error (reproduceable on every build)

Complains about the pom prolog.

Appears to be missing first line xml prolog in pom.xml and this is causing the issue.

`<?xml version="1.0" encoding="UTF-8"?>`

Could we have it added please in 6.3?  Thank you

**Comment by cheenamalhotra** [comment]
Hi @mcleanl Thanks for bringing up the issue. 
I created PR #606 with desired tag, we'll add this in our next release.

**Comment by cheenamalhotra** [comment]
Hi @mcleanl We merged the PR referred above, and this tag will be available in our next stable release v6.4.0. We cannot add it back to 6.3.x as they were preview releases and we generally don't update them. 

Let us know if you have any concerns.

**Comment by cheenamalhotra** [comment]
Closing the issue as the PR was merged. 
Feel free to reopen if needed.
