### ISSUE TITLE
Remove obsolete methods from DriverJDBCVersion

### ISSUE THREAD

**Issue by gstojsic** [Microsoft/mssql-jdbc#61]
If I understand correctly the current codebase supports jdbc 4.1 and jdbc 4.2 specs. This means that there is no need to check if the driver supports jdbc 4.1 and lower since 4.1 is the earliest jdbc version implemented by the driver. Therefore I believe that the methods in DriverJDBCVersion:
`checkSupportsJDBC4`
and
`checkSupportsJDBC41`
are obsolete and can safely be removed. There are just under 200 references in the code for the two methods and removing them would make the code much cleaner. The methods are no-ops and are probably removed by the compiler anyway.

**Comment by marschall** [comment]
As #187 has been merged I believe this can be closed.
