### ISSUE TITLE
Retry logic for prepared statements

### ISSUE THREAD

**Issue by TobiasSQL** [Microsoft/mssql-jdbc#628]
https://github.com/Microsoft/mssql-jdbc/blob/a64b9ef50076ab42eba898d76ae45db27ad24c45/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerPreparedStatement.java#L568

@cheenamalhotra 

With the re-introduction of retry logic for prepared statements we should not retry if the statement needs to be prepared. For some reason this was removed late in pr #618 and needs to be put back.

I.e. for `retryBasedOnFailedReuseOfCachedHandle` pass `needsPrepare` and return false if `needsPrepare` is `true`.

**Comment by TobiasSQL** [comment]
In addition, the check for error number 99586 should be removed from the same method.

**Comment by cheenamalhotra** [comment]
Hi @TobiasSQL 

Created PR #629 - kindly review.

**Comment by TobiasSQL** [comment]
Cool, started review.

**Comment by cheenamalhotra** [comment]
Closing issue as requested changes merged to driver.
