### ISSUE TITLE
Suggestion : continuous calls of StringBuilder.append 

### ISSUE THREAD

**Issue by o0lwj0o** [Microsoft/mssql-jdbc#654]
Hi,
&nbsp;&nbsp;&nbsp;&nbsp;I have found some continuous calls about `StringBuilder.append(..)` in some files. For example, there are six continuous calls in the function xidDisplay from the file mssql-jdbc/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerXAResource.java. 
```Java
static String xidDisplay(Xid xid) {
        if (null == xid)
            return "(null)";
        StringBuilder sb = new StringBuilder(300);
        sb.append("formatId=");
        sb.append(xid.getFormatId());
        sb.append(" gtrid=");
        sb.append(Util.byteToHexDisplayString(xid.getGlobalTransactionId()));
        sb.append(" bqual=");
        sb.append(Util.byteToHexDisplayString(xid.getBranchQualifier()));
        return sb.toString();
 }
```
&nbsp;&nbsp;&nbsp;&nbsp;If it was achieved like `StringBuilder.append(..).append(..)append(..)`, it will promote its performance.

**Comment by peterbae** [comment]
Hi @o0lwj0o, thanks for the input. It looks like there is no performance difference between the two styles: https://softwareengineering.stackexchange.com/questions/173377/java-performance-of-stringbuilder-append-chains

Will close this issue soon unless there's something else you want us to look at regarding this.
