### ISSUE TITLE
Replace synchronized increment integer patterns with AtomicInteger

### ISSUE THREAD

**Issue by tonytamwk** [Microsoft/mssql-jdbc#67]
Simpler code with less synchronized and better performance

**Comment by v-xiangs** [comment]
@tonytamwk thank you for your suggestion. We will consider it for future enhancement.

**Comment by tonytamwk** [comment]
@v-xiangs I've done the changes. Can I have right to push?

**Comment by ajlam** [comment]
@tonytamwk, can you please open a PR in the dev branch?

**Comment by v-nisidh** [comment]
Closing this issue as #93 is merged back to dev 30 days back. 
Thanks again @tonytamwk for your contribution.
