### ISSUE TITLE
Should InputStream be open after resultset is closed?

### ISSUE THREAD

**Issue by CheriePun** [Microsoft/mssql-jdbc#697]
## Driver version or jar name
- sqljdbc4:4.0
- mssql-jdbc:6.5.2.jre8-preview

## SQL Server version
2016

## Client operating system
MacOS

## Java/JVM version
1.8.0_101

## Table schema
Table: test
Columns
- id: autogenerated
- data: VARBINARY(MAX)

## Problem description
I would like to pass the InputStream which is generated from reading a VARBINARY(MAX) column to another method for processing. However, it seems like the stream is closed right after the resultset is closed. According to rene-ye's comment in https://github.com/Microsoft/mssql-jdbc/issues/567 , "The JDBC spec also states that the user should have access to the blob even after the statement has been closed, and the driver's current behavior does not reflect that." , the fix was released in 6.5.0 but I am still have trouble using the stream. 

I have written three tests to show what I have understood the behaviour of the InputStream to be: https://github.com/CheriePun/binary-stream-example . All three ways of getting the stream from a blob should remain accessible outside of the rowmapper.  _lobHandler()_ shows the current implementation in my code which is working with the jtds driver. _getBlobGetBinaryStream()_ will work with the older driver, however I believe this will load the entire data into memory which is something I am trying to avoid.

Please correct me if I am wrong in interpreting what the expected behaviour for the InputStream, or the implementation of the read for the InputStream from a blob.

## Expected behavior and actual behavior
Input stream should remain open after resultSet is closed

## Repro code
https://github.com/CheriePun/binary-stream-example

Using the old jdbc driver 4.0 will pass the test getBlobGetBinaryStream() but not the other two. Using the newest jdbc driver 6.5.2.jre8-preview will fail all three tests.

Thank you very much!

**Comment by rene-ye** [comment]
Hi @CheriePun, the LoB objects were changed in a way to be available for the user after the Resultset/Connection is closed. However, this does not apply to an Inputstream created by the user. When requesting a stream, either through getBinaryStream() for Blobs or getCharacterStream() for Clobs/Nclobs, a user is opting to maintain a stream to the Resultset column instead of loading the data into memory. Closing the stream, by closing the Resultset object, moving the Resultset cursor, or the Connection object, will terminate that stream.

The changes address the availability of data in the LoB objects themselves, which is now available even after the Resultset/Connection is closed assuming the user did not close the LoBs. Calling either getBinaryStream() or getCharacterStream() after the Resultset/Connection closes will now return the user a working stream.

```Java
//create connection object conn, and ResultSet object rs
Blob b = rs.getBlob(1);
Inputstream is = b.getBinaryStream(); //streaming from the database
is.read(); //works as expected
rs.close(); //blob data is loaded into memory here
is.read(); //fails with connection is closed, we can't stream from a connection that's closed
is = b.getBinaryStream(); //this is a new Inputstream, made from the data in memory
is.read(); //now this works
```

I suggest choosing either to stream a LoB or to load it into memory. Even though the functionality of using both on a single LoB is possible, it may bring unwanted behavior. E.g. some users want to continue to read the stream at the index before the Resultset/Connection closed, while others expect a fresh new stream (the latter is the current behavior).

I hope I've been helpful in clearing up any confusion regarding the implementation. If you have more questions, feel free to post them here.

**Comment by CheriePun** [comment]
Hi @rene-ye, thank you for replying to so quickly. I have a few questions regarding your reply:

- > the LoB objects were changed in a way to be available for the user after the Resultset/Connection is closed. However, this does not apply to an Inputstream created by the user. 

   What would be considered to be a stream that is not created by the user?

- Could you provide an example on how I could stream a LoB so that the data is not loaded completely into memory please? It seems that behind the scene the `LoB.getBlobAsBinaryStream()` is either calling `getBinaryStream()` or `getBlob().getBinaryStream()`, but both of these were called while the result set is opened. Wouldn't this mean the stream returned by the LoB will still be closed after resultset is closed?

Thanks for helping me out!

**Comment by rene-ye** [comment]
> What would be considered to be a stream that is not created by the user?
My choice of wording here was poor. What I meant by this statement was that the user requests the LoB to create a stream for them. If you were wondering whether a user could receive a stream which would not be affected by closing the Resultset object, moving the Resultset cursor, or the Connection object, the answer is unfortunately no.

> Could you provide an example on how I could stream a LoB so that the data is not loaded completely into memory
If there are issues with hardware capabilities compared to LoB size, I strongly recommend handling each LoB before moving onto another.
```java
//create connection conn and resultset rs
//loop through blobs
Blob b = rs.getBlob(i);
Inputstream is = b.getBinaryStream();
/*
process the input stream here, parsing what is needed or passing other functions what they need
*/
is.close();
b.free(); //freeing the blob so it doesn't get populated when we move onto the next one. Important if memory is an issue
//loop end
rs.close();
conn.close();
```
If multiple other functions need to parse the inputstream, I recommend using the Inputstream.reset() functionality as the streams offered by the LoB objects are all mark supported.

**Comment by CheriePun** [comment]
Thanks for the reply again. Sorry for asking so many questions but I am new to using Blob and streaming it and all that jazz. 

From my understanding of your answer, we can't stream from the database directly outside of the result set, is that right? In that case, the following code would not work? 

My use case is that I would like to pass the InputStream to another class for handling the data, which is not in the scope of the result set. This is how we used to do it with the jtds driver to avoid loading the whole data into memory.

```
  @Test
  public void lobHandler() throws IOException {

    String sql =
        " INSERT INTO test (Data) " +
        " VALUES (:data) ";

    KeyHolder keyHolder = new GeneratedKeyHolder();

    SqlParameterSource params = new MapSqlParameterSource().
        addValue("data", new SqlLobValue("Hello World"), Types.BLOB);

    jdbcTemplate.update(sql, params, keyHolder);

    int id = keyHolder.getKey().intValue();

    RowMapper<InputStream> rowMapper = (rs, rowNum) -> lobHandler.getBlobAsBinaryStream(rs, "Data");
    String sql1 =
        " SELECT Data " +
        " FROM test " +
        " WHERE id = :id ";

    SqlParameterSource params1 = new MapSqlParameterSource("id", id);

    InputStream inputStream = jdbcTemplate.queryForObject(sql1, params1, rowMapper);

    assertTrue(inputStream.available() > 0);
  }

```
Thanks again, really appreciate your help.

**Comment by rene-ye** [comment]
If I understand JTDS's LoB streaming correctly, they load the LoB into a file, and then stream from the file. This approach avoids loading the objects in memory and is fundamentally different from the way the Microsoft JDBC Driver streams LoB data. There are other issues which come with this approach, and the team decided not to handle our LoB streaming the same way.

As for whether the code you posted will work, I don't know enough about `jdbcTemplate`, `RowMapper`, and `lobHandler` to give a definite answer. From what I can tell, many of these are objects from the Spring framework, and the code seems to be relying on the framework to handle retrieving blobs/streams.

I suggest using JDBC Driver APIs over Spring APIs for achieving your goal, seeing as there are memory concerns. You'll have a greater degree  of control over what the driver is doing, and the goal of passing an InputStream to another class for handling should be possible. I noticed in the code above that you never have to create a Blob object, which leads me to believe the Spring framework is creating the Blob with the JDBC driver. The problem with this is you're never sure what exactly it's doing with the Blob. Is the Blob loaded into memory before you receive the stream? Does it free the Blob object when it moves on, or does it load it into memory unnecessarily?

However, if the class needs to store the stream as a variable, and it's impossible to refactor the code in a way where the class consumes what it needs before the ResultSet is closed; then you might need to look for other avenues of approach. The JTDS approach of streaming to file should work just fine, but this is something the user has to perform manually.

**Comment by CheriePun** [comment]
Hi, 

Sorry for the late reply, been a bit hectic last week. Thanks for your suggestion, we have gone for the stream into memory approach for now and investigating into how we could improve that in the future. Thank you very much for your detailed explanation!

**Comment by rene-ye** [comment]
Closing thread for now. Please feel free to re-open or create another one if there are more questions.
