### ISSUE TITLE
Provide DataSourceFactory Service for JDBC driver

### ISSUE THREAD

**Issue by laeubi** [Microsoft/mssql-jdbc#699]
## Driver version or jar name
Any version

## SQL Server version
Any version

## Client operating system
Any operating system

## Java/JVM version
1.8.0+

## Problem description
OSGi defines a Data Service Specification for JDBC (see https://osgi.org/specification/osgi.cmpn/7.0.0/service.jdbc.html) that provides a convenient and save way to obtain datasources, even though it can be implemented by clients it is advised that jdbc driver vendors include an implementation if possible

## Expected behavior and actual behavior
The driver contains code that (if deployed inside an OSGi-Container) provides a DataSourceFactory

**Comment by cheenamalhotra** [comment]
Closing as PR #700 is now merged.
