### ISSUE TITLE
Escape catalog name in DatabaseMetadata.getSchemas

### ISSUE THREAD

**Issue by fabiocorneti** [Microsoft/mssql-jdbc#715]
## Driver version or jar name
`6.5.4-SNAPSHOT` (15a01c967867a37b3ef632abfe868bc8a6d6d920)

## SQL Server version
`microsoft/mssql-server-linux:2017-latest`

## Client operating system
OS X Sierra

## Java/JVM version
Oracle 10.0.1

## Table schema
None.

## Problem description
If you have a catalog containing a `-` in the name (or other non alpha chars) and pass the catalog name to `DatabaseMetadata.getSchema(String catalog, String schemaPattern)`, the method fails with a syntax exception as the catalog name is not escaped in the resulting query.

## Expected behavior and actual behavior
I would expect the method to work with an unescaped catalog name as other metadata methods (e.g. `getTables`).

## Repro code
See tests in https://github.com/fabiocorneti/mssql-jdbc/pull/1 .

**Comment by cheenamalhotra** [comment]
Hi @fabiocorneti 

This is a good finding. Please feel free to create a PR in this repository for adding this change to driver.
We appreciate and welcome contributions from the community.

We would like to review and merge this change in upcoming releases.

**Comment by rene-ye** [comment]
PR merged, closing issue.
