### ISSUE TITLE
Cannot establish a connection to remote DB

### ISSUE THREAD

**Issue by olegbonar** [Microsoft/mssql-jdbc#719]
## Driver version or jar name
6.4.0.jre8, 6.5.3.jre8-preview are tested

## SQL Server version
10.50.4000.0

## Client operating system
Ubuntu 18.04

## Java/JVM version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)

openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.18.04.1-b11)

java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)

## Table schema
Any

## Problem description
Cannot use JDBC driver with any app on this system

```java
com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "SQL Server did not return a response. The connection has been closed. ClientConnectionId:d576e930-9065-4896-90d9-d29c70fe081e".
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:2670)
	at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1837)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2257)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1921)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1762)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1077)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:623)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at connectURL.main(connectURL.java:18)
Caused by: java.io.IOException: SQL Server did not return a response. The connection has been closed. ClientConnectionId:d576e930-9065-4896-90d9-d29c70fe081e
	at com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeInputStream.ensureSSLPayload(IOBuffer.java:780)
	at com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeInputStream.readInternal(IOBuffer.java:836)
	at com.microsoft.sqlserver.jdbc.TDSChannel$SSLHandshakeInputStream.read(IOBuffer.java:827)
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.readInternal(IOBuffer.java:1009)
	at com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream.read(IOBuffer.java:997)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1767)
	... 8 more
```

## Expected behavior and actual behavior
Should be able to connect to the database (on Ubuntu 16.04 it was ok)

## Repro code
```java
import java.sql.*;  

public class connectURL {  

   public static void main(String[] args) {  

      // Create a variable for the connection string.  
      String connectionUrl = "jdbc:sqlserver://***.***.**.**:****;user=*******;password=**********";  

      // Declare the JDBC objects.  
      Connection con = null;  
      Statement stmt = null;  
      ResultSet rs = null;  

      try {  
         // Establish the connection.  
         Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
         con = DriverManager.getConnection(connectionUrl);  

         // Create and execute an SQL statement that returns some data.  
         String SQL = "SELECT TOP 10 * FROM Person.Contact";  
         stmt = con.createStatement();  
         rs = stmt.executeQuery(SQL);  

         // Iterate through the data in the result set and display it.  
         while (rs.next()) {  
            System.out.println(rs.getString(4) + " " + rs.getString(6));  
         }  
      }  

      // Handle any errors that may have occurred.  
      catch (Exception e) {  
         e.printStackTrace();  
      }  
      finally {  
         if (rs != null) try { rs.close(); } catch(Exception e) {}  
         if (stmt != null) try { stmt.close(); } catch(Exception e) {}  
         if (con != null) try { con.close(); } catch(Exception e) {}  
      }  
   }  
} 
```

**Comment by rene-ye** [comment]
Hi @olegbonar, the team is able to use the driver/run tests with Ubuntu18.04. Can you ping the SQL server you want to connect to, and share more information regarding your environment.

**Comment by olegbonar** [comment]
@rene-ye, hello, thanks for your reply! I'm using openvpn client to be able to connect to the server and i definitely can ping the server while it's turned on. Also there is no problem connecting using IntelliJ IDEA plugin "Database Tools and SQL" (Version: 181.5087.20) with both ms jdbc driver and jtds driver. By the way i have no trouble using jtds with any app on my laptop, it just works.

**Comment by rene-ye** [comment]
Hi @olegbonar, I was successfully able to connect to a database using a fresh copy of Ubuntu18.04 (from their website), java 10, and the sample code provided. Please ensure your connection string follows the format:  "jdbc:sqlserver://databaseURL:port;database=DatabaseName;user=Username;password=Password;". If you are specifying your database target the way jtds does, with databaseURL/databaseName, the driver will not work (I noticed you don't have this property in the code above).

**Comment by olegbonar** [comment]
@rene-ye, I edited the connection string exactly like this: `jdbc:sqlserver://databaseURL:port;database=DatabaseName;user=Username;password=Password;` and tried #414 solution, both did not work, still trying to find what is wrong.

**Comment by cheenamalhotra** [comment]
Hi @olegbonar

Can you check this [link](https://blogs.msdn.microsoft.com/jdbcteam/2008/09/09/the-driver-could-not-establish-a-secure-connection-to-sql-server-by-using-secure-sockets-layer-ssl-encryption/) for troubleshooting SSL Error if it helps?

If nothing works, please enable tracing and provide us trace logs for deeper investigation as mentioned in the link above.

**Comment by Athou** [comment]
We have a similar issue, the error and the stacktrace are the same.
We're having this issue with JDK8u171, we were not having it with u162.

The error seems to be related to a change in u171:
 3DES Cipher Suites Disabled 
To improve the strength of SSL/TLS connections, 3DES cipher suites have been disabled in SSL/TLS connections in the JDK via the jdk.tls.disabledAlgorithms Security Property.
(http://www.oracle.com/technetwork/java/javase/8u171-relnotes-4308888.html)

After changing java.security and removing 3DES_EDE_CBC from jdk.certpath.disabledAlgorithms everything works fine. I'm not sure what needs to be changed in SQLServer config to disable 3DES as an SSL scheme though.

**Comment by olegbonar** [comment]
@Athou, thanks for your reply, changing the `jdk.tls.disabledAlgorithms` property helped me.

**Comment by shinka81** [comment]
Commenting how to disable 3DES cipher suites on sqlserver 2003/2005 for others incase they run in to a similar situation where it was not feasible to change the java security config everywhere.

[this](https://support.microsoft.com/en-us/help/245030/how-to-restrict-the-use-of-certain-cryptographic-algorithms-and-protoc) article lists the ways to disable it. Specifically the section on `Triple DES 168`, setting `DWORD` to `0x0`.

**Comment by victorpalmeida** [comment]
Hi, I was facing the same issue when using IBM JDK 8 since it was using TLSv1 connecting to a MS SQL Server installed on Win2019 which was enforcing TLSv1.2. I solved the problem by setting this property at JVM level: 
**-Dcom.ibm.jsse2.overrideDefaultTLS=true**. The SQL jdbc driver version used was v12.2 jre8.
