### ISSUE TITLE
Socket Timeout support for jdbc connection

### ISSUE THREAD

**Issue by aharbunou** [Microsoft/mssql-jdbc#72]
Hi,
Please correct me if I'm wrong but there is no possibility to configure socket (or read) timeout for MS SQL Server JDBC driver. I've found the following threads about this

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/95755534-bbef-4c2c-afa4-b80ca2a2c333/how-can-i-set-sotimeout-on-the-sockets-used-by-the-jdbc-2005-driver?forum=sqldataaccess

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/3373d40a-2a0b-4fe4-b6e8-46f2988debf8/any-plans-to-add-socket-timeout-option-in-jdbc-driver?forum=sqldataaccess

From my perspective it is a must have feature as network issues can cause thread hanging if there is no configured timeout. I will be very appreciate if you could support socket level timeout.

Thank you in advance!

**Comment by ajlam** [comment]
@angelfallen thank you for opening a feature request. We will be considering this in our planning/prioritization for the next set of features to be released.

**Comment by v-xiangs** [comment]
@aharbunou thank you for your suggestion. We have submitted a PR for this issue.

**Comment by aharbunou** [comment]
Thank you for the quick update! Great job! Do you have some target date of mssql driver release with the new feature?

**Comment by v-xiangs** [comment]
@aharbunou The preview version that supports socket timeout has now been released. You can pick up the jar files from Maven. we have more details here: https://blogs.msdn.microsoft.com/jdbcteam/2017/01/12/early-technical-preview-of-jdbc-6-1-2-for-sql-server-released/
Thank you

**Comment by ajlam** [comment]
@aharbunou - as this functionality has been released in our most recent preview (v6.1.2), are we okay to close this issue?

**Comment by aharbunou** [comment]
@ajlam, @v-xiangs  Thank you guys for the good job! I've verified that socket timeout is applied and I added issue to fix NullPointerException. So you can close this ticket.

**Comment by ajlam** [comment]
Thanks @aharbunou. We've also addressed the NullPointerException (#121) in PR #122.

**Comment by SouvikB01** [comment]
@ajlam Could you please let us know when we will be getting the stable version of mssql jdbc driver having socket timeout feature support.
