### ISSUE TITLE
Stored procedure is unable to create while modification are done while removing existing functionality due to encryption 

### ISSUE THREAD

**Issue by vijjusree** [Microsoft/mssql-jdbc#743]
## Driver version or jar name
Microsoft JDBC server 

## SQL Server version
Microsoft SQL Server Management Studio	14.0.17213.0

## Client operating system
Windows

## Java/JVM version
Version: Mars.2 Release (4.5.2)

## Table schema

create PROCEDURE [dbo].[sp_Create_Denormalized_Customer]

WITH EXECUTE AS OWNER
AS
BEGIN
BEGIN
	DECLARE @COLUMNS VARCHAR (8000),
			@TABLES VARCHAR (8000),			
			@COUNT varchar(100),
			@INSERTTABLE varchar(8000),
			@DROPINDEXES varchar(8000),	
			@INSERTINDEXES varchar(8000),			
			@SELECTCOUNT nvarchar(MAX),
			@TABLENAME varchar(100),
			@ROWCOUNT int,
			@ENCRYPTION_ENABLED VARCHAR(10) = 'false',
			@SSN_SELECT varchar(500),
			@SSN_GROUPBY varchar(500),
			@UPDATESQL VARCHAR (500)
			
	SET @TABLENAME = 'D_CUSTOMER_SEARCH' 
		
--This SP is executed during the installation of theapplication and during the EOD process.
--The [sp_Create_Denormalized_Customer] will drop (if it exists) and create the D_CUSTOMER_SEARCH table. 
--The D_CUSTOMER_SEARCH is then use by the ListCustomersEvent to search for customers.  
--This table is currently static (no updates to the table).
--At EOD the SP is executed by the SP sp_Create_Denormalized_Tables.
--
--Note, all COA's are in this table because the customer search function can find customers belonging to multiple COA's.

IF dbo.FN_CHECK_ENCRYPTION_ENABLED() = 'true' 
 BEGIN  
	SET @ENCRYPTION_ENABLED = 'true'
	set @SSN_SELECT  = 'CONVERT(varchar, DecryptByKeyAutoCert (cert_ID(''SpectrumCertificate'') , NULL ,cust.SSN_encrypted)) ssn,'
	set @SSN_SELECT  = @SSN_SELECT + 'CONVERT(varchar, DecryptByKeyAutoCert (cert_ID(''SpectrumCertificate'') , NULL ,cust.TAX_IDENTIFIER_encrypted)) TAX_IDENTIFIER,'
	
	
	set @SSN_GROUPBY = 'CONVERT(varchar, DecryptByKeyAutoCert (cert_ID(''SpectrumCertificate'') , NULL ,cust.SSN_encrypted)) ,'
	set @SSN_GROUPBY = @SSN_GROUPBY + 'CONVERT(varchar, DecryptByKeyAutoCert (cert_ID(''SpectrumCertificate'') , NULL ,cust.TAX_IDENTIFIER_encrypted)) ,'
 END
else
 BEGIN  
	SET @ENCRYPTION_ENABLED = 'false'
	set @SSN_SELECT  = 'cust.ssn,'
	set @SSN_SELECT  = @SSN_SELECT + 'cust.TAX_IDENTIFIER,'
	set @SSN_GROUPBY = 'cust.ssn,'
	set @SSN_GROUPBY = @SSN_GROUPBY + 'cust.TAX_IDENTIFIER,'
 END
END
	--SELECT COLUMNS
	SET @COLUMNS =  ' SELECT '
	SET @COLUMNS = @COLUMNS + ' IDENTITY (int, 1, 1) AS CUSTOMER_SEARCH_ID
 		,cust.company,
       cust.operations_area,
       cust.customer_id,
       cust.field_id,
       cust.customer_number,
       cust.object_type_code,
       cust.search_name,
       cust.previous_search_name,
       cust.BIRTH_DATE,
       cust.SEARCH_SSN,
       cust.SEARCH_TIN, '
	  
	SET @COLUMNS = @COLUMNS + @SSN_SELECT

    SET @COLUMNS = @COLUMNS + 
	  'cust.legal_reporting_type,
       cust.legal_type,
       addr.city,
       addr.SEARCH_CITY,
	   addr.SEARCH_ADDRESS,
       addr.state,
       addr.postal_code,
       Min(COALESCE(phone.area_code, ''''))            area_code,
       Min(COALESCE(phone.phone_number, ''''))       PHONE_NUMBER,
       Min(COALESCE(phone.foreign_phone_number, '''')) FOREIGN_PHONE_NUMBER,
       cust.status,
       cust.previous_customer_number,
       cust.original_customer_number,
       cust.group_code,
       cust.dealer_usage_type

	INTO ' + @TABLENAME 
	
	--SELECT TABLES
	SET @TABLES = '
	FROM   s_customer_e49 cust
       left outer JOIN (SELECT city,
                          state,
                          postal_code,
                          customer_id,
                          address_id,
                          is_primary,
                          search_city,
                          search_address
                   FROM   s_address_e01) addr
               ON addr.customer_id = cust.customer_id
       left outer JOIN (SELECT area_code,
                          phone_number,
                          foreign_phone_number,
                          customer_id,
                          phone_number_id
                   FROM   s_phone_number_e18) phone
               ON phone.customer_id = cust.customer_id
 where 
      ( phone.phone_number_id is null or
       phone.phone_number_id = (SELECT Min(phone1.phone_number_id)
                                    FROM   s_phone_number_e18 phone1
                                    WHERE  phone1.customer_id = cust.customer_id
                                           AND phone1.phone_number =
                                               phone.phone_number)
       )
       AND 
		(addr.address_id is null or 
       addr.address_id = (SELECT Min(addr1.address_id)
                              FROM   s_address_e01 addr1
                              WHERE  addr1.customer_id = cust.customer_id)
        )

GROUP  BY cust.company,
          cust.operations_area,
          cust.customer_id,
          cust.field_id,
          cust.customer_number,
          cust.object_type_code,
          cust.search_name,
          cust.previous_search_name,
          cust.BIRTH_DATE,
          cust.SEARCH_SSN,
          cust.SEARCH_TIN,'

   SET @TABLES = @TABLES + @SSN_GROUPBY

    SET @TABLES = @TABLES + 
         'cust.legal_type,
          cust.legal_reporting_type,
          addr.SEARCH_CITY,
		  addr.SEARCH_ADDRESS,
          addr.city,
          addr.state,
          addr.postal_code,
          cust.status,
          cust.previous_customer_number,
          cust.original_customer_number,
          cust.group_code,
          cust.dealer_usage_type
 '
	
 
						
	--SET INDEXES
SET @INSERTINDEXES = '
	CREATE CLUSTERED INDEX PK_customer_search_id
	ON ' + @TABLENAME + ' ([CUSTOMER_SEARCH_ID] ASC);

	CREATE NONCLUSTERED INDEX X_IE1
	ON ' + @TABLENAME + ' ([search_name])
	INCLUDE ([customer_id]);

	CREATE NONCLUSTERED INDEX X_IE2
	ON ' + @TABLENAME + ' ([area_code] ASC,[PHONE_NUMBER] asc)
	INCLUDE ([customer_id]);

	CREATE NONCLUSTERED INDEX X_IE3
	ON ' + @TABLENAME + ' (ssn ASC);

	CREATE NONCLUSTERED INDEX X_IE4
	ON ' + @TABLENAME + ' ([tax_identifier] ASC);
	
	CREATE NONCLUSTERED INDEX X_IE5
	ON ' + @TABLENAME + ' ([customer_number] ASC);
	
	CREATE NONCLUSTERED INDEX X_IE6
	ON ' + @TABLENAME + ' ([SEARCH_SSN] asc);
		
	CREATE NONCLUSTERED INDEX X_IE7
	ON ' + @TABLENAME + ' ([SEARCH_TIN] asc);

	CREATE NONCLUSTERED INDEX X_IE8
	ON ' + @TABLENAME + ' ([SEARCH_CITY] asc, [SEARCH_ADDRESS] asc);

	CREATE NONCLUSTERED INDEX X_IE9
	ON ' + @TABLENAME + ' (SEARCH_ADDRESS asc);	

	CREATE NONCLUSTERED INDEX X_IE10
	ON ' + @TABLENAME + ' (phone_Number asc);	

	CREATE NONCLUSTERED INDEX X_IE11
	ON ' + @TABLENAME + '([state] ASC, [search_name] ASC) 
	INCLUDE ([customer_id]);	

			'			

	SET @INSERTTABLE = @COLUMNS + @TABLES

	
	

	--DROP EXISTING TABLE
	EXEC sp_Drop_Denormalized_Table @TABLENAME

	
	BEGIN

		EXEC(@INSERTTABLE)	

		IF dbo.FN_CHECK_ENCRYPTION_ENABLED() = 'true' 
			BEGIN  
				ALTER TABLE D_CUSTOMER_SEARCH ADD SSN_ENCRYPTED VARBINARY(128)
				ALTER TABLE D_CUSTOMER_SEARCH ADD tax_identifier_ENCRYPTED VARBINARY(128)
				
				OPEN SYMMETRIC KEY Spectrum_Key DECRYPTION BY CERTIFICATE SpectrumCertificate  
				SET @UPDATESQL = 'Update D_CUSTOMER_SEARCH set SSN_ENCRYPTED =  EncryptByKey(Key_GUID(''Spectrum_Key''), SSN), SSN = null'
				SET @UPDATESQL = @UPDATESQL + ',tax_identifier_ENCRYPTED =  EncryptByKey(Key_GUID(''Spectrum_Key''), tax_identifier), tax_identifier = null'
				--print @UPDATESQL
				EXEC (@UPDATESQL)
				CLOSE SYMMETRIC KEY Spectrum_Key 
			END
			
		EXEC(@INSERTINDEXES)

	END	
END
go

## Problem description
Msg 156, Level 15, State 1, Line 1
Incorrect syntax near the keyword 'PROCEDURE'.
Msg 156, Level 15, State 1, Line 1
Incorrect syntax near the keyword 'PROCEDURE'.
Msg 156, Level 15, State 1, Line 1
Incorrect syntax near the keyword 'PROCEDURE'.
Msg 156, Level 15, State 1, Line 1
Incorrect syntax near the keyword 'PROCEDURE'.
Msg 156, Level 15, State 1, Line 1
Incorrect syntax near the keyword 'PROCEDURE'.
Msg 156, Level 15, State 1, Line 3
Incorrect syntax near the keyword 'AS'.
Msg 156, Level 15, State 1, Line 3
Incorrect syntax near the keyword 'AS'.
Msg 156, Level 15, State 1, Line 3
Incorrect syntax near the keyword 'AS'.
Msg 156, Level 15, State 1, Line 3
Incorrect syntax near the keyword 'AS'.
Msg 156, Level 15, State 1, Line 3
Incorrect syntax near the keyword 'AS'.
Msg 8180, Level 16, State 1, Procedure sp_describe_parameter_encryption, Line 1 [Batch Start Line 0]
Statement(s) could not be prepared.
Msg 8180, Level 16, State 1, Procedure sp_describe_parameter_encryption, Line 1 [Batch Start Line 0]
Statement(s) could not be prepared.
Msg 8180, Level 16, State 1, Procedure sp_describe_parameter_encryption, Line 1 [Batch Start Line 0]
Statement(s) could not be prepared.
Msg 8180, Level 16, State 1, Procedure sp_describe_parameter_encryption, Line 1 [Batch Start Line 0]
Statement(s) could not be prepared.
Msg 8180, Level 16, State 1, Procedure sp_describe_parameter_encryption, Line 1 [Batch Start Line 0]
Statement(s) could not be prepared.
An error occurred while executing batch. Error message is: Internal error. The format of the resultset returned by sp_describe_parameter_encryption is invalid. One of the resultsets is missing.

Since I'm encrypting phone_number and area_code this error is causing which effecting adapater test suit to fail

**Comment by vijjusree** [comment]
Even though I removed all the functionalities for phone_number and area code in all the tables and stpred procedure there is same error which is blocking whole test cases to pass

**Comment by peterbae** [comment]
Hi @vijjusree, could I ask a few questions to help you solve this problem?

1. What's the exact version of the MSSQL JDBC driver you're using?
2. Can you share the code from the java application you are using, that uses our driver?
3. Have you tried the commands you're running here on Microsoft SQL Server Management Studio (SSMS)? The error message looks like it's coming from the SSMS, and not from our driver.

**Comment by vijjusree** [comment]
What's the exact version of the MSSQL JDBC driver you're using?

<dependency>
                                 <groupId>com.microsoft.sqlserver</groupId>
                                 <artifactId>mssql-jdbc</artifactId>
                                 <version>6.5.1.jre8-preview</version>
                                 <type>jar</type>
                             </dependency> 

Have you tried the commands you're running here on Microsoft SQL Server Management Studio (SSMS)? The error message looks like it's coming from the SSMS, and not from our driver.

Can you tell me what commands that are used for running in SSMS

**Comment by peterbae** [comment]
Hi @vijjusree, thanks for the reply. Typically, when you want to run your queries in SSMS, you can execute them by clicking on the 'Execute' button after you're connected to your data source (more detailed information should be readily accessible online).

The error messages look like it's coming from SSMS, which is an independent application from our JDBC Driver. If you try running the same queries you are running through our JDBC driver against SSMS and still see the same errors, that would confirm that the problem lies in the query itself, and not in our driver.

Have you tried running your queries directly against SSMS to pin down where the problem is coming from?

**Comment by rene-ye** [comment]
Hi @vijjusree, there seems to be some confusion regarding Java version and SQL Server version. I've posted how to retrieve them below.

**Java/JVM version**
1. Start command prompt.
2. Type "java -version" and hit enter.
![cmd_2018-07-13_11-58-44](https://user-images.githubusercontent.com/6042742/42709178-84793f7c-8694-11e8-95b4-a9bbc67a4ece.png)



**SQL Server version**
1. Start Microsoft SQL Server Management Studio (SSMS)
2. Connect to the database you're using in these tests.
3. Create a new query.
4. Execute "SELECT @@version"
![ssms_2018-07-13_11-59-50](https://user-images.githubusercontent.com/6042742/42709179-848e50f6-8694-11e8-864e-c35395604d3c.png)

**Comment by vijjusree** [comment]
@peterbae  I have resolved the issue by adding SELECT OR ALTER STATEMENT in procedure and there is failing is syntax where
 @ENCRYPTION_ENABLED VARCHAR(10) = 'false',
should be written in 
@ENCRYPTION_ENABLED VARCHAR(10) 
@ENCRYPTION_ENABLED = 'false',
Its be resolved and my adapter test  is passed ....

Thank you ,

**Comment by vijjusree** [comment]
@rene-ye  Thank you for Info Helpful
