### ISSUE TITLE
Error due to SQL when encryption is turned on phone_number 

### ISSUE THREAD

**Issue by vijjusree** [Microsoft/mssql-jdbc#759]
## Driver version or jar name
<groupId>com.microsoft.sqlserver</groupId>
                                 <artifactId>mssql-jdbc</artifactId>
                                 <version>6.5.1.jre8-preview</version>
                                 <type>jar</type>
                             </dependency> 
## SQL Server version
Microsoft SQL Server 2016 (SP1-GDR) (KB4057118) - 13.0.4210.6 (X64)  

## Client operating system
WINDOWS 

## Java/JVM version
"1.8.0_171"

## Problem description
PreparedStatementCallback; uncategorized SQLException for SQL [Select cust.COMPANY, cust.OPERATIONS_AREA, cust.CUSTOMER_ID, cust.CUSTOMER_NUMBER, cust.OBJECT_TYPE_CODE, cust.SEARCH_NAME, cust.PREVIOUS_SEARCH_NAME, cust.SSN, cust.TAX_IDENTIFIER, cust.LEGAL_REPORTING_TYPE, cust.LEGAL_TYPE, addr.CITY, addr.STATE, addr.POSTAL_CODE, MIN(COALESCE(phone.AREA_CODE, ''))  area_code, phone.PHONE_NUMBER  PHONE_NUMBER, phone.FOREIGN_PHONE_NUMBER FOREIGN_PHONE_NUMBER, cust.STATUS, cust.PREVIOUS_CUSTOMER_NUMBER, cust.ORIGINAL_CUSTOMER_NUMBER , cust.GROUP_CODE, cust.DEALER_USAGE_TYPE from S_CUSTOMER_E49 cust  inner join (select CITY, STATE, POSTAL_CODE, CUSTOMER_ID, ADDRESS_ID, IS_PRIMARY, SEARCH_CITY, SEARCH_ADDRESS from S_ADDRESS_E01) addr on addr.CUSTOMER_ID = cust.CUSTOMER_ID inner join (select AREA_CODE, PHONE_NUMBER, FOREIGN_PHONE_NUMBER, CUSTOMER_ID, PHONE_NUMBER_ID from S_PHONE_NUMBER_E18) phone on phone.CUSTOMER_ID = cust.CUSTOMER_ID and phone.AREA_CODE = ?  and phone.PHONE_NUMBER = ?  where cust.SEARCH_NAME like ?  and  phone.PHONE_NUMBER_ID = (Select min(phone1.PHONE_NUMBER_ID) from S_PHONE_NUMBER_E18 phone1 where phone1.CUSTOMER_ID = cust.CUSTOMER_ID and phone1.PHONE_NUMBER = phone.PHONE_NUMBER )  and  addr.address_id = (Select min(addr1.address_id) from S_ADDRESS_E01 addr1 where addr1.CUSTOMER_ID = cust.CUSTOMER_ID  )  group by 	cust.COMPANY, cust.OPERATIONS_AREA,cust.CUSTOMER_ID, cust.CUSTOMER_NUMBER, cust.OBJECT_TYPE_CODE, cust.SEARCH_NAME, cust.PREVIOUS_SEARCH_NAME, cust.SSN, cust.TAX_IDENTIFIER,	cust.LEGAL_TYPE, cust.LEGAL_REPORTING_TYPE, addr.CITY, addr.STATE, addr.POSTAL_CODE, cust.STATUS, cust.PREVIOUS_CUSTOMER_NUMBER, cust.ORIGINAL_CUSTOMER_NUMBER , cust.GROUP_CODE , cust.DEALER_USAGE_TYPE , phone.FOREIGN_PHONE_NUMBER , phone.PHONE_NUMBER  order by  cust.SEARCH_NAME  ,  AREA_CODE , PHONE_NUMBER]; SQL state [S0002]; error code [33299]; Encryption scheme mismatch for columns/variables '@P1', 'PHONE_NUMBER', 'PHONE_NUMBER'. The encryption scheme for the columns/variables is (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'CEKSpectrumLevel3', column_encryption_key_database_name = 'vvadisala-spectrum-head') and the expression near line '1' expects it to be (encryption_type = 'PLAINTEXT') (or weaker). ; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: Encryption scheme mismatch for columns/variables '@P1', 'PHONE_NUMBER', 'PHONE_NUMBER'. The encryption scheme for the columns/variables is (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'CEKSpectrumLevel3', column_encryption_key_database_name = 'vvadisala-spectrum-head') and the expression near line '1' expects it to be (encryption_type = 'PLAINTEXT') (or weaker).

## Expected behavior and actual behavior
Getting this error since it PHONE_NUMBER Is encrypted

**Comment by vijjusree** [comment]
I haev performed encryption in deterministic for both phone_number and foreign phone number

**Comment by ulvii** [comment]
Hi @vijjusree ,
The error message suggests that, you are not using parameterized queries with encrypted columns. Please take a look at [Retrieving plaintext data example](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-always-encrypted-with-the-jdbc-driver?view=sql-server-2017#retrieving-plaintext-data-example) or [Retrieving encrypted data example](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-always-encrypted-with-the-jdbc-driver?view=sql-server-2017#retrieving-encrypted-data-example) for instructions on how to use `PreparedStatement` to fetch encrypted data.

**Comment by ulvii** [comment]
Closing the issue. Please let us know if you have any other questions.
