### ISSUE TITLE
Database connection hangs on failover from one node to another

### ISSUE THREAD

**Issue by jmerzgd** [Microsoft/mssql-jdbc#764]
## Driver version or jar name
> 6.4.0.jre7

## SQL Server version
> Microsoft SQL Server 2016 (SP1-CU5) (KB4040714) - 13.0.4451.0 (X64) 
> 	Sep  5 2017 16:12:34 
> 	Copyright (c) Microsoft Corporation
> 	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 6.3 <X64> (Build 14393: )

## Client operating system
> CentOS Linux 3.10.0-862.3.3.el7.x86_64

## Java/JVM version
> java version "1.8.0_144"
> Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
> Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

## Problem description
We are using the MSSQL JDBC driver to connect to a SQL Server multi-subnet AlwaysOn cluster.
Our JDBC URL is: jdbc:sqlserver://[hostname]:1433;databaseName=[dbName];multiSubnetFailover=true;transparentNetworkIPResolution=false;socketTimeout=7200000

The problem we are having is that sometimes when the database fails over, not all active connections are closed in a way that let's the client side know that the server is no longer holding onto the other end of the socket.

### The sequence of events is:

1. Query begins from client application using either a newly created connection or an existing connection from our pool. Either the communication happens over a socket that was opened by the driver.
2. Database fails over from one node to another
3. Client query hangs indefinitely blocking to read from the socket. (See example stack dump of such a thread below)

The most frequently impacted queries are longer-running, though that is quite possibly due to the higher likelihood that they are running during a failover. The frequently impacted queries also have very small result sets - for instance a query that may run for several minutes and returns only a single row with a single column, as opposed to a large or possibly continuous quantity of data.

This occurs both with planned failovers (i.e. a failover to perform maintenance on the primary node where the node we are failing over from is healthy) and also with unplanned failovers (where the node we are failing away from is unhealthy).

## Expected behavior and actual behavior
The client application should be able to detect that the socket has been lost on the server side so that the query simply fails rather than hanging.

### Example stack dump from a hung thread:
_(dumped via jstack)_
```
"scheduler_Worker-7" #158 prio=5 os_prio=0 tid=0x00007f069ffad800 nid=0xf7e runnable [0x00007f06334f8000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at com.microsoft.sqlserver.jdbc.TDSChannel.read(IOBuffer.java:1983)
        at com.microsoft.sqlserver.jdbc.TDSReader.readPacket(IOBuffer.java:6497)
        - locked <0x000000034322afb8> (a com.microsoft.sqlserver.jdbc.TDSReader)
        at com.microsoft.sqlserver.jdbc.TDSCommand.startResponse(IOBuffer.java:7741)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:546)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:479)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7347)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2713)
        - locked <0x000000036708ba18> (a java.lang.Object)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:224)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:204)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:401)

        ...application code from this point forward...
```

**Comment by ulvii** [comment]
Hi @jmerzgd ,

I will setup an environment to investigate the issue, would you mind sharing a repro code (preferably vanilla JDBC code)?

**Comment by ulvii** [comment]
@jmerzgd , please also enable the JDBC logger and set it to `FINER` or higher level. For instructions on how  to enable the logger, see [this page](https://docs.microsoft.com/en-us/sql/connect/jdbc/tracing-driver-operation?view=sql-server-2017).

**Comment by jmerzgd** [comment]
Hi @ulvii ,

Thanks for looking into it, and for the tip on the JDBC logger. We're setting up a small test cluster to attempt to reproduce with and writing a small test case. I'll hopefully add it here in a day or two.

**Comment by cheenamalhotra** [comment]
Hi @jmerzgd 

Does this issue still occur and in that case do you have a repro to share?

**Comment by jmerzgd** [comment]
Hi @cheenamalhotra,

Unfortunately we haven't succeeded in developing a simplified reproduction yet. It's a little hard to say whether it is still happening or not... we were doing a number of failovers in our production systems while making some infrastructural changes for a little while and now haven't done one for a few weeks, so haven't had a situation to possibly produce the issue.

On account of our inability so far to reproduce at will, I'm tempted to say you can close this issue (or whatever is your preference) and if/when we're able to to reproduce reliably I can either re-open or file a new ticket.

**Comment by cheenamalhotra** [comment]
Sounds fair. I'll close the issue for now :)
