### ISSUE TITLE
Question - Can we connect using Kebereos Token

### ISSUE THREAD

**Issue by keyoke** [Microsoft/mssql-jdbc#765]
Hi,
I know its possible to supply a keytab file and let the jdbc driver request Kerberos tokens.
But we would like to manage the Kerberos token requests(Key Tab etc) outside of our db application, is it possible to supply a pre-existing Kerberos token when connecting with the mssql jdbc driver?

Thanks

**Comment by ulvii** [comment]
Hi @keyoke ,

The driver does not support authentication with Kerberos tokens.

**Comment by ulvii** [comment]
I should also mention that, you can connect to Azure AD if you have an access token. Please see  [Connecting using Access Token](https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-using-azure-active-directory-authentication?view=sql-server-2017#connecting-using-access-token) for instructions.
