### ISSUE TITLE
LocalDB support

### ISSUE THREAD

**Issue by SebastianPfliegel** [Microsoft/mssql-jdbc#769]
## Driver version or jar name
7.0.0.jre8

## SQL Server version
LocalDB 13.0.4001

## Client operating system
Windows 10

## Java/JVM version
java version "1.8.0"

## Problem description
Please share more details with us.

## Expected behavior and actual behavior
Trying to connect to url `jdbc:sqlserver://(localdb)\\MSSQLLocalDB:1433;databaseName=master;integratedSecurity=false;`, which fails with following error:
```
Fehler beim Herstellen der TCP/IP-Verbindung mit dem Host '(localdb)', Port 1433. Fehler: '(localdb). Überprüfen Sie die Verbindungseigenschaften. Stellen Sie sicher, dass eine SQL Server-Instanz auf dem Host ausgeführt wird und am Port TCP/IP-Verbindungen akzeptiert. Vergewissern Sie sich, dass am Port keine TCP-Verbindungen durch eine Firewall blockiert werden.'.
```

**Comment by cheenamalhotra** [comment]
Hi @SebastianPfliegel ,

Please confirm:
* TCP/IP Ports are enabled for your **MSSQLLocalDB** instance 
(You can verify and look for enabled protocols in SQL Server Configuration Manager)
* Please provide `integratedSecurity=true` in connection string, or provide user credentials with `user` and `password` connection properties.

I hope this will resolve your issue.

**Comment by cheenamalhotra** [comment]
Hi @gordthompson 
Yes your findings are correct.

LocalDB can only be connected with SQLExpress Instance `localhost\\SQLEXPRESS` with MS JDBC Driver.
`(LocalDB)\\MSSQLLocalDB` shall not work as this driver only uses TCP/IP and expects `(localdb)` to be Hostname, hence the exception above.

Connection to `(localdb)` works with SSMS, SQLClient and jTDS drivers as they all support named pipes.
