### ISSUE TITLE
SQLServerBulkCopy / getDestinationMetadata fails when there's an apostrophe in the table name

### ISSUE THREAD

**Issue by Gaff** [Microsoft/mssql-jdbc#775]
## Driver version or jar name
mssql-jdbc:6.4.0-jre8

## Problem description
When attempting to bulk upload to a table with `'` in the name the upload fails with:

    com.microsoft.sqlserver.jdbc.SQLServerException: Unable to retrieve column metadata.
	at 
 com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.getDestinationMetadata(SQLServerBulkCopy.java:1781)

The code does queries such as:

    select collation_name from sys.columns where " + "object_id=OBJECT_ID('" + destinationTableName + "') 

Which fails because `destinationTableName` contains unescaped `'`

**Comment by cheenamalhotra** [comment]
Hi @Gaff 

Thanks for bringing forward this issue with us. I've created a [PR](https://github.com/Microsoft/mssql-jdbc/pull/780) that fixes this issue in the driver. Please take a look and let me know for any changes needed.

**Comment by Gaff** [comment]
Wow thanks for the quick turnaround! Looks good (in so much as I can tell, I'm not going to claim to be an expert).

**Comment by cheenamalhotra** [comment]
Hi @Gaff 

PR #780 has been merged and will be available since v7.1.1 release version. Closing issue.
