### ISSUE TITLE
Unable to insert a BigDecimal with high scale

### ISSUE THREAD

**Issue by jan-krakora** [Microsoft/mssql-jdbc#787]
## Driver version or jar name
mssql-jdbc-7.0.0.jre8.jar

## SQL Server version
SQL Server 2017

## Client operating system
Windows 10 x64

## Java/JVM version
Oracle JDK 9.0.4

## Problem description
When trying to insert a BigDecimal value parsed from text like "9.99E+99" I've got an error
com.microsoft.sqlserver.jdbc.SQLServerException: Error converting data type nvarchar to decimal.

**Comment by jan-krakora** [comment]
Hi @cheenamalhotra ,

thank you for your response. My column type is NUMERIC. I would expect an error like "Too high value precision" then. Message "Error converting data type nvarchar to decimal" is IMHO very misleading.

**Comment by cheenamalhotra** [comment]
Hi @jan-krakora ,

Please test PR #796 changes for Out of Range Exception to be thrown instead.

**Comment by jan-krakora** [comment]
How can I test it? Is there a way to get a PR as a branch and build the jdbc driver? Looking at your commit it  seems fine to me.

**Comment by cheenamalhotra** [comment]
Hi @jan-krakora 

Please find the Jars for testing: [mssql-jdbc-PR796.zip](https://github.com/Microsoft/mssql-jdbc/files/2337818/mssql-jdbc-PR796.zip)

**Comment by jan-krakora** [comment]
Hi @cheenamalhotra,

I can confirm the exception with 'out of range' message is thrown. Thank you.

**Comment by cheenamalhotra** [comment]
Hi @jan-krakora 

PR #796 has been merged and changes will be available since v7.1.1 release. Closing issue.
