### ISSUE TITLE
Add constrained delegation support

### ISSUE THREAD

**Issue by jacobovazquez** [Microsoft/mssql-jdbc#79]
I am able to obtain a service ticket for SQL Server using an impersonated credential with Java 8 but when I try to use this with the driver I am getting the next error:

> KrbException: The ticket isn't for us (35)

It seems that the problem is in the KerbAuthentication class inside the method intAuthInit(). In this class a context is created for the authentication and this context requests that the initiator's credentials be delegated to the acceptor during context establishment. This behavior is not possible within a constrained delegation scenario.

The service ticket obtained using the impersonated credential is not a forwardable ticket and is not usable for the driver. Changing the next set to false makes the authentication works.

`peerContext.requestCredDeleg(true);`

I understand this is not the right change since the SQL Server can need to use a delegated credential in order to connect to other SQL Server instances using open delegation, but a change is necessary to set this property to false in a constrained delegation scenery.

**Comment by v-suhame** [comment]
Hi @jacobovazquez, can you share the code used for reproducing KrbException?

**Comment by jacobovazquez** [comment]
Hi, 

    Sure, no problem. You need to change the constant values for the ones of your environment, have the driver in the classpath and execute with Java 8. Let me know if you need more information to reproduce the exception.

best regards,

[ImpersonationJDBC.zip](https://github.com/Microsoft/mssql-jdbc/files/766530/ImpersonationJDBC.zip)

**Comment by v-suhame** [comment]
Thanks @jacobovazquez! I'm trying to setup the environment for testing, what was the intermediate server you used, between the client and the SQL Server?

**Comment by jacobovazquez** [comment]
@v-suhame I just created an account in the Active Directory for this purpose, it is not necessary to use a special intermediate server to reproduce the problem. Of course, you need to configure this account to support Constrained Delegation, set an appropriate SPN and create a KeyTab file in order to impersonate the client using this service.

**Comment by v-suhame** [comment]
Thanks for confirming @jacobovazquez, I do have the setup you detailed but I'm running into,
`Exception in thread "main" GSSException: Failure unspecified at GSS-API level (M
echanism level: Attempt to obtain S4U2self credentials failed!)`

`Caused by: KrbException: S4U2self ticket must be FORWARDABLE`
 
Are you by any chance using OpenJDK9?

**Comment by jacobovazquez** [comment]
No @v-suhame , I'm using the Oracle JDK 8. I think the problem is in the service account configuration in the Active Directory. Since we are using S4U2self, you need to configure the service account to support the transition protocol. In the "Delegation" tab you have to select the option "Use any authentication protocol" instead of "Use Kerberos only".

**Comment by v-suhame** [comment]
That worked, I'm able to reproduce the exception, I will investigate it further and keep you updated.

**Comment by permagnushansson** [comment]
Great that this is being worked on!

Just a question regarding your example code, @jacobovazquez, and the future support for Kerberos Constrained Delegation, @v-suhame: shouldn't the context creation be performed by the JDBC driver (using the Subject of a service principal allowed to delegate and the proxy credentials for the user being delegated), and not the program wrapping the driver?

The few examples I have seen of JDBC drivers explicitly stating that they support Kerberos Constrained Delegation take the delegated user's credential as a property when creating the connection, according to the pattern:
```java
Properties connectionProps = new Properties();
connectionProps.put("userGSSCredential", delegateeGSSCredential);
Connection con = Subject.doAs(serviceSubject,
  (PrivilegedActionException<Connection>) () -> driver.connect(url, connectionProps));
```
where the delegateeGSSCredential has been obtained via S4U2Self impersonation, or received when the service subject accepted a context initiated by the user.

Is something like this going to be implemented for the MSSQL JDBC driver?

**Comment by jacobovazquez** [comment]
I an agree with you @permagnushansson, both approachs seems ok to me. 
In the case of passing the userGSSCredential to the driver, this is the one that has to know the SPN of the SQL Server and generate the service ticket. The client should do as few steps as possible.
On the other hand, you are misusing a Properties objet because you are putting an object different than a String, taking advantage of the bad inheritance of this class.

**Comment by permagnushansson** [comment]
@jacobovazquez, yes, it would entail using the HashTable nature of the Properties class to transfer a non-String to the driver. I would still prefer this to the hassle of sidestepping the driver by creating a GSSContext directly with the database before calling Driver.connect(..) (which will create a new GSSContext).

For reference, and argument, these are the JDBC driver vendors I have found that do this:
IBM Netezza:
http://www-01.ibm.com/support/docview.wss?uid=swg21997658
Simba Impala: 
http://www.simba.com/products/Impala/doc/JDBC_InstallGuide/content/jdbc/im/authenticating/delegatedkerberos.htm

As an application developer, I just want to provide the credentials I have to the driver, and then let the driver manage SPNs and GSSContext negotiations, just like in the unconstrained delegation case.

**Comment by v-suhame** [comment]
@permagnushansson that's a good idea. We were just doing the basic investigation, it seems that to fix the issue raised by @jacobovazquez the JDBC driver needs to create the GSSConext using impersonated credential, rather than it being created in the client application. So yes, the implementation is leaning towards your suggestion.

**Comment by v-suhame** [comment]
Support for constrained delegation is added in [#178]. Can you please review and test it?

You can add `GSSCredential` to the driver connection property and pass impersonated credential as value.

**Comment by jacobovazquez** [comment]
I tried both, 4.1 and 4.2, and it is working. Thanks!

**Comment by v-suhame** [comment]
It will be helpful if the code you provided for reproducing the issue, can be modified and added under [sample code](https://github.com/Microsoft/mssql-jdbc/tree/dev/src/samples). Can you please tweak it and submit a PR?
