### ISSUE TITLE
Is there some way to get client statistics like in SSMS?

### ISSUE THREAD

**Issue by philippn** [Microsoft/mssql-jdbc#814]
Hi there,

please excuse me if this is the wrong place to ask this question, I couldn't find any other related issues here or on Stackoverflow though. I'm currently investigating some performance issues with an Azure SQL instance of mine. In Azure query insight everything seems to be fine, but the statistics from the OR-Mapper look quite mediocre to say the least (even for simple queries).

So here is my question: In SSMS there is an option to execute a query with client statistics enabled. Is there some way to obtain these with the JDBC driver as well? That might help me hunting down the problem.

Or are there some loggers that you know of that be worth looking at? I looked at https://docs.microsoft.com/en-us/sql/connect/jdbc/tracing-driver-operation?view=sql-server-2017, it doesn't mention anything about performance timings though.

Thanks for your time and kind regards,
Philipp

**Comment by peterbae** [comment]
Hi @philippn, thanks for contacting us. By client statics like the one from SSMS, I assume you mean a tool that measures how much time each phase of a SQL statement took from the driver? (TDS packet read/write time, internal processing time, etc.)

Unfortunately, our JDBC driver doesn't offer such a functionality like SSMS, but as our driver is open source, you can use the logging feature (from the link you mentioned) or add Java code inside the driver code to measure the performance of specific queries yourself. You can also use a Java profiler if that helps as well.

**Comment by philippn** [comment]
Thanks for the heads-up, I guess this issue can be closed then...
