### ISSUE TITLE
Eclipse/Maven: QueryDSL and SQL Server Issue Using Integrated Security

### ISSUE THREAD

**Issue by burrm** [Microsoft/mssql-jdbc#823]
I'm not sure if this is a Microsoft driver bug per se, but any help would be appreciated...

## Driver version
7.0.0jre8

## SQL Server version
Microsoft SQL Server 2016 (SP1-GDR) (KB4458842) - 13.0.4224.16 (X64)   Aug 18 2018 09:00:06   Copyright (c) Microsoft Corporation  Express Edition (64-bit) on Windows 10 Enterprise 6.3 <X64> (Build 17134: ) (Hypervisor) 

## Client Operating System
Windows 10

## JAVA/JVM version
1.10

## Table schema
N/A

## Problem description
Maven issue: see https://stackoverflow.com/questions/52650326/eclipse-maven-querydsl-and-sql-server-issue-using-integrated-security

## JDBC trace logs
I'm not sure that these would be helpful here, but let me know if you would like me to try to get them...

## Reproduction code
See Stackoverflow question for details. Involves creating 2 databases, schemas can be of your choosing, uses build workflow through Eclipse/Maven using QueryDSL.

**Comment by peterbae** [comment]
Hi @burrm, thanks for contacting us. I've taken a look at your SO question, and it seems like the question has multiple parts. I don't think this is a driver bug, but I see that you're having some trouble with setting up Integrated Authentication with our driver (in both questions). I think [this](https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-2017#Connectingintegrated) page can help you solve your problem on that end - please let me know if you need anything else from our end.

**Comment by burrm** [comment]
Hi Peter,

Unfortunately no. I have Integrated Security working with the JDBC driver, but the issue seems to be how Eclipse, Maven, QueryDSL, and the JDBC driver all work together in this scenario.

Anyway I have a workaround, which involves restarting Eclipse to run the update and load any schema changes with QueryDSL.

Thanks for your help.

**Comment by peterbae** [comment]
Thanks for letting me know @burrm. I'm going to close the issue now, but please feel free to reopen it if you need any further assistance.
