### ISSUE TITLE
materialized_clob (hibernate) returns iso encoded content as utf16 (chinese!!) - fixed with 7.1.1

### ISSUE THREAD

**Issue by carstenartur** [Microsoft/mssql-jdbc#832]
## Driver version
7.0.0

## SQL Server version
13.0.4210.6

## Client Operating System
windows 10

## JAVA/JVM version
Oracle 1.8.0_181

## Table schema
varchar(max)

## Problem description
1. Expected behaviour: should return readable text similar to what Microsoft SQL Server Management Studio displays
2. Actual behaviour: get chinese characters half of the size
3. Error message/stack trace:
4. Any other details that can be helpful: It looks like that 7.0.0 is missing the concept of charset for clob or only understands ascii and utf16 in some situations. Unclear when it is doing what. The changelog of 7.1.1 does not contain any hint of this problem so I wonder if you are aware of that you kind of fixed it in 7.1.1 compared to 7.0.0.

**Comment by rene-ye** [comment]
Hi @carstenartur, PR #799 linked in the notes contains more detailed information on the fix. We are aware of an encoding change that went in along with the streaming issue. However, you mentioned in your post that the problem was "kind of fixed". Can you elaborate on this point a little and give an example where encoding is still not working as expected in 7.1.1-preview? Thanks.

**Comment by Thopap** [comment]
FYI: we Run into the same issue here. 7.0.0 cannot be use, 7.1.1 seems top work fine. Hopefully a final Version ist releases soon.

**Comment by carstenartur** [comment]
Hi Rene-Ye,
It might be fine now using 7.1.1. Nothing to complain from my side regarding this issue. Older versions work, 7.0.0 does not work and 7.1.1 works again. So looks like a regression. I just was not sure if it is just looking like it is fixed as there had not been any hint about the problem in the changelog. I was not aware there is a more detailed version that in fact contains detailed information. Sorry for overlooking that.
However I did not test everything yet. Regarding the comment that streaming on (n)clob is not possible using unicode I still have to do tests. That would be an important feature for me as I cannot get big files of text from the database otherwise.
Thanks for your attention!
Can be closed now if you ask me.
Best regards,
Carsten

**Comment by rene-ye** [comment]
Hi carstenartur,
Streaming of NClobs is still supported. Users should call getCharacterStream() to stream NClobs and getAsciiStream() to stream Clobs.

**Comment by carstenartur** [comment]
Hi Rene-Ye,
thanks for the info - good to hear!
Best regards,
Carsten

**Comment by carstenartur** [comment]
thanks, not sure who is expected to do this - as I opened it I close it now the changelog has been improved. Hope you don't care..
