### ISSUE TITLE
Provide ability to load library using the runtime instead of JVM params

### ISSUE THREAD

**Issue by carlmolemans** [Microsoft/mssql-jdbc#852]
https://github.com/Microsoft/mssql-jdbc/blob/e52178054c0650e51c31e35db99eb64fa6a71afc/src/main/java/com/microsoft/sqlserver/jdbc/AuthenticationJNI.java#L52

**Comment by cheenamalhotra** [comment]
Hi @carlmolemans 

The code you mentioned loads sqljdbc_auth library from the classpath and classpath is set only once when starting a JVM process.

Can you please elaborate how would you propose this change? Are you suggesting to allow reloading library from the same classpath at runtime?

**Comment by cheenamalhotra** [comment]
Hi @carlmolemans 

`java.library.path` is ideal solution to provide path to DLL when running Java application.
Could you please elaborate your use-case, in what case would you need to load DLL using System.load(path.to.dll) that cannot be loaded with java.library.path?

**Comment by cheenamalhotra** [comment]
Hi @carlmolemans 

As of currently, we do not feel necessary to provide an additional option in the driver to load DLL as it can be easily handled with `java.library.path` specified, hence we are closing this issue. Let us know if you have any more questions.
