### ISSUE TITLE
BigDecimal in TVP can incorrectly cause SQLServerException related to invalid precision or scale

### ISSUE THREAD

**Issue by jschulist** [Microsoft/mssql-jdbc#86]
I pulled together some [tests](https://github.com/jschulist/mssql-jdbc-decimal-tvp) which reproduce the behavior I'm encountering.  I've been testing using java build 1.8.0_101-b13,  mssql-jdbc driver version 6.1.0.jre8 and Microsoft SQL Server 2016 (RTM) - 13.0.1601.5 (X64).  

I suspect the issue might be caused by the driver code incorrectly assuming that the precision and scale values of BigDecimal mirror those of the decimal data type in SQL Server, namely the code found [here](https://github.com/Microsoft/mssql-jdbc/blob/eb14f63077c47ef1fc1c690deb8cfab602baeb85/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataTable.java#L158).  

Let me know if any additional details would be helpful.

**Comment by v-suhame** [comment]
@jschulist Thanks for raising this issue and for the repro test code. We will submit a PR with the fix shortly.

**Comment by v-suhame** [comment]
[PR#92](https://github.com/Microsoft/mssql-jdbc/pull/92) should fix precision issue. Please use it for testing.
