### ISSUE TITLE
SQL errors - provide error line number info

### ISSUE THREAD

**Issue by serge-rider** [Microsoft/mssql-jdbc#885]
## Driver version
7.0.0

## SQL Server version
Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64) 
	Oct 28 2016 18:17:30 
	Copyright (c) Microsoft Corporation
	Express Edition (64-bit) on Windows 10 Home Single Language 6.3 <X64> (Build 17134: )

## Client Operating System
Windows 10

## JAVA/JVM version
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)

## Problem description
Please provide information about error line number in SQLException. 

It is already received by tds and stored in StreamError class but then it just never passed to user.
Please provide some way to obtain this info (add special getter in SQLServerException or at least add it in  error messages).

**Comment by ulvii** [comment]
Hi @serge-rider,

Thank you for creating the issue. We will investigate and get back to you soon.

**Comment by cheenamalhotra** [comment]
Hi @serge-rider 

I created PR #905 to resolve your issue. Let us know your thoughts.

**Comment by cheenamalhotra** [comment]
Closing Issue since PR #905 is merged.
The fix shall be available in next Preview Release (v7.1.4)
