### ISSUE TITLE
DataSource with SQL auth coming out of JNDI can't connect to database

### ISSUE THREAD

**Issue by maeichris** [microsoft/mssql-jdbc#892]
## Driver version
6.2.2.  I believe this worked correctly in 2.0, and it has been an issue since 3.0 all the way to the current 7.0.

## SQL Server version
Microsoft SQL Server 2014 (SP2-GDR) (KB4057120) - 12.0.5214.6 (X64) 
	Jan  9 2018 15:03:12 
	Copyright (c) Microsoft Corporation
	Express Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)

## Client Operating System
Development: Windows 7.0 Professional.
Build: CentOS 6.0.

## JAVA/JVM version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

## Table schema
Don't need one.  See unit test below.

## Problem description
1. Expected behaviour:
I expect to be able to put a functional SQLServerXADataSource with SQL login into JNDI, and when I get it back out be able to get a usable connection.

2. Actual behaviour:
The new DataSource does not know enough to be able to connect to the database.  There is a login error on the connection.

3. Error message/stack trace:
```
com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'XXXX'. ClientConnectionId:2f6eadae-a703-4ed9-9773-9fd06b0c5a63
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:258)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onEOF(tdsparser.java:256)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:108)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:4290)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:3157)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$100(SQLServerConnection.java:82)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:3121)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7151)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2478)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:2026)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:1687)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:1528)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:866)
	at com.microsoft.sqlserver.jdbc.SQLServerDataSource.getConnectionInternal(SQLServerDataSource.java:968)
	at com.microsoft.sqlserver.jdbc.SQLServerDataSource.getConnection(SQLServerDataSource.java:69)
	at com.mycompany.common.sqltests.DataSourceTest.runSimpleQuery(DataSourceTest.java:40)
	at com.mycompany.common.sqltests.DataSourceTest.testSomething(DataSourceTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

4. Any other details that can be helpful:

It appears that a "Reference" object, which is an interpretive dance version of the original DataSource that was created using SQLServerDataSource.getReferenceInternal(...), is being used to try to create a new DataSource.  However, notice that in the getReferenceInternal() method that creates the Reference in the first place, there is the following code:

```
                // do not add passwords to the collection. we have normal password
                if (!propertyName.contains(SQLServerDriverStringProperty.PASSWORD.toString()))
                    ref.add(new StringRefAddr(propertyName, connectionProps.getProperty(propertyName)));
```

The password therefore doesn't make it to the copy of the data source, and it will therefore be unable to create a valid connection to the database.  I'm not sure what the comment is implying by "we have normal password"; there must have been a reason for it in the first place.

## JDBC trace logs
Server log gives:
```
2018-11-29 11:46:25.25 Logon       Login failed for user 'XXXX'. Reason: Password did not match that for the login provided. [CLIENT: 127.0.0.1]
```

## Reproduction code

Here's a unit test.  Note we are using SQL Server logins, not integrated logins.  The unit test doesn't require a full schema, just a blank database to run against.  You'll have to go in and fix up the username, password, and jdbcurl.

```
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Types;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NameNotFoundException;
import javax.naming.NamingException;
import javax.naming.Reference;
import javax.sql.DataSource;

import org.junit.Assert;
import org.junit.Test;

import com.microsoft.sqlserver.jdbc.SQLServerXADataSource;

public class DataSourceTest
{
	@Test
	public void testSomething()
		throws SQLException, NamingException
	{
		SQLServerXADataSource ds = createDataSource();
		runSimpleQuery(ds); // Proves that the initial DataSource is functional.

		registerDataSource("test", ds);
		DataSource newDs = lookUpJdbcDataSource("test");

		runSimpleQuery(newDs);
	}

	private void runSimpleQuery(DataSource newDs)
		throws SQLException
	{
		try (Connection conn = newDs.getConnection())
		{
			try (PreparedStatement ps = conn.prepareStatement("SELECT CAST('2017-01-01' AS Date) AS d1"))
			{
				try (ResultSet rs = ps.executeQuery())
				{
					Assert.assertTrue(rs.next());
					ResultSetMetaData rsMetaData = rs.getMetaData();
					Assert.assertEquals(Types.DATE, rsMetaData.getColumnType(1));
					Assert.assertEquals("2017-01-01", rs.getString(1));
				}
			}
		}
	}

	private SQLServerXADataSource createDataSource()
	{
		String url = "jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=???;autoReconnect=true;applicationName=blah";
		String userName = "XXXX";
		String password = "SOMEPASSWORD";

		SQLServerXADataSource ds = new SQLServerXADataSource();
		ds.setURL(url);

		// not integrated security
		ds.setUser(userName);
		ds.setPassword(password);
		return ds;
	}

	public static synchronized DataSource lookUpJdbcDataSource(String lookupName)
		throws SQLException
	{
		try
		{
			Context initContext = new InitialContext();
			Context envContext  = (Context)initContext.lookup(JDBC_PREFIX);
			Object object = envContext.lookup(lookupName);
			if (object instanceof Reference)
			{
				Reference ref = (Reference)object;
				throw new NamingException("For " + lookupName +
					", only found Ref for " + ref.getClassName() +
					", factory=" + ref.getFactoryClassName() +
					", factoryLocation=" + ref.getFactoryClassLocation());
			}
			return (DataSource)object;
		}
		catch (NamingException ne)
		{
			throw new SQLException("Lookup failure name=" + lookupName, ne);
		}
	}

	private static final String JDBC_PREFIX = "java:/comp/env/jdbc/";

	public void registerDataSource(String dataSourceName, DataSource ds)
		throws NamingException
	{
		// The code to allow for JNDI lookup in unit tests comes from this page:
		// https://blogs.oracle.com/randystuph/entry/injecting_jndi_datasources_for_junit
		// The contextfactory requires lib/catalina.jar and bin/tomcat-juli.jar
		// Create initial context
		System.setProperty(Context.INITIAL_CONTEXT_FACTORY,
			"org.apache.naming.java.javaURLContextFactory");
		System.setProperty(Context.URL_PKG_PREFIXES, "org.apache.naming");
		InitialContext ic = new InitialContext();
		String resourceName = JDBC_PREFIX + dataSourceName;

		try
		{
			ic.lookup("java:");
		}
		catch (NameNotFoundException nnfe)
		{
			ic.createSubcontext("java:");
			ic.createSubcontext("java:/comp");
			ic.createSubcontext("java:/comp/env");
			ic.createSubcontext("java:/comp/env/jdbc");
		}
		ic.bind(resourceName, ds);
	}
}
```

**Comment by cheenamalhotra** [comment]
Hi @maeichris 

I can reproduce your problem.
This is due to the reason that "password" is not set when setting reference as you can see on this [line](https://github.com/Microsoft/mssql-jdbc/blob/47d6eb43df137d0997608dfb637e4d9180da58c8/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java#L1098). 

Password is not stored in encrypted format by the driver, and hence is not passed on to JNDI reference.

**Comment by maeichris** [comment]
Hi, @cheenamalhotra, thanks for looking into this.

You mention that the password is not stored in an encrypted format by the driver and not passed on to JNDI for security reasons.  I don't have a good understanding of the security concerns in this regard.

Does that mean that putting a DataSource into JNDI is a bad practice?  (My impression is that is how it's done generally in a J2EE application server, and my test was an attempt to mimic that in straight code.)  Or does it mean that I should store the password somewhere else and reset the password on the DataSource every time I pull a DataSource out of JNDI?  I'm not sure what the best practice is for something like this.

Thanks,
Chris

**Comment by cheenamalhotra** [comment]
Hi @maeichris 

I investigated more about this issue and looks like other JDBC Drivers do send password information when registering driver into JNDI. We will need to seek security clearance for this support and will hopefully support this change in near future.

I will follow up for this change and will let you know when I have any update.

**Comment by maeichris** [comment]
There was never a response about getting the security clearance that @cheenamalhotra mentioned a little over a year ago.

The line of code that removes the password was in the initial commit of the code on Nov 9, 2016.

https://github.com/microsoft/mssql-jdbc/commit/cfba660ac950a14da127cb9399430425473fb46f#diff-18d0d0627e5a0b7a9abe73358d2358a8

I am still running with version 2.0 of the driver because of this issue (the last one where this worked).  I am a bit surprised that no one else has come across the problem, unless there is some other way of getting around it that I am not aware of (very possible).

**Comment by ulvii** [comment]
Hi @maeichris ,
Sorry for the delay, we will look into this and get back to you.

**Comment by peterbae** [comment]
Hi @maeichris,

Sorry for the delay. As was discussed in the above comments, the driver is intentionally removing the password as a property in this case for security concerns. The idea is that if the same client with knowledge of the password for the original DataSource that was created, the client should be able to provide the password again after retrieving the reference for that DataSource. I don't think putting DataSource into JNDI is a bad practice, but as you suggested, you should store the password somewhere else and provide the password again after you pull it out of JNDI, at least for our driver.

Please let me know if this solves your problem, and sorry for not getting back to you earlier on this.

**Comment by maeichris** [comment]
Hi, @peterbae,

Thanks for taking up this matter, and for the explanation.  Based on that, I did some digging/debugging to figure out how it actually works in the container (Tomcat 8.5).

In the container, the application knows nothing of the database connection, including whether it is using integrated or SQL Server logins.  The container sets up the DataSource.  The application gets the DataSource and then gets a connection without the application having to specify a password.  The container has managed it all.

Previously I was creating the DataSource like this:

		SQLServerXADataSource ds = new SQLServerXADataSource();
		ds.setURL(url);

		if (StringUtils.isNotBlank(userName))
		{
			// not integrated security
			ds.setUser(userName);
			ds.setPassword(password);
		}

It appears Tomcat 8.5 bypasses SQLServerXADataSource/SQLServerDataSource altogether, and uses org.apache.tomcat.dbcp.dbcp2.BasicDataSource, which contains an org.apache.tomcat.dbcp.dbcp2.PoolingDataSource.  These in turn talk to the driver specifically, which is specified in the context's Resource configured with type="javax.sql.DataSource" and driverClassName="com.microsoft.sqlserver.jdbc.SQLServerDriver".

Therefore, I tried creating a BasicDataSource like this and it seems to work:

		BasicDataSource ds = new BasicDataSource();
		ds.setDriverClassName(com.microsoft.sqlserver.jdbc.SQLServerDriver.class.getName());
		ds.setUrl(url);

		if (StringUtils.isNotBlank(userName))
		{
			// not integrated security
			ds.setUsername(userName);
			ds.setPassword(password);
		}

This means that the unit tests (okay, actually _integration_ tests) would need to add a dependency on dbcp.

While I am not sure why a DataSource would want to remove the password, a workaround is to use a kind of DataSource that does not remove it.  I am guessing the reason why the SQLServerXADataSource/SQLServerDataSource remove the password is for cases where a single DataSource is used to support multiple logins.  But an app within a container probably uses a single account, thus the reason Tomcat uses DataSource which sets the password once for each connection that is created on the application's behalf.

Since Tomcat has a system that assures the password is set for each new connection, the behavior is probably expected.  As such, that makes me think this ticket is not valid (and the workaround I wrote above may help future people with the same problem).  If you agree, please go ahead and close out this ticket.

**Comment by peterbae** [comment]
Thank you for the investigation @maeichris, I agree with your findings. I'll close the ticket.
