### ISSUE TITLE
getParameterMetadata fails with statement creating views

### ISSUE THREAD

**Issue by mohitj13** [Microsoft/mssql-jdbc#911]
## Driver version
mssql-jdbc-7.0.0.jre8

## SQL Server version
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Express Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 15063: ) 

## JAVA/JVM version
1.8.0_191

## Table schema
Table: UserTbl
| user_id | username |
|             |                  |

## Problem description
Though this is just a sample scenario when creating view with "mssql-jdbc driver" database fails to get  the ParameterMetaData and throw exception.
SQL Statement: 

> create view vw_user_tbl as Select u.user_id, u.username from UserTbl u;

1. Expected behaviour:
Should Create view without throwing any exception. 
2. Actual behaviour:
Exception message:
`The metadata could not be determined because statement 'create view vw_user_tbl as Select u.user_id, u.username from UserTbl u' does not support metadata discovery.`
3. Error message/stack trace:

```
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:254)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1608)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:578)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:508)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7240)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2869)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:243)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:218)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQueryInternal(SQLServerPreparedStatement.java:448)
	at com.microsoft.sqlserver.jdbc.SQLServerParameterMetaData.<init>(SQLServerParameterMetaData.java:602)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.getParameterMetaData(SQLServerPreparedStatement.java:3057)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.getParameterMetaData(SQLServerPreparedStatement.java:3068)
	at org.apache.commons.dbutils.AbstractQueryRunner.fillStatement(AbstractQueryRunner.java:341)
	at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:527)
	at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:417)
```

4. Any other details that can be helpful:
Using Apache DBUtils -> QueryRunner to execute the statement.
When simply execute the same statement with 'pmdKnowBroken' to true, It executes the statement as it do not fetch ParameterMetaData. 

## JDBC trace logs
```
FINE: SQLServerCallableStatement:477 created by (ConnectionID:1 ClientConnectionId: 249236b7-aa4d-4c12-9b3b-698e9fb36503)
Dec. 17, 2018 3:48:13 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement buildExecSQLParams
FINE: SQLServerCallableStatement:477: calling sp_executesql: SQL:exec sp_describe_undeclared_parameters @P0        
Dec. 17, 2018 3:48:13 PM com.microsoft.sqlserver.jdbc.SQLServerResultSet <init>
FINE: SQLServerResultSet:239 created by (SQLServerCallableStatement:477)
Dec. 17, 2018 3:48:13 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement buildExecSQLParams
FINE: SQLServerPreparedStatement:476: calling sp_executesql: SQL:create table tbl_sequences ( sequence_name varchar(255), sequence_next_hi_value int, primary key (sequence_name) )
Dec. 17, 2018 3:48:13 PM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
FINE: SQLServerPreparedStatement:478 created by (ConnectionID:1 ClientConnectionId: 249236b7-aa4d-4c12-9b3b-698e9fb36503)
Dec. 17, 2018 3:48:40 PM com.microsoft.sqlserver.jdbc.SQLServerParameterMetaData <init>
FINE:  SQLServerParameterMetaData:237 created by (SQLServerPreparedStatement:478)
Dec. 17, 2018 3:48:45 PM com.microsoft.sqlserver.jdbc.SQLServerStatement <init>
FINE: SQLServerCallableStatement:479 created by (ConnectionID:1 ClientConnectionId: 249236b7-aa4d-4c12-9b3b-698e9fb36503)
Dec. 17, 2018 3:51:54 PM com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement buildExecSQLParams
FINE: SQLServerCallableStatement:479: calling sp_executesql: SQL:exec sp_describe_undeclared_parameters @P0        
Dec. 17, 2018 3:51:54 PM com.microsoft.sqlserver.jdbc.SQLServerException logException
FINE: *** SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: The metadata could not be determined because statement 'create view vw_user_print_logs as select u.user_id, u.user_name, u.full_name as user_full_name' does not support metadata discovery. Msg 11527, Level 16, State 1, The metadata could not be determined because statement 'create view vw_user_print_logs as select u.user_id, u.user_name, u.full_name as user_full_name' does not support metadata discovery.
```

## Reproduction code
Underlying problem is when it tries to execute the procedure to get the MetaData
`exec sp_describe_undeclared_parameters N' create view vw_user_tbl as Select u.user_id, u.username from UserTbl u';`
Throws the same error as provided from the driver itself.

**Comment by lilgreenbird** [comment]
hi @mohitj13 

I tried executing the same statement you provided with the driver the view does get created with no error.

I'm not sure what your framework does to trigger a call to `sp_describe_undeclared_parameters` but as the error message says, that statement does not support metadata discovery so the error is as expected. You can see the same error in SSMS as well. 

Please let us know if you have more questions,

**Comment by lilgreenbird** [comment]
hi @mohitj13 

The jTDS driver always use `SET FMTONLY` to get metadata since `sp_describe_undeclared_parameters` was not available at the time. This was introduced for SQL Servers starting 2012 and up was meant to replace `SET FMTONLY`. Unfortunately we have since discovered there are many limitations with this stored procedure so we will be working on providing an option for users to switch to use `SET FMTONLY` when fetching ParameterMetaData in a future release. With this, queries like this which does not return metadata will execute without returning anything but not throw any errors. We will start work on this soon, but until then, I'm afraid this is the behavior to be expected for now.

We have an open issue [](https://github.com/Microsoft/mssql-jdbc/issues/493) that is also related that I am linking here so it can be tracked.

**Comment by peterbae** [comment]
Issue is being tracked in #927, closing this issue.
