### ISSUE TITLE
[BUG] CallableStatement.execute() does not raise SQLException

### ISSUE THREAD

**Issue by SteBoe82** [Microsoft/mssql-jdbc#937]
## Driver version
6.4.0.jre8

## SQL Server version
14.0.1000

## Client Operating System
Windows 10

## JAVA/JVM version
1.8.0 u181

## Problem description
1. Expected behaviour:
CallableStatement.execute() raises an SQLException in case the Stored Procedure raises an error
2. Actual behaviour:
CallableStatement.execute() does not raise the SQLException, SQLException is only raised in case the THROW statement is the first statement in the Store Procedure
3. Error message/stack trace:
4. Any other details that can be helpful:

## Reproduction code
[TestStoredProcredure.txt](https://github.com/Microsoft/mssql-jdbc/files/2772346/TestStoredProcredure.txt)
[SQLExceptionTest.txt](https://github.com/Microsoft/mssql-jdbc/files/2772342/SQLExceptionTest.txt)

**Comment by rene-ye** [comment]
Hi @SteBoe82, please iterate through the ResultSet (via `resultset.next()`) returned by the server in order to access any exceptions. The driver can only send user requests to the server, it doesn't actually execute or parse any user SQL. In order for the driver to know an exception occured, it must be allowed to look through the responses, hence the necessity to iterate through the ResultSets returned.

**Comment by SteBoe82** [comment]
The described solution works only partially. 

Most of our statements do not return a result set (`stmt.execute()` returns `false`). How can I handle SQLExeptions in that case?

**Comment by rene-ye** [comment]
Hi @SteBoe82, can you give an example of this? For example, the follow code throws a `Divide by zero encountered` error even if no Resultset is returned. Foo is a table with a single varchar column.
```java
final String query = "INSERT INTO FOO VALUES (CONVERT(varchar(10),(1/0)))";
try (Connection con = DriverManager.getConnection(cString); CallableStatement stmt = con.prepareCall(query)) {
    stmt.execute();
} catch (SQLException se) {
    se.printStackTrace();
}
```

**Comment by SteBoe82** [comment]
I found a solution to handle possible exceptions.
