### ISSUE TITLE
[BUG]  [Microsoft JDBC Driver] connect SQL Server very slow

### ISSUE THREAD

**Issue by phamtuan993** [Microsoft/mssql-jdbc#938]
## Driver version

mssql-jdbc-7.1.4.jre8-preview.jar
## SQL Server version

Microsoft SQL Server 2012 - 11.0.2100.60 (X64) 
	Feb 10 2012 19:39:15 
	Copyright (c) Microsoft Corporation
	Express Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: )

## Client Operating System

OS Name:                         Microsoft Windows 10 Pro
System Type:                     x64-based PC
Total Physical Memory:     8,00 GB
CPU:                                  Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz 2.90 GHz
## JAVA/JVM version

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
## Problem description

1. Expected behaviour:
Reduce time create connection SQL Server ->  ~ time connect SQL Server C#
2. Actual behaviour:
3. Error message/stack trace:
4. Any other details that can be helpful:
I create a program java create connection SQL Server ( only create connection, not execute any query) 
Java:
/**
   * get connection use Microsoft JDBC Driver
   */
private void sqlDriverConnect() {
                try {
                    long time = System.currentTimeMillis();
                    SQLServerDataSource dataSource = new SQLServerDataSource();
                    dataSource.setServerName("192.168.1.98");
                    dataSource.setDatabaseName("testdatabase");
                    dataSource.setUser("tuanpv");
                    dataSource.setPassword("123");
                    dataSource.setApplicationName("tuanpv");
                    connection = dataSource.getConnection();
                    connection.close();
                    time = System.currentTimeMillis() - time;
                    System.out.println("Time: " + time);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

//===================================
            /**
             * get connection use jtds-1.3.1-dist
             */
            private void jtdsDriverConnect() {
                try {
                  long time = System.currentTimeMillis();
                    String url = "jdbc:jtds:sqlserver://192.168.1.98:1433;DatabaseName=testdatabase;";
                    connection = DriverManager.getConnection(url, "tuanpv", "123");
                    connection.close();
                   time = System.currentTimeMillis() - time;
                   System.out.println("Time: " + time);
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }

//=========================== 
Code C# open connect SQL Server 
public static SqlConnection GetDbConnection(string dataSource, string database)
        {
            string connectionString = $"Data Source={dataSource};Initial Catalog={database};User ID=tuanpv;Password=123";
            SqlConnection connection = new SqlConnection(connectionString);
            return connection;
        }
        static void Main(string[] args)
        {
             Stopwatch stopwatch = new Stopwatch();
            stopwatch.Start();
            var sqlConnection = GetDbConnection("192.168.1.98", "testdatabase");
            sqlConnection.Open();
            var sqlCommand = sqlConnection.CreateCommand();
            sqlConnection.Close();
            sqlConnection.Dispose();
            stopwatch.Stop();
            Console.WriteLine("Time : "+stopwatch.ElapsedMilliseconds);
        }

//===================================================
Create a program open multiple process:
public void main() {
        List<Process> listProcess = new ArrayList<>();

       List<String> cmds = Arrays.asList(commandline run program (C#, Jar file));   
        for (int i = 0; i < 20; i++) {
            ProcessBuilder processBuilder = new ProcessBuilder(cmds);
            try {
                Process process =Runtime.getRuntime().exec(cmds.toArray(new String[0]));
                listProcess.add(process);

            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        for (Process process : listProcess) {
            try {
                process.waitFor();
                BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(process.getInputStream(), StandardCharsets.UTF_8));
                String str = bufferedReader.readLine();
                System.out.println(str);
                bufferedReader.close();
                process.destroy();
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

=======================================================
Result Test:

***** Run only one PROCESSS *****
-Java using Microsoft JDBC Driver (mssql-jdbc-7.1.4.jre8-preview.jar)
Time: 900ms ~ 1500ms

-Java using jtds-1.3.1-dist
Time: 380ms ~ 500ms

-C# (Net Framework 4.6.1)
Time: 80ms ~ 150 ms

***** Run 20 PROCESSS  *****
-Java using Microsoft JDBC Driver (mssql-jdbc-7.1.4.jre8-preview.jar)
Time: 7900ms ~ 11000ms

-Java using jtds-1.3.1-dist
Time: 900ms ~ 4000ms

-C# (Net Framework 4.6.1)
Time: 180ms ~ 1700 ms

Why [Microsoft JDBC Driver] connect SQL Server very slow ?

**Comment by peterbae** [comment]
Hi @phamtuan993, thanks for reporting this. I just tested with the same versions you tried for our Microsoft JDBC driver (7.1.4.jre8-preview) and the jtds (1.3.1-dist) driver, and I saw that our driver was connecting faster than JTDS. I've attached the screenshot of my simple testing below.

![image](https://user-images.githubusercontent.com/30157681/51503913-c344af80-1d92-11e9-8d1e-1065d7ac2ec2.png)

Do you think the disparity between our results could be coming from the connectivity to your database? I've shown "localhost" as my test database for the screenshot, but I've tested against other non-local SQL Servers as well and my outcome was consistent with what I've attached.

Please let me know if I've missed anything.

**Comment by phamtuan993** [comment]
Hi @peterbae , thank you for reply.
Here my code test:
`    public static void main(String[] args) throws Exception {
        int countThreadExecute = 10;
        ExecutorService executorService = Executors.newFixedThreadPool(countThreadExecute);
        long time = System.currentTimeMillis();
        for (int i = 0; i < countThreadExecute; i++) {
            // create thread run Main::testCreateConnection
            executorService.execute(Main::testCreateConnection);
        }
        // wait all threads end
        executorService.shutdown();
        executorService.awaitTermination(1, TimeUnit.HOURS);
  // after all threads end
        time = System.currentTimeMillis() - time;
        System.out.println("Total time: "+ time);
    }

    public static void testCreateConnection(){
        String microsoftConnectionString = "jdbc:sqlserver://localhost:1433;databaseName=testdatabase";
        String jtdsConnectionString = "jdbc:jtds:sqlserver://localhost:1433;DatabaseName=testdatabase;";
       long time = System.currentTimeMillis();
        for (int i = 0; i < 1; i++) {
            try {
                Connection connection = DriverManager.getConnection(microsoftConnectionString, "tuanpv", "123");
                connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        time = System.currentTimeMillis() - time;
        System.out.println(Thread.currentThread().getName() + " connection create succeed: " + time);
    }`
When I test create 1 connection
Microsoft JDBC Driver:
![capture](https://user-images.githubusercontent.com/20065944/51543985-74ca0a80-1e91-11e9-891d-010235b1f51c.PNG)
jtds JDBC driver
![capture](https://user-images.githubusercontent.com/20065944/51544087-aba02080-1e91-11e9-8de0-0e903e8e3a8b.PNG)
**From second connection -> Microsoft JDBC driver very good**
![image](https://user-images.githubusercontent.com/20065944/51545139-ec009e00-1e93-11e9-86ce-85d0559c9407.png)

Thank you.
