### ISSUE TITLE
[QUESTION] Slow batch processing into Azure SQL

### ISSUE THREAD

**Issue by robinic** [Microsoft/mssql-jdbc#945]
Hi,

We are currently converting an application from on-prem SQL 2012 into Azure SQL, and have come across an issue where the batch inserts for 270,000 rows in 2000 row batches take around 2 minutes on-prem, take up to 15 minutes in Azure. We are not receiving any exceptions or indications from the execution, and the data is loaded correctly, it just takes time

## Background Info
**Environment: Working**
Application Host: Windows 10, JRE1.70, mssql-jdbc-6.4.0.jre7.jar
Server: SQL 2012 SP2,  Server 2012

**Environment: New**
Application Host: Server 2016, JRE1.70, mssql-jdbc-6.4.0.jre7.jar
Server: Azure SQL (2 vCore, also tried with 4 and 8 vCore configs)

The connection string being used is 
`jdbc:sqlserver://<sqlHostname>:1433;databaseName=<dbName>;user=<sqlUser>;password=<password>`

We have checked resource logs on our Azure setup and confirmed that it is not due to any resource limitations on either the host VM, Azure SQL, or networking between them. The actual inserts in SQL perform as expected and take approximately the same time on both systems.

## Logs
We have run logs for both on-prem and Azure versions, and have identified that there seem to be additional entries in the logs for equivalent batches. Our devs have identified that " com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream readInternal" in this logs is when the process is slowing on Azure. 

Local Instance:
```
Jan 25, 2019 4:26:56:917 PM com.microsoft.sqlserver.jdbc.TDSCommand onRequestComplete
FINEST: TDSCommand@700498b0 (SQLServerPreparedStatement:15 executeBatch): request complete
Jan 25, 2019 4:26:56:917 PM com.microsoft.sqlserver.jdbc.TDSCommand startResponse
FINEST: TDSCommand@700498b0 (SQLServerPreparedStatement:15 executeBatch): Reading response...
Jan 25, 2019 4:26:57:182 PM com.microsoft.sqlserver.jdbc.TDSChannel logPacket
```

Azure Instance:
```
Jan 25, 2019 4:28:58:220 PM com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream writeInternal
FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream@43e1c1ac Writing 37 bytes
Jan 25, 2019 4:28:58:221 PM com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream flush
FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream@43e1c1ac Flushing
Jan 25, 2019 4:28:58:221 PM com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream writeInternal
FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream@43e1c1ac Writing 2245 bytes
Jan 25, 2019 4:28:58:221 PM com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream flush
FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyOutputStream@43e1c1ac Flushing
Jan 25, 2019 4:28:58:221 PM com.microsoft.sqlserver.jdbc.TDSCommand onRequestComplete
FINEST: TDSCommand@7118b81f (SQLServerPreparedStatement:15 executeBatch): request complete
Jan 25, 2019 4:28:58:221 PM com.microsoft.sqlserver.jdbc.TDSCommand startResponse
FINEST: TDSCommand@7118b81f (SQLServerPreparedStatement:15 executeBatch): Reading response...
Jan 25, 2019 4:28:58:221 PM com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream readInternal
FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@1a722605 Reading 5 bytes
Jan 25, 2019 4:28:58:229 PM com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream readInternal
FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@1a722605 Read 5 bytes
Jan 25, 2019 4:28:58:229 PM com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream readInternal
FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@1a722605 Reading 64 bytes
Jan 25, 2019 4:28:58:229 PM com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream readInternal
FINEST: com.microsoft.sqlserver.jdbc.TDSChannel$ProxyInputStream@1a722605 Read 64 bytes
Jan 25, 2019 4:28:58:229 PM com.microsoft.sqlserver.jdbc.TDSChannel logPacket
```

Unfortunately, we are limited to JRE 1.70, so cannot use the 7.0 release of the driver.

We are now at a loss as to where to look next in terms of possible solutions, as we couldn't find any references to a similar issues or the $ProxyInputStream, and were hoping for some suggestions or input from someone that has come across this issue, or who is more familiar with the driver

This is my first time posting to Github, so if there is any additional info required, please let me know.

Thanks,

Robin

**Comment by peterbae** [comment]
Hi @robinic, thanks for asking this question. The slow insertion time you're experiencing with Azure is unfortunately a bottleneck on Azure SQL Database's end. The driver isn't performing anything special against Azure - the data is sent in a similar fashion to both SQL Server and Azure SQL Database, but each transaction between the driver and Azure just costs more time.

That being said, to address this issue, we've added a connection property "useBulkCopyForBatchInsert" that uses bulk copy API to allow the users to insert data faster. However, I don't think this applies to your case currently since this is supported from mssql-jdbc driver version 6.5.4 and above (which requires java 8 or 10), and also this is only available against Azure Data Warehouse.

If your application is able to use bulk copy to insert data instead of batch insert against Azure SQL Server, it will greatly speed up your insertion process, since bulk copy requires significantly less number of transactions compared to the traditional batch inserts. However, as for the slower insertion speed for batch insert against Azure, it is expected.

Please let me know if you have any other questions.

**Comment by robinic** [comment]
Hi, apologies for my lack of response. I caught up with our dev that was looking after this and we were able to resolve the issue we were having, reducing the process time from approx 15 minutes to about 2 minutes. The below is the actions our team took to resolve:

> We disabled the auto-commit mode which is a default when creating a connection in JDBC and handled our own transactions manually. So instead of committing each individual record, we commit at the very end.
