### ISSUE TITLE
[QUESTION] Field set to length 8000 causes blocking chain

### ISSUE THREAD

**Issue by ilbonte** [Microsoft/mssql-jdbc#946]
We are using JDBC v6.4.0 and MS SQL Server 2014 and our DBAs warned us about a blocking chain starting from this simple update query 
```sql
(@P0 varchar(8000),@P1 varchar(8000),@P2 varchar(8000))
update table_to_update set field_one = @P0, field_two = @P1 
where field_three = @P2        
```
They think that the issue may be the field length setted to 8000.

**1st question: may the field's length be the reason of the lock?** 

Looking at the code and following the debugger we got to [this line of code](https://github.com/Microsoft/mssql-jdbc/blob/v6.4.0/src/main/java/com/microsoft/sqlserver/jdbc/Parameter.java#L735) where the field's length is "forced" to 8K 
Looks like that the only way cusomize the field's length is to use the [Always Encrypyed Feature](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-database-engine?view=sql-server-2016#feature-details) but is not available in MS SQL Server 2014 (and unfortunately we can't upgrade soon)
**2nd question: Is there another way to set field's length?**
_____
Some more information about how we execute a statement:
Stripped down to the essentials 
```java
PreparedStatement statement=connection.prepareStatement(sql);
statement.setObject(position, parameter);
statement.execute();
```

**Comment by rene-ye** [comment]
Hi @ilbonte, the information provided isn't complete to the point where I can give you a definite answer regarding this exact use case, but I'll try to bring some clarity using the information given.

>may the field's length be the reason of the lock?

This shouldn't be the case, [this article](http://www.sqlservercentral.com/articles/Blocking/101926/) gives a nice explanation regarding common use cases that may result in a blocking chain. There can be a few ways of fixing this, from simply just enabling auto commit to handling updates from multiple connections more gracefully.

>Is there another way to set field's length?

This shouldn't be necessary for the use case explained in the issue. If I create a table with the following query (with SSMS):

```sql
CREATE TABLE issue946 (c1 varchar(20), c2 varchar(8000), c3 varchar(max));
INSERT INTO issue946 VALUES ('20 precision', '8000 precision', 'max precision');
INSERT INTO issue946 VALUES ('row 1', 'row 2', 'row 3');
INSERT INTO issue946 VALUES ('UPDATE 200', 'UPDATE 8000', 'SELECT ME');
```
I will end up with something like this: 
![image](https://user-images.githubusercontent.com/6042742/51865634-bb898b80-22fb-11e9-9cfe-60a4e2f247f9.png)
Attempting to insert values above the precision limit with the driver...
```java
try (Connection c = ds.getConnection(); PreparedStatement s = c.prepareStatement("UPDATE issue946 SET c1 = ?, c2 = ? WHERE c3 = ?")) {
	s.setString(1,"20 PRECISION 20 PRECISION 20 PRECISION 20 PRECISION 20 PRECISION 20 PRECISION 20 PRECISION");
	s.setString(2,"8000 precision");
	s.setString(3,"SELECT ME");
	s.execute();
}
```
will result in a SQLServerException: `Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated`. The same is true when using `setObject()`.

However, inserting less than the max precision is perfectly fine:
```java
try (Connection c = ds.getConnection(); PreparedStatement s = c.prepareStatement("UPDATE issue946 SET c1 = ?, c2 = ? WHERE c3 = ?")) {
	s.setString(1,"less than 20");
	s.setString(2,"8000 precision");
	s.setString(3,"SELECT ME");
	s.execute();
}
```
![image](https://user-images.githubusercontent.com/6042742/51866686-761a8d80-22fe-11e9-9737-7ed02a6bea4a.png)
The same is true for exact precision:
```java
try (Connection c = ds.getConnection(); PreparedStatement s = c.prepareStatement("UPDATE issue946 SET c1 = ?, c2 = ? WHERE c3 = ?")) {
	s.setObject(1,"ThisStringIsExactly2");
	s.setObject(2,"8000 precision");
	s.setObject(3,"SELECT ME");
	s.execute();
}
```
![image](https://user-images.githubusercontent.com/6042742/51866792-b843cf00-22fe-11e9-8367-857332fd3af4.png)
Both of the above holds true for `setString()` as well as `setObject()`, and it's not necessary for the user to specify precision. In regards to the question itself, no it's not possible to set the precision when using `PreparedStatement`.

Instead, users can use `CallableStatement`:
```java
try (Connection c = ds.getConnection(); CallableStatement s = c.prepareCall("UPDATE issue946 SET c1 = ?, c2 = ? WHERE c3 = ?")) {
	s.setObject(1, "send exactly 15", java.sql.Types.VARCHAR, 15);
	s.setObject(2, "8000 precision");
	s.setObject(3, "SELECT ME");
	s.execute();
}
```
![image](https://user-images.githubusercontent.com/6042742/51867789-386b3400-2301-11e9-8e6a-85e2a30593d5.png)

If further assistance is required, please post additional information such as table structure, reproduction code, and other applicable fields outlined in the template.

**Comment by ilbonte** [comment]
Thanks! We will look in this further!

**Comment by cheenamalhotra** [comment]
Hi @ilbonte 

Do you have any other queries, or we can go for closing this issue?

**Comment by ilbonte** [comment]
We didn't experience the issue again and so we didn't investigate further. 
Thanks for the support!
