### ISSUE TITLE
[BUG] JDBC 7.2.0.jre8 problem with prepared statement

### ISSUE THREAD

**Issue by KarelHaruda** [Microsoft/mssql-jdbc#952]
## Driver version
7.2.0.jre8
<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>mssql-jdbc</artifactId>
    <version>7.2.0.jre8</version>
</dependency>

## SQL Server version
Microsoft SQL Server 2017 (RTM-CU13) (KB4466404) - 14.0.3048.4 (X64) 
	Nov 30 2018 12:57:58 
	Copyright (C) 2017 Microsoft Corporation
	Express Edition (64-bit) on Linux (Ubuntu 18.04.1 LTS)

## Client Operating System
Windows 10 PRO

## JAVA/JVM version
Oracle JAVA 1.8.0_191

## Problem description
There is different behavior between versions 7.2.0.jre8 and 7.0.0.jre8
I have query which should determinate structure of table. Query contains just ONE parameter in WHERE section (WHERE Upper(sys.tables.name) = ?). Setting the parameter value on JDBC 7.0.0.jre8 works fine (stmt.setString(1, "TABLE1");) but same step on driver 7.2.0.jre8 throws exception

com.microsoft.sqlserver.jdbc.SQLServerException: The index 1 is out of range.	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:228)  at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setterGetParam(SQLServerPreparedStatement.java:1124) at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setValue(SQLServerPreparedStatement.java:1138)	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.setString(SQLServerPreparedStatement.java:1683)

## Reproduction code
package eu.kaha.test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import org.junit.Test;

public class MSSQLTest {
	private final String SQL = "SELECT sys.all_columns.Name,\n" + 
			"CASE sys.types.Name\n" + 
			"WHEN 'int' THEN 'INTEGER'\n" + 
			"WHEN 'smallint' THEN 'INTEGER'\n" + 
			"WHEN 'bigint' THEN 'INTEGER'\n" + 
			"WHEN 'numeric' THEN 'NUMERIC'\n" + 
			"WHEN 'float' THEN\n" + 
			"CASE sys.all_columns.max_length\n" + 
			"WHEN 4 THEN 'FLOAT'\n" + 
			"ELSE 'DOUBLE'\n" + 
			"END\n" + 
			"WHEN 'char' THEN 'CHAR'\n" + 
			"WHEN 'varchar' THEN\n" + 
			"CASE sys.all_columns.max_length\n" + 
			"WHEN -1 THEN 'CLOB'\n" + 
			"ELSE 'VARCHAR'\n" + 
			"END\n" + 
			"WHEN 'varbinary' THEN 'BLOB'\n" + 
			"ELSE 'UNKNOWN'\n" + 
			"END,\n" + 
			"CASE sys.all_columns.precision\n" + 
			"WHEN 0  THEN sys.all_columns.max_length\n" + 
			"ELSE sys.all_columns.precision\n" + 
			"END,\n" + 
			"sys.all_columns.scale,\n" + 
			"CASE sys.all_columns.is_nullable\n" + 
			"WHEN 1 THEN 'Y'\n" + 
			"ELSE 'N'\n" + 
			"END,\n" + 
			"CASE sys.default_constraints.definition\n" + 
			"WHEN NULL THEN ''\n" + 
			"ELSE\n" + 
			"CASE SubString(sys.default_constraints.definition, 2, 1)\n" + 
			"WHEN '(' THEN SubString(sys.default_constraints.definition, 3, Len(sys.default_constraints.definition)-4)\n" + 
			"ELSE SubString(sys.default_constraints.definition, 2, Len(sys.default_constraints.definition)-2)\n" + 
			"END\n" + 
			"END\n" + 
			"FROM sys.Tables\n" + 
			"JOIN sys.all_columns ON sys.tables.object_id = sys.all_columns.object_id\n" + 
			"JOIN sys.types ON sys.all_columns.system_type_id = sys.types.system_type_id\n" + 
			"LEFT JOIN sys.default_constraints ON sys.default_constraints.parent_object_id = sys.all_columns.object_id AND sys.default_constraints.parent_column_id = sys.all_columns.column_id\n" + 
			"WHERE Upper(sys.tables.name) = ? \n" + 
			"ORDER BY sys.all_columns.column_id";
	
	@Test
	public void testSerialization() {
		try {
			Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
			String userName = "SA";
			String password = "---pass----";
			String url = "jdbc:sqlserver://192.168.56.99;databaseName=DATABASE";
			Connection conn = DriverManager.getConnection(url, userName, password);
			PreparedStatement stmt  = conn.prepareStatement(SQL);
			stmt.setString(1, "TABLE1");
			stmt.executeQuery();
			ResultSet rs = stmt.getResultSet();
			rs.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}

**Comment by KarelHaruda** [comment]
Same situation is on JAVA 11 version
7.1.2.jre11-preview    works fine 
7.2.0.jre11     throws  com.microsoft.sqlserver.jdbc.SQLServerException: The index 1 is out of range.

**Comment by struberg** [comment]
FTR: Same seems to happen when testing 7.2.0 with Apache OpenJPA.
Our query in the test is `SELECT (?+SUBSTRING(t0.name, CHARINDEX(?, t0.name), LEN(t0.name) - (CHARINDEX(?, t0.name) - 1))) FROM CompUser t0 WHERE (t0.name = ?)`
And mssql-jdbc-7.2.0 claims it only sees 2 parameters.

**Comment by cheenamalhotra** [comment]
@struberg 

I believe testing with latest dev branch built jars would be ideal to get past the issue. We have recognized and fixed regression caused with 7.2.0 release, in PR #950.

**Comment by martinm1000** [comment]
```sql
"WHERE RES_DATE >= ? AND RES_DATE <= ? "
```
I also got this problem (only have 2 parameters), tested with the current dev branch and my query works again on 7.2.1-jre11.

**Comment by darkedges** [comment]
Works for me (with limited testing i.e Application now starts up) for JRE8.

**Comment by alternate11** [comment]
When will 7.2.1 be released?

**Comment by cheenamalhotra** [comment]
Hi Everyone!

**7.2.1** Hotfix Release is completed for JDBC Driver, the artifacts will be available on [Maven Central](http://central.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/) and [Microsoft Download Center](https://www.microsoft.com/en-us/download/details.aspx?id=57782) shortly. The new hotfix driver version fixes reported issue with parameterized Prepared Statements.

You may now upgrade your applications to [**7.2.1 Hotfix & Stable Release**](https://github.com/Microsoft/mssql-jdbc/releases/tag/v7.2.1) version.

Thanks for your support!
