### ISSUE TITLE
switch project to standard Maven SNAPSHOT versions

### ISSUE THREAD

**Issue by struberg** [Microsoft/mssql-jdbc#953]
## Question
Is there really any reason why you use a fixed version (right now 7.2.1.jre8) in your pom.xml?
This is _not_ how maven works! You will break quite a few versioning mechanics that way.

I suggest to rather use a SNAPSHOT version instead. The correct version would be `7.2.1.jre8-SNAPSHOT` during development. And only during the release you should switch to a fixed version.

**Comment by cheenamalhotra** [comment]
Hi @struberg

Yes we are in process to perform HotFix Release 7.2.1 soon in a few days, and the source code is sealed for anymore pushes until release, hence there is no Snapshot version for this one.

We will switch back to Snapshot version post release for our next preview release version. Thanks for your observation!

**Comment by struberg** [comment]
oki cool, thanks for pushing this!
Btw, you might try the maven-release-plugin pushChanges=false and localCheckout=true settings.
Example for it can be found here https://github.com/apache/deltaspike/blob/master/pom.xml#L123
Happy to discuss and improve missing parts in Maven.
