### ISSUE TITLE
[Bug] SQLServerResultSetMetaData.getColumnName() doesn't return the actual column name from database, if an sql as clause is specified

### ISSUE THREAD

**Issue by abzycdxw65** [Microsoft/mssql-jdbc#975]
## Driver version
7.2.1

## SQL Server version
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 17134: ) (Hypervisor) 

## Client Operating System
Windows 10 Enterprise

## JAVA/JVM version
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

## Problem description
SQLServerResultSetMetaData.getColumnName() doesn't return the actual column name from database, if an sql as clause is specified

According to jdbc documenation getColumnName() should return the designated column name, 
whereas getColumnLabel() should return the alias, if an alias is specified and the getColumnName() result otherwise.

But varying from other jdbc drivers, getColumnName() and getColumnLabel() both return the alias, if an alias is specified.
Both methods have the same implementation in SQLServerResultSetMetaData.
But getColumnName() should return "rs.getColumn( column ).getBaseColumnName();" instead.
According to com.microsoft.sqlserver.jdbc.Column, the base column name is the actual column name in an underlying table.

Other jdbc drivers i tested (h2-1.3.176.jar and mariadb-java-client-2.3.0.jar) were working as expected.

1. Expected behaviour:
SQLServerResultSetMetaData.getColumnName() returns the actual column name from database if an sql as clause is specified for a column

2. Actual behaviour:
SQLServerResultSetMetaData.getColumnName() returns the alias if an sql as clause is specified for a column

## JDBC trace logs
none

**Comment by peterbae** [comment]
Hi @abzycdxw65, thanks for contacting us. When the driver issues a select query with SQL AS keyword, SQL Server only sends the alias of the column without the actual name underneath, and the ResultSet doesn't contain any information about the underlying column name. This is why SQLServerResultSetMetaData.getColumnLabel and SQLServerResultSetMetaData.getColumnName return the same results.

The example drivers you have mentioned are drivers for a different data source (h2 and mariadb) - and I imagine that they send data differently from SQL Server. I've done some testing with jTDS driver (which also works with SQL Server), and verified that jTDS driver also behaves the same as our driver.

Please let me know if you have any other questions/concerns.

**Comment by peterbae** [comment]
Closing issue due to no action required. Please feel free to re-open if you have any other questions.
