### ISSUE TITLE
Support cursor out parameters

### ISSUE THREAD

**Issue by marschall** [Microsoft/mssql-jdbc#98]
It is my understanding that stored procedure with a cursor can not be called from JDBC. An example would be this

```java
CREATE PROCEDURE simpleCursor
    @OutputCursor CURSOR VARYING OUTPUT
AS
BEGIN
    SET @OutputCursor = CURSOR
    FORWARD_ONLY STATIC FOR
    SELECT 'hello' UNION ALL SELECT 'world';

    OPEN @OutputCursor;
    return;
END;
```

which you should be able to call using this code

```java
try (CallableStatement call = connection.prepareCall("{ call simpleCursor(?)}")) {
    call.registerOutParameter(1, Types.REF_CURSOR);
    call.execute();
    try (ResultSet resultSet = call.getObject(1, ResultSet.class)) {
        while (resultSet.next()) {
            System.out.println(resultSet.getObject(1, String.class));
        }
    }
}
```

This does not work because ref cursor support is not implemented in the driver. Instead the procedure has to be rewritten into this

```sql
CREATE PROCEDURE simpleCursor
AS
BEGIN
    SELECT 'hello' UNION ALL SELECT 'world'
END;
```

and the Java code has to be changed to

```java
try (CallableStatement call = connection.prepareCall("{ call simpleCursor()}")) {
    call.execute();
    try (ResultSet resultSet = call.getResultSet) {
        while (resultSet.next()) {
            System.out.println(resultSet.getString(1));
        }
    }
}
```

**Comment by TobiasSQL** [comment]
@marschall , the use of cursor output parameters is limited to within SQL Server. These [cannot be used from database APIs](https://technet.microsoft.com/en-us/library/ms175498(v=sql.105).aspx).

**Comment by marschall** [comment]
@TobiasSQL so, should we close this then or is there a chance this may change in future versions of SQL Sever?

**Comment by TobiasSQL** [comment]
@marschall, yes unless this is an extremely critical case I would suggest closing it. This is not something we have currently planned for future versions of SQL Server.

**Comment by marschall** [comment]
Closing as per discussion above. Can not be implemented.
