### ISSUE TITLE
[BUG] SQLServerConnection javadoc contradiction

### ISSUE THREAD

**Issue by ecki** [Microsoft/mssql-jdbc#980]
While reading the SQLServerConnection class Javadoc I noticed it states that it is and isn’t thread safe. Most likely one of both needs to be removed.

https://github.com/Microsoft/mssql-jdbc/blob/bb72f76374479740c1084c7a321c522609de3961/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L76
https://github.com/Microsoft/mssql-jdbc/blob/bb72f76374479740c1084c7a321c522609de3961/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L82

**Comment by cheenamalhotra** [comment]
@ecki

Thanks for pointing out, we'll consider updating it in the next Preview Release.

**Comment by peterbae** [comment]
This issue has been addressed in PR #984. Closing issue.
