### ISSUE TITLE
[BUG] SQLServerConnection#connectInternal extracts SELECT_METHOD twice

### ISSUE THREAD

**Issue by ecki** [Microsoft/mssql-jdbc#981]
There are two times where the SELECT_METHOD property is extracted, only one checks for values and assigns it to the field. The locations can probably be consolidated

https://github.com/Microsoft/mssql-jdbc/blob/bb72f76374479740c1084c7a321c522609de3961/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L1758
https://github.com/Microsoft/mssql-jdbc/blob/bb72f76374479740c1084c7a321c522609de3961/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java#L1482

Suggestion (which also reduces number of case changes and compares):

    sPropValue = sPropValue.toLowerCase(Locale.ENGLISH);
    selectMethod = null;
    if ("cursor".equals(sPropValue) || "direct".equals(sPropValue)) {        
                activeConnectionProperties.setProperty(sPropKey, sPropValue);
                selectMethod = sPropValue;
     } else {

And remove the second occurrence. I can make a PR if you agree.

**Comment by cheenamalhotra** [comment]
@ecki 

Please feel free to create PR for the same. 👍

**Comment by peterbae** [comment]
This issue has been addressed in PR #987. Closing issue.

**Comment by ecki** [comment]
Looks good, thanks.
